### ISSUE TITLE
Current commit has introduced errors that weren't present 24hrs prior

### ISSUE THREAD

**Issue by shaneholloman** [Mikubill/sd-webui-controlnet#101]
```sh
Error calling: E:\ai\sd\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
Traceback (most recent call last):
  File "E:\ai\sd\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "E:\ai\sd\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 239, in ui
    module.change(build_sliders, inputs=[module], outputs=[processor_res, threshold_a, threshold_b])
  File "E:\ai\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py", line 81, in change
    dep = self.set_event_trigger(
  File "E:\ai\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 226, in set_event_trigger
    "outputs": [block._id for block in outputs],
  File "E:\ai\sd\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 226, in <listcomp>
    "outputs": [block._id for block in outputs],
AttributeError: 'tuple' object has no attribute '_id'
```

**Comment by Mikubill** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/45ccea66b6390cf761bbde1131463a240e1887c7

**Comment by shaneholloman** [comment]
Cool 

FYI: I rolled back 2 commits and was back up and running
![image](https://user-images.githubusercontent.com/1563909/219403458-3b106262-0ccd-4ad4-bb68-cf2db0e1a857.png)

Yup, https://github.com/Mikubill/sd-webui-controlnet/commit/45ccea66b6390cf761bbde1131463a240e1887c7 fixed it

BTW, your app is sick!
