### ISSUE TITLE
[New Model] The finished tile model will be released in 48 hours

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1033]
hello everyone, we will release the finished tile model in 48 hours. The name will be 

'control_v11f1e_sd15_tile' (The old "control_v11u_sd15_tile" will be removed)

You will have 3 ways to use it:

1. it can do 2x, 4x, or 8x super resolution
2. it can add, or change, or re-generate image details in an image
3. it can fix, refine, and improve bad image details obtained by any other super resolution methods like bad details or blurring from RealESRGAN
4. it can guide SD to diffuse in tiles, "one beautiful girl" will not generate 16 girls if you use 16 tiles and denoising strength 1.0.
5. **it can finish unfinished artwork drafts if those drafts are drawn by color blocks**

The performance of this model will be between production-ready and experimental. Final quality flag is [e].

**Comment by lllyasviel** [comment]
right now, control net has strong capability to control images when you have existing or extracted edges, depth, or pose.

However, in some unfinished artworks, the edge is not clear, depth is not clear, and pose is hard to recognize.

In those cases, the only available thing is artist’s color blocks, and the tile model will be the last missing piece to fill in this path – it can control Stable Diffusion with coarse color blocks.

Recently, we suddenly received many feedbacks requesting a way to directly use coarse color blocks to control image composition even when all depth, edge, poses are not available. It seems that the feedbacks are mainly from China and related to social media Weibo. We are not sure what happens but will provide that model soon.

**Comment by 2blackbar** [comment]
That sounds great, are there any examples of its outputs somewhere ?

**Comment by lllyasviel** [comment]
If you have any problem, make sure that you are using "control_v11f1e_sd15_tile", not the old "control_v11u_sd15_tile".

Pay attention to the name "v11f1e"

**Comment by lllyasviel** [comment]
Beside official ways to use it, for a1111 users, we provide a special functionality: the tile model can be combined with "my prompt is more important" to do arbitary prompt-based transfer

![image](https://user-images.githubusercontent.com/19834515/234436025-d89b830a-9649-4398-9fb0-2c34630f2440.png)
![image](https://user-images.githubusercontent.com/19834515/234436045-b9c1ca59-e019-4ddc-9d09-b0de7d0c938f.png)
![image](https://user-images.githubusercontent.com/19834515/234436052-8870414f-d6c6-42fb-9de9-822ec480cb94.png)

**Comment by lllyasviel** [comment]
some other up scaling tests should be trivial. just try your self

**Comment by lllyasviel** [comment]
![image](https://user-images.githubusercontent.com/19834515/234443167-40470c1b-acf7-4caf-852d-f444610aa022.png)
![image](https://user-images.githubusercontent.com/19834515/234443147-30b20077-308f-4d09-8f9a-108568a05324.png)
![image](https://user-images.githubusercontent.com/19834515/234443188-f86a3243-a5da-484d-a0ae-aeb374ba98ec.png)
![image](https://user-images.githubusercontent.com/19834515/234443203-e5087ef5-0bd4-4a80-966e-6e75f2123979.png)

when the detail replacement is large (using "my prompt is more important"), it can interprete the contents and replace with promts while maintaining the overall structure. This method does not rely on image depth or edges

**Comment by 54681** [comment]
![I%@%J0 0K5U~`A2_IWCLH81](https://user-images.githubusercontent.com/125456320/234446918-2b63e17f-d458-4b4a-a5ee-4916606ec8f5.png)
![K PDP9W47VOW FYLX8UP8SX](https://user-images.githubusercontent.com/125456320/234446925-d818dd2d-9fd4-42fa-acc2-57e95c380b1b.png)
![5_ AA{0W)$MD0O(RK7U61XF](https://user-images.githubusercontent.com/125456320/234446930-4362bc15-0c34-4a59-a4d7-8f80cde5db2f.png)
Simple poses that only require one image are awesome. It also supports lora well

**Comment by lllyasviel** [comment]
OK perhaps I need to give an upscale example so that it can be really called "tile" and prove that it is not off topic.

Below is protogen without using any external upscaler (except the native a1111 Lanczos, which is not a super resolution method, just for resampling)

This is from 192x256 to 1536x2048

![image](https://user-images.githubusercontent.com/19834515/234445938-ae8e5606-e9bc-4d5e-867d-d0c25f10b06e.png)

meta:

beautiful woman in sweater, high-quality, extremely detailed
Negative prompt: long body, low resolution, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality
Steps: 40, Sampler: Euler a, CFG scale: 7, Seed: 1, Size: 512x680, Model hash: 44f90a0972, Model: protogenX34Photorealism_1, Denoising strength: 0.35, Clip skip: 2, ControlNet-0 Enabled: True, ControlNet-0 Module: tile_resample, ControlNet-0 Model: control_v11f1e_sd15_tile [a371b31b], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1, Hires upscale: 3, Hires steps: 40, Hires upscaler: Lanczos

Note that image content may be changed because I used prompts to specify "in sweater"

screen (note that I am using the more challenging t2i, which is weaker than i2i in upscaling):

![image](https://user-images.githubusercontent.com/19834515/234449367-e0a2a326-e28a-4c41-99a2-45d48bd3ea38.png)
![image](https://user-images.githubusercontent.com/19834515/234449388-481e9566-506c-4ef5-9853-278a259e4a2a.png)


non cherry picked, random seed "1":

![image](https://user-images.githubusercontent.com/19834515/234449413-39f56271-edec-4aa9-875b-09aea25898dd.png)

non cherry picked, random seed "2":

![image](https://user-images.githubusercontent.com/19834515/234449769-24fd3b1c-04c6-4e46-a742-a23fb9882ac8.png)

Note that I am using the **worst** method to do upscaling to test **the worst performance**. I am not using any XXX upscaler. This is just a basic t2i diffusion. Users may find much better ways. This is just the "nake" results without the help of special things. I am not even using esrgan

**Comment by torealise** [comment]
Hi. I have a problem. 

Seems like controlNet tile doesn't work for me.

It doesn't affect an image at all.

Image generated same with and without control net 

I am using this versions:

ControlNet v1.1.111

Model
control_v11f1e_sd15_tile [a371b31b]

Preprocessor:
- none
- tile_resample


python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.23.0  •  commit: [22bcc7be]


What can be wrong?

Thanks

![cn](https://user-images.githubusercontent.com/127824727/234456602-e219eac4-46ff-4902-a19b-f15d7e4d3d90.jpg)

**Comment by foggyflute** [comment]
@torealise I dont know if it's your intention to us no preprocessor or not, but does it work with tile_resample preprocessor?

**Comment by lllyasviel** [comment]
my bad. i forget to rename yaml. now fixed. update and restart completely

**Comment by torealise** [comment]
> my bad. i forget to rename yaml. now fixed. update and restart completely

Thank you. Could I please ask about the chance of contacting you and having a talk? We have been using your ControlNet in our research, and it would be fascinating to have you as our adviser. If it is possible, would you be available for a conversation?

**Comment by lllyasviel** [comment]
now all 1.1 models and usage codes are finished. We will not release more things unless there is bug fix. The next update will be ControlNet 1.2. But this may depend on what Stability is going to release.

**Comment by torealise** [comment]
I downloaded control_v11f1e_sd15_tile.pth, and updated control_v11f1e_sd15_tile.yaml, then even restarted pc, but still control net tile doesn't make any difference to generated image.

![Screenshot_1](https://user-images.githubusercontent.com/127824727/234465235-738ae338-cabb-4bb8-b55b-bc5e79376982.jpg)

Maybe I use it wrong way?

- I go to txt2img
- type prompt
- setup resolution 512x768
- enable controlnet 1.1.111
- select none or tile_resampler a preprocessor
- select control_v11f1e_sd15_tile as a model
- press generate

but result is the same with control net turned on and off

**Comment by lllyasviel** [comment]
share logs please

**Comment by torealise** [comment]
Loaded state_dict from [C:\stable-diffusion-portable-main\extensions\sd-webui-controlnet\models\control_v11f1e_sd15_tile.pth]
Loading config: C:\stable-diffusion-portable-main\extensions\sd-webui-controlnet\models\control_v11f1e_sd15_tile.yaml
Error running process: C:\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\stable-diffusion-portable-main\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 959, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "C:\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 645, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "C:\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\controlnet.py", line 713, in build_control_model
    network = network_module(
  File "C:\stable-diffusion-portable-main\extensions\sd-webui-controlnet\scripts\cldm.py", line 63, in __init__
    self.config = OmegaConf.load(config_path)
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\omegaconf\omegaconf.py", line 188, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\stable-diffusion-portable-main\venv\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\stable-diffusion-portable-main\extensions\sd-webui-controlnet\models\control_v11f1e_sd15_tile.yaml", line 28, column 66

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 27.43it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 20.60it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 28.55it/s]

**Comment by lllyasviel** [comment]
See readme:

Do not right click the filenames in HuggingFace website to download. Some users right clicked those HuggingFace HTML websites and saved those HTML pages as PTH/YAML files. They are not downloading correct PTH/YAML files. Instead, please click the small download arrow “↓” icon in HuggingFace to download.

**Comment by torealise** [comment]
> See readme:
> 
> Do not right click the filenames in HuggingFace website to download. Some users right clicked those HuggingFace HTML websites and saved those HTML pages as PTH/YAML files. They are not downloading correct PTH/YAML files. Instead, please click the small download arrow “↓” icon in HuggingFace to download.

Thanks, it is working now. And it is working amazing. Use it as an upscaler. Works so well that cannot even be compared to other methods of upscaling.

Many thanks!

**Comment by 2blackbar** [comment]
works good but when you use it in img2img dont put in any prompts

**Comment by Rkkss** [comment]
I thought you were supposed to use it with tile based upscale script like sd upscaler, ultimate upscaler. Guess I was wrong

**Comment by lllyasviel** [comment]
Anime upscale test
Input (512)
![image](https://user-images.githubusercontent.com/19834515/234525311-42de8468-cb2d-4253-9e68-8d78e911bbc3.png)

1girl, high-quality, extremely detailed
Negative prompt: long body, low resolution, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 12345, Size: 1024x1280, Model hash: abcaf14e5a, Model: anything-v3-full, Denoising strength: 0.5, Clip skip: 2, ControlNet-0 Enabled: True, ControlNet-0 Module: tile_resample, ControlNet-0 Model: control_v11f1e_sd15_tile [a371b31b], ControlNet-0 Weight: 0.75, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1

![image](https://user-images.githubusercontent.com/19834515/234525481-a3f30bef-6141-4d3d-b733-999fddabd901.png)

not sure why some anime model cause a bit "Halo feeling"

This is Counterfeit

1girl, high-quality, extremely detailed
Negative prompt: long body, low resolution, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 12345, Size: 1024x1280, Model hash: a074b8864e, Model: Counterfeit-V2.5_pruned, Denoising strength: 0.5, Clip skip: 2, ControlNet-0 Enabled: True, ControlNet-0 Module: tile_resample, ControlNet-0 Model: control_v11f1e_sd15_tile [a371b31b], ControlNet-0 Weight: 0.75, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1

![image](https://user-images.githubusercontent.com/19834515/234526189-9edcc484-f716-4d60-a9b6-d0236a1da2ef.png)

**Comment by 2blackbar** [comment]
If you do img2img then the only prompt that improve the image is negative one , if you put in something in actual prompt then it cant do its thing as good as without it from what i see.
Its just first test so all that could be unimportant once a solid workflow will be figured out
( blurry,worst ,jpeg artifacts,compression:1.2)

![image](https://user-images.githubusercontent.com/33694664/234526686-223f4963-2f5e-4526-bfb0-f546ee311a7c.png)

**Comment by lllyasviel** [comment]
I seem to get the best parameters:

cfg scale 30 (!), 0.5 denosing strength, 50 steps
![image](https://user-images.githubusercontent.com/19834515/234527684-4863b3b5-9d52-4a90-8510-15b5eb0abe14.png)

**Comment by 2blackbar** [comment]
I can tell it works, and can really recognize whats in the image, it detected rabbit and cat, heres original image, with controlned tile and without it where it failed  (didnt recognize cat or rabbit) denoiuse is 0.7
![image](https://user-images.githubusercontent.com/33694664/234533646-265ad430-a89e-4c53-8d92-fad94c3618ae.png)
![00223-3029174923](https://user-images.githubusercontent.com/33694664/234533706-97c4352d-8f48-4135-b431-96bd3f6642bc.png)
![image](https://user-images.githubusercontent.com/33694664/234533738-2d70ecac-b5df-4b6e-9e44-5fc0a20cb4d4.png)

**Comment by lllyasviel** [comment]
the model's behavior is not very typical upscaling. it seems to recognize things and reconstruct at higher resolution. It is a completely new independent pass, rather than make images larger.

the benefit is that it has chance to make big difference and add many things to the image - the image will not "look like a upscaled image" and it feels like generated at that resolution (perhaps this is how we can get some "feeling of midjourney" - not sure about this)

the drawback is that it is not a very typical upscaling (but perhaps use lower denoising strength, but when denoising strength is low, this cn might not be necessary) and it will change your images

this time I tried the previous image in i2i

a beautiful woman, best quality
Negative prompt: blur, blur, blur, long body, low resolution, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality
Steps: 50, Sampler: DPM++ 2S a Karras, CFG scale: 30, Seed: 12345, Size: 1024x1280, Model hash: 44f90a0972, Model: protogenX34Photorealism_1, Denoising strength: 0.5, Clip skip: 2, ControlNet-0 Enabled: True, ControlNet-0 Module: tile_resample, ControlNet-0 Model: control_v11f1e_sd15_tile [a371b31b], ControlNet-0 Weight: 0.75, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1

Note that the cfg is 30(!)

![image](https://user-images.githubusercontent.com/19834515/234535160-558e466c-8269-4fe7-b4fe-c7b4c0c10686.png)
![image](https://user-images.githubusercontent.com/19834515/234535211-9d7413ee-be9a-474f-86e3-7d60ec10ea92.png)
![image](https://user-images.githubusercontent.com/19834515/234535259-cdb56c49-1174-4587-a947-4514a0a35ec1.png)

The hair does not look like "upscaled" hair. they look like hair generated at that resolution

Seems that sometimes the hair is recognized as cloth hole - well just another method to make images bigger

**Comment by lllyasviel** [comment]
perhaps this is the real contribution of this model.

nowadays people has 10000 ways to get images sharper and larger,

but this seems the first way to get effects likes just "re-generate things at larger scale without getting a feeling of upscaled"

but this is very hard to understand so perhaps this tile model will become more used by advanced/specific users - the behavior seems not very common in a wider aspect

**Comment by lllyasviel** [comment]
if midjourney is using similar mechanism, then this model has potential to fill that missing piece between sd and midjourney. but not sure

**Comment by lllyasviel** [comment]
basically confirmed that this model need cfg>15. not sure why. very misterious

**Comment by Lancer907** [comment]
Thank you for your work! I test it with the extension "ultimate SD upscale" in img2img, and it works.

controlnet off:
![00001-1591407306](https://user-images.githubusercontent.com/55968860/234541304-700d0605-ba21-46bb-87b7-8e9228e085c8.png)

controlnet on: 
![00002-1001118223](https://user-images.githubusercontent.com/55968860/234541455-449d1bbf-74a6-4ff7-b00a-0eafa7021621.png)

**Comment by lllyasviel** [comment]
basically it seems cfg 15 is robust enough, still not sure why. We do not add any special things to training
![image](https://user-images.githubusercontent.com/19834515/234542388-9e8f53c7-ae89-4a3a-b984-dad7012b0178.png)
1girl, dancing, river, dress, (((masterpiece))), best quality
Negative prompt: blur, blur, blur, long body, low resolution, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality
Steps: 50, Sampler: DPM++ 2S a Karras, CFG scale: 15, Seed: 12348, Size: 1024x1280, Model hash: abcaf14e5a, Model: anything-v3-full, Denoising strength: 0.5, Clip skip: 2, ControlNet-0 Enabled: True, ControlNet-0 Module: tile_resample, ControlNet-0 Model: control_v11f1e_sd15_tile [a371b31b], ControlNet-0 Weight: 0.75, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1
![image](https://user-images.githubusercontent.com/19834515/234542373-473ae2ec-46fc-4be7-a480-8d31130e7dad.png)

**Comment by 2blackbar** [comment]
I am getting better results with low CFG actually , this is cfg 3 vs cfg 5, with high cfg im getting this smeary low microdetail look that i dont really like much, with low CFG im getting actual microdetail added 
I think each model needs some separate docs written about it , the workflow with them is really scientific, and if you dont know what to do you will get crap results.
![00104-1685924968](https://user-images.githubusercontent.com/33694664/234546955-09d63fa4-8471-43a1-9383-3390601a2e3d.png)

![image](https://user-images.githubusercontent.com/33694664/234546924-c0c566b4-43ee-4405-94fd-d1d864a0a0e3.png)

**Comment by lllyasviel** [comment]
the second one feels like nijijourney. perhaps mj system is using cascaded diffusion and the tile model makes SD cascaded

**Comment by demirklvc** [comment]
can you show an example of upscaling only certain parts of an image?

**Comment by 2blackbar** [comment]
the best form of upscale is manual inpainting of head, torso, legs, shoes , hands etc, this is not really meant for upscaling , above like 800x800 resolution it stops to see , and the result is not that much better from 800x800 vs 1400x1400

**Comment by Jonseed** [comment]
I love this! It is like a contextual upscaler, using the context of each part of the image to add details at higher resolutions! I'm going to test this thoroughly. Thank you!

**Comment by Rkkss** [comment]
https://imgsli.com/MTczODk3/0/1

Ran a bunch of testing tile model on ultimate SD upscale script. 
This is the parameter I used to upscale:
`(masterpiece:1.2), (best_quality:1.2), highres, ultra detailed 8k wallpaper, extremely clear, realism, highly detailed, sharp focus, subsurface scattering, writing, paper, book, library, seductive smile 
Negative prompt: (easynegative:1.0), ng_deepnegative_v1_75t, (low_quality:1.4), (worst_quality:1.4), (normal quality:1.4), (blurry:1.4), lowres, jpeg artifacts, greyscale, monochrome, painting, sketch 
Steps: 35, Sampler: DPM++ 2S a Karras, CFG scale: 15, Seed: 192962981, Model hash: 4199bcdd14, Model: revAnimated_v122, VAE: vae-ft-mse-840000-ema-pruned, Denoising strength: 0.58, Clip skip: 2, ENSD: 31337, Ultimate SD upscale upscaler: ESRGAN_4x, Ultimate SD upscale tile_width: 1024, Ultimate SD upscale tile_height: 1024, Ultimate SD upscale mask_blur: 8, Ultimate SD upscale padding: 32, ControlNet-0 Enabled: True, ControlNet-0 Module: tile_resample, ControlNet-0 Model: control_v11f1e_sd15_tile [a371b31b], ControlNet-0 Weight: 0.75, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1`

Image was upscaled 2x from 869x1344. Started with tile size:1024x1024 because smaller tile size will lead to duplicated objects, maybe denoise is too high, guidance strength is not high enough?
Cfg 15 in most test. Increase to 20+ will give more details + overbake image. 
Quality tags in prompt have little effect but Negative on other hand, seems to do more. I put more weight on negative and the outcome is very notice able, Especially at high cfg. As you can see cfg 20+ weighted negative has sharp details & burns image even more.
The updated negative:
`(easynegative:1.0), ng_deepnegative_v1_75t, (low_quality:2.0), (worst_quality:2.0), (normal quality:2.0), (blurry:1.4), lowres, jpeg artifacts, (greyscale, monochrome, painting, sketch)`

Finally ran it again with a more "natural" tile size (512x768) that SD can gen well. Unsurprisingly, result was better, but it duplicate objects(in your prompt) often.

**Comment by katopz** [comment]
Do I need both `.pth` and `.yml` file?
At first I try only `.pth` file and it seem to work just fine so I'm not sure what `.yml` is for?

Thanks

**Comment by ssstylusss** [comment]
Any ideas why my output images looks always like i am using a f1/2 lens? the background is always blurred :(

![00010-3566173838](https://user-images.githubusercontent.com/113402819/235348250-ffdc1485-6ad3-4772-85bb-26bed231283b.png)

**Comment by davedfx** [comment]
![grannie-comp](https://user-images.githubusercontent.com/54312595/235352555-846982dc-eba2-4e6a-8dfa-076a5e9ee4fd.jpg)
![grannie-Comp_face](https://user-images.githubusercontent.com/54312595/235352557-8f90e59d-8d03-4909-b805-8643940973d0.jpg)
![grannie-Comp_torso](https://user-images.githubusercontent.com/54312595/235352562-ad0a5618-a1dd-40d0-9bfe-65e9786b496f.jpg)

![grannie-Comp_torso2](https://user-images.githubusercontent.com/54312595/235352567-4e9a887f-142f-4f65-8084-d4c7f602985b.jpg)


This is awesome! 
Img2Img Ultimate Sd upscale

**Comment by lllyasviel** [comment]
@davedfx impressive. this looks very seamless, yet i think ["tiled diffusion"](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) can make it even more seamless. perhaps can try run it in tiled vae again

**Comment by marcsyp** [comment]
Hi @davedfx -- that looks amazing!  Can you share some of your gen parameters, tips+tricks?  Thank you!

**Comment by davedfx** [comment]
![00102-1130658215 0-DPM++ SDE Karras-32-20230430222400-gigapixel-hq-scale-2_00x](https://user-images.githubusercontent.com/54312595/235366552-827cb9b8-3e0f-4772-a326-ea1653f92470.jpg)
![Copy (2) of 00102-1130658215 0-DPM++ SDE Karras-32-20230430222400-gigapixel-hq-scale-2_00x](https://user-images.githubusercontent.com/54312595/235366556-44e0c534-d7bf-428e-83c5-b56c1e753d14.jpg)
![Capture](https://user-images.githubusercontent.com/54312595/235366562-649453cf-62ce-4502-8536-24a24db9ba49.JPG)
![Capture2](https://user-images.githubusercontent.com/54312595/235366566-556c381e-194a-4af2-a432-77d002e119ac.JPG)

**Comment by davedfx** [comment]
> @davedfx impressive. this looks very seamless, yet i think ["tiled diffusion"](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) can make it even more seamless. perhaps can try run it in tiled vae again

I'll give that a try.

How does the Tile algorithm work? I'm testing txt2img with source image as tile preprocessor. Seems to influence the output very strong.

**Comment by marcsyp** [comment]
> https://imgsli.com/MTczODk3/0/1
> 
> Ran a bunch of testing tile model on ultimate SD upscale script. This is the parameter I used to upscale: `(masterpiece:1.2), (best_quality:1.2), highres, ultra detailed 8k wallpaper, extremely clear, realism, highly detailed, sharp focus, subsurface scattering, writing, paper, book, library, seductive smile Negative prompt: (easynegative:1.0), ng_deepnegative_v1_75t, (low_quality:1.4), (worst_quality:1.4), (normal quality:1.4), (blurry:1.4), lowres, jpeg artifacts, greyscale, monochrome, painting, sketch Steps: 35, Sampler: DPM++ 2S a Karras, CFG scale: 15, Seed: 192962981, Model hash: 4199bcdd14, Model: revAnimated_v122, VAE: vae-ft-mse-840000-ema-pruned, Denoising strength: 0.58, Clip skip: 2, ENSD: 31337, Ultimate SD upscale upscaler: ESRGAN_4x, Ultimate SD upscale tile_width: 1024, Ultimate SD upscale tile_height: 1024, Ultimate SD upscale mask_blur: 8, Ultimate SD upscale padding: 32, ControlNet-0 Enabled: True, ControlNet-0 Module: tile_resample, ControlNet-0 Model: control_v11f1e_sd15_tile [a371b31b], ControlNet-0 Weight: 0.75, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1`
> 
> Image was upscaled 2x from 869x1344. Started with tile size:1024x1024 because smaller tile size will lead to duplicated objects, maybe denoise is too high, guidance strength is not high enough? Cfg 15 in most test. Increase to 20+ will give more details + overbake image. Quality tags in prompt have little effect but Negative on other hand, seems to do more. I put more weight on negative and the outcome is very notice able, Especially at high cfg. As you can see cfg 20+ weighted negative has sharp details & burns image even more. The updated negative: `(easynegative:1.0), ng_deepnegative_v1_75t, (low_quality:2.0), (worst_quality:2.0), (normal quality:2.0), (blurry:1.4), lowres, jpeg artifacts, (greyscale, monochrome, painting, sketch)`
> 
> Finally ran it again with a more "natural" tile size (512x768) that SD can gen well. Unsurprisingly, result was better, but it duplicate objects(in your prompt) often.
> 
> Also this method works well with 86000-ema-pruned VAE, unsure why color shifted too much even at denoise 0.5

This is a great test, thank you for doing this -- Are you also using ControlNet is more important like dave?

**Comment by marcsyp** [comment]
@davedfx -- thank you that's fantastic.  One thing that improved my results was adjusting my "Just resize" mode, I had it on Just Resize (latent upscale).  I'm curious, what mode is supposed to be used with Ultimate SD Upscale?

One more question for you dave: the sample images you posted above, those are 4 passes of 2x?

Do you use the original image in the tile preprocessor or do you swap out the image with the result each time?

**Comment by marcsyp** [comment]
I have been getting great results with images using dave's settings above, and no prompts whatsoever.  Seems to best with understandable subjects, it struggles a bit with abstract art with realistic elements.  But WOW.  This is phenomenal.  I'll post some examples here soon.

**Comment by ssstylusss** [comment]
I am happy! Finally make it work using my previous workflow: 4xultrasharp. Seems you can go to 10X or even more. Cause it loads in memory by tiles, not the entire stuff: this case i went from 512x768 to 2048x3072. The denoise values was not as I desired, so changed more than I like:
![image](https://user-images.githubusercontent.com/113402819/235371766-d3262e7f-56f9-443e-96c8-f9a267850db3.png)

**Comment by alexfredo** [comment]
I don't understand how enable it, I have click on enable etc and nothing change when I generate a image I don''t get the upscale, I don't have error message please someone explain how use it ?

**Comment by ssstylusss** [comment]
> I don't understand how enable it, I have click on enable etc and nothing change when I generate a image I don't get the upscale, I don't have error message please someone explain how use it ?

You have to select a scale method on the script panel:
![image](https://user-images.githubusercontent.com/113402819/235372616-1f15caea-f61a-4c4a-9504-c307db4380fc.png)

**Comment by alexfredo** [comment]
Oh ok no I don't I was not aware that it's need another script, thanks !

**Comment by ssstylusss** [comment]
From 512kb to 2K. Using 4xUltrasharp
![2k](https://user-images.githubusercontent.com/113402819/235391499-3e08a647-5322-47a5-8d46-faf1784e38e9.png)

**Comment by davedfx** [comment]
> @davedfx -- thank you that's fantastic. One thing that improved my results was adjusting my "Just resize" mode, I had it on Just Resize (latent upscale). I'm curious, what mode is supposed to be used with Ultimate SD Upscale?
> 
> (Also, resizing my seed from 512x512 also helped)
> 
> One more question for you dave: the sample images you posted above, those are 2 passes of 2x?
> 
> Do you use the original image in the tile preprocessor or do you swap out the image with the result each time?

yes 2 passes of 2x

I manually swap out the img2img pic for each pass to get a progressive upscaling cuz Ultimate SD Upscaler have no loopback features

preprocessor image is the same starting image

**Comment by E7admin** [comment]
I seem to be running into a strange problem. I use "MultiDiffusion", "Tile VAE" and "ControlNet Tile Model" at the same time, or replace "MultiDiffusion" with "txt2img Hirex.Fix". The result is always some indescribable pictures. I'm pretty sure it's not something else because when I disabled ControlNet the problem went away. I tried completely deleting the ControlNet folder and reinstalling it, but it still didn't work.
![5111C94D06934BB4283545545E9EEB52](https://user-images.githubusercontent.com/128219466/235496887-1fbf3f14-6672-4af7-8dc0-b24b372244f4.jpg)
![07DE93246A7F7EE39E8715C5105DF223](https://user-images.githubusercontent.com/128219466/235496903-7936d143-4dc0-470b-8de8-89b0a4630f25.jpg)
![A1AF3281917BB6829EBB621A25B8E804](https://user-images.githubusercontent.com/128219466/235496923-99ee3059-e7ff-4a90-9169-a3ceb9f6912b.jpg)

**Comment by lllyasviel** [comment]
if you run into problems, please open bug issue with detailed info

**Comment by Rkkss** [comment]
> 
> This is a great test, thank you for doing this -- Are you also using ControlNet is more important like dave?

On that test no. However I did test with ControlNet is more important. Even at denoise strength 0.2 , it changes the face drastically unlike Dave's
https://imgsli.com/MTc1MjEz

 May give Dave's settings a try but I think the VAE did this to me. I have bad habit using 84000 mse vae for everything.

**Comment by Alphyn-gunner** [comment]
I found that it gives great results even without Ultimate SD Upscale. It looks like just setting a higher resolution in img2img gives better details and preserves the overall composition of the original picture really well (some color shift may occute at higher denoise settings, though). I immediately thought how awesome it would be if this model could be integrated into the HighresFix. Is this possible?
For the time being I'm just doing the highres fix manually by sending the generated images to img2img and upscaling them there. The results are very good, but this is a bit inconvenient.
