### ISSUE TITLE
Batch img2img error - AttributeError: 'numpy.ndarray' object has no attribute 'save'

### ISSUE THREAD

**Issue by Kaiten10** [Mikubill/sd-webui-controlnet#104]
When I run batch img2img with ControlNet enabled, I get this error:

```
Will process 1645 images, creating 1 new images for each.
Loading preprocessor: none, model: control_sd15_seg [fef5e48e]
Loaded state_dict from [E:\ProgramsE\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_seg.pth]
ControlNet model control_sd15_seg [fef5e48e] loaded.
        Tile 1/6
        Tile 2/6
        Tile 3/6
        Tile 4/6
        Tile 5/6
        Tile 6/6
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  4.72it/s]
Error completing request                                                          | 16/26320 [00:02<1:27:28,  5.01it/s]
Arguments: ('task(30ni9fvhnijhnpp)', 5, 'beautiful touhou character, beautiful face, epic wallpaper, masterpiece, best quality, cinematic scene, atmospheric environment, abstract art, artistic, vibrant, colorful, professional, official art, pixiv, wallpaper, extremely detailed, energetic, intricate details, strokes, strands, flowing, masterpiece, best quality', '', [], None, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, 'E:\\ProgramsE\\stable-diffusion-webui\\outputs\\img2img-images\\bad_apple\\in_shad_7.5fps', 'E:\\ProgramsE\\stable-diffusion-webui\\outputs\\img2img-images\\bad_apple\\out_768_9', '', [], 0, 0, 0, 0, 0, 0.25, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, 'x264', 'mci', 10, 0, False, True, True, True, 'intermediate', 'animation', True, 'none', 'control_sd15_seg [fef5e48e]', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, False, False, 'Denoised', 5.0, 0.0, 0.0, False, 'mp4', 'h264', 2.0, 0.0, 0.0, False, 0.0, True, True, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 512, 0.75, 0, 0.1, 0, 0.06, 1, False, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, True, True, True, False, 4.0, '', 10.0, 'Linear', 3, False, True, 30.0, True, False, False, 0, 0.0, 'Lanczos', 1, True, 10.0, True, 30.0, True, 0.0, 'Lanczos', 1, 'linear', 'lerp', 'token', 'random', '30', 'fixed', 1, '8', None, 'Lanczos', 2, 0, 0, 'mp4', 10.0, 0, '', True, False, False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2, '', '', False, '', 127, False, 30, 9999, 1, 10, 0.25, True, False, '1', '', True, '', '', '', '', '', '', '', '', '', '', '', 'None', 0.3, 60) {}
Traceback (most recent call last):
  File "E:\ProgramsE\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\ProgramsE\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\ProgramsE\stable-diffusion-webui\modules\img2img.py", line 166, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "E:\ProgramsE\stable-diffusion-webui\modules\img2img.py", line 79, in process_batch
    processed_image.save(os.path.join(output_dir, filename))
AttributeError: 'numpy.ndarray' object has no attribute 'save'
```

Here's my command line args: --xformers --opt-channelslast --gradio-img2img-tool color-sketch --api --disable-nan-check --no-half-vae

ControlNet works fine for individual images, and batch img2img has no issues when ControlNet is off.
I'm using the latest commit (6e96651).
Any ideas what could be the cause? Thx.

**Comment by Mikubill** [comment]
Enable `Do not append detectmap to output` in settings

**Comment by Kaiten10** [comment]
You're a lifesaver. It works great now! :)
