### ISSUE TITLE
[Bug]: zoe method missing dependency, wont work

### ISSUE THREAD

**Issue by 2blackbar** [Mikubill/sd-webui-controlnet#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Downloading: "https://huggingface.co/lllyasviel/Annotators/resolve/main/ZoeD_M12_N.pt" to F:\sd\extensions\sd-webui-controlnet\annotator\downloads\zoedepth\ZoeD_M12_N.pt

100%|██████████████████████████████████████████████████████████████████████████████| 1.34G/1.34G [00:12<00:00, 115MB/s]
img_size [384, 512]
Error running process: F:\sd\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\sd\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\sd\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1101, in process
    detected_map, is_image = preprocessor(input_image, res=preprocessor_resolution, thr_a=unit.threshold_a, thr_b=unit.threshold_b)
  File "F:\sd\extensions\sd-webui-controlnet\scripts\processor.py", line 426, in zoe_depth
    result = model_zoe_depth(img)
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 38, in __call__
    self.load_model()
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 27, in load_model
    model = ZoeDepth.build_from_config(conf)
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas.py", line 343, in build
    midas = torch.hub.load(midas_path, midas_model_type,
  File "F:\sd\venv\lib\site-packages\torch\hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "F:\sd\venv\lib\site-packages\torch\hub.py", line 569, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "F:\sd\venv\lib\site-packages\torch\hub.py", line 90, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\hubconf.py", line 5, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "F:\sd\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

### Steps to reproduce the problem

use zoe method after fresh install of controlnet and getting models 

### What should have happened?

should work like midas 

### Commit where the problem happens

current one from 26/04/2023

### Command Line Arguments

```Shell
xformers
```

### Console logs

```Shell
-
```

**Comment by 2blackbar** [comment]
I also ran pip install timm but its already satisfied

**Comment by ljleb** [comment]
Hard to say if this would break other extensions, and I do not think we want to try it in main. The reason it is already installed is that the webui explicitly requires version 0.4.12. It is possible that 0.6.13 is incompatible because of breaking changes. As the webui installs requirements on startup, people will be constantly downloading 2 different versions of this package on startup IIUC.

Vladmandic's repo has dependencies up to date, we should ask people to look into installing a more recent version of the webui instead probably. Not a satisfying solution but I am not confident we can do anything from within an extension code base.

**Comment by HeavenlyChorus** [comment]
im also getting this, did `pip install timm==0.6.13`

```
Preview Resolution = 512
img_size [384, 512]
Traceback (most recent call last):
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 474, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b, json_pose_callback=json_acceptor.accept)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 475, in zoe_depth
    result = model_zoe_depth(img)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/__init__.py", line 38, in __call__
    self.load_model()
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/__init__.py", line 27, in load_model
    model = ZoeDepth.build_from_config(conf)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/zoedepth/zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/zoedepth/zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas.py", line 343, in build
    midas = torch.hub.load(midas_path, midas_model_type,
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/hubconf.py", line 38, in DPT_BEiT_L_384
    model = DPTDepthModel(
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/dpt_depth.py", line 160, in __init__
    super().__init__(head, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/dpt_depth.py", line 71, in __init__
    self.pretrained, self.scratch = _make_encoder(
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/blocks.py", line 42, in _make_encoder
    pretrained = _make_pretrained_beitl16_384(
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/beit.py", line 175, in _make_pretrained_beitl16_384
    model = timm.create_model("beit_large_patch16_384", pretrained=pretrained)
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/timm/models/factory.py", line 81, in create_model
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/timm/models/beit.py", line 447, in beit_large_patch16_384
    model = _create_beit('beit_large_patch16_384', pretrained=pretrained, **model_kwargs)
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/timm/models/beit.py", line 398, in _create_beit
    model = build_model_with_cfg(
TypeError: build_model_with_cfg() missing 1 required positional argument: 'default_cfg'
```

**Comment by cooperdk** [comment]
You need timm==0.6.7, then it will work.
It is not acceptable that these dependencies are managed like crap from extensions AND from the webui.
