### ISSUE TITLE
[Bug]: controlnet no buton

### ISSUE THREAD

**Issue by sunghoonAm** [Mikubill/sd-webui-controlnet#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The controlnet bottom button does not appear.
never been able to solve
help

![controlnet no buton](https://user-images.githubusercontent.com/131747370/234540149-5409f72f-aec3-40b6-bd24-b19b83d2bc03.png)
![controlnet no buton](https://user-images.githubusercontent.com/131747370/234540273-4aca99d7-d9a9-4833-9887-5efce788ec22.png)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

There should be a button at the bottom of the controlnet

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
use of windows
```

### Console logs

```Shell
venv "C:\Users\anshh\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Installing opencv-python for ABG_extension
Installing Pillow for ABG_extension

Error running install.py for extension C:\Users\anshh\stable-diffusion-webui\extensions\dddetailer.
Command: "C:\Users\anshh\stable-diffusion-webui\venv\Scripts\python.exe" "C:\Users\anshh\stable-diffusion-webui\extensions\dddetailer\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "C:\Users\anshh\stable-diffusion-webui\extensions\dddetailer\install.py", line 105, in <module>
    raise RuntimeError(message)
RuntimeError:
[-] dddetailer: Please remove the following:
      1. the original ddetailer extension - "stable-diffusion-webui/extensions/ddetailer" folder.
      2. original model files - "stable-diffusion-webui/models/mmdet" folder.



Installing sd-dynamic-prompts requirements.txt




Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\anshh\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Error loading script: dddetailer.py
Traceback (most recent call last):
  File "C:\Users\anshh\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\anshh\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\anshh\stable-diffusion-webui\extensions\dddetailer\scripts\dddetailer.py", line 138, in <module>
    startup()
  File "C:\Users\anshh\stable-diffusion-webui\extensions\dddetailer\scripts\dddetailer.py", line 96, in startup
    raise RuntimeError(dedent(message))
RuntimeError:
[-] dddetailer: dddetailer doesn't work with the original ddetailer extension.
                dddetailer는 원본 ddetailer 확장이 있을 때 동작하지 않습니다.


ControlNet v1.1.112
ControlNet v1.1.112
Loading weights [e6415c4892] from C:\Users\anshh\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV20_v20.safetensors
Creating model from config: C:\Users\anshh\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\anshh\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(20): atompunkstylesd15, awaitingtongue, caradelevingne_ti, corneo_mercy, corneo_yor_forger, emb-rrf2, jenn1f1850, jg_n4t4lee, koh_daisyridley, koh_miakhalifa, nami, ng_deepnegative_v1_75t, pureerosface_v1, style-bridal, style-empire, style-hamunaptra, style-miaozu-20000, Style-TronLegacy-12v-v2, Style-Winter, thelab-ada
Model loaded in 2.4s (load weights from disk: 0.2s, create model: 0.2s, apply weights to model: 0.4s, apply half(): 0.4s, move model to device: 0.4s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.7s (import torch: 1.4s, import gradio: 0.9s, import ldm: 0.4s, other imports: 0.9s, load scripts: 1.7s, load SD checkpoint: 2.5s, create ui: 3.7s, gradio launch: 0.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.25it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.39it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.64it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:21<00:00,  1.64it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:44<00:00,  1.57it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.93it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:21<00:00,  1.65it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:26<00:00,  2.69it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.20it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:20<00:00,  1.71it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:25<00:00,  2.75it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.05it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:21<00:00,  1.63it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:26<00:00,  2.66it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.05it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:21<00:00,  1.65it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:26<00:00,  2.65it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.40it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:21<00:00,  1.61it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:30<00:00,  2.28it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.79it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:21<00:00,  1.66it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:26<00:00,  2.63it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00, 10.76it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:20<00:00,  1.71it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:24<00:00,  2.82it/s]
Loading model: control_sd15_openpose [fef5e48e]████████████████████████████████████████| 70/70 [00:24<00:00,  1.73it/s]
Loaded state_dict from [C:\Users\anshh\stable-diffusion-webui\models\ControlNet\control_sd15_openpose.pth]
Loading config: C:\Users\anshh\stable-diffusion-webui\extensions\sd-webui-controlnet\models\cldm_v15.yaml
ControlNet model control_sd15_openpose [fef5e48e] loaded.
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  7.43it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:29<00:00,  1.20it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:35<00:00,  1.99it/s]
Loading model from cache: control_sd15_openpose [fef5e48e]█████████████████████████████| 70/70 [00:35<00:00,  1.20it/s]
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:03<00:00,  9.95it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:30<00:00,  1.15it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:35<00:00,  1.98it/s]
Loading model from cache: control_sd15_openpose [fef5e48e]█████████████████████████████| 70/70 [00:35<00:00,  1.24it/s]
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:05<00:00,  6.73it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:30<00:00,  1.16it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:37<00:00,  1.89it/s]
Loading model from cache: control_sd15_openpose [fef5e48e]█████████████████████████████| 70/70 [00:37<00:00,  1.19it/s]
using mask as input
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 1024
raw_W = 1024
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  7.21it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:29<00:00,  1.18it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:35<00:00,  1.96it/s]
Loading model from cache: control_sd15_openpose [fef5e48e]█████████████████████████████| 70/70 [00:35<00:00,  1.19it/s]
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  7.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:29<00:00,  1.18it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:35<00:00,  1.95it/s]
Loading model from cache: control_sd15_openpose [fef5e48e]█████████████████████████████| 70/70 [00:35<00:00,  1.18it/s]
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:04<00:00,  7.01it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:31<00:00,  1.10it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:37<00:00,  1.85it/s]
Loading model from cache: control_sd15_openpose [fef5e48e]█████████████████████████████| 70/70 [00:37<00:00,  1.12s/it]
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:05<00:00,  6.46it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:29<00:00,  1.20it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:36<00:00,  1.91it/s]
Loading model from cache: control_sd15_openpose [fef5e48e]█████████████████████████████| 70/70 [00:36<00:00,  1.21it/s]
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:05<00:00,  6.85it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:29<00:00,  1.20it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:36<00:00,  1.92it/s]
Loading model from cache: control_sd15_openpose [fef5e48e]█████████████████████████████| 70/70 [00:36<00:00,  1.11it/s]
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:05<00:00,  6.97it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:28<00:00,  1.22it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 70/70 [00:35<00:00,  1.97it/s]
Loading weights [929adade89] from C:\Users\anshh\stable-diffusion-webui\models\Stable-diffusion\fantasticmixReal_v30.safetensors
Loading VAE weights specified in settings: C:\Users\anshh\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying cross attention optimization (Doggettx).
Weights loaded in 1.3s (load weights from disk: 0.4s, apply weights to model: 0.4s, move model to device: 0.4s).
Loading model: control_sd15_openpose [fef5e48e]
Loaded state_dict from [C:\Users\anshh\stable-diffusion-webui\models\ControlNet\control_sd15_openpose.pth]
Loading config: C:\Users\anshh\stable-diffusion-webui\extensions\sd-webui-controlnet\models\cldm_v15.yaml
ControlNet model control_sd15_openpose [fef5e48e] loaded.
Loading preprocessor: none
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
```

**Comment by lllyasviel** [comment]
they are removed and not needed now
