### ISSUE TITLE
[Bug]: Problem with new Tile model

### ISSUE THREAD

**Issue by demirklvc** [Mikubill/sd-webui-controlnet#1051]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

<img width="1440" alt="Bildschirmfoto 2023-04-26 um 13 27 00" src="https://user-images.githubusercontent.com/78754525/234561997-03c1ae51-b4bd-4611-8ffa-cd0377f20b90.png">
<img width="1440" alt="Bildschirmfoto 2023-04-26 um 13 27 52" src="https://user-images.githubusercontent.com/78754525/234562011-accfefa8-922b-4793-bb6e-14b0b688923c.png">

Error running process: C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\RTX01\stable-diffusion-webui\modules\scripts.py", line 347, in process
    script.process(p, *script_args)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 959, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 645, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 659, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
.

### What should have happened?

.

### Commit where the problem happens

webui: 
controlnet: 
.

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by demirklvc** [comment]
like seen the models are in the folders-but it says there is no model found. how to fix?

**Comment by demirklvc** [comment]
<img width="767" alt="Bildschirmfoto 2023-04-26 um 15 37 53" src="https://user-images.githubusercontent.com/78754525/234593238-819ad48c-12c1-49e9-829d-8cb6a76c2af4.png">
@lllyasviel

**Comment by demirklvc** [comment]
wrong. ive selected the models and it says no model.

**Comment by demirklvc** [comment]
im getting either error above or 

Loading model: control_v11f1e_sd15_tile [e3b0c442]
Error running process: C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\RTX01\stable-diffusion-webui\modules\scripts.py", line 347, in process
    script.process(p, *script_args)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 959, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 645, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 669, in build_control_model
    state_dict = load_state_dict(model_path)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 11, in load_state_dict
    state_dict = get_state_dict(torch.load(
  File "C:\Users\RTX01\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "C:\Users\RTX01\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Users\RTX01\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\RTX01\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by demirklvc** [comment]
any idea? @lllyasviel
