### ISSUE TITLE
ControlNET v1.1 A1111 APIs Problems

### ISSUE THREAD

**Issue by lucianoambrosini** [Mikubill/sd-webui-controlnet#1058]
Hello and thank you in advance for all your work.

Hopefully, this is the right thread, I encountered this kind of issue during an API test after switching to ControlNET v1.1.

Below is the error on the terminal:
```
Error running process: D:\Desktop\SDlocal\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\Desktop\SDlocal\stable-diffusion-webui\modules\api\api.py", line 62, in decode_base64_to_image
    image = Image.open(BytesIO(base64.b64decode(encoding)))
  File "D:\Desktop\SDlocal\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000018DC8E66AC0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\SDlocal\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Desktop\SDlocal\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 789, in process
    image = image_dict_from_unit(unit)
  File "D:\Desktop\SDlocal\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 125, in image_dict_from_unit
    result['mask'] = external_code.to_base64_nparray(result['mask'])
  File "D:\Desktop\SDlocal\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 92, in to_base64_nparray
    return np.array(api.decode_base64_to_image(encoding)).astype('uint8')
  File "D:\Desktop\SDlocal\stable-diffusion-webui\modules\api\api.py", line 65, in decode_base64_to_image
    raise HTTPException(status_code=500, detail="Invalid encoded image")
fastapi.exceptions.HTTPException
```

Has anyone, had a similar problem?
With the same settings, no errors occurred with ControlNET v1.0.

Thank you for any tips!

**Comment by cic-gmk** [comment]
shit! you solved my problem finally.
and if someone met the  problem that controlnet api do not work, check the webui version and update it.

**Comment by lucianoambrosini** [comment]
> Yes. make sure that mask is set to none.

Thanks I will try 👍🏼

**Comment by Michaelvirga** [comment]
Do any of you guys have an example payload? I can not find an updated example payload for controlNET 1.1 anywhere. @lllyasviel @lucianoambrosini @cic-gmk @alitan
