### ISSUE TITLE
Any idea what is causing this to fail?

### ISSUE THREAD

**Issue by Luucid** [Mikubill/sd-webui-controlnet#107]
Error verifying pickled file from F:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_scribble.pth:
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\MyName\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "F:\stable-diffusion-webui\modules\safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Error running process: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 337, in process
    network = PlugableControlModel(
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 61, in __init__
    state_dict = load_state_dict(model_path)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 27, in load_state_dict
    state_dict = get_state_dict(torch.load(
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 35, in get_state_dict
    return d.get('state_dict', d)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Mikubill** [comment]
Checkpoint/model file is corrupted, consider redownload those files.

**Comment by Luucid** [comment]
Oh okey. Do you mean the control_sd15_*.pth files, or the v1-5-pruned.ckpt ?

**Comment by Mikubill** [comment]
try control_sd15_scribble.pth

**Comment by Luucid** [comment]
Thanks, it worked when i downloaded the files manualy. I first just used git clone. Cheers :)
