### ISSUE TITLE
Gradio 3.28.1 removes `decode_base64_to_file`

### ISSUE THREAD

**Issue by AI-Robot-Morris** [Mikubill/sd-webui-controlnet#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After installed controlnet 1.1.2 then full restarted (closed ternimal)
./webui.sh

**Error shown below**

### Steps to reproduce the problem

 installed controlnet 1.1.2 then restarted.

### What should have happened?

During start ./webui.sh

### Commit where the problem happens

controlnet: 1.1.2

### Command Line Arguments

```Shell
COMMANDLINE_ARGS="--xformers --listen --enable-insecure-extension-access
```

### Console logs

```Shell
Error loading script: api.py
Traceback (most recent call last):
  File "/home/wrt/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/wrt/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wrt/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 13, in <module>
    from modules.api import api
  File "/home/wrt/stable-diffusion-webui/modules/api/api.py", line 9, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py)

Error loading script: batch_hijack.py
Traceback (most recent call last):
  File "/home/wrt/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/wrt/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wrt/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
    from scripts import external_code
  File "/home/wrt/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/home/wrt/stable-diffusion-webui/modules/api/api.py", line 9, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py)

Error loading script: controlnet.py
Traceback (most recent call last):
  File "/home/wrt/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/wrt/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wrt/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 19, in <module>
    from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version
  File "/home/wrt/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/home/wrt/stable-diffusion-webui/modules/api/api.py", line 9, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py)

ControlNet v1.1.122
Error loading script: external_code.py
Traceback (most recent call last):
  File "/home/wrt/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/wrt/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wrt/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 8, in <module>
    from modules.api import api
  File "/home/wrt/stable-diffusion-webui/modules/api/api.py", line 9, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (/home/wrt/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py)
```

### Additional information

python: 3.10.9  •  torch: 2.0.0+cu118  •  xformers: 0.0.19  •  gradio: 3.28.1  •  commit: [22bcc7be] •  checkpoint: [fc2511737a]
blendmodes==2022
transformers==4.25.1
accelerate==0.12.0
basicsr==1.4.2
gfpgan==1.3.8
**gradio==3.28.1**
numpy==1.23.3
Pillow==9.4.0
realesrgan==0.3.0
**torch==2.0.0**
omegaconf==2.2.3
pytorch_lightning==1.9.4
scikit-image==0.19.2
timm==0.6.7
piexif==1.1.3
einops==0.4.1
jsonmerge==1.8.0
clean-fid==0.1.29
resize-right==0.0.2
torchdiffeq==0.2.3
kornia==0.6.7
lark==1.1.2
inflection==0.5.1
GitPython==3.1.30
torchsde==0.2.5
safetensors==0.3.0
httpcore<=0.15
fastapi==0.94.0

**Comment by huchenlei** [comment]
It looks like a Gradio version issue. Web UI requires gradio 3.23 [link](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements.txt). Also it is better to use python 3.10.6 according to Web UI docs.

**Comment by AI-Robot-Morris** [comment]
thanks for reply

**Comment by huchenlei** [comment]
I just saw WebUI bumps Gradio up to `3.28.1` in the most recent update. Maybe we should solve this issue in the controlnet code. (Replace the call to a deprecated Gradio API)

**Comment by huchenlei** [comment]
Nvm, Seems like the problematic code is already removed.

**Comment by AI-Robot-Morris** [comment]
you can upgrade to 3.28.1 by requirements_versions.txt after reboot
