### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead

### ISSUE THREAD

**Issue by estebanmax** [Mikubill/sd-webui-controlnet#112]
I get this error every time I try to generate an image.

**Comment by Marcusgeorgiadis** [comment]
same

**Comment by KingPungy** [comment]
same

**Comment by LexVolkov** [comment]
What model are you using?

**Comment by Mikubill** [comment]
Inpatint model actually not works since the input channels are different. You may need to train a new controlnet from it.

**Comment by chromatic-descension** [comment]
I had a similar issue and here's what I did. Not sure which part helped.

Open a command prompt or Powershell, `cd` to the stable-diffusion-webui directory and run `git pull`. Then restart SD and refresh, go to the settings menu, go to ControlNet tab, click "Do not append detectmap to output", then "Apply settings". For me, it said I had updated 30-some settings, meaning I probably had old settings enabled prior.

**Comment by estebanmax** [comment]
@Mikubill: yes, I was using inpaint model, then switched to standard 1.5 model and it works fine!

**Comment by numz** [comment]
same here with  instructpix2pix model

**Comment by brovador** [comment]
Same issue when running txt2img with RealisticVision1.3 (standard 1.5 works well)

**Comment by Roozedidar** [comment]
Hi guys, I had the same error and I fixed it by turning off the ControlNet. Good luck!

**Comment by kensin1983123** [comment]
I'm reporting an error when I use INPAINT model local redraw RuntimeError: given groups=1, weight size [320, 9, 3, 3], expect 9 channels for input [2, 4, 64, 64] but get 4 channels instead What is the reason for this and how can I fix it?

**Comment by RoskoDaneworth** [comment]
Anyone knows how to turn off controlnet in Vladmandic SDnext ? because it comes preinstalled and it causes this same error. Cant generate a single pic while it is active.

**Comment by nono-london** [comment]
same error using Flux and controlnet and openpose full or canny. 
Spec. in case this is the issue:
* Cuda 12.1 
* 3070 8GO 
* System 40Go
I run SD Forge under SWL2 an duse the 17Go Flux model

Any help appreciated.
Note:
* the Controlnet/Openpose or Canny models work fine on the SD webui basic install
* The Flux 17Go works well when not activating ControlNet

error log:
`
2024-09-12 22:18:17,467 - ControlNet - INFO - Using preprocessor: openpose_full
2024-09-12 22:18:17,467 - ControlNet - INFO - preprocessor resolution = 512
[Unload] Trying to free 3072.00 MB for cuda:0 with 0 models keep loaded ... Current free memory is 6785.82 MB ... Done.
Automatic Memory Management: 3 Modules in 0.14 seconds.
2024-09-12 22:18:20,603 - ControlNet - INFO - Current ControlNet ControlNetPatcher: /home/my_linux_username/python_projects/stable-diffusion-webui-forge/models/ControlNet/control_v11p_sd15_openpose.pth
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
2024-09-12 22:18:20,609 - ControlNet - INFO - ControlNet Method openpose_full patched.
[Unload] Trying to free 16941.16 MB for cuda:0 with 0 models keep loaded ... Current free memory is 6784.84 MB ... Unload model IntegratedAutoencoderKL Done.
[Memory Management] Target: KModel, Free GPU: 6946.82 MB, Model Require: 11350.09 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: -5427.27 MB, CPU Swap Loaded (blocked method): 6732.00 MB, GPU Loaded: 4618.09 MB
[Memory Management] Target: ControlNet, Free GPU: 2252.69 MB, Model Require: 689.09 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 539.61 MB, All loaded to GPU.
Moving model(s) has taken 1.56 seconds
  0%|                                                                                                                                                                  | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules_forge/main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules/txt2img.py", line 121, in txt2img_function
    processed = processing.process_images(p)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/extensions/sd-webui-prompt-history/lib_history/image_process_hijacker.py", line 21, in process_images
    res = original_function(p)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules/processing.py", line 816, in process_images
    res = process_images_inner(p)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules/processing.py", line 959, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules/processing.py", line 1330, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 238, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 238, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/k_diffusion/sampling.py", line 129, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/modules/sd_samplers_cfg_denoiser.py", line 196, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 267, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, control_cond, len(cond_or_uncond))
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/backend/patcher/controlnet.py", line 338, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint.to(self.device), timesteps=timestep.float(), context=context.to(dtype), y=y)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/backend/nn/cnets/cldm.py", line 260, in forward
    h = module(h, emb, context)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/backend/nn/unet.py", line 89, in forward
    x = layer(x)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/backend/operations.py", line 170, in forward
    return super()._conv_forward(x, weight, bias)
  File "/home/my_linux_username/python_projects/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead
Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead
`

**Comment by Voraxre** [comment]
I'm having the same issue as @nono-london, using Flux with ControlNet. Both work individually, but together they cause this.

**Comment by dariaflavin** [comment]
im having the same KSampler
Given groups=1, weight of size [320, 8, 3, 3], expected input[28, 20, 72, 128] to have 8 channels, but got 20 channels instead problem when trying to do an image 2 video in comfy, what is it???
