### ISSUE TITLE
Simple diffusion test failed

### ISSUE THREAD

**Issue by lllyasviel** [Mikubill/sd-webui-controlnet#1160]
Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1043, in process
    self.enabled_units = self.get_enabled_units(p)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1006, in get_enabled_units
    unit = self.parse_remote_call(p, unit, idx)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 858, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'bool' object has no attribute 'enabled'

**Comment by lllyasviel** [comment]
@ljleb

**Comment by ljleb** [comment]
Can you describe what generated the error? I'm lacking context.

**Comment by lllyasviel** [comment]
nvm it seems did not restarted terminal
