### ISSUE TITLE
[Bug]: tile_resample preprocessor issue. Slider broken

### ISSUE THREAD

**Issue by bananasss00** [Mikubill/sd-webui-controlnet#1186]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Error when select 'tile_resample' preprocessor. Error appears when selecting 'tile_resample' after another preprocessor
![изображение](https://user-images.githubusercontent.com/30229634/236646930-f1b2658a-4f7a-476f-bd8c-c1c108fec4b4.png)

### Steps to reproduce the problem

a)
1. Go to Preprocessor
2. Choose any preprocessor
3. Choose 'tile_resample'

b)
1. Update webui page in browser
2. Choose 'tile_resample'
PS: no error appears, but there is no slider 'Down Sampling Rate' that used to be here

### What should have happened?

fix Down Sampling Rate slider

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89
controlnet: [90ca6d17af89fcf9a0191f58fde01175ba877205](https://github.com/Mikubill/sd-webui-controlnet/commit/90ca6d17af89fcf9a0191f58fde01175ba877205)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sdp-attention
```

### Console logs

```Shell
Traceback (most recent call last):
  File "i:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "i:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "i:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "i:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "i:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "i:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 386, in build_sliders
    if slider_config['name'] == flag_preprocessor_resolution:
TypeError: 'int' object is not subscriptable
```

**Comment by lllyasviel** [comment]
fixed in 1.1.145
