### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'save' in batch processing

### ISSUE THREAD

**Issue by simonhavelock** [Mikubill/sd-webui-controlnet#126]
Everything works smoothly in img2img tab on singular images, but when using batch processing the following error comes up.
Windows 10.

```
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\img2img.py", line 163, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "D:\stable-diffusion-webui\modules\img2img.py", line 76, in process_batch
    processed_image.save(os.path.join(output_dir, filename))
AttributeError: 'numpy.ndarray' object has no attribute 'save'
```

**Comment by Mikubill** [comment]
In settings tab, tick the "Do not append detectmap to output" checkbox.

**Comment by simonhavelock** [comment]
Perfect, that solves it!
Is there a way to separately save the output of segmentation? Would be useful possibly for some after effects post-processing fun.
