### ISSUE TITLE
ControlNet failed to use VAE

### ISSUE THREAD

**Issue by Zullian** [Mikubill/sd-webui-controlnet#1260]
When I try to upscale with Tiled Diffusion/VAE, with controlnet enabled and preprocessor "reference_only" I get error:

ValueError: ControlNet failed to use VAE. Please try to add `--no-half-vae`, `--no-half` and remove `--precision full` in launch cmd.

I tried to run with those commands but still didn't work.

**Comment by BlackGlory** [comment]
I don't get this error, but I can confirm that using control_v11p_sd15_inpaint under txt2img does not use VAE: the generated image is faded whether I set SD VAE or not.

It may be related to #1164.

**Comment by Arron17** [comment]
Can confirm I get the same issue.

If you use Img2Img with the Reference_Only PreProcessor along with the Tiled diffusion and/or tiled vae from the Extension "https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111"

You will get an error similar to this:

```[Tiled Diffusion] upscaling image with 4x-UltraSharp...
[Tiled Diffusion] ControlNet found, support is enabled.
Loading preprocessor: reference_only
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.RESIZE
raw_H = 585
raw_W = 780
target_H = 585
target_W = 780
estimation = 585.0
preprocessor resolution = 585
                                                                                                                       MultiDiffusion hooked into 'DPM++ 2M Karras' sampler, Tile size: 96x96, Tile batches: 2, Batch size: 1. (ext: ContrlNet)
MultiDiffusion Sampling:   0%|                                                                  | 0/54 [00:00<?, ?it/s]Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 2, 3, 584, 768]
  0%|                                                                                           | 0/27 [00:00<?, ?it/s]
Error completing request                                                                        | 0/27 [00:00<?, ?it/s]
Arguments: ('task(npdkk6687mlsdjk)', 0, 'A cinematic Photograph of a Ferrari 360 on a broken road', 'painted by bad-artist', [], <PIL.Image.Image image mode=RGBA size=600x450 at 0x179FF78B0A0>, None, None, None, None, None, None, 35, 15, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, 1350254317.0, -1.0, 0, 0, 0, False, 0, 512, 680, 1, 0, 0, 32, 0, '', '', '', [], 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, '4x-UltraSharp', 1.3, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 1536, 96, True, True, True, False, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <controlnet.py.UiControlNetUnit object at 0x00000179FF76A110>, <controlnet.py.UiControlNetUnit object at 0x000001790AD5FC70>, <controlnet.py.UiControlNetUnit object at 0x000001790AD5E830>, False, '', 0.5, True, False, '', 'Lerp', False, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, None, False, None, False, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 238, in forward
    latent_hint = outer.sd_ldm.encode_first_stage(latent_hint)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 523, in forward
    hs = [self.conv_in(x)]
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 376, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\lycoris.py", line 746, in lyco_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lyco(self, input)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 2, 3, 584, 768]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\img2img.py", line 182, in img2img
    processed = process_images(p)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\processing.py", line 680, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\processing.py", line 1135, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 350, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 350, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 135, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 243, in wrapper
    return fn(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 103, in kdiff_forward
    return self.sample_one_step(x_in, org_func, repeat_func, custom_func)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 179, in sample_one_step
    x_tile_out = repeat_func(x_tile, bboxes)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 97, in repeat_func
    x_tile_out = self.sampler_forward(x_tile, sigma_in_tile, cond=new_cond)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 402, in forward_webui
    return forward(*args, **kwargs)
  File "D:\Code\Stable-Diffusion\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 251, in forward
    raise ValueError('ControlNet failed to use VAE. Please try to add `--no-half-vae`, `--no-half` and remove `--precision full` in launch cmd.')
ValueError: ControlNet failed to use VAE. Please try to add `--no-half-vae`, `--no-half` and remove `--precision full` in launch cmd.
```

**Comment by Padusarbor** [comment]
I use Vlad, when txt-to-img with Tiled VAE ON and with the reference_only preprocessor, the image becomes corrupted.

**Comment by GapMondragon** [comment]
up

**Comment by Razunter** [comment]
I'm getting this if I don't select VAE manually in settings.

**Comment by Shumpei0706** [comment]
I had updated SD-webUI to the latest version and I could resolve this

**Comment by PaperOrb** [comment]
Piggy backing on this to say I'm not getting any errors in the log, but when I use reference_only @ fidelity of 1.0 alongside the softedge preprocessor+softedge model v11p_sd15, my images look like there's no VAE enabled. Let me know if there's another issue for this though because I didn't see one.

**Comment by NakiriRuri** [comment]
I can reproduce this problem too, but I use the tile series preprocessor.

**Comment by demib72** [comment]
I am getting this with the inpainting model. Was working before.

**Comment by DrakenZA** [comment]
Still seems Reference Mode(rest are fine) gives this error when attempting to use Multi-Diffusion Extension. This should be possible, someone who understands the code most likely could resolve.

**Comment by 1joshw** [comment]
i too getting the error with controlnet enabled and preprocessor "reference_only" I get error:
ValueError: ControlNet failed to use VAE. Please try to add --no-half-vae, --no-half and remove --precision full in launch cmd.

everything is up to date 
 any tips

**Comment by janfeldmann** [comment]
I added `--precision autocast` which is the default in the webui-user.sh and it worked again

`export COMMANDLINE_ARGS="--precision autocast"`

**Comment by gohan2091** [comment]
I'm having the same error. I already have precision set to autocast. I tried enabling Use full precision for VAE (--no-half-vae) but it didn't help. Then I tried enabling Use full precision for model (--no-half) but no joy. If I enable both no-half settings together it doesn't help. If I enable all 3 (precision to full, and the two no-half) THEN reference only ControlNet works but now my generation speed is much slower. Please can someone help?
