### ISSUE TITLE
Encountered this issue while using mlsd. How to solve it?（http.client.RemoteDisconnected: Remote end closed connection without response）

### ISSUE THREAD

**Issue by chaai2** [Mikubill/sd-webui-controlnet#1292]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 478, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b, json_pose_callback=json_acceptor.accept)
  File "D:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\processor.py", line 157, in mlsd
    result = model_mlsd(img, thr_v, thr_d)
  File "D:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\annotator\mlsd\__init__.py", line 32, in apply_mlsd
    load_file_from_url(remote_model_path, model_dir=modeldir)
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\basicsr\utils\download_util.py", line 98, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "D:\stable-diffusion-webui-master\venv\lib\site-packages\torch\hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "D:\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\python\lib\urllib\request.py", line 1352, in do_open
    r = h.getresponse()
  File "D:\python\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "D:\python\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "D:\python\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by UriahKong** [comment]
same bro
