### ISSUE TITLE
[Bug]: KeyError: 'cn_1_overwrite_frames'

### ISSUE THREAD

**Issue by zhangshaoju1987** [Mikubill/sd-webui-controlnet#1301]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/69586325/146a67fa-7163-4dbb-bc0e-dc176c69c749)

### Steps to reproduce the problem

1. install deform and reload webui
2. report that error

### What should have happened?

Deform Tab should show in webui

### Commit where the problem happens

webui: latest SD-WebUI revision: b08500cec8a791ef20082628b49b17df833f5dda
controlnet: v1.1.139

### Command Line Arguments

```Shell
Launching Web UI with arguments: --port 7860 --skip-version-check
```

### Console logs

```Shell
Launching Web UI with arguments: --port 7860 --skip-version-check
No module 'xformers'. Proceeding without it.
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\stable-diffustion\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
dirname:  C:\stable-diffustion\stable-diffusion-webui\localizations
localizations:  {'zh-Hans (Stable)': 'C:\\stable-diffustion\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Stable).json', 'zh-Hans (Testing)': 'C:\\stable-diffustion\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-localization-zh_Hans\\localizations\\zh-Hans (Testing).json'}
ControlNet v1.1.139
ControlNet v1.1.139
Civitai: API loaded
Loading weights [4078eb4174] from C:\stable-diffustion\stable-diffusion-webui\models\Stable-diffusion\3Guofeng3_v33.safetensors
Creating model from config: C:\stable-diffustion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
*Deforum ControlNet support: enabled*
'ControlNet UI setup failed with error: 'module 'extensions.sd-webui-controlnet.scripts.external_code' has no attribute 'get_modules_detail''!
Error executing callback ui_tabs_callback for C:\stable-diffustion\stable-diffusion-webui\extensions\deforum\scripts\deforum.py
Traceback (most recent call last):
  File "C:\stable-diffustion\stable-diffusion-webui\modules\script_callbacks.py", line 134, in ui_tabs_callback
    res += c.callback() or []
  File "C:\stable-diffustion\stable-diffusion-webui\extensions\deforum\scripts\deforum.py", line 293, in on_ui_tabs
    component_list = [components[name] for name in deforum_args.get_component_names()]
  File "C:\stable-diffustion\stable-diffusion-webui\extensions\deforum\scripts\deforum.py", line 293, in <listcomp>
    component_list = [components[name] for name in deforum_args.get_component_names()]
KeyError: 'cn_1_overwrite_frames'

Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 2.4s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.5s, apply half(): 0.5s, move model to device: 0.4s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Civitai: Check resources for missing preview images
Startup time: 7.4s (import torch: 0.8s, import gradio: 0.7s, import ldm: 0.2s, other imports: 0.5s, load scripts: 0.9s, opts onchange: 1.2s, create ui: 0.9s, gradio launch: 2.1s).
Civitai: Found 7 resources missing preview images
Civitai: No preview images found on Civitai
```

**Comment by shaoxi2093** [comment]
mark，same error

**Comment by sven721** [comment]
mark，same error

**Comment by AidenFan** [comment]
I solved this by pulling the lastest sd-webui-controlnet.

**Comment by oldwhite83** [comment]
> I solved this by pulling the lastest sd-webui-controlnet.

me too
