### ISSUE TITLE
[Bug]: zoe preprocessor not working

### ISSUE THREAD

**Issue by HeavenlyChorus** [Mikubill/sd-webui-controlnet#1305]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

same issue of:
https://github.com/Mikubill/sd-webui-controlnet/issues/1047

after installing `pip install timm==0.6.13` i got the following error:

```
Preview Resolution = 512
img_size [384, 512]
Traceback (most recent call last):
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 474, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b, json_pose_callback=json_acceptor.accept)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 475, in zoe_depth
    result = model_zoe_depth(img)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/__init__.py", line 38, in __call__
    self.load_model()
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/__init__.py", line 27, in load_model
    model = ZoeDepth.build_from_config(conf)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/zoedepth/zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/zoedepth/zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas.py", line 343, in build
    midas = torch.hub.load(midas_path, midas_model_type,
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/torch/hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/hubconf.py", line 38, in DPT_BEiT_L_384
    model = DPTDepthModel(
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/dpt_depth.py", line 160, in __init__
    super().__init__(head, **kwargs)
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/dpt_depth.py", line 71, in __init__
    self.pretrained, self.scratch = _make_encoder(
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/blocks.py", line 42, in _make_encoder
    pretrained = _make_pretrained_beitl16_384(
  File "/root/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/beit.py", line 175, in _make_pretrained_beitl16_384
    model = timm.create_model("beit_large_patch16_384", pretrained=pretrained)
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/timm/models/factory.py", line 81, in create_model
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/timm/models/beit.py", line 447, in beit_large_patch16_384
    model = _create_beit('beit_large_patch16_384', pretrained=pretrained, **model_kwargs)
  File "/opt/conda/envs/diffusers/lib/python3.10/site-packages/timm/models/beit.py", line 398, in _create_beit
    model = build_model_with_cfg(
TypeError: build_model_with_cfg() missing 1 required positional argument: 'default_cfg'
```
have to open a new issue since the old one was closed without a solution for some reason

### Steps to reproduce the problem

choose depth_zoe as preprocessor and hit preview
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13861429/280e0811-ad03-4271-9645-cdf4a673bd9d)

### What should have happened?

preview image appears

### Commit where the problem happens

webui: cf17dfcd
controlnet: d831043c 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--deepdanbooru --xformers --allow-code --no-half-vae --listen --port --share --gradio-auth --enable-insecure-extension-access
```

### Console logs

```Shell
as mentioned
```

**Comment by shixiaotong123** [comment]
i install timm==0.6.7 it works

**Comment by juukesoon111** [comment]
Having a similar issue, tried to install timm == 0.6.7

For mine, the difference is that it will just keep taking up vram and go OOM. it has never happened before, the other controlnet preprocessors work fine and i can run 3-4 of them at once, just not the depth zoe.

tried reinstalling controlnet too.

Any help will be greatly appreciated!
