### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'convert'

### ISSUE THREAD

**Issue by thxshj** [Mikubill/sd-webui-controlnet#1317]
Error completing request
Arguments: ('task(3oog2vxc04ef5jl)', 0, 'Flowers,', '', [], None, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 0, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <controlnet.py.UiControlNetUnit object at 0x000002186DB63040>, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, 50) {}
Traceback (most recent call last):
  File "D:\Stable Diffusion\novelai-webui\novelai-webui-aki-v3\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable Diffusion\novelai-webui\novelai-webui-aki-v3\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable Diffusion\novelai-webui\novelai-webui-aki-v3\modules\img2img.py", line 90, in img2img
    image = init_img.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

**Comment by thxshj** [comment]
An error occurred when using img2img.
Reinstalling did not solve the problem
