### ISSUE TITLE
[Bug]: Webui-docker-auto exiting during restart after controlnet install

### ISSUE THREAD

**Issue by bdarley5** [Mikubill/sd-webui-controlnet#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Fresh install of [stable-diffusion-webui-docker](https://github.com/AbdBarho/stable-diffusion-webui-docker)
After following the install instructions provided for sd-webui-controlnet the webui-docker-auto1 container exits with code 1 after first restart. 

### Steps to reproduce the problem

1. Fresh install of [stable-diffusion-webui-docker](https://github.com/AbdBarho/stable-diffusion-webui-docker)
2. follow the install instructions provided for sd-webui-controlnet
3. restart the container as required

### What should have happened?

Should have restarted normally 

### Commit where the problem happens

webui: 6.0.0
controlnet: current

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

None

### Console logs

```Shell

DURING INSTALL
webui-docker-auto-1  | Installing sd-webui-controlnet requirement: mediapipe
webui-docker-auto-1  | Installing sd-webui-controlnet requirement: svglib
webui-docker-auto-1  | Couldn't install sd-webui-controlnet requirement: svglib.
webui-docker-auto-1  | Command: "/usr/local/bin/python" -m pip install svglib --prefer-binary
webui-docker-auto-1  | Error code: 1
webui-docker-auto-1  | stdout: Collecting svglib
webui-docker-auto-1  |   Downloading svglib-1.5.1.tar.gz (913 kB)
webui-docker-auto-1  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 913.9/913.9 kB 12.1 MB/s eta 0:00:00
webui-docker-auto-1  |   Preparing metadata (setup.py): started
webui-docker-auto-1  |   Preparing metadata (setup.py): finished with status 'done'
webui-docker-auto-1  | Collecting reportlab
webui-docker-auto-1  |   Downloading reportlab-4.0.0-py3-none-any.whl (1.9 MB)
webui-docker-auto-1  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 31.4 MB/s eta 0:00:00
webui-docker-auto-1  | Collecting lxml
webui-docker-auto-1  |   Downloading lxml-4.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.1 MB)
webui-docker-auto-1  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 53.9 MB/s eta 0:00:00
webui-docker-auto-1  | Collecting tinycss2>=0.6.0
webui-docker-auto-1  |   Downloading tinycss2-1.2.1-py3-none-any.whl (21 kB)
webui-docker-auto-1  | Collecting cssselect2>=0.2.0
webui-docker-auto-1  |   Downloading cssselect2-0.7.0-py3-none-any.whl (15 kB)
webui-docker-auto-1  | Collecting webencodings
webui-docker-auto-1  |   Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
webui-docker-auto-1  | Collecting freetype-py<2.4,>=2.3.0
webui-docker-auto-1  |   Downloading freetype_py-2.3.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (978 kB)
webui-docker-auto-1  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 978.9/978.9 kB 22.6 MB/s eta 0:00:00
webui-docker-auto-1  | Collecting rlPyCairo<1,>=0.2.0
webui-docker-auto-1  |   Downloading rlPyCairo-0.2.0-py3-none-any.whl (10 kB)
webui-docker-auto-1  | Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.10/site-packages (from reportlab->svglib) (9.4.0)
webui-docker-auto-1  | Collecting pycairo>=1.20.0
webui-docker-auto-1  |   Downloading pycairo-1.23.0.tar.gz (344 kB)
webui-docker-auto-1  |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 344.6/344.6 kB 10.2 MB/s eta 0:00:00
webui-docker-auto-1  |   Installing build dependencies: started
webui-docker-auto-1  |   Installing build dependencies: finished with status 'done'
webui-docker-auto-1  |   Getting requirements to build wheel: started
webui-docker-auto-1  |   Getting requirements to build wheel: finished with status 'done'
webui-docker-auto-1  |   Installing backend dependencies: started
webui-docker-auto-1  |   Installing backend dependencies: finished with status 'done'
webui-docker-auto-1  |   Preparing metadata (pyproject.toml): started
webui-docker-auto-1  |   Preparing metadata (pyproject.toml): finished with status 'done'
webui-docker-auto-1  | Building wheels for collected packages: svglib, pycairo
webui-docker-auto-1  |   Building wheel for svglib (setup.py): started
webui-docker-auto-1  |   Building wheel for svglib (setup.py): finished with status 'done'
webui-docker-auto-1  |   Created wheel for svglib: filename=svglib-1.5.1-py3-none-any.whl size=30909 sha256=8eb9f79089b06ebad5624b575c58a9af9f96ff9e6b670de9bc038c236370abff
webui-docker-auto-1  |   Stored in directory: /data/.cache/pip/wheels/0d/01/86/44e257e6f677ffa5d3b64609b443f275faf92428f4256aca85
webui-docker-auto-1  |   Building wheel for pycairo (pyproject.toml): started
webui-docker-auto-1  |   Building wheel for pycairo (pyproject.toml): finished with status 'error'
webui-docker-auto-1  | Successfully built svglib
webui-docker-auto-1  | Failed to build pycairo
webui-docker-auto-1  |
webui-docker-auto-1  | stderr:   error: subprocess-exited-with-error
webui-docker-auto-1  |
webui-docker-auto-1  |   × Building wheel for pycairo (pyproject.toml) did not run successfully.
webui-docker-auto-1  |   │ exit code: 1
webui-docker-auto-1  |   ╰─> [12 lines of output]
webui-docker-auto-1  |       running bdist_wheel
webui-docker-auto-1  |       running build
webui-docker-auto-1  |       running build_py
webui-docker-auto-1  |       creating build
webui-docker-auto-1  |       creating build/lib.linux-x86_64-cpython-310
webui-docker-auto-1  |       creating build/lib.linux-x86_64-cpython-310/cairo
webui-docker-auto-1  |       copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-310/cairo
webui-docker-auto-1  |       copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-310/cairo
webui-docker-auto-1  |       copying cairo/py.typed -> build/lib.linux-x86_64-cpython-310/cairo
webui-docker-auto-1  |       running build_ext
webui-docker-auto-1  |       'pkg-config' not found.
webui-docker-auto-1  |       Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
webui-docker-auto-1  |       [end of output]
webui-docker-auto-1  |
webui-docker-auto-1  |   note: This error originates from a subprocess, and is likely not a problem with pip.
webui-docker-auto-1  |   ERROR: Failed building wheel for pycairo
webui-docker-auto-1  | ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
webui-docker-auto-1  |
webui-docker-auto-1  | [notice] A new release of pip available: 22.3.1 -> 23.1.2
webui-docker-auto-1  | [notice] To update, run: pip install --upgrade pip
webui-docker-auto-1  |
webui-docker-auto-1  |
webui-docker-auto-1  | Warning: Failed to install svglib, some preprocessors may not work.
webui-docker-auto-1  | Installing sd-webui-controlnet requirement: fvcore

AFTER REBOOT

2023-05-20 13:05:47 webui-docker-auto-1      | Traceback (most recent call last):
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/stable-diffusion-webui/webui.py", line 35, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     from modules import extra_networks, ui_extra_networks_checkpoints
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 5, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     from modules import shared, ui_extra_networks, sd_models
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/stable-diffusion-webui/modules/ui_extra_networks.py", line 8, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     from modules.images import read_info_from_image
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/stable-diffusion-webui/modules/images.py", line 21, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     from modules import sd_samplers, shared, script_callbacks, errors
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 9, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     from modules import sd_samplers_common, prompt_parser, shared
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/stable-diffusion-webui/modules/sd_samplers_common.py", line 5, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     from modules import devices, processing, images, sd_vae_approx
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/stable-diffusion-webui/modules/processing.py", line 12, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     import cv2
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2023-05-20 13:05:47 webui-docker-auto-1      |     bootstrap()
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/usr/local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2023-05-20 13:05:47 webui-docker-auto-1      |     native_module = importlib.import_module("cv2")
2023-05-20 13:05:47 webui-docker-auto-1      |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-05-20 13:05:47 webui-docker-auto-1      |     return _bootstrap._gcd_import(name[level:], package, level)
2023-05-20 13:05:47 webui-docker-auto-1      | ImportError: libGL.so.1: cannot open shared object file: No such file or directory
1970-01-01 10:00:00 webui-docker-auto-1 exited with code 1
```

**Comment by MiikaH** [comment]
This is a problem with stable-diffusion-webui-docker.

You can work around it by adding a line `RUN apt-get -y install libgl1-mesa-glx && apt-get clean` in `services/AUTOMATIC1111/Dockerfile` (for example below the line where it installs opencv-python-headless).

If you don't want to manually modify the Dockerfile you should report the issue in the webui-docker repository and maybe @AbdBarho can add libgl install there to fix this for everyone.

**Comment by AbdBarho** [comment]
I am not a big fan of adding `libgl` because it installs half gigabyte of unnecessary dependencies, with trivial workaround already [in the wiki](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Usage#extensions).

Alas, this is not the first time a problem like this happened, and probably won't be the last. I will add it so it works for everyone.

This comment I made half a year ago explains it better  https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/778#issuecomment-1254846762

**Comment by MiikaH** [comment]
Please note that I'm not in any way affiliated with `sd-webui-controlnet`. I just noticed this issue ticket and having added `libgl1-mesa-glx` to my webui-docker Dockerfile to get controlnet working I shared the workaround here, pointing out that this technically isn't a "bug" in this repository itself.

And yes, ideally all extensions would use `open-cv-headless` to keep them docker compatible but here we are. :)

**Comment by larangin** [comment]
@MiikaH thanks. your solution worked :confetti_ball: . hopefully it can addressed in next version.

**Comment by bdarley5** [comment]
Thanks, guys I appreciate all the help.
