### ISSUE TITLE
[Bug]: Error running process

### ISSUE THREAD

**Issue by FlexReid21** [Mikubill/sd-webui-controlnet#1368]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Whenever i try to use ControlNet i get this error in the terminal, and the image generates without any adjustments from ControlNet. I don't have any other extensions installed either.

### Steps to reproduce the problem

1. Enable ControlNet

### What should have happened?

worked

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
--xformers --autolaunch
```

### List of enabled extensions

ControlNet

### Console logs

```Shell
Error running process: C:\Users\Flexo\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Flexo\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "C:\Users\Flexo\Downloads\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1065, in process
    raise ValueError('controlnet is enabled but no input image is given')
```

**Comment by katopz** [comment]
Do you have multiple controlnet tab and somehow `enable` it?

**Comment by hanrw** [comment]
same issue
```
12:45 PMHint: You can take a look at [/home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/models] to find many existing YAML files.
7/22/2023 6:12:45 PM
7/22/2023 6:12:45 PM2023-07-22 10:12:45,763 - ControlNet - INFO - Loading config: /home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_mlsd.yaml
7/22/2023 6:12:48 PM2023-07-22 10:12:48,425 - ControlNet - INFO - ControlNet model control_v1p_sd15_brightness [5f6aa6ed] loaded.
7/22/2023 6:12:48 PM2023-07-22 10:12:48,449 - ControlNet - INFO - Loading preprocessor: none
7/22/2023 6:12:48 PM2023-07-22 10:12:48,449 - ControlNet - INFO - preprocessor resolution = 832
7/22/2023 6:12:48 PM2023-07-22 10:12:48,461 - ControlNet - INFO - Loading model from cache: control_v1p_sd15_brightness [5f6aa6ed]
7/22/2023 6:12:48 PM*** Error running process: /home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
7/22/2023 6:12:48 PM    Traceback (most recent call last):
7/22/2023 6:12:48 PM      File "/home/diffusion/stable-diffusion-webui/modules/scripts.py", line 474, in process
7/22/2023 6:12:48 PM        script.process(p, *script_args)
7/22/2023 6:12:48 PM      File "/home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 734, in process
7/22/2023 6:12:48 PM        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
7/22/2023 6:12:48 PM      File "/home/diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 652, in choose_input_image
7/22/2023 6:12:48 PM        raise ValueError('controlnet is enabled but no input image is given')
7/22/2023 6:12:48 PM    ValueError: controlnet is enabled but no input image is given
```

version: [v1.4.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/f865d3e11647dfd6c7b2cdf90dde24680e58acd8)  •  python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: [bc2f30f4ad](https://google.com/search?q=bc2f30f4adbedf85c81d5aa3d2714461c0244c5941dabcd7946b8ffe54c34f46)

**Comment by hanrw** [comment]
There are 3 three tabs.  fixed by disable other two tabs.
<img width="710" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/1201118/8ccb4845-2bfe-45ad-b44d-dc771493fe30">
