### ISSUE TITLE
[Bug]: AttributeError: module 'scripts.global_state' has no attribute 'cache_preprocessors'

### ISSUE THREAD

**Issue by HARUKAGUEN** [Mikubill/sd-webui-controlnet#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

after I have updated to the latest version of ControlNet, the ControlNet disappeared from the webUI.

I have did the following:

- Reset the webUI
- Delete Controlnet and download again
- Fresh install for Automatic1111

Nothing has fixed the issue. I would appreciate any advice

### Steps to reproduce the problem

1. Download ControlNet
2. Update the latest ControlNet
3. Launch WebUI

### What should have happened?

ControlNet should have showed up in the WebUI

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![Screenshot 2023-05-23 222945](https://github.com/Mikubill/sd-webui-controlnet/assets/134449807/1ffc85f9-9577-4ee3-a159-d3de34746c50)

### Console logs

```Shell
ControlNet v1.1.189
Error loading script: global_state.py
Traceback (most recent call last):
  File "E:\AI Generation Test\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\AI Generation Test\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI Generation Test\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 9, in <module>
    from scripts.utils import ndarray_lru_cache
ImportError: cannot import name 'ndarray_lru_cache' from 'scripts.utils' (E:\AI Generation Test\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py)

(SETUP) Loading Unprompted v9.2.0 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Logging enabled for the following message types: RESULT,ERROR
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Error executing callback app_started_callback for E:\AI Generation Test\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py
Traceback (most recent call last):
  File "E:\AI Generation Test\stable-diffusion-webui\modules\script_callbacks.py", line 107, in app_started_callback
    c.callback(demo, app)
  File "E:\AI Generation Test\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 49, in controlnet_api
    cached_cn_preprocessors = global_state.cache_preprocessors(global_state.cn_preprocessor_modules)
AttributeError: module 'scripts.global_state' has no attribute 'cache_preprocessors'
```

**Comment by huchenlei** [comment]
Similar issue as #1381. Completely restart WebUI should fix the problem.
