### ISSUE TITLE
Errors running openpose preprocessors 

### ISSUE THREAD

**Issue by ApoyPH** [Mikubill/sd-webui-controlnet#1409]
### Is there an existing issue for this?
I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?
Whenever I run openpose preprocessors in ControlNet suddenly I get an error. All other preprocessors works just fine. My openpose preprocessors worked just fine before this happened

### Steps to reproduce the problem
1. Run openpose, openpose_full, openpose_hand, openpose_face, openpose_faceonly preprocessors

### What should have happened?
Worked.

### Commit where the problem happens
Webui
ControlNet
openpose preprocessor

### What browsers do you use to access the UI ?
Google Chrome

###Command Line Arguments
--xformers --medvram

### List of enabled extensions
ControlNet
Deforum
Animator Extension
Vram Estimator
EBsynth Utility
gif2gif
sd-3dmodel_loader
llul
text2video
dreambooth
embedding editor
images browser
training picker
ultimate upscale

### Console Logs

```
Launching Web UI with arguments: --xformers --medvram
Loading weights [ef8629e2c8] from C:\stable-diffusion-webui\models\Stable-diffusion\protogenX34Photorealism_protogenX34.safetensors
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): EasyNegative
Model loaded in 5.9s (load weights from disk: 0.1s, create model: 3.8s, apply weights to model: 0.9s, apply half(): 1.1s).
[AddNet] Updating model hashes...
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1604.63it/s]
[AddNet] Updating model hashes...
100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 8023.54it/s]
ControlNet v1.1.189
ControlNet v1.1.189
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
[VRAMEstimator] Loaded benchmark data.
*Deforum ControlNet support: enabled*
CUDA SETUP: Loading binary C:\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 23.8s (import torch: 4.1s, import gradio: 1.2s, import ldm: 0.5s, other imports: 1.0s, load scripts: 9.8s, create ui: 6.8s, gradio launch: 0.3s).
Preview Resolution = 512
Calling preprocessor openpose outside of cache.
ControlNet preprocessor location: C:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 485, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b,
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 70, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 58, in cached_func
    return func(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 248, in run_model
    return remove_pad(self.model_openpose(
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 258, in __call__
    poses = self.detect_poses(oriImg, include_hand, include_face)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 202, in detect_poses
    self.load_model()
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 138, in load_model
    self.face_estimation = Face(face_modelpath)
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\face.py", line 325, in __init__
    self.model.load_state_dict(torch.load(face_model_path))
  File "C:\stable-diffusion-webui\modules\safe.py", line 107, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "C:\stable-diffusion-webui\modules\safe.py", line 152, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 595170 more bytes. The file might be corrupted.
```

**Comment by lllyasviel** [comment]
"The file might be corrupted."

try backup models and reinstall

**Comment by ApoyPH** [comment]
Should I reinstall the controlnet only or the whole sd?
Thank you.
