### ISSUE TITLE
[Bug]: ControlNet does not participate in the process (Macbook M1)

### ISSUE THREAD

**Issue by korronald** [Mikubill/sd-webui-controlnet#1418]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Whatever I set, it seems, that Control Net does not participate in a prompt. 

CN is doing correct preprocess, I tested scribble, lineart, canny and other models, but it does not reflect the final result in any way.

comp: Macbook M1, ContNet 54f7c64b (I did an update today to see if it fixed anything, but no result)

Tested on several SD checkpoints: 1.5, 2.1 and others

ControlNet models 15 produced plenty of errors, CN models 21 are not producing errors (but they do not producing results) 

![CNsettings](https://github.com/Mikubill/sd-webui-controlnet/assets/81590304/0e7258e1-4020-4469-9450-00c8dbb8e77c)
![extn](https://github.com/Mikubill/sd-webui-controlne
![controlnetWorksNot2_CNoff](https://github.com/Mikubill/sd-webui-controlnet/assets/81590304/7b65dba9-d7c6-4569-ab15-3c917cb59dc5)
![controlnetWorksNot2_CNon](https://github.com/Mikubill/sd-webui-controlnet/assets/81590304/c5183caf-037a-4cf1-b9b2-32409ff44188)
t/assets/81590304/4ef3e32b-cc4d-435c-b4ae-5194570d32eb)
![controlnetWorksNot](https://github.com/Mikubill/sd-webui-controlnet/assets/81590304/b06cecb5-faeb-4062-b299-b3e86b86b693)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Control net should control, I guess :)

### Commit where the problem happens

webui: version: [v1.2.1] python: 3.10.11  •  torch: 2.1.0.dev20230522  •  xformers: N/A  •  gradio: 3.29.0  •  checkpoint: [e1441589a6]

controlnet:  [54f7c64b]

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
webui-user.sh:

#!/bin/bash
#########################################################
# Uncomment and change the variables below to your need:#
#########################################################

# Install directory without trailing slash
#install_dir="/home/$(whoami)"

# Name of the subdirectory
#clone_dir="stable-diffusion-webui"

# Commandline arguments for webui.py, for example: export COMMANDLINE_ARGS="--medvram --opt-split-attention"
export COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate"

# python3 executable
#python_cmd="python3"

# git executable
#export GIT="git"

# python3 venv without trailing slash (defaults to ${install_dir}/${clone_dir}/venv)
venv_dir="venv-torch-nightly"

# script to launch to start the app
#export LAUNCH_SCRIPT="launch.py"

# install command for torch
export TORCH_COMMAND="pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html --upgrade pip"

# Requirements file to use for stable-diffusion-webui
#export REQS_FILE="requirements_versions.txt"

# Fixed git repos
#export K_DIFFUSION_PACKAGE=""
#export GFPGAN_PACKAGE=""

# Fixed git commits
#export STABLE_DIFFUSION_COMMIT_HASH=""
#export TAMING_TRANSFORMERS_COMMIT_HASH=""
#export CODEFORMER_COMMIT_HASH=""
#export BLIP_COMMIT_HASH=""

# Uncomment to enable accelerated launch
#export ACCELERATE="True"

###########################################
```

### List of enabled extensions

![extn](https://github.com/Mikubill/sd-webui-controlnet/assets/81590304/5aab2c1b-80e3-4090-b6bf-8bc4009c4358)

### Console logs

```Shell
Last login: Wed May 24 20:47:33 on ttys000
rw@RAFmb ~ % cd stable-diffusion-webui
rw@RAFmb stable-diffusion-webui % ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on rw user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Installing requirements

No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 requests-2.31.0 tensorboard-data-server-0.6.1 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[!] xformers NOT installed.
[+] torch version 2.1.0.dev20230522 installed.
[+] torchvision version 0.16.0.dev20230522 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.


Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
ControlNet v1.1.190
ControlNet v1.1.190
Loading weights [e1441589a6] from /Users/rw/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.ckpt
Creating model from config: /Users/rw/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 3.2s (load weights from disk: 1.5s, create model: 0.6s, apply weights to model: 0.3s, apply half(): 0.3s, move model to device: 0.4s).
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 9.7s (import torch: 3.0s, import gradio: 0.5s, import ldm: 0.2s, other imports: 0.5s, load scripts: 4.4s, create ui: 0.9s).
Loading model: control_v11p_sd21_canny [4ac9f628]
Loaded state_dict from [/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd21_canny.safetensors]
Loading config: /Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd21_canny.yaml
Error running process: /Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/Users/rw/stable-diffusion-webui/modules/scripts.py", line 418, in process
    script.process(p, *script_args)
  File "/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1036, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 699, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 779, in build_control_model
    network = network_module(
  File "/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 91, in __init__
    self.control_model.load_state_dict(state_dict)
  File "/Users/rw/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2056, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:
	size mismatch for input_blocks.1.1.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
	size mismatch for input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for input_blocks.1.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
	size mismatch for input_blocks.2.1.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
	size mismatch for input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for input_blocks.2.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
	size mismatch for input_blocks.4.1.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
	size mismatch for input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
	size mismatch for input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
	size mismatch for input_blocks.4.1.proj_out.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
	size mismatch for input_blocks.5.1.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
	size mismatch for input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
	size mismatch for input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
	size mismatch for input_blocks.5.1.proj_out.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
	size mismatch for input_blocks.7.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for input_blocks.7.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for input_blocks.8.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for input_blocks.8.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for middle_block.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for middle_block.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for middle_block.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for middle_block.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.40it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.60it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.60it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.60it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:32<00:00,  2.43it/s]
Loading model: control_v11p_sd21_openpose [2be3125b]█████████████████████████████████████████████████████████████████████████████████| 80/80 [00:32<00:00,  2.58it/s]
Loaded state_dict from [/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd21_openpose.safetensors]
Loading config: /Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd21_openpose.yaml
Error running process: /Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/Users/rw/stable-diffusion-webui/modules/scripts.py", line 418, in process
    script.process(p, *script_args)
  File "/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1036, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 699, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 779, in build_control_model
    network = network_module(
  File "/Users/rw/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 91, in __init__
    self.control_model.load_state_dict(state_dict)
  File "/Users/rw/stable-diffusion-webui/venv-torch-nightly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2056, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:
	size mismatch for input_blocks.1.1.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
	size mismatch for input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for input_blocks.1.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
	size mismatch for input_blocks.2.1.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
	size mismatch for input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
	size mismatch for input_blocks.2.1.proj_out.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
	size mismatch for input_blocks.4.1.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
	size mismatch for input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
	size mismatch for input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
	size mismatch for input_blocks.4.1.proj_out.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
	size mismatch for input_blocks.5.1.proj_in.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
	size mismatch for input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
	size mismatch for input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([640, 1024]) from checkpoint, the shape in current model is torch.Size([640, 768]).
	size mismatch for input_blocks.5.1.proj_out.weight: copying a param with shape torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1, 1]).
	size mismatch for input_blocks.7.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for input_blocks.7.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for input_blocks.8.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for input_blocks.8.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for middle_block.1.proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).
	size mismatch for middle_block.1.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for middle_block.1.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([1280, 1024]) from checkpoint, the shape in current model is torch.Size([1280, 768]).
	size mismatch for middle_block.1.proj_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1280, 1, 1]).

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.59it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.60it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.60it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.61it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:32<00:00,  2.46it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.58it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.60it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.60it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.60it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:32<00:00,  2.45it/s]
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:32<00:00,  2.61it/s]
```

**Comment by korronald** [comment]
additional info:
I also did test with the same seed, just to be sure:
https://imgur.com/a/GHgo7HJ
and this confirms, that Control does not work here.

Also I investigated this further, playing around with yaml files, as advised here: 
https://huggingface.co/thibaud/controlnet-sd21/discussions/37#644aa2b8cb45734dfd439fa3

but I ended up with RuntimeError: linear(): input and weight.T shapes cannot be multiplied (77x768 and 1024x320)

**Comment by deverelo** [comment]
also have this issue, macbook m1 max

**Comment by bjornlarssen** [comment]
Ha, I've been having this problem with TheLastBen's notebook and Stable-Diffusion-Art. ControlNet > OpenPose gives me this:

Loading model: control_v11p_sd15_openpose [cab727d4]
Loaded state_dict from [/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_openpose.pth]
Loading config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_openpose.yaml
ControlNet model control_v11p_sd15_openpose [cab727d4] loaded.
using mask as input
Loading preprocessor: none
preprocessor resolution = 512
Calling preprocessor none outside of cache.
100% 20/20 [00:08<00:00, 2.30it/s]

And no actual result.

**Comment by korronald** [comment]
> Ha, I've been having this problem with TheLastBen's notebook and Stable-Diffusion-Art on Colab Pro. ControlNet > OpenPose gives me this:
> 
> Loading model: control_v11p_sd15_openpose [cab727d4] Loaded state_dict from [/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_openpose.pth] Loading config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_openpose.yaml ControlNet model control_v11p_sd15_openpose [cab727d4] loaded. using mask as input Loading preprocessor: none preprocessor resolution = 512 Calling preprocessor none outside of cache. 100% 20/20 [00:08<00:00, 2.30it/s]
> 
> And no actual result.

Finaly it worked. Solution proposed here:
https://huggingface.co/thibaud/controlnet-sd21/discussions/37#644aa2b8cb45734dfd439fa3
worked for me, I just mixed up new yaml and models with old checkpoint. When I run it on checkpoint 21 it finally worked great.

**Comment by bjornlarssen** [comment]
> > Ha, I've been having this problem with TheLastBen's notebook and Stable-Diffusion-Art on Colab Pro. ControlNet > OpenPose gives me this:
> > Loading model: control_v11p_sd15_openpose [cab727d4] Loaded state_dict from [/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_openpose.pth] Loading config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_openpose.yaml ControlNet model control_v11p_sd15_openpose [cab727d4] loaded. using mask as input Loading preprocessor: none preprocessor resolution = 512 Calling preprocessor none outside of cache. 100% 20/20 [00:08<00:00, 2.30it/s]
> > And no actual result.
> 
> Finaly it worked. Solution proposed here: https://huggingface.co/thibaud/controlnet-sd21/discussions/37#644aa2b8cb45734dfd439fa3 worked for me, I just mixed up new yaml and models with old checkpoint. When I run it on checkpoint 21 it finally worked great.

Can I just ask checkpoint 21 of what? I am using a simplified version of the notebook, where only the models and extensions etc. get downloaded, so I don't have access to the yaml files, but I can install the whole thing on Colab if I want to, it will just take more time.

(I tried various commits of webui itself in the meantime, and as a result of my hard work I managed to break everything completely, I'm special like that ;) )
