### ISSUE TITLE
[Bug]: As soon as deforum uses controlnet, any preprocessor or model, there are a lot of errors on the console, it is not clear what the cause is and how to solve it. but deforum can output videos normally.

### ISSUE THREAD

**Issue by Shuiyixiu** [Mikubill/sd-webui-controlnet#1426]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

As soon as deforum uses controlnet, any preprocessor or model, there are a lot of errors on the console, it is not clear what the cause is and how to solve it. but deforum can output videos normally.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

As soon as deforum uses controlnet, any preprocessor or model, there are a lot of errors on the console, it is not clear what the cause is and how to solve it. but deforum can output videos normally.

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

no

### Console logs

```Shell
Error running process: E:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process: E:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process: E:\sd-webui-aki-v4\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 17 required positional arguments: 'loraratios', 'useblocks', 'xyzsetting', 'xtype', 'xmen', 'ytype', 'ymen', 'ztype', 'zmen', 'exmen', 'eymen', 'ecount', 'diffcol', 'thresh', 'revxy', 'elemental', and 'elemsets'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running before_process_batch: E:\sd-webui-aki-v4\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 426, in before_process_batch
    script.before_process_batch(p, *script_args, **kwargs)
TypeError: Script.before_process_batch() missing 17 required positional arguments: 'loraratios', 'useblocks', 'xyzsetting', 'xtype', 'xmen', 'ytype', 'ymen', 'ztype', 'zmen', 'exmen', 'eymen', 'ecount', 'diffcol', 'thresh', 'revxy', 'elemental', and 'elemsets'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process_batch: E:\sd-webui-aki-v4\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "E:\sd-webui-aki-v4\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 190, in process_batch
    if not args[0]:
IndexError: tuple index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running process_batch: E:\sd-webui-aki-v4\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
TypeError: Script.process_batch() missing 17 required positional arguments: 'loraratios', 'useblocks', 'xyzsetting', 'xtype', 'xmen', 'ytype', 'ymen', 'ztype', 'zmen', 'exmen', 'eymen', 'ecount', 'diffcol', 'thresh', 'revxy', 'elemental', and 'elemsets'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running postprocess_batch: E:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 453, in postprocess_batch
    script.postprocess_batch(p, *script_args, images=images, **kwargs)
TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running postprocess: E:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error running postprocess: E:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
```

**Comment by huchenlei** [comment]
Please follow steps in https://github.com/Mikubill/sd-webui-controlnet/issues/1153.

**Comment by 66ssoo88** [comment]
It's the same as the situation I encountered, but it doesn't affect the use. I don't understand how to solve the error reporting problem.
