### ISSUE TITLE
Colab: TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by R-N** [Mikubill/sd-webui-controlnet#146]
Google Colab uses Python 3.9, which isn't fully compatible with Python 3.10 hints.

```
Error calling: /content/nai/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py/ui
Traceback (most recent call last):
  File "/content/nai/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/content/nai/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 277, in ui
    def svgPreprocess(inputs) -> np.ndarray | _Image.Image | str | Dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Error calling: /content/nai/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py/ui
Traceback (most recent call last):
  File "/content/nai/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/content/nai/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 277, in ui
    def svgPreprocess(inputs) -> np.ndarray | _Image.Image | str | Dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/fa35459ff9030b4c8c2ec8b4ccc17c9028a5c2c3

**Comment by R-N** [comment]
That was really quick. Thank you
