### ISSUE TITLE
[Bug]: Txt2img Inpaint, "The size of tensor a (56) must match the size of tensor b (64) at non-singleton dimension 3"

### ISSUE THREAD

**Issue by ZeroCool22** [Mikubill/sd-webui-controlnet#1481]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I'm trying to inpaint with this method an image that's 512x704 and i always get this:

```
RuntimeError: The size of tensor a (56) must match the size of tensor b (64) at non-singleton dimension 3

Time taken: 1.31s

Torch active/reserved: 3459/4732 MiB, Sys VRAM: 6412/11264 MiB (56.92%)
```

https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/8d9baa98-f4f8-43f4-a103-aee8a224d4d7

And i'm not using an **Inpainting Model**, just a normal one.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Work.

### Commit where the problem happens

webui: 20ae71faa8ef035c31aa3a410b707d792c8203a3
controlnet: 7b707dc1

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --api --vae-path "F:\Stable-diffusion\vae-ft-mse-840000-ema-pruned.ckpt"

call webui.bat
```

### List of enabled extensions

![Screenshot_3](https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/bb8d2b5e-2244-405a-b815-36ef35c23aaa)

### Console logs

```Shell
venv "C:\Users\ZeroCool22\Desktop\Auto\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.0
Commit hash: 20ae71faa8ef035c31aa3a410b707d792c8203a3
Installing requirements
[Auto-Photoshop-SD] Attempting auto-update...
[Auto-Photoshop-SD] switch branch to extension branch.
checkout_result: Your branch is up to date with 'origin/master'.

[Auto-Photoshop-SD] Current Branch.
branch_result: * master

[Auto-Photoshop-SD] Fetch upstream.
fetch_result:
[Auto-Photoshop-SD] Pull upstream.
pull_result: Already up to date.



Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...


If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 gitpython-3.1.31 google-auth-oauthlib-0.4.6 transformers-4.26.1


Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Launching Web UI with arguments: --xformers --api --vae-path F:\Stable-diffusion\vae-ft-mse-840000-ema-pruned.ckpt
C:\Users\ZeroCool22\Desktop\Auto\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: llow is an invalid version and will not be supported in a future release
  warnings.warn(
python_server_full_path:  C:\Users\ZeroCool22\Desktop\Auto\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
ControlNet v1.1.204
ControlNet v1.1.204
Loading weights [5415fd85c7] from C:\Users\ZeroCool22\Desktop\Auto\models\Stable-diffusion\dreamshaper_5PrunedNovae.safetensors
Creating model from config: C:\Users\ZeroCool22\Desktop\Auto\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights from commandline argument: F:\Stable-diffusion\vae-ft-mse-840000-ema-pruned.ckpt
Textual inversion embeddings loaded(4): bad-hands-5, bad-image-v2-39000, bad_prompt_version2, EasyNegative
Textual inversion embeddings skipped(3): nartfixer, nfixer, nrealfixer
Model loaded in 3.2s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.5s, apply half(): 0.6s, load VAE: 0.2s, move model to device: 0.6s, load textual inversion embeddings: 0.8s).
Applying optimization: xformers... done.
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
CUDA SETUP: Loading binary C:\Users\ZeroCool22\Desktop\Auto\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 12.8s (import torch: 2.9s, import gradio: 0.7s, import ldm: 0.3s, other imports: 0.8s, load scripts: 5.4s, create ui: 2.3s, gradio launch: 0.1s).
Loading model: control_v11p_sd15_inpaint [ebff9138]
Loaded state_dict from [C:\Users\ZeroCool22\Desktop\Auto\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.pth]
Loading config: C:\Users\ZeroCool22\Desktop\Auto\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.yaml
ControlNet model control_v11p_sd15_inpaint [ebff9138] loaded.
using inpaint as input
Loading preprocessor: inpaint_only
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 704
raw_W = 512
target_H = 712
target_W = 512
estimation = 517.8181818181819
preprocessor resolution = 518
Calling preprocessor inpaint_only outside of cache.
                                  Data shape for DDIM sampling is (1, 4, 80, 56), eta 0.0
Running DDIM Sampling with 25 timesteps
DDIM Sampler:   0%|                                                                             | 0/25 [00:00<?, ?it/s]ControlNet used torch.float16 VAE to encode torch.Size([1, 4, 89, 64]).
DDIM Sampler:   0%|                                                                             | 0/25 [00:01<?, ?it/s]
Error completing request
Arguments: ('task(4qlwrupn5vrpocc)', '', '', [], 25, 19, False, False, 1, 1, 5, -1.0, -1.0, 0, 0, 0, False, 712, 512, True, 0.25, 2, 'None', 0, 0, 0, 0, '', '', [], 0, <controlnet.py.UiControlNetUnit object at 0x0000026624FAE3B0>, <controlnet.py.UiControlNetUnit object at 0x0000026624EDFD00>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, None, False, None, None, False, 50) {}
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "C:\Users\ZeroCool22\Desktop\Auto\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\processing.py", line 729, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "C:\Users\ZeroCool22\Desktop\Auto\extensions\sd-webui-controlnet\scripts\hook.py", line 291, in process_sample
    return process.sample_before_CN_hack(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\processing.py", line 977, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\sd_samplers_compvis.py", line 222, in sample
    samples_ddim = self.launch_sampling(steps, lambda: self.sampler.sample(S=steps, conditioning=conditioning, batch_size=int(x.shape[0]), shape=x[0].shape, verbose=False, unconditional_guidance_scale=p.cfg_scale, unconditional_conditioning=unconditional_conditioning, x_T=x, eta=self.eta)[0])
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\sd_samplers_compvis.py", line 51, in launch_sampling
    return func()
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\sd_samplers_compvis.py", line 222, in <lambda>
    samples_ddim = self.launch_sampling(steps, lambda: self.sampler.sample(S=steps, conditioning=conditioning, batch_size=int(x.shape[0]), shape=x[0].shape, verbose=False, unconditional_guidance_scale=p.cfg_scale, unconditional_conditioning=unconditional_conditioning, x_T=x, eta=self.eta)[0])
  File "C:\Users\ZeroCool22\Desktop\Auto\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddim.py", line 104, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "C:\Users\ZeroCool22\Desktop\Auto\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddim.py", line 164, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\sd_samplers_compvis.py", line 58, in p_sample_ddim_hook
    res = self.orig_p_sample_ddim(x_dec, cond, ts, *args, unconditional_conditioning=unconditional_conditioning, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddim.py", line 212, in p_sample_ddim
    model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\ZeroCool22\Desktop\Auto\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\ZeroCool22\Desktop\Auto\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\ZeroCool22\Desktop\Auto\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\extensions\sd-webui-controlnet\scripts\hook.py", line 587, in forward_webui
    return forward(*args, **kwargs)
  File "C:\Users\ZeroCool22\Desktop\Auto\extensions\sd-webui-controlnet\scripts\hook.py", line 573, in forward
    x0 = x0_prd * mask + x0_origin * (1 - mask)
RuntimeError: The size of tensor a (56) must match the size of tensor b (64) at non-singleton dimension 3
```

**Comment by 2blackbar** [comment]
use normal model like sd 1.5 and post again if it happens with it too

**Comment by ZeroCool22** [comment]
> use normal model like sd 1.5 and post again if it happens with it too

Same:


https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/74f95b84-c114-4747-ac73-cba98e2ab03e

And this time i tried a different resolution, same error.

**Comment by ZeroCool22** [comment]
Ok, i found where the problem/bug is, when you have this option checked, this bug appears:

![Screenshot_5](https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/eee0b32c-cbc4-4d40-aee0-0077374b279f)

It should work with this option enable too...

**Comment by gharmonica** [comment]
Same issue happening here, it's not a hires fix issue, as it still happens if Hires fix is disabled.

It only happens with Inpaint_only

**Comment by ZeroCool22** [comment]
> Same issue happening here, it's not a hires fix issue, as it still happens if Hires fix is disabled.
> 
> It only happens with Inpaint_only

No, it's **only** when the setting option Fix is enabled, you can see it very clearly in this video, _(with and without the option enabled)_:


https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/4bc12442-095d-4b8b-b665-2f18852f2351

At least in my case.

**Comment by ZeroCool22** [comment]
> > Same issue happening here, it's not a hires fix issue, as it still happens if Hires fix is disabled.
> > It only happens with Inpaint_only
> 
> No, it's **only** when the setting option Fix is enabled, you can see it very clearly in this video, _(with and without the option enabled)_:
> 2023-05-31.20-57-42.mp4
> 
> At least in my case.

@huchenlei when we can expect a fix for this?

**Comment by huchenlei** [comment]
It seems to be a compability setting to go back to legacy behaviour in A1111. Is there any reason why you want to use the legacy behaviour for hires?

```python
options_templates.update(options_section(('compatibility', "Compatibility"), {
    "use_old_emphasis_implementation": OptionInfo(False, "Use old emphasis implementation. Can be useful to reproduce old seeds."),
    "use_old_karras_scheduler_sigmas": OptionInfo(False, "Use old karras scheduler sigmas (0.1 to 10)."),
    "use_old_hires_fix_width_height": OptionInfo(False, "For hires fix, use width/height sliders to set final resolution rather than first pass (disables Upscale by, Resize width/height to)."),
}))
```

**Comment by huchenlei** [comment]
It shows that the line with exception is last modified by @lllyasviel in #1441 . Assigning to him for triage.

**Comment by ZeroCool22** [comment]
>Is there any reason why you want to use the legacy behaviour for hires?

My answer to that:

https://www.youtube.com/watch?v=yvOEMtfm-oY

❌For hires fix Setting OFF = Duplicate subjects.
✅For hires fix Setting ON= No Duplicate subjects.

You can test it by yourself using the same settings i show in the video.

**Comment by huchenlei** [comment]
> > Is there any reason why you want to use the legacy behaviour for hires?
> 
> My answer to that:
> 
> https://www.youtube.com/watch?v=yvOEMtfm-oY
> 
> ❌For hires fix Setting OFF = Duplicate subjects. ✅For hires fix Setting ON= No Duplicate subjects.
> 
> You can test it by yourself using the same settings i show in the video.

From the video I can tell:
With setting off: 1024x1024 -> 1024x1024
Essentially you are generating a single 1024x1024 image with the SD1.5 model trained on 512x512 images, so likely to get duplicated objects as SD don't know what to put in the empty space.

With setting on: 512x512 -> 1024x1024
You generate a 512x512 image and then hires fix it to 1024x1024. It is similar to SD upscale. Because the initial image is generated in the same size as SD model is trained on, there will not be duplicated objects.

What you can do is reduce the canvas size to 512x512 and set upscale ratio to 2 with settings off to get the same effect as showed when setting is on in the video.

**Comment by ZeroCool22** [comment]
> What you can do is reduce the canvas size to 512x512 and set upscale ratio to 2 with settings off to get the same effect as showed when setting is on in the video.

But it takes a lot more time to generate that way...😞


But thanks anyway, i understand now why it happens.

**Comment by trxsudo** [comment]
I have the same issue when try to use inpaint+ lama
but unchecking the hires option doesnt help
how may i solve this?

**Comment by bugsebe** [comment]
self.weight += updown
    RuntimeError: The size of tensor a (768) must match the size of tensor b (2048) at non-singleton dimension 1
same issue on SDXL 
Gosh I'm so glad the dev teem closes issues WHEN THEY AREN"T FUCKING FIXED!! fuck you. pussies.
