### ISSUE TITLE
ControlNet not working or activating

### ISSUE THREAD

**Issue by mastajooh** [Mikubill/sd-webui-controlnet#15]
Hello,

Just got back from work and been hear the craze over this. I installed the extension, updated my WebUI, got everything set up, appiled the highres fix, but whenever I generate an image with ControlNet enabled, I get hit with this error. 

##
Error running process: C:\Users\Joseph\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Joseph\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\Users\Joseph\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 231, in process
    restore_networks()
  File "C:\Users\Joseph\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 217, in restore_networks
    self.latest_network.restore(unet)
  File "C:\Users\Joseph\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 111, in restore
    model.forward = model._original_forward
  File "C:\Users\Joseph\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'UNetModel' object has no attribute '_original_forward'
##
Tried to figure out what's going on, but this is something far beyond my knowledge. Any help would be appreciated. Thanks.

**Comment by mastajooh** [comment]
Still getting the same error. Updated the extension too.

**Comment by Mikubill** [comment]
Hmm no idea, could you share the full output when this error occurred, or the input args of process func?

**Comment by mastajooh** [comment]
Going to reinstall it from scratch and will report back if it still happens.

**Comment by mastajooh** [comment]
Ok I did a clean reinstall of the extension, I think its working, but now I cant get rid of the "Sizes of tensors must match except in dimension 1. Expected size 30 but got size 29 for tensor number 1 in the list." I also applied the highres fix patch, but that did nothing. 
and if this helps.
##
 File "C:\Users\Joseph\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Joseph\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\Joseph\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\Joseph\stable-diffusion-webui\modules\processing.py", line 628, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Users\Joseph\stable-diffusion-webui\modules\processing.py", line 828, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Users\Joseph\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 323, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Users\Joseph\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 221, in launch_sampling
    return func()
  File "C:\Users\Joseph\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 323, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Users\Joseph\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\Joseph\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 135, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
  File "C:\Users\Joseph\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\Joseph\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\Joseph\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\Joseph\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Joseph\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 97, in forward2
    h = h.type(x.dtype)
  File "C:\Users\Joseph\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 83, in forward
    h = module(h, emb, context)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 30 but got size 29 for tensor number 1 in the list.
##

**Comment by mastajooh** [comment]
Okay. I fixed it. Just had to use a filesize divisible by 64. So a clean install of the extension was my fix. Thanks for trying to help.
