### ISSUE TITLE
[Bug]: Can't select model on "Seg" section.

### ISSUE THREAD

**Issue by pakresi** [Mikubill/sd-webui-controlnet#1505]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Can't select model on "Seg" section. I know its already downloaded model when i press preview button. But none of them selectable. **Preview working but when creating Image its raising error:**

  raise RuntimeError(f"You have not selected any ControlNet Model.")
RuntimeError: You have not selected any ControlNet Model.

like this
<img width="889" alt="Screenshot 2023-06-02 at 16 12 53" src="https://github.com/Mikubill/sd-webui-controlnet/assets/133514291/6c59cdbe-61ca-445e-92d7-145cfe26870f">

None of them selectable:
<img width="746" alt="Screenshot 2023-06-02 at 16 12 26" src="https://github.com/Mikubill/sd-webui-controlnet/assets/133514291/95be0b44-ae95-4bd5-8b45-1669fde23ec0">

### Steps to reproduce the problem

1. Select "Seg"
2. Press Preview button and its downloading models
3. When you enable any of Seg models its :

raise RuntimeError(f"You have not selected any ControlNet Model.")
RuntimeError: You have not selected any ControlNet Model.

models not selectable but just working for preview.

### What should have happened?

Normally it must select automatically

### Commit where the problem happens

webui: v1.3.0
controlnet: v1.1.204

### Command Line Arguments

```Shell
./webui.sh --listen --enable-insecure-extension-access --xformers --opt-channelslast
```

### List of enabled extensions

standart

### Console logs

```Shell
preprocessor resolution = 512
Error running process: /home/banias/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/home/banias/stable-diffusion-webui/modules/scripts.py", line 451, in process
    script.process(p, *script_args)
  File "/home/banias/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1075, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/home/banias/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 735, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/home/banias/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 744, in build_control_model
    raise RuntimeError(f"You have not selected any ControlNet Model.")
RuntimeError: You have not selected any ControlNet Model.
```

**Comment by lllyasviel** [comment]
https://huggingface.co/lllyasviel/ControlNet-v1-1/blob/main/control_v11p_sd15_seg.pth

**Comment by pakresi** [comment]
i am sure about there is a problem with seg. 
still not working

**Comment by ELL0-ELL0** [comment]
im having the same problem on Lineart, 


Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 676, in process
    model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 260, in load_control_model
    model_net = Script.build_control_model(p, unet, model, lowvram)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 270, in build_control_model
    raise RuntimeError(f"You have not selected any ControlNet Model.")
RuntimeError: You have not selected any ControlNet Model.

Model dropdown is empty,
