### ISSUE TITLE
[Bug]: The reference functionality of the control plugin in the stable diffusion webui version, version: v1.3.1-RC-148-g3e995778, is experiencing an error.

### ISSUE THREAD

**Issue by jackchen2025** [Mikubill/sd-webui-controlnet#1506]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The reference functionality of the control plugin in the stable diffusion webui version, version: v1.3.1-RC-148-g3e995778, is experiencing an error.
![屏幕截图 2023-06-02 220903](https://github.com/Mikubill/sd-webui-controlnet/assets/36725996/32ed585a-dcd4-4494-8854-65b949041a8d)

### Steps to reproduce the problem

1. Set the startup parameter in webui-user.bat of the stable diffusion webui to COMMANDLINE_ARGS=--xformers --medvram --no-half-vae, noting that --medvram is a possible cause of the issue.
2. Enable the reference functionality of the control plugin in the stable diffusion webui.
3. Click on "generate" to generate the images.
4. An error occurs.

### What should have happened?

The Preprocessor reference feature should work correctly in the stable diffusion webui version v1.3.1-RC-148-g3e995778.

### Commit where the problem happens

webui: version: [v1.3.1-RC-148-g3e995778](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3e995778fc525ff15d56c1472c1a1bc701019ec5)  •  python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.32.0  •  checkpoint: [16736832bd](https://google.com/search?q=16736832bd01c2e11a493672b45e956bff27e7a6952192930d7e3928e062ce8e)

controlnet: sd-webui-controlnet
https://github.com/Mikubill/sd-webui-controlnet | main | e78d486c | Fri Jun 2 03:07:14 2023 | unknown

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --medvram --no-half-vae
```

### List of enabled extensions

![屏幕截图 2023-06-02 220704](https://github.com/Mikubill/sd-webui-controlnet/assets/36725996/6222d938-7fcb-477e-946b-e78c80fa844c)

### Console logs

```Shell
Loading model: control_v11p_sd15_lineart [43d4be0d]
Loaded state_dict from [D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_lineart.pth]
Loading config: D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_lineart.yaml
ControlNet model control_v11p_sd15_lineart [43d4be0d] loaded.
Loading preprocessor: lineart_anime_denoise
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 1152
raw_W = 768
target_H = 800
target_W = 600
estimation = 600.0
preprocessor resolution = 600
Calling preprocessor lineart_anime_denoise outside of cache.
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:24<00:00,  1.63it/s]
SwinIR tiles: 100%|████████████████████████████████████████████████████████████████████| 20/20 [00:17<00:00,  1.17it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [02:00<00:00,  3.00s/it]
Total progress: 160it [10:02,  3.77s/it]
Loading preprocessor: reference_only/it]
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 1152
raw_W = 768
target_H = 800
target_W = 600
estimation = 600.0
preprocessor resolution = 600
Calling preprocessor reference_only outside of cache.
  0%|                                                                                           | 0/40 [00:00<?, ?it/s]ControlNet used torch.float32 VAE to encode torch.Size([1, 4, 100, 75]).                         | 0/40 [00:00<?, ?it/s]
  0%|                                                                                           | 0/40 [00:01<?, ?it/s]
*** Error completing request
*** Arguments: ('task(zrtwplm1xw4ndi4)', '1girl, clothes lift, mouth hold, underboob, smile, underboob, small breasts, against wall, tank top, hand on own navel, short hair, side ponytail, black hair, red eyes, forehead, blunt bangs, large breasts, outdoors, peace sign<lora:ClothesInMouth:1>', '(low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), bad composition, inaccurate eyes, extra digit, fewer digits, (extra arms:1.2)', [], 40, 16, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 800, 600, True, 0.5, 2, 'SwinIR_4x', 0, 0, 0, 0, '', '', [], 0, <scripts.ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FEAE818F40>, <scripts.ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FECB5210F0>, <scripts.ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FECB521720>, <scripts.ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FECB522DA0>, <scripts.ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FEAE818D30>, <scripts.ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FEAE81A050>, <scripts.ui.controlnet_ui_group.UiControlNetUnit object at 0x000001FEAE81A8C0>, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5\nface:1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "D:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "D:\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\txt2img.py", line 57, in txt2img
        processed = processing.process_images(p)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 613, in process_images
        res = process_images_inner(p)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 733, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 293, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 981, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 433, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 275, in launch_sampling
        return func()
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 433, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 161, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict([cond_in[a:b]], image_cond_in[a:b]))
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
        result = forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 617, in forward_webui
        return forward(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 494, in forward
        outer.original_forward(
      File "D:\stable-diffusion\stable-diffusion-webui\modules\sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 789, in forward
        emb = self.time_embed(t_emb)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
        input = module(input)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stable-diffusion\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 400, in lora_Linear_forward
        return torch.nn.Linear_forward_before_lora(self, input)
      File "D:\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

---
```

**Comment by lllyasviel** [comment]
Fixed in 1.1.121. Feel free to reopen if not fixed
