### ISSUE TITLE
txt2img tests silently broke

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#1541]
See this tryjob:
https://github.com/Mikubill/sd-webui-controlnet/actions/runs/5165879820/jobs/9305660056

I changed `print` to `logger.error` and the build fails. 

Previously we were only checking `'error'` in `stderr`, while we were outputing our own error message to `stdout`. 

```
Traceback (most recent call last):
  File "/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/tests/web_api/txt2img_test.py", line 130, in test_call_with_preprocessors
    self.assert_status_ok(f'Running preprocessor module: {module}')
  File "/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/tests/web_api/txt2img_test.py", line 77, in assert_status_ok
    self.assertFalse('error' in stderr, "Errors in stderr: \n" + stderr)

2023-06-03 22:22:44,537 - controlnet - info - loading model: control_canny-fp16 [e3fe7712]
2023-06-03 22:22:44,591 - controlnet - info - loaded state_dict from [/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_canny-fp16.safetensors]
2023-06-03 22:22:44,593 - controlnet - error - error: controlnet cannot find model config [/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_canny-fp16.yaml] 
error: controlnet will use a wrong config [/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/models/cldm_v15.yaml] to load your model. 
error: the wrong config may not match your model. the generated results can be bad. 
error: you are using a controlnet model [control_canny-fp16] without correct yaml config file. 
error: the performance of this model may be worse than your expectation. 
error: if this model cannot get good results, the reason is that you do not have a yaml file for the model. 
solution: please download yaml file, or ask your model provider to provide [/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_canny-fp16.yaml] for you to download.
hint: you can take a look at [/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/models] to find many existing yaml files.
```

@lllyasviel Any idea how to fix this?

**Comment by huchenlei** [comment]
https://github.com/Mikubill/sd-webui-controlnet/blob/d8551e447d8718e15b8ff5de04036d3fd1b3c5ce/.github/workflows/tests.yml#L35

Changing `control_canny-fp16.safetensors` to something else?

**Comment by lllyasviel** [comment]
common problem of github. wait one day or so

**Comment by lllyasviel** [comment]
oh wait - you changed stderr? then perhaps we do change control_canny-fp16.safetensors to whatever

**Comment by lllyasviel** [comment]
https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/blob/main/control_v11p_sd15_canny_fp16.safetensors

**Comment by huchenlei** [comment]
Header too large?
https://github.com/Mikubill/sd-webui-controlnet/actions/runs/5166659665/jobs/9307103236 

```
2023-06-04 02:19:54,100 - controlnet - info - loading model: control_v11p_sd15_canny_fp16 [e3b0c442]
error running process: /home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
traceback (most recent call last):
  file "/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  file "/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 674, in process
    model_net = script.load_control_model(p, unet, unit.model, unit.low_vram)
  file "/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 260, in load_control_model
    model_net = script.build_control_model(p, unet, model, lowvram)
  file "/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 288, in build_control_model
    state_dict = load_state_dict(model_path)
  file "/home/runner/work/sd-webui-controlnet/sd-webui-controlnet/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 17, in load_state_dict
    state_dict = safetensors.torch.load_file(ckpt_path, device=location)
  file "/opt/hostedtoolcache/python/3.10.6/x64/lib/python3.10/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.safetensorerror: error while deserializing header: headertoolarge
```
