### ISSUE TITLE
[Bug]: Problem with installing the controlnet. Error loading script: controlnet.py

### ISSUE THREAD

**Issue by SergBaskakov** [Mikubill/sd-webui-controlnet#1543]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After installing the controlnet, an error appears. The no controlnet does not appear in the interface.

```
2023-06-04 16:17:23,752 - ControlNet - INFO - ControlNet v1.1.215
Error loading script: controlnet.py
Traceback (most recent call last):
  File "C:\Program Files\Stable\SD_TUTOROGRAD_v3-2\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Program Files\Stable\SD_TUTOROGRAD_v3-2\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Program Files\Stable\SD_TUTOROGRAD_v3-2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 24, in <module>
    from scripts.controlnet_ui.controlnet_ui_group import ControlNetUiGroup, UiControlNetUnit
  File "C:\Program Files\Stable\SD_TUTOROGRAD_v3-2\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 22, in <module>
    from modules.ui_components import FormRow
ModuleNotFoundError: No module named 'modules.ui_components'

2023-06-04 16:17:23,778 - ControlNet - INFO - ControlNet v1.1.215
LatentDiffusion: Running in eps-prediction mode
```

**Comment by huchenlei** [comment]
What version is a1111 are you using? FormGroup is part of a1111.

**Comment by SergBaskakov** [comment]
I use automatic 1111, but I don't know where the version number is indicated in it. Here is the commit hash: 8504db51704d238cc7616f6bf59eb049d3eb101d

**Comment by SergBaskakov** [comment]
> What version of a1111 are you using? FormRow is part of a1111.

I use automatic 1111, but I don't know where the version number is indicated in it. Here is the commit hash: 8504db51704d238cc7616f6bf59eb049d3eb101d

**Comment by huchenlei** [comment]
Your A1111 version is too old:

```
commit 8504db51704d238cc7616f6bf59eb049d3eb101d (HEAD)
Author: AUTOMATIC <16777216c@gmail.com>
Date:   Sun Dec 4 01:04:24 2022 +0300
```

Please update to the newest version. Thanks!

**Comment by SergBaskakov** [comment]
Okay, thanks, I'll try

**Comment by SergBaskakov** [comment]
It seems to have really helped, thank you very much!
