### ISSUE TITLE
[Bug]: FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Sirlansolot** [Mikubill/sd-webui-controlnet#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Every time I try to use control net with reference I get the error: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\usernamehere\\AppData\\Local\\Temp\\gradio\\tmpbczkmpie.png and the preview image disappears from the window. It still outputs the file in the folder but this makes workflow slow.

### Steps to reproduce the problem

drop image intro controlnet, set preprocessor to reference_adain, select reference, select pixel perfect, click generate in txt2img. It will generate the image and the preview and as soon as it's done it will disappear with the error 

### What should have happened?

jesus how many *** questions do we need when they don't apply?

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
medvram and xformers
```

### List of enabled extensions

controlnet and ultimate-upscale-for-automatic1111

### Console logs

```Shell
2023-06-05 15:11:50,470 - ControlNet - INFO - Loading preprocessor: reference_adain
2023-06-05 15:11:50,470 - ControlNet - INFO - Pixel Perfect Computation:
2023-06-05 15:11:50,472 - ControlNet - INFO - resize_mode = ResizeMode.INNER_FIT
2023-06-05 15:11:50,472 - ControlNet - INFO - raw_H = 512
2023-06-05 15:11:50,473 - ControlNet - INFO - raw_W = 512
2023-06-05 15:11:50,473 - ControlNet - INFO - target_H = 512
2023-06-05 15:11:50,474 - ControlNet - INFO - target_W = 512
2023-06-05 15:11:50,475 - ControlNet - INFO - estimation = 512.0
2023-06-05 15:11:50,475 - ControlNet - INFO - preprocessor resolution = 512
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]ControlNet used torch.float16 VAE to encode torch.Size([1, 4, 64, 64]).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.24it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.66it/s]
Traceback (most recent call last):█████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.93it/s]
  File "C:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\A1111\stable-diffusion-webui\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\usernamehere\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "C:\Users\usernamehere\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\usernamehere\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\usernamehere\\AppData\\Local\\Temp\\gradio\\tmpbczkmpie.png
```

**Comment by Sirlansolot** [comment]
btw wasn't swearing, I think it's ridiculous github has so many asterisk type entries, to the point you're just repeating yourself over and over again. I am sure it dissuades people from submitting bugs.

**Comment by lllyasviel** [comment]
https://github.com/Mikubill/sd-webui-controlnet/issues/1563

**Comment by lllyasviel** [comment]
closed as duplicated.
