### ISSUE TITLE
[Bug]: img2img + ControlNet v1.1.220 no longer works with 3GB RAM (tried canny)

### ISSUE THREAD

**Issue by mikkorantalainen** [Mikubill/sd-webui-controlnet#1593]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I'm running webui + ControlNet on Ubuntu 20.04 with GTX 1060 3 GB. This setup used to work with img2img + ControlNet + canny with 512x512 images two weeks ago.

However, after updating to latest ControlNet v1.1.220 this setup cannot be used anymore.

### Steps to reproduce the problem

1. Start with Ubuntu 20.04 and GTX 1060 3 GB
2. Start webui + open http://127.0.0.1:7860 in a browser (I used Chrome but that doesn't seem to matter for this issue)
3. Go to img2img tab and drag-and-drop some 512x512 image as the source
4. Check "enable" for ControlNet and press canny (assuming you've already loaded the canny model)
5. Press Generate (it doesn't matter if the prompt is empty or not)

### What should have happened?

Stable Diffusion should generate the image in maybe 15 seconds, just like a couple of weeks ago I last used this before I installed all latest updates.

### Commit where the problem happens

webui: tried two versions: 89f9faa63388756314e8a1d96cf86bf5e0663045 and baf6946e06249c5af9851c60171692c44ef633e0
controlnet: 8004669c (Fri Jun 2 18:28:02 2023)

### Command Line Arguments

```Shell
--lowvram --xformers --always-batch-cond-uncond --opt-sub-quad-attention --opt-split-attention-v1 --opt-sdp-no-mem-attention --max-batch-count 16 --autolaunch --theme dark
```

### List of enabled extensions

- ultimate-upscale-for-automatic1111 (756bb505)
- LDSR
- Lora
- ScuNET
- SwinIR
- prompt-bracket-checker

### Console logs

```Shell
$ ./webui.sh 

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on XXXX user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc.so.4
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: c9fe758757e022f05ca5a53fa8fac28889e4f1cf...
Installing requirements

Launching Web UI with arguments: --lowvram --xformers --always-batch-cond-uncond --opt-sub-quad-attention --opt-split-attention-v1 --opt-sdp-no-mem-attention --max-batch-count 16 --autolaunch --theme dark
2023-06-08 20:06:13.109961: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
ControlNet v1.1.211
ControlNet v1.1.211
Loading weights [6ce0161689] from /home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: /home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Create LRU cache (max_size=16) for preprocessor results.
Startup time: 15.5s (import torch: 4.4s, import gradio: 1.3s, import ldm: 1.6s, other imports: 3.6s, setup codeformer: 0.3s, load scripts: 1.6s, create ui: 0.5s, gradio launch: 2.1s).
Applying optimization: xformers... done.
Textual inversion embeddings loaded(0): 
Model loaded in 20.3s (load weights from disk: 1.7s, create model: 2.3s, apply weights to model: 12.7s, apply half(): 3.6s).
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:29<00:00,  1.48s/it]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.36s/it]
Loading model: control_v11p_sd15_canny [d14c016b]███████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.34s/it]
Loaded state_dict from [/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_canny.pth]
Loading config: /home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_canny.yaml
ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
Loading preprocessor: canny
Pixel Perfect Mode Enabled.
resize_mode = ResizeMode.INNER_FIT
raw_H = 512
raw_W = 512
target_H = 512
target_W = 512
estimation = 512.0
preprocessor resolution = 512
Calling preprocessor canny outside of cache.
Error completing request
Arguments: ('task(ywno8mjpndw7lld)', 0, 'plastic ducks', '', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x7FEBC15186A0>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 0, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7febbdb14f10>, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/img2img.py", line 178, in img2img
    processed = process_images(p)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/processing.py", line 610, in process_images
    res = process_images_inner(p)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/processing.py", line 670, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/processing.py", line 1230, in init
    self.init_latent = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image))
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/modules/lowvram.py", line 48, in first_stage_model_encode_wrap
    return first_stage_model_encode(x)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/model.py", line 523, in forward
    hs = [self.conv_in(x)]
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 415, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/XXXX/dev/stable-diffusion-webui/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 2.94 GiB total capacity; 873.65 MiB already allocated; 65.06 MiB free; 902.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Additional information

May be related to issue #1569

Based on my backup files, I think sd-webui-controlnet version 2514a460ab9e0c6db38033aed29b12c94d5f1964 used to work correctly with GTX 1060 3 GB RAM using the same GPU drivers (nvidia-driver-530).

**Comment by huchenlei** [comment]
Since you already know a good version and a bad version, can you use [`git bisect`](https://git-scm.com/docs/git-bisect) to find the culprit? 

We don't have the exact hardware setup to reproduce the issue, so need to do this to find the culprit commit. Once the culprit is identified, we can decide what to do with it.

**Comment by lllyasviel** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11063
