### ISSUE TITLE
[Bug]: Getting error on v

### ISSUE THREAD

**Issue by Thawneflash** [Mikubill/sd-webui-controlnet#1596]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

<img width="943" alt="22211" src="https://github.com/Mikubill/sd-webui-controlnet/assets/132301431/311cb9c4-22b1-4135-b754-d5ef48622110">

### Steps to reproduce the problem

1. Just start generating with inpaint+llama

### What should have happened?

should work properly

### Commit where the problem happens

web ui: v1.3.0
Controlnet: v1.1.221

### Command Line Arguments

```Shell
--xformers --disable-nan-check --disable-safe-unpickle
```

### List of enabled extensions

<img width="1122" alt="2343" src="https://github.com/Mikubill/sd-webui-controlnet/assets/132301431/f4f34fcb-f69c-43d6-a648-a37f44fb87b9">

### Console logs

```Shell
Creating model from config: C:\Git\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: sdp... done.
Textual inversion embeddings loaded(5): bad-hands-5, badhandv4, easynegative, EasyNegativeV2, lr
Model loaded in 6.5s (load weights from disk: 1.2s, create model: 1.0s, apply weights to model: 1.4s, apply half(): 0.8s, move model to device: 0.7s, load textual inversion embeddings: 1.3s).
2023-06-08 17:49:38,477 - ControlNet - INFO - Preview Resolution = 512
2023-06-08 17:49:48,833 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "C:\Git\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Git\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Git\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Git\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Git\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Git\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 632, in run_annotator
    result, is_image = preprocessor(
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 485, in lama_inpaint
    from annotator.lama import LamaInpainting
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 12, in <module>
    from annotator.lama.saicinpainting.training.trainers import load_checkpoint
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\trainers\__init__.py", line 3, in <module>
    from annotator.lama.saicinpainting.training.trainers.default import DefaultInpaintingTrainingModule
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\trainers\default.py", line 7, in <module>
    from annotator.lama.saicinpainting.training.data.datasets import make_constant_area_crop_params
  File "C:\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\data\datasets.py", line 6, in <module>
    import albumentations as A
ModuleNotFoundError: No module named 'albumentations'
```

**Comment by lllyasviel** [comment]
fixed in 1.1.222
