### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'model'(openpose)

### ISSUE THREAD

**Issue by vxkj1211** [Mikubill/sd-webui-controlnet#1606]
![截图_20230610171730](https://github.com/Mikubill/sd-webui-controlnet/assets/12245156/327561c9-a79b-4b68-915a-598d52fd90f7)
023-06-10 17:30:35,171 - ControlNet - INFO - Preview Resolution = 512
2023-06-10 17:30:38,492 - ControlNet - INFO - Preview Resolution = 512
2023-06-10 17:31:10,246 - ControlNet - INFO - Pixel Perfect Computation:
2023-06-10 17:31:10,246 - ControlNet - INFO - resize_mode = ResizeMode.INNER_FIT
2023-06-10 17:31:10,246 - ControlNet - INFO - raw_H = 912
2023-06-10 17:31:10,246 - ControlNet - INFO - raw_W = 512
2023-06-10 17:31:10,246 - ControlNet - INFO - target_H = 512
2023-06-10 17:31:10,246 - ControlNet - INFO - target_W = 512
2023-06-10 17:31:10,247 - ControlNet - INFO - estimation = 512.0
2023-06-10 17:31:10,247 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4.1\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4.1\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 632, in run_annotator
    result, is_image = preprocessor(
  File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
    return cached_func(*args, **kwargs)
  File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\processor.py", line 251, in run_model
    return remove_pad(self.model_openpose(
  File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 324, in __call__
    poses = self.detect_poses(oriImg, include_hand, include_face)
  File "D:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 272, in detect_poses
    self.face_estimation.model.to(self.device)
AttributeError: 'NoneType' object has no attribute 'model'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by lllyasviel** [comment]
looks like file corruption. consider delete and download preprocessors again
