### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Patchesaa** [Mikubill/sd-webui-controlnet#1624]
Need some help with this, I'm not sure what to do. The reference and depth control types are working for me, but I get this error for every other one.

**Command line args**:
"--port 3000 --xformers --listen --enable-insecure-extension-access --precision full --no-half --no-half-vae --no-gradio-queue --update-all-extensions"

**Extensions**: 
openpose-editor, sd-webui-controlnet, sd-webui-openpose-editor

**Error**:
Error running process: /workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/workspace/stable-diffusion-webui/modules/scripts.py", line 451, in process
    script.process(p, *script_args)
  File "/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 686, in process
    model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 268, in load_control_model
    model_net = Script.build_control_model(p, unet, model, lowvram)
  File "/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 296, in build_control_model
    state_dict = load_state_dict(model_path)
  File "/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 19, in load_state_dict
    state_dict = get_state_dict(
  File "/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 28, in get_state_dict
    return d.get("state_dict", d)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by kopyl** [comment]
@Patchesaa how did you solve it?
