### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by mikecastrodemaria** [Mikubill/sd-webui-controlnet#1641]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

the extension crash and not start to render

### Steps to reproduce the problem

1. do many rendrer after 3 to 6, you have this message in the consol

### What should have happened?

In normal case the render start

### Commit where the problem happens

webui:   python: 3.10.6  •  torch: 2.0.1  •  xformers: N/A  •  gradio: 3.23.0  •  commit: 955df775  •  checkpoint: 9aba26abdf
controlnet:  v1.1.224
Python 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]
Commit hash: 955df7751eef11bb7697e2d77f6b8a6226b21e13

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
./webui.sh --skip-torch-cuda-test --skip-version-check --no-half --disable-safe-unpickle
```

### List of enabled extensions

Config-Presets, a1111-sd-webui-lycoris, adetailer, openpose-editor, sd-webui-ar, sd-webui-controlnet, stable-diffusion-webui-pixelization, stable-diffusion-webui-two-shot, ultimate-upscale-for-automatic1111, LDSR 	built-in, Lora 	built-in, ScuNET 	built-in ,SwinIR 	built-in , prompt-bracket-checker 	built-in

### Console logs

```Shell
Error completing request
Arguments: ('task(eqau6qcylmqol3u)', 'a painting of a (woman cry:1.2) with a red dress and flowers in her hair and a red dress, Edwin Georgi, highly detailed digital painting, a digital painting, photorealism', '', [], 25, 0, True, False, 1, 4, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 32, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 32, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x2f3b58190>, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, False, 50) {}
Traceback (most recent call last):
  File ".....xxx...../modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File ".....xxx...../modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File ".....xxx...../modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File ".....xxx...../modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File ".....xxx...../extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File ".....xxx...../modules/processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File ".....xxx...../extensions/sd-webui-controlnet/scripts/hook.py", line 350, in process_sample
    return process.sample_before_CN_hack(*args, **kwargs)
  File ".....xxx...../modules/processing.py", line 852, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File ".....xxx...../modules/sd_samplers_kdiffusion.py", line 351, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File ".....xxx...../modules/sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File ".....xxx...../modules/sd_samplers_kdiffusion.py", line 351, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File ".....xxx...../sd_venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File ".....xxx...../repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File ".....xxx...../sd_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File ".....xxx...../modules/sd_samplers_kdiffusion.py", line 119, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File ".....xxx...../sd_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File ".....xxx...../repositories/k-diffusion/k_diffusion/external.py", line 114, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File ".....xxx...../repositories/k-diffusion/k_diffusion/external.py", line 140, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File ".....xxx...../modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File ".....xxx...../modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File ".....xxx...../repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File ".....xxx...../sd_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File ".....xxx...../repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File ".....xxx...../sd_venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File ".....xxx...../extensions/sd-webui-controlnet/scripts/hook.py", line 661, in forward_webui
    return forward(*args, **kwargs)
  File ".....xxx...../extensions/sd-webui-controlnet/scripts/hook.py", line 423, in forward
    param.control_model.to(devices.get_device_for("controlnet"))
```

**Comment by huchenlei** [comment]
Cannot reproduce.
