### ISSUE TITLE
[Bug]: AttributeError: 'int' object has no attribute 'enabled'；TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by Defeng11** [Mikubill/sd-webui-controlnet#1646]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

使用该扩展时，如下面图片所展示，勾选之后，无论是txt2img或者是img2img都会出现“TypeError: 'bool' object is not subscriptable”，“AttributeError: 'int' object has no attribute 'enabled'”

When using this extension, as shown in the picture below, after checking, "TypeError: 'bool' object is not subscriptable" and "AttributeError: 'int' object has no attribute 'enabled'" will appear whether it is txt2img or img2img

### Steps to reproduce the problem

none

### What should have happened?

none

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --api

call webui.bat
```

### List of enabled extensions

![微信截图_20230615162251](https://github.com/Mikubill/sd-webui-controlnet/assets/128026631/534ee8d1-2fac-47fc-91eb-9668bd3f3383)
![微信截图_20230615161948](https://github.com/Mikubill/sd-webui-controlnet/assets/128026631/d15588e0-4e60-4276-b7ab-551ae459d871)

### Console logs

```Shell
2023-06-15 16:19:11,467 - ControlNet - INFO - Pixel Perfect Computation:
2023-06-15 16:19:11,467 - ControlNet - INFO - resize_mode = ResizeMode.INNER_FIT
2023-06-15 16:19:11,467 - ControlNet - INFO - raw_H = 1280
2023-06-15 16:19:11,467 - ControlNet - INFO - raw_W = 1280
2023-06-15 16:19:11,467 - ControlNet - INFO - target_H = 512
2023-06-15 16:19:11,467 - ControlNet - INFO - target_W = 512
2023-06-15 16:19:11,467 - ControlNet - INFO - estimation = 512.0
2023-06-15 16:19:11,467 - ControlNet - INFO - Preview Resolution = 512
Error running process: D:\SDweinew\extensions\sd-webui-segment-anything\scripts\sam.py
Traceback (most recent call last):
  File "D:\SDweinew\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "D:\SDweinew\extensions\sd-webui-segment-anything\scripts\sam.py", line 786, in process
    process_unit.set_process_attributes(p)
  File "D:\SDweinew\extensions\sd-webui-segment-anything\scripts\process_params.py", line 99, in set_process_attributes
    inpaint_image, inpaint_mask = self.sam_inpaint_unit.get_input_and_mask(inpaint_mask_blur)
  File "D:\SDweinew\extensions\sd-webui-segment-anything\scripts\process_params.py", line 45, in get_input_and_mask
    mask = Image.open(self.output_mask_gallery[self.output_chosen_mask + 3]['name']).convert('L')
TypeError: 'bool' object is not subscriptable

Error running process: D:\SDweinew\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\SDweinew\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "D:\SDweinew\extensions\sd-webui-controlnet\scripts\controlnet.py", line 653, in process
    self.enabled_units = Script.get_enabled_units(p)
  File "D:\SDweinew\extensions\sd-webui-controlnet\scripts\controlnet.py", line 534, in get_enabled_units
    unit = Script.parse_remote_call(p, unit, idx)
  File "D:\SDweinew\extensions\sd-webui-controlnet\scripts\controlnet.py", line 382, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'int' object has no attribute 'enabled'

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.39it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.08it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.41it/s]
```

**Comment by garment-chan** [comment]
Same problem

**Comment by Defeng11** [comment]
> 

I tried to delete the associated extension, and then there will be no error, which shows the extension "sd-webui-segment-anything". You can delete it to solve it, but the plugin will no longer work.

**Comment by Defeng11** [comment]
> Same problem

It is possible that I did not have a perfect installation of this extension, which caused this problem

**Comment by mtpiercey** [comment]
In my situation, disabling the "Segment Anything" extension and re-installing the latest version of the ControlNet extension fixed this issue for me.

Maybe there's a dependency issue/conflict between these two extensions?
