### ISSUE TITLE
[Bug]: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

### ISSUE THREAD

**Issue by waynoedm** [Mikubill/sd-webui-controlnet#1663]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

On a new fresh install of Automatix1111, and the extension, I am getting the following error:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

Webui displays error.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38258903/bea34d70-96f2-4db6-8060-5195c3e0b02c)

### Steps to reproduce the problem

Loading most of the pre-processors in ControlNet reproduces the problem. Depth definitely does not work. Canny does work.

### What should have happened?

There should be no errors, and ControlNet pre-processors should work as intended.

### Commit where the problem happens

webui: 1.3.2
controlnet: 1.1.224

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38258903/24131f23-620a-4f4c-9839-cdf0a8106989)

### Console logs

```Shell
venv "C:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
2023-06-21 05:12:43,322 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-06-21 05:12:43,398 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [6ce0161689] from C:\AI\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 5.2s (import torch: 1.4s, import gradio: 1.0s, import ldm: 0.5s, other imports: 0.8s, load scripts: 0.9s, create ui: 0.3s, gradio launch: 0.2s).
Creating model from config: C:\AI\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: Doggettx... done.
Textual inversion embeddings loaded(0):
Model loaded in 3.6s (load weights from disk: 0.5s, create model: 0.3s, apply weights to model: 0.6s, apply half(): 0.7s, move model to device: 0.6s, load textual inversion embeddings: 0.7s).
2023-06-21 05:13:06,646 - ControlNet - INFO - Preview Resolution = 512
Downloading: "https://huggingface.co/lllyasviel/ControlNet/resolve/main/annotator/ckpts/dpt_hybrid-midas-501f0c75.pt" to C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\midas\dpt_hybrid-midas-501f0c75.pt

Traceback (most recent call last):
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 632, in run_annotator
    result, is_image = preprocessor(
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 180, in midas
    result, _ = model_midas(img, a)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\midas\__init__.py", line 19, in apply_midas
    model = MiDaSInference(model_type="dpt_hybrid")
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\midas\api.py", line 173, in __init__
    model, _ = load_model(model_type)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\midas\api.py", line 106, in load_model
    load_file_from_url(remote_model_path, model_dir=base_model_path)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\basicsr\utils\download_util.py", line 98, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

**Comment by waynoedm** [comment]
I was thinking it was an issue with the Python environment due to a one-click install of either Automatic1111 or other software so I did wiped the O/S (it was new so starting over wasn't a killer). Now I get the error on Automatic1111 install so this issue isn't Controlnet, and it's only getting worse for me. Lol.

**Comment by imkrg** [comment]
I am having the same issue. everything is same, how do resolve this?

**Comment by gensou747** [comment]
Same problem.

**Comment by FugueSegue** [comment]
I'm getting the same sort of error when I try to preprocess.

**Comment by innopanda** [comment]
我也有这个问题 URLError: <urlopen 错误 [SSL: CERTIFICATE_VERIFY_FAILED] 证书验证失败：无法获取本地颁发者证书 (_ssl.c:997)>  怎么处理

**Comment by xxwinlake** [comment]
"C:\Users\wayno\AppData\Local\Programs\Python\Python310\lib\urllib\request.py" 


Please add it. It's completely resolved.

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

**Comment by phongthuong** [comment]
Hello! I am using forge version 231 and have this error when using controlnet. I am using windows, please help me.
![z5895079610535_b367f148f30d143daa181028930b58fb](https://github.com/user-attachments/assets/5a31704c-0ffa-4a1e-bb13-94b6e1df7321)

**Comment by DaivdHan** [comment]
我遇到了类似的问题(controlnet v1.1.455， sd v1.10.1)，并且成功解决，这里给出我解决办法，供大家参考。分析了出错的原因是预处理器模型下载不了，需要修改模型下载地址。
1. stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py （提前备份好）。
第28，31，34，37，39，42行，把路径 https://huggingface.co/lllyasviel/ControlNet/resolve/main/annotator 中的resolve修改为tree
2. 手动下载这些文件放入到sd\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\对应的目录。我的是body_pose_model.pth，hand_pose_model.pth，facenet.pth这三个文件下载出错，我手动下载放到.\annotator\downloads\openpose\ 这个目录下。
3. 重启sd， 加载openpose模型，点击爆炸图可以显示骨架。
![1728032738883](https://github.com/user-attachments/assets/85d4c5f8-50a0-4cd9-b0d9-4391a0c18c24)
![1728033750415](https://github.com/user-attachments/assets/bc23d2e0-b166-44d7-968d-d697a6b1d819)

**Comment by Dikansky** [comment]
Привет, не могу найти решение этой проблемы:
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by Dikansky** [comment]
Hi, I can't find a solution to this problem:
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by alfakat** [comment]
For me replacing 'resolve' by 'raw' in all paths of the extensions/sd-webui-controlnet/annotator/openpose/__init__.py file

body_model_path = (
    "https://huggingface.co/lllyasviel/Annotators/raw/main/body_pose_model.pth"
)
hand_model_path = (
    "https://huggingface.co/lllyasviel/Annotators/raw/main/hand_pose_model.pth"
)
face_model_path = (
    "https://huggingface.co/lllyasviel/Annotators/raw/main/facenet.pth"
)

remote_onnx_det = "https://huggingface.co/yzd-v/DWPose/raw/main/yolox_l.onnx"
remote_onnx_pose = (
    "https://huggingface.co/yzd-v/DWPose/raw/main/dw-ll_ucoco_384.onnx"
)

animal_onnx_pose = "https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/raw/main/Annotators/rtmpose-m_simcc-ap10k_pt-aic-coco_210e-256x256-7a041aa1_20230206.onnx"


or download models from https://huggingface.co/lllyasviel/Annotators/tree/main and copy to the extensions\sd-webui-controlnet\annotator\downloads

**Comment by worldconquer999** [comment]
> 我遇到了类似的问题(controlnet v1.1.455， sd v1.10.1)，并且成功解决，这里给出我解决办法，供大家参考。分析了出错的原因是预处理器模型下载不了，需要修改模型下载地址。
> 
> 1. stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose__init__.py （提前备份好）。
>    第28，31，34，37，39，42行，把路径 https://huggingface.co/lllyasviel/ControlNet/resolve/main/annotator 中的resolve修改为tree
> 2. 手动下载这些文件放入到sd\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\对应的目录。我的是body_pose_model.pth，hand_pose_model.pth，facenet.pth这三个文件下载出错，我手动下载放到.\annotator\downloads\openpose\ 这个目录下。
> 3. 重启sd， 加载openpose模型，点击爆炸图可以显示骨架。
>    ![1728032738883](https://private-user-images.githubusercontent.com/27048739/373584302-85d4c5f8-50a0-4cd9-b0d9-4391a0c18c24.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjY4NTksIm5iZiI6MTczMTEyNjU1OSwicGF0aCI6Ii8yNzA0ODczOS8zNzM1ODQzMDItODVkNGM1ZjgtNTBhMC00Y2Q5LWIwZDktNDM5MWEwYzE4YzI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA0MjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZjk2NjYyYzY5MjdlYmFhMDAzYjUyNjQ0MzRiOGZmYWVlNmZjN2M5OGVhYzdmMWZjZmE1YzY0ZDAzOTQ4M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DfVD1bT_LyHaBNH2NSBM9BITINkL1SBY-OSNTli1J_M)
>    ![1728033750415](https://private-user-images.githubusercontent.com/27048739/373584313-bc23d2e0-b166-44d7-968d-d697a6b1d819.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjY4NTksIm5iZiI6MTczMTEyNjU1OSwicGF0aCI6Ii8yNzA0ODczOS8zNzM1ODQzMTMtYmMyM2QyZTAtYjE2Ni00NGQ3LTk2OGQtZDY5N2E2YjFkODE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDA0MjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OGNhNjgzYTU2MGIzM2RkYmJiYWMxYmRmM2MwZmYwYTM1MzYzMzY5Njc0NTYxZjBjNWRhYWUxNmRiNzg3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oLeQua3DDiFfkPhDkKhmmy4S5agZnAY8RWPHfl5--m4)




Hey, thankyou so much, this fix my problem

**Comment by alfakat** [comment]
Anytime!
