### ISSUE TITLE
[Bug]: Traceback error stopping control net from influencing render

### ISSUE THREAD

**Issue by Steakbouncer** [Mikubill/sd-webui-controlnet#1664]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The UI is not showing any errors, but ControlNet images don't influence the image being rendered in txt2img or img2img regardless of the control type, checkpoint model or starting image I use. I have tried restarting SD and A1111, and deleting and reinstalling control net through the UI. This had no impact. I can create a preprocessor preview in ControlNet, but it wont translate to the image I render.

I'm running Windows 10 and have attempted running A1111 in Firefox and Edge with the same issue in both.

### Steps to reproduce the problem

1. Go to A1111
2. Type any prompt
3. Generate
4. Recycle seed
5. Drag and drop any image into Controlnet
6. Enable control net
7. Adjust any settings in ControlNet, or don't. Doesn't impact outcome
8. Hit Generate
9. Same image is rendered, unimpacted by ControlNet

### What should have happened?

ControlNet should have influenced the rendered image to be similar to the image dropped into ControlNet

### Commit where the problem happens

webui: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0)
controlnet: v1.1.224

### What browsers do you use to access the UI ?

Mozilla Firefox, Microsoft Edge

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers --autolaunch
git pull
call webui.bat
```

### List of enabled extensions

SD-CN-Animation
batch-face-swap
sd-webui-controlnet
sd-webui-segment-anything
sd-webui-text2video
sd-webui-txt-img-to-3d-model
sd_dreambooth_extension
stable-diffusion-webui-eyemask
LDSR
Lora
ScuNET
SwinIR
prompt-bracket-checker

### Console logs

```Shell
Already up to date.
venv "C:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.3.2
Commit hash: baf6946e06249c5af9851c60171692c44ef633e0
Installing requirements
Installing requirements for Batch Face Swap

Installing SD-CN-Animation requirement: scikit-image





If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: dc413a14379b165355502d9f65856c40a4bb5b6f
Successfully installed accelerate-0.19.0 fastapi-0.94.1 gitpython-3.1.31 transformers-4.29.2


Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.1+cu118 installed.
[+] torchvision version 0.15.2+cu118 installed.
[+] accelerate version 0.19.0 installed.
[+] diffusers version 0.16.1 installed.
[+] transformers version 4.29.2 installed.
[+] bitsandbytes version 0.35.4 installed.

Installing dlib
Couldn't install dlib.
Command: "C:\AI\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install dlib==19.24.0
Error code: 1
stdout: Collecting dlib==19.24.0
  Using cached dlib-19.24.0.tar.gz (3.2 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py): started
  Building wheel for dlib (setup.py): finished with status 'error'
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib: started
  Running setup.py install for dlib: finished with status 'error'

stderr:   error: subprocess-exited-with-error

  python setup.py bdist_wheel did not run successfully.
  exit code: 1

  [7 lines of output]
  running bdist_wheel
  running build
  running build_py
  running build_ext

  ERROR: CMake must be installed to build dlib

  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  error: subprocess-exited-with-error

  Running setup.py install for dlib did not run successfully.
  exit code: 1

  [9 lines of output]
  running install
  C:\AI\stable-diffusion-webui\venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  running build_ext

  ERROR: CMake must be installed to build dlib

  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

Encountered error while trying to install package.

dlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: C:\AI\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

----------------------------------------------
Failed building wheel for dlib
ERROR: CMake must be installed to build dlib
Install cmake from https://cmake.org/download/
----------------------------------------------

Launching Web UI with arguments: --xformers --autolaunch
reading checkpoint metadata: C:\AI\stable-diffusion-webui\models\Stable-diffusion\consistentColorful_v103.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\sd_models.py", line 62, in __init__
    self.metadata = read_metadata_from_safetensors(filename)
  File "C:\AI\stable-diffusion-webui\modules\sd_models.py", line 230, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\AI\stable-diffusion-webui\models\Stable-diffusion\consistentColorful_v103.safetensors is not a safetensors file

2023-06-21 23:30:52,568 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\models
2023-06-21 23:30:52,678 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [1a36578807] from C:\AI\stable-diffusion-webui\models\Stable-diffusion\colorful_v30.safetensors
Creating model from config: C:\AI\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Textual inversion embeddings loaded(0):
Model loaded in 3.4s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 0.7s, apply half(): 0.7s, move model to device: 0.6s, load textual inversion embeddings: 0.9s).
Error loading script: em_api.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_api.py", line 16, in <module>
    from eyemask.api import EyeMaskApi
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\api\__init__.py", line 3, in <module>
    from . api import EyeMaskApi
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\api\api.py", line 8, in <module>
    from .. import script as eye_mask_script
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 2, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'

Error loading script: em_script.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_script.py", line 15, in <module>
    from eyemask import constants, ui, script as eye_mask_script
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\ui.py", line 8, in <module>
    from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 2, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'

Error loading script: em_script_embedded.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_script_embedded.py", line 15, in <module>
    from eyemask import constants, ui, script_embedded as eye_mask_script
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\ui.py", line 8, in <module>
    from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
    from . import mask_generator, utils, widlcards
  File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 2, in <module>
    import dlib
ModuleNotFoundError: No module named 'dlib'

Applying optimization: xformers... done.
reading checkpoint metadata: C:\AI\stable-diffusion-webui\models\Stable-diffusion\consistentColorful_v103.safetensors: AssertionError
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\sd_models.py", line 62, in __init__
    self.metadata = read_metadata_from_safetensors(filename)
  File "C:\AI\stable-diffusion-webui\modules\sd_models.py", line 230, in read_metadata_from_safetensors
    assert metadata_len > 2 and json_start in (b'{"', b"{'"), f"{filename} is not a safetensors file"
AssertionError: C:\AI\stable-diffusion-webui\models\Stable-diffusion\consistentColorful_v103.safetensors is not a safetensors file

CUDA SETUP: Loading binary C:\AI\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 12.6s (import torch: 1.8s, import gradio: 1.5s, import ldm: 0.5s, other imports: 0.8s, setup codeformer: 0.2s, load scripts: 6.2s, create ui: 1.2s, gradio launch: 0.4s).
Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\sam.py", line 786, in process
    process_unit.set_process_attributes(p)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 99, in set_process_attributes
    inpaint_image, inpaint_mask = self.sam_inpaint_unit.get_input_and_mask(inpaint_mask_blur)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-segment-anything\scripts\process_params.py", line 45, in get_input_and_mask
    mask = Image.open(self.output_mask_gallery[self.output_chosen_mask + 3]['name']).convert('L')
TypeError: 'bool' object is not subscriptable

Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 653, in process
    self.enabled_units = Script.get_enabled_units(p)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 534, in get_enabled_units
    unit = Script.parse_remote_call(p, unit, idx)
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 382, in parse_remote_call
    unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True)
AttributeError: 'int' object has no attribute 'enabled'

100%|███████████████████████████████████████████████████████████████████████████████| 25/25 [00:07<00:00,  3.56it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████| 25/25 [00:08<00:00,  2.87it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████| 25/25 [00:08<00:00,  4.21it/s]
```

### Additional information

I recently reformatted my PC. Prior to reformatting, SD and ControlNet worked perfectly. After reformatting I reinstalled SD and ControlNet from scratch. The only thing I kept from the previous install was the SD models. Nothing from ControlNet.

**Comment by huchenlei** [comment]
Seems like the crash in the eye mask extension has messed up all other extensions' param sequence. Try remove that eye mask extension.

**Comment by Steakbouncer** [comment]
Removing eyemask didn't help, but your suggestion did lead me in the right direction. I removed the segment anything extension and it's working perfectly now.
Thanks friend.
