### ISSUE TITLE
[Bug]: Error when trying to generate preprocessor preview in Img2Img in AUTO1111

### ISSUE THREAD

**Issue by Gushousekai195** [Mikubill/sd-webui-controlnet#1665]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I put an image in the Img2Img window and left the ControlNet window empty. I click the explosion button which is supposed to generate a preprocessor preview, but instead I get an error:
```Traceback (most recent call last):
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (run_annotator) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [image, checkbox, html, html]
Received outputs:
    [{'value': None, 'visible': True, '__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}]

### Steps to reproduce the problem

1. Go to Img2Img tab in Automatic1111 webui
2. Drop image in Img2Img box
3. Scroll down to ControlNet and click the Explosion ("Run Preprocessor") button


### What should have happened?

I should have been shown a preview image of the results of the preprocessor running.

### Commit where the problem happens

webui: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0)
controlnet: [5fc95279](https://github.com/Mikubill/sd-webui-controlnet/commit/5fc952793aa97bdd0078574b3be8bc98e1fcf2cd)


### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --no-half-vae
```

### List of enabled extensions

![e06e77e6bdcfd5af1fc4cdd7fd80eb79](https://github.com/Mikubill/sd-webui-controlnet/assets/64454655/59979f04-3556-4c02-8e03-4aae61cb6094)

### Console logs

```Shell
Web UI with arguments: --xformers --no-half-vae
2023-06-21 16:51:53,184 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: C:\Users\****\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-06-21 16:51:53,273 - ControlNet - INFO - ControlNet v1.1.224
Loading weights [88d96ca570] from C:\Users\****\stable-diffusion-webui\models\Stable-diffusion\******.ckpt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.5s (import torch: 1.5s, import gradio: 1.0s, import ldm: 0.5s, other imports: 0.8s, load scripts: 2.2s, create ui: 1.4s, gradio launch: 0.1s).
Creating model from config: C:\Users\****\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\****\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.pt
Applying optimization: xformers... done.
Textual inversion embeddings loaded(20): *******************************************
Model loaded in 6.2s (load weights from disk: 3.4s, create model: 0.3s, apply weights to model: 0.4s, apply half(): 0.5s, load VAE: 0.2s, move model to device: 0.6s, load textual inversion embeddings: 0.8s).
Traceback (most recent call last):
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\****\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (run_annotator) didn't receive enough output values (needed: 4, received: 3).
Wanted outputs:
    [image, checkbox, html, html]
Received outputs:
    [{'value': None, 'visible': True, '__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}]
```

**Comment by huchenlei** [comment]
Unmatched number of output params fixed in #1666.

Img2Img input is only used as fallback when hit A1111 generation. Run preprocessor function does not accept img2img input image.
