### ISSUE TITLE
[Bug]: An error occurred in bound_check_params()

### ISSUE THREAD

**Issue by jnyfil** [Mikubill/sd-webui-controlnet#1669]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I tried to generate an image using `tile_resample` in img2img but not working with below error:

```python
Error running process: /content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion/modules/scripts.py", line 451, in process
    script.process(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/scripts/controlnet.py", line 699, in process
    Script.bound_check_params(unit)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/scripts/controlnet.py", line 649, in bound_check_params
    defaults = tuple(
  File "/content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/scripts/controlnet.py", line 650, in <genexpr>
    cfg[i]['value'] if i < len(cfg) else default
TypeError: 'NoneType' object is not subscriptable
```

So I printed cfg, but it seems that the wrong result as below:
```python
for idx, value in enumerate(cfg):
  print(idx, value)

0 None
1 {'name': 'Down Sampling Rate', 'value': 1.0, 'min': 1.0, 'max': 8.0, 'step': 0.01}
```
I'm hoping for a fix as I don't know the exact problem.

### Steps to reproduce the problem

1. Go to img2img Tab
2. Upload an image
3. Check `Enable` and `Pixel Perfect` in CN
4. Click `Tile` on Control Type
5. Click `Generate` button

### What should have happened?

```python
 cfg = preprocessor_sliders_config.get(
            global_state.get_module_basename(unit.module), [])
```
It is estimated that the 'processor_res', 'threshold_a', and 'threshold_b' values should be included in `cfg`

### Commit where the problem happens

webui: v1.3.2
controlnet: v1.1.224

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
python webui.py --api --disable-safe-unpickle --no-download-sd-model --no-half-vae --opt-sdp-attention --disable-console-progressbars
```

### List of enabled extensions

only sd-webui-controlnet

### Console logs

```Shell
2023-06-22 05:19:52,513 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/annotator/downloads
2023-06-22 05:19:53,083 - ControlNet - INFO - ControlNet v1.1.224
Running on local URL: https://127.0.0.1
✔ Connected
Startup time: 35.6s (import torch: 12.0s, import gradio: 2.7s, import ldm: 0.8s, other imports: 2.9s, setup codeformer: 0.2s, list SD models: 2.2s, load scripts: 10.4s, refresh VAE: 0.1s, initialize extra networks: 0.1s, create ui: 3.1s, gradio launch: 0.5s, scripts app_started_callback: 0.4s).
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /content/gdrive/MyDrive/sd/stable-diffusion/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying optimization: sdp... done.
Model loaded in 34.6s (load weights from disk: 21.7s, create model: 1.4s, apply weights to model: 5.5s, apply half(): 2.0s, load VAE: 2.4s, move model to device: 1.6s)
Error running process: /content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion/modules/scripts.py", line 451, in process
    script.process(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/scripts/controlnet.py", line 699, in process
    Script.bound_check_params(unit)
  File "/content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/scripts/controlnet.py", line 649, in bound_check_params
    defaults = tuple(
  File "/content/gdrive/MyDrive/sd/stable-diffusion/extensions/sd-webui-controlnet/scripts/controlnet.py", line 650, in <genexpr>
    cfg[i]['value'] if i < len(cfg) else default
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kevin12314** [comment]
I also encountered the same problem. It seems that the static method added recently to controlnet.py did not consider that some elements in the existing preprocessor_sliders_config array are defined as None.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/10508800/1470dd8c-46d0-4dad-a66a-016792c07bdf)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/10508800/b96a20cb-4a96-4e12-9c3b-0c4eb901ac9d)

**Comment by AndreyRGW** [comment]
Same error

**Comment by watarukamei** [comment]
Same error

**Comment by Nova-lotus** [comment]
Yep, getting the same thing

**Comment by lllyasviel** [comment]
reverted. should be fixed now

**Comment by huchenlei** [comment]
My bad not including unittest for every modules. The change was introduced to remove the try-catch blocked based access. The try-catch implementation can easily hide bugs, and make the code hard to debug. 

The proper way to construct defaults is probably:
```python
cfg = preprocessor_sliders_config.get(
            global_state.get_module_basename(unit.module), [])

defaults = {
  param: cfg_default
  for param, config_default in zip(("processor_res", 'threshold_a', 'threshold_b'), cfg)
  if cfg_default is not None
}

for k, v in defaults.items():
  if getattr(unit, k) < 0:
    setattr(unit, k, v)
```
When the param is not required for the module, the value of the param should not matter. And we should not overwrite the default value or print console message in this situtation.
