### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hackxingxing** [Mikubill/sd-webui-controlnet#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Traceback (most recent call last):
  File "/Users/FXL/stable-diffusion-webui/launch.py", line 38, in <module>
    main()
  File "/Users/FXL/stable-diffusion-webui/launch.py", line 34, in main
    start()
  File "/Users/FXL/stable-diffusion-webui/modules/launch_utils.py", line 334, in start
    webui.webui()
  File "/Users/FXL/stable-diffusion-webui/webui.py", line 376, in webui
    shared.demo = modules.ui.create_ui()
  File "/Users/FXL/stable-diffusion-webui/modules/ui.py", line 445, in create_ui
    modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
  File "/Users/FXL/stable-diffusion-webui/modules/scripts.py", line 311, in initialize_scripts
    script = script_data.script_class()
  File "/Users/FXL/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 215, in __init__
    self.preprocessor = global_state.cache_preprocessors(global_state.cn_preprocessor_modules)
  File "/Users/FXL/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 23, in cache_preprocessors
    CACHE_SIZE = shared.cmd_opts.controlnet_preprocessor_cache_size
AttributeError: 'Namespace' object has no attribute 'controlnet_preprocessor_cache_size'

### Steps to reproduce the problem

我从插件栏安装的sd-webui-controinet.
电脑系统是mac ,m1 

### What should have happened?

无法启动sd-webui！

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
./webui.sh
```

### List of enabled extensions

roop

### Console logs

```Shell
无
```

**Comment by huchenlei** [comment]
Completely restart WebUI should solve the issue.
