### ISSUE TITLE
[Bug]: outpainting using inpaint + lama gives me "The size of tensor a must match the size of tensor b" error 

### ISSUE THREAD

**Issue by trxsudo** [Mikubill/sd-webui-controlnet#1709]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

in img2img, outpainting using inpaint + lama gives me "The size of tensor a must match the size of tensor b" error which render outpainting unsuccessful.

### Steps to reproduce the problem

1. create a 512x768 image in txt2img
2. transfer the image to img2img
3. resize to 1440x768
4. open controlnet inpaint + lama (resize and fill, controlnet more important, weight 0.55)
5. terminal gives the error message

### What should have happened?

should have no error

### Commit where the problem happens

webui: v1.3.0
controlnet: v1.1.227

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.3.0
Commit hash: 20ae71faa8ef035c31aa3a410b707d792c8203a3
Installing requirements

Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Installing requirements for TemporalKit extension

Launching Web UI with arguments: --theme dark --xformers --no-half-vae --api --autolaunch
[-] ADetailer initialized. version: 23.6.3, num models: 8
[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

2023-06-25 05:35:39,149 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\annotator\downloads
2023-06-25 05:35:39,282 - ControlNet - INFO - ControlNet v1.1.227
Loading weights [e6415c4892] from D:\sd\sd-webui-aki-v4.1\models\Stable-diffusion\realisticVisionV20_v20NoVAE.safetensors
Creating model from config: D:\sd\sd-webui-aki-v4.1\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Couldn't find VAE named vae-ft-mse-840000-ema-pruned.safetensors; using None instead
Textual inversion embeddings loaded(1): EasyNegative
Model loaded in 2.1s (load weights from disk: 0.3s, create model: 0.3s, apply weights to model: 0.5s, apply half(): 0.5s, move model to device: 0.5s).
2023-06-25 05:35:45,681 - roop - INFO - roop v0.0.2
2023-06-25 05:35:45,682 - roop - INFO - roop v0.0.2
2023-06-25 05:35:45,684 - roop - INFO - roop-unlock v0.0.2
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\supercupid/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\supercupid/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\supercupid/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\supercupid/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\supercupid/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applying optimization: xformers... done.
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 29.6s (import torch: 7.1s, import gradio: 0.8s, import ldm: 0.7s, other imports: 2.1s, load scripts: 15.5s, create ui: 1.3s, gradio launch: 1.4s, scripts app_started_callback: 0.6s).
Loading weights [9483a64615] from D:\sd\sd-webui-aki-v4.1\models\Stable-diffusion\absolutereality_v1.safetensors
Loading VAE weights specified in settings: D:\sd\sd-webui-aki-v4.1\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying optimization: xformers... done.
Weights loaded in 3.9s (load weights from disk: 0.5s, apply weights to model: 2.4s, load VAE: 0.2s, move model to device: 0.7s).
Restoring base VAE
Applying optimization: xformers... done.
VAE weights loaded.
Loading VAE weights specified in settings: D:\sd\sd-webui-aki-v4.1\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying optimization: xformers... done.
VAE weights loaded.
2023-06-25 05:39:02,384 - ControlNet - INFO - Loading model: control_v11p_sd15_inpaint [ebff9138]
2023-06-25 05:39:02,804 - ControlNet - INFO - Loaded state_dict from [D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.pth]
2023-06-25 05:39:02,805 - ControlNet - INFO - Loading config: D:\supercupid\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.yaml
2023-06-25 05:39:04,756 - ControlNet - INFO - ControlNet model control_v11p_sd15_inpaint [ebff9138] loaded.
2023-06-25 05:39:04,813 - ControlNet - INFO - Loading preprocessor: inpaint_only
2023-06-25 05:39:04,813 - ControlNet - INFO - preprocessor resolution = 789
Error running process: D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/76946041/a38ac0b9-2bdd-4037-a7aa-9019de88f5f3)

### Console logs

```Shell
2023-06-25 05:53:03,482 - ControlNet - INFO - Loading model: control_v11p_sd15_inpaint [ebff9138]
2023-06-25 05:53:03,970 - ControlNet - INFO - Loaded state_dict from [D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.pth]
2023-06-25 05:53:03,971 - ControlNet - INFO - Loading config: D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.yaml
2023-06-25 05:53:05,593 - ControlNet - INFO - ControlNet model control_v11p_sd15_inpaint [ebff9138] loaded.
2023-06-25 05:53:05,716 - ControlNet - INFO - Loading preprocessor: inpaint_only+lama
2023-06-25 05:53:05,996 - ControlNet - INFO - preprocessor resolution = 768
Error running process: D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\sd\sd-webui-aki-v4.1\modules\scripts.py", line 451, in process
    script.process(p, *script_args)
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 829, in process
    detected_map, is_image = preprocessor(
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
    return cached_func(*args, **kwargs)
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\processor.py", line 489, in lama_inpaint
    prd_color = model_lama(img_res)
  File "D:\sd\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 51, in __call__
    color = color * (1 - mask)
RuntimeError: The size of tensor a (3) must match the size of tensor b (0) at non-singleton dimension 2
```

**Comment by kuzman123** [comment]
I have the same problem. Im fed up of trying to fix things every day. Fix it already

**Comment by BobBoxArt** [comment]
I get the same error.

**Comment by BobBoxArt** [comment]
I have found a workaround for this.
If you go into the settings and change to only have 1 controlnet the issue is gone.
So it seems that multi controlnet is breaking this feature.
