### ISSUE TITLE
[Bug]: when using 2.1checkpoint, controlnet failed

### ISSUE THREAD

**Issue by jasoncow007** [Mikubill/sd-webui-controlnet#1727]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

it's ok when im using 1.5 checkpoint, but error occurs switch to 2.1 checkpoint

RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)

### Steps to reproduce the problem

1. choose 2.1 checkpoints 
2. enable controlnet
3. softedge or lineart whatever,,,

genernate and error popup

### What should have happened?

switch to 1.5 checkpoints, runs good

### Commit where the problem happens

webui: [v1.4.0]
controlnet: v1.1.227
python: 3.10.11  •  torch: 2.0.0+cu118  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: [b513c6287d]

### Command Line Arguments

```Shell
microsoft edge
```

### List of enabled extensions

segmentanything
dynamic promt

### Console logs

```Shell
---
2023-06-29 10:09:45,729 - ControlNet - INFO - Preview Resolution = 768
2023-06-29 10:09:52,701 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_softedge [a8575a2a]
2023-06-29 10:09:52,705 - ControlNet - INFO - Loading preprocessor: none
2023-06-29 10:09:52,705 - ControlNet - INFO - preprocessor resolution = 768
*** Error completing request
*** Arguments: ('task(rqjdj9emdir51f7)', 'masterpiece,best quality,white car,Porsche Panamera,(background (city street))\n', '(low quality, worst quality:1.4), (bad anatomy), extra finger, fewer digits, jpeg artifacts,', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 768, 1368, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 1536, 96, True, True, True, False, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E3695FAE60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E3695F95A0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E3695FB1F0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E2F998C8B0>, 0, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, None, False, '0', 'D:\\sd-webui-aki-v4\\models\\roop\\inswapper_128.onnx', 'CodeFormer', 1, '', 1, 1, False, True, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'None', '', '', 1, 'FirstGen', False, False, 'Current', False,   1 2 3
*** 0      , False, '', False, 1, False, False, 30, '', False, False, False, '', '', '', '', '', None, None, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "D:\sd-webui-aki-v4\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "D:\sd-webui-aki-v4\modules\txt2img.py", line 57, in txt2img
        processed = processing.process_images(p)
      File "D:\sd-webui-aki-v4\modules\processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "D:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\sd-webui-aki-v4\modules\processing.py", line 739, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\hook.py", line 350, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "D:\sd-webui-aki-v4\modules\processing.py", line 992, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\sd-webui-aki-v4\modules\sd_samplers_kdiffusion.py", line 439, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\sd-webui-aki-v4\modules\sd_samplers_kdiffusion.py", line 278, in launch_sampling
        return func()
      File "D:\sd-webui-aki-v4\modules\sd_samplers_kdiffusion.py", line 439, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\sd-webui-aki-v4\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\modules\sd_samplers_kdiffusion.py", line 158, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\repositories\k-diffusion\k_diffusion\external.py", line 167, in forward
        return self.get_v(input * c_in, self.sigma_to_t(sigma), **kwargs) * c_out + input * c_skip
      File "D:\sd-webui-aki-v4\repositories\k-diffusion\k_diffusion\external.py", line 177, in get_v
        return self.inner_model.apply_model(x, t, cond)
      File "D:\sd-webui-aki-v4\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\sd-webui-aki-v4\modules\sd_hijack_utils.py", line 26, in __call__
        return self.__sub_func(self.__orig_func, *args, **kwargs)
      File "D:\sd-webui-aki-v4\modules\sd_hijack_unet.py", line 45, in apply_model
        return orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs).float()
      File "D:\sd-webui-aki-v4\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\hook.py", line 661, in forward_webui
        return forward(*args, **kwargs)
      File "D:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\hook.py", line 445, in forward
        control = param.control_model(x=x_in, hint=hint, timesteps=timesteps, context=context)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\cldm.py", line 99, in forward
        return self.control_model(*args, **kwargs)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\cldm.py", line 366, in forward
        h = module(h, emb, context)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
        x = layer(x, context)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
        x = block(x, context=context[i])
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
        return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
      File "D:\sd-webui-aki-v4\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\autograd\function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "D:\sd-webui-aki-v4\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "D:\sd-webui-aki-v4\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
        x = self.attn2(self.norm2(x), context=context) + x
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\modules\sd_hijack_optimizations.py", line 482, in scaled_dot_product_attention_forward
        k_in = self.to_k(context_k)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\sd-webui-aki-v4\extensions\a1111-sd-webui-locon\scripts\..\..\..\extensions-builtin/Lora\lora.py", line 400, in lora_Linear_forward
        return torch.nn.Linear_forward_before_lora(self, input)
      File "D:\sd-webui-aki-v4\extensions\a1111-sd-webui-lycoris\lycoris.py", line 741, in lyco_Linear_forward
        return torch.nn.Linear_forward_before_lyco(self, input)
      File "D:\sd-webui-aki-v4\py310\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x1024 and 768x320)
```

### Additional information

nope

**Comment by mira-6** [comment]
This isn't a bug.

**Comment by jasoncow007** [comment]
got it but how could I use controlnet over 2.1 models,,,,,,is there a sd21 contronet version?

**Comment by jasoncow007** [comment]
> This isn't a bug.

got it but how could I use controlnet over 2.1 models,,,,,,is there a sd21 contronet version?

**Comment by mira-6** [comment]
You need controlnet models specifically for 2.1.
https://huggingface.co/thibaud/controlnet-sd21 has a bunch.

**Comment by jasoncow007** [comment]
> You need controlnet models specifically for 2.1. https://huggingface.co/thibaud/controlnet-sd21 has a bunch.

thank you!

**Comment by Woisek** [comment]
> You need controlnet models specifically for 2.1. https://huggingface.co/thibaud/controlnet-sd21 has a bunch.

But that don't work. Somehow never did. At least for me. Still waiting for a proper version (also with smaller sized models) set up in one place.
