### ISSUE TITLE
getting error for lama "Expected state_dict to be dict-like, got <class 'NoneType'>"

### ISSUE THREAD

**Issue by mrgamerrg** [Mikubill/sd-webui-controlnet#1729]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

im trying to use preprocessor inpaint only=lama but it gives me the error "Expected state_dict to be dict-like, got <class 'NoneType'>"

### Steps to reproduce the problem

1. load inpaint only+lama
2. start generating or run preprocessor 

### What should have happened?

preprocessor runs

### Commit where the problem happens

webui: 
controlnet: [8e143d35]

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

TemporalKit
a1111-sd-webui-tagcomplete
adetailer
canvas-zoom
sd-dynamic-prompts
sd-extension-system-info
sd-webui-3d-open-pose-editor
sd-webui-aspect-ratio-helper
sd-webui-controlnet
sd-webui-depth-lib
sd-webui-e621-prompt
sd-webui-inpaint-anything
sd-webui-openpose-editor
stable-diffusion-webui-images-browser
stable-diffusion-webui-rembg

### Console logs

```Shell
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: <none>
Commit hash: <none>
Installing xformers
Collecting xformers==0.0.17
  Using cached xformers-0.0.17-cp310-cp310-win_amd64.whl (112.6 MB)
Installing collected packages: xformers
Successfully installed xformers-0.0.17
Installing requirements


Requirement already satisfied: send2trash~=1.8 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (1.8.2)
Requirement already satisfied: dynamicprompts[attentiongrabber,magicprompt]~=0.27.0 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (0.27.0)
Requirement already satisfied: jinja2~=3.1 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.2)
Requirement already satisfied: pyparsing~=3.0 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.0)
Requirement already satisfied: transformers[torch]~=4.19 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.25.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from jinja2~=3.1->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.1.3)
Requirement already satisfied: filelock in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.12.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.15.1)
Requirement already satisfied: numpy>=1.17 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (6.0)
Requirement already satisfied: regex!=2019.12.17 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.6.3)
Requirement already satisfied: requests in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.65.0)
Requirement already satisfied: torch!=1.12.0,>=1.7 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.0.1+cu118)
Requirement already satisfied: fsspec in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub<1.0,>=0.10.0->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub<1.0,>=0.10.0->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.6.3)
Requirement already satisfied: sympy in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.12)
Requirement already satisfied: networkx in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1)
Requirement already satisfied: colorama in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.27->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in c:\tcht\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.3.0)
sd-dynamic-prompts installer: running 'C:\TCHT\stable-diffusion-webui\venv\Scripts\python.exe' -m pip install 'send2trash~=1.8' 'dynamicprompts[attentiongrabber,magicprompt]~=0.27.0'







Installing requirements for TemporalKit extension

Launching Web UI with arguments: --xformers --reinstall-xformers --xformers --reinstall-xformers
[-] ADetailer initialized. version: 23.6.4, num models: 8
2023-06-29 08:18:22,323 - ControlNet - INFO - ControlNet v1.1.227
ControlNet preprocessor location: C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-06-29 08:18:22,429 - ControlNet - INFO - ControlNet v1.1.227
Image Browser: ImageReward is not installed, cannot be used.
Loading weights [853e7e85c4] from C:\TCHT\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_631BakedVae.safetensors
Creating model from config: C:\TCHT\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 20.7s (import torch: 2.6s, import gradio: 1.3s, import ldm: 1.2s, other imports: 1.8s, setup codeformer: 0.2s, load scripts: 11.4s, create ui: 1.9s, gradio launch: 0.3s).
Applying optimization: xformers... done.
Textual inversion embeddings loaded(0):
Model loaded in 45.5s (load weights from disk: 0.8s, create model: 0.8s, apply weights to model: 38.2s, apply half(): 4.6s, move model to device: 0.9s).
2023-06-29 08:19:19,794 - ControlNet - INFO - Preview Resolution = -1
Error verifying pickled file from C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\lama\ControlNetLama.pth:
Traceback (most recent call last):
  File "C:\TCHT\stable-diffusion-webui\modules\safe.py", line 82, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Python310\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Python310\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TCHT\stable-diffusion-webui\modules\safe.py", line 136, in load_with_extra
    check_pt(filename, extra_handler)
  File "C:\TCHT\stable-diffusion-webui\modules\safe.py", line 103, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Traceback (most recent call last):
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 636, in run_annotator
    result, is_image = preprocessor(
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 489, in lama_inpaint
    prd_color = model_lama(img_res)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 43, in __call__
    self.load_model()
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 33, in load_model
    self.model = load_checkpoint(cfg, os.path.abspath(modelpath), strict=False, map_location='cpu')
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\trainers\__init__.py", line 28, in load_checkpoint
    model.load_state_dict(state, strict=strict)
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1994, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.
```

**Comment by mrgamerrg** [comment]
i did put the commad --disable-safe-unpickle and now it gives me this error:

Traceback (most recent call last):
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 636, in run_annotator
    result, is_image = preprocessor(
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 489, in lama_inpaint
    prd_color = model_lama(img_res)
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 43, in __call__
    self.load_model()
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 33, in load_model
    self.model = load_checkpoint(cfg, os.path.abspath(modelpath), strict=False, map_location='cpu')
  File "C:\TCHT\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\trainers\__init__.py", line 27, in load_checkpoint
    state = torch.load(path, map_location=map_location)
  File "C:\TCHT\stable-diffusion-webui\modules\safe.py", line 107, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "C:\TCHT\stable-diffusion-webui\modules\safe.py", line 152, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\TCHT\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
