### ISSUE TITLE
[Bug]: img2img-img2img controlnet inpaint_only

### ISSUE THREAD

**Issue by xiaojiemeidu** [Mikubill/sd-webui-controlnet#1733]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

bug

### Steps to reproduce the problem

NO

### What should have happened?

NO

### Commit where the problem happens

webui: 1.4.0
controlnet: 1.1.227

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
2023-06-29 22:57:04,664 - ControlNet - INFO - Loading model: control_v11p_sd15_inpaint [ebff9138]
2023-06-29 22:57:04,982 - ControlNet - INFO - Loaded state_dict from [D:\StabilityAI\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.pth]
2023-06-29 22:57:04,983 - ControlNet - INFO - Loading config: D:\StabilityAI\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_inpaint.yaml
2023-06-29 22:57:07,005 - ControlNet - INFO - ControlNet model control_v11p_sd15_inpaint [ebff9138] loaded.
2023-06-29 22:57:07,051 - ControlNet - INFO - Loading preprocessor: inpaint_only
2023-06-29 22:57:07,051 - ControlNet - INFO - preprocessor resolution = -1
*** Error running process: D:\StabilityAI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\StabilityAI\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "D:\StabilityAI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 904, in process
        final_inpaint_mask = final_inpaint_feed[0, 3, :, :].astype(np.float32)
    IndexError: index 3 is out of bounds for axis 1 with size 3
```

### List of enabled extensions

NO

### Console logs

```Shell
NO
```

**Comment by huchenlei** [comment]
Closing as no enough context is provided. Feel free to file another issue with all context information.
