### ISSUE TITLE
Error Loading controlnet.py, bad file descriptor [Bug]: 

### ISSUE THREAD

**Issue by AModestMouse** [Mikubill/sd-webui-controlnet#1755]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

On launch, an error is returned
![error](https://github.com/Mikubill/sd-webui-controlnet/assets/138523364/c84c63cc-c380-47fe-a8a6-3087e50811a6)

OSError: [Errno9} Bad file descriptor: 

ControlNet not present in the webUI

Tried manually pulling the most updated versions of both the WebUI and ControlNet, both should be fully up to date.

### Steps to reproduce the problem

run webui-user.bat

???

No profit

### What should have happened?

no error

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Command Line Arguments

```Shell
--no-half --xformers --ckpt-dir I:\Stable Diffusion
```

### List of enabled extensions

![extensions](https://github.com/Mikubill/sd-webui-controlnet/assets/138523364/4b92d262-e799-4879-9b66-387f1b7bb5a0)

### Console logs

```Shell
Already up to date.
venv "C:\Users\user\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements
current transparent-background 1.2.3


Installing imageio-ffmpeg requirement for depthmap script
Installing pyqt5 requirement for depthmap script

Launching Web UI with arguments: --no-half --xformers --ckpt-dir I:\Stable Diffusion
2023-07-03 11:40:11,897 - ControlNet - INFO - ControlNet v1.1.228
ControlNet preprocessor location: C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "C:\Users\user\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\user\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 84, in <module>
        global_state.update_cn_models()
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 208, in update_cn_models
        found = get_all_models(sort_by, filter_by, path)
      File "C:\Users\user\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 192, in get_all_models
        res[name + f" [{sd_models.model_hash(filename)}]"] = filename
      File "C:\Users\user\stable-diffusion-webui\modules\sd_models.py", line 154, in model_hash
        with open(filename, "rb") as file:
    OSError: [Errno 9] Bad file descriptor: 'C:\\Users\\user\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\models\\control_sd15_canny.pth'

---
2023-07-03 11:40:11,934 - ControlNet - INFO - ControlNet v1.1.228
Loading weights [02e37aad9f] from I:\Stable Diffusion\openjourney-v4.ckpt
*** Error executing callback ui_tabs_callback for C:\Users\user\stable-diffusion-webui\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py
    Traceback (most recent call last):
      File "C:\Users\user\stable-diffusion-webui\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\user\stable-diffusion-webui\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py", line 749, in on_ui_tabs
        create_tab(tab)
      File "C:\Users\user\stable-diffusion-webui\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py", line 585, in create_tab
        ip2p_prompt, ip2p_prompt_styles, ip2p_negative_prompt, submit, ip2p_interrogate, ip2p_deepbooru, ip2p_prompt_style_apply, ip2p_save_style, ip2p_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=True)
    ValueError: too many values to unpack (expected 14)

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.0s (import torch: 5.2s, import gradio: 1.4s, import ldm: 0.6s, other imports: 1.4s, setup codeformer: 0.1s, load scripts: 5.9s, create ui: 1.0s, gradio launch: 0.3s).
preload_extensions_git_metadata for 13 extensions took 2.21s
Creating model from config: C:\Users\user\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Textual inversion embeddings loaded(1): orogen
Model loaded in 6.8s (load weights from disk: 3.3s, create model: 0.8s, apply weights to model: 0.7s, move model to device: 1.7s, calculate empty prompt: 0.2s).
```

**Comment by huchenlei** [comment]
Seems like a model issue. Please verify that you have models downloaded and put to correct locations.

**Comment by AModestMouse** [comment]
all models are downloaded and in the correct location, which would have caused issues before now, but i confirmed they are in the correct place.

**Comment by AModestMouse** [comment]
update, one of the model files was corrupted and unable to be deleted, to fix the issue i moved all other .pth and .yaml files to a new folder and renamed that folder to models.
