### ISSUE TITLE
Only scan dir if dir exists

### ISSUE THREAD

**Issue by devingfx** [Mikubill/sd-webui-controlnet#1767]
Hi guys!
I have trouble using the commandline arguments to move the models and annotators folder to a place outside extensions folder (and outside webui also)...
Is this supposed to be in production ? Or maybe active on a certain commit ?

Here is my commandline args for CN:
```
--controlnet-dir /home/dig/dev/AI/models/img/ControlNet/models --controlnet-annotator-models-path /home/dig/dev/AI/models/img/ControlNet/annotators
```
Here is my full webui commandline string (if maybe any conflict with a full CPU config):
```
Launching Web UI with arguments: --ckpt-dir /home/dig/dev/AI/models/img/stable-diffusion --lora-dir /home/dig/dev/AI/models/img/lora --embeddings-dir /home/dig/dev/AI/models/img/embeddings --textual-inversion-templates-dir /home/dig/dev/AI/models/img/textual_inversion_templates --hypernetwork-dir /home/dig/dev/AI/models/img/hypernetworks --enable-insecure-extension-access --api --skip-torch-cuda-test --opt-channelslast --use-cpu all --no-half --precision autocast --controlnet-dir /home/dig/dev/AI/models/img/ControlNet/models --controlnet-annotator-models-path /home/dig/dev/AI/models/img/ControlNet/annotators
```
...and here is the error I get:
```bash
Error loading script: controlnet.py
Traceback (most recent call last):
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/modules/scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 84, in <module>
    global_state.update_cn_models()
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 208, in update_cn_models
    found = get_all_models(sort_by, filter_by, path)
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 175, in get_all_models
    fileinfos = traverse_all_files(path, [])
  File "/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 163, in traverse_all_files
    for entry in os.scandir(curr_path)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/dig/dev/AI/A1111/stable-diffusion-webui/extensions/sd-webui-controlnet/models'
```

Could somebody help me point out why CN is still searching the models in old location ?

THX

_Originally posted by @devingfx in https://github.com/Mikubill/sd-webui-controlnet/issues/893#issuecomment-1620500296_

**Comment by huchenlei** [comment]
#1759 have fixed the scanning non-existent for issue.
