### ISSUE TITLE
[Bug]:controlnet cant use in i2i ,but can use in t2i

### ISSUE THREAD

**Issue by magicwang1111** [Mikubill/sd-webui-controlnet#1783]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

controlnet cant use in i2i ,but can use in t2i

### Steps to reproduce the problem

1. input prompt ,select image
2. select softedge
3. ...

### What should have happened?

The picture is generated normally, and controlnet is enabled

### Commit where the problem happens

webui: version: [v1.4.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/394ffa7b0a7fff3ec484bcd084e673a8b301ccc8)  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.19  •  gradio: 3.32.0  •  checkpoint: [9748325dce](https://google.com/search?q=9748325dceb12565b0a38ca6bdbded56f39ab82de0ea5ff6a1c66e40d0091c21)
controlnet: 
ControlNet v1.1.228

### Command Line Arguments

```Shell
Launching Web UI with arguments: --theme dark --xformers --force-enable-xformers --opt-channelslast --api --autolaunch
Stop Motion CN - Running Preload
Set Gradio Queue: True
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/131337141/601945f3-61b0-4b2c-9c09-5e189ed119c6)

### Console logs

```Shell
2023-07-10 11:31:40,202 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: F:\sd-webui-aki-v4\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "F:\sd-webui-aki-v4\extensions\adetailer\adetailer\traceback.py", line 156, in wrapper
        raise error from None
    ValueError: 
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
    ┌─────────────────────────────────────────────────────────────────────────┐
    │                               System info                               │
    │ ┌─────────────┬───────────────────────────────────────────────────────┐ │
    │ │             │ Value                                                 │ │
    │ ├─────────────┼───────────────────────────────────────────────────────┤ │
    │ │    Platform │ Windows-10-10.0.19041-SP0                             │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023,          │ │
    │ │             │ 00:38:17) [MSC v.1929 64 bit (AMD64)]                 │ │
    │ │     Version │ v1.4.0                                                │ │
    │ │      Commit │ 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8              │ │
    │ │ Commandline │ ['F:\\sd-webui-aki-v4\\launch.py', '--theme', 'dark', │ │
    │ │             │ '--xformers', '--force-enable-xformers',              │ │
    │ │             │ '--opt-channelslast', '--api', '--autolaunch']        │ │
    │ └─────────────┴───────────────────────────────────────────────────────┘ │
    │                                 Inputs                                  │
    │ ┌─────────────────┬───────────────────────────────────────────────────┐ │
    │ │                 │ Value                                             │ │
    │ ├─────────────────┼───────────────────────────────────────────────────┤ │
    │ │          prompt │ masterpiece, best quality,1girl, full body,       │ │
    │ │                 │ outdoors, sea, starfish, dolphin, shark,          │ │
    │ │                 │ shell,alihanfu,                                   │ │
    │ │ negative_prompt │ (worst quality, low quality:2), monochrome,       │ │
    │ │                 │ zombie,overexposure, watermark,text,bad           │ │
    │ │                 │ anatomy,bad hand,extra hands,extra fingers,too    │ │
    │ │                 │ many fingers,fused fingers,bad arm,distorted      │ │
    │ │                 │ arm,extra arms,fused arms,extra legs,missing      │ │
    │ │                 │ leg,disembodied leg,extra nipples, detached arm,  │ │
    │ │                 │ liquid hand,inverted hand,disembodied limb, small │ │
    │ │                 │ breasts, loli, oversized head,extra               │ │
    │ │                 │ body,completely nude, extra                       │ │
    │ │                 │ navel,easynegative,(hair between eyes),sketch,    │ │
    │ │                 │ duplicate, ugly, huge eyes, text, logo, worst     │ │
    │ │                 │ face, (bad and mutated hands:1.3),  (blurry:2.0), │ │
    │ │                 │ horror, geometry, bad_prompt, (bad hands),        │ │
    │ │                 │ (missing fingers), multiple limbs, bad anatomy,   │ │
    │ │                 │ (interlocked fingers:1.2), Ugly Fingers, (extra   │ │
    │ │                 │ digit and hands and fingers and legs and          │ │
    │ │                 │ arms:1.4), ((2girl)), (deformed fingers:1.2),     │ │
    │ │                 │ (long fingers:1.2),(bad-artist-anime),            │ │
    │ │                 │ bad-artist, bad hand, extra legs                  │ │
    │ │                 │ ,(ng_deepnegative_v1_75t)                         │ │
    │ │          n_iter │ 1                                                 │ │
    │ │      batch_size │ 1                                                 │ │
    │ │           width │ 800                                               │ │
    │ │          height │ 800                                               │ │
    │ │    sampler_name │ Euler a                                           │ │
    │ │       enable_hr │ False                                             │ │
    │ │     hr_upscaler │                                                   │ │
    │ │      checkpoint │ 测试\alihanfu0705_512.safetensors [9748325dce]    │ │
    │ │             vae │ vae-ft-mse-840000-ema-pruned.safetensors          │ │
    │ │            unet │ Automatic                                         │ │
    │ └─────────────────┴───────────────────────────────────────────────────┘ │
    │ ┌───────────────── Traceback (most recent call last) ─────────────────┐ │
    │ │ F:\sd-webui-aki-v4\extensions\adetailer\adetailer\traceback.py:136  │ │
    │ │ in wrapper                                                          │ │
    │ │                                                                     │ │
    │ │   133 │   │   width = width - 4 if width > 4 else None              │ │
    │ │   134 │   │   console = Console(file=string, force_terminal=force_t │ │
    │ │   135 │   │   try:                                                  │ │
    │ │ > 136 │   │   │   return func(*args, **kwargs)                      │ │
    │ │   137 │   │   except Exception as e:                                │ │
    │ │   138 │   │   │   tables = [                                        │ │
    │ │   139 │   │   │   │   get_table(title, data)                        │ │
    │ │                                                                     │ │
    │ │ F:\sd-webui-aki-v4\extensions\adetailer\scripts\!adetailer.py:500   │ │
    │ │ in process                                                          │ │
    │ │                                                                     │ │
    │ │   497 │   │   if getattr(p, "_disable_adetailer", False):           │ │
    │ │   498 │   │   │   return                                            │ │
    │ │   499 │   │                                                         │ │
    │ │ > 500 │   │   if self.is_ad_enabled(*args_):                        │ │
    │ │   501 │   │   │   arg_list = self.get_args(p, *args_)               │ │
    │ │   502 │   │   │   extra_params = self.extra_params(arg_list)        │ │
    │ │   503 │   │   │   p.extra_generation_params.update(extra_params)    │ │
    │ │                                                                     │ │
    │ │ F:\sd-webui-aki-v4\extensions\adetailer\scripts\!adetailer.py:171   │ │
    │ │ in is_ad_enabled                                                    │ │
    │ │                                                                     │ │
    │ │   168 │   │   │   │   │      [-] ADetailer: Invalid arguments passe │ │
    │ │   169 │   │   │   │   │   │      input: {args_!r}                   │ │
    │ │   170 │   │   │   │   │      """                                    │ │
    │ │ > 171 │   │   │   raise ValueError(dedent(message))                 │ │
    │ │   172 │   │   enable = args_[0] if isinstance(args_[0], bool) else  │ │
    │ │   173 │   │   checker = EnableChecker(enable=enable, arg_list=arg_l │ │
    │ │   174 │   │   return checker.is_enabled()                           │ │
    │ └─────────────────────────────────────────────────────────────────────┘ │
    │ ValueError:                                                             │
    │ [-] ADetailer: Invalid arguments passed to ADetailer.                   │
    │     input: ()                                                           │
    │                                                                         │
    └─────────────────────────────────────────────────────────────────────────┘

---
*** Error running process: F:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 11 required positional arguments: 'enabled', 'override_image_size', 'image_width', 'image_height', 'keep_input_size', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_index', and 'scale_factor'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: F:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 21 required positional arguments: 'enabled', 'method', 'overwrite_size', 'keep_input_size', 'image_width', 'image_height', 'tile_width', 'tile_height', 'overlap', 'tile_batch_size', 'upscaler_name', 'scale_factor', 'noise_inverse', 'noise_inverse_steps', 'noise_inverse_retouch', 'noise_inverse_renoise_strength', 'noise_inverse_renoise_kernel', 'control_tensor_cpu', 'enable_bbox_control', 'draw_background', and 'causal_layers'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: F:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'encoder_tile_size', 'decoder_tile_size', 'vae_to_gpu', 'fast_decoder', 'fast_encoder', and 'color_fix'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: F:\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "F:\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\sam.py", line 785, in process
        process_unit = SAMProcessUnit(args, is_img2img)
      File "F:\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\process_params.py", line 63, in __init__
        self.sam_inpaint_unit = SAMInpaintUnit(args, is_img2img)
      File "F:\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\process_params.py", line 25, in __init__
        self.init_sam_single_image_process(args)
      File "F:\sd-webui-aki-v4\extensions\sd-webui-segment-anything\scripts\process_params.py", line 29, in init_sam_single_image_process
        self.inpaint_upload_enable      = args[0]
    IndexError: tuple index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: F:\sd-webui-aki-v4\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 17 required positional arguments: 'loraratios', 'useblocks', 'xyzsetting', 'xtype', 'xmen', 'ytype', 'ymen', 'ztype', 'zmen', 'exmen', 'eymen', 'ecount', 'diffcol', 'thresh', 'revxy', 'elemental', and 'elemsets'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
2023-07-10 11:31:40,314 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running process: F:\sd-webui-aki-v4\extensions\stable-diffusion-webui-composable-lora\scripts\composable_lora_script.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: ComposableLoraScript.process() missing 3 required positional arguments: 'enabled', 'opt_uc_text_model_encoder', and 'opt_uc_diffusion_model'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process: F:\sd-webui-aki-v4\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 5 required positional arguments: 'enabled', 'raw_divisions', 'raw_positions', 'raw_weights', and 'raw_end_at_step'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running before_process_batch: F:\sd-webui-aki-v4\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 482, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
    TypeError: Script.before_process_batch() missing 17 required positional arguments: 'loraratios', 'useblocks', 'xyzsetting', 'xtype', 'xmen', 'ytype', 'ymen', 'ztype', 'zmen', 'exmen', 'eymen', 'ecount', 'diffcol', 'thresh', 'revxy', 'elemental', and 'elemsets'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process_batch: F:\sd-webui-aki-v4\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "F:\sd-webui-aki-v4\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 190, in process_batch
        if not args[0]:
    IndexError: tuple index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running process_batch: F:\sd-webui-aki-v4\extensions\sd-webui-lora-block-weight\scripts\lora_block_weight.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
    TypeError: Script.process_batch() missing 17 required positional arguments: 'loraratios', 'useblocks', 'xyzsetting', 'xtype', 'xmen', 'ytype', 'ymen', 'ztype', 'zmen', 'exmen', 'eymen', 'ecount', 'diffcol', 'thresh', 'revxy', 'elemental', and 'elemsets'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess_batch: F:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess_image: F:\sd-webui-aki-v4\extensions\adetailer\scripts\!adetailer.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "F:\sd-webui-aki-v4\extensions\adetailer\adetailer\traceback.py", line 156, in wrapper
        raise error from None
    ValueError: 
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
    ┌─────────────────────────────────────────────────────────────────────────┐
    │                               System info                               │
    │ ┌─────────────┬───────────────────────────────────────────────────────┐ │
    │ │             │ Value                                                 │ │
    │ ├─────────────┼───────────────────────────────────────────────────────┤ │
    │ │    Platform │ Windows-10-10.0.19041-SP0                             │ │
    │ │      Python │ 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023,          │ │
    │ │             │ 00:38:17) [MSC v.1929 64 bit (AMD64)]                 │ │
    │ │     Version │ v1.4.0                                                │ │
    │ │      Commit │ 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8              │ │
    │ │ Commandline │ ['F:\\sd-webui-aki-v4\\launch.py', '--theme', 'dark', │ │
    │ │             │ '--xformers', '--force-enable-xformers',              │ │
    │ │             │ '--opt-channelslast', '--api', '--autolaunch']        │ │
    │ └─────────────┴───────────────────────────────────────────────────────┘ │
    │                                 Inputs                                  │
    │ ┌─────────────────┬───────────────────────────────────────────────────┐ │
    │ │                 │ Value                                             │ │
    │ ├─────────────────┼───────────────────────────────────────────────────┤ │
    │ │          prompt │ masterpiece, best quality,1girl, full body,       │ │
    │ │                 │ outdoors, sea, starfish, dolphin, shark,          │ │
    │ │                 │ shell,alihanfu,                                   │ │
    │ │ negative_prompt │ (worst quality, low quality:2), monochrome,       │ │
    │ │                 │ zombie,overexposure, watermark,text,bad           │ │
    │ │                 │ anatomy,bad hand,extra hands,extra fingers,too    │ │
    │ │                 │ many fingers,fused fingers,bad arm,distorted      │ │
    │ │                 │ arm,extra arms,fused arms,extra legs,missing      │ │
    │ │                 │ leg,disembodied leg,extra nipples, detached arm,  │ │
    │ │                 │ liquid hand,inverted hand,disembodied limb, small │ │
    │ │                 │ breasts, loli, oversized head,extra               │ │
    │ │                 │ body,completely nude, extra                       │ │
    │ │                 │ navel,easynegative,(hair between eyes),sketch,    │ │
    │ │                 │ duplicate, ugly, huge eyes, text, logo, worst     │ │
    │ │                 │ face, (bad and mutated hands:1.3),  (blurry:2.0), │ │
    │ │                 │ horror, geometry, bad_prompt, (bad hands),        │ │
    │ │                 │ (missing fingers), multiple limbs, bad anatomy,   │ │
    │ │                 │ (interlocked fingers:1.2), Ugly Fingers, (extra   │ │
    │ │                 │ digit and hands and fingers and legs and          │ │
    │ │                 │ arms:1.4), ((2girl)), (deformed fingers:1.2),     │ │
    │ │                 │ (long fingers:1.2),(bad-artist-anime),            │ │
    │ │                 │ bad-artist, bad hand, extra legs                  │ │
    │ │                 │ ,(ng_deepnegative_v1_75t)                         │ │
    │ │          n_iter │ 1                                                 │ │
    │ │      batch_size │ 1                                                 │ │
    │ │           width │ 800                                               │ │
    │ │          height │ 800                                               │ │
    │ │    sampler_name │ Euler a                                           │ │
    │ │       enable_hr │ False                                             │ │
    │ │     hr_upscaler │                                                   │ │
    │ │      checkpoint │ 测试\alihanfu0705_512.safetensors [9748325dce]    │ │
    │ │             vae │ vae-ft-mse-840000-ema-pruned.safetensors          │ │
    │ │            unet │ Automatic                                         │ │
    │ └─────────────────┴───────────────────────────────────────────────────┘ │
    │ ┌───────────────── Traceback (most recent call last) ─────────────────┐ │
    │ │ F:\sd-webui-aki-v4\extensions\adetailer\adetailer\traceback.py:136  │ │
    │ │ in wrapper                                                          │ │
    │ │                                                                     │ │
    │ │   133 │   │   width = width - 4 if width > 4 else None              │ │
    │ │   134 │   │   console = Console(file=string, force_terminal=force_t │ │
    │ │   135 │   │   try:                                                  │ │
    │ │ > 136 │   │   │   return func(*args, **kwargs)                      │ │
    │ │   137 │   │   except Exception as e:                                │ │
    │ │   138 │   │   │   tables = [                                        │ │
    │ │   139 │   │   │   │   get_table(title, data)                        │ │
    │ │                                                                     │ │
    │ │ F:\sd-webui-aki-v4\extensions\adetailer\scripts\!adetailer.py:596   │ │
    │ │ in postprocess_image                                                │ │
    │ │                                                                     │ │
    │ │   593 │   │   if getattr(p, "_disable_adetailer", False):           │ │
    │ │   594 │   │   │   return                                            │ │
    │ │   595 │   │                                                         │ │
    │ │ > 596 │   │   if not self.is_ad_enabled(*args_):                    │ │
    │ │   597 │   │   │   return                                            │ │
    │ │   598 │   │                                                         │ │
    │ │   599 │   │   p._ad_idx = getattr(p, "_ad_idx", -1) + 1             │ │
    │ │                                                                     │ │
    │ │ F:\sd-webui-aki-v4\extensions\adetailer\scripts\!adetailer.py:171   │ │
    │ │ in is_ad_enabled                                                    │ │
    │ │                                                                     │ │
    │ │   168 │   │   │   │   │      [-] ADetailer: Invalid arguments passe │ │
    │ │   169 │   │   │   │   │   │      input: {args_!r}                   │ │
    │ │   170 │   │   │   │   │      """                                    │ │
    │ │ > 171 │   │   │   raise ValueError(dedent(message))                 │ │
    │ │   172 │   │   enable = args_[0] if isinstance(args_[0], bool) else  │ │
    │ │   173 │   │   checker = EnableChecker(enable=enable, arg_list=arg_l │ │
    │ │   174 │   │   return checker.is_enabled()                           │ │
    │ └─────────────────────────────────────────────────────────────────────┘ │
    │ ValueError:                                                             │
    │ [-] ADetailer: Invalid arguments passed to ADetailer.                   │
    │     input: ()                                                           │
    │                                                                         │
    └─────────────────────────────────────────────────────────────────────────┘

---
*** Error running postprocess: F:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: F:\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
```

**Comment by huchenlei** [comment]
Extension conflict. Please disable all extensions except ControlNet. Reopen if issue persists.

**Comment by magicwang1111** [comment]
> Extension conflict. Please disable all extensions except ControlNet. Reopen if issue persists.扩展冲突。请禁用除控制网以外的所有扩展。如果问题仍然存在，请重新打开。

how to disable all extensions except ControlNet?Do you mean delete all other extensions?

**Comment by huchenlei** [comment]
You can temporarily move them out of extension folder.
