### ISSUE TITLE
[Bug]:  Reference-only precision mismatch occurs in latest version?

### ISSUE THREAD

**Issue by ym-ctw** [Mikubill/sd-webui-controlnet#1787]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

RuntimeError: shape '[154, 8, 40]' is invalid for input of size 24640

### Steps to reproduce the problem

1. Go to .... img2img, controlnet use reference-only
2. Press .... generate
3. Get error:  shape '[154, 8, 40]' is invalid for input of size 24640

### What should have happened?

generate success

### Commit where the problem happens

It seems that  reference-only in new version have precision mismatch problems.

### Command Line Arguments

```Shell
sh webui.sh --xformers
```

### List of enabled extensions

controlnet

### Console logs

```Shell
*** Arguments: ('task(4695za2o1cjj7th)', 0, 'asdasdasdas', '', [], <PIL.Image.Image image mode=RGBA size=1024x1024 at 0x7EFC34BF3880>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 0, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7efc34973ca0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7efc349734f0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x7efc34973c10>, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nSTYLE:1,0,0,0,0,0,0,0,0,0,0,0.8,1,1,1,1,1\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5\n\nGSTYLE: 1,0,0.7,0.46,0,0.66,0.7,0,0.66,0.7,0,0,0,1,0,0,0,1,1,1,0.5,0.5,0.5,0.2,0.5,1\nYSTYLE: 0.8,0,1,0.8,0,1,1,0,1,0.5,0,0,0,1,0,0,0,0.5,0.8,0.3,0.2,0.2,0.3,0,0.3,0.3\nZJ4:1,0,0.7,0.7,0,0.7,0.7,0,1,1,0,0,0,1,0,0,0,1,1,0.6,0.5,0.6,0.8,0.7,0.7,0.6\n\nH1:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0\nCF:0,0,0,0.3,0,0.5,0.5,0,1,1,0,0,0,1,0,0,0,1,1,1,0.5,0.5,0.5,0,0.3,0.7', True, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False, 'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:0\n\nXYZ:::1', False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/img2img.py", line 198, in img2img
        processed = process_images(p)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/processing.py", line 739, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 350, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/processing.py", line 1316, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 409, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 278, in launch_sampling
        return func()
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 409, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 158, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 661, in forward_webui
        return forward(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 564, in forward
        outer.original_forward(
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 84, in forward
        x = layer(x, context)
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 334, in forward
        x = block(x, context=context[i])
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 269, in forward
        return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 121, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 136, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 697, in hacked_basic_transformer_inner_forward
        x = self.attn2(self.norm2(x), context=context) + x
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/ec2-user/SageMaker/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 461, in xformers_attention_forward
        out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=get_xformers_flash_attention_op(q, k, v))
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 192, in memory_efficient_attention
        return _memory_efficient_attention(
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 290, in _memory_efficient_attention
        return _memory_efficient_attention_forward(
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 310, in _memory_efficient_attention_forward
        out, *_ = op.apply(inp, needs_gradient=False)
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/xformers/ops/fmha/flash.py", line 235, in apply
        ) = _convert_input_format(inp)
      File "/home/ec2-user/anaconda3/envs/ui/lib/python3.10/site-packages/xformers/ops/fmha/flash.py", line 177, in _convert_input_format
        key=key.reshape([batch * seqlen_kv, num_heads, head_dim_q]),
    RuntimeError: shape '[154, 8, 40]' is invalid for input of size 24640
```

**Comment by wbclark** [comment]
Facing the same issue (it happens with the other reference_* preprocessors as well, and also in text2img mode)

I've tried the following, none worked to fix it:
  - Disabling xformers
  - Upcast cross attention layer to float32
  - Started with --precision full --no-half

**Comment by wbclark** [comment]
I figured out what was causing it for me -- it's an interaction between reference_* preprocessors and composable diffusion like `$prompt1 AND $prompt2` when one or more of the prompts has >75 tokens. Compare these two prompts:

I. `$prompt2` has <= 75 tokens, works with or without reference_* preprocessor

```
a photo of a beloved pet
AND dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog
```

II. `$prompt2` has >75 tokens, works without reference_* preprocessor but fails when reference_* preprocessor is enabled

```
a photo of a beloved pet
AND dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog dog
```

**Comment by Razunter** [comment]
I have this with empty prompt in txt2img on SD.NEXT

```
│ f:\Soft\SDNext\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                                  │
│                                                                                                                      │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                              │
│   1502 │   │   # Do not call functions when jit is used                                                              │
│                                                                                                                      │
│ F:\Soft\SDNext\modules\sd_hijack_optimizations.py:372 in scaled_dot_product_attention_forward                        │
│                                                                                                                      │
│   371 │   q = q_in.view(batch_size, -1, h, head_dim).transpose(1, 2)                                                 │
│ ❱ 372 │   k = k_in.view(batch_size, -1, h, head_dim).transpose(1, 2)                                                 │
│   373 │   v = v_in.view(batch_size, -1, h, head_dim).transpose(1, 2)                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: shape '[2, -1, 8, 40]' is invalid for input of size 24640
```

**Comment by Razunter** [comment]
I've reset my SD settings completely and now it works 🤷‍♂️

**Comment by vixenius** [comment]
disabling hypertile in settings fixed it for me
