### ISSUE TITLE
[Bug]: Error loading script: lora_script.py

### ISSUE THREAD

**Issue by AuYuHui** [Mikubill/sd-webui-controlnet#1825]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

SD-webUI:V 1.5.0
ControlNet: V1.1.233
ubuntu: 20.22

```
*** Error loading script: lora_script.py
    Traceback (most recent call last):
      File "/home/atmob/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/atmob/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/home/atmob/stable-diffusion-webui/extensions-builtin/Lora/scripts/lora_script.py", line 7, in <module>
        import network
      File "/home/atmob/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 101, in <module>
        class ModuleType:
      File "/home/atmob/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 102, in ModuleType
        def create_module(self, net: Network, weights: NetworkWeights) -> Network | None:
    TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

---
```

### Steps to reproduce the problem

sh webui.sh  --listen --no-half-vae

### What should have happened?

no error

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
sh webui.sh  --listen --no-half-vae
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/38815121/0d543b63-4b80-430c-8165-1c560aa75215)

### Console logs

```Shell
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.9.17 (main, Jul  5 2023, 20:41:20) 
[GCC 11.2.0]
Version: v1.5.0
Commit hash: a3ddf464a2ed24c999f67ddfef7969f8291567be

Launching Web UI with arguments: --listen --no-half-vae
No module 'xformers'. Proceeding without it.
2023-07-25 14:29:38,626 - ControlNet - INFO - ControlNet v1.1.233
ControlNet preprocessor location: /home/atmob/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-07-25 14:29:38,727 - ControlNet - INFO - ControlNet v1.1.233
*** Error loading script: lora_script.py
    Traceback (most recent call last):
      File "/home/atmob/stable-diffusion-webui/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/home/atmob/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/home/atmob/stable-diffusion-webui/extensions-builtin/Lora/scripts/lora_script.py", line 7, in <module>
        import network
      File "/home/atmob/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 101, in <module>
        class ModuleType:
      File "/home/atmob/stable-diffusion-webui/extensions-builtin/Lora/network.py", line 102, in ModuleType
        def create_module(self, net: Network, weights: NetworkWeights) -> Network | None:
    TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

---
Loading weights [4199bcdd14] from /home/atmob/stable-diffusion-webui/models/Stable-diffusion/revAnimated_v122.safetensors
```

**Comment by huchenlei** [comment]
Based on stacktrace, I don’t think this is a controlnet issue. Please file issue in a1111 repo. Thanks.
