### ISSUE TITLE
[Bug]: ControlNet Model is None!

### ISSUE THREAD

**Issue by p0mad** [Mikubill/sd-webui-controlnet#1838]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/131435526/42edc548-aa8c-4ffd-a723-34cbdf97ebd1)
while controlnet preview shows the openpose, but the model is none!
and can not be changed and also it wont affect the generated im2im or tex2im , ...

what would be the problem?

### Steps to reproduce the problem

1. Go to tex2im
2. Press enable controlnet unit1 
3. check preview and pixel perfect!
4. preprocessor to openpose-full or any other types
5. model choose is empty! you can only use none
6.  when i hit run preprocess it can generate openpose preview
7. it wont generate images on the main tab

### What should have happened?

it should generate images based on the controlnet
and also controlnet model should be open to choose from options but its none!

### Commit where the problem happens

webui: version: [v1.5.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a3ddf464a2ed24c999f67ddfef7969f8291567be)  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.32.0  •  checkpoint: [6ce0161689](https://google.com/search?q=6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa)
controlnet: ControlNet v1.1.233

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
None!
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/131435526/82438a1a-271f-43d8-af83-91f5af3f3fa1)

### Console logs

```Shell
---
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  7.90it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  7.49it/s]
*** Error running process: D:\ABC\extensions\sd-webui-controlnet\scripts\controlnet.py█████████| 16/16 [00:02<00:00,  8.36it/s]
    Traceback (most recent call last):
      File "D:\ABC\modules\scripts.py", line 495, in process
        script.process(p, *script_args)
      File "D:\ABC\extensions\sd-webui-controlnet\scripts\controlnet.py", line 731, in process
        model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
      File "D:\ABC\extensions\sd-webui-controlnet\scripts\controlnet.py", line 292, in load_control_model
        model_net = Script.build_control_model(p, unet, model, lowvram)
      File "D:\ABC\extensions\sd-webui-controlnet\scripts\controlnet.py", line 302, in build_control_model
        raise RuntimeError(f"You have not selected any ControlNet Model.")
    RuntimeError: You have not selected any ControlNet Model.
```

**Comment by sd707589** [comment]
@p0mad Hi, I am encountering the same bug as you. How did you solve this?
