### ISSUE TITLE
点击爆炸按钮的时候报了一个错误，求解决，我的stable-diffusion-webui版本是v1.3.2 ，controlnet版本是v1.1.132

### ISSUE THREAD

**Issue by wosilusheng** [Mikubill/sd-webui-controlnet#1842]
Preview Resolution = 512
Traceback (most recent call last):
  File "/Users/lusheng01/code/open/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/lusheng01/code/open/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Users/lusheng01/code/open/stable-diffusion-webui/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/lusheng01/code/open/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/lusheng01/code/open/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/lusheng01/code/open/stable-diffusion-webui/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/lusheng01/code/open/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 543, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b, json_pose_callback=json_acceptor.accept)
  File "/Users/lusheng01/code/open/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 208, in run_model
    from annotator.openpose import OpenposeDetector
  File "/Users/lusheng01/code/open/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/__init__.py", line 16, in <module>
    from . import util
  File "/Users/lusheng01/code/open/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/util.py", line 127, in <module>
    def draw_handpose(canvas: np.ndarray, keypoints: List[Keypoint] | None) -> np.ndarray:
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'

**Comment by huchenlei** [comment]
Update your controlnet please. 1.1.132 is a very old version. So does the 1.3 webui. 

The error you are seeing is caused by running python version below 3.10. Webui requires python 3.10.
