### ISSUE TITLE
[Bug]: raise RuntimeError(f"model not found: {model}")     RuntimeError: model not found: None

### ISSUE THREAD

**Issue by nbalive2k** [Mikubill/sd-webui-controlnet#1849]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The controlnet works perfectly in img2img or txt2img generation,
But in deforum, i get this error when i try to enable any controlnet tab

Reading ControlNet 1 base frame #1 at /content/stable-diffusion-webui/outputs/img2img-images/Deforum_20230731181650/controlnet_1_inputframes/000000001.jpg
*** Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 474, in process
        script.process(p, *script_args)
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 736, in process
        model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 292, in load_control_model
        model_net = Script.build_control_model(p, unet, model, lowvram)
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 310, in build_control_model
        raise RuntimeError(f"model not found: {model}")
    RuntimeError: model not found: None

==
I have all controlnet models downloaded

### Steps to reproduce the problem

1. Go to deforum controlnet tab
2. Press ''enable'' on any CN Model
3. Generate
![xa](https://github.com/Mikubill/sd-webui-controlnet/assets/88097321/8e1f28c2-f294-496f-8350-56872a9f188d)

### What should have happened?

the controlnet work with deforum
with this error it just doesn't work
the result is exactly the same as if it were disabled

### Commit where the problem happens

webui: [1.4.1]
controlnet: v1.1.234

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![ex](https://github.com/Mikubill/sd-webui-controlnet/assets/88097321/db591c73-576c-42f1-922c-b505ce1854e2)

### Console logs

```Shell
Reading ControlNet 1 base frame #1 at /content/stable-diffusion-webui/outputs/img2img-images/Deforum_20230731181650/controlnet_1_inputframes/000000001.jpg
*** Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 474, in process
        script.process(p, *script_args)
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 736, in process
        model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 292, in load_control_model
        model_net = Script.build_control_model(p, unet, model, lowvram)
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 310, in build_control_model
        raise RuntimeError(f"model not found: {model}")
    RuntimeError: model not found: None
```

**Comment by Mahdigouadria7** [comment]
did you find any solution ?
