### ISSUE TITLE
Failed to launch controlnet.py and xyz_grid_support.py

### ISSUE THREAD

**Issue by SaladSaladSaladSalad** [Mikubill/sd-webui-controlnet#185]
This is the log

Error loading script: controlnet.py
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 33, in <module>
    from svglib.svglib import svg2rlg
  File "/usr/local/lib/python3.9/dist-packages/svglib/svglib.py", line 46, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/usr/lib/python3/dist-packages/lxml/__init__.py)

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "/notebooks/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/notebooks/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/xyz_grid_support.py", line 2, in <module>
    from scripts import controlnet
  File "/notebooks/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 33, in <module>
    from svglib.svglib import svg2rlg
  File "/usr/local/lib/python3.9/dist-packages/svglib/svglib.py", line 46, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/usr/lib/python3/dist-packages/lxml/__init__.py)

Same error occures every time.

**Comment by Mikubill** [comment]
Added some workaround. update and retry

**Comment by SaladSaladSaladSalad** [comment]
Fixed perfectly! Thanks a lot...
