### ISSUE TITLE
[Bug]: Cannot import name 'appdirs' from  'pkg_resources.extern'

### ISSUE THREAD

**Issue by minhnhat0709** [Mikubill/sd-webui-controlnet#1873]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I run my google colab notebook with latest automatic1111 and controlnet branch. Last night everything is working normally, but today the controlnet is not working.
I have checked the log and see this: 

*** Error running install.py for extension /content/stable-diffusion-webui/extensions/sd-webui-controlnet.
*** Command: "/usr/bin/python3" "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py"
*** Error code: 1
*** stdout: Installing sd-webui-controlnet requirement: mediapipe
*** Installing sd-webui-controlnet requirement: svglib
*** Installing sd-webui-controlnet requirement: fvcore
*** Installing sd-webui-controlnet requirement: openmim
*** 
*** stderr: Traceback (most recent call last):
***   File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py", line 49, in <module>
***     install_mim_packages(mim_packages)
***   File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py", line 39, in install_mim_packages
***     packages = {p for (p, *_) in mim.list_package()}
***   File "/usr/local/lib/python3.10/dist-packages/mim/commands/list.py", line 43, in list_package
***     importlib.reload(pkg_resources)
***   File "/usr/lib/python3.10/importlib/__init__.py", line 169, in reload
***     _bootstrap._exec(spec, module)
***   File "<frozen importlib._bootstrap>", line 619, in _exec
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 74, in <module>
***     from pkg_resources.extern import appdirs
*** ImportError: cannot import name 'appdirs' from 'pkg_resources.extern' (/usr/local/lib/python3.10/dist-packages/pkg_resources/extern/__init__.py)
Installing requirements for diffusers

### Steps to reproduce the problem

1. Clone lastest Automatic1111
2. Clone lastest controlnet-webui
3. Run Automatic1111

### What should have happened?

The controlnet showing for use

### Commit where the problem happens

controlnet: not showing on webui and log error

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--api --share --listen --theme dark --xformers --enable-insecure-extension-access --multiple --ui-config-file /content/drive/MyDrive/StableDiffusion/Setting/ui-config.json --ui-settings-file /content/drive/MyDrive/StableDiffusion/Setting/config.json --ckpt /content/drive/MyDrive/StableDiffusion/Model/RealisticVision_V30.safetensors --ckpt-dir /content/drive/MyDrive/StableDiffusion/Model/ --lora-dir /content/drive/MyDrive/StableDiffusion/Lora/ --embeddings-dir /content/drive/MyDrive/StableDiffusion/Embeddings --styles-file /content/drive/MyDrive/StableDiffusion/Setting/styles.csv --hypernetwork-dir /content/drive/MyDrive/StableDiffusion/Hypernetworks
```

### List of enabled extensions

https://github.com/Mikubill/sd-webui-controlnet
https://github.com/camenduru/sd-webui-tunnels
https://github.com/ashen-sensored/stable-diffusion-webui-two-shot
https://github.com/adieyal/sd-dynamic-prompts
https://github.com/DominikDoom/a1111-sd-webui-tagcomplete
https://github.com/zanllp/sd-webui-infinite-image-browsing
https://github.com/Uminosachi/sd-webui-inpaint-anything
https://github.com/hako-mikan/sd-webui-lora-block-weight

### Console logs

```Shell
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Cloning Stable Diffusion into /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning into '/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai'...
remote: Enumerating objects: 574, done.
remote: Counting objects: 100% (311/311), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 574 (delta 244), reused 219 (delta 219), pack-reused 263
Receiving objects: 100% (574/574), 73.43 MiB | 46.33 MiB/s, done.
Resolving deltas: 100% (276/276), done.
Cloning Stable Diffusion XL into /content/stable-diffusion-webui/repositories/generative-models...
Cloning into '/content/stable-diffusion-webui/repositories/generative-models'...
remote: Enumerating objects: 423, done.
remote: Counting objects: 100% (246/246), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 423 (delta 155), reused 121 (delta 93), pack-reused 177
Receiving objects: 100% (423/423), 22.27 MiB | 35.63 MiB/s, done.
Resolving deltas: 100% (193/193), done.
Cloning K-diffusion into /content/stable-diffusion-webui/repositories/k-diffusion...
Cloning into '/content/stable-diffusion-webui/repositories/k-diffusion'...
remote: Enumerating objects: 735, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 735 (delta 4), reused 6 (delta 4), pack-reused 724
Receiving objects: 100% (735/735), 143.59 KiB | 2.39 MiB/s, done.
Resolving deltas: 100% (482/482), done.
Cloning CodeFormer into /content/stable-diffusion-webui/repositories/CodeFormer...
Cloning into '/content/stable-diffusion-webui/repositories/CodeFormer'...
remote: Enumerating objects: 594, done.
remote: Counting objects: 100% (245/245), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 594 (delta 176), reused 167 (delta 147), pack-reused 349
Receiving objects: 100% (594/594), 17.31 MiB | 35.16 MiB/s, done.
Resolving deltas: 100% (287/287), done.
Cloning BLIP into /content/stable-diffusion-webui/repositories/BLIP...
Cloning into '/content/stable-diffusion-webui/repositories/BLIP'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 277 (delta 137), reused 136 (delta 135), pack-reused 112
Receiving objects: 100% (277/277), 7.03 MiB | 25.54 MiB/s, done.
Resolving deltas: 100% (152/152), done.
Installing requirements for CodeFormer
Installing requirements
Collecting dynamicprompts[attentiongrabber,magicprompt]~=0.29.0
  Downloading dynamicprompts-0.29.0-py2.py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.3/48.3 kB 997.7 kB/s eta 0:00:00
Requirement already satisfied: jinja2~=3.1 in /usr/local/lib/python3.10/dist-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (3.1.2)
Requirement already satisfied: pyparsing~=3.0 in /usr/local/lib/python3.10/dist-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (3.1.0)
Requirement already satisfied: transformers[torch]~=4.19 in /usr/local/lib/python3.10/dist-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (4.25.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2~=3.1->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (2.1.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (3.12.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (0.16.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (2022.10.31)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (2.27.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (4.65.0)
Requirement already satisfied: torch!=1.12.0,>=1.7 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (2.0.1+cu118)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.10.0->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.10.0->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (4.7.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (3.1)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (16.0.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (3.4)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch!=1.12.0,>=1.7->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.29.0) (1.3.0)
Installing collected packages: dynamicprompts
Successfully installed dynamicprompts-0.29.0
sd-dynamic-prompts installer: running /usr/bin/python3 -m pip install 'dynamicprompts[attentiongrabber,magicprompt]~=0.29.0'

*** Error running install.py for extension /content/stable-diffusion-webui/extensions/sd-webui-controlnet.
*** Command: "/usr/bin/python3" "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py"
*** Error code: 1
*** stdout: Installing sd-webui-controlnet requirement: mediapipe
*** Installing sd-webui-controlnet requirement: svglib
*** Installing sd-webui-controlnet requirement: fvcore
*** Installing sd-webui-controlnet requirement: openmim
*** 
*** stderr: Traceback (most recent call last):
***   File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py", line 49, in <module>
***     install_mim_packages(mim_packages)
***   File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/install.py", line 39, in install_mim_packages
***     packages = {p for (p, *_) in mim.list_package()}
***   File "/usr/local/lib/python3.10/dist-packages/mim/commands/list.py", line 43, in list_package
***     importlib.reload(pkg_resources)
***   File "/usr/lib/python3.10/importlib/__init__.py", line 169, in reload
***     _bootstrap._exec(spec, module)
***   File "<frozen importlib._bootstrap>", line 619, in _exec
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 74, in <module>
***     from pkg_resources.extern import appdirs
*** ImportError: cannot import name 'appdirs' from 'pkg_resources.extern' (/usr/local/lib/python3.10/dist-packages/pkg_resources/extern/__init__.py)
Installing requirements for diffusers
Installing requirements for segment_anything
Installing requirements for lama_cleaner
Installing requirements for ultralytics

Installing sd-webui-infinite-image-browsing requirement: python-dotenv
Installing sd-webui-infinite-image-browsing requirement: pyfunctional

Installing pycloudflared

Launching Web UI with arguments: --api --share --listen --theme dark --xformers --enable-insecure-extension-access --multiple --ui-config-file /content/drive/MyDrive/StableDiffusion/Setting/ui-config.json --ui-settings-file /content/drive/MyDrive/StableDiffusion/Setting/config.json --ckpt /content/drive/MyDrive/StableDiffusion/Model/RealisticVision_V30.safetensors --ckpt-dir /content/drive/MyDrive/StableDiffusion/Model/ --lora-dir /content/drive/MyDrive/StableDiffusion/Lora/ --embeddings-dir /content/drive/MyDrive/StableDiffusion/Embeddings --styles-file /content/drive/MyDrive/StableDiffusion/Setting/styles.csv --hypernetwork-dir /content/drive/MyDrive/StableDiffusion/Hypernetworks
2023-08-05 03:33:44.238031: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 11, in <module>
        from scripts import external_code, global_state
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
        from scripts import external_code
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 13, in <module>
        from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version, utils
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
2023-08-05 03:33:58,279 - ControlNet - INFO - ControlNet v1.1.237
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 5, in <module>
        from scripts import global_state
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
*** Error loading script: global_state.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
*** Error loading script: processor.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 8, in <module>
        import mmengine
    ModuleNotFoundError: No module named 'mmengine'

---
all detected, remote.moe trying to connect...
Warning: Permanently added 'localhost.run' (RSA) to the list of known hosts.
all detected, cloudflared trying to connect...
Download cloudflared...: 100% 34.5M/34.5M [00:00<00:00, 176MB/s]
Calculating sha256 for /content/drive/MyDrive/StableDiffusion/Model/RealisticVision_V30.safetensors: Public WebUI Colab URL: None 
Public WebUI Colab URL: https://4148b945-de77-4d06.gradio.live 
Public WebUI Colab URL: https://953a85844f72cc.lhr.life
Please do not use this link we are getting ERROR: Exception in ASGI application:  https://cf2edb5f69cea95dff.gradio.live
Public WebUI Colab URL: https://encourage-expo-drop-distance.trycloudflare.com
Startup time: 268.7s (launcher: 220.7s, import torch: 13.6s, import gradio: 1.2s, setup paths: 2.9s, other imports: 2.1s, setup codeformer: 0.7s, list SD models: 1.4s, load scripts: 16.6s, create ui: 4.2s, gradio launch: 3.5s, add APIs: 1.5s, app_started_callback: 0.3s).
c52892e92a397c09938c55ed30b1702bd9346542dbf50467a7085ff8e27f4ed1
Loading weights [c52892e92a] from /content/drive/MyDrive/StableDiffusion/Model/RealisticVision_V30.safetensors
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
```

**Comment by huchenlei** [comment]
GPT suspects this stacktrace caused by python environment. The PR should make other parts of ControlNet remain functional if you do not use DW openpose preprocessor.

Following is the text answer from GPT:

The error you are encountering, `ImportError: cannot import name 'appdirs' from 'pkg_resources.extern'`, suggests there's a problem with your Python environment, specifically with the `pkg_resources` package.

This can happen due to various reasons:

1. The `pkg_resources` package is not installed properly.
2. You have multiple Python installations and there's confusion between them.
3. There's a mismatch between Python versions used for installing packages and running the code.

Here are a few steps you could try to resolve this:

1. Upgrade setuptools:

    ```bash
    pip install --upgrade setuptools
    ```

2. If the error persists, try uninstalling and reinstalling `pkg_resources`. This is a part of setuptools, so reinstall setuptools:

    ```bash
    pip uninstall setuptools
    pip install setuptools
    ```

3. If you're using a virtual environment, deactivate and reactivate it. Sometimes the environment can get into a bad state.

    ```bash
    deactivate
    source venv/bin/activate  # Or however you activate your environment
    ```

4. Check if you have multiple Python installations. Use `which python` and `which pip` to check the Python and pip being used.

5. Ensure `appdirs` package is installed:

    ```bash
    pip install appdirs
    ```

These steps should help solve the error. If none of these work, it's possible there may be deeper issues with your Python environment setup.

**Comment by minhnhat0709** [comment]
I have folked the repository, and revert commit last night. Then everything is working normally. Thanks
