### ISSUE TITLE
Error loading script: controlnet.py on Paperspace webUI

### ISSUE THREAD

**Issue by KttKrl** [Mikubill/sd-webui-controlnet#189]
Hello! I'm sorry to trouble you!
Is it possible to run the controlNet in the webui on Paperspace? I did all in your instruction but I have errror with loading controlnet.py. Thank you for your time and attention! 

When I run it I have this message 
Error loading script: controlnet.py
Traceback (most recent call last):
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/storage/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/storage/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 34, in <module>
    from svglib.svglib import svg2rlg
  File "/usr/local/lib/python3.9/dist-packages/svglib/svglib.py", line 46, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/usr/lib/python3/dist-packages/lxml/__init__.py)

**Comment by Mikubill** [comment]
https://github.com/Mikubill/sd-webui-controlnet/commit/2d91ef71e0a63b0076c166d8066d13193bf108d1 fixed this. try update the extension (maybe reinstall or git pul) and restart webui

**Comment by KttKrl** [comment]
ok, it's working! Thank you very much!!!!!!!!!

**Comment by adron02** [comment]
> [2d91ef7](https://github.com/Mikubill/sd-webui-controlnet/commit/2d91ef71e0a63b0076c166d8066d13193bf108d1) fixed this. try update the extension (maybe reinstall or git pul) and restart webui

I have a similar problem:

ControlNet v1.1.152
Error loading script: controlnet.py
Traceback (most recent call last):
  File "C:\Stable Difusion(AI)\stable-diffusion-webui-master\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Stable Difusion(AI)\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Stable Difusion(AI)\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 32, in <module>
    from modules.ui_components import FormRow
ModuleNotFoundError: No module named 'modules.ui_components'

How to fix it?
