### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ControlNet

### ISSUE THREAD

**Issue by sss28765431** [Mikubill/sd-webui-controlnet#19]
Help! what the wrong it is...

Loaded state_dict from [E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\models\Anything3.ckpt]
Error running process: E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 247, in process
    network = PlugableControlModel(model_path, os.path.join(cn_models_dir, "cldm_v15.yaml"), weight, lowvram=lowvram)
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 49, in __init__
    self.control_model.load_state_dict(state_dict)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:

**Comment by Mikubill** [comment]
Hmm, could you share the whole log? Seems like it is truncated.

**Comment by Mikubill** [comment]
btw, put ControlNet models into `extensions\sd-webui-controlnet\models` not SD Model.

**Comment by sss28765431** [comment]
OK, may be I forget to use ControlNet models. This is another problem while I am trying to use ControlNet models. 

To create a public link, set `share=True` in `launch()`.
loading preprocessor: none, model: control_any3_canny(95070f75)
Loaded state_dict from [E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_any3_canny.pth]
ControlNet model control_any3_canny(95070f75) loaded.
  0%|                                                                                                                                                                                                                | 0/20 [00:02<?, ?it/s]
Error completing request
Arguments: ('task(4ugt8u234467qjt)', 'masterpiece,best quality, looking at viewer', '(low quality, worst quality:1.4)', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', True, 'none', 'control_any3_canny(95070f75)', 1, {'image': array([[[ 44,  97,  87],
        [ 43,  96,  90],
        [ 43,  95,  93],
        ...,
        [ 33,  78,  81],
        [ 34,  78,  81],
        [ 33,  77,  80]],

       [[ 43,  96,  86],
        [ 42,  95,  89],
        [ 42,  94,  92],
        ...,
        [ 33,  78,  81],
        [ 34,  78,  81],
        [ 33,  77,  80]],

       [[ 40,  96,  87],
        [ 39,  94,  88],
        [ 41,  93,  91],
        ...,
        [ 33,  78,  83],
        [ 33,  78,  83],
        [ 34,  77,  83]],

       ...,

       [[252, 253, 255],
        [252, 255, 255],
        [244, 249, 255],
        ...,
        [255, 250, 238],
        [255, 250, 238],
        [255, 250, 238]],

       [[255, 254, 251],
        [255, 255, 255],
        [248, 253, 255],
        ...,
        [254, 250, 238],
        [254, 250, 238],
        [254, 250, 238]],

       [[255, 254, 251],
        [255, 255, 255],
        [248, 253, 255],
        ...,
        [254, 250, 238],
        [254, 250, 238],
        [254, 250, 238]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', True, False, False, 'positive', 'comma', False, False, '', 1, '', 0, '', 0, '', True, False, False, False, False) {}
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\AI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "E:\AI\stable-diffusion-webui\modules\processing.py", line 484, in process_images
    res = process_images_inner(p)
  File "E:\AI\stable-diffusion-webui\modules\processing.py", line 626, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "E:\AI\stable-diffusion-webui\modules\processing.py", line 826, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "E:\AI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 290, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "E:\AI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 190, in launch_sampling
    return func()
  File "E:\AI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 290, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\AI\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 100, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\AI\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "E:\AI\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "E:\AI\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "E:\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 97, in forward2
    return forward(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 70, in forward
    emb = self.time_embed(t_emb)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\AI\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 178, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "E:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)

**Comment by Mikubill** [comment]
No idea about this issue. Try switching models or change VAE config?

**Comment by sss28765431** [comment]
Thank you. no bug after update SD webui.

**Comment by jkalkhof** [comment]
I had the same problem, but resolved it by making sure that the SD model matched the version of the controlnet models.
See settings below:
stable diffusion checkpoint: v1-5-pruned-emaonly.ckpt 
model: control_sd15_openpose

controlnet models from here:
https://huggingface.co/lllyasviel/ControlNet/tree/main/models
https://huggingface.co/lllyasviel/ControlNet/blob/main/models/control_sd15_openpose.pth
sd models from here:
https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/main/v1-5-pruned-emaonly.ckpt
