### ISSUE TITLE
[Bug]: Error after using dwpose preprocessor: Failed to parse ONNX model

### ISSUE THREAD

**Issue by richadlee** [Mikubill/sd-webui-controlnet#1905]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

**Bug Description**:
After using the dwpose preprocessor, I encountered an error related to parsing the ONNX model using OpenCV.

**Error Message**:
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:275: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\annotator\downloads\openpose\yolox_l.onnx in function 'cv::dnn::dnn4_v20221220::ONNXImporter::ONNXImporter'

### Steps to reproduce the problem

1.Controlnet selects the input image and selects dwpose_ Full preprocessor

2.Click to preview the image

3.An error occurred

### What should have happened?

The ONNX model should be parsed successfully without any errors.

### Commit where the problem happens

webui: 
controlnet: 
The above error message is thrown when trying to parse the ONNX model.

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--autolaunch --xformers --theme dark --api
```

### List of enabled extensions

StylePile	
a1111-sd-webui-lycoris	
ebsynth_utility	
multidiffusion-upscaler-for-automatic1111	
novelai-2-local-prompt	
openpose-editor	
posex	
sd-dynamic-prompts
sd-webui-controlnet	
sd-webui-depth-lib	
sd-webui-lora-block-weight
sd-webui-model-converter
sd-webui-segment-anything
sd-webui-supermerger	
sd_dreambooth_extension	
sdweb-merge-block-weighted-gui	
stable-diffusion-webui-composable-lora	
stable-diffusion-webui-pixelization
stable-diffusion-webui-two-shot
stable-diffusion-webui-wd14-tagger	
tagcomplete	
prompt-bracket-checker

### Console logs

```Shell
2023-08-11 10:08:21,619 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "D:\00_AI\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\00_AI\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\00_AI\stable-diffusion-webui_23-02-17\python\lib\site-packages\gradio\blocks.py", line 1051, in call_function    prediction = await anyio.to_thread.run_sync(
  File "D:\00_AI\stable-diffusion-webui_23-02-17\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\00_AI\stable-diffusion-webui_23-02-17\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\00_AI\stable-diffusion-webui_23-02-17\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run    result = context.run(func, *args)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 609, in run_annotator
    result, is_image = preprocessor(
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\utils.py", line 79, in decorated_func
    return cached_func(*args, **kwargs)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\utils.py", line 67, in cached_func
    return func(*args, **kwargs)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\scripts\processor.py", line 252, in run_model
    return remove_pad(self.model_openpose(
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 358, in __call__
    poses = self.detect_poses_dw(oriImg)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 331, in detect_poses_dw
    self.load_dw_model()
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 215, in load_dw_model
    self.dw_pose_estimation = Wholebody(onnx_det, onnx_pose)
  File "D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\annotator\openpose\wholebody.py", line 20, in __init__
    self.session_det = cv2.dnn.readNetFromONNX(onnx_det)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:275: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\annotator\downloads\openpose\yolox_l.onnx in function 'cv::dnn::dnn4_v20221220::ONNXImporter::ONNXImporter'
```

**Comment by huchenlei** [comment]
Please upgrade you opencv to 4.8.0.

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/pull/1897

**Comment by richadlee** [comment]
> Please upgrade you opencv to 4.8.0.

Same error after upgraded:
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:279: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: D:\00_AI\stable-diffusion-webui_23-02-17\extensions\sd-webui-controlnet\annotator\downloads\openpose\yolox_l.onnx in function 'cv::dnn::dnn4_v20230620::ONNXImporter::ONNXImporter'

**Comment by huchenlei** [comment]
Can you confirm that your model file is not corrupted? You can manually download the model from huggingface.

**Comment by richadlee** [comment]
> huggingface

Could you please provide a download link?

**Comment by richadlee** [comment]
> Can you confirm that your model file is not corrupted? You can manually download the model from huggingface.

I redownload it from huggingface. Fixed!
Thanks!!
https://huggingface.co/yzd-v/DWPose/tree/main
