### ISSUE TITLE
Error loading LeReS depth model.

### ISSUE THREAD

**Issue by CyberLykan** [Mikubill/sd-webui-controlnet#197]
```
Loading preprocessor: depth_leres, model: res101 [cd701da0]
Loaded state_dict from [D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\models\res101.pth]
Error running process: D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 446, in process
    network = network_module(
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 107, in __init__
    self.control_model.load_state_dict(state_dict)
  File "D:\My Stuff\Extra Stuff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:
        Missing key(s) in state_dict: "time_embed.0.weight", "time_embed.0.bias", "time_embed.2.weight", "time_embed.2.bias", "input_blocks.0.0.weight", "input_blocks.0.0.bias", "input_blocks.1.0.in_layers.0.weight", "input_blocks.1.0.in_layers.0.bias", "input_blocks.1.0.in_layers.2.weight", "input_blocks.1.0.in_layers.2.bias", "input_blocks.1.0.emb_layers.1.weight", "input_blocks.1.0.emb_layers.1.bias", "input_blocks.1.0.out_layers.0.weight", "input_blocks.1.0.out_layers.0.bias", "input_blocks.1.0.out_layers.3.weight", "input_blocks.1.0.out_layers.3.bias", "input_blocks.1.1.norm.weight", "input_blocks.1.1.norm.bias", "input_blocks.1.1.proj_in.weight", "input_blocks.1.1.proj_in.bias", "input_blocks.1.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.1.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.1.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.1.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.1.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.1.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.1.1.transformer_blocks.0.norm1.weight", "input_blocks.1.1.transformer_blocks.0.norm1.bias", "input_blocks.1.1.transformer_blocks.0.norm2.weight", "input_blocks.1.1.transformer_blocks.0.norm2.bias", "input_blocks.1.1.transformer_blocks.0.norm3.weight", "input_blocks.1.1.transformer_blocks.0.norm3.bias", "input_blocks.1.1.proj_out.weight", "input_blocks.1.1.proj_out.bias", "input_blocks.2.0.in_layers.0.weight", "input_blocks.2.0.in_layers.0.bias", "input_blocks.2.0.in_layers.2.weight", "input_blocks.2.0.in_layers.2.bias", "input_blocks.2.0.emb_layers.1.weight", "input_blocks.2.0.emb_layers.1.bias", "input_blocks.2.0.out_layers.0.weight", "input_blocks.2.0.out_layers.0.bias", "input_blocks.2.0.out_layers.3.weight", "input_blocks.2.0.out_layers.3.bias", "input_blocks.2.1.norm.weight", "input_blocks.2.1.norm.bias", "input_blocks.2.1.proj_in.weight", "input_blocks.2.1.proj_in.bias", "input_blocks.2.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.2.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.2.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.2.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.2.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.2.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.2.1.transformer_blocks.0.norm1.weight", "input_blocks.2.1.transformer_blocks.0.norm1.bias", "input_blocks.2.1.transformer_blocks.0.norm2.weight", "input_blocks.2.1.transformer_blocks.0.norm2.bias", "input_blocks.2.1.transformer_blocks.0.norm3.weight", "input_blocks.2.1.transformer_blocks.0.norm3.bias", "input_blocks.2.1.proj_out.weight", "input_blocks.2.1.proj_out.bias", "input_blocks.3.0.op.weight", "input_blocks.3.0.op.bias", "input_blocks.4.0.in_layers.0.weight", "input_blocks.4.0.in_layers.0.bias", "input_blocks.4.0.in_layers.2.weight", "input_blocks.4.0.in_layers.2.bias", "input_blocks.4.0.emb_layers.1.weight", "input_blocks.4.0.emb_layers.1.bias", "input_blocks.4.0.out_layers.0.weight", "input_blocks.4.0.out_layers.0.bias", "input_blocks.4.0.out_layers.3.weight", "input_blocks.4.0.out_layers.3.bias", "input_blocks.4.0.skip_connection.weight", "input_blocks.4.0.skip_connection.bias", "input_blocks.4.1.norm.weight", "input_blocks.4.1.norm.bias", "input_blocks.4.1.proj_in.weight", "input_blocks.4.1.proj_in.bias", "input_blocks.4.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.4.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.4.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.4.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.4.1.transformer_blocks.0.norm1.weight", "input_blocks.4.1.transformer_blocks.0.norm1.bias", "input_blocks.4.1.transformer_blocks.0.norm2.weight", "input_blocks.4.1.transformer_blocks.0.norm2.bias", "input_blocks.4.1.transformer_blocks.0.norm3.weight", "input_blocks.4.1.transformer_blocks.0.norm3.bias", "input_blocks.4.1.proj_out.weight", "input_blocks.4.1.proj_out.bias", "input_blocks.5.0.in_layers.0.weight", "input_blocks.5.0.in_layers.0.bias", "input_blocks.5.0.in_layers.2.weight", "input_blocks.5.0.in_layers.2.bias", "input_blocks.5.0.emb_layers.1.weight", "input_blocks.5.0.emb_layers.1.bias", "input_blocks.5.0.out_layers.0.weight", "input_blocks.5.0.out_layers.0.bias", "input_blocks.5.0.out_layers.3.weight", "input_blocks.5.0.out_layers.3.bias", "input_blocks.5.1.norm.weight", "input_blocks.5.1.norm.bias", "input_blocks.5.1.proj_in.weight", "input_blocks.5.1.proj_in.bias", "input_blocks.5.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.5.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.5.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.5.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.5.1.transformer_blocks.0.norm1.weight", "input_blocks.5.1.transformer_blocks.0.norm1.bias", "input_blocks.5.1.transformer_blocks.0.norm2.weight", "input_blocks.5.1.transformer_blocks.0.norm2.bias", "input_blocks.5.1.transformer_blocks.0.norm3.weight", "input_blocks.5.1.transformer_blocks.0.norm3.bias", "input_blocks.5.1.proj_out.weight", "input_blocks.5.1.proj_out.bias", "input_blocks.6.0.op.weight", "input_blocks.6.0.op.bias", "input_blocks.7.0.in_layers.0.weight", "input_blocks.7.0.in_layers.0.bias", "input_blocks.7.0.in_layers.2.weight", "input_blocks.7.0.in_layers.2.bias", "input_blocks.7.0.emb_layers.1.weight", "input_blocks.7.0.emb_layers.1.bias", "input_blocks.7.0.out_layers.0.weight", "input_blocks.7.0.out_layers.0.bias", "input_blocks.7.0.out_layers.3.weight", "input_blocks.7.0.out_layers.3.bias", "input_blocks.7.0.skip_connection.weight", "input_blocks.7.0.skip_connection.bias", "input_blocks.7.1.norm.weight", "input_blocks.7.1.norm.bias", "input_blocks.7.1.proj_in.weight", "input_blocks.7.1.proj_in.bias", "input_blocks.7.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.7.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.7.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.7.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.7.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.7.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.7.1.transformer_blocks.0.norm1.weight", "input_blocks.7.1.transformer_blocks.0.norm1.bias", "input_blocks.7.1.transformer_blocks.0.norm2.weight", "input_blocks.7.1.transformer_blocks.0.norm2.bias", "input_blocks.7.1.transformer_blocks.0.norm3.weight", "input_blocks.7.1.transformer_blocks.0.norm3.bias", "input_blocks.7.1.proj_out.weight", "input_blocks.7.1.proj_out.bias", "input_blocks.8.0.in_layers.0.weight", "input_blocks.8.0.in_layers.0.bias", "input_blocks.8.0.in_layers.2.weight", "input_blocks.8.0.in_layers.2.bias", "input_blocks.8.0.emb_layers.1.weight", "input_blocks.8.0.emb_layers.1.bias", "input_blocks.8.0.out_layers.0.weight", "input_blocks.8.0.out_layers.0.bias", "input_blocks.8.0.out_layers.3.weight", "input_blocks.8.0.out_layers.3.bias", "input_blocks.8.1.norm.weight", "input_blocks.8.1.norm.bias", "input_blocks.8.1.proj_in.weight", "input_blocks.8.1.proj_in.bias", "input_blocks.8.1.transformer_blocks.0.attn1.to_q.weight", "input_blocks.8.1.transformer_blocks.0.attn1.to_k.weight", "input_blocks.8.1.transformer_blocks.0.attn1.to_v.weight", "input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.weight", "input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.bias", "input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.weight", "input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.bias", "input_blocks.8.1.transformer_blocks.0.ff.net.2.weight", "input_blocks.8.1.transformer_blocks.0.ff.net.2.bias", "input_blocks.8.1.transformer_blocks.0.attn2.to_q.weight", "input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.bias", "input_blocks.8.1.transformer_blocks.0.norm1.weight", "input_blocks.8.1.transformer_blocks.0.norm1.bias", "input_blocks.8.1.transformer_blocks.0.norm2.weight", "input_blocks.8.1.transformer_blocks.0.norm2.bias", "input_blocks.8.1.transformer_blocks.0.norm3.weight", "input_blocks.8.1.transformer_blocks.0.norm3.bias", "input_blocks.8.1.proj_out.weight", "input_blocks.8.1.proj_out.bias", "input_blocks.9.0.op.weight", "input_blocks.9.0.op.bias", "input_blocks.10.0.in_layers.0.weight", "input_blocks.10.0.in_layers.0.bias", "input_blocks.10.0.in_layers.2.weight", "input_blocks.10.0.in_layers.2.bias", "input_blocks.10.0.emb_layers.1.weight", "input_blocks.10.0.emb_layers.1.bias", "input_blocks.10.0.out_layers.0.weight", "input_blocks.10.0.out_layers.0.bias", "input_blocks.10.0.out_layers.3.weight", "input_blocks.10.0.out_layers.3.bias", "input_blocks.11.0.in_layers.0.weight", "input_blocks.11.0.in_layers.0.bias", "input_blocks.11.0.in_layers.2.weight", "input_blocks.11.0.in_layers.2.bias", "input_blocks.11.0.emb_layers.1.weight", "input_blocks.11.0.emb_layers.1.bias", "input_blocks.11.0.out_layers.0.weight", "input_blocks.11.0.out_layers.0.bias", "input_blocks.11.0.out_layers.3.weight", "input_blocks.11.0.out_layers.3.bias", "zero_convs.0.0.weight", "zero_convs.0.0.bias", "zero_convs.1.0.weight", "zero_convs.1.0.bias", "zero_convs.2.0.weight", "zero_convs.2.0.bias", "zero_convs.3.0.weight", "zero_convs.3.0.bias", "zero_convs.4.0.weight", "zero_convs.4.0.bias", "zero_convs.5.0.weight", "zero_convs.5.0.bias", "zero_convs.6.0.weight", "zero_convs.6.0.bias", "zero_convs.7.0.weight", "zero_convs.7.0.bias", "zero_convs.8.0.weight", "zero_convs.8.0.bias", "zero_convs.9.0.weight", "zero_convs.9.0.bias", "zero_convs.10.0.weight", "zero_convs.10.0.bias", "zero_convs.11.0.weight", "zero_convs.11.0.bias", "input_hint_block.0.weight", "input_hint_block.0.bias", "input_hint_block.2.weight", "input_hint_block.2.bias", "input_hint_block.4.weight", "input_hint_block.4.bias", "input_hint_block.6.weight", "input_hint_block.6.bias", "input_hint_block.8.weight", "input_hint_block.8.bias", "input_hint_block.10.weight", "input_hint_block.10.bias", "input_hint_block.12.weight", "input_hint_block.12.bias", "input_hint_block.14.weight", "input_hint_block.14.bias", "middle_block.0.in_layers.0.weight", "middle_block.0.in_layers.0.bias", "middle_block.0.in_layers.2.weight", "middle_block.0.in_layers.2.bias", "middle_block.0.emb_layers.1.weight", "middle_block.0.emb_layers.1.bias", "middle_block.0.out_layers.0.weight", "middle_block.0.out_layers.0.bias", "middle_block.0.out_layers.3.weight", "middle_block.0.out_layers.3.bias", "middle_block.1.norm.weight", "middle_block.1.norm.bias", "middle_block.1.proj_in.weight", "middle_block.1.proj_in.bias", "middle_block.1.transformer_blocks.0.attn1.to_q.weight", "middle_block.1.transformer_blocks.0.attn1.to_k.weight", "middle_block.1.transformer_blocks.0.attn1.to_v.weight", "middle_block.1.transformer_blocks.0.attn1.to_out.0.weight", "middle_block.1.transformer_blocks.0.attn1.to_out.0.bias", "middle_block.1.transformer_blocks.0.ff.net.0.proj.weight", "middle_block.1.transformer_blocks.0.ff.net.0.proj.bias", "middle_block.1.transformer_blocks.0.ff.net.2.weight", "middle_block.1.transformer_blocks.0.ff.net.2.bias", "middle_block.1.transformer_blocks.0.attn2.to_q.weight", "middle_block.1.transformer_blocks.0.attn2.to_k.weight", "middle_block.1.transformer_blocks.0.attn2.to_v.weight", "middle_block.1.transformer_blocks.0.attn2.to_out.0.weight", "middle_block.1.transformer_blocks.0.attn2.to_out.0.bias", "middle_block.1.transformer_blocks.0.norm1.weight", "middle_block.1.transformer_blocks.0.norm1.bias", "middle_block.1.transformer_blocks.0.norm2.weight", "middle_block.1.transformer_blocks.0.norm2.bias", "middle_block.1.transformer_blocks.0.norm3.weight", "middle_block.1.transformer_blocks.0.norm3.bias", "middle_block.1.proj_out.weight", "middle_block.1.proj_out.bias", "middle_block.2.in_layers.0.weight", "middle_block.2.in_layers.0.bias", "middle_block.2.in_layers.2.weight", "middle_block.2.in_layers.2.bias", "middle_block.2.emb_layers.1.weight", "middle_block.2.emb_layers.1.bias", "middle_block.2.out_layers.0.weight", "middle_block.2.out_layers.0.bias", "middle_block.2.out_layers.3.weight", "middle_block.2.out_layers.3.bias", "middle_block_out.0.weight", "middle_block_out.0.bias".
        Unexpected key(s) in state_dict: "depth_model", "shift_model", "focal_model".
```

**Comment by AugmentedRealityCat** [comment]
An alternative workflow for the moment would be to use[ the Depth Map extension](https://github.com/thygate/stable-diffusion-webui-depthmap-script) to synthesize your LeRes depth map first, and then use it directly as a source for depth map driven ControlNet .

**Comment by CyberLykan** [comment]
Nevermind, this was an error on my part. It seems the depth model can be used for both midas and leres.

Here, I think I tried loading the processor as the model.
