### ISSUE TITLE
Error loading script:

### ISSUE THREAD

**Issue by monmonchan** [Mikubill/sd-webui-controlnet#198]
The following error message appears and the file does not load properly.
Help

Error loading script: controlnet.py
Traceback (most recent call last):
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 16, in <module>
    from kohya_sd_scripts_webui.scripts.utils import load_state_dict
ModuleNotFoundError: No module named 'kohya_sd_scripts_webui'

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 2, in <module>
    from scripts import controlnet
  File "C:\Users\〇〇〇〇\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 16, in <module>
    from kohya_sd_scripts_webui.scripts.utils import load_state_dict
ModuleNotFoundError: No module named 'kohya_sd_scripts_webui'

**Comment by Mikubill** [comment]
cc @ddPn08

**Comment by taraxis1** [comment]
Having the same issue as well

**Comment by ddPn08** [comment]
I fixed it by temporarily renaming the file. It will be reflected if you update `kohya-sd-scripts-webui`.
https://github.com/ddPn08/kohya-sd-scripts-webui/commit/977c3f56ded8e405a8fa9d9b6d710c16298ef4d4

However, I honestly don't know if this is the correct way to fix it.

**Comment by monmonchan** [comment]
Thank you very much. Resolved.
