### ISSUE TITLE
[Bug]: AttributeError: 'dict' object has no attribute 'then'

### ISSUE THREAD

**Issue by Lucifer-101** [Mikubill/sd-webui-controlnet#1983]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

hii, so controlnet v311 was working fine and after the last updates to v312 I get new error at the start up of the running stable diffusion webui and warning when I try to generate image using V312 (controlnet v312 doest take any effect in my generated images) 
-
Note: I didnt change anything from my settings/setups/etc in v311

### Steps to reproduce the problem

...

### What should have happened?

...

### Commit where the problem happens

webui: python: 3.10.12  •  torch: 1.13.1+cu116  •  xformers: 0.0.16  •  gradio: 3.16.2  •  commit: 0cc0ee1b  •  checkpoint: e4b17ce185
-------------
controlnet: V312

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Launching Web UI with arguments: --listen --share --xformers --enable-insecure-extension-access --theme dark --gradio-queue --no-half-vae
```

### List of enabled extensions

a1111-sd-webui-locon-main			
batchlinks-webui-main			
sd-Webui-controlnet
sd-civitai-browser-main			
sd-webui-additional-networks-main			
sd-webui-tunnels-main			
sd_webui_stealth_pnginfo-main			
stable-diffusion-webui-catppuccin-main			
stable-diffusion-webui-huggingface-main			
stable-diffusion-webui-images-browser-main			
stable-diffusion-webui-rembg-master			
stable-diffusion-webui-two-shot-main			
LDSR	built-in		
Lora	built-in		
ScuNET	built-in		
SwinIR	built-in		
prompt-bracket-checker

### Console logs

```Shell
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
2023-08-25 10:14:09,160 - ControlNet - INFO - ControlNet v1.1.312
ControlNet preprocessor location: /content/ui/extensions/sd-Webui-controlnet/annotator/downloads
2023-08-25 10:14:09,523 - ControlNet - INFO - ControlNet v1.1.312
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Calculating sha256 for /content/ui/models/Stable-diffusion/anything-v4.5-pruned.ckpt: e4b17ce185857a3a20d778efb5222f32dfb65b89f258b29014a5659d319cb4bd
Loading weights [e4b17ce185] from /content/ui/models/Stable-diffusion/anything-v4.5-pruned.ckpt
Creating model from config: /content/ui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json: 100% 961k/961k [00:00<00:00, 7.23MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 4.05MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 2.41MB/s]
Downloading (…)okenizer_config.json: 100% 905/905 [00:00<00:00, 5.45MB/s]
Downloading (…)lve/main/config.json: 100% 4.52k/4.52k [00:00<00:00, 2.39MB/s]
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(9): ng_deepnegative_v1_75t, verybadimagenegative_v1.3, bad_prompt_version2, bad-image-v2-39000, bad-artist-anime, EasyNegativeV2, EasyNegative, bad-artist, bad-hands-5
Model loaded in 46.2s (calculate hash: 21.4s, load weights from disk: 10.9s, create model: 12.6s, apply weights to model: 1.1s).
Error calling: /content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py/ui
Traceback (most recent call last):
  File "/content/ui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py", line 283, in ui
    group, state = self.uigroup(f"ControlNet", is_img2img, elem_id_tabname)
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py", line 258, in uigroup
    group.register_callbacks(is_img2img)
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 771, in register_callbacks
    self.preset_panel.register_callbacks(self.type_filter, *[
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet_ui/preset.py", line 130, in register_callbacks
    ).then(
AttributeError: 'dict' object has no attribute 'then'

Error calling: /content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py/ui
Traceback (most recent call last):
  File "/content/ui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py", line 283, in ui
    group, state = self.uigroup(f"ControlNet", is_img2img, elem_id_tabname)
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet.py", line 258, in uigroup
    group.register_callbacks(is_img2img)
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 771, in register_callbacks
    self.preset_panel.register_callbacks(self.type_filter, *[
  File "/content/ui/extensions/sd-Webui-controlnet/scripts/controlnet_ui/preset.py", line 130, in register_callbacks
    ).then(
AttributeError: 'dict' object has no attribute 'then'

Running on local URL:  http://0.0.0.0:7860
Running on public URL: 

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
2023-08-25 10:19:04,952 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
2023-08-25 10:19:04,952 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
  0% 0/20 [00:00<?, ?it/s]
  5% 1/20 [00:12<03:55, 12.41s/it]
 10% 2/20 [00:12<01:38,  5.45s/it]
 15% 3/20 [00:13<00:55,  3.24s/it]
 20% 4/20 [00:14<00:35,  2.19s/it]
 25% 5/20 [00:14<00:24,  1.62s/it]
 30% 6/20 [00:15<00:17,  1.27s/it]
```

### Additional information

I didnt add any new extensions.

**Comment by huchenlei** [comment]
It's seems like gradio version problem. Try upgrade your a1111 to lastest version.
