### ISSUE TITLE
[Bug]: An error occurs when I put an image into the controlnet after the update.

### ISSUE THREAD

**Issue by toyxyz** [Mikubill/sd-webui-controlnet#1988]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

An error occurs when I put an image into the controlnet after the update. (d5137f063ebd1d31384957a8d3bea61ba5940fff)

Changing to a previous commit fixed the problem. bbabb39c6afa320b0a72ddffdc339eb9325230f1

### Steps to reproduce the problem

1. d5137f063ebd1d31384957a8d3bea61ba5940fff
2. Input image to controlnet

### What should have happened?

No errors should occur.

### Commit where the problem happens

webui: c9c8485bc1e8720aba70f029d25cba1c4abf2b5c
controlnet: d5137f063ebd1d31384957a8d3bea61ba5940fff

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--ckpt-dir --no-download-sd-model --opt-sdp-attention --api --no-half-vae --autolaunch
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/8006000/1fea71e2-d2f1-40c9-93f2-fdfb0a62f2f4)

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
Startup time: 61.9s (launcher: 37.3s, import torch: 6.2s, import gradio: 0.6s, setup paths: 0.6s, other imports: 1.1s, list SD models: 0.4s, load scripts: 8.1s, create ui: 6.0s, gradio launch: 0.6s, app_started_callback: 0.7s).
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 141, in svg_preprocess
    return preprocess(inputs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1842, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 51, in decode_base64_to_image
    image_encoded = extract_base64_data(encoding)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 42, in extract_base64_data
    return x.rsplit(",", 1)[-1]
AttributeError: 'NoneType' object has no attribute 'rsplit'
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 141, in svg_preprocess
    return preprocess(inputs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1842, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 51, in decode_base64_to_image
    image_encoded = extract_base64_data(encoding)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 42, in extract_base64_data
    return x.rsplit(",", 1)[-1]
AttributeError: 'NoneType' object has no attribute 'rsplit'
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1171, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 141, in svg_preprocess
    return preprocess(inputs)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1842, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 51, in decode_base64_to_image
    image_encoded = extract_base64_data(encoding)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 42, in extract_base64_data
    return x.rsplit(",", 1)[-1]
AttributeError: 'NoneType' object has no attribute 'rsplit'
```

**Comment by nikgrid7** [comment]
Yes I'm having an issue when I use Tile controlnet with Ultimate SD Upscale. I paste an image in controlnet open pose but when I add the tile controlnet I can see the image I just pasted and now when I use Ult SD upscale I get this error.

 TypeError: Script.run() missing 18 required positional arguments: '_', 'tile_width', 'tile_height', 'mask_blur', 'padding', 'seams_fix_width', 'seams_fix_denoise', 'seams_fix_padding', 'upscaler_index', 'save_upscaled_image', 'redraw_mode', 'save_seams_fix_image', 'seams_fix_mask_blur', 'seams_fix_type', 'target_size_type', 'custom_width', 'custom_height', and 'custom_scale'

**Comment by huchenlei** [comment]
Culprit reverted.
