### ISSUE TITLE
webui dosent work with img2img on google collab

### ISSUE THREAD

**Issue by revolverocelot1** [Mikubill/sd-webui-controlnet#199]
tried everything but it gives error only in collab not on local it gives the following error
Error completing request
Arguments: ('task(4twe4ewtmnxm602)', 2, ' (extremely detailed CG unity 8k wallpaper), masterpiece, (8k wallpaper), perfect, masterpiece, intimate composition, Cinestill 800T, modelshoot style, (8k wallpaper), perfect anatomy, masterpiece, highres, hdr, 8k, 85mm, Cinematic, sexual, (smirk), (big eyes), sexy', ' lace, intricate, out of frame, out of shot, child, childlike, clipping, 3d, cartoon, 3dcg, doll, render, lowres, bad anatomy, bad hands, text, error, illustration,multiple hands, old', [], <PIL.Image.Image image mode=RGBA size=345x659 at 0x7FB1A0D88790>, None, {'image': <PIL.Image.Image image mode=RGBA size=345x659 at 0x7FB1A0D88E80>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=345x659 at 0x7FB1A0D88250>}, None, None, None, None, 32, 16, 4, 0, 1, False, False, 5, 1, 7, 1.5, 0.7, -1.0, -1.0, 0, 0, 0, False, 816, 432, 0, 0, 44, 0, '', '', '', [], 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', True, 'canny', 'control_canny-fp16(e3fe7712)', 1, {'image': array([[[ 83,  83,  75],
        [ 52,  52,  42],
        [ 76,  79,  62],
        ...,
        [106, 107, 111],
        [195, 196, 198],
        [215, 216, 218]],

       [[183, 182, 177],
        [ 61,  61,  51],
        [ 72,  74,  60],
        ...,
        [131, 132, 136],
        [236, 237, 239],
        [232, 234, 233]],

       [[240, 241, 236],
        [172, 173, 167],
        [ 83,  85,  72],
        ...,
        [218, 222, 223],
        [224, 228, 227],
        [228, 230, 227]],

       ...,

       [[131, 117, 104],
        [136, 122, 109],
        [137, 123, 110],
        ...,
        [204, 209,  93],
        [125, 125,  25],
        [ 79,  76,   0]],

       [[131, 117, 104],
        [133, 119, 106],
        [143, 129, 116],
        ...,
        [145, 147,  38],
        [119, 116,  23],
        [ 86,  82,  11]],

       [[119, 105,  92],
        [136, 122, 109],
        [127, 113, 100],
        ...,
        [104, 106,   0],
        [132, 129,  36],
        [104, 100,  29]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/img2img.py", line 169, in img2img
    processed = process_images(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 628, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/content/stable-diffusion-webui/modules/processing.py", line 1044, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 302, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 221, in launch_sampling
    return func()
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 302, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 116, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/content/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 106, in forward2
    return forward(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 93, in forward
    h = torch.cat([h, hs_input + control_input * outer.weight], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 52 but got size 51 for tensor number 1 in the list.

**Comment by revolverocelot1** [comment]
this error on ui 
Sizes of tensors must match except in dimension 1. Expected size 52 but got size 51 for tensor number 1 in the list.

**Comment by revolverocelot1** [comment]
> this error on ui Sizes of tensors must match except in dimension 1. Expected size 52 but got size 51 for tensor number 1 in the list.

IT does work with txt2img weirdly. Hope anyone helps me

**Comment by revolverocelot1** [comment]
its solved i got it, someone has similar project with same name
