### ISSUE TITLE
[Bug]: `depth_zoe` preprocessor broken

### ISSUE THREAD

**Issue by huchenlei** [Mikubill/sd-webui-controlnet#1998]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

`depth_zoe` preprocessor is broken.

### Steps to reproduce the problem

- Upload an image
- Select `depth_zoe` as preprocessor
- Click run_preprocessor button
- Observe stacktrace in console

### What should have happened?

Should generate a depth map

### Commit where the problem happens

webui: dev branch (04cfcf91)
controlnet:  lastest checkout (eacfe99)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
"args": [
                "--no-half",
                "--api",
                "--xformers",
                "--theme",
                "dark",
                "--cors-allow-origins",
                "https://localhost:5173,https://huchenlei.github.io",
                "--controlnet-loglevel",
                "DEBUG"
            ]
```

### List of enabled extensions

ControlNet only

### Console logs

```Shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
2023-08-27 17:20:28,832 - ControlNet - DEBUG - Create LRU cache (max_size=16) for preprocessor results.
Startup time: 39.0s (prepare environment: 11.4s, import torch: 9.8s, import gradio: 2.1s, setup paths: 1.1s, initialize shared: 0.3s, other imports: 1.1s, setup codeformer: 0.3s, load scripts: 8.7s, create ui: 2.7s, gradio launch: 1.1s, add APIs: 0.3s).
Loading VAE weights specified in settings: D:\stable-diffusion-webui\models\Stable-diffusion\anygenz5.6.vae.pt
Applying attention optimization: xformers... done.
Model loaded in 15.7s (load weights from disk: 3.4s, create model: 0.8s, apply weights to model: 7.5s, apply float(): 1.2s, load VAE: 1.0s, calculate empty prompt: 1.6s).
2023-08-27 17:22:55,251 - ControlNet - INFO - Preview Resolution = 512
2023-08-27 17:22:55,252 - ControlNet - DEBUG - Calling preprocessor depth_zoe outside of cache.
img_size [384, 512]
Params passed to Resize transform:
        width:  512
        height:  384
        resize_target:  True
        keep_aspect_ratio:  True
        ensure_multiple_of:  32
        resize_method:  minimal
Traceback (most recent call last):
  File "d:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "d:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "d:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "d:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "d:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "d:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "d:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 629, in run_annotator
    result, is_image = preprocessor(
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 79, in decorated_func
    return cached_func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 67, in cached_func
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 519, in zoe_depth
    result = model_zoe_depth(img)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 47, in __call__
    depth = self.model.infer(image_depth)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\depth_model.py", line 126, in infer
    return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\depth_model.py", line 110, in infer_with_flip_aug
    out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\depth_model.py", line 88, in _infer_with_pad_aug
    out = self._infer(x)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\depth_model.py", line 55, in _infer
    return self(x)['metric_depth']
  File "d:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 144, in forward
    rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
  File "d:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas.py", line 269, in forward
    rel_depth = self.core(x)
  File "d:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\dpt_depth.py", line 166, in forward
    return super().forward(x).squeeze(dim=1)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\dpt_depth.py", line 114, in forward
    layers = self.forward_transformer(self.pretrained, x)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\backbones\beit.py", line 15, in forward_beit
    return forward_adapted_unflatten(pretrained, x, "forward_features")
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\backbones\utils.py", line 86, in forward_adapted_unflatten
    exec(f"glob = pretrained.model.{function_name}(x)")
  File "<string>", line 1, in <module>
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\backbones\beit.py", line 125, in beit_forward_features
    x = blk(x, resolution, shared_rel_pos_bias=rel_pos_bias)
  File "d:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\backbones\beit.py", line 102, in block_forward
    x = x + self.drop_path(self.gamma_1 * self.attn(self.norm1(x), resolution,
  File "d:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Block' object has no attribute 'drop_path'
```
```


### Additional information

_No response_

**Comment by lllyasviel** [comment]
https://github.com/isl-org/MiDaS/pull/234

**Comment by lllyasviel** [comment]
will fix later
