### ISSUE TITLE
[Bug]: Commits after Thursday Aug 31 2023 have broken preview function

### ISSUE THREAD

**Issue by raisindetre** [Mikubill/sd-webui-controlnet#2035]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Ran an update check and installed two hours ago and two recent commits broke previews in ControlNet.

Workaround was to checkout commit:

`commit c3b32f254368ffc96b6aae9eab0a8fe7450a359f
Author: lllyasviel <lyuminzhang@outlook.com>
Date:   Thu Aug 31 02:22:10 2023 -0700

    fix gradio (#2013)
`
`$ git checkout c3b32f254368ffc96b6aae9eab0a8fe7450a359f`

And restart UI. Preview now works.

### Steps to reproduce the problem

1. Run "Check for Updates" in Extensions pane of current Automatic1111.
2. Restart.
3. In ControlNet turn on "Preview" checkbox.
4. Attempt to preview Depth, OpenPose or other model with preview.
5. UI displays "No Preview in red" and does not display a preview.

### What should have happened?

Preview should have been generated.

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/e2cd3b91a8addb64a526c0eaa8d72469e0638e3c

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

sd-webui-controlnet
Plus all built-in.

### Console logs

```Shell
Traceback (most recent call last):
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui.old/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 697, in run_annotator
    *self.openpose_editor.update(json_acceptor.value),
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui.old/extensions/sd-webui-controlnet/scripts/controlnet_ui/openpose_editor.py", line 109, in update
    html = f"""<a href='{encode_data_url(json_string)}'
  File "/Users/username/Documents/Projects/StableDiffusion/stable-diffusion-webui.old/extensions/sd-webui-controlnet/scripts/controlnet_ui/openpose_editor.py", line 24, in encode_data_url
    base64_encoded_json = base64.b64encode(json_string.encode("utf-8")).decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'
```

### Additional information

Running on OSX 13.5.1 Ventura.

**Comment by alexbofa** [comment]
The same

**Comment by kid77vad** [comment]
Only the "Preprocessor Preview" window errors, models work

**Comment by Bonifes07** [comment]
same here

**Comment by sv-hmelevsky** [comment]
Same...
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/4187388/b8d00d20-4cd2-4d74-b9a3-f79103202536)

**Comment by lllyasviel** [comment]
fixed just now

**Comment by LeoMaster26** [comment]
It's good that it's fixed, yes I just updated it :3
