### ISSUE TITLE
[Bug]: ControlNet-M2M script FileNotFoundError

### ISSUE THREAD

**Issue by darrynGit** [Mikubill/sd-webui-controlnet#2045]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When using the ControlNet-M2M script to process a video file the processing proceeds normally. The processed images are created but at the end of the processing the following error appears and the gif sequences are not saved.

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\TRAINING\\StableDiffusion\\ControlNet\\outputs/txt2img-images/controlnet-m2m'

Manually creating the "controlnet-m2m" directory at the path the script is looking for allows the gif sequences to be created and saved into the folder.

### Steps to reproduce the problem

1. Enable ControlNet
2. Set the parameters
3. Select the "controlnet m2m" script from the Scripts dropdown
4. Add a video file to the "Movie Input"
5. Set the duration
6. Select "Save preprocessed"
7. Click "Generate"

### What should have happened?

The normal behaviour should be that the script automatically creates the required directory to save the gif sequences into

### Commit where the problem happens

webui: AUTOMATIC1111 v1.6.0 
controlnet: v1.1.400 (Same error occurred in the previous version of Control Net)

python: 3.10.6
torch: 2.0.1+cu118
xformers: 0.0.20
gradio: 3.41.2
checkpoint: 6ce0161689

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --theme dark --no-half
```

### List of enabled extensions

<img width="696" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/141466252/4c9868c3-dc01-4299-8125-6cd4e0bd3488">

### Console logs

```Shell
venv "C:\Users\darry\Documents\StableDiffusion\Automatic1111\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --xformers --theme dark --no-half
2023-09-05 15:10:52,231 - ControlNet - INFO - ControlNet v1.1.400
ControlNet preprocessor location: C:\Users\darry\Documents\StableDiffusion\Automatic1111\extensions\sd-webui-controlnet\annotator\downloads
2023-09-05 15:10:52,576 - ControlNet - INFO - ControlNet v1.1.400
Loading weights [6ce0161689] from C:\Users\darry\Documents\StableDiffusion\Automatic1111\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\darry\Documents\StableDiffusion\Automatic1111\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 29.2s (prepare environment: 5.1s, import torch: 6.8s, import gradio: 4.0s, setup paths: 4.6s, initialize shared: 0.3s, other imports: 5.0s, setup codeformer: 0.4s, load scripts: 1.9s, create ui: 0.8s, gradio launch: 0.7s).
Applying attention optimization: xformers... done.
Model loaded in 7.7s (load weights from disk: 0.7s, create model: 1.0s, apply weights to model: 3.2s, load textual inversion embeddings: 1.3s, calculate empty prompt: 1.4s).
10
2023-09-05 15:12:28,799 - ControlNet - INFO - Loading model: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:12:29,276 - ControlNet - INFO - Loaded state_dict from [C:\Users\darry\Documents\StableDiffusion\Automatic1111\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.pth]
2023-09-05 15:12:29,277 - ControlNet - INFO - controlnet_default_config
2023-09-05 15:12:31,836 - ControlNet - INFO - ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
2023-09-05 15:12:31,918 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:12:31,919 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:12:31,919 - ControlNet - INFO - preprocessor resolution = 512
100%|█████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.11it/s]
2023-09-05 15:12:36,598 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:12:36,598 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:12:36,600 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:12:36,600 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.68it/s]
2023-09-05 15:12:40,220 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:12:40,220 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:12:40,221 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:12:40,221 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.73it/s]
2023-09-05 15:12:43,821 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:12:43,822 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:12:43,824 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:12:43,825 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.81it/s]
2023-09-05 15:12:47,370 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:12:47,370 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:12:47,371 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:12:47,371 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.91it/s]
2023-09-05 15:12:50,913 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:12:50,913 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:12:50,914 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:12:50,914 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.77it/s]
2023-09-05 15:12:54,506 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:12:54,507 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:12:54,509 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:12:54,509 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.76it/s]
2023-09-05 15:12:58,111 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:12:58,112 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:12:58,115 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:12:58,115 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.73it/s]
2023-09-05 15:13:01,694 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:13:01,694 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:13:01,696 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:13:01,696 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.72it/s]
2023-09-05 15:13:05,325 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2023-09-05 15:13:05,326 - ControlNet - WARNING - Warn: Using legacy field 'p.controlnet_input_image'
2023-09-05 15:13:05,328 - ControlNet - INFO - Loading preprocessor: canny
2023-09-05 15:13:05,329 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.66it/s]
*** Error completing request,  6.75it/s]
*** Arguments: ('task(m5d689fv9qletqs)', 'Victorian era man', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x0000018CE24CC5E0>, 4, False, '', 0.8, -1, False, -1, 0, 0, 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000018CE25047F0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000018CE2504BB0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000018CE2505D80>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 'C:\\Users\\darry\\AppData\\Local\\Temp\\gradio\\9349f40103affd7d8f309eed8e788da23d24099a\\Video01_Short.mp4', None, True, None, None, False, None, None, False, 10) {}
    Traceback (most recent call last):
      File "C:\Users\darry\Documents\StableDiffusion\Automatic1111\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\darry\Documents\StableDiffusion\Automatic1111\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\darry\Documents\StableDiffusion\Automatic1111\modules\txt2img.py", line 52, in txt2img
        processed = modules.scripts.scripts_txt2img.run(p, *args)
      File "C:\Users\darry\Documents\StableDiffusion\Automatic1111\modules\scripts.py", line 601, in run
        processed = script.run(p, *script_args)
      File "C:\Users\darry\Documents\StableDiffusion\Automatic1111\extensions\sd-webui-controlnet\scripts\movie2movie.py", line 161, in run
        seq = images.get_next_sequence_number(f"{p.outpath_samples}{_BASEDIR}", "")
      File "C:\Users\darry\Documents\StableDiffusion\Automatic1111\modules\images.py", line 511, in get_next_sequence_number
        for p in os.listdir(path):
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\TRAINING\\StableDiffusion\\ControlNet\\outputs/txt2img-images/controlnet-m2m'

---
```

**Comment by lllyasviel** [comment]
I am not familiar with m2m. we need someone familiar with m2m to take a look
