### ISSUE TITLE
[Bug]: Runtime error running depth_zoe

### ISSUE THREAD

**Issue by tranzmatt** [Mikubill/sd-webui-controlnet#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Some commit broke ZOE depth and it still doesn't work

### Steps to reproduce the problem

Prior to breakage, this would generate a depth map

1. Load clean webui
2. Set dimensions to 768x768
3. Go to Controlnet
4. Load 768x768 image
5. Select Perfect Pixel, Depth, depth_zoe (use default model)
6. Run Preprocessor

### What should have happened?

A zoe depth map should have been produced

### Commit where the problem happens

webui (via vladmandic):  36001151bbbcbe817ff2103579f5df930571461e
controlnet: b15636ed35eff934af69985bcdfbc407cfedfe7d

### What browsers do you use to access the UI ?

Firefox

### Command Line Arguments

```Shell
--listen --insecure
```

### List of enabled extensions

a1111-sd-webui-lycoris  
LDSR  
multidiffusion-upscaler-for-automatic1111  
sd-dynamic-thresholding   
sd-webui-agent-scheduler  
stable-diffusion-webui-images-browser  
SwinIR
clip-interrogator-ext   
Lora  
ScuNET
sd-extension-system-info  
sd-webui-controlnet 
stable-diffusion-webui-rembg

### Console logs

```Shell
img_size [384, 512]
Params passed to Resize transform:
        width:  512
        height:  384
        resize_target:  True
        keep_aspect_ratio:  True
        ensure_multiple_of:  32
        resize_method:  minimal
Traceback (most recent call last):
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "/home/stable/automatic-stable-diffusion-webui/extensions-builtin/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 679, in run_annotator
    result, is_image = preprocessor(
  File "/home/stable/automatic-stable-diffusion-webui/extensions-builtin/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
    return cached_func(*args, **kwargs)
  File "/home/stable/automatic-stable-diffusion-webui/extensions-builtin/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
    return func(*args, **kwargs)
  File "/home/stable/automatic-stable-diffusion-webui/extensions-builtin/sd-webui-controlnet/scripts/global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "/home/stable/automatic-stable-diffusion-webui/extensions-builtin/sd-webui-controlnet/scripts/processor.py", line 517, in zoe_depth
    result = model_zoe_depth(img)
  File "/home/stable/automatic-stable-diffusion-webui/extensions-builtin/sd-webui-controlnet/annotator/zoe/__init__.py", line 38, in __call__
    self.load_model()
  File "/home/stable/automatic-stable-diffusion-webui/extensions-builtin/sd-webui-controlnet/annotator/zoe/__init__.py", line 28, in load_model
    model.load_state_dict(torch.load(modelpath, map_location=model.device)['model'])
  File "//home/stable/anaconda3/envs/vladmandic/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ZoeDepth:
        Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", "core.core.pretrained.model.blocks.1.attn.relative_position_index", "core.core.pretrained.model.blocks.2.attn.relative_position_index", "core.core.pretrained.model.blocks.3.attn.relative_position_index", "core.core.pretrained.model.blocks.4.attn.relative_position_index", "core.core.pretrained.model.blocks.5.attn.relative_position_index", "core.core.pretrained.model.blocks.6.attn.relative_position_index", "core.core.pretrained.model.blocks.7.attn.relative_position_index", "core.core.pretrained.model.blocks.8.attn.relative_position_index", "core.core.pretrained.model.blocks.9.attn.relative_position_index", "core.core.pretrained.model.blocks.10.attn.relative_position_index", "core.core.pretrained.model.blocks.11.attn.relative_position_index", "core.core.pretrained.model.blocks.12.attn.relative_position_index", "core.core.pretrained.model.blocks.13.attn.relative_position_index", "core.core.pretrained.model.blocks.14.attn.relative_position_index", "core.core.pretrained.model.blocks.15.attn.relative_position_index", "core.core.pretrained.model.blocks.16.attn.relative_position_index", "core.core.pretrained.model.blocks.17.attn.relative_position_index", "core.core.pretrained.model.blocks.18.attn.relative_position_index", "core.core.pretrained.model.blocks.19.attn.relative_position_index", "core.core.pretrained.model.blocks.20.attn.relative_position_index", "core.core.pretrained.model.blocks.21.attn.relative_position_index", "core.core.pretrained.model.blocks.22.attn.relative_position_index", "core.core.pretrained.model.blocks.23.attn.relative_position_index".
```

### Additional information

Others like Leras and Midas work.

**Comment by CodeLinyc** [comment]
Me too. Have you solved it yet？
