### ISSUE TITLE
[Bug]: "RuntimeError: Attempting to deserialize object on a CUDA device" error in Automatic1111 v1.6, ControlNet v1.1.409 - Mac ARM M2

### ISSUE THREAD

**Issue by raisindetre** [Mikubill/sd-webui-controlnet#2098]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Installed SD1.5 ip-adapter_* models from https://huggingface.co/lllyasviel/sd_control_collection/tree/main to v1.60 Automatic1111 using CN v1.1.409 and restarted. Using IP-Adapter within Control Net generates random images and an "Attempting to deserialize object on a CUDA device" runtime error. Other models tested (Reference, OpenPose) working as expected.

### Steps to reproduce the problem

1. In A1111 v1.6.0 OSX M2, download  ip-adapter_* models from https://huggingface.co/lllyasviel/sd_control_collection/tree/main 
2. Rename suffix *.bin to *.pth and place in ./extensions/sd-webui-controlnet/models
3. Restart A1111 from commandline.
4. Send image to txt2image
5. Delete prompt.
6. Enable ControlNet -> IP Adapter and select ip-adapter_sd15 model.
7. Load image from (4) into ControlNet.
8. Generate,
9. Random image generated and error thrown.

### What should have happened?

New image generated similar to image provided to Control Net.

### Commit where the problem happens

webui: 5ef669de080814067961f28357256e8fe27544f4
controlnet: b15636ed35eff934af69985bcdfbc407cfedfe7d

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Installation defaults in webui-macos-env.sh
COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate".
```

### List of enabled extensions

<img width="1076" alt="extensions" src="https://github.com/Mikubill/sd-webui-controlnet/assets/10620977/8e685df3-6381-4235-b904-5787ed5500f0">

### Console logs

```Shell
...
2023-09-10 21:04:57,087 - ControlNet - STATUS - preprocessor resolution = 512
*** Error running process: /Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 350, in clip
        from annotator.clipvision import ClipVisionDetector
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/clipvision/__init__.py", line 81, in <module>
        clip_vision_h_uc = torch.load(clip_vision_h_uc)['uc']
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/modules/safe.py", line 108, in load
        return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
        return unsafe_torch_load(filename, *args, **kwargs)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
        return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
        result = unpickler.load()
      File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pickle.py", line 1254, in load_binpersid
        self.append(self.persistent_load(pid))
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1142, in persistent_load
        typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1116, in load_tensor
        wrap_storage=restore_location(storage, location),
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 217, in default_restore_location
        result = fn(storage, location)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
        device = validate_cuda_device(location)
      File "/Users/guestuser/Documents/Projects/StableDiffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 166, in validate_cuda_device
        raise RuntimeError('Attempting to deserialize object on a CUDA '
    RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by HansonChan** [comment]
same error
 RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by pedro-sousamartins** [comment]
I've got exactly the **same error** on a Apple M1 Max (32GB ram) macbook pro.

**Comment by raisindetre** [comment]
A current workaround that has worked for me - need to do more testing to see if it's consistent - is to add the command-line flag "--no-half" to your launch settings. This has provided reasonable results and suppressed errors in the console. Interesting though, that the issue only occurs for these models.

**Comment by magimyster** [comment]
the same error even with --no half on, a few days ago it was working

**Comment by krummrey** [comment]
--no-half didn't help my setup:
```
M1 16gb
version: [v1.6.0] •  python: 3.10.9  •  torch: 2.0.1  •  xformers: N/A  •  gradio: 3.41.2  •  checkpoint: [9aba26abdf]
ControlNet v1.1.410
```
