### ISSUE TITLE
[Bug]: TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int]

### ISSUE THREAD

**Issue by Enferlain** [Mikubill/sd-webui-controlnet#2113]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Trying to use depth zoe with an image and pressing generate after enabling cn throws an error that I've never seen.

all the other preprocessors seem to work fine, seems like it's just depth zoe for some reason

torch: 2.2.0.dev20230911+rocm5.6 

### Steps to reproduce the problem

1. Be on amd
2. Follow the steps on the extension page 
3. generate or run preprocessor with depth_zoe selected

### What should have happened?

No errors

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/e67e017731aad05796b9615dc6eadce911298ea1

### Command Line Arguments

```Shell
None
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/15861396/2495410e-9e03-4792-96e3-f064d8a78ee6)

### Console logs

```Shell
*** Error running process: /home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/home/imi/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
                                 ^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 517, in zoe_depth
        result = model_zoe_depth(img)
                 ^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/__init__.py", line 47, in __call__
        depth = self.model.infer(image_depth)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/depth_model.py", line 126, in infer
        return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/depth_model.py", line 110, in infer_with_flip_aug
        out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/depth_model.py", line 88, in _infer_with_pad_aug
        out = self._infer(x)
              ^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/depth_model.py", line 55, in _infer
        return self(x)['metric_depth']
               ^^^^^^^
      File "/home/imi/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/zoedepth/zoedepth_v1.py", line 144, in forward
        rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
        return forward_call(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas.py", line 263, in forward
        x = self.prep(x)
            ^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas.py", line 187, in __call__
        return self.normalization(self.resizer(x))
                                  ^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/zoe/zoedepth/models/base_models/midas.py", line 174, in __call__
        return nn.functional.interpolate(x, (height, width), mode='bilinear', align_corners=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/imi/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/nn/functional.py", line 3924, in interpolate
        raise TypeError(
    TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.int64'>, <class 'numpy.int64'>]
```

### Additional information

Also ip2p preprocessor is missing

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/15861396/8324900a-519f-48db-9e83-d426d47029ed)

**Comment by iamwavecut** [comment]
@Enferlain had you luck fixing it?

**Comment by Enferlain** [comment]
Nah, still happens.

**Comment by Czxck001** [comment]
@Enferlain I met the same issue. I realized the culprit is incompatibility of the sd-webui-controlnet and torch==2.1.0. Moving back to torch==2.0.1 solved the issue on my side.

**Comment by fenneishi** [comment]
the bug is in "isl-org/ZoeDepth" and  controlNet using "isl-org/ZoeDepth",detail :
[isl-org/ZoeDepth](https://github.com/isl-org/ZoeDepth/issues/79)
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/33345538/9afff0df-3dfe-416c-94a5-bd108ea3ddbe)

**Comment by davidmartinrius** [comment]
> @Enferlain I met the same issue. I realized the culprit is incompatibility of the sd-webui-controlnet and torch==2.1.0. Moving back to torch==2.0.1 solved the issue on my side.

Ok, this is a workaround,  but when downgrading there are other things like image generation that may fail. Like when using the latest version of xformers.

**Comment by hudada-stack** [comment]
I solved this problem with type coercion，turn the variate be int

**Comment by rubenponsaers** [comment]
Solved it by converting numpy type to int:

`size = tuple([int(width), int(height)])
        return nn.functional.interpolate(x, size=size, mode='bilinear', align_corners=True)`

and

`size = tuple([int(new_height), int(new_width)])
    new_sub_table = F.interpolate(old_sub_table, size=size, mode="bilinear")`

**Comment by mchtey** [comment]
> @Enferlain I met the same issue. I realized the culprit is incompatibility of the sd-webui-controlnet and torch==2.1.0. Moving back to torch==2.0.1 solved the issue on my side.

_this method solved the problem for me. thanks. :)_
