### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'control_model'

### ISSUE THREAD

**Issue by thelordaa** [Mikubill/sd-webui-controlnet#2122]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/58760095/f0edda62-d45e-42fd-8689-cdf80614d41a)

Hello, if I use 'ReferenceOnly' without drawing on the image, it works normally. However, if I just draw the part I want from that image, I get an error. Regardless, the image continues rendering but without ControlNet.

this is the error:
2023-09-17 02:07:13,584 - ControlNet - INFO - using mask as input
2023-09-17 02:07:13,591 - ControlNet - INFO - Loading preprocessor: none
*** Error running process: C:\Users\***\Automatic1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\***\Automatic1111\webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\Users\***\Automatic1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "C:\Users\***\Automatic1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\***\Automatic1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 789, in controlnet_main_entry
        global_average_pooling = model_net.control_model.global_average_pooling
    AttributeError: 'NoneType' object has no attribute 'control_model'

### Steps to reproduce the problem

1. Go to ControlNet and select referenceOnly
2. drag and drop an image and draw what you want of the image like only the face
3. Press generate
4. Check the terminal for the error.

### What should have happened?

just process the part i'm drawing

### Commit where the problem happens

webui: 5ef669de080814067961f28357256e8fe27544f4
controlnet: e67e017

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --autolaunch --upcast-sampling
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/58760095/31f3d9e2-e137-4d31-b1f7-56f87bdbb439)

### Console logs

```Shell
Already up to date.
venv "C:\Users\Alex\Automatic1111\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --xformers --autolaunch --upcast-sampling
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.9.2, num models: 9
2023-09-17 02:21:13,943 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: C:\Users\Alex\Automatic1111\webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-17 02:21:14,191 - ControlNet - INFO - ControlNet v1.1.410
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [bff4610d23] from C:\Users\Alex\Automatic1111\webui\models\Stable-diffusion\epicrealism_naturalSin.safetensors
Creating model from config: C:\Users\Alex\Automatic1111\webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[Lobe]: Initializing Lobe
Startup time: 27.8s (prepare environment: 5.7s, import torch: 6.1s, import gradio: 1.7s, setup paths: 1.5s, initialize shared: 0.3s, other imports: 1.1s, setup codeformer: 0.2s, setup gfpgan: 0.2s, load scripts: 6.6s, create ui: 1.2s, gradio launch: 3.0s).
Loading VAE weights specified in settings: C:\Users\Alex\Automatic1111\webui\models\VAE\anythingKlF8Anime2VaeFtMse840000_klF8Anime2.safetensors
Applying attention optimization: xformers... done.
Model loaded in 14.7s (load weights from disk: 1.5s, create model: 0.8s, apply weights to model: 9.2s, load VAE: 2.5s, calculate empty prompt: 0.5s).
Traceback (most recent call last):
  File "C:\Users\Alex\Automatic1111\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Alex\Automatic1111\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\Alex\Automatic1111\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Alex\Automatic1111\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Alex\Automatic1111\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Alex\Automatic1111\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Alex\Automatic1111\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Alex\Automatic1111\webui\modules\ui_extra_networks.py", line 400, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Users\Alex\Automatic1111\webui\modules\ui_extra_networks.py", line 400, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "C:\Users\Alex\Automatic1111\webui\modules\ui_extra_networks.py", line 162, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "C:\Users\Alex\Automatic1111\webui\modules\ui_extra_networks.py", line 162, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "C:\Users\Alex\Automatic1111\webui\extensions-builtin\Lora\ui_extra_networks_lora.py", line 69, in list_items
    for index, name in enumerate(networks.available_networks):
RuntimeError: dictionary changed size during iteration
2023-09-17 02:23:20,672 - ControlNet - INFO - using mask as input
2023-09-17 02:23:20,677 - ControlNet - INFO - Loading preprocessor: none
*** Error running process: C:\Users\Alex\Automatic1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\Alex\Automatic1111\webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\Users\Alex\Automatic1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "C:\Users\Alex\Automatic1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\Alex\Automatic1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 789, in controlnet_main_entry
        global_average_pooling = model_net.control_model.global_average_pooling
    AttributeError: 'NoneType' object has no attribute 'control_model'

---
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
```

**Comment by gzlock** [comment]
Hi, did you resolved this issue?
When I use the controlnet + reference function, the console showed the error info same with yours:
```
*** Error running process: E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1053, in process
        self.controlnet_hack(p)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1042, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 859, in controlnet_main_entry
        global_average_pooling = model_net.control_model.global_average_pooling
    AttributeError: 'NoneType' object has no attribute 'control_model'
```

**Comment by jcward** [comment]
I got this error when I had accidentally painted some of the reference image with the brush tool. I removed / replaced the reference image, and tried again, and then it worked.
