### ISSUE TITLE
after update RuntimeError in img2img

### ISSUE THREAD

**Issue by sra-tatata** [Mikubill/sd-webui-controlnet#213]
version 

sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet | a24089a6 (Sun Feb 19 07:08:12 2023) | latest
-- | -- | -- | --

RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead

Loading preprocessor: canny, model: control_sd15_canny [fef5e48e]
Loaded state_dict from [/home/user/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_sd15_canny.pth]
ControlNet model control_sd15_canny [fef5e48e] loaded.
  0%|                                                    | 0/16 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(1yh9rxbafv4ig0e)', 0, 'cat', '', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x7F422037DFD0>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 0, True, 'canny', 'control_sd15_canny [fef5e48e]', 1, {'image': array([[[188, 216, 219],
        [185, 213, 221],
        [198, 229, 232],
        ...,
        [ 14,   9,  11],
        [ 13,  10,  13],
        [ 19,  16,  18]],

       [[189, 218, 224],
        [185, 214, 221],
        [198, 225, 229],
        ...,
        [ 16,  11,  17],
        [ 11,  13,  15],
        [ 14,  12,  14]],

       [[188, 216, 224],
        [185, 214, 220],
        [197, 224, 228],
        ...,
        [ 14,  11,  15],
        [ 12,  12,  16],
        [ 16,  15,  18]],

       ...,

       [[170, 185, 188],
        [170, 184, 188],
        [170, 186, 189],
        ...,
        [162, 104,  55],
        [158, 100,  51],
        [159, 100,  48]],

       [[168, 187, 187],
        [168, 185, 186],
        [170, 185, 188],
        ...,
        [160, 101,  52],
        [155,  95,  49],
        [156,  95,  44]],

       [[170, 185, 187],
        [168, 185, 186],
        [169, 183, 188],
        ...,
        [158,  98,  50],
        [155,  94,  48],
        [145,  91,  46]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, True, 512, 100, 200, 1, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/home/user/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/modules/img2img.py", line 169, in img2img
    processed = process_images(p)
  File "/home/user/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/home/user/stable-diffusion-webui/modules/processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/home/user/stable-diffusion-webui/modules/processing.py", line 1048, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/home/user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 322, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "/home/user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 322, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 117, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/home/user/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1333, in forward
    out = self.diffusion_model(xc, t, context=cc)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 168, in forward2
    return forward(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 134, in forward
    control = outer.control_model(x=x, hint=outer.hint_cond, timesteps=timesteps, context=context)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 456, in forward
    h = module(h, emb, context)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 86, in forward
    x = layer(x)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[2, 9, 64, 64] to have 4 channels, but got 9 channels instead

**Comment by Mikubill** [comment]
see https://github.com/Mikubill/sd-webui-controlnet/issues/112
