### ISSUE TITLE
[Bug]: When I use controlnet IP-Adapter by Mac M2 Mac OS venturer 13.4（22F66）Error happen

### ISSUE THREAD

**Issue by wealthbaka** [Mikubill/sd-webui-controlnet#2131]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I also have similar issue 
https://github.com/tencent-ailab/IP-Adapter/issues/53
a 

### Steps to reproduce the problem

1. Go to Control net use IP-Adapter
2. Use this model https://huggingface.co/lllyasviel/sd_control_collection/tree/main
4. Press generate
5. Error happen

### What should have happened?

*** Error running process: /Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/Users/username/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 350, in clip
        from annotator.clipvision import ClipVisionDetector
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/clipvision/__init__.py", line 81, in <module>
        clip_vision_h_uc = torch.load(clip_vision_h_uc)['uc']
      File "/Users/username/stable-diffusion-webui/modules/safe.py", line 108, in load
        return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
      File "/Users/username/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
        return unsafe_torch_load(filename, *args, **kwargs)
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
        return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
        result = unpickler.load()
      File "/Users/username/.pyenv/versions/3.10.4/lib/python3.10/pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "/Users/username/.pyenv/versions/3.10.4/lib/python3.10/pickle.py", line 1254, in load_binpersid
        self.append(self.persistent_load(pid))
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1142, in persistent_load
        typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1116, in load_tensor
        wrap_storage=restore_location(storage, location),
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 217, in default_restore_location
        result = fn(storage, location)
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
        device = validate_cuda_device(location)
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 166, in validate_cuda_device
        raise RuntimeError('Attempting to deserialize object on a CUDA '
    RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### Commit where the problem happens

webui: txt2img
controlnet: IP-Adapter

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

webui: txt2img
controlnet: IP-Adapter

### Console logs

```Shell
*** Error running process: /Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/Users/username/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 350, in clip
        from annotator.clipvision import ClipVisionDetector
      File "/Users/username/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/clipvision/__init__.py", line 81, in <module>
        clip_vision_h_uc = torch.load(clip_vision_h_uc)['uc']
      File "/Users/username/stable-diffusion-webui/modules/safe.py", line 108, in load
        return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
      File "/Users/username/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
        return unsafe_torch_load(filename, *args, **kwargs)
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
        return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
        result = unpickler.load()
      File "/Users/username/.pyenv/versions/3.10.4/lib/python3.10/pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "/Users/username/.pyenv/versions/3.10.4/lib/python3.10/pickle.py", line 1254, in load_binpersid
        self.append(self.persistent_load(pid))
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1142, in persistent_load
        typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1116, in load_tensor
        wrap_storage=restore_location(storage, location),
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 217, in default_restore_location
        result = fn(storage, location)
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
        device = validate_cuda_device(location)
      File "/Users/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 166, in validate_cuda_device
        raise RuntimeError('Attempting to deserialize object on a CUDA '
    RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by Aime-ry** [comment]
I also have the same issue.

**Comment by arony5** [comment]
same problem.

**Comment by arony5** [comment]
[raisindetre](https://github.com/raisindetre) commented [last week](https://github.com/Mikubill/sd-webui-controlnet/issues/2098#issuecomment-1716605802)
A current workaround that has worked for me - need to do more testing to see if it's consistent - is to add the command-line flag "--no-half" to your launch settings. This has provided reasonable results and suppressed errors in the console. Interesting though, that the issue only occurs for these models.


[艾梅里](https://github.com/Aime-ry) 评论道 [2天前](https://github.com/tencent-ailab/IP-Adapter/issues/53#issuecomment-1729322454)
这是因为您无法在 Mac 计算机上使用 CPU 预处理。要解决此问题，您可以使用文本编辑器或 IDE（例如 VSCode 或 PyCharm）打开位于 /stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/clipvision/ init .py 的文件。

1、导航到第 81 行并找到以下行：clip_vision_h_uc = torch.load(clip_vision_h_uc)['uc']。
2、修改这一行为：clip_vision_h_uc = torch.load(clip_vision_h_uc, map_location=torch.device('cpu'))['uc']。
3、保存更改并退出编辑器。
4、再次运行你的程序。这应该可以防止任何与 CUDA 相关的错误。
但是，即使进行此更改，您在生成图像时仍然可能会遇到错误。



It works fine

**Comment by Aime-ry** [comment]
If there is no --no-half option, can sdxl function normally? @arony5

**Comment by arony5** [comment]
> If there is no --no-half option, can sdxl function normally? @arony5

When I add the --no-half option and modify the init.py file, the SD 1.5 IP-Adapter works fine, but the SDXL does not function normally.
I have now reversed everything.

**Comment by AltairAlAnon** [comment]
Hello, dont know if M1 and M2 issues are similar, but on a
Apple M1 Max
13.6
Latest webui and ControlNet

Was getting an unrelated image and the following error:

    RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

So I changed line 81 in the init to:
clip_vision_h_uc = torch.load(clip_vision_h_uc, map_location=torch.device('cpu'))['uc']

Set my bat file to include:
set COMMANDLINE_ARGS= --medvram --opt-split-attention  --skip-torch-cuda-test --precision full --no-half 

And I still get an unrelated image with the following error:

*** Error running process: /Users/ /stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/Users/ /stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/Users/ stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/Users/ /stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/Users/ /stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 944, in controlnet_main_entry
        param.control_model.hook(
      File "/Users /stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/Users/ /stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 327, in hook
        self.image_emb, self.uncond_image_emb = self.ipadapter.get_image_embeds(clip_vision_output)
      File "/Users/ /stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/Users/ /stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 209, in get_image_embeds
        image_prompt_embeds = self.image_proj_model(clip_image_embeds)
      File "/Users/ /stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/Users/ /stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 24, in forward
        clip_extra_context_tokens = self.proj(embeds).reshape(-1, self.clip_extra_context_tokens,
      File "/Users/ /stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/Users/ /stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 429, in network_Linear_forward
        return originals.Linear_forward(self, input)
      File "/Users/ /stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1024 and 1280x8192)

**Comment by Ansyarai** [comment]
i have this issue when using this model (ip-adapter-plus-face_sd15 [71693645])
Can someone help me?


*** Error running process: C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\Ansya\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 351, in clip
        clip_encoder[config] = ClipVisionDetector(config)
      File "C:\Users\Ansya\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\clipvision\__init__.py", line 108, in __init__
        sd = torch.load(file_path, map_location=torch.device('cpu'))
      File "C:\Users\Ansya\stable-diffusion-webui\modules\safe.py", line 108, in load
        return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
      File "C:\Users\Ansya\stable-diffusion-webui\modules\safe.py", line 156, in load_with_extra
        return unsafe_torch_load(filename, *args, **kwargs)
      File "C:\Users\Ansya\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 797, in load
        with _open_zipfile_reader(opened_file) as opened_zipfile:
      File "C:\Users\Ansya\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 283, in __init__
        super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
    RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by jackykyd** [comment]
> I have referred to the following comments. just solved it, works fine
> 
> [raisindetre](https://github.com/raisindetre) commented [last week](https://github.com/Mikubill/sd-webui-controlnet/issues/2098#issuecomment-1716605802) A current workaround that has worked for me - need to do more testing to see if it's consistent - is to add the command-line flag "--no-half" to your launch settings. This has provided reasonable results and suppressed errors in the console. Interesting though, that the issue only occurs for these models.
> 
> [Aime-ry](https://github.com/Aime-ry) commented [2 days ago](https://github.com/tencent-ailab/IP-Adapter/issues/53#issuecomment-1729322454) This is because you can't use CPU preprocessing on a Mac computer. To fix this, you can open the file located at /stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/clipvision/init.py using a text editor or IDE (such as VSCode or PyCharm).
> 
> 1、Navigate to line 81 and locate the line: clip_vision_h_uc = torch.load(clip_vision_h_uc)['uc']. 2、Modify this line to: clip_vision_h_uc = torch.load(clip_vision_h_uc, map_location=torch.device('cpu'))['uc']. 3、Save your changes and exit the editor. 4、Run your program again. This should prevent any CUDA-related errors. However, even after this change, you may still encounter errors when generating images.

M1 Max, used this method, but still has the following ERROR
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

**Comment by Aime-ry** [comment]
> > I have referred to the following comments. just solved it, works fine
> > [raisindetre](https://github.com/raisindetre) commented [last week](https://github.com/Mikubill/sd-webui-controlnet/issues/2098#issuecomment-1716605802) A current workaround that has worked for me - need to do more testing to see if it's consistent - is to add the command-line flag "--no-half" to your launch settings. This has provided reasonable results and suppressed errors in the console. Interesting though, that the issue only occurs for these models.
> > [Aime-ry](https://github.com/Aime-ry) commented [2 days ago](https://github.com/tencent-ailab/IP-Adapter/issues/53#issuecomment-1729322454) This is because you can't use CPU preprocessing on a Mac computer. To fix this, you can open the file located at /stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/clipvision/init.py using a text editor or IDE (such as VSCode or PyCharm).
> > 1、Navigate to line 81 and locate the line: clip_vision_h_uc = torch.load(clip_vision_h_uc)['uc']. 2、Modify this line to: clip_vision_h_uc = torch.load(clip_vision_h_uc, map_location=torch.device('cpu'))['uc']. 3、Save your changes and exit the editor. 4、Run your program again. This should prevent any CUDA-related errors. However, even after this change, you may still encounter errors when generating images.
> 
> M1 Max, used this method, but still has the following ERROR TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

You can switch the model and run it again.

**Comment by Dreamz-Dziner** [comment]
> I have referred to the following comments. just solved it, works fine
> 
> [raisindetre](https://github.com/raisindetre) commented [last week](https://github.com/Mikubill/sd-webui-controlnet/issues/2098#issuecomment-1716605802) A current workaround that has worked for me - need to do more testing to see if it's consistent - is to add the command-line flag "--no-half" to your launch settings. This has provided reasonable results and suppressed errors in the console. Interesting though, that the issue only occurs for these models.
> 
> [Aime-ry](https://github.com/Aime-ry) commented [2 days ago](https://github.com/tencent-ailab/IP-Adapter/issues/53#issuecomment-1729322454) This is because you can't use CPU preprocessing on a Mac computer. To fix this, you can open the file located at /stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/clipvision/init.py using a text editor or IDE (such as VSCode or PyCharm).
> 
> 1、Navigate to line 81 and locate the line: clip_vision_h_uc = torch.load(clip_vision_h_uc)['uc']. 2、Modify this line to: clip_vision_h_uc = torch.load(clip_vision_h_uc, map_location=torch.device('cpu'))['uc']. 3、Save your changes and exit the editor. 4、Run your program again. This should prevent any CUDA-related errors. However, even after this change, you may still encounter errors when generating images.

Literally had been constantly deleting and reinstalling every repo and controlnet versions to solve this crazy issue dealing with clipvision models. I am not sure how many subreddits and github discussions I searched through to find that godsend solution. Finally I see it. Thank you from the bottom of my heart my friend. This method solved my problem. So relieved after all that hardship of 2 weeks. Words can't express my gratitude towards you:-). God bless you!

**Comment by huchenlei** [comment]
This should be fixed with https://github.com/Mikubill/sd-webui-controlnet/pull/2248. Please reopen if issue persists.
