### ISSUE TITLE
[Bug]: ControlNet doesn't apply anything

### ISSUE THREAD

**Issue by EpicDreamX** [Mikubill/sd-webui-controlnet#2135]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hello there,

my ControlNet doesnt apply any setting i do, i tried depth and openpose but it doesnt take any effect:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/85649233/21ad715e-b416-4ad5-8d1b-70eb4d2cd3b4)

i tried different diffusers, with and without preprocessors, different settings and sizes... its just ignored.

But i get some Errors in Console... im not sure if theyre related.
I even reinstalled the Webui 2 times, but never worked - but i dont know if that error was showing before.

Any idea why?

### Steps to reproduce the problem

Create a Depthmap or Openpose and send it to ControlNet.
Set all Settings
Generating a Picture.

### What should have happened?

Applying the ControlNet-Settings to the generation.

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
nothing special
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/85649233/89b61122-693c-41ea-852b-e820c3025817)

### Console logs

```Shell
100%|##########| 40/40 [00:09<00:00,  4.17it/s]
Total progress: 100%|██████████| 40/40 [00:09<00:00,  4.03it/s]s]
2023-09-19 23:25:41,700 - ControlNet - INFO*** Error running process: E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py
 - Loading model: control_v11p_sd15_openpose [e3b0c442]
    Traceback (most recent call last):
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\controlnet.py", line 349, in build_control_model
        state_dict = load_state_dict(model_path)
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\sd-webui-controlnet\scripts\utils.py", line 20, in load_state_dict
        state_dict = unsafe_torch_load(ckpt_path, map_location=torch.device(location))
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\serialization.py", line 815, in load
        return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
      File "E:\Program Files\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
        magic_number = pickle_module.load(f, **pickle_load_args)
    _pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by Woisek** [comment]
If you use an already made pose image, you must not select an pre-processor. Set it to none and try again.

**Comment by EpicDreamX** [comment]
Sorry, but i read that several times in my research and thus tried it - but to no avail. :/
The output with or without Controlnet and Preprocessor is always the same, as if its completely ignored

But thank you for this suggestion.

**Comment by DominikDoom** [comment]
From the error message, you can see that it fails to load the control model itself. _pickle.UnpicklingError: invalid load key, '<' at the end means that it fails to convert the file back to a python object. The file may be corrupted in some way. Make sure you've downloaded it correctly, for example by comparing the sha256 file hashes with those specified on huggingface.
You could also try using the pruned safetensor versions from https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/tree/main instead as a workaround.

**Comment by EpicDreamX** [comment]
Sry for the late reply, i downloaded everything again and compared it - tried even the pruned ones, but both didnt work for me.

**Comment by EpicDreamX** [comment]
Hm... after i reinstalled it, i get this Error:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/85649233/1f658bbd-bc3f-424f-a25e-f410f91ed177)

**Comment by DominikDoom** [comment]
Make absolutely sure you downloaded the right files, and that they are the expected file size (723mb for pruned fp16, 1.45GB for default, as listed on huggingface). This is another error that can happen if the file format is wrong. Some possible causes are:
- You downloaded the HTML file instead of the actual model from huggingface (happens if you use the right click "Save as" menu, you need to click on the download arrow in the file list instead).
   - Also read https://github.com/Mikubill/sd-webui-controlnet#download-models for more info.
- You downloaded the whole git repo, but Git LFS (large file storage) wasn't installed or activated. In that case you would've only downloaded a small pointer file, not the model it points to

**Comment by EpicDreamX** [comment]
I can't believe that im that stupid! -.-

After reinstalling controlnet and downloading the diffusers the correct way... it finally works!

Thank you very much!

**Comment by zmfltmaktm** [comment]
Hello friend, I have similar symptoms as you, so please tell me how to solve it. When running Control Net, images that are not applied are being printed. Have you reinstalled the stability matrix? Tell me more about it

![화면 캡처 2024-01-20 170056](https://github.com/Mikubill/sd-webui-controlnet/assets/157203149/9d79d891-7ac6-4c07-99fd-ba8c1fc55b4d)
