### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute '_id'

### ISSUE THREAD

**Issue by iurysouzatx** [Mikubill/sd-webui-controlnet#2136]
### Is there an existing issue for this?

- [ ] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Can't even launch the WebUI when ControlNet is installed.
I updated the ControlNet and that's it.

### Steps to reproduce the problem

Just open the WebUI

### What should have happened?

The WebUI started normally.

### Commit where the problem happens

webui: 5ef669de080814067961f28357256e8fe27544f4
controlnet: [e67e017](https://github.com/Mikubill/sd-webui-controlnet/commit/e67e017731aad05796b9615dc6eadce911298ea1)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers
```

### List of enabled extensions

Pixel Art

### Console logs

```Shell
*** Error calling: E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
    Traceback (most recent call last):
      File "E:\AI\SD\webui\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 288, in ui
        group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname)
      File "E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 268, in uigroup
        group.register_callbacks(is_img2img)
      File "E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 820, in register_callbacks
        self.preset_panel.register_callbacks(
      File "E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\preset.py", line 172, in register_callbacks
        getattr(element, action)(
      File "E:\AI\SD\system\python\lib\site-packages\gradio\events.py", line 140, in __call__
        dep, dep_index = self.trigger.set_event_trigger(
      File "E:\AI\SD\system\python\lib\site-packages\gradio\blocks.py", line 286, in set_event_trigger
        "inputs": [block._id for block in inputs],
      File "E:\AI\SD\system\python\lib\site-packages\gradio\blocks.py", line 286, in <listcomp>
        "inputs": [block._id for block in inputs],
    AttributeError: 'NoneType' object has no attribute '_id'

---
*** Error calling: E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
    Traceback (most recent call last):
      File "E:\AI\SD\webui\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 288, in ui
        group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname)
      File "E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 268, in uigroup
        group.register_callbacks(is_img2img)
      File "E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 820, in register_callbacks
        self.preset_panel.register_callbacks(
      File "E:\AI\SD\webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\preset.py", line 172, in register_callbacks
        getattr(element, action)(
      File "E:\AI\SD\system\python\lib\site-packages\gradio\events.py", line 140, in __call__
        dep, dep_index = self.trigger.set_event_trigger(
      File "E:\AI\SD\system\python\lib\site-packages\gradio\blocks.py", line 286, in set_event_trigger
        "inputs": [block._id for block in inputs],
      File "E:\AI\SD\system\python\lib\site-packages\gradio\blocks.py", line 286, in <listcomp>
        "inputs": [block._id for block in inputs],
    AttributeError: 'NoneType' object has no attribute '_id'

---
```

**Comment by Guillaume-Fgt** [comment]
in your `stable-diffusion-webui\extensions\sd-webui-controlnet` folder, do you have a presets folder? Is it empty? If not, try to delete this folder and reload the webui.

**Comment by PeterTF656** [comment]
same issue here

**Comment by iurysouzatx** [comment]
I don't know what caused this, but a new fresh install of SD got it to work again :/

**Comment by PeterTF656** [comment]
> I don't know what caused this, but a new fresh install of SD got it to work again :/

I tried a lot of fixes, but none worked. Finally I had to reinstall as well. Took me half a day... But I can make my waifus again now, so overall not bad...

**Comment by matthew-p-gilley** [comment]
Delete your `ui-config.json` and `config.json` files.

AUTO1111 will complain the files don't exist on starting the server; don't worry, it's just a warning. You can recreate them by going to `Settings `and clicking "`Apply settings`"

Hopefully this saves others from having to completely rebuild their install.

**Comment by CurtisDS** [comment]
@huchenlei This issue is still happening on the latest commit if I alter the order of the UI. You marked this as closed, Was it supposed to have been fixed?

**Comment by huchenlei** [comment]
Follow instructions in this comment:
https://github.com/Mikubill/sd-webui-controlnet/issues/2136#issuecomment-1741850364

**Comment by CurtisDS** [comment]
That doesn't fix the issue. See https://github.com/Mikubill/sd-webui-controlnet/issues/2136#issuecomment-1789932744 
As soon as I change the UI order back to the way I like it (using a built in setting of Automatic1111) the error occurs again.

It appears that Control Net is assuming the UI will be in a specific state when it shouldn't and thus leading to the gradio error. I don't mean to be pushy but since this is a repeatable and narrow issue with the extension not supporting a built in setting of Automatic1111 I hope it could be addressed with a proper fix of some kind.

**Comment by YuLinkun** [comment]
I print the list `inputs`, and found one of the list is empty, so I repair it by change `[block._id for block in inputs]` to `[block._id for block in inputs if block is not None]`. It works for me.
