### ISSUE TITLE
ControlNet v1.1.410 Not Work  "AttributeError: 'dict' object has no attribute 'then'"

### ISSUE THREAD

**Issue by pseudoua** [Mikubill/sd-webui-controlnet#2138]
On startup SD:
Error calling: D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
Traceback (most recent call last):
  File "D:\BIN\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 288, in ui
    group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname)
  File "D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 268, in uigroup
    group.register_callbacks(is_img2img)
  File "D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 820, in register_callbacks
    self.preset_panel.register_callbacks(
  File "D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\preset.py", line 177, in register_callbacks
    ).then(
AttributeError: 'dict' object has no attribute 'then'

Error calling: D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
Traceback (most recent call last):
  File "D:\BIN\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 288, in ui
    group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname)
  File "D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 268, in uigroup
    group.register_callbacks(is_img2img)
  File "D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 820, in register_callbacks
    self.preset_panel.register_callbacks(
  File "D:\BIN\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\preset.py", line 177, in register_callbacks
    ).then(
AttributeError: 'dict' object has no attribute 'then'

When working

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-09-22 13:07:01,735 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().

ON OUTPUT
Does not affect the image

**Comment by huchenlei** [comment]
Update your gradio to latest version should resolve the problem.

**Comment by pseudoua** [comment]
Package                 Version
----------------------- ---------------
gradio                  3.44.4
gradio_client           0.5.1
I already tried it! Then I rolled back because something else stopped working. Now, just in case, I updated it again. Does not help

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/issues/1983 for more details.

**Comment by pseudoua** [comment]
I've seen this problem. My a1111 has been updated to the latest version. Gradio too. 
 don't understand why you sent me there.
he only interesting thing about this message is that its number coincides with my year of birth)

**Comment by huchenlei** [comment]
```
2023-09-22 13:07:01,735 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
```

The log indicates that you are having more problems than the gradio version issue. Please disable all extensions other than ControlNet and see if the problem persists.

**Comment by pseudoua** [comment]
Yes, I already found that canvas zoom changes it. I removed this module, but for some reason it still changes it...Uninstalling modified gradio for canvas-zoom

**Comment by pseudoua** [comment]
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/68471179/09f4415b-4edd-4da4-9539-6638326be75c)

**Comment by pseudoua** [comment]
oh , I still have a problem with git. Okay thank you. I'll look into it further.

**Comment by MIDG3Tp3nguin** [comment]
Recieving error in version: [v1.7.0]  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [025b30da6f]
