### ISSUE TITLE
[Bug]: SDXL pose doesnt read the pose image

### ISSUE THREAD

**Issue by captainzero93** [Mikubill/sd-webui-controlnet#2142]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Trying to use https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0 with SDXL , it effects the image if I draw the lines
but not when I load a pose image

### Steps to reproduce the problem

use it

### What should have happened?

followed bone pose

### Commit where the problem happens

version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
[ERROR:9@1959.405] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (909) cv::dnn::dnn4_v20211220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Identity]:(onnx::Clip_1106) from domain='ai.onnx'
*** Error running process: B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "B:\ASSD16\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 252, in run_model
        return remove_pad(self.model_openpose(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 350, in __call__
        poses = self.detect_poses_dw(oriImg)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 323, in detect_poses_dw
        self.load_dw_model()
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 207, in load_dw_model
        self.dw_pose_estimation = Wholebody(onnx_det, onnx_pose)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\wholebody.py", line 24, in __init__
        self.session_pose = cv2.dnn.readNetFromONNX(onnx_pose)
    cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
    > Node [Identity@ai.onnx]:(onnx::Clip_1106) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp:6017: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20211220::Layer::getMemoryShapes'
    >
```

### List of enabled extensions

![plugins](https://github.com/Mikubill/sd-webui-controlnet/assets/125401979/316ec5d6-050e-4819-a62b-d5dc4c5c9d8b)

### Console logs

```Shell
---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.46it/s]
2023-09-24 10:32:46,958 - ControlNet - INFO - Loading model from cache: t2i-openpose-sdxl-1 [274bb89a]
2023-09-24 10:32:46,958 - ControlNet - INFO - using mask as input
2023-09-24 10:32:46,961 - ControlNet - INFO - Loading preprocessor: none
2023-09-24 10:32:46,961 - ControlNet - INFO - preprocessor resolution = 1024
2023-09-24 10:32:47,009 - ControlNet - INFO - ControlNet Hooked - Time = 0.05758929252624512
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.48it/s]
2023-09-24 10:33:06,829 - ControlNet - INFO - Loading model from cache: t2i-openpose-sdxl-1 [274bb89a]
2023-09-24 10:33:06,831 - ControlNet - INFO - Loading preprocessor: dw_openpose_full
2023-09-24 10:33:06,831 - ControlNet - INFO - preprocessor resolution = 1024
[ERROR:4@906.534] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (909) cv::dnn::dnn4_v20211220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Identity]:(onnx::Clip_1106) from domain='ai.onnx'
*** Error running process: B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "B:\ASSD16\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 252, in run_model
        return remove_pad(self.model_openpose(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 350, in __call__
        poses = self.detect_poses_dw(oriImg)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 323, in detect_poses_dw
        self.load_dw_model()
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 207, in load_dw_model
        self.dw_pose_estimation = Wholebody(onnx_det, onnx_pose)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\wholebody.py", line 24, in __init__
        self.session_pose = cv2.dnn.readNetFromONNX(onnx_pose)
    cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
    > Node [Identity@ai.onnx]:(onnx::Clip_1106) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp:6017: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20211220::Layer::getMemoryShapes'
    >

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.42it/s]
2023-09-24 10:34:06,105 - ControlNet - INFO - Loading model from cache: t2i-openpose-sdxl-1 [274bb89a]
2023-09-24 10:34:06,107 - ControlNet - INFO - Loading preprocessor: openpose_full
2023-09-24 10:34:06,107 - ControlNet - INFO - preprocessor resolution = 1024
2023-09-24 10:34:08,122 - ControlNet - INFO - ControlNet Hooked - Time = 2.0230326652526855
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.49it/s]
2023-09-24 10:36:16,909 - ControlNet - INFO - Loading model from cache: t2i-openpose-sdxl-1 [274bb89a]
2023-09-24 10:36:16,910 - ControlNet - INFO - Loading preprocessor: openpose_full
2023-09-24 10:36:16,910 - ControlNet - INFO - preprocessor resolution = 1024
2023-09-24 10:36:18,905 - ControlNet - INFO - ControlNet Hooked - Time = 2.1225507259368896
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.36it/s]
2023-09-24 10:36:43,872 - ControlNet - INFO - Loading model from cache: t2i-openpose-sdxl-1 [274bb89a]
2023-09-24 10:36:43,873 - ControlNet - INFO - using mask as input
2023-09-24 10:36:43,873 - ControlNet - INFO - Loading preprocessor: none
2023-09-24 10:36:43,873 - ControlNet - INFO - preprocessor resolution = 1024
2023-09-24 10:36:43,910 - ControlNet - INFO - ControlNet Hooked - Time = 0.14257216453552246
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.48it/s]
2023-09-24 10:37:46,684 - ControlNet - INFO - Loading model from cache: t2i-openpose-sdxl-1 [274bb89a]
2023-09-24 10:37:46,686 - ControlNet - INFO - Loading preprocessor: dw_openpose_full
2023-09-24 10:37:46,686 - ControlNet - INFO - preprocessor resolution = 512
[ERROR:7@1186.322] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (909) cv::dnn::dnn4_v20211220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Identity]:(onnx::Clip_1106) from domain='ai.onnx'
*** Error running process: B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "B:\ASSD16\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 252, in run_model
        return remove_pad(self.model_openpose(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 350, in __call__
        poses = self.detect_poses_dw(oriImg)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 323, in detect_poses_dw
        self.load_dw_model()
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 207, in load_dw_model
        self.dw_pose_estimation = Wholebody(onnx_det, onnx_pose)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\wholebody.py", line 24, in __init__
        self.session_pose = cv2.dnn.readNetFromONNX(onnx_pose)
    cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
    > Node [Identity@ai.onnx]:(onnx::Clip_1106) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp:6017: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20211220::Layer::getMemoryShapes'
    >

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.45it/s]
2023-09-24 10:38:04,944 - ControlNet - INFO - Loading model from cache: t2i-openpose-sdxl-1 [274bb89a]
2023-09-24 10:38:04,946 - ControlNet - INFO - Loading preprocessor: dw_openpose_full
2023-09-24 10:38:04,946 - ControlNet - INFO - preprocessor resolution = 768
[ERROR:8@1204.656] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (909) cv::dnn::dnn4_v20211220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Identity]:(onnx::Clip_1106) from domain='ai.onnx'
*** Error running process: B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "B:\ASSD16\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 252, in run_model
        return remove_pad(self.model_openpose(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 350, in __call__
        poses = self.detect_poses_dw(oriImg)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 323, in detect_poses_dw
        self.load_dw_model()
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 207, in load_dw_model
        self.dw_pose_estimation = Wholebody(onnx_det, onnx_pose)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\wholebody.py", line 24, in __init__
        self.session_pose = cv2.dnn.readNetFromONNX(onnx_pose)
    cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
    > Node [Identity@ai.onnx]:(onnx::Clip_1106) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp:6017: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20211220::Layer::getMemoryShapes'
    >

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.55it/s]
2023-09-24 10:39:13,702 - ControlNet - INFO - Loading model: t2i-adapter_xl_openpose [18cb12c1]
2023-09-24 10:39:13,704 - ControlNet - INFO - Loaded state_dict from [B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\models\t2i-adapter_xl_openpose.safetensors]
2023-09-24 10:39:13,704 - ControlNet - INFO - t2i_adapter_config
2023-09-24 10:39:14,025 - ControlNet - INFO - ControlNet model t2i-adapter_xl_openpose [18cb12c1] loaded.
2023-09-24 10:39:14,042 - ControlNet - INFO - Loading preprocessor: openpose_full
2023-09-24 10:39:14,042 - ControlNet - INFO - preprocessor resolution = 512
2023-09-24 10:39:14,650 - ControlNet - INFO - ControlNet Hooked - Time = 1.2034375667572021
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.34it/s]
2023-09-24 10:39:37,752 - ControlNet - INFO - Loading model: t2i-openpose-sdxl-1 [274bb89a]
2023-09-24 10:39:37,753 - ControlNet - INFO - Loaded state_dict from [B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\models\t2i-openpose-sdxl-1.safetensors]
2023-09-24 10:39:37,754 - ControlNet - INFO - t2i_adapter_config
2023-09-24 10:39:38,071 - ControlNet - INFO - ControlNet model t2i-openpose-sdxl-1 [274bb89a] loaded.
2023-09-24 10:39:38,102 - ControlNet - INFO - Loading preprocessor: openpose_full
2023-09-24 10:39:38,102 - ControlNet - INFO - preprocessor resolution = 512
2023-09-24 10:39:38,132 - ControlNet - INFO - ControlNet Hooked - Time = 0.47168970108032227
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:04<00:00,  3.24it/s]
2023-09-24 10:50:39,447 - ControlNet - INFO - Loading model: control-lora-openposeXL2-rank256 [72a4faf9]
2023-09-24 10:50:39,635 - ControlNet - INFO - Loaded state_dict from [B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control-lora-openposeXL2-rank256.safetensors]
2023-09-24 10:50:39,635 - ControlNet - INFO - controlnet_sdxl_config (using lora)
2023-09-24 10:50:39,677 - ControlNet - INFO - ControlNet model control-lora-openposeXL2-rank256 [72a4faf9] loaded.
2023-09-24 10:50:39,700 - ControlNet - INFO - Loading preprocessor: dw_openpose_full
2023-09-24 10:50:39,700 - ControlNet - INFO - preprocessor resolution = 768
[ERROR:9@1959.405] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (909) cv::dnn::dnn4_v20211220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Identity]:(onnx::Clip_1106) from domain='ai.onnx'
*** Error running process: B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "B:\ASSD16\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 808, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 252, in run_model
        return remove_pad(self.model_openpose(
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 350, in __call__
        poses = self.detect_poses_dw(oriImg)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 323, in detect_poses_dw
        self.load_dw_model()
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 207, in load_dw_model
        self.dw_pose_estimation = Wholebody(onnx_det, onnx_pose)
      File "B:\ASSD16\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\wholebody.py", line 24, in __init__
        self.session_pose = cv2.dnn.readNetFromONNX(onnx_pose)
    cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
    > Node [Identity@ai.onnx]:(onnx::Clip_1106) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\dnn.cpp:6017: error: (-215:Assertion failed) inputs.size() in function 'cv::dnn::dnn4_v20211220::Layer::getMemoryShapes'
    >

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.20it/s]
```

**Comment by huchenlei** [comment]
Your opencv version is too low. ControlNet specifies opencv >= 4.8.0 here https://github.com/Mikubill/sd-webui-controlnet/blob/main/requirements.txt

**Comment by captainzero93** [comment]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.6/113.6 kB 6.9 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement opencv>=4.8.0 (from versions: none)
ERROR: No matching distribution found for opencv>=4.8.0

**Comment by captainzero93** [comment]
for anyone googling this issue, I had to download from here 
https://pypi.org/project/opencv-python/#files
then use pip install opencv_python-4.8.0.76-cp37-abi3-win_amd64.whl

**Comment by captainzero93** [comment]
(venv) PS B:\ASSD16\stable-diffusion-webui> pip install opencv_python-4.8.0.76-cp37-abi3-win_amd64.whl
WARNING: Ignoring invalid distribution -rotobuf (b:\assd16\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (b:\assd16\stable-diffusion-webui\venv\lib\site-packages)
Processing b:\assd16\stable-diffusion-webui\opencv_python-4.8.0.76-cp37-abi3-win_amd64.whl
Requirement already satisfied: numpy>=1.17.0 in b:\assd16\stable-diffusion-webui\venv\lib\site-packages (from opencv-python==4.8.0.76) (1.23.5)
opencv-python is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.

The same issue, loaded images just show as black on the output, it is not working with the openpose images

**Comment by huchenlei** [comment]
Choose `None` as preprocessor if your input is already an openpose image.
