### ISSUE TITLE
[Bug]: Always getting "detected dubious ownership in repository"

### ISSUE THREAD

**Issue by DjSapsan** [Mikubill/sd-webui-controlnet#2156]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

During first installation and then after running the web UI for my models, I'm getting the error:
`fatal: detected dubious ownership in repository at ...path...`
In the terminal I can fix each one by one by running the proposed commands (git config --global --add safe.directory).
But now I'm trying to install the controlnet via Web UI and it's just crashes. 
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12209464/0401df59-7c6e-4ee0-ae30-e651feb36c11)

My system is:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/12209464/f4d15e1f-090e-4ae4-8d60-841912062fbf)

### Steps to reproduce the problem

Install from URL

### What should have happened?

control net installed as per instructions

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
just launch.py
```

### List of enabled extensions

trying to get one

### Console logs

```Shell
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Version: 1.6.0
Commit hash: <none>
Launching Web UI with arguments: 
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Loading weights [15012c538f] from /install-path/imgen/stable-diff-webui/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV51_v51VAE.safetensors
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Creating model from config: /install-path/imgen/stable-diff-webui/stable-diffusion-webui/configs/v1-inference.yaml
Startup time: 5.5s (prepare environment: 1.1s, import torch: 1.8s, import gradio: 0.6s, setup paths: 0.4s, initialize shared: 0.1s, other imports: 0.3s, setup codeformer: 0.2s, load scripts: 0.3s, create ui: 0.3s, gradio launch: 0.4s).
Applying attention optimization: Doggettx... done.
Model loaded in 1.4s (load weights from disk: 0.5s, create model: 0.4s, apply weights to model: 0.4s).
*** Error completing request
*** Arguments: ('', 'https://github.com/Mikubill/sd-webui-controlnet.git', '') {}
    Traceback (most recent call last):
      File "/install-path/imgen/stable-diff-webui/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/install-path/imgen/stable-diff-webui/stable-diffusion-webui/modules/ui_extensions.py", line 638, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "/install-path/imgen/stable-diff-webui/stable-diffusion-webui/modules/ui_extensions.py", line 368, in install_extension_from_url
        repo.remote().fetch()
      File "/home/myUser/.local/lib/python3.10/site-packages/git/remote.py", line 1015, in fetch
        res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
      File "/home/myUser/.local/lib/python3.10/site-packages/git/remote.py", line 854, in _get_fetch_info_from_stderr
        proc.wait(stderr=stderr_text)
      File "/home/myUser/.local/lib/python3.10/site-packages/git/cmd.py", line 604, in wait
        raise GitCommandError(remove_password_if_present(self.args), status, errstr)
    git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
      cmdline: git fetch -v -- origin
      stderr: 'fatal: detected dubious ownership in repository at '/install-path/imgen/stable-diff-webui/stable-diffusion-webui/tmp/sd-webui-controlnet''

---
```

**Comment by acorderob** [comment]
> fatal: not a git repository (or any parent up to mount point /)

Your webui doesn't seem to be a git clone. That might be causing those ownership errors. Install it properly and they probably go away.
