### ISSUE TITLE
[Bug]: ip-adapter_sdxl_vit-h / ip-adapter-plus_sdxl_vit-h

### ISSUE THREAD

**Issue by ledadu** [Mikubill/sd-webui-controlnet#2166]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

ip-adapter_sdxl_vit-h / ip-adapter-plus_sdxl_vit-h are not working.
ip-adapter_sdxl is working.

What i already try:
- remove the venv
- remove sd-webui-controlnet

### Steps to reproduce the problem

Launch a generation with  ip-adapter_sdxl_vit-h or ip-adapter-plus_sdxl_vit-h

### What should have happened?

Using the control model.

### Commit where the problem happens

webui: v1.6.0
controlnet: v1.1.410

### Command Line Arguments

```Shell
--xformers --medvram --medvram-sdxl --listen --enable-insecure-extension-access --api --reinstall-xformers --no-half-vae
```

### List of enabled extensions

Only sd-webui-controlnet

### Console logs

```Shell
Error using  ip-adapter_sdxl_vit-h :
`2023-10-07 09:52:53,090 - ControlNet - INFO - Loading model from cache: ip-adapter_sdxl_vit-h [75a08f84]
2023-10-07 09:52:53,094 - ControlNet - INFO - Loading preprocessor: ip-adapter_clip_sdxl
2023-10-07 09:52:53,094 - ControlNet - INFO - preprocessor resolution = 1024
*** Error running process: G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui_new\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py", line 944, in controlnet_main_entry
        param.control_model.hook(
      File "G:\stable-diffusion-webui_new\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 327, in hook
        self.image_emb, self.uncond_image_emb = self.ipadapter.get_image_embeds(clip_vision_output)
      File "G:\stable-diffusion-webui_new\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 209, in get_image_embeds
        image_prompt_embeds = self.image_proj_model(clip_image_embeds)
      File "G:\stable-diffusion-webui_new\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 24, in forward
        clip_extra_context_tokens = self.proj(embeds).reshape(-1, self.clip_extra_context_tokens,
      File "G:\stable-diffusion-webui_new\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "G:\stable-diffusion-webui_new\extensions-builtin\Lora\networks.py", line 429, in network_Linear_forward
        return originals.Linear_forward(self, input)
      File "G:\stable-diffusion-webui_new\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1280 and 1024x8192)`

Error on ip-adapter-plus_sdxl_vit-h :
`2023-10-07 09:59:59,804 - ControlNet - INFO - Loading model: ip-adapter-plus_sdxl_vit-h [f1f19f7d]
2023-10-07 10:00:10,300 - ControlNet - INFO - Loaded state_dict from [G:\stable-diffusion-webui_new\models\ControlNet\ip-adapter-plus_sdxl_vit-h.pth]
*** Error running process: G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui_new\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet.py", line 350, in build_control_model
        network = build_model_by_guess(state_dict, unet, model_path)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlnet_model_guess.py", line 233, in build_model_by_guess
        network = PlugableIPAdapter(state_dict, channel, plus)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 299, in __init__
        self.ipadapter = IPAdapterModel(state_dict, clip_embeddings_dim=clip_embeddings_dim, is_plus=is_plus)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 191, in __init__
        self.load_ip_adapter(state_dict)
      File "G:\stable-diffusion-webui_new\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 194, in load_ip_adapter
        self.image_proj_model.load_state_dict(state_dict["image_proj"])
      File "G:\stable-diffusion-webui_new\venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
        raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
    RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for latents: copying a param with shape torch.Size([1, 16, 1280]) from checkpoint, the shape in current model is torch.Size([1, 16, 2048]).
        size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([2048, 1280]).
        size mismatch for proj_in.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for proj_out.weight: copying a param with shape torch.Size([2048, 1280]) from checkpoint, the shape in current model is torch.Size([2048, 2048]).
        size mismatch for layers.0.0.norm1.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.0.0.norm1.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.0.0.norm2.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.0.0.norm2.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.0.0.to_q.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([768, 2048]).
        size mismatch for layers.0.0.to_kv.weight: copying a param with shape torch.Size([2560, 1280]) from checkpoint, the shape in current model is torch.Size([1536, 2048]).
        size mismatch for layers.0.0.to_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([2048, 768]).
        size mismatch for layers.0.1.0.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.0.1.0.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.0.1.1.weight: copying a param with shape torch.Size([5120, 1280]) from checkpoint, the shape in current model is torch.Size([8192, 2048]).
        size mismatch for layers.0.1.3.weight: copying a param with shape torch.Size([1280, 5120]) from checkpoint, the shape in current model is torch.Size([2048, 8192]).
        size mismatch for layers.1.0.norm1.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.1.0.norm1.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.1.0.norm2.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.1.0.norm2.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.1.0.to_q.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([768, 2048]).
        size mismatch for layers.1.0.to_kv.weight: copying a param with shape torch.Size([2560, 1280]) from checkpoint, the shape in current model is torch.Size([1536, 2048]).
        size mismatch for layers.1.0.to_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([2048, 768]).
        size mismatch for layers.1.1.0.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.1.1.0.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.1.1.1.weight: copying a param with shape torch.Size([5120, 1280]) from checkpoint, the shape in current model is torch.Size([8192, 2048]).
        size mismatch for layers.1.1.3.weight: copying a param with shape torch.Size([1280, 5120]) from checkpoint, the shape in current model is torch.Size([2048, 8192]).
        size mismatch for layers.2.0.norm1.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.2.0.norm1.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.2.0.norm2.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.2.0.norm2.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.2.0.to_q.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([768, 2048]).
        size mismatch for layers.2.0.to_kv.weight: copying a param with shape torch.Size([2560, 1280]) from checkpoint, the shape in current model is torch.Size([1536, 2048]).
        size mismatch for layers.2.0.to_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([2048, 768]).
        size mismatch for layers.2.1.0.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.2.1.0.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.2.1.1.weight: copying a param with shape torch.Size([5120, 1280]) from checkpoint, the shape in current model is torch.Size([8192, 2048]).
        size mismatch for layers.2.1.3.weight: copying a param with shape torch.Size([1280, 5120]) from checkpoint, the shape in current model is torch.Size([2048, 8192]).
        size mismatch for layers.3.0.norm1.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.0.norm1.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.0.norm2.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.0.norm2.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.0.to_q.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([768, 2048]).
        size mismatch for layers.3.0.to_kv.weight: copying a param with shape torch.Size([2560, 1280]) from checkpoint, the shape in current model is torch.Size([1536, 2048]).
        size mismatch for layers.3.0.to_out.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([2048, 768]).
        size mismatch for layers.3.1.0.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.1.0.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([2048]).
        size mismatch for layers.3.1.1.weight: copying a param with shape torch.Size([5120, 1280]) from checkpoint, the shape in current model is torch.Size([8192, 2048]).
        size mismatch for layers.3.1.3.weight: copying a param with shape torch.Size([1280, 5120]) from checkpoint, the shape in current model is torch.Size([2048, 8192]).`
```

**Comment by SpenserCai** [comment]
same issue +1
