### ISSUE TITLE
Error: 'local variable 'value_is_number' referenced before assignment'

### ISSUE THREAD

**Issue by idesign2018** [Mikubill/sd-webui-controlnet#2169]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

In the use of deforum, I will be available before the configuration file imported into the deforum, modified the prompt word, key frame movement and some other parameters on the prompt error message, the key is also the regular changes, and did not add a new setting, no matter how I repeatedly try, or this problem, seeking everyone's help!

Here is a screenshot of the problem:
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/42263070/4adaf870-3549-473e-a3c4-8b8467dd675d)

### Steps to reproduce the problem

1. Import the previously available configuration file
2. Normal replacement of file contents
3. Clicking run gives me an error and it never runs properly

### What should have happened?

It should work.

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
not
```

### List of enabled extensions

deforum

### Console logs

```Shell
started run_deforum
times_to_run: 1
Deforum extension for auto1111 webui
Git commit: f635a215
Starting job task(f2paltne8k32cv8)-0...

*START OF TRACEBACK*
Traceback (most recent call last):
  File "C:\Meta\SD\sd-webui-aki-v4.4\extensions\sd-webui-deforum\scripts\deforum_helpers\run_deforum.py", line 110, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
  File "C:\Meta\SD\sd-webui-aki-v4.4\extensions\sd-webui-deforum\scripts\deforum_helpers\render.py", line 84, in render_animation
    parseq_adapter = ParseqAdapter(parseq_args, anim_args, video_args, controlnet_args, loop_args)
  File "C:\Meta\SD\sd-webui-aki-v4.4\extensions\sd-webui-deforum\scripts\deforum_helpers\parseq_adapter.py", line 45, in __init__
    self.anim_keys = ParseqAnimKeysDecorator(self, DeformAnimKeys(anim_args))
  File "C:\Meta\SD\sd-webui-aki-v4.4\extensions\sd-webui-deforum\scripts\deforum_helpers\animation_key_frames.py", line 50, in __init__
*END OF TRACEBACK*
    self.checkpoint_schedule_series = self.fi.parse_inbetweens(anim_args.checkpoint_schedule, 'checkpoint_schedule', is_single_string = True)
  File "C:\Meta\SD\sd-webui-aki-v4.4\extensions\sd-webui-deforum\scripts\deforum_helpers\animation_key_frames.py", line 107, in parse_inbetweens

    return self.get_inbetweens(self.parse_key_frames(value, filename = filename), filename = filename, is_single_string = is_single_string)
User friendly error message:
  File "C:\Meta\SD\sd-webui-aki-v4.4\extensions\sd-webui-deforum\scripts\deforum_helpers\animation_key_frames.py", line 124, in get_inbetweens
Error: local variable 'value_is_number' referenced before assignment. Please, check your schedules/ init values.
    if not value_is_number:
UnboundLocalError: local variable 'value_is_number' referenced before assignment
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。
```

**Comment by huchenlei** [comment]
Please file issue in deforum repo.
