### ISSUE TITLE
[Bug]: Preprocessor models downloads stop early. Corrupted Files.

### ISSUE THREAD

**Issue by Zaazu** [Mikubill/sd-webui-controlnet#2174]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When choosing a Preprocessor that hasn't been ran before, ControlNet will download a Preprosessor model. This download stops at 95-99% and will continue to try using the model downloaded, and fail. Downloading the file via a web browser and pasting it in the expected folder works fine.

### Steps to reproduce the problem

Problem:
1. Enable ControlNet
2. Click on IP-Adapter
3. Click on "Run preprocessor"
4. A preprosessor model will download, stop at 95-99% in the log
5. Console Log: Error verifying pickled file. The file is most likely corrupted

Workaround:
1. Download the model manually from the huggingface link in the command window
2. Paste model into the expected folder
3. Click on "Run preprocessor"
4. Success

### What should have happened?

The download should complete 100% instead of skipping after 95-99%.

### Commit where the problem happens

webui: v1.6.0 5ef669de080814067961f28357256e8fe27544f4
controlnet: v1.1.410

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--no-half-vae
--opt-sdp-no-mem-attention
--ckpt-dir ..\..\Models\Stable-diffusion
--vae-dir ..\..\Models\VAE
--lora-dir ..\..\Models\Lora
--embeddings-dir ..\..\Models\Embeddings
--esrgan-models-path ..\..\Models\ESRGAN
--realesrgan-models-path ..\..\Models\RealESRGAN
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/22891753/f7271c3a-3982-4211-b9a4-48481d6cb4f8)

### Console logs

```Shell
Downloading: "https://huggingface.co/lllyasviel/Annotators/resolve/main/ControlNetLama.pth" to D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\lama\ControlNetLama.pth

 95%|███████████████████████████████████████████████████████████████████████████▎   | 186M/195M [00:18<00:00, 10.6MB/s]
*** Error verifying pickled file from D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\lama\ControlNetLama.pth
*** -----> !!!! The file is most likely corrupted !!!! <-----
*** You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.
***
    Traceback (most recent call last):
      File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\modules\safe.py", line 83, in check_pt
        with zipfile.ZipFile(filename) as z:
      File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1267, in __init__
        self._RealGetContents()
      File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1334, in _RealGetContents
        raise BadZipFile("File is not a zip file")
    zipfile.BadZipFile: File is not a zip file

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1245, in load_persid
        pid = self.readline()[:-1].decode("ascii")
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 63: ordinal not in range(128)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\modules\safe.py", line 104, in check_pt
        unpickler.load()
      File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "C:\Users\Ryan\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1247, in load_persid
        raise UnpicklingError(
    _pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

---
Traceback (most recent call last):
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 679, in run_annotator
    result, is_image = preprocessor(
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
    return cached_func(*args, **kwargs)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
    return func(*args, **kwargs)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 489, in lama_inpaint
    prd_color = model_lama(img_res)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 43, in __call__
    self.load_model()
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 33, in load_model
    self.model = load_checkpoint(cfg, os.path.abspath(modelpath), strict=False, map_location='cpu')
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\saicinpainting\training\trainers\__init__.py", line 28, in load_checkpoint
    model.load_state_dict(state, strict=strict)
  File "D:\Software\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1994, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.
```

### Additional information

It doesn't matter which control type you choose, it'll stop downloading before 100%, so long as there's a Preprocessor model to download.

This issue persists after deleting ControlNet and re-installing.

**Comment by huchenlei** [comment]
It is very likely to be a connection issue as we do not recieve similar bug reports from other users. You can always manually download models from huggingface.
