### ISSUE TITLE
提示：Python 运行时抛出了一个异常

### ISSUE THREAD

**Issue by renyizheng41** [Mikubill/sd-webui-controlnet#2175]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

怎么解决这个提示：Python 运行时抛出了一个异常。请检查疑难解答页面   谢谢大家

### Steps to reproduce the problem

2023-10-12 18:01:10,320 - ControlNet - INFO - ControlNet v1.1.406 ControlNet preprocessor location: E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-controlnet\annotator\downloads 2023-10-12 18:01:10,406 - ControlNet - INFO - ControlNet v1.1.406 sd-webui-prompt-all-in-one background API service started successfully. Loading weights [6a58d8488c] from E:\Stable Diffusion\sd-webui-aki-v4.4\models\Stable-diffusion\卡通.safetensors Creating model from config: E:\Stable Diffusion\sd-webui-aki-v4.4\configs\v1-inference.yaml Running on local URL:  http://127.0.0.1:7860 Loading VAE weights specified in settings: E:\Stable Diffusion\sd-webui-aki-v4.4\models\VAE\animevae.pt Applying attention optimization: xformers... done. Model loaded in 2.8s (load weights from disk: 0.6s, create model: 0.2s, apply weights to model: 1.3s, load VAE: 0.5s).  To create a public link, set `share=True` in `launch()`. Startup time: 54.6s (prepare environment: 2.6s, import torch: 2.2s, import gradio: 1.0s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, setup codeformer: 0.2s, load scripts: 43.9s, create ui: 1.0s, gradio launch: 2.4s).   IS-NET_pro: start generating... *** Error verifying pickled file from E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\..\saved_models\IS-Net\isnet-general-use.pth *** The file may be malicious, so the program is not going to read it. *** You can skip this check with --disable-safe-unpickle commandline argument. ***      Traceback (most recent call last):       File "E:\Stable Diffusion\sd-webui-aki-v4.4\modules\safe.py", line 137, in load_with_extra         check_pt(filename, extra_handler)       File "E:\Stable Diffusion\sd-webui-aki-v4.4\modules\safe.py", line 83, in check_pt         with zipfile.ZipFile(filename) as z:       File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\zipfile.py", line 1251, in __init__         self.fp = io.open(file, filemode)     FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Stable Diffusion\\sd-webui-aki-v4.4\\extensions\\sd-webui-IS-NET-pro\\isnet_pro\\..\\saved_models\\IS-Net\\isnet-general-use.pth' 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。  --- Traceback (most recent call last):   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict     output = await app.get_blocks().process_api(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api     result = await self.call_function(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function     prediction = await anyio.to_thread.run_sync(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync     return await get_asynclib().run_sync_in_worker_thread(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread     return await future   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run     result = context.run(func, *args)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper     response = f(*args, **kwargs)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\Inference2.py", line 308, in pic_generation_single     res_pic,mask= IS_inference_single(img_mode,img_numpy_data,background_path,result_path,ui_set_aim_bacground_rgb,IS_recstrth/255,IS_recstrth_low/255,reverse_flag)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\Inference2.py", line 336, in IS_inference_single     net.load_state_dict(torch.load(model_path))   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1994, in load_state_dict     raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict))) TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>. 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。[Bug]: 

### What should have happened?

12023-10-12 18:01:10,320 - ControlNet - INFO - ControlNet v1.1.406 ControlNet preprocessor location: E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-controlnet\annotator\downloads 2023-10-12 18:01:10,406 - ControlNet - INFO - ControlNet v1.1.406 sd-webui-prompt-all-in-one background API service started successfully. Loading weights [6a58d8488c] from E:\Stable Diffusion\sd-webui-aki-v4.4\models\Stable-diffusion\卡通.safetensors Creating model from config: E:\Stable Diffusion\sd-webui-aki-v4.4\configs\v1-inference.yaml Running on local URL:  http://127.0.0.1:7860 Loading VAE weights specified in settings: E:\Stable Diffusion\sd-webui-aki-v4.4\models\VAE\animevae.pt Applying attention optimization: xformers... done. Model loaded in 2.8s (load weights from disk: 0.6s, create model: 0.2s, apply weights to model: 1.3s, load VAE: 0.5s).  To create a public link, set `share=True` in `launch()`. Startup time: 54.6s (prepare environment: 2.6s, import torch: 2.2s, import gradio: 1.0s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, setup codeformer: 0.2s, load scripts: 43.9s, create ui: 1.0s, gradio launch: 2.4s).   IS-NET_pro: start generating... *** Error verifying pickled file from E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\..\saved_models\IS-Net\isnet-general-use.pth *** The file may be malicious, so the program is not going to read it. *** You can skip this check with --disable-safe-unpickle commandline argument. ***      Traceback (most recent call last):       File "E:\Stable Diffusion\sd-webui-aki-v4.4\modules\safe.py", line 137, in load_with_extra         check_pt(filename, extra_handler)       File "E:\Stable Diffusion\sd-webui-aki-v4.4\modules\safe.py", line 83, in check_pt         with zipfile.ZipFile(filename) as z:       File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\zipfile.py", line 1251, in __init__         self.fp = io.open(file, filemode)     FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Stable Diffusion\\sd-webui-aki-v4.4\\extensions\\sd-webui-IS-NET-pro\\isnet_pro\\..\\saved_models\\IS-Net\\isnet-general-use.pth' 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。  --- Traceback (most recent call last):   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict     output = await app.get_blocks().process_api(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api     result = await self.call_function(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function     prediction = await anyio.to_thread.run_sync(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync     return await get_asynclib().run_sync_in_worker_thread(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread     return await future   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run     result = context.run(func, *args)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper     response = f(*args, **kwargs)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\Inference2.py", line 308, in pic_generation_single     res_pic,mask= IS_inference_single(img_mode,img_numpy_data,background_path,result_path,ui_set_aim_bacground_rgb,IS_recstrth/255,IS_recstrth_low/255,reverse_flag)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\Inference2.py", line 336, in IS_inference_single     net.load_state_dict(torch.load(model_path))   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1994, in load_state_dict     raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict))) TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>. 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。[Bug]: 

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
1
```

### List of enabled extensions

1

### Console logs

```Shell
2023-10-12 18:01:10,320 - ControlNet - INFO - ControlNet v1.1.406 ControlNet preprocessor location: E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-controlnet\annotator\downloads 2023-10-12 18:01:10,406 - ControlNet - INFO - ControlNet v1.1.406 sd-webui-prompt-all-in-one background API service started successfully. Loading weights [6a58d8488c] from E:\Stable Diffusion\sd-webui-aki-v4.4\models\Stable-diffusion\卡通.safetensors Creating model from config: E:\Stable Diffusion\sd-webui-aki-v4.4\configs\v1-inference.yaml Running on local URL:  http://127.0.0.1:7860 Loading VAE weights specified in settings: E:\Stable Diffusion\sd-webui-aki-v4.4\models\VAE\animevae.pt Applying attention optimization: xformers... done. Model loaded in 2.8s (load weights from disk: 0.6s, create model: 0.2s, apply weights to model: 1.3s, load VAE: 0.5s).  To create a public link, set `share=True` in `launch()`. Startup time: 54.6s (prepare environment: 2.6s, import torch: 2.2s, import gradio: 1.0s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, setup codeformer: 0.2s, load scripts: 43.9s, create ui: 1.0s, gradio launch: 2.4s).   IS-NET_pro: start generating... *** Error verifying pickled file from E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\..\saved_models\IS-Net\isnet-general-use.pth *** The file may be malicious, so the program is not going to read it. *** You can skip this check with --disable-safe-unpickle commandline argument. ***      Traceback (most recent call last):       File "E:\Stable Diffusion\sd-webui-aki-v4.4\modules\safe.py", line 137, in load_with_extra         check_pt(filename, extra_handler)       File "E:\Stable Diffusion\sd-webui-aki-v4.4\modules\safe.py", line 83, in check_pt         with zipfile.ZipFile(filename) as z:       File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\zipfile.py", line 1251, in __init__         self.fp = io.open(file, filemode)     FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Stable Diffusion\\sd-webui-aki-v4.4\\extensions\\sd-webui-IS-NET-pro\\isnet_pro\\..\\saved_models\\IS-Net\\isnet-general-use.pth' 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。  --- Traceback (most recent call last):   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict     output = await app.get_blocks().process_api(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api     result = await self.call_function(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function     prediction = await anyio.to_thread.run_sync(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync     return await get_asynclib().run_sync_in_worker_thread(   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread     return await future   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run     result = context.run(func, *args)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper     response = f(*args, **kwargs)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\Inference2.py", line 308, in pic_generation_single     res_pic,mask= IS_inference_single(img_mode,img_numpy_data,background_path,result_path,ui_set_aim_bacground_rgb,IS_recstrth/255,IS_recstrth_low/255,reverse_flag)   File "E:\Stable Diffusion\sd-webui-aki-v4.4\extensions\sd-webui-IS-NET-pro\isnet_pro\Inference2.py", line 336, in IS_inference_single     net.load_state_dict(torch.load(model_path))   File "E:\Stable Diffusion\sd-webui-aki-v4.4\python\lib\site-packages\torch\nn\modules\module.py", line 1994, in load_state_dict     raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict))) TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>. 提示：Python 运行时抛出了一个异常。请检查疑难解答页面。[Bug]:
```

**Comment by huchenlei** [comment]
The stacktrace shows that the issue originates from `sd-webui-IS-NET-pro`. Please file an issue there instead. Thanks.
