### ISSUE TITLE
[Scripting] Help with script to choose random pose image

### ISSUE THREAD

**Issue by gobshyte** [Mikubill/sd-webui-controlnet#2193]
Hi
I'm trying to create a script to choose a random pose image: 

```
import os
import shutil
import random
import numpy as np
from PIL import Image 

import modules.scripts as scripts
import gradio as gr

from modules import images
from modules.processing import process_images
from modules.shared import opts, state
import modules.sd_samplers

source_folder = "C:\Temp\Poses"

def get_random_file(folder):
    source_files = os.listdir(folder)
    random_file = random.choice(source_files)
    return random_file


class Script(scripts.Script):
    def title(self):
        return "Pose Random"

    def ui(self, is_img2img):
        return []

    def run(self, p):
        image_name = get_random_file(source_folder)
        image_path = source_folder + '\\' + image_name
        with Image.open(image_path) as img_file:
            img_array = np.asarray(img_file)
        img = {}
        img['image'] = img_array
        img['mask'] = 255 * np.zeros_like(img_array , dtype = np.uint8)
        p.control_net_image = img
        processed = process_images(p)               
        return processed
```

The script itself does not seem to generate any errors, but when the processing occurs I get:

```
*** Error running process: C:\SDAI\A1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\SDAI\A1111\webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\SDAI\A1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "C:\SDAI\A1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\SDAI\A1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 696, in controlnet_main_entry
        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
      File "C:\SDAI\A1111\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 608, in choose_input_image
        raise ValueError('controlnet is enabled but no input image is given')
    ValueError: controlnet is enabled but no input image is given
```

Any ideas how I can get this to work please?

**Comment by gobshyte** [comment]
Note I do not get that error if I choose an image manually, but the script continues to use that image. I am guessing this bit here is wrong, maybe?
`p.control_net_image = img`

**Comment by gobshyte** [comment]
I was using this conversation as reference:
https://github.com/Mikubill/sd-webui-controlnet/issues/444

**Comment by huchenlei** [comment]
#444's way of passing image to controlnet is deprecated. See 

https://github.com/Mikubill/sd-webui-controlnet/blob/150d6f140d8c8d00add682189c87da09dddb6803/scripts/controlnet.py#L538-L553

Also please confirm that you are overriding the correct method from `Script`. It is very likely the `run` method did not execute as ControlNet is collecting the input image.

I am not sure why you want to make such an extension. You can simply write a script calling into A1111 API with different poses for ControlNet instead,  which should be much more straightforward.
