### ISSUE TITLE
Controlnet not working at all

### ISSUE THREAD

**Issue by Wage72** [Mikubill/sd-webui-controlnet#2198]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Controlnet simply doesn't work, an image generates but I get the error I pasted below, and controlnet does not apply. Additionally, the preview doesn't load. I'm not very experienced in coding so I'm basically just confused. Any help would be much appreciated.

### Steps to reproduce the problem

1. Enable Controlnet
2. Select a controltype
3. Generate an image

### What should have happened?

Controlnet should be applied to the generated image

### Commit where the problem happens

webui: 1.6.0
controlnet: 1.1.411

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

ControlNet

### Console logs

```Shell
*** Error running process: W:\Programs\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "W:\Programs\A1111\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "W:\Programs\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "W:\Programs\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "W:\Programs\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "W:\Programs\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "W:\Programs\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 349, in build_control_model
        state_dict = load_state_dict(model_path)
      File "W:\Programs\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 20, in load_state_dict
        state_dict = unsafe_torch_load(ckpt_path, map_location=torch.device(location))
      File "W:\Programs\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 815, in load
        return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
      File "W:\Programs\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
        magic_number = pickle_module.load(f, **pickle_load_args)
    EOFError: Ran out of input
```

### Additional information

I have searched through all I could find for people with a similar error, none of the solutions work. I tried fresh installs of both controlnet and A1111; manually installing the .yaml files; running it in a different browser and with all extensions disabled; deleting all command line arguments. I've never used controlnet before so I'm just trying to get it started.

**Comment by huchenlei** [comment]
You downloaded models might be corrupted. Please follow https://github.com/Mikubill/sd-webui-controlnet#download-models closely to download models. .yaml files are not models. You should download `.safetensor`/`.pth` files from huggingface.

**Comment by Wage72** [comment]
I can't believe it took me that long, thank you. I literally just didn't let the files finish downloading before putting them into the folder
