### ISSUE TITLE
[Bug]: Controlnet does not show preset image upload

### ISSUE THREAD

**Issue by Lukeable** [Mikubill/sd-webui-controlnet#2201]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Controlnet did not recognize uploaded preset pictures

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Normally the picture has to be show up in the Controlnet UI

### Commit where the problem happens

webui: no picture showing
controlnet: 

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet	main	[e382d161](https://github.com/Mikubill/sd-webui-controlnet/commit/e382d1618593ae05a7115006de8680d3ddbd9777)	2023-10-26 03:35:02	unknown
sd-webui-reactor	https://github.com/Gourieff/sd-webui-reactor	main	[6aed6ae1](https://github.com/Gourieff/sd-webui-reactor/commit/6aed6ae14183098c3e0b17310547ec6415cd1fb8)	2023-10-26 12:34:51	unknown
ultimate-upscale-for-automatic1111	https://github.com/Coyote-A/ultimate-upscale-for-automatic1111	master	[728ffcec](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/728ffcec7fa69c83b9e653bf5b96932acdce750f)	2023-09-09 12:47:23	unknown
LDSR	[built-in](http://127.0.0.1:7860/)	None			
Lora	[built-in](http://127.0.0.1:7860/)	None			
ScuNET	[built-in](http://127.0.0.1:7860/)	None			
SwinIR	[built-in](http://127.0.0.1:7860/)	None			
canvas-zoom-and-pan	[built-in](http://127.0.0.1:7860/)	None			
extra-options-section	[built-in](http://127.0.0.1:7860/)	None			
mobile	[built-in](http://127.0.0.1:7860/)	None			
prompt-bracket-checker	[built-in](http://127.0.0.1:7860/)	None

### Console logs

```Shell
H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui>git pull
Already up to date.
venv "H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Checking ReActor requirements... Ok
Launching Web UI with arguments: --xformers --medvram
2023-10-28 16:37:54,523 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-10-28 16:37:54,637 - ControlNet - INFO - ControlNet v1.1.411
16:37:55 - ReActor - STATUS - Running v0.4.3
Loading weights [84d76a0328] from H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\models\Stable-diffusion\epicrealism_naturalSinRC1VAE.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\configs\v1-inference.yaml
Startup time: 15.2s (prepare environment: 4.7s, import torch: 3.7s, import gradio: 1.2s, setup paths: 1.1s, initialize shared: 0.2s, other imports: 1.1s, setup codeformer: 0.2s, load scripts: 1.9s, create ui: 0.5s, gradio launch: 0.6s).
Applying attention optimization: xformers... done.
Model loaded in 17.0s (load weights from disk: 0.9s, create model: 0.3s, apply weights to model: 11.4s, calculate empty prompt: 4.3s).
Traceback (most recent call last):
  File "H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 137, in svg_preprocess
    return preprocess(inputs)
  File "H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\venv\lib\site-packages\gradio\components\image.py", line 274, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 59, in decode_base64_to_image
    img = Image.open(BytesIO(base64.b64decode(image_encoded)))
  File "H:\Stable Diffusion\stable diffusion new\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002DA931E3C90>
```

**Comment by huchenlei** [comment]
Please share the image you would like ControlNet to recognize and reopen.
