### ISSUE TITLE
[Bug]: Changing UI item causes exception on startup

### ISSUE THREAD

**Issue by CurtisDS** [Mikubill/sd-webui-controlnet#2214]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I updated Control Net to and it caused a ton of errors when I start A111.

I narrowed it down to the fact that I had a custom order for my txt2img/img2img UI items.

### Steps to reproduce the problem

1. Install Control Net
2. Go to Settings > User Interface
3. Set txt2img/img2img UI item order to "scripts"
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20732674/7b2f3a91-0c74-4f47-9fe7-cd9e3d97a13e)
4. Close A111 command prompt window and run the webui-user.bat to restart it.

### What should have happened?

No errors during startup

### Commit where the problem happens

webui: 5ef669de080814067961f28357256e8fe27544f4
controlnet: 3011ff6e706d3fdd0cc7d2ac8ff0d59020b8f767

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers
```

### List of enabled extensions

Just Control Net and the "build-in" extensions

### Console logs

```Shell
venv "G:\Stable-diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Launching Web UI with arguments: --xformers
2023-11-01 21:37:49,971 - ControlNet - INFO - ControlNet v1.1.415
ControlNet preprocessor location: G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-11-01 21:37:50,040 - ControlNet - INFO - ControlNet v1.1.415
Loading weights [bd51fbd4fe] from G:\Stable-diffusion\stable-diffusion-webui\models\Stable-diffusion\sd15.safetensors
*** Error calling: G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
    Traceback (most recent call last):
      File "G:\Stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 288, in ui
        group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname)
      File "G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 268, in uigroup
        group.register_callbacks(is_img2img)
      File "G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 816, in register_callbacks
        self.register_send_dimensions(is_img2img)
      File "G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 454, in register_send_dimensions
        self.send_dimen_button.click(
      File "G:\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py", line 140, in __call__
        dep, dep_index = self.trigger.set_event_trigger(
      File "G:\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 287, in set_event_trigger
        "outputs": [block._id for block in outputs],
      File "G:\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 287, in <listcomp>
        "outputs": [block._id for block in outputs],
    AttributeError: 'NoneType' object has no attribute '_id'

---
*** Error calling: G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
    Traceback (most recent call last):
      File "G:\Stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 402, in wrap_call
        return func(*args, **kwargs)
      File "G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 288, in ui
        group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname)
      File "G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 268, in uigroup
        group.register_callbacks(is_img2img)
      File "G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 816, in register_callbacks
        self.register_send_dimensions(is_img2img)
      File "G:\Stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 454, in register_send_dimensions
        self.send_dimen_button.click(
      File "G:\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\events.py", line 140, in __call__
        dep, dep_index = self.trigger.set_event_trigger(
      File "G:\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 287, in set_event_trigger
        "outputs": [block._id for block in outputs],
      File "G:\Stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 287, in <listcomp>
        "outputs": [block._id for block in outputs],
    AttributeError: 'NoneType' object has no attribute '_id'

---
Creating model from config: G:\Stable-diffusion\stable-diffusion-webui\configs\v1-inference.yaml
```

**Comment by CurtisDS** [comment]
actually, may be a duplicate of https://github.com/Mikubill/sd-webui-controlnet/issues/2136
