### ISSUE TITLE
[Feature Request]: Support the ip adapter face transfer models.

### ISSUE THREAD

**Issue by jetjodh** [Mikubill/sd-webui-controlnet#2216]
Support the ip adapter face transfer safetensor models.
https://huggingface.co/h94/IP-Adapter/tree/main/sdxl_models

**Comment by Clocktown** [comment]
Adding to this - currently I get the following error:
`*** Error running process: D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\GitProjects\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 350, in build_control_model
        network = build_model_by_guess(state_dict, unet, model_path)
      File "D:\GitProjects\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_model_guess.py", line 237, in build_model_by_guess
        raise '[ControlNet Error] Cannot recognize the ControlModel!'
    TypeError: exceptions must derive from BaseException`
with both `ip-adapter-plus_sdxl_vit.h` and `ip-adapter-plus-face_sdxl_vit-h`, with both the SDXL clip preprocessor and the vith preprocessor, and they don't seem to generate expected results. The "regular" sdxl ip-adapter does work without issues.
