### ISSUE TITLE
little error pops up on console even when not enabled

### ISSUE THREAD

**Issue by gsgoldma** [Mikubill/sd-webui-controlnet#223]
rror running postprocess: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 404, in postprocess
    script.postprocess(p, processed, *script_args)
  File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 532, in postprocess
    detectmap_dir = os.path.join(shared.opts.data.get("control_net_detectedmap_dir", False), self.latest_params[0])
  File "D:\Python\Python310\lib\ntpath.py", line 143, in join
    genericpath._check_arg_types('join', path, *paths)
  File "D:\Python\Python310\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/a8c5b4e25516cbaf8457dfc3ee863a174eb0678d
