### ISSUE TITLE
[Bug]:error of using controlnet module:ip-adapter_clip_sdxl_plus_vith

### ISSUE THREAD

**Issue by TigerHH6866** [Mikubill/sd-webui-controlnet#2234]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

model: xl base 1.0
controlnet module:ip-adapter_clip_sdxl_plus_vith
model:ip-adapter_xl [4209e9f7]

error: 

2023-11-06 13:03:23,031 - ControlNet - INFO - Loading model: ip-adapter_xl [4209e9f7]████████████████████████████████████████████████████████████████████████████████| 25/25 [00:22<00:00,  1.30it/s]
2023-11-06 13:03:23,472 - ControlNet - INFO - Loaded state_dict from [/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ip-adapter_xl.pth]
2023-11-06 13:03:27,195 - ControlNet - INFO - ControlNet model ip-adapter_xl [4209e9f7] loaded.
2023-11-06 13:03:27,197 - ControlNet - INFO - Loading preprocessor: ip-adapter_clip_sdxl_plus_vith
2023-11-06 13:03:27,197 - ControlNet - INFO - preprocessor resolution = 770
*** Error running process: /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 944, in controlnet_main_entry
        param.control_model.hook(
      File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 342, in hook
        self.image_emb, self.uncond_image_emb = self.ipadapter.get_image_embeds(clip_vision_output)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 209, in get_image_embeds
        image_prompt_embeds = self.image_proj_model(clip_image_embeds)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 24, in forward
        clip_extra_context_tokens = self.proj(embeds).reshape(-1, self.clip_extra_context_tokens,
      File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 429, in network_Linear_forward
        return originals.Linear_forward(self, input)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1024 and 1280x8192)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

1

### Commit where the problem happens

webui: 1.6.0
controlnet: 1.1.415

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

controlnet

### Console logs

```Shell
2023-11-06 13:03:23,031 - ControlNet - INFO - Loading model: ip-adapter_xl [4209e9f7]████████████████████████████████████████████████████████████████████████████████| 25/25 [00:22<00:00,  1.30it/s]
2023-11-06 13:03:23,472 - ControlNet - INFO - Loaded state_dict from [/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ip-adapter_xl.pth]
2023-11-06 13:03:27,195 - ControlNet - INFO - ControlNet model ip-adapter_xl [4209e9f7] loaded.
2023-11-06 13:03:27,197 - ControlNet - INFO - Loading preprocessor: ip-adapter_clip_sdxl_plus_vith
2023-11-06 13:03:27,197 - ControlNet - INFO - preprocessor resolution = 770
*** Error running process: /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 944, in controlnet_main_entry
        param.control_model.hook(
      File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 342, in hook
        self.image_emb, self.uncond_image_emb = self.ipadapter.get_image_embeds(clip_vision_output)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 209, in get_image_embeds
        image_prompt_embeds = self.image_proj_model(clip_image_embeds)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlmodel_ipadapter.py", line 24, in forward
        clip_extra_context_tokens = self.proj(embeds).reshape(-1, self.clip_extra_context_tokens,
      File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "/root/autodl-tmp/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 429, in network_Linear_forward
        return originals.Linear_forward(self, input)
      File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1024 and 1280x8192)
```

**Comment by huchenlei** [comment]
Vit preprocessor should be used along with bit controlnet model.

**Comment by TigerHH6866** [comment]
> Vit preprocessor should be used along with vit controlnet model.

thx,but cant see vit model in collection page. do you know where to download?

**Comment by TigerHH6866** [comment]
well,get vit model and it fixed

**Comment by designrans** [comment]
> well,get vit model and it fixed

[ip-adapter_sdxl_vit-h.safetensors](https://huggingface.co/h94/IP-Adapter/blob/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors) 
it this?

**Comment by TigerHH6866** [comment]
> > well,get vit model and it fixed
> 
> [ip-adapter_sdxl_vit-h.safetensors](https://huggingface.co/h94/IP-Adapter/blob/main/sdxl_models/ip-adapter_sdxl_vit-h.safetensors) it this?

use .bin
