### ISSUE TITLE
[Bug]: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

### ISSUE THREAD

**Issue by 4goman** [Mikubill/sd-webui-controlnet#2253]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

On Linux 23.10.24 with python v 3.10, fresh and working installation of Automatic1111, after installation of ControlNet extension (no error during installation) , restarting the WebUI, i got this error message: 

"ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation."

### Steps to reproduce the problem

1. Install ControlNet 
2. Applay and restart UI
3. Launch Automatic1111 with ./webui.sh --share --api --xformers
4. Error appear: "recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation."

### What should have happened?

Working WebUI with installed extension ControlNet

### Commit where the problem happens

webui: 4afaaf8
controlnet: 457da74

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Microsoft Edge

### Command Line Arguments

```Shell
./webui.sh --share --api --xformers --enable-insecure-extension-access
```

### List of enabled extensions

ControlNet

### Console logs

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on azureuser user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Cannot locate TCMalloc (improves CPU memory usage)
Python 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments: --share --api --xformers
['/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/repositories/k-diffusion', '/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/venv/lib/python3.10/site-packages/cv2', '/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/venv/lib/python3.10/site-packages/git/ext/gitdb', '/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd', '/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd', '/anaconda/envs/azureml_py310_sdkv2/lib/python310.zip', '/anaconda/envs/azureml_py310_sdkv2/lib/python3.10', '/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/lib-dynload', '/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/venv/lib/python3.10/site-packages', '/tmp/tmp2ru65vmj', '/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/repositories/stable-diffusion-stability-ai', '/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/repositories/CodeFormer', '/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/repositories/BLIP']
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/launch.py", line 48, in <module>
    main()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/launch.py", line 44, in main
    start()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/modules/launch_utils.py", line 432, in start
    import webui
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/webui.py", line 13, in <module>
    initialize.imports()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/modules/initialize.py", line 37, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/modules/processing.py", line 14, in <module>
    import cv2
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/mlsd2/code/sd/venv/lib/python3.10/site-packages/cv2/__init__.py", line 76, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
```

### Additional information

ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

**Comment by huchenlei** [comment]
I am not convinced from the stacktrace that the issue is caused by ControlNet. Please file an issue in A1111 repo instead.
