### ISSUE TITLE
my controlnet can't work after update

### ISSUE THREAD

**Issue by hliu00** [Mikubill/sd-webui-controlnet#2281]
version is 1.1.419,run weith error:
`Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 670, in run_annotator
    resize_mode=external_code.resize_mode_from_value(rm),
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 57, in resize_mode_from_value
    return ResizeMode(resize_mode_aliases.get(value, value))
  File "/root/miniconda3/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/root/miniconda3/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'ResizeMode.INNER_FIT' is not a valid ResizeMode`

**Comment by huchenlei** [comment]
Plase reopen with reproduction steps.
