### ISSUE TITLE
[Bug]: controlnet.py Error

### ISSUE THREAD

**Issue by Greczy** [Mikubill/sd-webui-controlnet#2305]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hello there,
i already searched for this error and also found similiar things but couldnt quite get howw to fix it. So basically i was using [ip-adapter-plus-face_sdxl_vit-h.bin] and the image gets generated but without any reference to the original picture due to the error. The normal image generation works fine.

### Steps to reproduce the problem

1. enable controlnet with lowram 
2. input photo
3. put prepocessor and model to ip-adapter_clip_sdxl_plus_vith

### What should have happened?

The normal behavior should be that the generated face would like the one in the input + the scenario described in the prompt

### Commit where the problem happens

webui: [v1.6.1]
controlnet: ControlNet v1.1.422

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --lowvram --xformers

call webui.bat
```

### List of enabled extensions

StyleSelectorXL
sd-webui-controlnet
LDSR
Lora
ScuNET
SwinIR
canvas-zoom-and-pan
extra-options-section
mobile
prompt-bracket-checker

### Console logs

```Shell
venv "D:\julia\Documents\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.1
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments: --lowvram --xformers
2023-12-08 02:21:23,446 - ControlNet - INFO - ControlNet v1.1.422
ControlNet preprocessor location: D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-12-08 02:21:23,627 - ControlNet - INFO - ControlNet v1.1.422
Loading weights [74dda471cc] from D:\julia\Documents\stable-diffusion-webui\models\Stable-diffusion\realvisxlV20_v20Bakedvae.safetensors
Creating model from config: D:\julia\Documents\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 26.9s (prepare environment: 7.1s, import torch: 6.5s, import gradio: 2.4s, setup paths: 2.4s, initialize shared: 0.4s, other imports: 1.8s, setup codeformer: 0.4s, load scripts: 3.1s, create ui: 2.1s, gradio launch: 0.6s).
Applying attention optimization: xformers... done.
Model loaded in 34.5s (load weights from disk: 1.6s, create model: 1.5s, apply weights to model: 28.0s, apply half(): 0.3s, load weights from state dict: 0.1s, move model to device: 0.1s, hijack: 0.1s, load textual inversion embeddings: 0.1s, calculate empty prompt: 2.6s).
2023-12-08 02:34:45,702 - ControlNet - INFO - unit_separate = False, style_align = False
2023-12-08 02:35:35,650 - ControlNet - INFO - Loading model: ip-adapter-plus-face_sdxl_vit-h [368cf551]
2023-12-08 02:35:35,768 - ControlNet - INFO - Loaded state_dict from [D:\julia\Documents\stable-diffusion-webui\models\ControlNet\ip-adapter-plus-face_sdxl_vit-h.safetensors]
2023-12-08 02:35:39,041 - ControlNet - INFO - ControlNet model ip-adapter-plus-face_sdxl_vit-h [368cf551] loaded.
2023-12-08 02:35:39,058 - ControlNet - INFO - Loading preprocessor: ip-adapter_clip_sdxl
2023-12-08 02:35:39,059 - ControlNet - INFO - preprocessor resolution = 512
*** Error verifying pickled file from D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\clip_vision\clip_g.pth
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "D:\julia\Documents\stable-diffusion-webui\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "D:\julia\Documents\stable-diffusion-webui\modules\safe.py", line 95, in check_pt
        unpickler.load()
      File "C:\Users\julia\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "C:\Users\julia\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1590, in load_reduce
        stack[-1] = func(*args)
      File "D:\julia\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\_utils.py", line 169, in _rebuild_tensor_v2
        tensor = _rebuild_tensor(storage, storage_offset, size, stride)
      File "D:\julia\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\_utils.py", line 148, in _rebuild_tensor
        return t.set_(storage._untyped_storage, storage_offset, size, stride)
    RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 54525952 bytes.

---
*** Error running process: D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\julia\Documents\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1053, in process
        self.controlnet_hack(p)
      File "D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1042, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 878, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 351, in clip
        clip_encoder[config] = ClipVisionDetector(config)
      File "D:\julia\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\clipvision\__init__.py", line 113, in __init__
        self.model.load_state_dict(sd, strict=False)
      File "D:\julia\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1994, in load_state_dict
        raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
    TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.
```

**Comment by huchenlei** [comment]
Make sure you have enough RAM (Not VRAM) if you are running on CPU.
