### ISSUE TITLE
[Bug]: FileNotFoundError

### ISSUE THREAD

**Issue by hben35096** [Mikubill/sd-webui-controlnet#2312]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The pth file is always there, but it is not recognized
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/24514a92-22d5-4df6-9999-5bcdbca0ceff)

### Steps to reproduce the problem

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/b1f39710-021a-41b5-848b-4d0c1db805ea)

### What should have happened?

Generate pre-processed images

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
python launch.py --no-download-sd-model --xformers --enable-insecure-extension-access --theme=dark --disable-safe-unpickle
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/5c011eef-86b0-46a2-8124-6f6d011fa1a3)

### Console logs

```Shell
/mnt/workspace/stable-diffusion-webui
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Version: v1.6.1
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
/opt/conda/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]
loading WD14-tagger reqs from /mnt/workspace/stable-diffusion-webui/extensions/stable-diffusion-webui-wd14-tagger/requirements.txt
Checking WD14-tagger requirements.
Launching Web UI with arguments: --no-download-sd-model --xformers --enable-insecure-extension-access --theme=dark --disable-safe-unpickle
2023-12-10 02:01:27.780367: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-10 02:01:27.813407: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-10 02:01:27.813437: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-10 02:01:27.813459: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-10 02:01:27.819260: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-10 02:01:28.650944: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-12-10 02:01:32,847 - ControlNet - INFO - ControlNet v1.1.422
ControlNet preprocessor location: /mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-12-10 02:01:33,051 - ControlNet - INFO - ControlNet v1.1.422
sd-webui-prompt-all-in-one background API service started successfully.
== WD14 tagger /gpu:0, uname_result(system='Linux', node='dsw-283924-5f59f56959-h2ctk', release='4.19.24-7.34.cbp.al7.x86_64', version='#1 SMP Tue Jun 20 06:15:49 UTC 2023', machine='x86_64') ==
Loading weights [1fe6c7ec54] from /mnt/workspace/stable-diffusion-webui/models/Stable-diffusion/juggernautXL_version6Rundiffusion.safetensors
2023-12-10 02:01:33,975 - AnimateDiff - INFO - Injecting LCM to UI.
2023-12-10 02:01:34,442 - AnimateDiff - INFO - Hacking i2i-batch.
Running on local URL:  http://127.0.0.1:7860
Creating model from config: /mnt/workspace/stable-diffusion-webui/repositories/generative-models/configs/inference/sd_xl_base.yaml

To create a public link, set `share=True` in `launch()`.
Startup time: 17.6s (prepare environment: 4.9s, import torch: 4.1s, import gradio: 0.5s, setup paths: 1.0s, initialize shared: 0.1s, other imports: 0.4s, load scripts: 2.2s, create ui: 0.9s, gradio launch: 2.3s, app_started_callback: 1.1s).
Applying attention optimization: xformers... done.
Model loaded in 5.6s (load weights from disk: 2.0s, create model: 0.7s, apply weights to model: 2.5s, calculate empty prompt: 0.2s).
2023-12-10 02:01:41,438 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 694, in run_annotator
    result, is_image = preprocessor(
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
    return cached_func(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
    return func(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 633, in anime_face_segment
    result = model_anime_face_segment(img)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/anime_face_segment/__init__.py", line 160, in __call__
    self.load_model()
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/anime_face_segment/__init__.py", line 144, in load_model
    ckpt = torch.load(modelpath)
  File "/mnt/workspace/stable-diffusion-webui/modules/safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/anime_face_segment/Unet.pth'
```

**Comment by hben35096** [comment]
This is only the case with seg_anime_face.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/b0ef1422-06af-4f14-95ad-5ffbce53b748)

**Comment by sdbds** [comment]
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/8085926/2cd70187-ee90-455a-9490-ad2972b18ea9)

Cant reproduce the problem

Did you try to delete it and re-download？

**Comment by hben35096** [comment]
I re-downloaded it, the problem still exists, I don't know if the following information is related?

2023-12-10 13:58:12,233 - ControlNet - INFO - Preview Resolution = 512
*** Error verifying pickled file from /mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/anime_face_segment/Unet.pth
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
*** 
    Traceback (most recent call last):
      File "/mnt/workspace/stable-diffusion-webui/modules/safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "/mnt/workspace/stable-diffusion-webui/modules/safe.py", line 83, in check_pt
        with zipfile.ZipFile(filename) as z:
      File "/opt/conda/lib/python3.10/zipfile.py", line 1249, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: '/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/anime_face_segment/Unet.pth'

---
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 694, in run_annotator
    result, is_image = preprocessor(
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
    return cached_func(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
    return func(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 633, in anime_face_segment
    result = model_anime_face_segment(img)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/anime_face_segment/__init__.py", line 160, in __call__
    self.load_model()
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/anime_face_segment/__init__.py", line 145, in load_model
    for key in list(ckpt.keys()):
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by hben35096** [comment]
The above is an aliyun server instance, and I am experiencing the same problem in an AutoDL ECS instance.

2023-12-10 14:36:33,764 - ControlNet - INFO - Preview Resolution = 512
*** Error verifying pickled file from /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/anime_face_segment/Unet.pth
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
*** 
    Traceback (most recent call last):
      File "/root/autodl-tmp/stable-diffusion-webui/modules/safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "/root/autodl-tmp/stable-diffusion-webui/modules/safe.py", line 83, in check_pt
        with zipfile.ZipFile(filename) as z:
      File "/root/miniconda3/lib/python3.10/zipfile.py", line 1249, in __init__
        self.fp = io.open(file, filemode)
    FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/anime_face_segment/Unet.pth'

---
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 694, in run_annotator
    result, is_image = preprocessor(
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
    return cached_func(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
    return func(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 633, in anime_face_segment
    result = model_anime_face_segment(img)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/anime_face_segment/__init__.py", line 160, in __call__
    self.load_model()
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/anime_face_segment/__init__.py", line 145, in load_model
    for key in list(ckpt.keys()):
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by hben35096** [comment]
I tried a different installation method and chose the configuration:
Miniconda  conda3
Python  3.10(ubuntu22.04)
Cuda  11.8
The problems that arise are all the same.

**Comment by sdbds** [comment]
Fix it caused by capitalization in Linux.

**Comment by hben35096** [comment]
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/2d838ac3-704a-4422-80e7-38c1e5ce720c)
Perfectly solved, thank you very much :D
