### ISSUE TITLE
[Bug]: `script` errors

### ISSUE THREAD

**Issue by bryanhpchiang** [Mikubill/sd-webui-controlnet#2324]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

```
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version: v1.6.1
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments: 
[2023-12-12 00:31:40,769] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-12-12 00:31:41.367566: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
No module 'xformers'. Proceeding without it.
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 13, in <module>
        from scripts import external_code, global_state
    ImportError: cannot import name 'external_code' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
        from scripts import external_code
    ImportError: cannot import name 'external_code' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 15, in <module>
        from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version, utils
    ImportError: cannot import name 'global_state' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: controlnet_model_guess.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_model_guess.py", line 7, in <module>
        from scripts.adapter import PlugableAdapter, Adapter, StyleAdapter, Adapter_light
    ModuleNotFoundError: No module named 'scripts.adapter'

---
*** Error loading script: controlnet_version.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_version.py", line 3, in <module>
        from scripts.logging import logger
    ModuleNotFoundError: No module named 'scripts.logging'

---
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from scripts import global_state
    ImportError: cannot import name 'global_state' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: global_state.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
    ModuleNotFoundError: No module named 'scripts.processor'

---
*** Error loading script: hook.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 9, in <module>
        from scripts.logging import logger
    ModuleNotFoundError: No module named 'scripts.logging'

---
*** Error loading script: infotext.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/infotext.py", line 7, in <module>
        from scripts import external_code
    ImportError: cannot import name 'external_code' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: utils.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 12, in <module>
        from scripts.logging import logger
    ModuleNotFoundError: No module named 'scripts.logging'

---
```

### Steps to reproduce the problem

I cloned stable-diffusion-webui. I installed sd-webui-controlnet following the instructions in the README. I restarted everything and ran ./webui.sh. Everything is on the latest commit.

### What should have happened?

It should run without errors.

### Commit where the problem happens

webui: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
controlnet: 0d0841671ef165d6d408f7b9cd6bfb1dda3d78cf

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/98059440/d17987c8-c47a-4cb2-8f5e-bd1d016f4cfc)

### Console logs

```Shell
(gpu) bryan@ito:/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui$ ./webui.sh 

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on bryan user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
python venv already activate or run without venv: /home/bryan/venv/gpu
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version: v1.6.1
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Launching Web UI with arguments: 
[2023-12-12 00:34:10,220] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-12-12 00:34:10.529931: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
No module 'xformers'. Proceeding without it.
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 13, in <module>
        from scripts import external_code, global_state
    ImportError: cannot import name 'external_code' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 7, in <module>
        from scripts import external_code
    ImportError: cannot import name 'external_code' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 15, in <module>
        from scripts import global_state, hook, external_code, processor, batch_hijack, controlnet_version, utils
    ImportError: cannot import name 'global_state' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: controlnet_model_guess.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_model_guess.py", line 7, in <module>
        from scripts.adapter import PlugableAdapter, Adapter, StyleAdapter, Adapter_light
    ModuleNotFoundError: No module named 'scripts.adapter'

---
*** Error loading script: controlnet_version.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_version.py", line 3, in <module>
        from scripts.logging import logger
    ModuleNotFoundError: No module named 'scripts.logging'

---
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from scripts import global_state
    ImportError: cannot import name 'global_state' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: global_state.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 8, in <module>
        from scripts.processor import *
    ModuleNotFoundError: No module named 'scripts.processor'

---
*** Error loading script: hook.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 9, in <module>
        from scripts.logging import logger
    ModuleNotFoundError: No module named 'scripts.logging'

---
*** Error loading script: infotext.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/infotext.py", line 7, in <module>
        from scripts import external_code
    ImportError: cannot import name 'external_code' from 'scripts' (/home/bryan/venv/gpu/lib/python3.10/site-packages/scripts/__init__.py)

---
*** Error loading script: utils.py
    Traceback (most recent call last):
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 12, in <module>
        from scripts.logging import logger
    ModuleNotFoundError: No module named 'scripts.logging'

---
Loading weights [6ce0161689] from /media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860
Creating model from config: /media/bryan/817ef30c-1c98-4521-8c91-334a6d39e73c/stable-diffusion-webui/configs/v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 2.0s (load weights from disk: 0.4s, create model: 0.2s, apply weights to model: 1.1s, load textual inversion embeddings: 0.2s).

To create a public link, set `share=True` in `launch()`.
Startup time: 11.8s (prepare environment: 2.0s, import torch: 5.4s, import gradio: 0.3s, setup paths: 0.5s, other imports: 0.2s, load scripts: 0.6s, create ui: 0.2s, gradio launch: 2.4s).
```

**Comment by huchenlei** [comment]
You probably want to ask this environment issue in A1111 repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues
