### ISSUE TITLE
HELP control net not working

### ISSUE THREAD

**Issue by SEETHE333** [Mikubill/sd-webui-controlnet#2334]
Im not good at anything and ive tried every fix ive found on reddit/github, can someone give me a step by step on how to fix this

Error running process: D:\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1053, in process
    self.controlnet_hack(p)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1042, in controlnet_hack
    self.controlnet_main_entry(p)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 750, in controlnet_main_entry
    Script.check_sd_version_compatible(unit)
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 693, in check_sd_version_compatible
    sd_version = global_state.get_sd_version()
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\global_state.py", line 249, in get_sd_version
    if shared.sd_model.is_sdxl:
  File "D:\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LatentDiffusion' object has no attribute 'is_sdxl'

**Comment by huchenlei** [comment]
Try update your A1111 version. `is_sdxl` is added since WebUI 1.6.0.
