### ISSUE TITLE
ControlNet not working

### ISSUE THREAD

**Issue by TaTsuuYa** [Mikubill/sd-webui-controlnet#234]
It keeps giving me the same error, sometimes the image gets generated but it doesn't get processed by ControlNet

my settings (I usually have an image in the image section): 
![127 0 0 1_7860_](https://user-images.githubusercontent.com/114253973/220109780-2e41501b-f933-4d5c-9222-e2e49e2e01fc.png)

### ERROR:
Loading preprocessor: openpose, model: control_sd15_openpose [fef5e48e]
Loaded state_dict from [C:\MAIN\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_openpose.pth]
Error running process: C:\MAIN\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\MAIN\AI\stable-diffusion-webui\modules\scripts.py", line 347, in process
    script.process(p, *script_args)
  File "C:\MAIN\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 483, in process
    network.to(p.sd_model.device, dtype=p.sd_model.dtype)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 6.00 GiB total capacity; 5.23 GiB already allocated; 0 bytes free; 5.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Error completing request
Arguments: ('1girl, solo', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, True, 'openpose', 'control_sd15_openpose [fef5e48e]', 1, {'image': array([[[ 48,  52,  63],
        [ 48,  52,  63],
        [ 48,  52,  63],
        ...,
        [ 70,  76,  90],
        [ 69,  75,  89],
        [ 69,  75,  89]],

       [[ 48,  52,  63],
        [ 48,  52,  63],
        [ 48,  52,  63],
        ...,
        [ 70,  76,  90],
        [ 69,  75,  89],
        [ 69,  75,  89]],

       [[ 48,  52,  63],
        [ 48,  52,  63],
        [ 48,  52,  63],
        ...,
        [ 70,  76,  90],
        [ 69,  75,  89],
        [ 69,  75,  89]],

       ...,

       [[163, 147, 124],
        [163, 147, 124],
        [163, 147, 124],
        ...,
        [203, 181, 144],
        [203, 181, 144],
        [203, 181, 144]],

       [[163, 147, 124],
        [163, 147, 124],
        [163, 147, 124],
        ...,
        [203, 181, 144],
        [203, 181, 144],
        [203, 181, 144]],

       [[164, 148, 125],
        [164, 148, 125],
        [164, 148, 125],
        ...,
        [203, 181, 144],
        [203, 181, 144],
        [203, 181, 144]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Just Resize', False, True, 512, 64, 64, 1, False, False, False, False, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "C:\MAIN\AI\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\MAIN\AI\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\MAIN\AI\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
    processed = process_images(p)
  File "C:\MAIN\AI\stable-diffusion-webui\modules\processing.py", line 479, in process_images
    res = process_images_inner(p)
  File "C:\MAIN\AI\stable-diffusion-webui\modules\processing.py", line 597, in process_images_inner
    uc = get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, p.steps, cached_uc)
  File "C:\MAIN\AI\stable-diffusion-webui\modules\processing.py", line 565, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "C:\MAIN\AI\stable-diffusion-webui\modules\prompt_parser.py", line 138, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\MAIN\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\MAIN\AI\stable-diffusion-webui\modules\sd_hijack_clip.py", line 220, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\MAIN\AI\stable-diffusion-webui\modules\sd_hijack_clip.py", line 245, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\MAIN\AI\stable-diffusion-webui\modules\sd_hijack_clip.py", line 293, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward
    return self.text_model(
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 643, in forward
    encoder_outputs = self.encoder(
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 574, in forward
    layer_outputs = encoder_layer(
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 317, in forward
    hidden_states, attn_weights = self.self_attn(
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 209, in forward
    query_states = self.q_proj(hidden_states) * self.scale
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\MAIN\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

**Comment by Lexcess** [comment]
You were first, but this seems to be the same as #252
