### ISSUE TITLE
[Bug]: Error running process...controlnet.py

### ISSUE THREAD

**Issue by Happytiger07** [Mikubill/sd-webui-controlnet#2355]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have seen other people with the same problem, but I haven't seen a solution that works for me yet. Controlnet worked for about 2 days before It stopped working saying:
*** Error running process: C:\Users\leifj\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
   

### Steps to reproduce the problem

.

### What should have happened?

.

### Commit where the problem happens

I get this when I try to generate.

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

openpose-editor
sd-civitai-browser-plus
sd-extension-system-info
sd-webui-controlnet
sd_civitai_extension

### Console logs

```Shell
*** Error running process: C:\Users\leifj\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\leifj\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\Users\leifj\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1053, in process
        self.controlnet_hack(p)
      File "C:\Users\leifj\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1042, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\leifj\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 750, in controlnet_main_entry
        Script.check_sd_version_compatible(unit)
      File "C:\Users\leifj\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 702, in check_sd_version_compatible
        raise Exception(f"ControlNet model {unit.model}({cnet_sd_version}) is not compatible with sd model({sd_version})")
    Exception: ControlNet model control_v11p_sd15_openpose [cab727d4](StableDiffusionVersion.SD1x) is not compatible with sd model(StableDiffusionVersion.SDXL)
```

**Comment by huchenlei** [comment]
You are trying to use an SD1.5 ControlNet model on SDXL base model. You can follow this thread to download ControlNet models for SDXL: https://github.com/Mikubill/sd-webui-controlnet/discussions/2039.
