### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'onnxruntime' when I use anime_openpose

### ISSUE THREAD

**Issue by edmondyip** [Mikubill/sd-webui-controlnet#2374]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I preview or generate image when animal openpose, it will have error in preview or generate image without controlnet.

### Steps to reproduce the problem

My controlnet settings
<img width="630" alt="Screenshot 2023-12-31 at 11 06 47" src="https://github.com/Mikubill/sd-webui-controlnet/assets/16853806/ca1be5cf-2068-43ae-8d2d-733b84bba677">

### What should have happened?

It should generate image when animal openpose

### Commit where the problem happens

webui:  v1.7.0
controlnet:  v1.1.425

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

- sd-webui-agent-scheduler
- sd-webui-animatediff
- sd-webui-controlnet
- sd-webui-segment-anything
- stable-diffusion-webui-state

### Console logs

```Shell
################################################################
Launching launch.py...
################################################################
Python 3.10.6 (main, Oct 12 2023, 01:22:54) [Clang 15.0.0 (clang-1500.0.40.1)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate --styles-file=./styles*.csv
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Using sqlite file: /Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-agent-scheduler/task_scheduler.sqlite3
ControlNet preprocessor location: /Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-12-31 11:30:34,908 - ControlNet - INFO - ControlNet v1.1.425
2023-12-31 11:30:34,979 - ControlNet - INFO - ControlNet v1.1.425
Loading weights [969673ad74] from /Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/models/Stable-diffusion/darkSushiMixMix_colorful.safetensors
Creating model from config: /Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/configs/v1-inference.yaml
2023-12-31 11:30:35,454 - AnimateDiff - INFO - Injecting LCM to UI.
2023-12-31 11:30:35,603 - AnimateDiff - INFO - Hacking i2i-batch.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 5.1s (prepare environment: 0.3s, import torch: 1.5s, import gradio: 0.4s, setup paths: 0.4s, initialize shared: 0.1s, other imports: 0.5s, load scripts: 0.9s, reload hypernetworks: 0.2s, create ui: 0.3s, gradio launch: 0.2s, app_started_callback: 0.1s).
Loading VAE weights specified in settings: /Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: sub-quadratic... done.
Model loaded in 2.5s (load weights from disk: 0.2s, create model: 0.6s, apply weights to model: 1.1s, load VAE: 0.1s, move model to device: 0.1s, calculate empty prompt: 0.2s).
2023-12-31 11:31:02,738 - ControlNet - INFO - Preview Resolution = 512
Downloading: "https://huggingface.co/yzd-v/DWPose/resolve/main/yolox_l.onnx" to /Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/openpose/yolox_l.onnx

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 207M/207M [00:35<00:00, 6.13MB/s]
Downloading: "https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/resolve/main/Annotators/rtmpose-m_simcc-ap10k_pt-aic-coco_210e-256x256-7a041aa1_20230206.onnx" to /Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/openpose/rtmpose-m_simcc-ap10k_pt-aic-coco_210e-256x256-7a041aa1_20230206.onnx

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52.0M/52.0M [00:08<00:00, 6.20MB/s]
Traceback (most recent call last):
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 703, in run_annotator
    result, is_image = preprocessor(
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 75, in decorated_func
    return cached_func(*args, **kwargs)
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 63, in cached_func
    return func(*args, **kwargs)
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 253, in run_model
    return remove_pad(self.model_openpose(
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/__init__.py", line 443, in __call__
    animals = self.detect_poses_animal(oriImg)
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/__init__.py", line 410, in detect_poses_animal
    self.load_animalpose_model()
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/__init__.py", line 262, in load_animalpose_model
    self.animal_pose_estimation = AnimalPose(onnx_det, onnx_pose)
  File "/Users/edmondyip/Documents/stable-diffusion/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/animalpose.py", line 88, in __init__
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'

```
```


### Additional information

_No response_

**Comment by huchenlei** [comment]
Sorry about that, I will submit a PR soon to make inference depend on opencv instead.
