### ISSUE TITLE
[Bug]: match statement is breaking Python 3.9-based installation

### ISSUE THREAD

**Issue by HowToSD** [Mikubill/sd-webui-controlnet#2381]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

https://github.com/Mikubill/sd-webui-controlnet/blob/main/scripts/enums.py contains:
   def encoder_block_num(self) -> int:
        match self:
match is added in Python 3.10 (https://peps.python.org/pep-0634/) and does not work with Python 3.9.
This causes an exception upon installing the extension on Automatic1111 using Python 3.9.

### Steps to reproduce the problem

1. Install Automatic1111 webui with Python 3.9
2. Install sd-webui-controlnet
3. Restart Automatic1111 webui

### What should have happened?

Use if else or some other backward compatible code.

### Commit where the problem happens

webui: cf2772fab0af5573da775e7437e6acdca424f26e.
controlnet: 0c0eb6b3179506099e793693874d6f19ee799e29

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

    LDSR
    Lora
    ScuNET
    SwinIR
    canvas-zoom-and-pan
    extra-options-section
    hypertile
    mobile
    prompt-bracket-checker
    sd-webui-controlnet

### Console logs

```Shell
*** Error loading script: api.py
Traceback (most recent call last):
File "<Installation directory>/stable-diffusion-webui/modules/scripts.py", line 469, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "<Installation directory>/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
module_spec.loader.exec_module(module)
File "", line 850, in exec_module
File "", line 228, in _call_with_frames_removed
File "<Installation directory>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 15, in
from scripts import external_code, global_state
File "<Installation directory>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in
from internal_controlnet.external_code import *
File "<Installation directory>/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in
from scripts import global_state
File "<Installation directory>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 12, in
from scripts.enums import StableDiffusionVersion
File "<Installation directory>/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 29
match self:
^
SyntaxError: invalid syntax
```
```


### Additional information

_No response_

**Comment by HowToSD** [comment]
@huchenlei Thank you for your super speedy fix. I really appreciate it.
