### ISSUE TITLE
[Bug]: Animatediff + CN (hr_option error)

### ISSUE THREAD

**Issue by IvanKorobko** [Mikubill/sd-webui-controlnet#2388]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

An error occurs when trying to use Controlnet with Animatediff in Automatic1111. While the preprocessor is running, it writes an error and continues to generate animation without the participation of the controlnet because preprocessor images were not generated.

### Steps to reproduce the problem

1. Enable Animatediff (any model, any animation type)
2. Enable Controlnet (any model)
3. Choose any image in tab (for processing by preprocessor)
4. Run generation

### What should have happened?

The animation must be generated using controlnet (lineart, IP adapter, openpose or any other)

### Commit where the problem happens

webui: cf2772fab0af5573da775e7437e6acdca424f26e
controlnet: bd23a0ecb63f3b4108e5518f24b0226a9fd5b5ac
animatediff: 55ecff365615aee28292ccbcea4c1de65b224fe6

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--autolaunch --theme=dark --xformers --upcast-sampling --medvram-sdxl --disable-safe-unpickle
```

### List of enabled extensions

![Без имени](https://github.com/Mikubill/sd-webui-controlnet/assets/31900557/2902664f-b842-415f-86d5-d2c1fc4e3c41)

### Console logs

```Shell
G:\neuro\stable-diffusion-webui>git pull
Already up to date.
venv "G:\neuro\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Civitai Link revision: 2008ba9126ddbb448f23267029b07e4610dffc15
SD-WebUI revision: cf2772fab0af5573da775e7437e6acdca424f26e

Checking Civitai Link requirements...
[+] python-socketio[client] version 5.7.2 installed.

#######################################################################################################
Launching Web UI with arguments: --autolaunch --theme=dark --xformers --upcast-sampling --medvram-sdxl --disable-safe-unpickle
[-] ADetailer initialized. version: 23.12.0, num models: 11
ControlNet preprocessor location: G:\neuro\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-01-02 14:13:36,558 - ControlNet - INFO - ControlNet v1.1.426
2024-01-02 14:13:36,677 - ControlNet - INFO - ControlNet v1.1.426
Civitai: API loaded
Loading weights [a7662a2ad3] from G:\neuro\stable-diffusion-webui\models\Stable-diffusion\SD_Cartoon_ArthemyComics_v50.safetensors
2024-01-02 14:13:36,996 - AnimateDiff - INFO - Injecting LCM to UI.
2024-01-02 14:13:37,311 - AnimateDiff - INFO - Hacking i2i-batch.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: G:\neuro\stable-diffusion-webui\configs\v1-inference.yaml
Civitai: Check resources for missing info files
Civitai: Check resources for missing preview images
Startup time: 17.5s (prepare environment: 6.1s, import torch: 3.1s, import gradio: 1.1s, setup paths: 0.8s, initialize shared: 0.2s, other imports: 0.6s, setup codeformer: 0.2s, load scripts: 3.7s, create ui: 0.8s, gradio launch: 0.6s).
Civitai: Found 4 resources missing info files
Civitai: Found 3 resources missing preview images
Civitai: No info found on Civitai
Civitai: No preview images found on Civitai
Loading VAE weights specified in settings: G:\neuro\stable-diffusion-webui\models\VAE\blessed2.vae.pt
Applying attention optimization: xformers... done.
Model loaded in 5.1s (load weights from disk: 1.1s, create model: 0.5s, apply weights to model: 2.7s, load VAE: 0.4s, calculate empty prompt: 0.2s).
2024-01-02 14:14:34,900 - AnimateDiff - INFO - AnimateDiff process start.
2024-01-02 14:14:34,901 - AnimateDiff - INFO - Loading motion module mm_sd15_v3.safetensors from G:\neuro\stable-diffusion-webui\extensions\sd-webui-animatediff\model\mm_sd15_v3.safetensors
2024-01-02 14:14:34,979 - AnimateDiff - INFO - Guessed mm_sd15_v3.safetensors architecture: MotionModuleType.AnimateDiffV3
2024-01-02 14:14:37,436 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2024-01-02 14:14:37,948 - AnimateDiff - INFO - Injecting motion module mm_sd15_v3.safetensors into SD1.5 UNet input blocks.
2024-01-02 14:14:37,948 - AnimateDiff - INFO - Injecting motion module mm_sd15_v3.safetensors into SD1.5 UNet output blocks.
2024-01-02 14:14:37,949 - AnimateDiff - INFO - Setting DDIM alpha.
2024-01-02 14:14:37,958 - AnimateDiff - INFO - Injection finished.
2024-01-02 14:14:37,958 - AnimateDiff - INFO - Hacking CFGDenoiser forward function.
2024-01-02 14:14:37,959 - AnimateDiff - INFO - Hacking ControlNet.
2024-01-02 14:14:38,118 - ControlNet - INFO - Loading model: ip-adapter_sd15_light [be1c9b97]
2024-01-02 14:14:38,154 - ControlNet - INFO - Loaded state_dict from [G:\neuro\stable-diffusion-webui\models\ControlNet\ip-adapter_sd15_light.pth]
2024-01-02 14:14:38,267 - ControlNet - INFO - ControlNet model ip-adapter_sd15_light [be1c9b97] loaded.
2024-01-02 14:14:38,268 - ControlNet - INFO - Loading preprocessor: ip-adapter_clip_sd15
2024-01-02 14:14:38,268 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:09<00:00,  9.08s/it]
*** Error running process: G:\neuro\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "G:\neuro\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "G:\neuro\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "G:\neuro\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "G:\neuro\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 471, in hacked_main_entry
        forward_param = ControlParams(
    TypeError: ControlParams.__init__() missing 1 required positional argument: 'hr_option'

---
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.08it/s]
==========================================================================================0/20 [00:17<00:00,  1.11it/s]
A tensor with all NaNs was produced in VAE.
Web UI will now convert VAE into 32-bit float and retry.
To disable this behavior, disable the 'Automatically revert VAE to 32-bit floats' setting.
To always start with 32-bit VAE, use --no-half-vae commandline flag.
==========================================================================================
2024-01-02 14:15:11,438 - AnimateDiff - INFO - Restoring ControlNet.
2024-01-02 14:15:11,438 - AnimateDiff - INFO - Restoring CFGDenoiser forward function.
2024-01-02 14:15:11,439 - AnimateDiff - INFO - Restoring DDIM alpha.
2024-01-02 14:15:11,439 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet input blocks.
2024-01-02 14:15:11,440 - AnimateDiff - INFO - Removing motion module from SD1.5 UNet output blocks.
2024-01-02 14:15:11,440 - AnimateDiff - INFO - Removal finished.
2024-01-02 14:15:11,440 - AnimateDiff - INFO - Merging images into GIF.
2024-01-02 14:15:12,669 - AnimateDiff - INFO - AnimateDiff process end.
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:23<00:00,  1.20s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:23<00:00,  1.11it/s]
```

### Additional information

Until yesterday and the last update of CN, the error did not occur. I checked it on a clean reinstalled Stable Diffusion without arguments and extensions (except for controlnet and animatediff) - have same error.

**Comment by IvanKorobko** [comment]
And all works fine after downgrade to v1.1.425 commit: [74f3749fb438379c1a71d206ec23b2abc9fb486f](https://github.com/Mikubill/sd-webui-controlnet/commit/74f3749fb438379c1a71d206ec23b2abc9fb486f)

**Comment by HappyBoyPat** [comment]
how did you downgrade your CN? I am having similar issue...

**Comment by huchenlei** [comment]
The issue has been fixed in #2392. If you are still encountering the same issue in lastest version, please file a new issue. Thanks!

**Comment by HappyBoyPat** [comment]
could I trouble you to let me know how to do that ?  I have the latest
A1111 and the latest controlnet (just updated it now), and AnimateDiff
still will not see ControlNet.  It was all working fine last week, then
broke with one of the updates I think.

Any help would be greatly appreciated. It's been very frustrating..I had
just nailed down my ideal workflow for my project.  thanks in advance for
any help you can give.

-patrick

**Comment by huchenlei** [comment]
The issue you are encountering probably will be fixed by https://github.com/continue-revolution/sd-webui-animatediff/pull/409. However, the owner of sd-webui-animatediff has not review/merge that PR yet.

**Comment by HappyBoyPat** [comment]
okay..thank you. I will wait for updates I guess.  getting into scripting stuff, python, etc is all scary territory for my right sided brain :)    I was just glad to see I was not alone, so hopefully it will get fixed before too long.
