### ISSUE TITLE
[Bug]: 当我同时开启hiresfix和controlnet的时候遇到这个报错

### ISSUE THREAD

**Issue by lucifer726** [Mikubill/sd-webui-controlnet#2396]
*** Error running process: /root/autodl-tmp/hf-sd-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/root/autodl-tmp/hf-sd-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/root/autodl-tmp/hf-sd-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "/root/autodl-tmp/hf-sd-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/root/autodl-tmp/hf-sd-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 960, in controlnet_main_entry
        hr_option=HiResFixOption.from_value(unit.hr_option) if high_res_fix else HiResFixOption.BOTH,
      File "/root/autodl-tmp/hf-sd-webui/extensions/sd-webui-controlnet/scripts/enums.py", line 78, in from_value
        return HiResFixOption(value)
      File "/root/miniconda3/lib/python3.10/enum.py", line 385, in __call__
        return cls.__new__(cls, value)
      File "/root/miniconda3/lib/python3.10/enum.py", line 710, in __new__
        raise ve_exc
    ValueError: 'HiResFixOption.BOTH' is not a valid HiResFixOption

**Comment by ShaunCassidyPoster** [comment]
I get a similar error when using sending "PNG Info" to "text2imag" using an image generated prior to me updating Controlnet and Automatic1111 today.

```
*** Error running process: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 960, in controlnet_main_entry
        hr_option=HiResFixOption.from_value(unit.hr_option) if high_res_fix else HiResFixOption.BOTH,
      File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\enums.py", line 78, in from_value
        return HiResFixOption(value)
      File "C:\Users\ShaunCassidy\.pyenv\pyenv-win\versions\3.10.6\lib\enum.py", line 385, in __call__
        return cls.__new__(cls, value)
      File "C:\Users\ShaunCassidy\.pyenv\pyenv-win\versions\3.10.6\lib\enum.py", line 710, in __new__
        raise ve_exc
    ValueError: 'HiResFixOption.BOTH' is not a valid HiResFixOption
```

If I manually paste the prompts in and reselect options by hand, then I can generate Controlnet images again (but High-Res Fix works poorly to my eye). I have also noted discrepancies in the PNG info I can see by opening images in Notepad++. Newly generated Controlnet images refer to an "Hr Option: Both" value, while previous ones don't (perhaps that's why previous gens produce an error--they don't seem to have this):

`Denoising strength: 0.2, ControlNet 0: "Module: depth_midas, Model: control_sd15_depth [fef5e48e], Weight: 1.2, Resize Mode: Crop and Resize, Low Vram: False, Processor Res: 512, Guidance Start: 0, Guidance End: 1, Pixel Perfect: True, Control Mode: My prompt is more important, Hr Option: Both, Save Detected Map: True", Hires upscale: 2, Hires steps: 150, Hires upscaler: 4x-UltraSharp,`

The reason I have not just carried on is that Automatic1111's High-Res Fix is no longer working satisfactorily whether I am using Controlnet or not, and so far I'm unable to determine whether it is a problem with Controlnet or Automatic1111.
