### ISSUE TITLE
[Bug]: Inpainting in A1111, controlnet uses the whole image instead of just the inpaint area

### ISSUE THREAD

**Issue by Kdawg50000** [Mikubill/sd-webui-controlnet#2402]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

This started about 2 days ago after I did an update. Using inpainting in A1111, I paint a small area to fix. I enable controlnet (depth, canny, etc). The controlnet preprocessor always uses the whole image instead of just the inpaint area. This results with the whole image jammed into a the small inpaint area.

### Steps to reproduce the problem

1. Go to A1111, img2img, inpaint tab
2. Inpaint a mask area
3. Enable controlnet (canny, depth, etc)
4. Generate

### What should have happened?

What should have happened is controlnet would only have used the small inpaint area for the preprocessor.

### Commit where the problem happens

webui: A1111
version: [v1.7.0]
python: 3.10.6
torch: 2.0.1+cu118
xformers: 0.0.20
gradio: 3.41.2
checkpoint: [84d76a0328]
controlnet: v1.1.427

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers --no-half-vae
git pull
call webui.bat
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/155604577/79c3fd65-2ccb-462f-b67d-893de74634cd)

### Console logs

```Shell
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 10 (delta 6), reused 10 (delta 6), pack-reused 0
Unpacking objects: 100% (10/10), 7.47 KiB | 22.00 KiB/s, done.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * [new branch]        mass-file-lister -> origin/mass-file-lister
Already up to date.
venv "D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing sd-webui-controlnet requirement: trimesh[easy]
ReActor preheating... Device: CUDA
*** Error running install.py for extension D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask.
*** Command: "D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe" "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\install.py"
*** Error code: 1
*** stderr: A matching Triton is not available, some optimizations will not be enabled.
*** Error caught was: No module named 'triton'
*** D:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** Traceback (most recent call last):
***   File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\install.py", line 6, in <module>
***     from modules.sd_models import model_hash
***   File "D:\StableDiffusion\stable-diffusion-webui\modules\sd_models.py", line 16, in <module>
***     from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config, sd_unet, sd_models_xl, cache, extra_networks, processing, lowvram, sd_hijack, patches
***   File "D:\StableDiffusion\stable-diffusion-webui\modules\sd_vae.py", line 5, in <module>
***     from modules import paths, shared, devices, script_callbacks, sd_models, extra_networks, lowvram, sd_hijack, hashes
***   File "D:\StableDiffusion\stable-diffusion-webui\modules\sd_hijack.py", line 5, in <module>
***     from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
***   File "D:\StableDiffusion\stable-diffusion-webui\modules\sd_hijack_optimizations.py", line 13, in <module>
***     from modules.hypernetworks import hypernetwork
***   File "D:\StableDiffusion\stable-diffusion-webui\modules\hypernetworks\hypernetwork.py", line 13, in <module>
***     from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
***   File "D:\StableDiffusion\stable-diffusion-webui\modules\sd_samplers.py", line 59, in <module>
***     set_samplers()
***   File "D:\StableDiffusion\stable-diffusion-webui\modules\sd_samplers.py", line 44, in set_samplers
***     samplers_hidden = set(shared.opts.hide_samplers)
*** AttributeError: 'NoneType' object has no attribute 'hide_samplers'
Launching Web UI with arguments: --xformers --no-half-vae
[-] ADetailer initialized. version: 23.12.0, num models: 9
ControlNet preprocessor location: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-01-03 22:49:06,793 - ControlNet - INFO - ControlNet v1.1.427
2024-01-03 22:49:06,855 - ControlNet - INFO - ControlNet v1.1.427
22:49:07 - ReActor - STATUS - Running v0.6.0-a4
*** Error loading script: em_api.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_api.py", line 16, in <module>
        from eyemask.api import EyeMaskApi
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\api\__init__.py", line 3, in <module>
        from . api import EyeMaskApi
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\api\api.py", line 8, in <module>
        from .. import script as eye_mask_script
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
        from . import mask_generator, utils, widlcards
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 2, in <module>
        import dlib
    ModuleNotFoundError: No module named 'dlib'

---
*** Error loading script: em_script.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_script.py", line 15, in <module>
        from eyemask import constants, ui, script as eye_mask_script
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\ui.py", line 8, in <module>
        from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
        from . import mask_generator, utils, widlcards
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 2, in <module>
        import dlib
    ModuleNotFoundError: No module named 'dlib'

---
*** Error loading script: em_script_embedded.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\em_script_embedded.py", line 15, in <module>
        from eyemask import constants, ui, script_embedded as eye_mask_script
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\ui.py", line 8, in <module>
        from . import constants, script, script_embedded, utils, widlcards, state, mask_generator
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\script.py", line 7, in <module>
        from . import mask_generator, utils, widlcards
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-eyemask\scripts\eyemask\mask_generator.py", line 2, in <module>
        import dlib
    ModuleNotFoundError: No module named 'dlib'

---
Loading weights [84d76a0328] from D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\epicrealism_naturalSinRC1VAE.safetensors
2024-01-03 22:49:07,201 - AnimateDiff - INFO - Injecting LCM to UI.
2024-01-03 22:49:07,371 - AnimateDiff - INFO - Hacking i2i-batch.
*Deforum ControlNet support: enabled*
Creating model from config: D:\StableDiffusion\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.0s (prepare environment: 9.3s, import torch: 2.1s, import gradio: 0.5s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, setup codeformer: 0.2s, load scripts: 2.1s, create ui: 0.5s, gradio launch: 0.3s).
Applying attention optimization: xformers... done.
Model loaded in 2.4s (load weights from disk: 0.4s, create model: 0.5s, apply weights to model: 1.3s).
2024-01-03 22:49:30,214 - ControlNet - INFO - (False, 0, False)
2024-01-03 22:49:30,782 - ControlNet - INFO - (True, 0, False)
2024-01-03 22:49:30,788 - ControlNet - INFO - (True, 0, False)
[-] ADetailer: img2img inpainting detected. adetailer disabled.
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.11it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 11.55it/s]
2024-01-03 22:50:32,430 - ControlNet - INFO - (True, 1, False)█████████████████████████| 16/16 [00:01<00:00, 14.63it/s]
2024-01-03 22:50:32,434 - ControlNet - INFO - (True, 1, False)
2024-01-03 22:50:32,464 - ControlNet - INFO - (True, 1, False)
[-] ADetailer: img2img inpainting detected. adetailer disabled.
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 14.54it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.09it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.████████████████████████| 16/16 [00:01<00:00, 14.63it/s]
2024-01-03 22:50:58,801 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:50:59,024 - ControlNet - INFO - Loading model: control_v11f1p_sd15_depth [cfd03158]
2024-01-03 22:50:59,635 - ControlNet - INFO - Loaded state_dict from [D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11f1p_sd15_depth.pth]
2024-01-03 22:50:59,636 - ControlNet - INFO - controlnet_default_config
2024-01-03 22:51:01,605 - ControlNet - INFO - ControlNet model control_v11f1p_sd15_depth [cfd03158] loaded.
2024-01-03 22:51:01,726 - ControlNet - INFO - Loading preprocessor: depth
2024-01-03 22:51:01,727 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:51:04,064 - ControlNet - INFO - ControlNet Hooked - Time = 5.266101837158203
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  8.63it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.54it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.████████████████████████| 16/16 [00:02<00:00,  9.78it/s]
2024-01-03 22:51:37,241 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:51:37,440 - ControlNet - INFO - Loading model from cache: control_v11f1p_sd15_depth [cfd03158]
2024-01-03 22:51:37,492 - ControlNet - INFO - Loading preprocessor: depth
2024-01-03 22:51:37,492 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:51:37,517 - ControlNet - INFO - ControlNet Hooked - Time = 0.28031253814697266
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.96it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.27it/s]
2024-01-03 22:54:34,384 - ControlNet - INFO - (True, 1, True)██████████████████████████| 16/16 [00:02<00:00, 10.15it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.
2024-01-03 22:55:06,793 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:55:06,796 - ControlNet - INFO - Loading model from cache: control_v11f1p_sd15_depth [cfd03158]
2024-01-03 22:55:07,164 - ControlNet - INFO - using mask as input
2024-01-03 22:55:07,170 - ControlNet - INFO - Loading preprocessor: none
2024-01-03 22:55:07,170 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:55:07,290 - ControlNet - INFO - ControlNet Hooked - Time = 0.5004820823669434
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.59it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.37it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.████████████████████████| 16/16 [00:02<00:00,  9.56it/s]
2024-01-03 22:55:32,933 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:55:33,170 - ControlNet - INFO - Loading model: control_v11p_sd15_canny [d14c016b]
2024-01-03 22:55:42,019 - ControlNet - INFO - Loaded state_dict from [D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.pth]
2024-01-03 22:55:42,020 - ControlNet - INFO - controlnet_default_config
2024-01-03 22:55:44,207 - ControlNet - INFO - ControlNet model control_v11p_sd15_canny [d14c016b] loaded.
2024-01-03 22:55:44,282 - ControlNet - INFO - using mask as input
2024-01-03 22:55:44,285 - ControlNet - INFO - Loading preprocessor: none
2024-01-03 22:55:44,286 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:55:44,347 - ControlNet - INFO - ControlNet Hooked - Time = 11.417062520980835
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  8.72it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.50it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.████████████████████████| 16/16 [00:02<00:00,  9.98it/s]
2024-01-03 22:56:05,200 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:56:05,206 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2024-01-03 22:56:05,209 - ControlNet - INFO - Loading preprocessor: canny
2024-01-03 22:56:05,209 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:56:05,234 - ControlNet - INFO - ControlNet Hooked - Time = 0.037030696868896484
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.10it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.22it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.████████████████████████| 16/16 [00:02<00:00,  9.20it/s]
2024-01-03 22:56:30,969 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:56:30,976 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2024-01-03 22:56:30,979 - ControlNet - INFO - using mask as input
2024-01-03 22:56:30,983 - ControlNet - INFO - Loading preprocessor: none
2024-01-03 22:56:30,984 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:56:31,046 - ControlNet - INFO - ControlNet Hooked - Time = 0.08108830451965332
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.57it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.45it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.████████████████████████| 16/16 [00:02<00:00,  9.65it/s]
2024-01-03 22:57:01,523 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:57:01,530 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2024-01-03 22:57:01,532 - ControlNet - INFO - using mask as input
2024-01-03 22:57:01,535 - ControlNet - INFO - Loading preprocessor: none
2024-01-03 22:57:01,536 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:57:01,595 - ControlNet - INFO - ControlNet Hooked - Time = 0.07492995262145996
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.59it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.48it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.████████████████████████| 16/16 [00:02<00:00,  9.55it/s]
2024-01-03 22:57:22,445 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:57:22,445 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2024-01-03 22:57:22,460 - ControlNet - INFO - using mask as input
2024-01-03 22:57:22,463 - ControlNet - INFO - Loading preprocessor: none
2024-01-03 22:57:22,464 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:57:22,524 - ControlNet - INFO - ControlNet Hooked - Time = 0.0797281265258789
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.89it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 16/16 [00:02<00:00,  6.50it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.████████████████████████| 16/16 [00:02<00:00, 10.17it/s]
2024-01-03 22:57:52,286 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:57:52,293 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2024-01-03 22:57:52,295 - ControlNet - INFO - using mask as input
2024-01-03 22:57:52,298 - ControlNet - INFO - Loading preprocessor: none
2024-01-03 22:57:52,299 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:57:52,359 - ControlNet - INFO - ControlNet Hooked - Time = 0.07552599906921387
100%|██████████████████████████████████████████████████████████████████████████████████| 19/19 [00:02<00:00,  6.77it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 19/19 [00:06<00:00,  2.92it/s]
2024-01-03 22:58:30,798 - ControlNet - INFO - (True, 1, False)█████████████████████████| 19/19 [00:06<00:00,  7.77it/s]
2024-01-03 22:58:33,883 - ControlNet - INFO - (True, 1, True)
[-] ADetailer: img2img inpainting detected. adetailer disabled.
100%|██████████████████████████████████████████████████████████████████████████████████| 19/19 [00:01<00:00, 11.34it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 19/19 [00:05<00:00,  3.24it/s]
2024-01-03 22:59:04,203 - ControlNet - INFO - (True, 1, False)█████████████████████████| 19/19 [00:05<00:00, 11.38it/s]
[-] ADetailer: img2img inpainting detected. adetailer disabled.
2024-01-03 22:59:16,020 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-03 22:59:16,026 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_canny [d14c016b]
2024-01-03 22:59:16,075 - ControlNet - INFO - Loading preprocessor: canny
2024-01-03 22:59:16,076 - ControlNet - INFO - preprocessor resolution = 512
2024-01-03 22:59:16,099 - ControlNet - INFO - ControlNet Hooked - Time = 0.08233642578125
100%|██████████████████████████████████████████████████████████████████████████████████| 19/19 [00:02<00:00,  7.75it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 19/19 [00:06<00:00,  2.92it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 19/19 [00:06<00:00,  7.59it/s]
```

**Comment by huchenlei** [comment]
![1704342700646](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/4ffc6fbe-2108-492e-81ef-38a7c090792a)

See https://github.com/Mikubill/sd-webui-controlnet/pull/2377.

Some other group of users want the other behaviour in https://github.com/Mikubill/sd-webui-controlnet/issues/2148.

**Comment by Kdawg50000** [comment]
Ah, a new checkbox snuck in there :-)
So I have to check "Upload independent control image" to see that option.
I just tested and I see that even though I check "Upload independent control image", I don't actually have to paste an image there, which is nice. Saves a step of pasting the same image from my img2img.

**Comment by huchenlei** [comment]
Wait a minute, maybe the checkbox should show even you don't use independent control image. I will test and adjust that.
