### ISSUE TITLE
I can't find "ControlNet" menu in the settings tab.

### ISSUE THREAD

**Issue by CrypticToilet** [Mikubill/sd-webui-controlnet#242]
I can't find "ControlNet" menu in the settings tab.
I think it was still there yesterday.
My webUI and sd-webui-controlnet  is up to date.
Has it been moved somewhere else?

**Comment by zhoobin021** [comment]
I have the same issue!

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/4737b4189c6b7b55e7fa43316a5a33554d5d7c42

**Comment by ljleb** [comment]
introduced here: 858a5b5679ecc99382125da7adcd5b3ccdc3fe09

One suggestion I have to allow other scripts to include the controlnet extension would be to create a separate file or module for this purpose. Put the shared code in a different folder and include it in both the script and the importable module.

**Comment by zhoobin021** [comment]
@Mikubill I have updated the extension again now, it's fixed, thank you.

**Comment by CrypticToilet** [comment]
Thank you for your hard work!

**Comment by 4rkl4y** [comment]
got this error after the update

```
Error loading script: controlnet.py
Traceback (most recent call last):
  File "H:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "H:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 13, in <module>
    from scripts.cldm import PlugableControlModel
ModuleNotFoundError: No module named 'scripts.cldm'; 'scripts' is not a package

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "H:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "H:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 2, in <module>
    from scripts import controlnet
ImportError: cannot import name 'controlnet' from 'scripts' (H:\A1111 Web UI Autoinstaller\stable-diffusion-webui\../..\scripts.py)


```
