### ISSUE TITLE
[Bug]: ValueError: controlnet is enabled but no input image is given.

### ISSUE THREAD

**Issue by LucasMali** [Mikubill/sd-webui-controlnet#2437]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

1. Started Automatic1111
1. In the web GUI, added a prompt to txt2img
1. In controlnet added an image and selected open pose
1. Clicked generate

### Steps to reproduce the problem

1. Started Automatic1111
1. In the web GUI, added a prompt to txt2img
1. In controlnet added an image and selected open pose
1. Click generate

### What should have happened?

The image should look similar to that of the controlnet open pose image.

### Commit where the problem happens

webui: 
controlnet: 
terminal:
```
*** Error running process: C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\lucas\sd.webui\webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 777, in controlnet_main_entry
        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
      File "C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 657, in choose_input_image
        raise ValueError('controlnet is enabled but no input image is given')
    ValueError: controlnet is enabled but no input image is given
    
```

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome, Brave, Microsoft Edge

### Command Line Arguments

```Shell
No, just the automatic1111 script provided
```

### List of enabled extensions

Extension | URL | Branch | Version | Date | Update
-- | -- | -- | -- | -- | --
LDSR | built-in | None |   |   |  
Lora | built-in | None |   |   |  
ScuNET | built-in | None |   |   |  
SwinIR | built-in | None |   |   |  
canvas-zoom-and-pan | built-in | None |   |   |  
extra-options-section | built-in | None |   |   |  
hypertile | built-in | None |   |   |  
mobile | built-in | None |   |   |  
prompt-bracket-checker | built-in | None |   |   |  
--sd-webui-ar-plus | https://github.com/LEv145/--sd-webui-ar-plus | main | cbb397e7 | 2023-11-28 11:30:35 | unknown
Stable-Diffusion-Webui-Civitai-Helper | https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper.git | master | 203cd5a1 | 2023-12-03 18:04:24 | unknown
Styles-Editor | https://github.com/chrisgoringe/Styles-Editor.git | main | 025f17f7 | 2023-12-06 21:14:43 | unknown
a1111-sd-webui-lycoris | https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git | main | df9c0093 | 2023-08-21 03:13:30 | unknown
clip-interrogator-ext | https://github.com/pharmapsychotic/clip-interrogator-ext.git | main | 0f1a4591 | 2023-09-09 19:35:46 | unknown
sd-dynamic-prompts | https://github.com/adieyal/sd-dynamic-prompts.git | main | 284d3ef3 | 2023-12-29 05:26:56 | unknown
sd-webui-controlnet | https://github.com/Mikubill/sd-webui-controlnet.git | main | bb9483d4 | 2024-01-07 17:08:18 | unknown
sd-webui-prompt-history | https://github.com/namkazt/sd-webui-prompt-history | main | dad4e456 | 2023-11-04 11:34:31 | unknown
ultimate-upscale-for-automatic1111 | https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git | master | 728ffcec | 2023-09-09 04:47:23 | unknown

### Console logs

```Shell
*** Error running process: C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\lucas\sd.webui\webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 777, in controlnet_main_entry
        input_image, image_from_a1111 = Script.choose_input_image(p, unit, idx)
      File "C:\Users\lucas\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 657, in choose_input_image
        raise ValueError('controlnet is enabled but no input image is given')
    ValueError: controlnet is enabled but no input image is given
    
```
```


### Additional information

It started after I ran an update.

**Comment by vixenius** [comment]
Controlnet inpaint gives me similar error, even though "MASK UPLOAD" option is NOT checked.

*** Error running process: D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AINOVO\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1062, in process
        self.controlnet_hack(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1047, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 761, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 647, in choose_input_image
        raise ValueError("No mask detected for ControlNet inpaint")
    ValueError: No mask detected for ControlNet inpaint

**Comment by AlexYZT** [comment]
I was able to reproduce this issue. In summary, if ControlNet Unit 0 is enabled by default, it seems to cause this error, and switching it back to disabled by default fixes it. Steps to reproduce: 

1. Go to txt2img > Generation > ControlNet v1.1.455 > ControlNet Unit 0, then check the box labelled "Enable". 
2. Go to Settings > Other > Defaults, then click "View changes". It should display this:
```
Path			| Old value	| New value
txt2img/Enable/value	  False		  True
```
3. Click "Apply", then "Reload UI".
4. Go to txt2img > Generation > ControlNet v1.1.455 > ControlNet Unit 0 > Single Image, then click "Click to Upload" to upload a test image.
5. Click Generate.
