### ISSUE TITLE
[Bug]: When I used depth_midas preprocessor, it gave me ”TypeError: argument of type 'NoneType' is not iterable“.

### ISSUE THREAD

**Issue by QueenPuxxi** [Mikubill/sd-webui-controlnet#2439]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I used depth_midas preprocessor, I couldn't get the depth image.

### Steps to reproduce the problem

1. go to ControlNet
2. press "Depth" module and select the "depth_midas" preprocessor
3. upload the image
4. run preprocessor💥
5. an error has been reported

### What should have happened?

I'll get the depth image.

### Commit where the problem happens

webui: cf2772f
controlnet: bb9483d

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136255531/9461f22b-5724-441f-bb04-0c9a581126ce)

### Console logs

```Shell
2024-01-09 18:00:33,417 - ControlNet - INFO - Preview Resolution = 512
2024-01-09 18:00:55,511 - ControlNet - INFO - Preview Resolution = 512
2024-01-09 18:01:01,659 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-09 18:01:02,247 - ControlNet - INFO - Loading model from cache: bdsqlsz_controlllite_xl_depth [c4d5ca3b]
2024-01-09 18:01:02,294 - ControlNet - INFO - Loading preprocessor: depth_leres
2024-01-09 18:01:02,295 - ControlNet - INFO - preprocessor resolution = 512
2024-01-09 18:01:20,406 - ControlNet - INFO - ControlNet Hooked - Time = 18.7558650970459
2024-01-09 18:04:34,028 - ControlNet - INFO - Preview Resolution = 512
*** Error verifying pickled file from C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\annotator\downloads\midas\dpt_hybrid-midas-501f0c75.pt
*** -----> !!!! The file is most likely corrupted !!!! <-----
*** You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.
***
    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4.5\modules\safe.py", line 83, in check_pt
        with zipfile.ZipFile(filename) as z:
      File "C:\sd-webui-aki-v4.5\python\lib\zipfile.py", line 1269, in __init__
        self._RealGetContents()
      File "C:\sd-webui-aki-v4.5\python\lib\zipfile.py", line 1336, in _RealGetContents
        raise BadZipFile("File is not a zip file")
    zipfile.BadZipFile: File is not a zip file

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4.5\python\lib\pickle.py", line 1245, in load_persid
        pid = self.readline()[:-1].decode("ascii")
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 63: ordinal not in range(128)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\sd-webui-aki-v4.5\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "C:\sd-webui-aki-v4.5\modules\safe.py", line 104, in check_pt
        unpickler.load()
      File "C:\sd-webui-aki-v4.5\python\lib\pickle.py", line 1213, in load
        dispatch[key[0]](self)
      File "C:\sd-webui-aki-v4.5\python\lib\pickle.py", line 1247, in load_persid
        raise UnpicklingError(
    _pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

---
Traceback (most recent call last):
  File "C:\sd-webui-aki-v4.5\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\sd-webui-aki-v4.5\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\sd-webui-aki-v4.5\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\sd-webui-aki-v4.5\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\sd-webui-aki-v4.5\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\sd-webui-aki-v4.5\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\sd-webui-aki-v4.5\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 729, in run_annotator
    result, is_image = preprocessor(
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
    return func(*args, **kwargs)
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\scripts\processor.py", line 184, in midas
    result, _ = model_midas(img, a)
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\annotator\midas\__init__.py", line 19, in apply_midas
    model = MiDaSInference(model_type="dpt_hybrid")
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\annotator\midas\api.py", line 173, in __init__
    model, _ = load_model(model_type)
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\annotator\midas\api.py", line 108, in load_model
    model = DPTDepthModel(
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\annotator\midas\midas\dpt_depth.py", line 105, in __init__
    self.load(path)
  File "C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\annotator\midas\midas\base_model.py", line 13, in load
    if "optimizer" in parameters:
TypeError: argument of type 'NoneType' is not iterable
```

### Additional information

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/136255531/ff029f7a-0dca-4a2d-936e-6120445ed396)

**Comment by huchenlei** [comment]
According to the error log, you need to delete midas model file and re-download it.

```
*** Error verifying pickled file from C:\sd-webui-aki-v4.5\extensions\sd-webui-controlnet\annotator\downloads\midas\dpt_hybrid-midas-501f0c75.pt
*** -----> !!!! The file is most likely corrupted !!!! <-----
*** You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.
***
```

**Comment by QueenPuxxi** [comment]
Thank you very much! It really helps me!
