### ISSUE TITLE
I can't install ControlNet (help wanted)

### ISSUE THREAD

**Issue by LepLop-Onur** [Mikubill/sd-webui-controlnet#2444]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I tried to install ControlNet extension but unfortunately i couldn't. When i paste the link to "URL for extension's git repository" and click install i got error: ValueError: Reference at 'HEAD' does not exist. 
![errorType](https://github.com/Mikubill/sd-webui-controlnet/assets/93081444/a6aca074-d063-41d6-90c0-2e4b81944c0c)

### Steps to reproduce the problem

1. Click extensions tab on Automatic1111
2. Then press Install from URL
3. Then paste the link to "URL for extension's git repository" 
4. Click install

### What should have happened?

It supposed to be installed.

### Commit where the problem happens

webui: Automatic 1111
controlnet: I couldn't installed yet

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![extensions](https://github.com/Mikubill/sd-webui-controlnet/assets/93081444/92be00d5-0e6b-4019-925e-788d209f4119)

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Fetching updates for Stable Diffusion...
Checking out commit for Stable Diffusion with hash: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf...
Previous HEAD position was 47b6b60 Merge pull request #39 from CookieLau/patch-1
HEAD is now at cf1d67a Update modelcard.md
Cloning Stable Diffusion XL into C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\repositories\generative-models...
Cloning into 'C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\repositories\generative-models'...
remote: Enumerating objects: 860, done.
remote: Counting objects: 100% (503/503), done.
remote: Compressing objects: 100% (233/233), done.
remote: Total 860 (delta 359), reused 309 (delta 266), pack-reused 357
Receiving objects: 100% (860/860), 42.67 MiB | 4.47 MiB/s, done.
Resolving deltas: 100% (435/435), done.
Fetching updates for K-diffusion...
Checking out commit for K-diffusion with hash: ab527a9a6d347f364e3d185ba6d714e22d80cb3c...
Previous HEAD position was 5b3af03 Release 0.0.12
HEAD is now at ab527a9 Release 0.0.16
Installing requirements
Launching Web UI with arguments:
no module 'xformers'. Processing without...
No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu117. You might want to consider upgrading.
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\styles.csv
==============================================================================
You are running torch 1.13.1+cu117.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 3.97G/3.97G [14:43<00:00, 4.83MB/s]
Calculating sha256 for C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors: Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1047.7s (initial startup: 0.1s, prepare environment: 139.3s, import torch: 7.6s, import gradio: 2.4s, setup paths: 5.0s, import ldm: 0.1s, initialize shared: 0.6s, other imports: 3.1s, setup codeformer: 0.8s, list SD models: 883.9s, load scripts: 3.1s, create ui: 0.7s, gradio launch: 0.9s).
6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa
Loading weights [6ce0161689] from C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\configs\v1-inference.yaml
vocab.json: 100%|███████████████████████████████████████████████████████████████████| 961k/961k [00:00<00:00, 1.68MB/s]
merges.txt: 100%|███████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 2.62MB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████| 389/389 [00:00<?, ?B/s]
tokenizer_config.json: 100%|███████████████████████████████████████████████████████████| 905/905 [00:00<00:00, 897kB/s]
config.json: 100%|████████████████████████████████████████████████████████████████████████| 4.52k/4.52k [00:00<?, ?B/s]
Applying attention optimization: Doggettx... done.
Model loaded in 36.3s (calculate hash: 17.6s, load weights from disk: 0.5s, create model: 3.0s, apply weights to model: 4.5s, apply half(): 2.0s, load VAE: 0.2s, calculate empty prompt: 8.3s).
Reusing loaded model v1-5-pruned-emaonly.safetensors [6ce0161689] to load picxReal_10.safetensors
Calculating sha256 for C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\models\Stable-diffusion\picxReal_10.safetensors: 07919b495df62d7b1b2c6f1715669e1b8f9ce92e496de3a688b30744daece525
Loading weights [07919b495d] from C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\models\Stable-diffusion\picxReal_10.safetensors
Applying attention optimization: Doggettx... done.
Weights loaded in 80.9s (send model to cpu: 1.4s, calculate hash: 22.7s, load weights from disk: 3.4s, apply weights to model: 51.9s, move model to device: 1.5s).
WARNING:git.objects.submodule.base:Failed to checkout tracking branch refs/heads/master
*** Error completing request
*** Arguments: ('', 'https://github.com/Mikubill/sd-webui-controlnet', '') {}
    Traceback (most recent call last):
      File "C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\modules\ui_extensions.py", line 641, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "C:\Users\leplo\OneDrive\Masaüstü\sd.webui\webui\modules\ui_extensions.py", line 372, in install_extension_from_url
        submodule.update()
      File "C:\Users\leplo\OneDrive\Masaüstü\sd.webui\system\python\lib\site-packages\git\objects\submodule\base.py", line 729, in update
        is_detached = mrepo.head.is_detached
      File "C:\Users\leplo\OneDrive\Masaüstü\sd.webui\system\python\lib\site-packages\git\refs\symbolic.py", line 409, in is_detached
        self.ref
      File "C:\Users\leplo\OneDrive\Masaüstü\sd.webui\system\python\lib\site-packages\git\refs\symbolic.py", line 307, in _get_reference
        sha, target_ref_path = self._get_ref_info(self.repo, self.path)
      File "C:\Users\leplo\OneDrive\Masaüstü\sd.webui\system\python\lib\site-packages\git\refs\symbolic.py", line 210, in _get_ref_info
        return cls._get_ref_info_helper(repo, ref_path)
      File "C:\Users\leplo\OneDrive\Masaüstü\sd.webui\system\python\lib\site-packages\git\refs\symbolic.py", line 193, in _get_ref_info_helper
        raise ValueError("Reference at %r does not exist" % ref_path)
    ValueError: Reference at 'HEAD' does not exist

---
```

### Additional information

Pc specs:
graphic card: Gtx 950M
ram: 16 gb 
CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
OS: Windows 10

**Comment by huchenlei** [comment]
It seems to work fine in a local fresh A1111 checkout:
![1704921880874](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/86475b59-d362-44ed-aa13-88737250a7dd)

You probably want to file an issue in A1111 repo as the exception does not happen in this repo's code. https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues
