### ISSUE TITLE
"Error verifying pickled file" while using control net

### ISSUE THREAD

**Issue by PSC0027** [Mikubill/sd-webui-controlnet#245]
**_I have tried to used Control Net with SD-web-UI with Mikubil's project. After I loaded sd-webui-controlnet, the control net UI showed. But when I tried to use for example canny preprocessor. I got this Error:_**

Loading preprocessor: canny, model: control_sd15_canny [fef5e48e]
Error verifying pickled file from D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_canny.pth:
Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Users\PSC0027\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\PSC0027\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\modules\safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "D:\StableDiffusion\stable-diffusion-webui\modules\safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Error running process: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 469, in process
    state_dict = load_state_dict(model_path)
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 11, in load_state_dict
    state_dict = get_state_dict(torch.load(
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 19, in get_state_dict
    return d.get('state_dict', d)
AttributeError: 'NoneType' object has no attribute 'get'

**_Then I just got a result without affect from Control Net. Neither did I got proprocessed result. Could anyone help me with this problem? Thank you._**

**Comment by Mikubill** [comment]
If you believe the checkpoint file is safe and correct, try disable safety check using disable-safe-unpickle

**Comment by PSC0027** [comment]
_**Thank you for your reply! I tried disable safety check, and the previous error disappear. Unfortunately, I got a new error after trying to use control net:**_

Error running process: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 469, in process
    state_dict = load_state_dict(model_path)
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 11, in load_state_dict
    state_dict = get_state_dict(torch.load(
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\reallysafe.py", line 117, in load
    return load_with_extra(filename, *args, **kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd_dreambooth_extension\reallysafe.py", line 164, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\StableDiffusion\stable-diffusion-webui\PSC0027\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "D:\StableDiffusion\stable-diffusion-webui\PSC0027\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**_Still, I didn't got proprocessed result._**

**Comment by Mikubill** [comment]
Could you share your checkpoints' *filename* and simply run test below:
```py
# if your file ends with .pth
import torch
torch.load(filename).keys()

# if your file ends with .safetensors
from safetensors.torch import load_file
load_file(filename).keys()

```

**Comment by PSC0027** [comment]
**_For testing I used protogenV22:_**
![image](https://user-images.githubusercontent.com/48559024/220359456-91e55e49-1e77-4670-806f-0300acd0a276.png)



**_Configurations:_**
![image](https://user-images.githubusercontent.com/48559024/220358503-b0cde549-5dc8-4e2b-bca3-2425345eb1ed.png)
![image](https://user-images.githubusercontent.com/48559024/220358598-db32873d-49dc-469e-9abb-64bbb48fefb1.png)
![image](https://user-images.githubusercontent.com/48559024/220358688-55a65530-ca1d-4b77-9bf1-a2e1e8b059f6.png)


**_Result:_**
![image](https://user-images.githubusercontent.com/48559024/220359554-9611e195-ce56-4d0d-8245-e4001166c464.png)


**_I used a safetensors form model, so I should put following code into controlnet.py?_**

```
from safetensors.torch import load_file
load_file(filename).keys()
```

**Comment by Hantang-Li** [comment]
I faced the same problem. Later I found an error message as I used git clone to download the control net models, and the model's size I downloaded was much smaller than expected.
![1](https://user-images.githubusercontent.com/27784582/220473918-ba194cd3-b080-4ebe-ab28-d2736ca6d87a.png)
So I re-downloaded the models, and the problem was solved.

**Comment by PSC0027** [comment]
> I faced the same problem. Later I found an error message as I used git clone to download the control net models, and the model's size I downloaded was much smaller than expected. ![1](https://user-images.githubusercontent.com/27784582/220473918-ba194cd3-b080-4ebe-ab28-d2736ca6d87a.png) So I re-downloaded the models, and the problem was solved.

I re-downloaded the control net models manually from huggingface. It fixed my problem. Thank you!

**Comment by HEXtoDEC** [comment]
### There is another possibility

Back up and delete everything in the `\stable-diffusion-webui\models\leres` directory and let webui download again.
