### ISSUE TITLE
[Bug]: IP Adapter Facer ID Preprocessor crops image in img2img

### ISSUE THREAD

**Issue by rytt0001** [Mikubill/sd-webui-controlnet#2455]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

when using independant image in CN module, and that image is not the same size as the inpainted image (and the inpaint region is small, the independant image get cropped and the face recognition doesn't work.
a small fix workaroud I found is modifying the lines 811-814 in controlnet.py from: 
```python
 if (
                'reference' not in unit.module
                and is_only_masked_inpaint
                and (is_upscale_script or unit.inpaint_crop_input_image)
            ):
```
to :
```python
 if (
                'reference' not in unit.module
                and 'ip-adapter_face_id' not in unit.module
                and is_only_masked_inpaint
                and (is_upscale_script or unit.inpaint_crop_input_image)
            ):
```

as I thought that the IP adapter FaceID should maybe behave like reference, at least when using an independant image
because internally the preprocessor scan the image for a face.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

 I thought that the IP adapter FaceID should maybe behave like reference, at least when using an independant image
because internally the preprocessor scan the image for a face.

### Commit where the problem happens

webui: 1.6.0
controlnet: 1.1.430

### Command Line Arguments

```Shell
cd stable-diffusion-webui
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:128
python launch.py --listen --show-negative-prompt --disable-safe-unpickle --lowram --deepdanbooru --api --cors-allow-origins=* --skip-install --no-gradio-queue --opt-sdp-no-mem-attention
```

### List of enabled extensions

not a conflict between extensions

### Console logs

```Shell
2024-01-11 12:23:17,034 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-11 12:23:17,034 - ControlNet - INFO - Loading model from cache: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-01-11 12:23:17,034 - ControlNet - INFO - Loading preprocessor: ip-adapter_face_id_plus
2024-01-11 12:23:17,035 - ControlNet - INFO - preprocessor resolution = 896
2024-01-11 12:23:17,035 - ControlNet - INFO - Loading model from cache: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-01-11 12:23:17,036 - ControlNet - INFO - Loading preprocessor: ip-adapter_face_id_plus
2024-01-11 12:23:17,036 - ControlNet - INFO - preprocessor resolution = 896
*** Error running process: D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1095, in process
        self.controlnet_hack(p)
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1080, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 911, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 712, in face_id_plus
        face_embed, _ = g_insight_face_model.run_model(img)
      File "D:\ComfyUI_windows_portable\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 697, in run_model
        raise Exception("Insightface: No face found in image.")
    Exception: Insightface: No face found in image.

---
```

**Comment by huchenlei** [comment]
You can just uncheck "Crop Input image with A1111 mask" checkbox to achieve this.
