### ISSUE TITLE
[Bug]: None of the control models work after the update

### ISSUE THREAD

**Issue by vixenius** [Mikubill/sd-webui-controlnet#2456]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

So, i tried new openpose densepose preprocessor and it only works the first time you start automatic 1111, every other time you try to generate a pic it throws this error for openpose and other control types like depth, reference etc. This is the error log.

*** Error running process: D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AINOVO\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 756, in controlnet_main_entry
        self.unloadable.get(key, lambda:None)()
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 674, in unload_densepose_model
        model_densepose.unload_model()
    AttributeError: 'function' object has no attribute 'unload_model'

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

it should have worked

### Commit where the problem happens

webui: version: [v1.7.0]
controlnet: [v1.1.430]

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--xformers --autolaunch --api
```

### List of enabled extensions

![Screenshot 2024-01-11 s131654](https://github.com/Mikubill/sd-webui-controlnet/assets/11150079/1f4410d7-cfd1-4da1-ade6-8458010971e3)

### Console logs

```Shell
*** Error running process: D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AINOVO\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 756, in controlnet_main_entry
        self.unloadable.get(key, lambda:None)()
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 674, in unload_densepose_model
        model_densepose.unload_model()
    AttributeError: 'function' object has no attribute 'unload_model'
```

### Additional information

This is the log when i use controlnet densepose for the very first time, it loads the model and generates the picture, but like i said earlier, it just don't work the second time i try it and other control types start throwing the same error. 

2024-01-11 13:10:48,054 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-11 13:10:48,338 - ControlNet - INFO - Loading model: control_v11p_sd15_openpose [cab727d4]
2024-01-11 13:10:58,567 - ControlNet - INFO - Loaded state_dict from [D:\AINOVO\stable-diffusion-webui\models\ControlNet\control_v11p_sd15_openpose.pth]
2024-01-11 13:10:58,568 - ControlNet - INFO - controlnet_default_config
2024-01-11 13:11:00,650 - ControlNet - INFO - ControlNet model control_v11p_sd15_openpose [cab727d4] loaded.
2024-01-11 13:11:00,711 - ControlNet - INFO - Loading preprocessor: densepose
2024-01-11 13:11:00,711 - ControlNet - INFO - preprocessor resolution = 512
2024-01-11 13:11:12,077 - ControlNet - INFO - ControlNet Hooked - Time = 24.02637481689453

**Comment by huchenlei** [comment]
Problematic PR reverted.
