### ISSUE TITLE
[Bug]: ValueError: Reference at 'HEAD' does not exist

### ISSUE THREAD

**Issue by Terreas123** [Mikubill/sd-webui-controlnet#2479]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have just downloaded Stable Diffusion without a problem. I tried Installing this URL:: https://github.com/Mikubill/sd-webui-controlnet.git 
From: https://github.com/Mikubill/sd-webui-controlnet

But when copy paste this in the ''install from URL'' tab to ''URL for extension's git repository'' When I click install it gives me this error. 

And if I click install once again it says: GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v --filter=blob:none -- https://github.com/Mikubill/sd-webui-controlnet.git C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\tmp\sd-webui-controlnet stderr: 'fatal: destination path 'C:\Users\pc\OneDrive\MasaÃ¼stÃ¼\Stable Diffusion Kurulum Dosyalari\webui\tmp\sd-webui-controlnet' already exists and is not an empty directory. '

I tried deleting the file it shows me and tried again but it does not work. its just a repeating cycle for me. 

### Steps to reproduce the problem

1. Go to .... stabvle diffusion, put the url
2. Press .... install
3. ... error

### What should have happened?

should be installed like it said in this link https://github.com/Mikubill/sd-webui-controlnet

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

none

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments:
no module 'xformers'. Processing without...
No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cu117. You might want to consider upgrading.
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\styles.csv
==============================================================================
You are running torch 1.13.1+cu117.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Loading weights [6ce0161689] from C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\configs\v1-inference.yaml
Startup time: 7.4s (prepare environment: 1.2s, import torch: 2.1s, import gradio: 0.8s, setup paths: 0.7s, initialize shared: 0.2s, other imports: 0.5s, setup codeformer: 0.1s, load scripts: 1.0s, create ui: 0.2s, gradio launch: 0.4s).
Applying attention optimization: Doggettx... done.
Model loaded in 3.2s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 1.3s, apply half(): 0.4s, move model to device: 0.3s, calculate empty prompt: 0.4s).
WARNING:git.objects.submodule.base:Failed to checkout tracking branch refs/heads/master
*** Error completing request
*** Arguments: ('', 'https://github.com/Mikubill/sd-webui-controlnet.git', '') {}
    Traceback (most recent call last):
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\modules\ui_extensions.py", line 641, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\modules\ui_extensions.py", line 372, in install_extension_from_url
        submodule.update()
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\objects\submodule\base.py", line 729, in update
        is_detached = mrepo.head.is_detached
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\refs\symbolic.py", line 409, in is_detached
        self.ref
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\refs\symbolic.py", line 307, in _get_reference
        sha, target_ref_path = self._get_ref_info(self.repo, self.path)
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\refs\symbolic.py", line 210, in _get_ref_info
        return cls._get_ref_info_helper(repo, ref_path)
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\refs\symbolic.py", line 193, in _get_ref_info_helper
        raise ValueError("Reference at %r does not exist" % ref_path)
    ValueError: Reference at 'HEAD' does not exist

---
*** Error completing request
*** Arguments: ('', 'https://github.com/Mikubill/sd-webui-controlnet.git', '') {}
    Traceback (most recent call last):
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\modules\ui_extensions.py", line 641, in <lambda>
        fn=modules.ui.wrap_gradio_call(lambda *args: [gr.update(), *install_extension_from_url(*args)], extra_outputs=[gr.update(), gr.update()]),
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\modules\ui_extensions.py", line 369, in install_extension_from_url
        with git.Repo.clone_from(url, tmpdir, filter=['blob:none']) as repo:
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\repo\base.py", line 1327, in clone_from
        return cls._clone(
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\repo\base.py", line 1236, in _clone
        finalize_process(proc, stderr=stderr)
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\util.py", line 419, in finalize_process
        proc.wait(**kwargs)
      File "C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\system\python\lib\site-packages\git\cmd.py", line 604, in wait
        raise GitCommandError(remove_password_if_present(self.args), status, errstr)
    git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
      cmdline: git clone -v --filter=blob:none -- https://github.com/Mikubill/sd-webui-controlnet.git C:\Users\pc\OneDrive\Masaüstü\Stable Diffusion Kurulum Dosyalari\webui\tmp\sd-webui-controlnet
      stderr: 'fatal: destination path 'C:\Users\pc\OneDrive\MasaÃ¼stÃ¼\Stable Diffusion Kurulum Dosyalari\webui\tmp\sd-webui-controlnet' already exists and is not an empty directory.
    '
```

### Additional information

none

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/issues/2444. 

You probably want to file an issue in A1111 repo, as the code throws the exception is in A1111 repo. https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/issues
