### ISSUE TITLE
[Bug]: Is Outpainting Broken?

### ISSUE THREAD

**Issue by Haoming02** [Mikubill/sd-webui-controlnet#2480]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I tried to do Outpainting again today, it now throws an `No mask detected` error instead.

### Steps to reproduce the problem

1. Go to `txt2img`
2. Enable `ControlNet`
3. Set to `Inpaint`
4. Upload an image
5. Set render resolution to a different aspect ratio than that of the uploaded image
6. Set `Resize Mode` to `Resize and Fill`
7. Press `Generate`
8. See an error message and incorrect results

### What should have happened?

Before, it would not throw any error, and would correctly outpaint the "missing area" of the image

### Commit where the problem happens

**Webui:** [v1.7.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cf2772fab0af5573da775e7437e6acdca424f26e)
**ControlNet:** [8b5f7c1d](https://github.com/Mikubill/sd-webui-controlnet/commit/8b5f7c1d0e6b857b9033a54226ad83714553770d)

*(Haven't tried this for a while, so I can only give my current version.)*

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--xformers --no-half-vae
```

### List of enabled extensions

<p align="center"><img src="https://github.com/Mikubill/sd-webui-controlnet/assets/73768377/75edd0a7-b461-493e-9571-3f9b71200102"></p>

### Console logs

```Shell
*** Error running process: C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1064, in process
        self.controlnet_hack(p)
      File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1049, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 763, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "C:\Users\Michael.C\Documents\GitHub\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 649, in choose_input_image
        raise ValueError("No mask detected for ControlNet inpaint")
    ValueError: No mask detected for ControlNet inpaint
```

### Additional information

<p align="center"><img src="https://github.com/Mikubill/sd-webui-controlnet/assets/73768377/4c3544e1-377c-46ac-b1f7-bf1975923c4d"></p>

**Comment by Haoming02** [comment]
Just tried in `img2img` tab, but still getting the same error as well...

**Comment by Haoming02** [comment]
Reference Tutorial *(that used to work)*:
https://youtu.be/Z2d4tFan7cE?si=8xxinymXoETBdPhx
