### ISSUE TITLE
[Bug]: RuntimeError: The size of tensor a (3) must match the size of tensor b (0) at non-singleton dimension 2

### ISSUE THREAD

**Issue by alexgilseg** [Mikubill/sd-webui-controlnet#2484]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Trying to use outpainting and I keep getting this error: RuntimeError: The size of tensor a (3) must match the size of tensor b (0) at non-singleton dimension 2

### Steps to reproduce the problem

1. Fresh install of SD1111
2. Update everything.
3. Atempting to outpaint following the exact steps in every major tutorial on youtube..

### What should have happened?

Outpaint be done

### Commit where the problem happens

  RuntimeError: The size of tensor a (3) must match the size of tensor b (0) at non-singleton dimension 2

### Command Line Arguments

```Shell
2024-01-16 16:13:32,878 - ControlNet - INFO - unit_separate = False, style_align = False██████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 12.26it/s]
2024-01-16 16:13:32,879 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-01-16 16:13:32,879 - ControlNet - INFO - Loading preprocessor: inpaint_only+lama
2024-01-16 16:13:32,898 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\SDXL\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1062, in process
        self.controlnet_hack(p)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1047, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 878, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 496, in lama_inpaint
        prd_color = model_lama(img_res)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 51, in __call__
        color = color * (1 - mask)
    RuntimeError: The size of tensor a (3) must match the size of tensor b (0) at non-singleton dimension 2
```

### List of enabled extensions

controlnet only

### Console logs

```Shell
2024-01-16 16:13:32,878 - ControlNet - INFO - unit_separate = False, style_align = False██████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 12.26it/s]
2024-01-16 16:13:32,879 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-01-16 16:13:32,879 - ControlNet - INFO - Loading preprocessor: inpaint_only+lama
2024-01-16 16:13:32,898 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\SDXL\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1062, in process
        self.controlnet_hack(p)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1047, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 878, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 75, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 63, in cached_func
        return func(*args, **kwargs)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 496, in lama_inpaint
        prd_color = model_lama(img_res)
      File "D:\SDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 51, in __call__
        color = color * (1 - mask)
    RuntimeError: The size of tensor a (3) must match the size of tensor b (0) at non-singleton dimension 2
```

**Comment by huchenlei** [comment]
For now you can paint the edge of image where you want to outpaint to bypass this issue. I will work on a fix later today.
