### ISSUE TITLE
[Bug]: Warning: Failed to install handrefinerportable@git+https://github.com/huchenlei/HandRefinerPortable.git, some preprocessors may not work.

### ISSUE THREAD

**Issue by swumagic** [Mikubill/sd-webui-controlnet#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Installing sd-webui-controlnet requirement: handrefinerportable@git+https://github.com/huchenlei/HandRefinerPortable.git
Couldn't install sd-webui-controlnet requirement: handrefinerportable@git+https://github.com/huchenlei/HandRefinerPortable.git.
Command: "J:\StableDiffusion\sdwebui\py310\python.exe" -m pip install handrefinerportable@git+https://github.com/huchenlei/HandRefinerPortable.git --prefer-binary
Error code: 2
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl
Collecting handrefinerportable@ git+https://github.com/huchenlei/HandRefinerPortable.git
  Cloning https://github.com/huchenlei/HandRefinerPortable.git to c:\users\admin\appdata\local\temp\pip-install-5vu9tjyg\handrefinerportable_4aae1388755947fd8fce07cb91d99ad7
  Resolved https://github.com/huchenlei/HandRefinerPortable.git to commit d9c5506a1c13b396499dfdbaada9b7650e5d6d65
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/huchenlei/HandRefinerPortable.git 'C:\Users\admin\AppData\Local\Temp\pip-install-5vu9tjyg\handrefinerportable_4aae1388755947fd8fce07cb91d99ad7'
ERROR: Exception:
Traceback (most recent call last):
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 534, in collect_root_requirements
    reqs = list(
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 490, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\distributions\sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_internal\utils\misc.py", line 751, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "J:\StableDiffusion\sdwebui\py310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hatchling'

### Steps to reproduce the problem

Warning: Failed to install handrefinerportable@git+https://github.com/huchenlei/HandRefinerPortable.git, some preprocessors may not work.
ModuleNotFoundError: No module named 'hatchling'

### What should have happened?

1

### Commit where the problem happens

webui: 1.7.0
controlnet: Updated to the latest version today
Python：3.10.11
rtx4090
cuda:2.1.2+11.8

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Launching Web UI with arguments: --theme dark --xformers --api --autolaunch --enable-insecure-extension-access --allow-code
```

### List of enabled extensions

1

### Console logs

```Shell
1
```

**Comment by swumagic** [comment]
J:\StableDiffusion\sdwebui\py310\python.exe -m pip install hatchling
J:\StableDiffusion\sdwebui\py310\python.exe -m pip install handrefinerportable@git+https://github.com/huchenlei/HandRefinerPortable.git --prefer-binary
ok!
