### ISSUE TITLE
[Bug]: Absolute unit of a wall of text when i try and install

### ISSUE THREAD

**Issue by TeKett** [Mikubill/sd-webui-controlnet#2522]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Im getting an absolute unit of a wall of text when i try to install, several errors, and unnecessary info that packages are already installed (like i needed to know that)

### Steps to reproduce the problem

paste the link into a1111 and hit install

### What should have happened?

it installs with no problems

### Commit where the problem happens

i installed from url, so no clue

### Command Line Arguments

```Shell
--xformers --port 7861
```

### List of enabled extensions

sd-dynamic-prompts
stable-diffusion-webui-state

### Console logs

```Shell
venv "C:\Stable diffusion\venv\Scripts\Python.exe"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: 1.7.0
Commit hash: <none>
Launching Web UI with arguments: --xformers --port 7861
Style database not found: C:\Stable diffusion\styles.csv
Loading weights [7f96a1a9ca] from C:\Stable diffusion\models\Stable-diffusion\AnythingV5.safetensors
Creating model from config: C:\Stable diffusion\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 13.8s (prepare environment: 2.3s, import torch: 3.2s, import gradio: 1.1s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 0.7s, setup codeformer: 0.1s, list SD models: 2.9s, load scripts: 1.4s, create ui: 0.7s, gradio launch: 0.2s).
Loading VAE weights specified in settings: C:\Stable diffusion\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 3.1s (load weights from disk: 0.8s, create model: 0.4s, apply weights to model: 1.4s, load VAE: 0.2s, move model to device: 0.2s, calculate empty prompt: 0.1s).
*** Error running install.py for extension C:\Stable diffusion\extensions\sd-webui-controlnet.
*** Command: "C:\Stable diffusion\venv\Scripts\python.exe" "C:\Stable diffusion\extensions\sd-webui-controlnet\install.py"
*** Error code: 1
*** stdout: Installing sd-webui-controlnet requirement: mediapipe
*** Couldn't install sd-webui-controlnet requirement: mediapipe.
*** Command: "C:\Stable diffusion\venv\Scripts\python.exe" -m pip install mediapipe --prefer-binary
*** Error code: 1
*** stdout: Collecting mediapipe
***   Using cached mediapipe-0.10.9-cp310-cp310-win_amd64.whl (50.5 MB)
*** Collecting protobuf<4,>=3.11
***   Using cached protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
*** Requirement already satisfied: matplotlib in c:\stable diffusion\venv\lib\site-packages (from mediapipe) (3.8.2)
*** Requirement already satisfied: numpy in c:\stable diffusion\venv\lib\site-packages (from mediapipe) (1.23.5)
*** Requirement already satisfied: attrs>=19.1.0 in c:\stable diffusion\venv\lib\site-packages (from mediapipe) (23.2.0)
*** Collecting opencv-contrib-python
***   Using cached opencv_contrib_python-4.9.0.80-cp37-abi3-win_amd64.whl (45.3 MB)
*** Requirement already satisfied: absl-py in c:\stable diffusion\venv\lib\site-packages (from mediapipe) (2.0.0)
*** Collecting sounddevice>=0.4.4
***   Using cached sounddevice-0.4.6-py3-none-win_amd64.whl (199 kB)
*** Requirement already satisfied: flatbuffers>=2.0 in c:\stable diffusion\venv\lib\site-packages (from mediapipe) (23.5.26)
*** Collecting CFFI>=1.0
***   Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl (181 kB)
*** Requirement already satisfied: pyparsing>=2.3.1 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->mediapipe) (3.1.1)
*** Requirement already satisfied: python-dateutil>=2.7 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->mediapipe) (2.8.2)
*** Requirement already satisfied: packaging>=20.0 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->mediapipe) (23.2)
*** Requirement already satisfied: kiwisolver>=1.3.1 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->mediapipe) (1.4.5)
*** Requirement already satisfied: contourpy>=1.0.1 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->mediapipe) (1.2.0)
*** Requirement already satisfied: cycler>=0.10 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->mediapipe) (0.12.1)
*** Requirement already satisfied: pillow>=8 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->mediapipe) (9.5.0)
*** Requirement already satisfied: fonttools>=4.22.0 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->mediapipe) (4.47.0)
*** Requirement already satisfied: pycparser in c:\stable diffusion\venv\lib\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.21)
*** Requirement already satisfied: six>=1.5 in c:\stable diffusion\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)
*** Installing collected packages: protobuf, opencv-contrib-python, CFFI, sounddevice, mediapipe
***   Attempting uninstall: protobuf
***     Found existing installation: protobuf 4.25.2
***     Uninstalling protobuf-4.25.2:
***       Successfully uninstalled protobuf-4.25.2
***
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
***     WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Stable diffusion\\venv\\Lib\\site-packages\\google\\~upb\\_message.pyd'
*** Check the permissions.
***
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
***
*** [notice] A new release of pip available: 22.3.1 -> 23.3.2
*** [notice] To update, run: C:\Stable diffusion\venv\Scripts\python.exe -m pip install --upgrade pip
***
*** Warning: Failed to install mediapipe, some preprocessors may not work.
*** Installing sd-webui-controlnet requirement: insightface
***
*** stderr: Traceback (most recent call last):
***   File "C:\Stable diffusion\extensions\sd-webui-controlnet\install.py", line 107, in try_install_insight_face
***     launch.run_pip(
***   File "C:\Stable diffusion\modules\launch_utils.py", line 144, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "C:\Stable diffusion\modules\launch_utils.py", line 116, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install sd-webui-controlnet requirement: insightface.
*** Command: "C:\Stable diffusion\venv\Scripts\python.exe" -m pip install https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl --prefer-binary
*** Error code: 1
*** stdout: Collecting insightface==0.7.3
***   Using cached https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl (841 kB)
*** Requirement already satisfied: numpy in c:\stable diffusion\venv\lib\site-packages (from insightface==0.7.3) (1.23.5)
*** Collecting prettytable
***   Using cached prettytable-3.9.0-py3-none-any.whl (27 kB)
*** Collecting cython
***   Using cached Cython-3.0.8-cp310-cp310-win_amd64.whl (2.8 MB)
*** Requirement already satisfied: easydict in c:\stable diffusion\venv\lib\site-packages (from insightface==0.7.3) (1.11)
*** Requirement already satisfied: scipy in c:\stable diffusion\venv\lib\site-packages (from insightface==0.7.3) (1.11.4)
*** Requirement already satisfied: requests in c:\stable diffusion\venv\lib\site-packages (from insightface==0.7.3) (2.31.0)
*** Requirement already satisfied: scikit-image in c:\stable diffusion\venv\lib\site-packages (from insightface==0.7.3) (0.21.0)
*** Requirement already satisfied: Pillow in c:\stable diffusion\venv\lib\site-packages (from insightface==0.7.3) (9.5.0)
*** Collecting onnx
***   Using cached onnx-1.15.0-cp310-cp310-win_amd64.whl (14.3 MB)
*** Requirement already satisfied: tqdm in c:\stable diffusion\venv\lib\site-packages (from insightface==0.7.3) (4.66.1)
*** Collecting scikit-learn
***   Using cached scikit_learn-1.4.0-1-cp310-cp310-win_amd64.whl (10.6 MB)
*** Requirement already satisfied: matplotlib in c:\stable diffusion\venv\lib\site-packages (from insightface==0.7.3) (3.8.2)
*** Collecting albumentations
***   Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
*** Collecting qudida>=0.0.4
***   Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
*** Requirement already satisfied: PyYAML in c:\stable diffusion\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
*** Collecting opencv-python-headless>=4.1.1
***   Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
*** Requirement already satisfied: tifffile>=2022.8.12 in c:\stable diffusion\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2023.12.9)
*** Requirement already satisfied: lazy_loader>=0.2 in c:\stable diffusion\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (0.3)
*** Requirement already satisfied: imageio>=2.27 in c:\stable diffusion\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.33.1)
*** Requirement already satisfied: networkx>=2.8 in c:\stable diffusion\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.2.1)
*** Requirement already satisfied: packaging>=21 in c:\stable diffusion\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (23.2)
*** Requirement already satisfied: PyWavelets>=1.1.1 in c:\stable diffusion\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.5.0)
*** Requirement already satisfied: pyparsing>=2.3.1 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.1)
*** Requirement already satisfied: fonttools>=4.22.0 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.47.0)
*** Requirement already satisfied: contourpy>=1.0.1 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.0)
*** Requirement already satisfied: kiwisolver>=1.3.1 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
*** Requirement already satisfied: python-dateutil>=2.7 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.8.2)
*** Requirement already satisfied: cycler>=0.10 in c:\stable diffusion\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
*** Requirement already satisfied: protobuf>=3.20.2 in c:\stable diffusion\venv\lib\site-packages (from onnx->insightface==0.7.3) (3.20.3)
*** Requirement already satisfied: wcwidth in c:\stable diffusion\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
*** Requirement already satisfied: certifi>=2017.4.17 in c:\stable diffusion\venv\lib\site-packages (from requests->insightface==0.7.3) (2023.11.17)
*** Requirement already satisfied: charset-normalizer<4,>=2 in c:\stable diffusion\venv\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
*** Requirement already satisfied: idna<4,>=2.5 in c:\stable diffusion\venv\lib\site-packages (from requests->insightface==0.7.3) (3.6)
*** Requirement already satisfied: urllib3<3,>=1.21.1 in c:\stable diffusion\venv\lib\site-packages (from requests->insightface==0.7.3) (2.1.0)
*** Collecting joblib>=1.2.0
***   Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
*** Requirement already satisfied: threadpoolctl>=2.0.0 in c:\stable diffusion\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.2.0)
*** Requirement already satisfied: colorama in c:\stable diffusion\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
*** Requirement already satisfied: six>=1.5 in c:\stable diffusion\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
*** Requirement already satisfied: typing-extensions in c:\stable diffusion\venv\lib\site-packages (from qudida>=0.0.4->albumentations->insightface==0.7.3) (4.9.0)
*** Installing collected packages: prettytable, opencv-python-headless, onnx, joblib, cython, scikit-learn, qudida, albumentations, insightface
***
*** stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Stable diffusion\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
*** Check the permissions.
***
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -rotobuf (c:\stable diffusion\venv\lib\site-packages)
***
*** [notice] A new release of pip available: 22.3.1 -> 23.3.2
*** [notice] To update, run: C:\Stable diffusion\venv\Scripts\python.exe -m pip install --upgrade pip
***
***
*** During handling of the above exception, another exception occurred:
***
*** Traceback (most recent call last):
***   File "C:\Stable diffusion\extensions\sd-webui-controlnet\install.py", line 137, in <module>
***     try_install_insight_face()
***   File "C:\Stable diffusion\extensions\sd-webui-controlnet\install.py", line 113, in try_install_insight_face
***     "ControlNet init warning: Unable to install insightface automatically. "
*** TypeError: can only concatenate str (not "RuntimeError") to str
```

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/discussions/2442. If automatic installation fails, you need to manually install insightface.
