### ISSUE TITLE
[Bug]: Hand refiner run error

### ISSUE THREAD

**Issue by AhBumm** [Mikubill/sd-webui-controlnet#2541]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

can't use hand refiner preprocessor
report: RuntimeError: Unable to open file at E:\stable-diffusion-webui\venv\lib\site-packages/E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\hand_landmarker.task, errno=22

### Steps to reproduce the problem

1. Go to t2i
2. turn on adetailer enable hand_yolov8n.pt
3. ControlNet model sai_xl_depth_256lora and depth_hand_refiner
4. run

### What should have happened?

preprocessor not work

### Commit where the problem happens

webui: 1.7.0
controlnet: 1.1.434

### What browsers do you use to access the UI ?

Chrome latest version

### Command Line Arguments

```Shell
--listen --xformers --enable-insecure-extension-access
```

### List of enabled extensions

![screenshot-20240122-133337](https://github.com/Mikubill/sd-webui-controlnet/assets/103174943/22e27707-6e66-4c5d-bc02-b825d78e95a1)

### Console logs

```Shell
0: 640x640 1 hand, 3.0ms
Speed: 1.0ms preprocess, 3.0ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
2024-01-22 12:29:11,716 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-22 12:29:11,970 - ControlNet - WARNING - [depth_hand_refiner.processor_res] Invalid value(-1), using default value 512.
2024-01-22 12:29:11,971 - ControlNet - INFO - Loading model: sai_xl_depth_256lora [73ad23d1]
2024-01-22 12:29:12,078 - ControlNet - INFO - Loaded state_dict from [E:\stable-diffusion-webui\extensions\sd-webui-controlnet\models\sd_control_collection\sai_xl_depth_256lora.safetensors]
2024-01-22 12:29:12,078 - ControlNet - INFO - Using ControlNet lora (SDXL)
2024-01-22 12:29:12,108 - ControlNet - INFO - ControlNet model sai_xl_depth_256lora [73ad23d1] loaded.
2024-01-22 12:29:12,162 - ControlNet - INFO - Loading preprocessor: depth_hand_refiner
2024-01-22 12:29:12,163 - ControlNet - INFO - preprocessor resolution = 1024
set os.environ[OMP_NUM_THREADS] to 4
E:\stable-diffusion-webui\venv\lib\site-packages\scipy\sparse\_index.py:100: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
=> loading pretrained model E:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\hand_refiner\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth
*** Error running process: E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1084, in process
        self.controlnet_hack(p)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1069, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 891, in controlnet_main_entry
        detected_map, is_image = preprocessor(
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 76, in decorated_func
        return cached_func(*args, **kwargs)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 733, in run_model
        self.load_model()
      File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 719, in load_model
        self.model = MeshGraphormerDetector.from_pretrained(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\__init__.py", line 17, in from_pretrained
        pipeline = MeshGraphormerMediapipe(args)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\pipeline.py", line 198, in __init__
        self.detector = vision.HandLandmarker.create_from_options(options)
      File "E:\stable-diffusion-webui\venv\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 364, in create_from_options
        return cls(
      File "E:\stable-diffusion-webui\venv\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 70, in __init__
        self._runner = _TaskRunner.create(graph_config, packet_callback)
    RuntimeError: Unable to open file at E:\stable-diffusion-webui\venv\lib\site-packages/E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\hand_landmarker.task, errno=22

---
100%|██████████████████████████████████████████████████| 7/7 [00:01<00:00,  6.57it/s]
Total progress: 100%|████████████████████████████████| 31/31 [00:21<00:00,  1.44it/s]
100%|████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.19it/s]
```

### Additional information

os: windows11
python: 3.10

**Comment by huchenlei** [comment]
Does this issue also happen when you invoke the preprocessor with the trigger button?

**Comment by AhBumm** [comment]
> Does this issue also happen when you invoke the preprocessor with the trigger button?

yes. the same error logs

**Comment by AhBumm** [comment]
invoke the preprocessor with the trigger button
```
2024-01-22 17:27:03,447 - ControlNet - INFO - Preview Resolution = 0
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 999, in run_annotator
    result, is_image = preprocessor(
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
    return cached_func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 736, in run_model
    img, remove_pad = resize_image_with_pad(img, res)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 32, in resize_image_with_pad
    img = cv2.resize(img, (W_target, H_target), interpolation=interpolation)
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4065: error: (-215:Assertion failed) inv_scale_x > 0 in function 'cv::resize'
```

**Comment by huchenlei** [comment]
The cv2 error might be caused by preprocessor resolution. See https://github.com/Mikubill/sd-webui-controlnet/issues/1751.

**Comment by Tophness** [comment]
I'm getting the same "unable to open hand_landmarker.task error" with preprocessor trigger and full generation.
Changing preprocessor resolution doesn't help

**Comment by Tophness** [comment]
"Unable to open file at E:\stable-diffusion-webui\venv\lib\site-packages/E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\hand_landmarker.task" suggests it might be a failed os.path.join() that's combining an absolute path and a relative one

**Comment by huchenlei** [comment]
See https://github.com/huchenlei/HandRefinerPortable/blob/d9c5506a1c13b396499dfdbaada9b7650e5d6d65/hand_refiner/pipeline.py#L191-L198

I think I did my best to ensure that `model_asset_path` is valid. It's mediapipe's code doing the extra unnecessary `os.join`.

**Comment by Tophness** [comment]
Solved it by deleting the sd-webui-controlnet repo from extensions and cloning it back in, then deleting hand_refiner and handrefinerportable-2024.1.18.0.dist-info from venv\Lib\site-packages.
Not sure which one did it.
