### ISSUE TITLE
[Bug]: IP-Adapter Face ID and ID plus not working

### ISSUE THREAD

**Issue by vixenius** [Mikubill/sd-webui-controlnet#2546]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

2024-01-22 20:40:41,982 - ControlNet - INFO - unit_separate = False, style_align = False 20/20 [00:08<00:00,  2.72it/s]
2024-01-22 20:40:41,982 - ControlNet - INFO - Loading model: ip-adapter-full-face_sd15 [3459c5eb]
2024-01-22 20:40:41,996 - ControlNet - INFO - Loaded state_dict from [D:\AINOVO\stable-diffusion-webui\models\ControlNet\ip-adapter-full-face_sd15.pth]
2024-01-22 20:40:42,104 - ControlNet - INFO - ControlNet model ip-adapter-full-face_sd15 [3459c5eb] loaded.
2024-01-22 20:40:42,113 - ControlNet - INFO - Using preprocessor: ip-adapter_face_id_plus
2024-01-22 20:40:42,113 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AINOVO\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1104, in process
        self.controlnet_hack(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1089, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1063, in controlnet_main_entry
        param.control_model.hook(
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 538, in hook
        self.image_emb, self.uncond_image_emb = self.ipadapter.get_image_embeds(clip_vision_output)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 339, in get_image_embeds
        cond = self.image_proj_model(clip_vision_output['hidden_states'][-2].to(device='cpu', dtype=torch.float32))
    TypeError: tuple indices must be integers or slices, not str

### Steps to reproduce the problem

1. Go to .... Txt2img, enter prompt, enable controlnet Ip-adapter control type, load face id or face id plus preprocessor, upload face photo of a person
2. Press .... generate
3. ... error

### What should have happened?

The IP-Adapter face id only worked for the very first time i used it, just after the webui downloaded and loaded the model, and since then its just spewing the error i already pasted above. Restarting the  webui doesnt help.

### Commit where the problem happens

webui: 1.7.0
controlnet: 1.1.4.3.4

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--xformers --autolaunch --api
```

### List of enabled extensions

![ext](https://github.com/Mikubill/sd-webui-controlnet/assets/11150079/247575cc-d05a-4117-acf1-0422e275489e)

### Console logs

```Shell
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.34it/s]
2024-01-22 20:40:41,982 - ControlNet - INFO - unit_separate = False, style_align = False 20/20 [00:08<00:00,  2.72it/s]
2024-01-22 20:40:41,982 - ControlNet - INFO - Loading model: ip-adapter-full-face_sd15 [3459c5eb]
2024-01-22 20:40:41,996 - ControlNet - INFO - Loaded state_dict from [D:\AINOVO\stable-diffusion-webui\models\ControlNet\ip-adapter-full-face_sd15.pth]
2024-01-22 20:40:42,104 - ControlNet - INFO - ControlNet model ip-adapter-full-face_sd15 [3459c5eb] loaded.
2024-01-22 20:40:42,113 - ControlNet - INFO - Using preprocessor: ip-adapter_face_id_plus
2024-01-22 20:40:42,113 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AINOVO\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1104, in process
        self.controlnet_hack(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1089, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1063, in controlnet_main_entry
        param.control_model.hook(
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 538, in hook
        self.image_emb, self.uncond_image_emb = self.ipadapter.get_image_embeds(clip_vision_output)
      File "D:\AINOVO\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\AINOVO\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 339, in get_image_embeds
        cond = self.image_proj_model(clip_vision_output['hidden_states'][-2].to(device='cpu', dtype=torch.float32))
    TypeError: tuple indices must be integers or slices, not str
```

### Additional information

![err](https://github.com/Mikubill/sd-webui-controlnet/assets/11150079/0d316827-5cfe-4522-bb80-c23c1557e0bd)

**Comment by huchenlei** [comment]
You are using wrong preprocessor/model pair.
`ip-adapter_face_id_plus` should be paired with `ip-adapter-faceid-plus_sd15 [d86a490f]` or `ip-adapter-faceid-plusv2_sd15 [6e14fc1a]`.

**Comment by huchenlei** [comment]
I will add a filter to help narrow down selection later.

**Comment by vixenius** [comment]
> ip-adapter-faceid-plusv2_sd15

I don't have those two on the list, do I have to download them manually? Could you provide links please?

**Comment by huchenlei** [comment]
See release note: https://github.com/Mikubill/sd-webui-controlnet/discussions/2442.

**Comment by vixenius** [comment]
> See release note: #2442.

Godbless!!

**Comment by chinalinshen** [comment]
2024-09-30 15:40:51,371 - ControlNet - INFO - unit_separate = False, style_align = False
2024-09-30 15:40:51,708 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-09-30 15:40:51,866 - ControlNet - INFO - Loaded state_dict from [D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\models\ip-adapter-faceid-plusv2_sd15.bin]
2024-09-30 15:40:52,211 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sd15 [6e14fc1a](ControlModelType.IPAdapter) loaded.
2024-09-30 15:40:52,237 - ControlNet - INFO - Using preprocessor: ip-adapter_face_id_plus
2024-09-30 15:40:52,237 - ControlNet - INFO - preprocessor resolution = 512
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 [1, 3, 192, 192] 0.0 1.0
*** Error running process: D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.9\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1228, in process
        self.controlnet_hack(p)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1213, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 941, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in get_control
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 242, in preprocess_input_image
        result = preprocessor.cached_call(
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 198, in cached_call
        result = self._cached_call(input_image, *args, **kwargs)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\utils.py", line 82, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\utils.py", line 66, in cached_func
        return func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 211, in _cached_call
        return self(*args, **kwargs)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 105, in __call__
        result, is_image = self.call_function(
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 768, in face_id_plus
        face_embed, _ = g_insight_face_model.run_model(img)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 696, in run_model
        self.load_model()
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 688, in load_model
        self.model = FaceAnalysis(
      File "D:\sd-webui-aki-v4.9\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
        assert 'detection' in self.models
    AssertionError
![42b96bc1b412d5a6d8cfd4de1a8ac1b](https://github.com/user-attachments/assets/02ec3c87-40f0-4007-a569-fae4fdd8d133)

**Comment by chinalinshen** [comment]
2024-09-30 15:40:51,371 - ControlNet - INFO - unit_separate = False, style_align = False
2024-09-30 15:40:51,708 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-09-30 15:40:51,866 - ControlNet - INFO - Loaded state_dict from [D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\models\ip-adapter-faceid-plusv2_sd15.bin]
2024-09-30 15:40:52,211 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sd15 [6e14fc1a](ControlModelType.IPAdapter) loaded.
2024-09-30 15:40:52,237 - ControlNet - INFO - Using preprocessor: ip-adapter_face_id_plus
2024-09-30 15:40:52,237 - ControlNet - INFO - preprocessor resolution = 512
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 [1, 3, 192, 192] 0.0 1.0
*** Error running process: D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.9\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1228, in process
        self.controlnet_hack(p)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1213, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 941, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in get_control
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet.py", line 242, in preprocess_input_image
        result = preprocessor.cached_call(
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 198, in cached_call
        result = self._cached_call(input_image, *args, **kwargs)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\utils.py", line 82, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\utils.py", line 66, in cached_func
        return func(*args, **kwargs)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 211, in _cached_call
        return self(*args, **kwargs)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 105, in __call__
        result, is_image = self.call_function(
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 768, in face_id_plus
        face_embed, _ = g_insight_face_model.run_model(img)
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 696, in run_model
        self.load_model()
      File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 688, in load_model
        self.model = FaceAnalysis(
      File "D:\sd-webui-aki-v4.9\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
        assert 'detection' in self.models
    AssertionError
![42b96bc1b412d5a6d8cfd4de1a8ac1b](https://github.com/user-attachments/assets/02ec3c87-40f0-4007-a569-fae4fdd8d133)
Even if modle is not used, it will still be Error
![cf6350529c34d99651cba4d5673c2b0](https://github.com/user-attachments/assets/f560a0d8-a7ab-4961-8116-9c591efc499e)
