### ISSUE TITLE
[Bug]: Got error when use ip-adapter：AttributeError: __enter__

### ISSUE THREAD

**Issue by shinywangshan** [Mikubill/sd-webui-controlnet#2553]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Got error when use ip-adapter：AttributeError: __enter__

### Steps to reproduce the problem

1. Use ip-adapter
2. Generate

### What should have happened?

Generate new image with ip-adapter

### Commit where the problem happens

webui: cf2772fab0af5573da775e7437e6acdca424f26e
controlnet: 7fb40bf803d05cde9ca9db8b1c6b8ee3c5efb352

### What browsers do you use to access the UI ?

Chrome

### Command Line Arguments

```Shell
(sd-py310) PS D:\Project_Diff\stable-diffusion-webui>  d:; cd 'd:\Project_Diff\stable-diffusion-webui'; & 'C:\Users\33\anaconda3\envs\sd-py310\python.exe' 'c:\Users\33\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '57766' '--' 'd:\Project_Diff\stable-diffusion-webui\launch.py'
```

### List of enabled extensions

![image - 2024-01-23T120148 465](https://github.com/Mikubill/sd-webui-controlnet/assets/128561762/20e27eae-58d9-4a0e-a052-d941d7d73d09)

### Console logs

```Shell
2024-01-23 11:41:53,079 - ControlNet - INFO - unit_separate = False, style_align = False
2024-01-23 11:41:53,339 - ControlNet - INFO - Loading model: ip-adapter_sd15_plus [32cd8f7f]
2024-01-23 11:41:53,427 - ControlNet - INFO - Loaded state_dict from [D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\models\ip-adapter_sd15_plus.pth]
2024-01-23 11:41:53,800 - ControlNet - INFO - ControlNet model ip-adapter_sd15_plus [32cd8f7f] loaded.
2024-01-23 11:41:53,808 - ControlNet - INFO - Using preprocessor: ip-adapter_clip_sd15
2024-01-23 11:41:53,809 - ControlNet - INFO - preprocessor resolution = 512
*** Error running process: D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\Project_Diff\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1113, in process
        self.controlnet_hack(p)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1098, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 919, in controlnet_main_entry
        detected_map, is_image = self.preprocessor[unit.module](
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 389, in clip
        clip_encoder[config] = ClipVisionDetector(config, low_vram)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\clipvision\__init__.py", line 105, in __init__
        with self.device:
    AttributeError: __enter__
```

**Comment by theSha1do1w** [comment]
It seems that the error is caused by device=None. May I ask if you are using GPU or CPU?

**Comment by shinywangshan** [comment]
> It seems that the error is caused by device=None. May I ask if you are using GPU or CPU?

wanna use gpu, rebase to the non-cpu code, still got the error

**Comment by shinywangshan** [comment]
> It seems that the error is caused by device=None. May I ask if you are using GPU or CPU?

I've seen your commit, actually remove with doesn't help, which I've tried at once. how could I guarantee device not None ?

**Comment by theSha1do1w** [comment]
> > It seems that the error is caused by device=None. May I ask if you are using GPU or CPU?
> 
> I've seen your commit, actually remove with doesn't help, which I've tried at once. how could I guarantee device not None ?

Can you paste the error log?

**Comment by shinywangshan** [comment]
> > > It seems that the error is caused by device=None. May I ask if you are using GPU or CPU?
> > 
> > 
> > I've seen your commit, actually remove with doesn't help, which I've tried at once. how could I guarantee device not None ?
> 
> Can you paste the error log?


I'll try upgrad torch version, since my coworker told me device has no __enter__ with torch1.13, which I'm using.

As follow：


*** Error completing request
*** Arguments: ('task(dujvc7zsxx6zihq)', 'masterpiece, best quality, white background,\n1girl, upper body, strapless dress, ', 'NFSW,lowres, bad anatomy, bad legs,bad hands, more legs,text,error, missing fingers,extra digt ,fewer digits,cropped, worst quality ,low quality,normal quality, jpeg,artifacts,signature,watermark, username, blurry, bad feet,artist name', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 768, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001FB639241F0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 
'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 
'ad_cfg_scale': 7, 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 
'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True, False, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.animatediff_ui.AnimateDiffProcess object at 0x000001FBAC0A7010>, UiControlNetUnit(enabled=True, module='ip-adapter_clip_sd15', model='ip-adapter_sd15_plus [32cd8f7f]', weight=1, image={'image': array([[[255, 255, 255],
***         [254, 255, 255],
***         [254, 255, 255],
***         ...,
***         [255, 255, 255],
***         [254, 255, 255],
***         [254, 254, 255]],
***
***        [[255, 255, 255],
***         [255, 255, 255],
***         [255, 255, 255],
***         ...,
***         [255, 255, 255],
***         [255, 255, 255],
***         [254, 255, 255]],
***
***        [[255, 255, 255],
***         [255, 255, 255],
***         [255, 255, 255],
***         ...,
***         [255, 255, 255],
***         [255, 255, 255],
***         [253, 255, 255]],
***
***        ...,
***
***        [[152, 159, 176],
***         [153, 159, 177],
***         [153, 159, 176],
***         ...,
***         [130, 136, 152],
***         [130, 136, 152],
***         [130, 135, 152]],
***
***        [[152, 160, 177],
***         [152, 160, 178],
***         [153, 159, 177],
***         ...,
***         [130, 135, 152],
***         [130, 136, 151],
***         [129, 134, 151]],
***
***        [[152, 158, 174],
***         [153, 160, 176],
***         [152, 160, 177],
***         ...,
***         [129, 136, 152],
***         [129, 135, 151],
***         [131, 132, 147]]], dtype=uint8), 'mask': array([[[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        ...,
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]],
***
***        [[0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0],
***         ...,
***         [0, 0, 0],
***         [0, 0, 0],
***         [0, 0, 0]]], dtype=uint8)}, resize_mode='Crop and Resize', low_vram=False, processor_res=512, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, False, False, False, '#000000', False, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'all', 'all', 'all', 'all', '', 5, 24, 12.5, 1000, '', 'DDIM', 0, 64, 64, '', 64, 7.5, 0.42, 'DDIM', 64, 64, 1, 0, 92, True, True, True, False, False, False, 'midas_v21_small', None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "D:\Project_Diff\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Project_Diff\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "D:\Project_Diff\stable-diffusion-webui\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\modules\processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 435, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\modules\processing.py", line 1142, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\Project_Diff\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\Project_Diff\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "D:\Project_Diff\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
        return func(*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\Project_Diff\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 845, in forward_webui
        raise e
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 842, in forward_webui
        return forward(*args, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 749, in forward
        h = module(h, emb, context)
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
        x = layer(x, context)
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
        x = block(x, context=context[i])
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
        return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "D:\Project_Diff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
        x = self.attn2(self.norm2(x), context=context) + x
      File "C:\Users\33\anaconda3\envs\sd-py310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
        return forward_call(*input, **kwargs)
      File "D:\Project_Diff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 400, in attn_forward_hacked
        out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0.0, is_causal=False)
    AttributeError: module 'torch.nn.functional' has no attribute 'scaled_dot_product_attention'
