### ISSUE TITLE
    ModuleNotFoundError: No module named 'depth_anything'

### ISSUE THREAD

**Issue by protector131090** [Mikubill/sd-webui-controlnet#2562]
*** Error running process: C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1117, in process
        self.controlnet_hack(p)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1102, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 923, in controlnet_main_entry
        detected_map, is_image = self.preprocessor[unit.module](
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
        return cached_func(*args, **kwargs)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\processor.py", line 194, in depth_anything
        from annotator.depth_anything import DepthAnythingDetector
      File "C:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\depth_anything.py", line 8, in <module>
        from depth_anything.dpt import DPT_DINOv2
    ModuleNotFoundError: No module named 'depth_anything'

**Comment by huchenlei** [comment]
We have code in install.py to auto-install depth_anything library. If it fails, you need to manually install the package.
```python
try_install_from_wheel(
    "depth_anything",
    wheel_url=os.environ.get(
        "DEPTH_ANYTHING_WHEEL",
        "https://github.com/huchenlei/Depth-Anything/releases/download/v1.0.0/depth_anything-2024.1.22.0-py2.py3-none-any.whl",
    ),
)
```

**Comment by Xiahussheng** [comment]
I have the same problem, what do you mean by "you need to manually install the package" in your reply and how should I do it?

**Comment by huchenlei** [comment]
Just run "pip install" followed by that wheel url in your a1111 venv.

**Comment by ritikvirus** [comment]
I was facing the same problem. To fix it, I uninstalled and reinstalled the ControlNet extension, then applied the changes and restarted. After that, it started working properly. If anyone else is experiencing this issue, you might want to try these steps.
