### ISSUE TITLE
[Bug]: multi-input for face-id-portrait via api throws assertion error with 1.1.436 and 1.1.437

### ISSUE THREAD

**Issue by dermesut** [Mikubill/sd-webui-controlnet#2572]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

not too long ago, with 1.1.435, i was able to use multi-input for face-id-portrait via api. simple piece of code collects images in a folder, puts them in a list and then: multi_imges = [{"image": img_pic} for img_pic in list_of_images]
the post to the server contained it {..."image": multi_imges, ...}, and it worked.
a face was generated, that looked like a mix of the given images.
since 1.1.436, i get this message:

2024-01-24 01:46:50,259 - ControlNet - INFO - Loading model: ip-adapter-faceid-portrait_sd15 [b2609049]
2024-01-24 01:46:50,281 - ControlNet - INFO - Loaded state_dict from [E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\models\ip-adapter-faceid-portrait_sd15.bin]
2024-01-24 01:46:50,428 - ControlNet - INFO - ControlNet model ip-adapter-faceid-portrait_sd15 [b2609049] loaded.
*** Error running before_process_batch: E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\ai\_gh_repos\sd.webui\webui\modules\scripts.py", line 726, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1127, in before_process_batch
        self.controlnet_hack(p)
      File "E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1102, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 898, in controlnet_main_entry
        assert unit.accepts_multiple_inputs()
    AssertionError

---

this is only with api.
using the webui itself shows no such message and works as expected.

### Steps to reproduce the problem

see above

### What should have happened?

using multi-input should have worked as in 1.1.435

### Commit where the problem happens

webui: [cf2772f]
controlnet: [3aed89e]

### Command Line Arguments

```Shell
--allow-code --api --port 7861 --device-id 1 --medvram --medvram-sdxl --xformers --no-half-vae
```

### List of enabled extensions

depth-image-io-for-SDWebui
sd-webui-animatediff
sd-webui-api-payload-display
sd-webui-controlnet
sd-webui-lcm
sd-webui-reactor

### Console logs

```Shell
2024-01-24 01:46:50,259 - ControlNet - INFO - Loading model: ip-adapter-faceid-portrait_sd15 [b2609049]
2024-01-24 01:46:50,281 - ControlNet - INFO - Loaded state_dict from [E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\models\ip-adapter-faceid-portrait_sd15.bin]
2024-01-24 01:46:50,428 - ControlNet - INFO - ControlNet model ip-adapter-faceid-portrait_sd15 [b2609049] loaded.
*** Error running before_process_batch: E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "E:\ai\_gh_repos\sd.webui\webui\modules\scripts.py", line 726, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1127, in before_process_batch
        self.controlnet_hack(p)
      File "E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1102, in controlnet_hack
        self.controlnet_main_entry(p)
      File "E:\ai\_gh_repos\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 898, in controlnet_main_entry
        assert unit.accepts_multiple_inputs()
    AssertionError

---
```

### Additional information

i'm using the web api way to achieve the above mentioned

**Comment by huchenlei** [comment]
I temporarily reverted the real multi-image API in https://github.com/Mikubill/sd-webui-controlnet/pull/2569 as the IPAdapter logic seem to be broken for real multi-image. (At least for that version of impl)

Now you need to call the API in a more awkward way like:
```
 def test_face_id_multi_inputs(self):
        for module, model, lora in self.settings:
            for i, negative_prompt in enumerate((general_negative_prompt, "", "bad")):
                name = "multi_inputs" + str((module, model, lora, i))
                with self.subTest(name=name):
                    self.assertTrue(
                        APITestTemplate(
                            name=name,
                            gen_type="txt2img",
                            payload_overrides={
                                "prompt": base_prompt,
                                "negative_prompt": negative_prompt,
                                "steps": 20,
                                "width": 512,
                                "height": 512,
                            },
                            unit_overrides=[openpose_unit]
                            + [
                                {
                                    "image": img,
                                    "module": module,
                                    "model": model,
                                    "weight": 1 / len(portrait_imgs),
                                }
                                for img in portrait_imgs
                            ],
                        ).exec()
                    )
```

**Comment by dermesut** [comment]
thank you for your response and help.
not sure, i am able to adapt to that. i'll probably wait until it's possible to use it in the way it worked in 1.1.435 - if that is going to happen, that is.
