### ISSUE TITLE
Error reported when using the local redraw model corresponding to sdxl。model: sd_xl_base_1.0_inpainting_0.1

### ISSUE THREAD

**Issue by hjj-lmx** [Mikubill/sd-webui-controlnet#2573]
Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1092, in process
        self.controlnet_hack(p)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1077, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 769, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 370, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 399, in build_control_model
        network = build_model_by_guess(state_dict, unet, model_path)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_model_guess.py", line 253, in build_model_by_guess
        raise '[ControlNet Error] Cannot recognize the ControlModel!'
    TypeError: exceptions must derive from BaseException

**Comment by sdbds** [comment]
sd_xl_base_1.0_inpainting_0.1 is not a controlnet model but a base model

**Comment by hjj-lmx** [comment]
> sd_xl_base_1.0_inpainting_0.1 不是 controlnet 模型，而是基础模型
It's not the basic model, it's an adaptive model for ControlNet. How can SDXL use the local drawing function of ControlNet? Is there a corresponding model?

**Comment by sdbds** [comment]
> sd_xl_base_1.0_inpainting

SDXL dont have controlnet inpaint model, it just a base model using like base model

**Comment by hjj-lmx** [comment]
> sd_xl_base_1.0_inpainting_0.1 不是 controlnet 模型，而是基础模型

May I ask how to use Controlnet to transform the background of product images and achieve good image fusion
