### ISSUE TITLE
Control.py not working at all. Has no attribute 'get_device_for'

### ISSUE THREAD

**Issue by Miraabilis** [Mikubill/sd-webui-controlnet#259]
Every time i run any generation of image i got this error specificaly down below
Also the script doesn't seem the get read correclty at all from the start for some reason i double check to be sure how i installed it, get rid of the extension and also reinstalled it to see but same problem, unable to got the extention without errors.
I have absolutely no idea how to read the command error correclty so if you can help me with it and if i did a rookie mistake i would love a bit of help

Error running process: C:\Users\kidav\Desktop\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\kidav\Desktop\AI\stable-diffusion-webui\modules\scripts.py", line 327, in process
    script.process(p, *script_args)
  File "C:\Users\kidav\Desktop\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 477, in process
    network = network_module(
  File "C:\Users\kidav\Desktop\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 115, in __init__
    self.control_model.to(devices.get_device_for("controlnet"))
AttributeError: module 'modules.devices' has no attribute 'get_device_for'

**Comment by Miraabilis** [comment]
I also get this error when i apply the changes in the ui, without the extension my Stable Diffusion is working perfectly, every time control.net is there and i reload i got this error

Reloading extensions
Reloading custom scripts
Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\kidav\Desktop\AI\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\kidav\Desktop\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\kidav\Desktop\AI\stable-diffusion-webui\extensions\stable-diffusion-webui\scripts\main.py", line 11, in <module>
    script_path = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
NameError: name '__file__' is not defined

**Comment by Mikubill** [comment]
Looks like you are using an old version of WebUI. Try updating your WebUI may help.

**Comment by Miraabilis** [comment]
> Looks like you are using an old version of WebUI. Try updating your WebUI may help.
Thank you, i'm trying that

**Comment by Miraabilis** [comment]
Works perfectly after all updates thanks !
