### ISSUE TITLE
'InstantIdControlNetInput' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by santaonholidays** [Mikubill/sd-webui-controlnet#2592]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I tried face id it broke c:

### Steps to reproduce the problem

.

### What should have happened?

Work :D

### Commit where the problem happens

At ndim

### Command Line Arguments

```Shell
"--xformers"
```

### List of enabled extensions

![Screenshot_24](https://github.com/Mikubill/sd-webui-controlnet/assets/33313717/20d43a97-e486-4553-b29b-145889492c67)

### Console logs

```Shell
dtype=uint8)}, resize_mode='Crop and Resize', low_vram=False, processor_res=512, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), UiControlNetUnit(enabled=False, module='none', model='None', weight=1, image=None, resize_mode='Crop and Resize', low_vram=False, processor_res=-1, threshold_a=-1, threshold_b=-1, guidance_start=0, guidance_end=1, pixel_perfect=False, control_mode='Balanced', inpaint_crop_input_image=False, hr_option='Both', save_detected_map=True, advanced_weighting=None), True, False, <PIL.Image.Image image mode=RGB size=1024x1280 at 0x204BF5BC100>, False, '0', '0', 'inswapper_128.onnx', 'None', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.8, True, False, 'CUDA', False, 0, 'None', '', None, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 41, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\processing.py", line 868, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\hook.py", line 436, in process_sample
        return process.sample_before_CN_hack(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\processing.py", line 1142, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\sd_samplers_cfg_denoiser.py", line 188, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\sd_models_xl.py", line 37, in apply_model
        return self.model(x, t, cond)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\repositories\generative-models\sgm\modules\diffusionmodules\wrappers.py", line 28, in forward
        return self.diffusion_model(
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
        result = forward_call(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\hook.py", line 862, in forward_webui
        raise e
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\hook.py", line 859, in forward_webui
        return forward(*args, **kwargs)
      File "H:\SD\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\hook.py", line 484, in forward
        if isinstance(param.hr_hint_cond, torch.Tensor) and x.ndim == 4 and param.hint_cond.ndim == 4 and param.hr_hint_cond.ndim == 4:
    AttributeError: 'InstantIdControlNetInput' object has no attribute 'ndim'
```

### Additional information

No addifitonal info

**Comment by huchenlei** [comment]
Currently instant id does not support high res fix.
