### ISSUE TITLE
[Bug]: TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

### ISSUE THREAD

**Issue by guahunyo** [Mikubill/sd-webui-controlnet#2606]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

when i use instantid

### Steps to reproduce the problem

controlnet use  instantid
TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'

### What should have happened?

...

### Commit where the problem happens

webui: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/18573180/a8d606b5-c6fe-477d-91f9-eb77a651bc08)

### Console logs

```Shell
Error running process: D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\controlnet.py", line 969, in controlnet_main_entry
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in input_images]))
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\controlnet.py", line 969, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in input_images]))
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\controlnet.py", line 936, in preprocess_input_image
        detected_map, is_image = self.preprocessor[unit.module](
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
        return cached_func(*args, **kwargs)
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\processor.py", line 801, in run_model_instant_id
        self.load_model()
      File "D:\BaiduNetdiskDownload\01-01HH\novelai-webui-aki-v3A\extensions\sd-webui-controlnet\scripts\processor.py", line 741, in load_model
        self.model = FaceAnalysis(
    TypeError: FaceAnalysis.__init__() got an unexpected keyword argument 'providers'
```

**Comment by guahunyo** [comment]
webui   4afaaf8a020c1df457bcf7250cb1c7f609699fa7

**Comment by huchenlei** [comment]
This is related to insightface library version. Be sure you install insightface version provided in the install script.

**Comment by guahunyo** [comment]
> This is related to insightface library version. Be sure you install insightface version provided in the install script.

Can you tell me which version I need? I don't see which version I need. Thank you.

**Comment by huchenlei** [comment]
You need insightface `0.7.3`.

**Comment by guahunyo** [comment]
> You need insightface `0.7.3`.

OK thank you
