### ISSUE TITLE
[Bug]: depth zoe cannot run normally under torch2.1 and torch2.2

### ISSUE THREAD

**Issue by RunawayOrange** [Mikubill/sd-webui-controlnet#2608]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

其他预处理器能正常运行，但唯独depth zoe在torch2.1和torch2.2环境下均无法正常运行，但depth zoe可以在torch2.0环境下正常运行

### Steps to reproduce the problem

在torch2.0下可正常运行
torch2.1和torch2.2环境下均无法正常运行

### What should have happened?

应该像其他预处理器一样正常运行

### Commit where the problem happens

webui: [v1.7.0-437-gce168ab5](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ce168ab5dbc8b54b7245f352a2eaa55a37019b91)
controlnet: 1.1.440

### Command Line Arguments

```Shell
--medvram-sdxl --theme dark --xformers --api --autolaunch
```

### List of enabled extensions

![AAA](https://github.com/Mikubill/sd-webui-controlnet/assets/127380484/8e74e2c2-68ef-424e-8471-66dfb706c7e9)

### Console logs

```Shell
img_size [384, 512]
Params passed to Resize transform:
        width:  512
        height:  384
        resize_target:  True
        keep_aspect_ratio:  True
        ensure_multiple_of:  32
        resize_method:  minimal
Traceback (most recent call last):
  File "F:\Stable-Diffusion\venv\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\venv\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\venv\Lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\Stable-Diffusion\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\venv\Lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 1013, in run_annotator
    result, is_image = preprocessor(
                       ^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\processor.py", line 558, in zoe_depth
    result = model_zoe_depth(img)
             ^^^^^^^^^^^^^^^^^^^^
  File "F:\Stable-Diffusion\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 38, in __call__
    self.load_model()
  File "F:\Stable-Diffusion\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 28, in load_model
    model.load_state_dict(torch.load(modelpath, map_location=model.device)['model'])
  File "F:\Stable-Diffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ZoeDepth:
        Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", "core.core.pretrained.model.blocks.1.attn.relative_position_index", "core.core.pretrained.model.blocks.2.attn.relative_position_index", "core.core.pretrained.model.blocks.3.attn.relative_position_index", "core.core.pretrained.model.blocks.4.attn.relative_position_index", "core.core.pretrained.model.blocks.5.attn.relative_position_index", "core.core.pretrained.model.blocks.6.attn.relative_position_index", "core.core.pretrained.model.blocks.7.attn.relative_position_index", "core.core.pretrained.model.blocks.8.attn.relative_position_index", "core.core.pretrained.model.blocks.9.attn.relative_position_index", "core.core.pretrained.model.blocks.10.attn.relative_position_index", "core.core.pretrained.model.blocks.11.attn.relative_position_index", "core.core.pretrained.model.blocks.12.attn.relative_position_index", "core.core.pretrained.model.blocks.13.attn.relative_position_index", "core.core.pretrained.model.blocks.14.attn.relative_position_index", "core.core.pretrained.model.blocks.15.attn.relative_position_index", "core.core.pretrained.model.blocks.16.attn.relative_position_index", "core.core.pretrained.model.blocks.17.attn.relative_position_index", "core.core.pretrained.model.blocks.18.attn.relative_position_index", "core.core.pretrained.model.blocks.19.attn.relative_position_index", "core.core.pretrained.model.blocks.20.attn.relative_position_index", "core.core.pretrained.model.blocks.21.attn.relative_position_index", "core.core.pretrained.model.blocks.22.attn.relative_position_index", "core.core.pretrained.model.blocks.23.attn.relative_position_index".
```

**Comment by waterdrop1024** [comment]
Same

**Comment by sparkleMing** [comment]
run
pip install timm==0.6.7 
and restart webui solved my problem

**Comment by hben35096** [comment]
pip install timm==0.9.5
This version also solves the problem

**Comment by hben35096** [comment]
Detection seems to be a bit of a problem, I've installed timm==0.9.5 but still prompts:

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/7d7921bb-2299-4219-a792-4729053ee6cc)

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/d5eab896-3818-4566-a714-bbb0d4f1d6cd)


![image](https://github.com/Mikubill/sd-webui-controlnet/assets/139383150/651c5265-ed4b-4646-ad43-4b0c031cb338)

**Comment by hben35096** [comment]
@huchenlei 
It worked, thanks ;-)
