### ISSUE TITLE
Crashes from just a update

### ISSUE THREAD

**Issue by GR-noob** [Mikubill/sd-webui-controlnet#2611]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hello everyone. I updated my controlnet and now it shows this message please someone help.

### Steps to reproduce the problem

from just the update

### What should have happened?

restart

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
--listen --no-half
```

### List of enabled extensions

![ECON-6-5 - Copy - Copy](https://github.com/Mikubill/sd-webui-controlnet/assets/27872693/7ae02c5e-eb28-4bec-b158-6b6080ecd55e)

### Console logs

```Shell
venv "D:\Program Files\stable difusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 11d432d92d63660c516540dcb48faac87669b4f0
Installing requirements for Web UI




Launching Web UI with arguments: --listen --no-half
No module 'xformers'. Proceeding without it.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
ControlNet preprocessor location: D:\Program Files\stable difusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
Warning: ControlNet failed to load SGM - will use LDM instead.
2024-02-01 02:30:39,665 - ControlNet - INFO - ControlNet v1.1.440
Error loading script: controlnet.py
Traceback (most recent call last):
  File "D:\Program Files\stable difusion\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Program Files\stable difusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program Files\stable difusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1299, in <module>
    script_callbacks.on_before_reload(ControlNetUiGroup.reset)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_before_reload'

2024-02-01 02:30:39,803 - ControlNet - INFO - ControlNet v1.1.440
Warning: ControlNet failed to load SGM - will use LDM instead.
Loading weights [1d1e459f9f] from D:\Program Files\stable difusion\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5.safetensors
Creating model from config: D:\Program Files\stable difusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\Program Files\stable difusion\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(1): easynegative
Model loaded in 5.4s (load weights from disk: 0.5s, create model: 0.6s, apply weights to model: 1.2s, load VAE: 0.2s, move model to device: 1.7s, load textual inversion embeddings: 1.1s).
calling D:\Program Files\stable difusion\stable-diffusion-webui\extensions\stable-diffusion-webui-pixelization\scripts\postprocessing_pixelization.py/ui: AttributeError
Traceback (most recent call last):
  File "D:\Program Files\stable difusion\stable-diffusion-webui\modules\scripts_postprocessing.py", line 53, in wrap_call
    res = func(*args, **kwargs)
  File "D:\Program Files\stable difusion\stable-diffusion-webui\extensions\stable-diffusion-webui-pixelization\scripts\postprocessing_pixelization.py", line 176, in ui
    with ui_components.InputAccordion(False, label="Pixelize") as enable:
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

Traceback (most recent call last):
  File "D:\Program Files\stable difusion\stable-diffusion-webui\launch.py", line 352, in <module>
    start()
  File "D:\Program Files\stable difusion\stable-diffusion-webui\launch.py", line 347, in start
    webui.webui()
  File "D:\Program Files\stable difusion\stable-diffusion-webui\webui.py", line 243, in webui
    shared.demo = modules.ui.create_ui()
  File "D:\Program Files\stable difusion\stable-diffusion-webui\modules\ui.py", line 978, in create_ui
    ui_postprocessing.create_ui()
  File "D:\Program Files\stable difusion\stable-diffusion-webui\modules\ui_postprocessing.py", line 25, in create_ui
    script_inputs = scripts.scripts_postproc.setup_ui()
  File "D:\Program Files\stable difusion\stable-diffusion-webui\modules\scripts_postprocessing.py", line 113, in setup_ui
    self.create_script_ui(script, inputs)
  File "D:\Program Files\stable difusion\stable-diffusion-webui\modules\scripts_postprocessing.py", line 84, in create_script_ui
    for control in script.controls.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by GR-noob** [comment]
what 
AttributeError: module 'modules.script_callbacks' has no attribute 'on_before_reload'
means ??
