### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shynesss** [Mikubill/sd-webui-controlnet#2615]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

*** Error running process: /home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/home/ubuntu/apps/stable-diffusion-webui/modules/scripts.py", line 718, in process
        script.process(p, *script_args)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 902, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 620, in choose_input_image
        resize_mode = external_code.resize_mode_from_value(unit.resize_mode)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 63, in resize_mode_from_value
        return ResizeMode(resize_mode_aliases.get(value, value))
      File "/usr/lib/python3.10/enum.py", line 385, in __call__
        return cls.__new__(cls, value)
      File "/usr/lib/python3.10/enum.py", line 710, in __new__
        raise ve_exc
    ValueError: 'ResizeMode.INNER_FIT' is not a valid ResizeMode

---

### Steps to reproduce the problem

1. use img2img
2. use adetailer 
3. use multiple controlent

### What should have happened?

*** Error running process: /home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/home/ubuntu/apps/stable-diffusion-webui/modules/scripts.py", line 718, in process
        script.process(p, *script_args)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 902, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 620, in choose_input_image
        resize_mode = external_code.resize_mode_from_value(unit.resize_mode)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 63, in resize_mode_from_value
        return ResizeMode(resize_mode_aliases.get(value, value))
      File "/usr/lib/python3.10/enum.py", line 385, in __call__
        return cls.__new__(cls, value)
      File "/usr/lib/python3.10/enum.py", line 710, in __new__
        raise ve_exc
    ValueError: 'ResizeMode.INNER_FIT' is not a valid ResizeMode

---

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
no
```

### List of enabled extensions

sd-controlnet, sd-adetailer

### Console logs

```Shell
*** Error running process: /home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/home/ubuntu/apps/stable-diffusion-webui/modules/scripts.py", line 718, in process
        script.process(p, *script_args)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 902, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 620, in choose_input_image
        resize_mode = external_code.resize_mode_from_value(unit.resize_mode)
      File "/home/ubuntu/apps/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 63, in resize_mode_from_value
        return ResizeMode(resize_mode_aliases.get(value, value))
      File "/usr/lib/python3.10/enum.py", line 385, in __call__
        return cls.__new__(cls, value)
      File "/usr/lib/python3.10/enum.py", line 710, in __new__
        raise ve_exc
    ValueError: 'ResizeMode.INNER_FIT' is not a valid ResizeMode

---
```

**Comment by markosole** [comment]
Same issue here, image is generated but does not follow ControlNet settings.

**Comment by VIncewww** [comment]
same issue here

**Comment by nianchu1** [comment]
same question here

**Comment by huchenlei** [comment]
Hoppfully the enum issue is fixed in https://github.com/Mikubill/sd-webui-controlnet/pull/2847.
