### ISSUE TITLE
[Bug]: `depth_hand_refiner` is unable to load `hand_landmarker.task` after running the `mediapipe_face` preprocessor

### ISSUE THREAD

**Issue by nightlymizu** [Mikubill/sd-webui-controlnet#2638]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

ControlNet `depth_hand_refiner` preprocessor is unable to load `hand_landmarker.task` after running the `mediapipe_face` preprocessor.

### Steps to reproduce the problem

1. Open a **new** SD WebUI backend
2. Open SD WebUI in browser and open ControlNet panel
3. Select and upload an image to ControlNet
4. Select `mediapipe_face` in the preprocessor dropdown
5. Run preprocessor
6. Select `depth_hand_refiner` in the preprocessor dropdown
7. Run preprocessor
8. Error occurred (see error message below)

It is important to restart the backend in step 1, otherwise the issue may not be reproducible due to cache.

If you omit step 4 and 5, the `depth_hand_refiner` can run just fine. So my guess is something in step 4 and 5 disrupted the internal state of `mediapipe`. And if you run `depth_hand_refiner` first then run `mediapipe_face` afterward, both can run well.

Also the same steps apply to [Stable Diffusion WebUI Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge) as well.

## Error Message

```powershell
=> loading pretrained model E:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\hand_refiner\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 1013, in run_annotator
    result, is_image = preprocessor(
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
    return cached_func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 859, in run_model
    self.load_model()
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 845, in load_model
    self.model = MeshGraphormerDetector.from_pretrained(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\__init__.py", line 17, in from_pretrained
    pipeline = MeshGraphormerMediapipe(args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\pipeline.py", line 198, in __init__
    self.detector = vision.HandLandmarker.create_from_options(options)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 364, in create_from_options
    return cls(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 70, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: Unable to open file at E:\stable-diffusion-webui\venv\lib\site-packages/E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\hand_landmarker.task, errno=22
```

* *Note that the file path is incorrect.*

### What should have happened?

Run `depth_hand_refiner` preprocessor without any error.

### Commit where the problem happens

* OS: Windows 11 Home (23H2)
* Python 3.10.11
* Stable Diffusion WebUI v1.7.0 (commit: `cf2772fab0af5573da775e7437e6acdca424f26e`)
* sd-webui-controlnet v1.1.440 (commit: `416c345072c9c2066101e225964e3986abe6945e`)
* handrefinerportable 2024.1.18.0
* mediapipe v0.10.9

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers --precision full --no-half --api --api-server-stop
```

### List of enabled extensions

`LDSR` (built-in)
`Lora` (built-in)
`ScuNET` (built-in)
`SwinIR` (built-in)
`canvas-zoom-and-pan` (built-in)
`extra-options-section` (built-in)
`hypertile` (built-in)
`mobile` (built-in)
`prompt-bracket-checker` (built-in)
`Stable-Diffusion-Webui-Civitai-Helper` (`https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper` `main 7f5707c0`)
`sd-webui-controlnet` (`https://github.com/Mikubill/sd-webui-controlnet.git` `main 416c3450`)
`sd-webui-openpose-editor` (`https://github.com/huchenlei/sd-webui-openpose-editor.git` `main cebe13e0`)

### Console logs

```Shell
venv "E:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --xformers --precision full --no-half --api --api-server-stop
Style database not found: E:\stable-diffusion-webui\styles.csv
Civitai Helper: Get Custom Model Folder
ControlNet preprocessor location: E:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-02-12 23:30:32,017 - ControlNet - INFO - ControlNet v1.1.440
2024-02-12 23:30:32,156 - ControlNet - INFO - ControlNet v1.1.440
Loading weights [abcdef1234] from E:\stable-diffusion-webui\models\Stable-diffusion\irrelevant.safetensors
2024-02-12 23:30:32,483 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Settings:
Civitai Helper: max_size_preview: True
Civitai Helper: skip_nsfw_preview: True
Civitai Helper: open_url_with_js: True
Civitai Helper: proxy:
Civitai Helper: use civitai api key: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: E:\stable-diffusion-webui\configs\v1-inference.yaml
Startup time: 20.6s (prepare environment: 4.7s, import torch: 5.7s, import gradio: 1.8s, setup paths: 1.1s, initialize shared: 0.7s, other imports: 1.0s, setup codeformer: 0.2s, list SD models: 0.2s, load scripts: 3.0s, create ui: 0.6s, gradio launch: 1.2s).
Loading VAE weights specified in settings: E:\stable-diffusion-webui\models\VAE\irrelevant.safetensors
Applying attention optimization: xformers... done.
Model loaded in 3.2s (load weights from disk: 0.9s, create model: 0.3s, apply weights to model: 1.7s, load VAE: 0.2s).
2024-02-12 23:33:12,804 - ControlNet - INFO - Preview Resolution = 512
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2024-02-12 23:33:23,684 - ControlNet - INFO - Preview Resolution = 512
set os.environ[OMP_NUM_THREADS] to 4
E:\stable-diffusion-webui\venv\lib\site-packages\scipy\sparse\_index.py:102: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
=> loading pretrained model E:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\hand_refiner\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 1013, in run_annotator
    result, is_image = preprocessor(
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
    return cached_func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 859, in run_model
    self.load_model()
  File "E:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 845, in load_model
    self.model = MeshGraphormerDetector.from_pretrained(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\__init__.py", line 17, in from_pretrained
    pipeline = MeshGraphormerMediapipe(args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\pipeline.py", line 198, in __init__
    self.detector = vision.HandLandmarker.create_from_options(options)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\mediapipe\tasks\python\vision\hand_landmarker.py", line 364, in create_from_options
    return cls(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 70, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: Unable to open file at E:\stable-diffusion-webui\venv\lib\site-packages/E:\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\hand_landmarker.task, errno=22
Stopping server...
Closing server running on port: 7860
```

## Workaround

As suggested in [google/mediapipe#4983](https://github.com/google/mediapipe/issues/4983#issuecomment-1854255489), instead of passing file path to `mediapipe`, load the file directly can avoid the file path bug in `mediapipe`.

Changes apply to [hand_refiner/pipeline.py, line #191](https://github.com/huchenlei/HandRefinerPortable/blob/d9c5506a1c13b396499dfdbaada9b7650e5d6d65/hand_refiner/pipeline.py#L191):

```diff
-        base_options = python.BaseOptions(model_asset_path=str( Path(__file__).parent / "hand_landmarker.task" ))
+        base_options = python.BaseOptions(model_asset_buffer=( Path(__file__).parent / "hand_landmarker.task" ).read_bytes())
```

## Related Issues

* [[Bug]: Hand refiner run error - Mikubill/sd-webui-controlnet#2541](https://github.com/Mikubill/sd-webui-controlnet/issues/2541)
* [[Bug]: hand_refiner - Bing-su/adetailer#496](https://github.com/Bing-su/adetailer/issues/496)
* [Unable to open file at \test\hand_landmarker.task - google/mediapipe#4983](https://github.com/google/mediapipe/issues/4983)

## Note

I am reporting this issue here rather than to [HandRefinerPortable](https://github.com/huchenlei/HandRefinerPortable) because reproducing this issue requires invoking other preprocessors in ControlNet. If the workaround is proven to be correct and effective, I will submit an issue there.

**Comment by huchenlei** [comment]
Thanks for providing such an detailed bug report and potential fix!

**Comment by huchenlei** [comment]
Successfully reproduced.

**Comment by huchenlei** [comment]
Proposed fix verified to be working.
