### ISSUE TITLE
[Bug]: instant_ID control type Preprocessor execute error

### ISSUE THREAD

**Issue by LFstefan** [Mikubill/sd-webui-controlnet#2640]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

<img width="1244" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/23207261/573530a6-ebb8-40b0-ae55-40eea19e70f3">
Preprocessor execute error，( i already install insightface module)
<img width="1061" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/23207261/68ad71d4-2bf4-419d-b322-463713fe62b6">

### Steps to reproduce the problem

1. use ControlNet v1.1.440
2. Control Type select instant_ID
3. Preprocessor select instant_id_face_keypoints
4. upload a img
5. run Preprocessor

### What should have happened?

show Preprocessor result without exception

### Commit where the problem happens

webui: v1.7.0
controlnet: 9a5f288

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--skip-torch-cuda-test --no-half
```

### List of enabled extensions

<img width="953" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/23207261/f29b5684-f6d6-4233-995d-8ba6492b4939">

### Console logs

```Shell
liufei ~/Documents/code/github/stable-diffusion-webui [(HEAD detached at v1.7.0)] $ ./webui.sh --skip-torch-cuda-test --no-half

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on liufei user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
ControlNet init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually.
Launching Web UI with arguments: --skip-torch-cuda-test --no-half --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: /Users/liufei/Documents/code/github/stable-diffusion-webui/styles.csv
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
ControlNet preprocessor location: /Users/liufei/Documents/code/github/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-02-13 19:52:58,066 - ControlNet - INFO - ControlNet v1.1.440
2024-02-13 19:52:58,240 - ControlNet - INFO - ControlNet v1.1.440
Loading weights [e9d3cedc4b] from /Users/liufei/Documents/code/github/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV40_v40VAE.safetensors
2024-02-13 19:52:58,673 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: /Users/liufei/Documents/code/github/stable-diffusion-webui/configs/v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.9s (prepare environment: 0.5s, import torch: 3.4s, import gradio: 1.1s, setup paths: 0.9s, initialize shared: 0.1s, other imports: 0.7s, setup codeformer: 0.1s, load scripts: 1.6s, create ui: 0.7s, gradio launch: 0.6s).
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
Applying attention optimization: InvokeAI... done.
Model loaded in 7.8s (load weights from disk: 0.9s, create model: 0.8s, apply weights to model: 2.5s, apply float(): 3.3s, calculate empty prompt: 0.1s).
2024-02-13 19:54:03,934 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 1013, in run_annotator
    result, is_image = preprocessor(
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 80, in decorated_func
    return cached_func(*args, **kwargs)
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 64, in cached_func
    return func(*args, **kwargs)
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/global_state.py", line 37, in unified_preprocessor
    return preprocessor_modules[preprocessor_name](*args, **kwargs)
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 801, in run_model_instant_id
    self.load_model()
  File "/Users/liufei/Documents/code/github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 739, in load_model
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'
```

### Additional information

<img width="1029" alt="image" src="https://github.com/Mikubill/sd-webui-controlnet/assets/23207261/2652aadb-f470-4250-b229-3474b0f92d2c">

**Comment by huchenlei** [comment]
See https://github.com/Mikubill/sd-webui-controlnet/discussions/2442. You need to first activate A1111's venv, and then pip install insightface.
