### ISSUE TITLE
[Bug]: Any of preprocessor wouldn't work (IndexError: too many indices for tensor of dimension 4)

### ISSUE THREAD

**Issue by vizgl** [Mikubill/sd-webui-controlnet#2641]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I enable any of preprocessors and try to generate image I got this error in the command line:

sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 384, in get_image_embeds
        clip_image_embeds = clip_vision_output['image_embeds'].to(device='cpu', dtype=torch.float32)
    IndexError: too many indices for tensor of dimension 4

### Steps to reproduce the problem

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/15825145/3da979d7-fdea-4091-a8fd-6e1747dfbd65)

### What should have happened?

Should work without errors

### Commit where the problem happens

webui:  1.70
controlnet:  1.1.440

### Command Line Arguments

```Shell
--medvram
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/15825145/c7f4f55a-3fd1-4a6d-b63f-25ac12c8d25a)

### Console logs

```Shell
100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:51<00:00,  2.34s/it]
2024-02-14 04:05:38,489 - ControlNet - INFO - Preview Resolution = -1
2024-02-14 04:05:43,593 - ControlNet - INFO - unit_separate = False, style_align = False
2024-02-14 04:05:43,937 - ControlNet - INFO - Loading model from cache: ip-adapter_sd15 [dbbc7cfe]
2024-02-14 04:05:43,938 - ControlNet - INFO - Using preprocessor: tile_resample
2024-02-14 04:05:43,938 - ControlNet - INFO - preprocessor resolution = -1
*** Error running process: D:\AI\stable-diffusion-webui-master-old\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui-master-old\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\AI\stable-diffusion-webui-master-old\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "D:\AI\stable-diffusion-webui-master-old\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\AI\stable-diffusion-webui-master-old\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1087, in controlnet_main_entry
        param.control_model.hook(
      File "D:\AI\stable-diffusion-webui-master-old\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\AI\stable-diffusion-webui-master-old\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 610, in hook
        self.image_emb = ImageEmbed.average_of(*[self.get_image_emb(o) for o in preprocessor_outputs])
      File "D:\AI\stable-diffusion-webui-master-old\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 610, in <listcomp>
        self.image_emb = ImageEmbed.average_of(*[self.get_image_emb(o) for o in preprocessor_outputs])
      File "D:\AI\stable-diffusion-webui-master-old\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 589, in get_image_emb
        return self.ipadapter.get_image_embeds(preprocessor_output)
      File "D:\AI\stable-diffusion-webui-master-old\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\AI\stable-diffusion-webui-master-old\extensions\sd-webui-controlnet\scripts\controlmodel_ipadapter.py", line 384, in get_image_embeds
        clip_image_embeds = clip_vision_output['image_embeds'].to(device='cpu', dtype=torch.float32)
    IndexError: too many indices for tensor of dimension 4

---
100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:32<00:00,  1.48s/it]
```

**Comment by huchenlei** [comment]
Why are you feeding depth map to ipadapter mdoel? If you want to use ipadapter, you need to choose corresponding clip model.
