### ISSUE TITLE
[Bug]: Max retries exceeded with url: /hr16/ControlNet-HandRefiner-pruned/resolve/main/graphormer_hand_state_dict.bin

### ISSUE THREAD

**Issue by yumianhuli1** [Mikubill/sd-webui-controlnet#2660]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Every time I use the depth_hand_refiner preprocessor of the control_v11f1p_sd15_depth_fp16 module, webui try to go to the url of hugggingface: / hr16 / ControlNet - HandRefiner - pruned/resolve/main/graphormer_hand_state_dict. bin.
But this controlnet and depth_hand_refiner I have already downloaded locally.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13059391/fb766909-0826-427e-a0fa-0393bea76435)

### Steps to reproduce the problem

Call the adtailer webui api
       
       "alwayson_scripts": {
                "ADetailer": {
                    "args": [
                        {
                            "ad_model": "face_yolov8n.pt",
                        },
                        {
                            "ad_model": "hand_yolov8n.pt",
                            "ad_denoising_strength": 0.2,
                            "ad_controlnet_model": "control_v11f1p_sd15_depth_fp16",
                            "ad_controlnet_module": "depth_hand_refiner"
                        }
                    ]
                }
            },

### What should have happened?

Load the local controlnet module and the depth_hand_refiner model directly

### Commit where the problem happens

webui: v4.6.1
controlnet: v1.1.439

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/13059391/1405646d-908d-4d98-8d85-e13cefba95e7)

### Console logs

```Shell
related logs:
2024-02-26 10:12:35,444 - ControlNet - [0;32mINFO[0m - unit_separate = False, style_align = False
2024-02-26 10:12:35,631 - ControlNet - [0;33mWARNING[0m - [depth_hand_refiner.processor_res] Invalid value(-1), using default value 512.
2024-02-26 10:12:35,631 - ControlNet - [0;32mINFO[0m - Loading model: control_v11f1p_sd15_depth_fp16 [4b72d323]
2024-02-26 10:12:35,650 - ControlNet - [0;32mINFO[0m - Loaded state_dict from [C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\models\ControlNet\control_v11f1p_sd15_depth_fp16.safetensors]
2024-02-26 10:12:35,651 - ControlNet - [0;32mINFO[0m - controlnet_default_config
2024-02-26 10:12:38,773 - ControlNet - [0;32mINFO[0m - ControlNet model control_v11f1p_sd15_depth_fp16 [4b72d323] loaded.
2024-02-26 10:12:38,836 - ControlNet - [0;32mINFO[0m - Using preprocessor: depth_hand_refiner
2024-02-26 10:12:38,836 - ControlNet - [0;32mINFO[0m - preprocessor resolution = 512
Failed to find C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\annotator\downloads\hand_refiner\hr16/ControlNet-HandRefiner-pruned\graphormer_hand_state_dict.bin.
 Downloading from huggingface.co
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /hr16/ControlNet-HandRefiner-pruned/resolve/main/graphormer_hand_state_dict.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002875C1C4D00>, 'Connection to huggingface.co timed out. (connect timeout=100)'))' thrown while requesting HEAD https://huggingface.co/hr16/ControlNet-HandRefiner-pruned/resolve/main/graphormer_hand_state_dict.bin
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /hr16/ControlNet-HandRefiner-pruned/resolve/main/graphormer_hand_state_dict.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002875C1C4D00>, 'Connection to huggingface.co timed out. (connect timeout=100)'))' thrown while requesting HEAD https://huggingface.co/hr16/ControlNet-HandRefiner-pruned/resolve/main/graphormer_hand_state_dict.bin
*** Error running process: C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1138, in process
        self.controlnet_hack(p)
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1123, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 930, in controlnet_main_entry
        detected_map, is_image = self.preprocessor[unit.module](
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\utils.py", line 80, in decorated_func
        return cached_func(*args, **kwargs)
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\utils.py", line 64, in cached_func
        return func(*args, **kwargs)
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\processor.py", line 858, in run_model
        self.load_model()
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\extensions\sd-webui-controlnet\scripts\processor.py", line 844, in load_model
        self.model = MeshGraphormerDetector.from_pretrained(
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\hand_refiner\__init__.py", line 14, in from_pretrained
        args.resume_checkpoint = custom_hf_download(pretrained_model_or_path, filename, cache_dir)
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\hand_refiner\util.py", line 178, in custom_hf_download
        model_path = hf_hub_download(repo_id=pretrained_model_or_path,
      File "<enhanced_experience patches.hfmirror.huggingface_hub>", line 52, in hf_hub_download_wrapper_inner
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
        return fn(*args, **kwargs)
      File "C:\jieya\sd-webui-aki\sd-webui-aki-v4.6.1\sd-webui-aki-v4.6.1\python\lib\site-packages\huggingface_hub\file_download.py", line 1291, in hf_hub_download
        raise LocalEntryNotFoundError(
    huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on
```

**Comment by huchenlei** [comment]
If you are in mainland China, you might want to find alternative source of preprocessor models download.

**Comment by huchenlei** [comment]
`control_v11f1p_sd15_depth_fp16.safetensors` is ControlNet model. The error you are seeing is from downloading preprocessor models. You need to download https://huggingface.co/hr16/ControlNet-HandRefiner-pruned/resolve/main/graphormer_hand_state_dict.bin and put it under `extensions/sd-webui-controlnet/annotator/downloads`.

**Comment by yumianhuli1** [comment]
> `control_v11f1p_sd15_depth_fp16.safetensors` is ControlNet model. The error you are seeing is from downloading preprocessor models. You need to download https://huggingface.co/hr16/ControlNet-HandRefiner-pruned/resolve/main/graphormer_hand_state_dict.bin and put it under `extensions/sd-webui-controlnet/annotator/downloads/hand_refiner`.

yes，I have done this
