### ISSUE TITLE
[Bug]: seg_ufade20k issue

### ISSUE THREAD

**Issue by DavideAlidosi** [Mikubill/sd-webui-controlnet#2693]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I would like to report that pre-processor seg_ufade20k does not seem to be working at the moment. The other pre-processors in the series work perfectly for me.

### Steps to reproduce the problem

1. Go to unit 0
2. Load a single image
3. select Segmentation
4. Select seg_ufade20k
5. Load control_v11p_sd15_seg [e1f51eb9]
6. Click on generate

### What should have happened?

Having a generation based on input image.

### Commit where the problem happens

webui: 1.8.0
controlnet: 1.441

### Command Line Arguments

```Shell
-xformers
```

### List of enabled extensions

![extension](https://github.com/Mikubill/sd-webui-controlnet/assets/19665235/0329d9f0-77ae-40b7-ae4b-cb5d8e1bb9c2)

### Console logs

```Shell
Traceback (most recent call last):
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\annotator\uniformer\inference.py", line 5, in <module>
        import mmcv as mmcv
    ModuleNotFoundError: No module named 'mmcv'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "L:\WebUI\webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1279, in process
        self.controlnet_hack(p)
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1264, in controlnet_hack
        self.controlnet_main_entry(p)
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1029, in controlnet_main_entry
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1029, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 986, in preprocess_input_image
        detected_map, is_image = self.preprocessor[unit.module](
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\utils.py", line 81, in decorated_func
        return cached_func(*args, **kwargs)
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\utils.py", line 65, in cached_func
        return func(*args, **kwargs)
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\scripts\processor.py", line 314, in uniformer
        from annotator.uniformer import apply_uniformer
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\annotator\uniformer\__init__.py", line 4, in <module>
        from annotator.uniformer.inference import init_segmentor, inference_segmentor, show_result_pyplot
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\annotator\uniformer\inference.py", line 11, in <module>
        import annotator.mmpkg.mmcv as mmcv
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\__init__.py", line 4, in <module>
        from .fileio import *
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\fileio\__init__.py", line 2, in <module>
        from .file_client import BaseStorageBackend, FileClient
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\fileio\file_client.py", line 15, in <module>
        from annotator.mmpkg.mmcv.utils.misc import has_method
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\__init__.py", line 3, in <module>
        from .config import Config, ConfigDict, DictAction
      File "L:\WebUI\webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\config.py", line 16, in <module>
        from addict import Dict
    ModuleNotFoundError: No module named 'addict'
```

### Additional information

Not needed

**Comment by huchenlei** [comment]
Issue confirmed reproducable.
