### ISSUE TITLE
[Bug]: IPAdapter doesn't recognize Face since new ControNet update

### ISSUE THREAD

**Issue by INTstinkt** [Mikubill/sd-webui-controlnet#2726]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

 think the new update broke FaceID it doesn't matter which picture i use in Controlnet i always get the same error message

I used the same pictures just yesterday to do some testing also tried some new pictures but it doesnt work at all anymore

I found out that if i mask the face or the whole picture i do not get the error message but it is way worse and mostly doesnt resemble the person very much

Heres one of the pictures which worked fine just yesterday
![file (4)](https://github.com/Mikubill/sd-webui-controlnet/assets/133846628/df5f0bdf-21b2-48ca-9336-883a61603810)

### Steps to reproduce the problem

Preprocessor : ip-adapter-auto
Model: ip-adapter-faceid-plusv2_sdxl
lora: lora:ip-adapter-faceid-plusv2_sdxl_lora:0.75

Before it worked without masking out the face, now if i dont mask out the face i get the error. if i do mask out the face the face has some similaritys but compared to yesterday way worse i would say

### What should have happened?

Should work without having to mask the face

### Commit where the problem happens

webui: A1111
version: [v1.8.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/bef51aed032c0aaa5cfd80445bc4cf0d85b408b5)  •  python: 3.10.11  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2

extension: ControlNet 1.1.443

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers
```

### List of enabled extensions

Adetailer
Multidiffusion Upscaler
AnimateDiff
ControlNet
extended-style-saver
hires-fix-tweaks
inpaint-anything
ultimate-upscale

### Console logs

```Shell
2024-04-01 00:04:12,215 - ControlNet - INFO - ip-adapter-auto => ip-adapter_face_id_plus
2024-04-01 00:04:12,215 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-01 00:04:12,510 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sdxl [187cb962]
2024-04-01 00:04:12,774 - ControlNet - INFO - Loaded state_dict from [C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\models\ip-adapter-faceid-plusv2_sdxl.bin]
2024-04-01 00:04:15,128 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sdxl [187cb962](https://github.com/Mikubill/sd-webui-controlnet/discussions/ControlModelType.IPAdapter) loaded.
2024-04-01 00:04:15,129 - ControlNet - INFO - using mask
2024-04-01 00:04:15,133 - ControlNet - INFO - Using preprocessor: ip-adapter_face_id_plus
2024-04-01 00:04:15,133 - ControlNet - INFO - preprocessor resolution = 512
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
*** Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 784, in process
script.process(p, script_args)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1245, in process
self.controlnet_hack(p)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1230, in controlnet_hack
self.controlnet_main_entry(p)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 995, in controlnet_main_entry
controls, hr_controls = list(zip([preprocess_input_image(img) for img in optional_tqdm(input_images)]))
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 995, in
controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 952, in preprocess_input_image
detected_map, is_image = self.preprocessor[unit.module](
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 81, in decorated_func
return cached_func(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 65, in cached_func
return func(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
return preprocessor_modules[preprocessor_name](*args, **kwargs)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 848, in face_id_plus
face_embed, _ = g_insight_face_model.run_model(img)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 771, in run_model
raise Exception("Insightface: No face found in image.")
Exception: Insightface: No face found in image.
```

**Comment by ZeroCool22** [comment]
Same problem, how i can go back to the version that works before?
