### ISSUE TITLE
[Bug]: Multi-inputs dont work

### ISSUE THREAD

**Issue by ivanced09** [Mikubill/sd-webui-controlnet#2731]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The multi-inputs function has stopped working since the last update, I used it with both FaceID or the IP adapter clip 1.5 without problems until it stopped working with any controlnet since the last update

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/113315177/0014dde9-d8bc-4f3e-abf3-ecd045641e09)

### Steps to reproduce the problem

1.Try use multi-inputs with IP adapters o another CN model

### What should have happened?

I usually use it to mix faces or styles

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
--xformers
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/113315177/214dc116-8d73-4bec-aef9-6a036e9c8be9)

### Console logs

```Shell
venv "H:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
CUDA 12.1
Launching Web UI with arguments: --xformers
[-] ADetailer initialized. version: 24.3.5, num models: 15
ControlNet preprocessor location: H:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-04-03 10:30:45,225 - ControlNet - INFO - ControlNet v1.1.443
2024-04-03 10:30:45,538 - ControlNet - INFO - ControlNet v1.1.443
10:30:48 - ReActor - STATUS - Running v0.7.0-b7 on Device: CUDA
Loading weights [07919b495d] from H:\stable-diffusion-webui\models\Stable-diffusion\picxReal_10.safetensors
Creating model from config: H:\stable-diffusion-webui\configs\v1-inference.yaml
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 42.7s (prepare environment: 11.5s, import torch: 7.7s, import gradio: 2.3s, setup paths: 3.9s, initialize shared: 2.9s, other imports: 1.8s, list SD models: 0.4s, load scripts: 8.5s, scripts before_ui_callback: 0.6s, create ui: 2.6s, gradio launch: 0.6s, app_started_callback: 0.2s).
Loading VAE weights specified in settings: H:\stable-diffusion-webui\models\VAE\vae-ft-ema-560000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
Model loaded in 25.6s (create model: 2.1s, apply weights to model: 20.7s, load VAE: 0.6s, move model to device: 0.1s, load textual inversion embeddings: 0.1s, calculate empty prompt: 1.9s).
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 4 images in a total of 1 batches.
2024-04-03 11:09:09,309 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:09:09,609 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-04-03 11:09:10,011 - ControlNet - INFO - Loaded state_dict from [H:\stable-diffusion-webui\models\ControlNet\ip-adapter-faceid-plusv2_sd15.bin]
2024-04-03 11:09:10,498 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sd15 [6e14fc1a](ControlModelType.IPAdapter) loaded.
*** Error running process: H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1245, in process
        self.controlnet_hack(p)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1230, in controlnet_hack
        self.controlnet_main_entry(p)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 916, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 700, in choose_input_image
        raise ValueError("controlnet is enabled but no input image is given")
    ValueError: controlnet is enabled but no input image is given

---
 33%|███████████████████████████▎                                                      | 10/30 [00:13<00:27,  1.37s/it]
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 4 images in a total of 1 batches.<00:18,  1.09it/s]
2024-04-03 11:09:27,161 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:09:27,162 - ControlNet - INFO - Loading model from cache: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
*** Error running process: H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1245, in process
        self.controlnet_hack(p)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1230, in controlnet_hack
        self.controlnet_main_entry(p)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 916, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 700, in choose_input_image
        raise ValueError("controlnet is enabled but no input image is given")
    ValueError: controlnet is enabled but no input image is given

---
Total progress:  33%|██████████████████████                                            | 10/30 [00:10<00:21,  1.06s/it]
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 4 images in a total of 1 batches.<00:18,  1.09it/s]
2024-04-03 11:14:42,321 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:14:42,322 - ControlNet - INFO - Loading model: control_v11p_sd15_lineart [43d4be0d]
2024-04-03 11:14:45,882 - ControlNet - INFO - Loaded state_dict from [H:\stable-diffusion-webui\models\ControlNet\control_v11p_sd15_lineart.pth]
2024-04-03 11:14:45,882 - ControlNet - INFO - controlnet_default_config
2024-04-03 11:14:48,868 - ControlNet - INFO - ControlNet model control_v11p_sd15_lineart [43d4be0d](ControlModelType.ControlNet) loaded.
*** Error running process: H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1245, in process
        self.controlnet_hack(p)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1230, in controlnet_hack
        self.controlnet_main_entry(p)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 916, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 700, in choose_input_image
        raise ValueError("controlnet is enabled but no input image is given")
    ValueError: controlnet is enabled but no input image is given

---
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:30<00:00,  1.01s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:29<00:00,  1.07s/it]
0: 640x640 1 face, 15.6ms
Speed: 0.0ms preprocess, 15.6ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)
2024-04-03 11:15:21,458 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:15:21,787 - ControlNet - INFO - Loading model: control_v11p_sd15_inpaint [ebff9138]
2024-04-03 11:15:22,561 - ControlNet - INFO - Loaded state_dict from [H:\stable-diffusion-webui\models\ControlNet\control_v11p_sd15_inpaint.pth]
2024-04-03 11:15:22,562 - ControlNet - INFO - controlnet_default_config
2024-04-03 11:15:25,444 - ControlNet - INFO - ControlNet model control_v11p_sd15_inpaint [ebff9138](ControlModelType.ControlNet) loaded.
2024-04-03 11:15:25,496 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-03 11:15:25,496 - ControlNet - INFO - preprocessor resolution = 512
2024-04-03 11:15:25,564 - ControlNet - INFO - ControlNet Hooked - Time = 4.105283975601196
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:06<00:00,  2.32it/s]
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
mediapipe: 1 detected.
2024-04-03 11:15:34,233 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:15:34,233 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-04-03 11:15:34,275 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-03 11:15:34,275 - ControlNet - INFO - preprocessor resolution = 512
2024-04-03 11:15:34,394 - ControlNet - INFO - ControlNet Hooked - Time = 0.16516971588134766
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  5.25it/s]

0: 640x640 1 face, 9.0ms
Speed: 5.0ms preprocess, 9.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
2024-04-03 11:15:38,385 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:15:38,386 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-04-03 11:15:38,429 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-03 11:15:38,430 - ControlNet - INFO - preprocessor resolution = 512
2024-04-03 11:15:38,492 - ControlNet - INFO - ControlNet Hooked - Time = 0.11106204986572266
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  5.23it/s]
mediapipe: 1 detected.
2024-04-03 11:15:42,405 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:15:42,405 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-04-03 11:15:42,447 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-03 11:15:42,447 - ControlNet - INFO - preprocessor resolution = 512
2024-04-03 11:15:42,510 - ControlNet - INFO - ControlNet Hooked - Time = 0.1091451644897461
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  5.21it/s]

0: 640x640 1 face, 11.0ms
Speed: 5.6ms preprocess, 11.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
2024-04-03 11:15:46,706 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:15:46,707 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-04-03 11:15:46,750 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-03 11:15:46,750 - ControlNet - INFO - preprocessor resolution = 512
2024-04-03 11:15:46,814 - ControlNet - INFO - ControlNet Hooked - Time = 0.11259603500366211
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  5.23it/s]
mediapipe: 1 detected.
2024-04-03 11:15:50,732 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:15:50,732 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-04-03 11:15:50,779 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-03 11:15:50,779 - ControlNet - INFO - preprocessor resolution = 512
2024-04-03 11:15:50,826 - ControlNet - INFO - ControlNet Hooked - Time = 0.09375452995300293
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  5.26it/s]

0: 640x640 1 face, 0.0ms
Speed: 15.6ms preprocess, 0.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)
2024-04-03 11:15:54,800 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:15:54,800 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-04-03 11:15:54,846 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-03 11:15:54,846 - ControlNet - INFO - preprocessor resolution = 512
2024-04-03 11:15:54,909 - ControlNet - INFO - ControlNet Hooked - Time = 0.10938334465026855
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:03<00:00,  5.26it/s]
mediapipe: 1 detected.
2024-04-03 11:15:58,799 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:15:58,799 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_inpaint [ebff9138]
2024-04-03 11:15:58,831 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-03 11:15:58,831 - ControlNet - INFO - preprocessor resolution = 512
2024-04-03 11:15:58,893 - ControlNet - INFO - ControlNet Hooked - Time = 0.10938286781311035
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  5.21it/s]
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 4 images in a total of 1 batches.
2024-04-03 11:16:02,187 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-03 11:16:02,187 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_lineart [43d4be0d]
*** Error running process: H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1245, in process
        self.controlnet_hack(p)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1230, in controlnet_hack
        self.controlnet_main_entry(p)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 916, in controlnet_main_entry
        input_image, resize_mode = Script.choose_input_image(p, unit, idx)
      File "H:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 700, in choose_input_image
        raise ValueError("controlnet is enabled but no input image is given")
    ValueError: controlnet is enabled but no input image is given

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [01:13<00:00,  2.46s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [01:13<00:00,  1.07s/it]
```

**Comment by CRCODE22** [comment]
I have seen it happen when you use the single image option but then before selecting an image you cancel then you use the multi input and select multiple images and then it will throw that error.

**Comment by huchenlei** [comment]
> I have seen it happen when you use the single image option but then before selecting an image you cancel then you use the multi input and select multiple images and then it will throw that error.

Can you give more context on reproduction steps?

**Comment by CRCODE22** [comment]
> > I have seen it happen when you use the single image option but then before selecting an image you cancel then you use the multi input and select multiple images and then it will throw that error.
> 
> Can you give more context on reproduction steps?

It is exactly as I described when you startup stable diffusion web ui and you choose single image input but you realize you wanted multi inputs you cancel without selecting an image and then you go to multi inputs and you select multiple images it will throw that error. 

To solve it you go back to single image input and choose an image then you use the x to remove that image from the single image input and then you can select multi input and select multi input images and it should work
