### ISSUE TITLE
[Bug]: Controlnet Multi input

### ISSUE THREAD

**Issue by Joris9044** [Mikubill/sd-webui-controlnet#2734]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Error when using multi put ins.

### Steps to reproduce the problem

Controlnet Unit one, add 2 images in multi input.
Controlnet Unit two, add Input Directory under Batch.

### What should have happened?

Generating images.

### Commit where the problem happens

Controlnet version: 679b6279

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/166191112/22b1f52d-78e8-42f8-84ad-34b068be9779)

### Console logs

```Shell
Traceback (most recent call last):
      File "E:\User\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "E:\User\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "E:\User\stable-diffusion-webui\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "E:\User\stable-diffusion-webui\modules\processing.py", line 785, in process_images
        res = process_images_inner(p)
      File "E:\User\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 63, in processing_process_images_hijack
        self.dispatch_callbacks(self.process_batch_callbacks, p, batches, output_dir)
      File "E:\User\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 179, in dispatch_callbacks
        callback(*args)
      File "E:\User\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1330, in batch_tab_process
        unit.batch_images = iter([batch[unit_i] for batch in batches])
      File "E:\User\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1330, in <listcomp>
        unit.batch_images = iter([batch[unit_i] for batch in batches])
    IndexError: list index out of range
```

**Comment by modey3** [comment]
Hello,

Has this issue been addressed? I am getting the same error. From what I understand about about Multi-Input (implemented using Reference function) , this should not impact whether I use single or batch in a different controlnet-unit (in this case implementing openpose within the controlnet-unit). Has anyone found a work around? Multi-Input (implemented within Reference function) is great for getting consistent images of the same character. I would like to see this resolved.
