### ISSUE TITLE
[Bug]:  Exception: Insightface: No face found in image.

### ISSUE THREAD

**Issue by ZeroCool22** [Mikubill/sd-webui-controlnet#2747]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When try to use it for Inpainting in img2img i get the follow error **(it didn't happen before the last update)**:

```
42%|██████████████████████████████████▉                                                | 8/19 [00:03<00:04,  2.23it/s]
2024-04-14 22:08:57,930 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-14 22:08:58,199 - ControlNet - INFO - Loading model: control_v11p_sd15_inpaint [ebff9138]
2024-04-14 22:09:01,117 - ControlNet - INFO - Loaded state_dict from [C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\models\1.5\control_v11p_sd15_inpaint.pth]
2024-04-14 22:09:01,117 - ControlNet - INFO - controlnet_default_config
2024-04-14 22:09:02,808 - ControlNet - INFO - ControlNet model control_v11p_sd15_inpaint [ebff9138](ControlModelType.ControlNet) loaded.
2024-04-14 22:09:02,844 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-14 22:09:02,844 - ControlNet - INFO - preprocessor resolution = 600
2024-04-14 22:09:03,071 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-04-14 22:09:03,393 - ControlNet - INFO - Loaded state_dict from [C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\models\ControlNet\ip-adapter-faceid-plusv2_sd15.bin]
2024-04-14 22:09:03,727 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sd15 [6e14fc1a](ControlModelType.IPAdapter) loaded.
2024-04-14 22:09:03,762 - ControlNet - INFO - Using preprocessor: ip-adapter_face_id_plus
2024-04-14 22:09:03,762 - ControlNet - INFO - preprocessor resolution = 600
*** Error running process: C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1245, in process
        self.controlnet_hack(p)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1230, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 995, in controlnet_main_entry
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 995, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 952, in preprocess_input_image
        detected_map, is_image = self.preprocessor[unit.module](
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 81, in decorated_func
        return cached_func(*args, **kwargs)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 65, in cached_func
        return func(*args, **kwargs)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 850, in face_id_plus
        face_embed, _ = g_insight_face_model.run_model(img)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 781, in run_model
        face = InsightFaceModel.pick_largest_face(faces)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 738, in pick_largest_face
        raise Exception("Insightface: No face found in image.")
    Exception: Insightface: No face found in image.
```

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Detect the face.

### Commit where the problem happens

webui: AUTOMATIC1111 
version: [v1.9.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/adadb4e3c7382bf3e4f7519126cd6c70f4f8557b)  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2

controlnet: 
![Screenshot_7](https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/50128314-d3f8-4127-ad2f-a38d91aad990)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--xformers --api --disable-nan-check --medvram-sdxl
```

### List of enabled extensions

![Screenshot_9](https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/6aaa2256-2632-4af2-8efe-cd48b866e1b7)

### Console logs

```Shell
42%|██████████████████████████████████▉                                                | 8/19 [00:03<00:04,  2.23it/s]
2024-04-14 22:08:57,930 - ControlNet - INFO - unit_separate = False, style_align = False
2024-04-14 22:08:58,199 - ControlNet - INFO - Loading model: control_v11p_sd15_inpaint [ebff9138]
2024-04-14 22:09:01,117 - ControlNet - INFO - Loaded state_dict from [C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\models\1.5\control_v11p_sd15_inpaint.pth]
2024-04-14 22:09:01,117 - ControlNet - INFO - controlnet_default_config
2024-04-14 22:09:02,808 - ControlNet - INFO - ControlNet model control_v11p_sd15_inpaint [ebff9138](ControlModelType.ControlNet) loaded.
2024-04-14 22:09:02,844 - ControlNet - INFO - Using preprocessor: inpaint
2024-04-14 22:09:02,844 - ControlNet - INFO - preprocessor resolution = 600
2024-04-14 22:09:03,071 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-04-14 22:09:03,393 - ControlNet - INFO - Loaded state_dict from [C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\models\ControlNet\ip-adapter-faceid-plusv2_sd15.bin]
2024-04-14 22:09:03,727 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sd15 [6e14fc1a](ControlModelType.IPAdapter) loaded.
2024-04-14 22:09:03,762 - ControlNet - INFO - Using preprocessor: ip-adapter_face_id_plus
2024-04-14 22:09:03,762 - ControlNet - INFO - preprocessor resolution = 600
*** Error running process: C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1245, in process
        self.controlnet_hack(p)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1230, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 995, in controlnet_main_entry
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 995, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 952, in preprocess_input_image
        detected_map, is_image = self.preprocessor[unit.module](
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 81, in decorated_func
        return cached_func(*args, **kwargs)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 65, in cached_func
        return func(*args, **kwargs)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 37, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 850, in face_id_plus
        face_embed, _ = g_insight_face_model.run_model(img)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 781, in run_model
        face = InsightFaceModel.pick_largest_face(faces)
      File "C:\Users\ZeroCool22\Desktop\AutoSDXL\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 738, in pick_largest_face
        raise Exception("Insightface: No face found in image.")
    Exception: Insightface: No face found in image.
```
```


### Additional information

_No response_

**Comment by ZeroCool22** [comment]
Image used in controlnet:

![45889999](https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/b89a2151-df43-4137-a297-deb70fbda27c)

**Comment by huchenlei** [comment]
Suspected culprit: #2744.

**Comment by huchenlei** [comment]
I cannot reproduce your issue. InstantID does correctly detects face in the image.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/20929282/063b38ed-b5c5-4d05-abd9-cefe403d8cb6)

**Comment by ZeroCool22** [comment]
> I cannot reproduce your issue. InstantID does correctly detects face in the image. ![image](https://private-user-images.githubusercontent.com/20929282/322340532-063b38ed-b5c5-4d05-abd9-cefe403d8cb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTA3ODQsIm5iZiI6MTcxMzE1MDQ4NCwicGF0aCI6Ii8yMDkyOTI4Mi8zMjIzNDA1MzItMDYzYjM4ZWQtYjVjNS00ZDA1LWFiZDktY2VmZTQwM2Q4Y2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAzMDgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExODdjNTJkZjllZjc2ZjM0MWQ0MDE4ZGRjYTI2ZjlhMWE1ZjU2ZDNhY2I2ODgxOWQ2NjdjMGI2NDdkZTY1NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fOtRjdVeSo8uuuIsdhOpaS5knhAcAHnucZMQH0Mbqps)

I use 1.5, NOT SDXL.

![Screenshot_8](https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/0296d922-3bc9-4fb3-9f06-2643ce3a41c9)

**Comment by ZeroCool22** [comment]
> Suspected culprit: #2744.

Can you tell me where i add that code line exatcly?

![Screenshot_10](https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/e5e0635c-3683-4a78-9bc4-8fec71dbae86)

**Comment by huchenlei** [comment]
You can find file change here: https://github.com/Mikubill/sd-webui-controlnet/pull/2744/files

You just need to change 2 lines of code to revert that PR.

**Comment by huchenlei** [comment]
I think the PR is justified as main instant id repo also has the RGB to BGR convertion before passing the image to insightface here: https://github.com/InstantID/InstantID/blob/042a57c75a265db302eea4e402265d7a803dc93d/gradio_demo/app.py#L233

**Comment by ZeroCool22** [comment]
Thx, and this one?: 

`face_image_cv2 = convert_from_image_to_cv2(face_image)`

**Comment by ZeroCool22** [comment]
> You can find file change here: https://github.com/Mikubill/sd-webui-controlnet/pull/2744/files
> 
> You just need to change 2 lines of code to revert that PR.

I did it but still get same error.

![Screenshot_11](https://github.com/Mikubill/sd-webui-controlnet/assets/13344308/bc0b0202-494d-49ef-841d-b7131d5be36d)

It's because i didn't add the other line yet? 

(face_image_cv2 = convert_from_image_to_cv2(face_image))

**Comment by huchenlei** [comment]
Hmmmm, maybe checkout https://github.com/Mikubill/sd-webui-controlnet/commit/eb451a007f7040288e865f96e9ee0842aa6ef91c and see if the issue is still there?

**Comment by ZeroCool22** [comment]
> Hmmmm, maybe checkout to [eb451a0](https://github.com/Mikubill/sd-webui-controlnet/commit/eb451a007f7040288e865f96e9ee0842aa6ef91c) and see if the issue is still there?

Did all the changes, but same error.

Anyway, thx for take the time to try to help.

Instant ID only works for SDXL right?

**PD:** If you want to see for yourself, we can use **AnyDesk** if you want sometime.
