### ISSUE TITLE
Error loading script: controlnet.py AttributeError: module 'modules.script_callbacks' has no attribute 'on_after_component'

### ISSUE THREAD

**Issue by hypervoxel** [Mikubill/sd-webui-controlnet#275]
Error loading script: controlnet.py
Traceback (most recent call last):
  File "G:\SD\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "G:\SD\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "G:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 667, in <module>
    script_callbacks.on_after_component(img2img_tab_tracker.on_after_component_callback)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_after_component'

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "G:\SD\stable-diffusion-webui\modules\scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "G:\SD\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "G:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 2, in <module>
    from scripts import controlnet
  File "G:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 667, in <module>
    script_callbacks.on_after_component(img2img_tab_tracker.on_after_component_callback)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_after_component'

I also do not see the contronet tab in txt2img or img2img (I've tried relaunching SD). Extension > installed shows as installed.

**Comment by ljleb** [comment]
Which version of the wwbui are you running? The webui defines this function. If you're running a recent version then I'm not sure what's going on, because it is defined.

**Comment by hypervoxel** [comment]
I likely need to update the webui then. Thank you. I'll try that and report back.
