### ISSUE TITLE
[Bug]: WebUI stops working after installing this extension

### ISSUE THREAD

**Issue by DatachPlayer** [Mikubill/sd-webui-controlnet#2756]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Problems started today when i have installed another model based on Pony Diffusion called AutismMix SDXL but i don't know if it is related to this problem exactly or not. After installing the extension this error comes up in cmd "ImportError: cannot import name 'Undefined' from 'pydantic.fields' (S:\AI\StableDiffusion\system\python\lib\site-packages\pydantic\fields.py)" and deleting controlnet extension in extensions folder does not help. The only thing that helps is deleting the contents of system folder and installing it again via sd.webui.zip and run.bat. I use Windows 10 and Firefox

### Steps to reproduce the problem

1. Go to Extensions tab in WebUI
2. Find the extension and press Install
3. Apply and restart WebUI

### What should have happened?

WebUI should start after applying and restarting

### Commit where the problem happens

webui: Automatic1111 1.9.0
controlnet: I have no idea as of webui doesn't start but it's the latest one at the moment of 17th of april 2024

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--theme dark --xformers
```

### List of enabled extensions

adetailer
sd-civitai-browser-plus
sd-dynamic-prompts
sd-webui-agent-scheduler
sd-webui-controlnet
sd-webui-infinite-image-browsing
sd-webui-regional-prompter

### Console logs

```Shell
Traceback (most recent call last):
  File "S:\AI\StableDiffusion\webui\launch.py", line 48, in <module>
    main()
  File "S:\AI\StableDiffusion\webui\launch.py", line 44, in main
    start()
  File "S:\AI\StableDiffusion\webui\modules\launch_utils.py", line 465, in start
    import webui
  File "S:\AI\StableDiffusion\webui\webui.py", line 13, in <module>
    initialize.imports()
  File "S:\AI\StableDiffusion\webui\modules\initialize.py", line 23, in imports
    import gradio  # noqa: F401
  File "S:\AI\StableDiffusion\system\python\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "S:\AI\StableDiffusion\system\python\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "S:\AI\StableDiffusion\system\python\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "S:\AI\StableDiffusion\system\python\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "S:\AI\StableDiffusion\system\python\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "S:\AI\StableDiffusion\system\python\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "S:\AI\StableDiffusion\system\python\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "S:\AI\StableDiffusion\system\python\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (S:\AI\StableDiffusion\system\python\lib\site-packages\pydantic\fields.py)
```

**Comment by huchenlei** [comment]
Merged into https://github.com/Mikubill/sd-webui-controlnet/issues/2757
