### ISSUE TITLE
[Bug]: Trying to install ControlNet breaks my WebUI

### ISSUE THREAD

**Issue by lksg98** [Mikubill/sd-webui-controlnet#2757]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When I try to install ControlNet it crashes my WebUI.
After I close webui-user.bat I am unable to use it again and its broken.

Unless I delete my 'venv' folder and delete sd-webui-controlnet folder from my extensions and run webui-user.bat again to create a new venv folder.

Can anyone explain step by step how to fix this?

### Steps to reproduce the problem

1. Go to .... Extensions Tab
2. Press .... Install from URL
3. ...Enter https://github.com/Mikubill/sd-webui-controlnet.git to "URL for extension's git repository".
4. Press "Install" button.
>Installed into C:\Users\user\Desktop\webuiclean\webui\extensions\sd-webui-controlnet. Use Installed tab to restart.
below I posted the last 3 lines in console log after this step.
"Warning: Failed to install handrefinerportable. Some processors will not work.
Installing sd-webui-controlnet requirement: depth_anything
Installing sd-webui-controlnet requirement: dsine"
_
6. Go to installed tab > Check for updates > Apply and restart UI
7. After restarting by using webui-user.bat I get a different error and I cannot open my WebUI again unless I delete my 'venv' folder and delete the sd-webui-controlnet folder

### What should have happened?

ControlNet installs and doesn't leave my webui broken

### Commit where the problem happens

version: [v1.9.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/adadb4e3c7382bf3e4f7519126cd6c70f4f8557b)  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2  •  checkpoint: [b65f69645c](https://google.com/search?q=b65f69645c4a02f66c163dab7201ef92f61260c6a8031bc1a7d028a14d916034)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --xformers

call webui.bat
```

### List of enabled extensions

LDSR
Lora
ScuNET
SwinIR
canvas-zoom-and-pan
extra-options-section
hypertile
mobile
postprocessing-for-training
prompt-bracket-checker
soft-inpainting
sd-webui-replacer - | https://github.com/light-and-ray/sd-webui-replacer
sd-webui-segment-anything | https://github.com/continue-revolution/sd-webui-segment-anything
sd-webui-animatediff- | https://github.com/light-and-ray/sd-webui-animatediff-

### Console logs

```Shell
venv "C:\Users\user\Desktop\webuiclean\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.0
Commit hash: adadb4e3c7382bf3e4f7519126cd6c70f4f8557b
Launching Web UI with arguments: --xformers
Loading weights [b65f69645c] from C:\Users\user\Desktop\webuiclean\webui\models\Stable-diffusion\majicmixRealistic_v7-inpainting.safetensors
Creating model from config: C:\Users\user\Desktop\webuiclean\webui\configs\v1-inpainting-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.3s (prepare environment: 2.5s, import torch: 3.9s, import gradio: 0.8s, setup paths: 1.0s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 1.5s, create ui: 0.5s, gradio launch: 0.2s).
Applying attention optimization: xformers... done.
Model loaded in 2.5s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 1.4s, calculate empty prompt: 0.1s).
Installing sd-webui-controlnet requirement: fvcore
Installing sd-webui-controlnet requirement: mediapipe
Couldn't install sd-webui-controlnet requirement: mediapipe.
Command: "C:\Users\user\Desktop\webuiclean\webui\venv\Scripts\python.exe" -m pip install mediapipe --prefer-binary
Error code: 1
stdout: Collecting mediapipe
  Using cached mediapipe-0.10.11-cp310-cp310-win_amd64.whl (50.8 MB)
Requirement already satisfied: attrs>=19.1.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from mediapipe) (23.2.0)
Collecting sounddevice>=0.4.4
  Using cached sounddevice-0.4.6-py3-none-win_amd64.whl (199 kB)
Requirement already satisfied: protobuf<4,>=3.11 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from mediapipe) (3.20.0)
Collecting absl-py
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.9.0.80-cp37-abi3-win_amd64.whl (45.3 MB)
Collecting flatbuffers>=2.0
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
Collecting jax
  Using cached jax-0.4.26-py3-none-any.whl (1.9 MB)
Requirement already satisfied: numpy in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from mediapipe) (1.26.2)
Requirement already satisfied: matplotlib in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from mediapipe) (3.8.4)
Collecting CFFI>=1.0
  Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl (181 kB)
Requirement already satisfied: scipy>=1.9 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from jax->mediapipe) (1.13.0)
Collecting opt-einsum
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting ml-dtypes>=0.2.0
  Using cached ml_dtypes-0.4.0-cp310-cp310-win_amd64.whl (126 kB)
Requirement already satisfied: cycler>=0.10 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe) (1.4.5)
Requirement already satisfied: pillow>=8 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe) (3.1.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe) (4.51.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe) (1.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe) (2.9.0.post0)
Requirement already satisfied: packaging>=20.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe) (24.0)
Collecting pycparser
  Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)
Installing collected packages: flatbuffers, pycparser, opt-einsum, opencv-contrib-python, ml-dtypes, absl-py, jax, CFFI, sounddevice, mediapipe

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\user\\Desktop\\webuiclean\\webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.


[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: C:\Users\user\Desktop\webuiclean\webui\venv\Scripts\python.exe -m pip install --upgrade pip

Warning: Failed to install mediapipe, some preprocessors may not work.
Installing sd-webui-controlnet requirement: onnxruntime
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: insightface
Couldn't install sd-webui-controlnet requirement: insightface.
Command: "C:\Users\user\Desktop\webuiclean\webui\venv\Scripts\python.exe" -m pip install https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl --prefer-binary
Error code: 1
stdout: Collecting insightface==0.7.3
  Using cached https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl (841 kB)
Collecting easydict
  Using cached easydict-1.13-py3-none-any.whl (6.8 kB)
Collecting prettytable
  Using cached prettytable-3.10.0-py3-none-any.whl (28 kB)
Requirement already satisfied: tqdm in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from insightface==0.7.3) (4.66.2)
Collecting cython
  Using cached Cython-3.0.10-cp310-cp310-win_amd64.whl (2.8 MB)
Requirement already satisfied: matplotlib in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from insightface==0.7.3) (3.8.4)
Requirement already satisfied: numpy in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from insightface==0.7.3) (1.26.2)
Requirement already satisfied: scikit-image in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from insightface==0.7.3) (0.21.0)
Collecting onnx
  Using cached onnx-1.16.0-cp310-cp310-win_amd64.whl (14.4 MB)
Collecting scikit-learn
  Using cached scikit_learn-1.4.2-cp310-cp310-win_amd64.whl (10.6 MB)
Requirement already satisfied: Pillow in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from insightface==0.7.3) (9.5.0)
Requirement already satisfied: scipy in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from insightface==0.7.3) (1.13.0)
Collecting albumentations
  Using cached albumentations-1.4.4-py3-none-any.whl (150 kB)
Requirement already satisfied: requests in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from insightface==0.7.3) (2.31.0)
Collecting pydantic>=2.6.4
  Using cached pydantic-2.7.0-py3-none-any.whl (407 kB)
Requirement already satisfied: PyYAML in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Requirement already satisfied: opencv-python-headless>=4.9.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (4.9.0.80)
Requirement already satisfied: typing-extensions>=4.9.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (4.11.0)
Requirement already satisfied: lazy_loader>=0.2 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (0.4)
Requirement already satisfied: packaging>=21 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (24.0)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.6.0)
Requirement already satisfied: tifffile>=2022.8.12 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2024.2.12)
Requirement already satisfied: networkx>=2.8 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.3)
Requirement already satisfied: imageio>=2.27 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.34.0)
Collecting joblib>=1.2.0
  Using cached joblib-1.4.0-py3-none-any.whl (301 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.4.0-py3-none-any.whl (17 kB)
Requirement already satisfied: cycler>=0.10 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.9.0.post0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.2)
Collecting protobuf>=3.20.2
  Using cached protobuf-5.26.1-cp310-abi3-win_amd64.whl (420 kB)
Requirement already satisfied: wcwidth in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2024.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: colorama in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Collecting annotated-types>=0.4.0
  Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Collecting pydantic-core==2.18.1
  Using cached pydantic_core-2.18.1-cp310-none-win_amd64.whl (1.9 MB)
Requirement already satisfied: six>=1.5 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Installing collected packages: easydict, threadpoolctl, pydantic-core, protobuf, prettytable, joblib, cython, annotated-types, scikit-learn, pydantic, onnx, albumentations, insightface
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.15
    Uninstalling pydantic-1.10.15:
      Successfully uninstalled pydantic-1.10.15

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\user\\Desktop\\webuiclean\\webui\\venv\\Lib\\site-packages\\~ydantic\\annotated_types.cp310-win_amd64.pyd'
Check the permissions.


[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: C:\Users\user\Desktop\webuiclean\webui\venv\Scripts\python.exe -m pip install --upgrade pip

ControlNet init warning: Unable to install insightface automatically.
Installing sd-webui-controlnet requirement: handrefinerportable
Couldn't install sd-webui-controlnet requirement: handrefinerportable.
Command: "C:\Users\user\Desktop\webuiclean\webui\venv\Scripts\python.exe" -m pip install -U https://github.com/huchenlei/HandRefinerPortable/releases/download/v1.0.1/handrefinerportable-2024.2.12.0-py2.py3-none-any.whl --prefer-binary
Error code: 1
stdout: Collecting handrefinerportable==2024.2.12.0
  Downloading https://github.com/huchenlei/HandRefinerPortable/releases/download/v1.0.1/handrefinerportable-2024.2.12.0-py2.py3-none-any.whl (13.1 MB)
     --------------------------------------- 13.1/13.1 MB 93.8 MB/s eta 0:00:00
Collecting trimesh[easy]
  Using cached trimesh-4.3.1-py3-none-any.whl (693 kB)
Collecting rtree
  Using cached Rtree-1.2.0-py3-none-win_amd64.whl (481 kB)
Collecting mediapipe
  Using cached mediapipe-0.10.11-cp310-cp310-win_amd64.whl (50.8 MB)
Collecting absl-py
  Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
Collecting opencv-contrib-python
  Using cached opencv_contrib_python-4.9.0.80-cp37-abi3-win_amd64.whl (45.3 MB)
Collecting protobuf<4,>=3.11
  Using cached protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
Requirement already satisfied: matplotlib in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from mediapipe->handrefinerportable==2024.2.12.0) (3.8.4)
Collecting jax
  Using cached jax-0.4.26-py3-none-any.whl (1.9 MB)
Collecting sounddevice>=0.4.4
  Using cached sounddevice-0.4.6-py3-none-win_amd64.whl (199 kB)
Requirement already satisfied: numpy in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from mediapipe->handrefinerportable==2024.2.12.0) (1.26.2)
Requirement already satisfied: attrs>=19.1.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from mediapipe->handrefinerportable==2024.2.12.0) (23.2.0)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from mediapipe->handrefinerportable==2024.2.12.0) (24.3.25)
Collecting xatlas
  Using cached xatlas-0.0.9-cp310-cp310-win_amd64.whl (193 kB)
Requirement already satisfied: lxml in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from trimesh[easy]->handrefinerportable==2024.2.12.0) (5.2.1)
Collecting vhacdx
  Using cached vhacdx-0.0.6-cp310-cp310-win_amd64.whl (127 kB)
Requirement already satisfied: setuptools in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from trimesh[easy]->handrefinerportable==2024.2.12.0) (63.2.0)
Requirement already satisfied: pillow in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from trimesh[easy]->handrefinerportable==2024.2.12.0) (9.5.0)
Collecting xxhash
  Using cached xxhash-3.4.1-cp310-cp310-win_amd64.whl (29 kB)
Collecting colorlog
  Using cached colorlog-6.8.2-py3-none-any.whl (11 kB)
Collecting shapely
  Using cached shapely-2.0.4-cp310-cp310-win_amd64.whl (1.4 MB)
Collecting svg.path
  Using cached svg.path-6.3-py2.py3-none-any.whl (16 kB)
Collecting pycollada
  Using cached pycollada-0.8-py3-none-any.whl
Requirement already satisfied: httpx in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from trimesh[easy]->handrefinerportable==2024.2.12.0) (0.24.1)
Requirement already satisfied: scipy in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from trimesh[easy]->handrefinerportable==2024.2.12.0) (1.13.0)
Requirement already satisfied: jsonschema in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from trimesh[easy]->handrefinerportable==2024.2.12.0) (4.21.1)
Collecting embreex
  Using cached embreex-2.17.7.post4-cp310-cp310-win_amd64.whl (13.4 MB)
Requirement already satisfied: networkx in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from trimesh[easy]->handrefinerportable==2024.2.12.0) (3.3)
Collecting mapbox-earcut
  Using cached mapbox_earcut-1.0.1-cp310-cp310-win_amd64.whl (71 kB)
Requirement already satisfied: chardet in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from trimesh[easy]->handrefinerportable==2024.2.12.0) (5.2.0)
Collecting CFFI>=1.0
  Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl (181 kB)
Requirement already satisfied: colorama in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from colorlog->trimesh[easy]->handrefinerportable==2024.2.12.0) (0.4.6)
Requirement already satisfied: sniffio in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from httpx->trimesh[easy]->handrefinerportable==2024.2.12.0) (1.3.1)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from httpx->trimesh[easy]->handrefinerportable==2024.2.12.0) (0.15.0)
Requirement already satisfied: idna in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from httpx->trimesh[easy]->handrefinerportable==2024.2.12.0) (3.7)
Requirement already satisfied: certifi in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from httpx->trimesh[easy]->handrefinerportable==2024.2.12.0) (2024.2.2)
Collecting ml-dtypes>=0.2.0
  Using cached ml_dtypes-0.4.0-cp310-cp310-win_amd64.whl (126 kB)
Requirement already satisfied: opt-einsum in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from jax->mediapipe->handrefinerportable==2024.2.12.0) (3.3.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from jsonschema->trimesh[easy]->handrefinerportable==2024.2.12.0) (0.18.0)
Requirement already satisfied: referencing>=0.28.4 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from jsonschema->trimesh[easy]->handrefinerportable==2024.2.12.0) (0.34.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from jsonschema->trimesh[easy]->handrefinerportable==2024.2.12.0) (2023.12.1)
Requirement already satisfied: packaging>=20.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe->handrefinerportable==2024.2.12.0) (24.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe->handrefinerportable==2024.2.12.0) (3.1.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe->handrefinerportable==2024.2.12.0) (1.4.5)
Requirement already satisfied: cycler>=0.10 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe->handrefinerportable==2024.2.12.0) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe->handrefinerportable==2024.2.12.0) (1.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe->handrefinerportable==2024.2.12.0) (2.9.0.post0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from matplotlib->mediapipe->handrefinerportable==2024.2.12.0) (4.51.0)
Requirement already satisfied: pycparser in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe->handrefinerportable==2024.2.12.0) (2.22)
Requirement already satisfied: anyio==3.* in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->trimesh[easy]->handrefinerportable==2024.2.12.0) (3.7.1)
Requirement already satisfied: h11<0.13,>=0.11 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->trimesh[easy]->handrefinerportable==2024.2.12.0) (0.12.0)
Requirement already satisfied: exceptiongroup in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from anyio==3.*->httpcore<0.18.0,>=0.15.0->httpx->trimesh[easy]->handrefinerportable==2024.2.12.0) (1.2.0)
Requirement already satisfied: six>=1.5 in c:\users\user\desktop\webuiclean\webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe->handrefinerportable==2024.2.12.0) (1.16.0)
Installing collected packages: xxhash, xatlas, vhacdx, trimesh, svg.path, shapely, rtree, protobuf, opencv-contrib-python, ml-dtypes, mapbox-earcut, embreex, colorlog, CFFI, absl-py, sounddevice, pycollada, jax, mediapipe, handrefinerportable
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.26.1
    Uninstalling protobuf-5.26.1:
      Successfully uninstalled protobuf-5.26.1

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\user\\Desktop\\webuiclean\\webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.


[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: C:\Users\user\Desktop\webuiclean\webui\venv\Scripts\python.exe -m pip install --upgrade pip

Warning: Failed to install handrefinerportable. Some processors will not work.
Installing sd-webui-controlnet requirement: depth_anything
Installing sd-webui-controlnet requirement: dsine
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.0
Commit hash: adadb4e3c7382bf3e4f7519126cd6c70f4f8557b
Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: insightface
Installing sd-webui-controlnet requirement: handrefinerportable
Launching Web UI with arguments: --xformers
Traceback (most recent call last):
  File "C:\Users\user\Desktop\webuiclean\webui\launch.py", line 48, in <module>
    main()
  File "C:\Users\user\Desktop\webuiclean\webui\launch.py", line 44, in main
    start()
  File "C:\Users\user\Desktop\webuiclean\webui\modules\launch_utils.py", line 465, in start
    import webui
  File "C:\Users\user\Desktop\webuiclean\webui\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\user\Desktop\webuiclean\webui\modules\initialize.py", line 23, in imports
    import gradio  # noqa: F401
  File "C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (C:\Users\user\Desktop\webuiclean\webui\venv\lib\site-packages\pydantic\fields.py)
Press any key to continue . . .
```

**Comment by huchenlei** [comment]
Please report that in main A1111 repo. ControlNet does not have explicit dependency on pydantic. It seems like pydantic is uninstalled from your log message due to OSError:

```
Installing collected packages: easydict, threadpoolctl, pydantic-core, protobuf, prettytable, joblib, cython, annotated-types, scikit-learn, pydantic, onnx, albumentations, insightface
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.15
    Uninstalling pydantic-1.10.15:
      Successfully uninstalled pydantic-1.10.15

stderr: ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\user\\Desktop\\webuiclean\\webui\\venv\\Lib\\site-packages\\~ydantic\\annotated_types.cp310-win_amd64.pyd'
Check the permissions.
```
