### ISSUE TITLE
The control net 1.1.444 dw_openpose_full has a preview error and cannot be used.

### ISSUE THREAD

**Issue by 2norang** [Mikubill/sd-webui-controlnet#2794]
The controlnet 1.1.444 dw_openpose_full has a preview error and cannot be used.

Other options for open poses, such as Animal Pose, etc., are not available due to errors in the same phenomenon.

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/167536637/89e15a3b-bee5-4865-91f9-aa5b3cc2ccec)

2024-04-22 23:41:46,054 - ControlNet - INFO - Preview Resolution = 512
Traceback (most recent call last):
  File "C:\Users\이노랑\Desktop\sd.webui\webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\이노랑\Desktop\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\이노랑\Desktop\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\이노랑\Desktop\sd.webui\webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\이노랑\Desktop\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\이노랑\Desktop\sd.webui\webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\이노랑\Desktop\sd.webui\webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 939, in run_annotator
    result = preprocessor.cached_call(
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\utils.py", line 81, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\utils.py", line 65, in cached_func
    return func(*args, **kwargs)
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 170, in cached_call
    return self(*args, **kwargs)
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 97, in __call__
    result, is_image = self.call_function(
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 274, in run_model
    return remove_pad(self.model_openpose(
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 445, in __call__
    poses = self.detect_poses_dw(oriImg)
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 392, in detect_poses_dw
    self.load_dw_model()
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 237, in load_dw_model
    self.dw_pose_estimation = Wholebody(onnx_det, onnx_pose)
  File "C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\annotator\openpose\wholebody.py", line 20, in __init__
    self.session_det = cv2.dnn.readNetFromONNX(onnx_det)
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:275: error: (-5:Bad argument) Can't read ONNX file: C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\annotator\downloads\openpose\yolox_l.onnx in function 'cv::dnn::dnn4_v20231225::ONNXImporter::ONNXImporter'

_Originally posted by @2norang in https://github.com/Mikubill/sd-webui-controlnet/discussions/2760#discussioncomment-9189933_

**Comment by huchenlei** [comment]
https://github.com/opencv/opencv/issues/22664

You might want to check if the file exist?

**Comment by 2norang** [comment]
Yes, I would like to find out any way as long as it is resolved.

**Comment by 2norang** [comment]
self.session_det = cv2.dnn.readNetFromONNX(onnx_det)
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:275: error: (-5:Bad argument) Can't read ONNX file: C:\Users\이노랑\Desktop\sd.webui\webui\extensions\sd-webui-controlnet\annotator\downloads\openpose\yolox_l.onnx in function 'cv::dnn::dnn4_v20231225::ONNXImporter::ONNXImporter'

**Comment by 2norang** [comment]
I don't know if it's the right way
I cancelled sync to Windows OneDrive, moved it to desktop, and it worked fine.
