### ISSUE TITLE
Error in loading state_dict for Adapter

### ISSUE THREAD

**Issue by z14git** [Mikubill/sd-webui-controlnet#281]
```
Loading preprocessor: segmentation, model: t2iadapter_seg_sd14v1 [6387afb5]
Loaded state_dict from [F:\stable_diffusion_webui\extensions\sd-webui-controlnet\models\t2iadapter_seg_sd14v1.pth]
Error running process: F:\stable_diffusion_webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\stable_diffusion_webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "F:\stable_diffusion_webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 477, in process
    network = network_module(
  File "F:\stable_diffusion_webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 65, in __init__
    self.control_model.load_state_dict(state_dict)
  File "F:\stable_diffusion_webui\py310\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Adapter:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 64, 3, 3]).
```

**Comment by Raivshard** [comment]
I'm getting the same error

**Comment by Mikubill** [comment]
change adapter config file in settings to `image/sketch..yaml`

**Comment by Piscabo** [comment]
> change adapter config file in settings to `image/sketch..yaml`
I'm not sure what this means. Can you give an exact description of what the entry must be? PLS.
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/123719842/c3c5812b-c5b9-4cb0-9150-a83e29a0e51c)

I Have the same error that starts with:
Error running process: C:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\AI_Files\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "C:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1036, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "C:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 699, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "C:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 779, in build_control_model
    network = network_module(
  File "C:\AI_Files\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 91, in __init__
    self.control_model.load_state_dict(state_dict)
  File "C:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ControlNet:
