### ISSUE TITLE
[Bug]: Instant ID not working

### ISSUE THREAD

**Issue by AlfaShot111** [Mikubill/sd-webui-controlnet#2827]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Forged SD version. TxtToImg. Generation don`t use Instant ID controlnet. Other controlnets are used correctly.

### Steps to reproduce the problem

Settings scrinshot:
![2024-04-30_161522](https://github.com/Mikubill/sd-webui-controlnet/assets/164072895/ff3251f4-30d0-4e76-82bb-06c045219896)

### What should have happened?

Generation with my face

### Commit where the problem happens

webui: yes
controlnet: yes

### Command Line Arguments

```Shell
No
```

### List of enabled extensions

![2024-04-30_161714](https://github.com/Mikubill/sd-webui-controlnet/assets/164072895/6ed3f0c9-f95e-48f6-9112-db50aad880c2)

### Console logs

```Shell
*** Error running postprocess_batch_list: /workspace/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/workspace/stable-diffusion-webui-forge/modules/scripts.py", line 859, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "/workspace/venvs/stable-diffusion-webui-forge/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/workspace/stable-diffusion-webui-forge/extensions-builtin/sd_forge_controlnet/scripts/controlnet.py", line 561, in postprocess_batch_list
        self.process_unit_after_every_sampling(p, unit, self.current_params[i], pp, *args, **kwargs)
    KeyError: 0
![2024-04-30_161007](https://github.com/Mikubill/sd-webui-controlnet/assets/164072895/eb48d6ef-4171-4d54-8ed8-5e494c9b3594)
```

**Comment by huchenlei** [comment]
Wrong repo. Please file the issue in forge repo: https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by AlfaShot111** [comment]
> Wrong repo. Please file the issue in forge repo: https://github.com/lllyasviel/stable-diffusion-webui-forge

Reinstalled automatic1111 from lllyasviel like you said. Even in plain version of stable-diffusion-webui-forge still same error

*** Error running process_before_every_sampling: C:\Stable Diffusion\Manual install\webui_forge_lllyasviel\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\Manual install\webui_forge_lllyasviel\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\Stable Diffusion\Manual install\webui_forge_lllyasviel\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Stable Diffusion\Manual install\webui_forge_lllyasviel\webui\extensions-builtin\sd_forge_controlnet\scripts\controlnet.py", line 555, in process_before_every_sampling
        self.process_unit_before_every_sampling(p, unit, self.current_params[i], *args, **kwargs)
    KeyError: 0

> Wrong repo. Please file the issue in forge repo: https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by huchenlei** [comment]
I am saying that you should file the issue in forge repo, because forge does not run on code in this repo. This repo is not compatible with SD Forge.

**Comment by AlfaShot111** [comment]
> I am saying that you should file the issue in forge repo, because forge does not run on code in this repo. This repo is not compatible with SD Forge.

Thanks for answer. I don`t get what you mean :(
Could you explain please, what should I do?

I execute run.bat file from stable-diffusion-webui-forge folder. then use controlnet and press generate.

**Comment by AlfaShot111** [comment]
I tried to install not forge web ui https://github.com/AUTOMATIC1111/stable-diffusion-webui

Same error:
*** Error running process: C:\Stable Diffusion\Manual install\stable-diffusion-webui v2\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\Manual install\stable-diffusion-webui v2\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "C:\Stable Diffusion\Manual install\stable-diffusion-webui v2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1267, in process
        self.controlnet_hack(p)
      File "C:\Stable Diffusion\Manual install\stable-diffusion-webui v2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1252, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Stable Diffusion\Manual install\stable-diffusion-webui v2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 949, in controlnet_main_entry
        Script.check_sd_version_compatible(unit)
      File "C:\Stable Diffusion\Manual install\stable-diffusion-webui v2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 878, in check_sd_version_compatible
        raise Exception(f"ControlNet model {unit.model}({cnet_sd_version}) is not compatible with sd model({sd_version})")
    Exception: ControlNet model ip-adapter_instant_id_sdxl [eb2d3ec0](StableDiffusionVersion.SDXL) is not compatible with sd model(StableDiffusionVersion.SD1x)

**Comment by huchenlei** [comment]
instant ID only works for SDXL right now
