### ISSUE TITLE
[Bug]: File "pydantic/main.py", line 357:  ValueError: "ControlNetUnit" object has no field "batch_mask_dir"

### ISSUE THREAD

**Issue by light-and-ray** [Mikubill/sd-webui-controlnet#2863]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After you added pydantic in the last commits, animatediff batch mask stopped work. As I understand it is caused by this field `batch_mask_dir` is not described in dataclass ControlNetUnit as others. Maybe you should add a dummy `batch_mask_dir: NoneType|str = None` there. None state is used in controlnet code in animatediff file in `getattr` in pair with `is not None` and maybe somewhere else, so "" can't be default

```
*** Error running before_process: /home/user/ai-apps/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/home/user/ai-apps/stable-diffusion-webui/modules/scripts.py", line 817, in before_process
        script.before_process(p, *script_args)
      File "/home/user/ai-apps/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 65, in before_process
        params.set_p(p)
      File "/home/user/ai-apps/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_ui.py", line 186, in set_p
        cn_unit.batch_mask_dir = self.mask_path
        ^^^^^^^^^^^^^^^^^^^^^^
      File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
    ValueError: "ControlNetUnit" object has no field "batch_mask_dir"
```

**Comment by huchenlei** [comment]
I think the better solution is to change ad impl here to `setattr(cn_unit, "batch_mask_dir", self.mask_path)` or just simply inherit ControlNetUnit and add these extra fields.

**Comment by huchenlei** [comment]
I will file
