### ISSUE TITLE
ValueError: "ControlNetUnit" object has no field "animatediff_batch"

### ISSUE THREAD

**Issue by light-and-ray** [Mikubill/sd-webui-controlnet#2869]
There is another field `animatediff_batch`

```
*** Error running before_process: /home/user/ai-apps/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/home/user/ai-apps/stable-diffusion-webui/modules/scripts.py", line 817, in before_process
        script.before_process(p, *script_args)
      File "/home/user/ai-apps/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 65, in before_process
        params.set_p(p)
      File "/home/user/ai-apps/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_ui.py", line 191, in set_p
        cn_unit.animatediff_batch = True # for A1111 sd-webui-controlnet
        ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
    ValueError: "ControlNetUnit" object has no field "animatediff_batch"

```

@huchenlei

_Originally posted by @light-and-ray in https://github.com/Mikubill/sd-webui-controlnet/issues/2863#issuecomment-2099432268_
            
Also I don't think "Backward compatible" is a good comment. It is just compatible

> `# Backward compatible with animatediff impl.`

**Comment by yinghuochong** [comment]
same error
