### ISSUE TITLE
Only normal_map and depth/depth_leres doesn't work

### ISSUE THREAD

**Issue by ChoiDDoSik** [Mikubill/sd-webui-controlnet#287]
When I try other preprocessors, it works. However, no matter how many times I reinstall the controlnet, it gives the same error message.

Loading preprocessor: normal_map
Error running process: D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py", line 547, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\processor.py", line 94, in midas_normal
    _, results  = model_midas(img, a, bg_th)
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\__init__.py", line 31, in apply_midas
    depth = model(image_depth)[0]
  File "D:\SDs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\api.py", line 168, in forward
    prediction = self.model(x)
  File "D:\SDs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\dpt_depth.py", line 108, in forward
    return super().forward(x).squeeze(dim=1)
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\dpt_depth.py", line 71, in forward
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\vit.py", line 59, in forward_vit
    glob = pretrained.model.forward_flex(x)
  File "D:\WSD\Windows_Stable_Diffusion_WebUI_DirectML_Easy-Setup\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\vit.py", line 127, in forward_flex
    x = self.patch_embed.backbone(x)
  File "D:\SDs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SDs\lib\site-packages\timm\models\resnetv2.py", line 447, in forward
    x = self.forward_features(x)
  File "D:\SDs\lib\site-packages\timm\models\resnetv2.py", line 435, in forward_features
    x = self.stem(x)
  File "D:\SDs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SDs\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "D:\SDs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\SDs\lib\site-packages\timm\models\layers\std_conv.py", line 69, in forward
    weight = F.batch_norm(
  File "D:\SDs\lib\site-packages\torch\nn\functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: shape '[1, 64, 1]' is invalid for input of size 0

Just in case, I'm using RX6800XT in Windows11 by DirectML

**Comment by Mikubill** [comment]
Maybe something like input image issue?

**Comment by ChoiDDoSik** [comment]
The input image was 427*447 png image. Other preprocessors such as openpose worked fine for the same image.

**Comment by Holyniwa** [comment]
is it me, or has the newest update broke mapping? i cant seem to recreate poses at all doing the same strategies. both in openpose and in normalmaps.

**Comment by t4ggno** [comment]
I have the same error using a AMD RX6700XT (12GB) with A1111-DirectML on Windows 11 and 64 GB RAM.
Like @ChoiDDoSik said, all other preprocessors are working fine. But even an image with resolution 512x512 will throw that error. Could be a problem with DirectML?!

**Comment by jack-devilgod** [comment]
openpose, depth and normal also doesn't work me. I get this message every single time. it gives an error on depth and normal. on openpose just a black image with no skeleton. 5800x, 6600 xt, win 10, web ui directml

Traceback (most recent call last):
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py", line 455, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\processor.py", line 84, in midas
    results, _ = model_midas(img, a)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\__init__.py", line 31, in apply_midas
    depth = model(image_depth)[0]
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\api.py", line 179, in forward
    prediction = self.model(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\dpt_depth.py", line 108, in forward
    return super().forward(x).squeeze(dim=1)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\dpt_depth.py", line 71, in forward
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\vit.py", line 59, in forward_vit
    glob = pretrained.model.forward_flex(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\vit.py", line 127, in forward_flex
    x = self.patch_embed.backbone(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\timm\models\resnetv2.py", line 447, in forward
    x = self.forward_features(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\timm\models\resnetv2.py", line 435, in forward_features
    x = self.stem(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\timm\models\layers\std_conv.py", line 69, in forward
    weight = F.batch_norm(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: shape '[1, 64, 1]' is invalid for input of size 0
Traceback (most recent call last):
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py", line 455, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\processor.py", line 84, in midas
    results, _ = model_midas(img, a)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\__init__.py", line 31, in apply_midas
    depth = model(image_depth)[0]
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\api.py", line 179, in forward
    prediction = self.model(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\dpt_depth.py", line 108, in forward
    return super().forward(x).squeeze(dim=1)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\dpt_depth.py", line 71, in forward
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\vit.py", line 59, in forward_vit
    glob = pretrained.model.forward_flex(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\midas\midas\vit.py", line 127, in forward_flex
    x = self.patch_embed.backbone(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\timm\models\resnetv2.py", line 447, in forward
    x = self.forward_features(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\timm\models\resnetv2.py", line 435, in forward_features
    x = self.stem(x)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\timm\models\layers\std_conv.py", line 69, in forward
    weight = F.batch_norm(
  File "C:\Users\jackj\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: shape '[1, 64, 1]' is invalid for input of size 0
