### ISSUE TITLE
[Bug]: ip adapter faceid不能使用

### ISSUE THREAD

**Issue by identify86** [Mikubill/sd-webui-controlnet#2899]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

when i try to use control net

preprocessor “ip-adapter-auto” model "ip-adapter-faceid-plusv2_sd15", i got thie bug

ImportError: cannot import name 'libsvm' from partially initialized module 'sklearn.svm' (most likely due to a circular import) (F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\svm_init.py)

### Steps to reproduce the problem

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/156264998/64a7e8e3-4658-47d4-848e-894c5aa5cbed)

### What should have happened?

采纳参考图

### Commit where the problem happens

webui: 1c0a0c4
controlnet:  v1.1.448

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
否
```

### List of enabled extensions

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/156264998/a29676b2-92dd-49ef-bb76-b83b36f744e9)

### Console logs

```Shell
2024-05-17 14:39:57,369 - ControlNet - INFO - unit_separate = False, style_align = False
2024-05-17 14:39:57,375 - ControlNet - INFO - Loading model: ip-adapter-faceid-plusv2_sd15 [6e14fc1a]
2024-05-17 14:39:57,571 - ControlNet - INFO - Loaded state_dict from [F:\sd-webui-aki-v4.1\models\ControlNet\ip-adapter-faceid-plusv2_sd15.bin]
2024-05-17 14:39:57,994 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plusv2_sd15 [6e14fc1a](ControlModelType.IPAdapter) loaded.
2024-05-17 14:39:57,998 - ControlNet - INFO - Using preprocessor: ip-adapter-auto
2024-05-17 14:39:57,998 - ControlNet - INFO - preprocessor resolution = 512
2024-05-17 14:39:58,000 - ControlNet - INFO - ip-adapter-auto => ip-adapter_face_id_plus
*** Error running process: F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki-v4.1\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1215, in process
        self.controlnet_hack(p)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1200, in controlnet_hack
        self.controlnet_main_entry(p)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 934, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in get_control
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\controlnet.py", line 242, in preprocess_input_image
        result = preprocessor.cached_call(
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 206, in cached_call
        result = self._cached_call(input_image, *args, **kwargs)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\utils.py", line 82, in decorated_func
        return cached_func(*args, **kwargs)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\utils.py", line 66, in cached_func
        return func(*args, **kwargs)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 219, in _cached_call
        return self(*args, **kwargs)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\preprocessor\ip_adapter_auto.py", line 25, in __call__
        return p(*args, **kwargs)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 105, in __call__
        result, is_image = self.call_function(
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 764, in face_id_plus
        face_embed, _ = g_insight_face_model.run_model(img)
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 692, in run_model
        self.load_model()
      File "F:\sd-webui-aki-v4.1\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 682, in load_model
        from insightface.app import FaceAnalysis
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\insightface\__init__.py", line 18, in <module>
        from . import app
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
        from .mask_renderer import *
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
        import albumentations as A
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\albumentations\__init__.py", line 3, in <module>
        from .augmentations import *
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\albumentations\augmentations\__init__.py", line 5, in <module>
        from .domain_adaptation import *
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 7, in <module>
        from albumentations.augmentations.domain_adaptation_functional import (
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\albumentations\augmentations\domain_adaptation_functional.py", line 8, in <module>
        from sklearn.decomposition import PCA
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\decomposition\__init__.py", line 9, in <module>
        from ._dict_learning import (
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\decomposition\_dict_learning.py", line 22, in <module>
        from ..linear_model import Lars, Lasso, LassoLars, orthogonal_mp_gram
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\linear_model\__init__.py", line 34, in <module>
        from ._logistic import LogisticRegression, LogisticRegressionCV
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\linear_model\_logistic.py", line 28, in <module>
        from ..svm._base import _fit_liblinear
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\svm\__init__.py", line 14, in <module>
        from ._classes import SVC, SVR, LinearSVC, LinearSVR, NuSVC, NuSVR, OneClassSVM
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\svm\_classes.py", line 11, in <module>
        from ._base import BaseLibSVM, BaseSVC, _fit_liblinear, _get_liblinear_solver_type
      File "F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\svm\_base.py", line 27, in <module>
        from . import _libsvm as libsvm  # type: ignore
    ImportError: cannot import name '_libsvm' from partially initialized module 'sklearn.svm' (most likely due to a circular import) (F:\sd-webui-aki-v4.1\python\lib\site-packages\sklearn\svm\__init__.py)
```

**Comment by huchenlei** [comment]
It seems like insightface's deps are not properly instsalled. You can try re-install insightface library. There is nothing we can do in this repo to resolve this issue.
