### ISSUE TITLE
get error:RuntimeError: unexpected EOF, expected 4946769 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by greengerong** [Mikubill/sd-webui-controlnet#2928]
get error:
```
Error running process: /mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/mnt/d/project/stable-diffusion-webui/modules/scripts.py", line 825, in process
        script.process(p, *script_args)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1222, in process
        self.controlnet_hack(p)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1207, in controlnet_hack
        self.controlnet_main_entry(p)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 941, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 290, in get_control
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 290, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 242, in preprocess_input_image
        result = preprocessor.cached_call(
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/supported_preprocessor.py", line 196, in cached_call
        result = self._cached_call(input_image, *args, **kwargs)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 82, in decorated_func
        return cached_func(*args, **kwargs)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 66, in cached_func
        return func(*args, **kwargs)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/supported_preprocessor.py", line 209, in _cached_call
        return self(*args, **kwargs)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/ip_adapter_auto.py", line 25, in __call__
        return p(*args, **kwargs)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/pulid.py", line 152, in __call__
        face_features_image = self.facexlib_detect(input_image)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/pulid.py", line 122, in facexlib_detect
        return facexlib_preprocessor(input_image, return_tensor=True)
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/pulid.py", line 70, in __call__
        self.load_model()
      File "/mnt/d/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/pulid.py", line 32, in load_model
        self.model = FaceRestoreHelper(
      File "/mnt/d/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/facexlib/utils/face_restoration_helper.py", line 99, in __init__
        self.face_det = init_detection_model(det_model, half=False, device=self.device, model_rootpath=model_rootpath)
      File "/mnt/d/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/facexlib/detection/__init__.py", line 22, in init_detection_model
        load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
      File "/mnt/d/project/stable-diffusion-webui/modules/safe.py", line 108, in load
        return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
      File "/mnt/d/project/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
        return unsafe_torch_load(filename, *args, **kwargs)
      File "/mnt/d/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
        return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
      File "/mnt/d/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/serialization.py", line 1051, in _legacy_load
        typed_storage._untyped_storage._set_from_file(
    RuntimeError: unexpected EOF, expected 4946769 more bytes. The file might be corrupted.
```

config:

![image](https://github.com/Mikubill/sd-webui-controlnet/assets/2569893/408b4c2f-e359-4052-ba0d-fbb83c307640)

How to fix it?

_Originally posted by @greengerong in https://github.com/Mikubill/sd-webui-controlnet/discussions/2841#discussioncomment-9524285_

**Comment by huchenlei** [comment]
You likely downloaded a corrupted file. Please redownload the model following instruction in model download page. https://github.com/Mikubill/sd-webui-controlnet/wiki/Model-download#installation

**Comment by greengerong** [comment]
> You likely downloaded a corrupted file. Please redownload the model following instruction in model download page. https://github.com/Mikubill/sd-webui-controlnet/wiki/Model-download#installation

It work fine with controlnet model  except PuLID. But there are no more details about the model details about controlnet-evaclip, just say: "A1111 this gets downloaded and installed by itself when running pulid for the first time.". I suspect this model download problem. 

Thanks
