### ISSUE TITLE
Depth Leres preprocessor is not working in a multi gpu environment

### ISSUE THREAD

**Issue by bigahega** [Mikubill/sd-webui-controlnet#293]
Depth leres Preprocessor fails with the following error:

```
Traceback (most recent call last):
  File "/app/modules/scripts.py", line 387, in process
    script.process(p, *script_args)
  File "/app/extensions/sd-webui-controlnet/scripts/controlnet.py", line 547, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "/app/extensions/sd-webui-controlnet/scripts/processor.py", line 111, in leres
    results = model_leres(img, thr_a, thr_b)
  File "/app/extensions/sd-webui-controlnet/annotator/leres/__init__.py", line 76, in apply_leres
    depth = estimateleres(input_image, model, width, height)
  File "/app/extensions/sd-webui-controlnet/annotator/leres/leres/depthmap.py", line 44, in estimateleres
    prediction = model.depth_model(img_torch)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/extensions/sd-webui-controlnet/annotator/leres/leres/multi_depth_model_woauxi.py", line 31, in forward
    lateral_out = self.encoder_modules(x)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/extensions/sd-webui-controlnet/annotator/leres/leres/network_auxi.py", line 96, in forward
    x = self.encoder(x)  # 1/32, 1/16, 1/8, 1/4
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/extensions/sd-webui-controlnet/annotator/leres/leres/Resnext_torch.py", line 223, in forward
    return self._forward_impl(x)
  File "/app/extensions/sd-webui-controlnet/annotator/leres/leres/Resnext_torch.py", line 199, in _forward_impl
    x = self.conv1(x)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/app/extensions-builtin/Lora/lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper__cudnn_convolution)
```

Not sure if leres supports selecting a specific device but I am launching webui with --device-id so if there is a possbility, it should be passed to leres as well.

**Comment by Mikubill** [comment]
Added some fix, it should work after update. 
(currently no multi-gpu env to test)

**Comment by bigahega** [comment]
It is working now, thanks!
