### ISSUE TITLE
XYZ grid support unexpected keyword argument 'choices'                         it's back

### ISSUE THREAD

**Issue by zaapas** [Mikubill/sd-webui-controlnet#2976]
2024-07-03 18:46:22,204 - ControlNet - INFO - ControlNet v1.1.449

*** Error loading script: xyz_grid_support.py
    Traceback (most recent call last):
      File "D:\stable-diffusion\stable-diffusion-webui-master\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 451, in <module>
        run()
      File "D:\stable-diffusion\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 445, in run
        add_axis_options(xyz_grid)
      File "D:\stable-diffusion\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 426, in add_axis_options
        xyz_grid.AxisOption("[ControlNet] Enabled", identity, apply_field("control_net_enabled"), confirm=confirm(bool_), choices=choices_bool),
    TypeError: AxisOption.__new__() got an unexpected keyword argument 'choices'

**Comment by Farkandro** [comment]
were you able to solve it? The same happens to me

**Comment by zaapas** [comment]
> were you able to solve it? The same happens to me

Nope. I had to reinstall Sd to a new directory and download all my extensions again. backing them up caused the same problem. probably the fault of an old file that didn't get deleted with the updates for some reason. Try deleting XY_grid. in scripts if you still have it. It worked for me when I first had this error
