### ISSUE TITLE
Error running process

### ISSUE THREAD

**Issue by cibernicola** [Mikubill/sd-webui-controlnet#299]
I've updated everything (all extensions, WebUI, etc..) and now it breaks :(

`ControlNet model control_openpose-fp16 [9ca67cc5] loaded.
Error running process: L:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "L:\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "L:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 532, in process
    model_net.reset()
  File "L:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PlugableControlModel' object has no attribute 'reset'`

Any suggestion? :S

**Comment by Mikubill** [comment]
The latest update requires fully restart WebUI.

**Comment by cibernicola** [comment]
Well, with the latest update (after my post), its working again :)
