### ISSUE TITLE
Error running process: extensions\sd-webui-controlnet\scripts\controlnet.py

### ISSUE THREAD

**Issue by lizabroaden** [Mikubill/sd-webui-controlnet#301]
Installed via link, reinstalled from extensions tab. Everything is showing but not working.
When starting a generation, getting this error:

Loading model: control_sd15_canny [fef5e48e]
Loaded state_dict from [E:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_sd15_canny.pth]
Error running process: E:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 327, in process
    script.process(p, *script_args)
  File "E:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 530, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "E:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 438, in build_control_model
    network = network_module(
  File "E:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 109, in __init__
    self.control_model.to(devices.get_device_for("controlnet"))
AttributeError: module 'modules.devices' has no attribute 'get_device_for'

*not tech savvy at all, but good at following orders. any help would be much appreciated!*

**Comment by Mikubill** [comment]
Update your WebUI will fix this

**Comment by lizabroaden** [comment]
when I launch it shows:

E:\stable-diffusion\stable-diffusion-webui>git pull
error: Your local changes to the following files would be overwritten by merge:
        launch.py
Please commit your changes or stash them before you merge.
Aborting
Updating 5cd5a672..0cc0ee1b

is that why it can't update? how do I fix this?

**Comment by mindfu23** [comment]
My UI is freshly updated, reloaded everything and started over, and this is still ocurring for me? 

Mac, Silicon M2 processor.

**Comment by ChrisYangTW** [comment]
> My UI is freshly updated, reloaded everything and started over, and this is still ocurring for me?

Also has <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]> ?
try to open the python folder (ex: /Applications/Python 3.x) and run the "Install Certificates.command" file.

**Comment by JamesLogan2KB** [comment]
> Update your WebUI will fix this

No, it. Doesn't I have updated my webui to latest version and it has not fixed that.

**Comment by JamesLogan2KB** [comment]
Did you manage to fix this?

**Comment by yzufardiansyah** [comment]
> Did you manage to fix this?

you have fix it now? i have same problem

**Comment by UIME** [comment]
Same

**Comment by guishade** [comment]
2023-10-08 02:50:48,554 - ControlNet - INFO - Loading model: control_sd15_depth [e3b0c442]
*** Error running process: D:\sd16\stable-diffusion-webui-1.6.0\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\sd16\stable-diffusion-webui-1.6.0\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\sd16\stable-diffusion-webui-1.6.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 977, in process
        self.controlnet_hack(p)
      File "D:\sd16\stable-diffusion-webui-1.6.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 966, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\sd16\stable-diffusion-webui-1.6.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 688, in controlnet_main_entry
        model_net = Script.load_control_model(p, unet, unit.model)
      File "D:\sd16\stable-diffusion-webui-1.6.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 321, in load_control_model
        model_net = Script.build_control_model(p, unet, model)
      File "D:\sd16\stable-diffusion-webui-1.6.0\extensions\sd-webui-controlnet\scripts\controlnet.py", line 349, in build_control_model
        state_dict = load_state_dict(model_path)
      File "D:\sd16\stable-diffusion-webui-1.6.0\extensions\sd-webui-controlnet\scripts\utils.py", line 20, in load_state_dict
        state_dict = unsafe_torch_load(ckpt_path, map_location=torch.device(location))
      File "D:\sd16\stable-diffusion-webui-1.6.0\venv\lib\site-packages\torch\serialization.py", line 815, in load
        return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
      File "D:\sd16\stable-diffusion-webui-1.6.0\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
        magic_number = pickle_module.load(f, **pickle_load_args)
    _pickle.UnpicklingError: invalid load key, '<'.



updated, deactivated all extentions but cn, still getting error
