### ISSUE TITLE
Controlnet installed but not showing up in setting or interface

### ISSUE THREAD

**Issue by ngtt17** [Mikubill/sd-webui-controlnet#3015]
I have installed controlnet following the steps, it also shows the extension installed. But it's not showing up in the interface or the setting column. 

I tried to reload webui and reinstall the extension, but still not appearing. Is there any way I could check what's happening or how to fix this?

**Comment by paboum** [comment]
I get the same issue with the error message in console:

```
ControlNet preprocessor location: ... (redacted)
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File " .../stable-diffusion-webui/modules/scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File " .../stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File " .../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 16, in <module>
        import scripts.preprocessor as preprocessor_init  # noqa
      File " .../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/__init__.py", line 9, in <module>
        from .mobile_sam import *
      File " .../stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/mobile_sam.py", line 1, in <module>
        from annotator.mobile_sam import SamDetector_Aux
      File " .../stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/mobile_sam/__init__.py", line 12, in <module>
        from controlnet_aux import SamDetector
    ModuleNotFoundError: No module named 'controlnet_aux'
```

**Comment by tv-logos** [comment]
I have same issue on Runpod

Edit:
Fixed! By using these commands and then restarting the pod.

```
rm -rf /workspace/venvs/a1111
rm /workspace/stable-diffusion-webui/template.json
```

**Comment by lebakerino** [comment]
Same issue here, how has there not been a solid solution for this in almost 2 months? I can't remember specifically where the error started for me other than having decided to update my Forge and Reforge last month when Flux became available and from some point since around then controlnet hasn't been showing up. (both inbuilt versions and seperate extension)

It is not working in A1111, Forge or Reforge for me, it actively enabled in my A1111 install but won't appear in the actual UI, in Forge and Reforge, it won't stay enabled' in the extension list at all and throws the same error:

"*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "C:\A1111\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\A1111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 101, in <module>
        global_state.update_cn_models()
      File "C:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 76, in update_cn_models
        found = get_all_models(sort_by, filter_by, path)
      File "C:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 43, in get_all_models
        fileinfos = traverse_all_files(path, [])
      File "C:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 27, in traverse_all_files
        f_list = [
      File "C:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 28, in <listcomp>
        (os.path.join(curr_path, entry.name), entry.stat())
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\A1111\\stable-diffusion-webui\\models\\ControlNet\\control_v11e_sd15_ip2p.pth'
"
