### ISSUE TITLE
Depth_anything_v2: No module named 'depth_anything_v2.dpt error

### ISSUE THREAD

**Issue by zthrx** [Mikubill/sd-webui-controlnet#3018]
Hey @MackinationsAi 

I've reinstalled Controlnet plugin but I keep getting this error.

Traceback (most recent call last):
  File "C:\Users\...\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\...\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users...\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\...\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\...\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\...\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\...\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 951, in run_annotator
    result = preprocessor.cached_call(
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 198, in cached_call
    result = self._cached_call(input_image, *args, **kwargs)
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 82, in decorated_func
    return cached_func(*args, **kwargs)
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 66, in cached_func
    return func(*args, **kwargs)
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 211, in _cached_call
    return self(*args, **kwargs)
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 105, in __call__
    result, is_image = self.call_function(
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 200, in depth_anything_v2
    from annotator.depth_anything_v2 import DepthAnythingV2Detector
  File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\depth_anything_v2.py", line 9, in <module>
    from depth_anything_v2.dpt import DepthAnythingV2
ModuleNotFoundError: No module named 'depth_anything_v2.dpt'

Depth_anything, midas etc. works fine

![depth2](https://github.com/user-attachments/assets/1326a9f6-5a0c-44ba-b0b0-3a6c31b07084)
![depth1](https://github.com/user-attachments/assets/2ef6e715-922b-44cf-bce9-bc8eb85df2f6)

Cheers! 

Z

**Comment by MackinationsAi** [comment]
@zthrx try the following. Open up cmd at your main folder - *C:\Users...\stable-diffusion-webui,* input ```venv\scripts\activate``` & hit enter, then run ```pip install https://github.com/MackinationsAi/UDAV2-ControlNet/releases/download/v1.0.0/depth_anything_v2-2024.7.1.0-py2.py3-none-any.whl```. Now go to your *C:\Users...\stable-diffusion-webui\venv\Lib\site-packages* folder & you should see a depth_anything_v2 & depth_anything_v2-2024.7.1.0.dist-info folder, that is where the module named 'depth_anything_v2.dpt' is located. Now that everything is installed correctly you should be able to run the depth_anything_v2 preprocessor! 

Also I noticed that you have depth_anything_v2_vitb_fp32 [c0792524] as your model, which will not work, that model is a preprocessor model & not a controlnet model. You need bdsqlsz_controlllite_xl_depth, diffusers_xl_depth_full, sargezt_xl_depth or one of the other sdxl controlnet depth models for sdxl generations. Or control_v11f1p_sd15_depth for sd_v1.5 generations.

**Comment by zthrx** [comment]
> @zthrx try the following. Open up cmd at your main folder - _C:\Users...\stable-diffusion-webui,_ input `venv\scripts\activate` & hit enter, then run `pip install https://github.com/MackinationsAi/UDAV2-ControlNet/releases/download/v1.0.0/depth_anything_v2-2024.7.1.0-py2.py3-none-any.whl`. Now go to your _C:\Users...\stable-diffusion-webui\venv\Lib\site-packages_ folder & you should see a depth_anything_v2 & depth_anything_v2-2024.7.1.0.dist-info folder, that is where the module named 'depth_anything_v2.dpt' is located. Now that everything is installed correctly you should be able to run the depth_anything_v2 preprocessor!
> 
> Also I noticed that you have depth_anything_v2_vitb_fp32 [c0792524] as your model, which will not work, that model is a preprocessor model & not a controlnet model. You need bdsqlsz_controlllite_xl_depth, diffusers_xl_depth_full, sargezt_xl_depth or one of the other sdxl controlnet depth models for sdxl generations. Or control_v11f1p_sd15_depth for sd_v1.5 generations.

Hey, 

Thank you for the solution. I've done everything you said but still getting the same errors :/

 File "C:\Users\...\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\depth_anything_v2.py", line 9, in <module>
    from depth_anything_v2.dpt import DepthAnythingV2
ModuleNotFoundError: No module named 'depth_anything_v2.dpt'

I just have no idea, I can live without depth_anything_v2 for now, everything else works fine except this one preprocessor 


After all that reinstallation I still do not see depth_anything_v2.dpt' in the depth_anything_v2-2024.7.1.0.dist-info folder


![depth3](https://github.com/user-attachments/assets/61454a1a-0923-40ad-b794-b056a73079b5)


Cheers!

**Comment by zthrx** [comment]
depth 2 folder 
![depth3](https://github.com/user-attachments/assets/30e7c227-0a84-4616-9ba4-3615dfe938b5)

**Comment by zthrx** [comment]
depth 2 folder

![dpt](https://github.com/user-attachments/assets/8502105c-fe01-4840-b07e-0f650fd6711b)

**Comment by MackinationsAi** [comment]
depth_anything_v2.dpt means from depth_anything_v2 folder, script dpt.py. Try copying the depth_anything_v2 folder from site-packages into your ```C:\Users...\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator``` folder that might fix the error.

**Comment by zthrx** [comment]
> depth_anything_v2.dpt means from depth_anything_v2 folder, script dpt.py. Try copying the depth_anything_v2 folder from site-packages into your `C:\Users...\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator` folder that might fix the error.

Hey, 

Tried every combination but no success. Getting same errors :(  (every other preprocessor works fine)

![jj2](https://github.com/user-attachments/assets/f42dda82-c390-470e-9380-fb3747979786)
![jjj](https://github.com/user-attachments/assets/2dc3c846-0cd7-4a22-811b-24a69c5c187e)

**Comment by MackinationsAi** [comment]
I have one more potential fix - [install](https://github.com/MackinationsAi/sd-webui-controlnet/releases/tag/transformers-4.44.1) if this doesn't work then I don't know how to get it working for you unfortunately... :/

**Comment by zthrx** [comment]
> I have one more potential fix - [install](https://github.com/MackinationsAi/sd-webui-controlnet/releases/tag/transformers-4.44.1) if this doesn't work then I don't know how to get it working for you unfortunately... :/

Hey, late reply (holiday mood)

I still can't make it work in controlnet but somehow it all works in "depth" tab 

![obraz](https://github.com/user-attachments/assets/0bd267e7-7bcd-4a63-982f-3385e25473ab)

**Comment by DominikDoom** [comment]
I had the same issue, and after experimenting a bit just put in a print for the imported module.
The result was:
```
<module 'depth_anything_v2' from 'C:\\sd-webui\\extensions\\stable-diffusion-webui-depthmap-script\\depth_anything_v2\\__init__.py'>
```

From this it's obvious that the issue was a namespace conflict with the depthmap script (to which the "Depth" tab in the picture from @zthrx belongs, so it's likely the same issue).

For maintainability reasons, depthmap-script doesn't require the v2 package or install it from a wheel, but instead ships with a full copy of the depth_anything_v2 code in a subfolder (from the looks of it, it's the depth_anything_v2 gradio demo). This has its own \_\_init\_\_.py, causing it to override the reference if it's loaded after controlnet.

Just deleting the whole depth_anything_v2 folder in depthmap-script's install root is enough, after that the import in controlnet references
```
<module 'depth_anything_v2' (<_frozen_importlib_external._NamespaceLoader object at ...>)>
```
(i.e. the one in the venv site-packages) and works as expected.
~It also still works in the Depth tab despite deleting the folder, since the depthmap-script import will just reference the proper package as well.~

Issue in the depthmap-script repo: https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/463

**Comment by zthrx** [comment]
> I had the same issue, and after experimenting a bit just put in a print for the imported module. The result was:
> 
> ```
> <module 'depth_anything_v2' from 'C:\\sd-webui\\extensions\\stable-diffusion-webui-depthmap-script\\depth_anything_v2\\__init__.py'>
> ```
> 
> From this it's obvious that the issue was a namespace conflict with the depthmap script (to which the "Depth" tab in the picture from @zthrx belongs, so it's likely the same issue).
> 
> For maintainability reasons, depthmap-script doesn't require the v2 package or install it from a wheel, but instead ships with a full copy of the depth_anything_v2 code in a subfolder (from the looks of it, it's the depth_anything_v2 gradio demo). This has its own __init__.py, causing it to override the reference if it's loaded after controlnet.
> 
> Just deleting the whole depth_anything_v2 folder in depthmap-script's install root is enough, after that the import in controlnet references
> 
> ```
> <module 'depth_anything_v2' (<_frozen_importlib_external._NamespaceLoader object at ...>)>
> ```
> 
> (i.e. the one in the venv site-packages) and works as expected. It also still works in the Depth tab despite deleting the folder, since the depthmap-script import will just reference the proper package as well.
> 
> Issue in the depthmap-script repo: [thygate/stable-diffusion-webui-depthmap-script#463](https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/463)

Heyooo, You are my hero!

Deleting depth_anything_v2 folder from depthmap script works! so I can use depth_anything_v2 in controlnet 
![d11](https://github.com/user-attachments/assets/6d08cc30-23df-467f-ae87-9de9377d9344)


**but by doing so it breaks my Depth tab plugin :(**

![d12](https://github.com/user-attachments/assets/10320155-b43d-45c9-8f2f-e20bdcd56443)


Temp solution for me is to **keep depth_anything_v2 somewhere** and when needed copy it back to stable-diffusion-webui-depthmap-script. 
Any other solution is welcome :) 

Thank you again for your reply!

**Comment by DominikDoom** [comment]
Ah sorry, looks like I changed something during experimenting without realizing. The same happens to me on a fresh install.
The proposed fix on the depthmap-script issue is just renaming the folder & import, which I can confirm works.

You can either wait for the official fix by them or just do the same manually:
1. Rename the root `depthmap-script/depth_anything_v2` folder to something different, e.g. **d**depth_anything_v2
2. Edit `depthmap-script/src/depthmap_generation.py` and change the import name in line 30 to the same thing:
![image](https://github.com/user-attachments/assets/7d84a602-f913-4550-aac7-aea1edf59075)

That should then work for both.

**Comment by zthrx** [comment]
> Ah sorry, looks like I changed something during experimenting without realizing. The same happens to me on a fresh install. The proposed fix on the depthmap-script issue is just renaming the folder & import, which I can confirm works.
> 
> You can either wait for the official fix by them or just do the same manually:
> 
>     1. Rename the root `depthmap-script/depth_anything_v2` folder to something different, e.g. **d**depth_anything_v2
> 
>     2. Edit `depthmap-script/src/depthmap_generation.py` and change the import name in line 30 to the same thing:
>        ![image](https://private-user-images.githubusercontent.com/34448969/358831129-7d84a602-f913-4550-aac7-aea1edf59075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4ODk0NzEsIm5iZiI6MTcyMzg4OTE3MSwicGF0aCI6Ii8zNDQ0ODk2OS8zNTg4MzExMjktN2Q4NGE2MDItZjkxMy00NTUwLWFhYzctYWVhMWVkZjU5MDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDEwMDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYWNhZGI4YTYyYzM2ZjEwY2RlMGJmYjBlNDg4Yjk5ODA0MjEzZWFlMWViM2M4YWE1YWRiYjliZThjNmY1YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uQnv8dmtuq3FpnPDxcMvhqAr2sjjV-kJP6w1aFQUXFQ)
> 
> 
> That should then work for both.

Heyo, 
Thank you for the solution. If it works for you then I must been doing something wrong :) 

I've renamed the folder 
![dd1](https://github.com/user-attachments/assets/d7855296-a757-4a93-8ba7-e9abc69b82e9)

and had to add this extra line with ddepth (edited in notepad like a noob :)
![note](https://github.com/user-attachments/assets/728851e4-eee0-4c5b-adb8-0e41eb5be959)


but still getting same error :(

![dd2](https://github.com/user-attachments/assets/863f2d6f-01d4-4c2b-8d63-7bda3d6bb8a4)


Thanks for your time!

**Comment by DominikDoom** [comment]
You misunderstood me, you have to replace the line, not add it. My screenshot is a diff view, meaning it shows what was there before (in red) and what it has been replaced with (green) to highlight changes.

**Comment by zthrx** [comment]
> You misunderstood me, you have to replace the line, not add it. My screenshot is a diff view, meaning it shows what was there before (in red) and what it has been replaced with (green) to highlight changes.

Damn, it works now. I will keep my replies just in case someone else will end up being as stupid as me ;) 

Thank you and have a great weekend!

**Comment by Tobies-Cormac** [comment]
I've found a working solution around this bug. I just simply run `pip uninstall https://github.com/MackinationsAi/UDAV2-ControlNet/releases/download/v1.0.0/depth_anything_v2-2024.7.1.0-py2.py3-none-any.whl` and say Yes to all the contents to be uninstall .
![image](https://github.com/user-attachments/assets/6d35178d-e6d6-4474-9e55-dd38f9d4515d)

After that i just did a simple re install with `pip install https://github.com/MackinationsAi/UDAV2-ControlNet/releases/download/v1.0.0/depth_anything_v2-2024.7.1.0-py2.py3-none-any.whl`
![image](https://github.com/user-attachments/assets/c956ad92-3b9e-45c9-af13-3a167a3c7337)
And it start to work. Hope someone find it useful:
![image](https://github.com/user-attachments/assets/995a68b2-0a45-40b2-84f6-d5b5039a69bf)
