### ISSUE TITLE
[Bug]: Unable to load the latest ControlNet

### ISSUE THREAD

**Issue by MtYCNN** [Mikubill/sd-webui-controlnet#3025]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

=================================================================================
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 17, in <module>
        from scripts import external_code, global_state
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "pydantic/main.py", line 178, in pydantic.main.ModelMetaclass.__new__
      File "pydantic/typing.py", line 400, in pydantic.typing.resolve_annotations
      File "/home/pai/envs/sd/lib/python3.9/typing.py", line 292, in _eval_type
        return t._evaluate(globalns, localns, recursive_guard)
      File "/home/pai/envs/sd/lib/python3.9/typing.py", line 554, in _evaluate
        eval(self.__forward_code__, globalns, localns),
      File "<string>", line 1, in <module>
    TypeError: unsupported operand type(s) for |: 'type' and 'type'

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 5, in <module>
        from scripts import external_code
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
ControlNet preprocessor location: /mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 18, in <module>
        from internal_controlnet.external_code import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: infotext.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/infotext.py", line 7, in <module>
        from internal_controlnet.external_code import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: xyz_grid_support.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/xyz_grid_support.py", line 8, in <module>
        from scripts.external_code import ResizeMode, ControlMode
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

### Steps to reproduce the problem

No matter how “Pydantic ”is upgraded or downgraded, this error is always reported

### What should have happened?

~

### Commit where the problem happens

webui: 
controlnet: 此处

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
=================================================================================
*** Error loading script: api.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 17, in <module>
        from scripts import external_code, global_state
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "pydantic/main.py", line 178, in pydantic.main.ModelMetaclass.__new__
      File "pydantic/typing.py", line 400, in pydantic.typing.resolve_annotations
      File "/home/pai/envs/sd/lib/python3.9/typing.py", line 292, in _eval_type
        return t._evaluate(globalns, localns, recursive_guard)
      File "/home/pai/envs/sd/lib/python3.9/typing.py", line 554, in _evaluate
        eval(self.__forward_code__, globalns, localns),
      File "<string>", line 1, in <module>
    TypeError: unsupported operand type(s) for |: 'type' and 'type'

---
*** Error loading script: batch_hijack.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 5, in <module>
        from scripts import external_code
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
ControlNet preprocessor location: /mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 18, in <module>
        from internal_controlnet.external_code import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: external_code.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: infotext.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/infotext.py", line 7, in <module>
        from internal_controlnet.external_code import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`

---
*** Error loading script: xyz_grid_support.py
    Traceback (most recent call last):
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/workspace/ktc/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/xyz_grid_support.py", line 8, in <module>
        from scripts.external_code import ResizeMode, ControlMode
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/external_code.py", line 1, in <module>
        from internal_controlnet.external_code import *  # noqa: F403
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/external_code.py", line 7, in <module>
        from .args import ControlNetUnit
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 53, in <module>
        class ControlNetUnit(BaseModel):
      File "/mnt/workspace/ktc/stable-diffusion-webui/extensions/sd-webui-controlnet/internal_controlnet/args.py", line 81, in ControlNetUnit
        def check_module(cls, value: str) -> str:
      File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
      File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
    pydantic.errors.ConfigError: duplicate validator function "internal_controlnet.args.ControlNetUnit.check_module"; if this is intended, set `allow_reuse=True`
```

### List of enabled extensions

无

### Console logs

```Shell
---
Loading weights [d7e2ac2f4a] from /mnt/workspace/ktc/stable-diffusion-webui/models/Stable-diffusion/majicMIX_realistic_麦橘写实_v2威力加强典藏版.safetensors
[LyCORIS]-WARNING: LyCORIS legacy extension is now loaded, if you don't expext to see this message, please disable this extension.
Creating model from config: /mnt/workspace/ktc/stable-diffusion-webui/configs/v1-inference.yaml
Running on local URL:  http://127.0.0.1:6006

To create a public link, set `share=True` in `launch()`.
Startup time: 14.6s (prepare environment: 1.6s, import torch: 2.3s, import gradio: 0.6s, setup paths: 1.3s, initialize shared: 1.3s, other imports: 0.6s, list SD models: 2.5s, load scripts: 3.5s, create ui: 0.7s).
Applying attention optimization: xformers... done.
Model loaded in 2.3s (create model: 0.7s, apply weights to model: 0.5s, calculate empty prompt: 0.8s).
```

**Comment by tsugg** [comment]
Ran into this too, and solved mine by upgrading my python version to 3.10

**Comment by sp1cae** [comment]
same issue

**Comment by sp1cae** [comment]
> same issue
Ran into this too, and solved mine by upgrading my python version to 3.10 
work +1
