### ISSUE TITLE
[Bug]: Controlnet Giving Error After Reinstalling

### ISSUE THREAD

**Issue by Yui007** [Mikubill/sd-webui-controlnet#3026]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

i tried to reinstall controlnet but now it is giving me the folling error message . I cant run it now:

ControlNet preprocessor location: /kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/kaggle/working/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 16, in <module>
        import scripts.preprocessor as preprocessor_init  # noqa
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/__init__.py", line 1, in <module>
        from .teed import *
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/teed.py", line 2, in <module>
        from skimage import morphology
      File "/opt/conda/lib/python3.10/site-packages/lazy_loader/__init__.py", line 74, in __getattr__
        return importlib.import_module(f"{package_name}.{name}")
      File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/opt/conda/lib/python3.10/site-packages/skimage/morphology/__init__.py", line 12, in <module>
        from .convex_hull import convex_hull_image, convex_hull_object
      File "/opt/conda/lib/python3.10/site-packages/skimage/morphology/convex_hull.py", line 4, in <module>
        from scipy.spatial import ConvexHull, QhullError
    ImportError: cannot import name 'QhullError' from 'scipy.spatial' (/opt/conda/lib/python3.10/site-packages/scipy/spatial/__init__.py)

### Steps to reproduce the problem

1. Go to .... reinstall
2. Press .... Run
3. ...

### What should have happened?

Controlnet Should have run

### Commit where the problem happens

webui: 1.10.1
controlnet: Latest Version also tried the previous commits still same isssue

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--port=1101 --xformers --api --enable-insecure-extension-access --theme dark --encrypt-pass=King --gradio-queue --no-half-vae
```

### List of enabled extensions

.

### Console logs

```Shell
ControlNet preprocessor location: /kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/kaggle/working/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 16, in <module>
        import scripts.preprocessor as preprocessor_init  # noqa
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/__init__.py", line 1, in <module>
        from .teed import *
      File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/teed.py", line 2, in <module>
        from skimage import morphology
      File "/opt/conda/lib/python3.10/site-packages/lazy_loader/__init__.py", line 74, in __getattr__
        return importlib.import_module(f"{package_name}.{name}")
      File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/opt/conda/lib/python3.10/site-packages/skimage/morphology/__init__.py", line 12, in <module>
        from .convex_hull import convex_hull_image, convex_hull_object
      File "/opt/conda/lib/python3.10/site-packages/skimage/morphology/convex_hull.py", line 4, in <module>
        from scipy.spatial import ConvexHull, QhullError
    ImportError: cannot import name 'QhullError' from 'scipy.spatial' (/opt/conda/lib/python3.10/site-packages/scipy/spatial/__init__.py)
```

**Comment by upseem** [comment]
touch extensions/sd-webui-controlnet/scripts/__init__.py 就能解决

**Comment by Yui007** [comment]
@upseem what can u please explain step by step what should i do
