### ISSUE TITLE
[Bug]: IP-adapter: IndexError: tensors used as indices must be long, int, byte or bool tensors.

### ISSUE THREAD

**Issue by Akramantic** [Mikubill/sd-webui-controlnet#3037]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

My ip adapter in controlnet does not work. In this case, the image is generated, but without an IP adapter.

### Steps to reproduce the problem

Launch stable diffusion.
Turn on IP adapter.
Generate.

### What should have happened?

The image should have been generated using the IP adapter preprocessor and the IP adapter model.

### Commit where the problem happens

webui: Commit hash: 67fdead6280bfe1f37c466d5279d54344c6305cf
controlnet: ControlNet v1.1.455

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Нет
```

### List of enabled extensions

LDSR	[built-in](http://127.0.0.1:7860/)	None			

Lora	[built-in](http://127.0.0.1:7860/)	None			

ScuNET	[built-in](http://127.0.0.1:7860/)	None			

SwinIR	[built-in](http://127.0.0.1:7860/)	None			

canvas-zoom-and-pan	[built-in](http://127.0.0.1:7860/)	None			

extra-options-section	[built-in](http://127.0.0.1:7860/)	None			

hypertile	[built-in](http://127.0.0.1:7860/)	None			

mobile	[built-in](http://127.0.0.1:7860/)	None			

postprocessing-for-training	[built-in](http://127.0.0.1:7860/)	None			

prompt-bracket-checker	[built-in](http://127.0.0.1:7860/)	None			

soft-inpainting	[built-in](http://127.0.0.1:7860/)	None			

TripoSR	https://github.com/VAST-AI-Research/TripoSR.git	main	[d26e3318](https://github.com/VAST-AI-
Research/TripoSR/commit/d26e33181947bbbc4c6fc0f5734e1ec6c080956e)	2024-05-14 15:24:35	unknown

a-person-mask-generator	https://github.com/djbielejeski/a-person-mask-generator.git	main	[5590766a](https://github.com/djbielejeski/a-person-mask-generator/commit/5590766ab2ec386d593cf822f51a94bb6297acb5)	2024-07-31 16:47:31	unknown

adetailer	https://github.com/Bing-su/adetailer.git	main	[25e7509f](https://github.com/Bing-su/adetailer/commit/25e7509fe018de8aa063a5f1902598f5eda0c06c)	2024-08-03 07:20:15	unknown

canvas-zoom	https://github.com/richrobber2/canvas-zoom.git	main	[b9c3cff8](https://github.com/richrobber2/canvas-zoom/commit/b9c3cff892d448f8825186500aeca710f243752a)	2024-08-13 15:02:30	unknown

clip-interrogator-ext	https://github.com/pharmapsychotic/clip-interrogator-ext.git	main	[0f1a4591](https://github.com/pharmapsychotic/clip-interrogator-ext/commit/0f1a4591f82b93859a1b854afb79494f39384662)	2023-09-10 04:35:46	unknown

extension-style-vars	https://github.com/SirVeggie/extension-style-vars	master	[b308fbe4](https://github.com/SirVeggie/extension-style-vars/commit/b308fbe454faa4b4730187323d4f1a839c55005a)	2024-04-01 05:23:34	unknown

openpose-editor	https://github.com/fkunn1326/openpose-editor.git	master	[c9357715](https://github.com/fkunn1326/openpose-editor/commit/c935771507f57201e26f4ed507aa47f3812ca491)	2023-10-11 12:04:20	unknown

sd-webui-3d-open-pose-editor	https://github.com/nonnonstop/sd-webui-3d-open-pose-editor.git	main	[f2d5aac5](https://github.com/nonnonstop/sd-webui-3d-open-pose-editor/commit/f2d5aac51d891bc5f266b1549f3cf4495fc52160)	2023-04-15 16:21:06	unknown

sd-webui-agentattention	https://github.com/v0xie/sd-webui-agentattention.git	master	[8c2fd24e](https://github.com/v0xie/sd-webui-agentattention/commit/8c2fd24ed5203e68450100064a49fa7873eea0bb)	2024-04-22 09:35:06	unknown

sd-webui-cli-interruption	https://github.com/light-and-ray/sd-webui-cli-interruption.git	master	[72ebefaf](https://github.com/light-and-ray/sd-webui-cli-interruption/commit/72ebefafd59f96a3d7c011c8cab70e7f5cf5b02a)	2024-04-05 22:39:29	unknown

sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[56cec5b2](https://github.com/Mikubill/sd-webui-controlnet/commit/56cec5b2958edf3b1807b7e7b2b1b5186dbd2f81)	2024-07-25 23:52:52	unknown

sd-webui-depth-lib	https://github.com/wywywywy/sd-webui-depth-lib.git	main	[9fecb8df](https://github.com/wywywywy/sd-webui-depth-lib/commit/9fecb8df55411d9ea7f65a23cf0b0bf216be8aba)	2023-11-30 01:55:41	unknown

sd-webui-detail-daemon	https://github.com/muerrilla/sd-webui-detail-daemon.git	main	[6e918d67](https://github.com/muerrilla/sd-webui-detail-daemon/commit/6e918d67a9458fa70b41f79135fc539556547c74)	2024-07-08 01:14:47	unknown

sd-webui-extended-style-saver	https://github.com/harukei-tech/sd-webui-extended-style-saver.git	master	[7750cc6b](https://github.com/harukei-tech/sd-webui-extended-style-saver/commit/7750cc6b2dcba91951402a682819bcb4fcc43bea)	2024-01-07 08:45:31	unknown

sd-webui-negpip	https://github.com/hako-mikan/sd-webui-negpip.git	main	[3b11e54b](https://github.com/hako-mikan/sd-webui-negpip/commit/3b11e54bbdb63240dbf1a858ef1b60302d30d17c)	2024-04-01 18:02:33	unknown

sd-webui-resharpen	https://github.com/Haoming02/sd-webui-resharpen.git	main	[4aab64fc](https://github.com/Haoming02/sd-webui-resharpen/commit/4aab64fc0421ffd9e0869b6650fc59eab1ac58bc)	2024-07-09 06:31:32	unknown

stable-diffusion-webui-state	https://github.com/ilian6806/stable-diffusion-webui-state.git	main	[ce1ca3a1](https://github.com/ilian6806/stable-diffusion-webui-state/commit/ce1ca3a1141f542ad61c66f074048989b14731f9)	2024-05-04 20:02:00	unknown

### Console logs

```Shell
ControlNet preprocessor location: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\downloads
2024-08-17 11:10:06,491 - ControlNet - INFO - ControlNet v1.1.455
Loading weights [879db523c3] from C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\models\Stable-diffusion\dreamshaper_8.safetensors
Creating model from config: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\configs\v1-inference.yaml
2024-08-17 11:10:07,658 - ControlNet - INFO - ControlNet UI callback registered.
C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 26.2s (prepare environment: 27.1s, initialize shared: 2.0s, load scripts: 2.8s, create ui: 1.2s, gradio launch: 0.8s).
Applying attention optimization: sub-quadratic... done.
Model loaded in 5.5s (load weights from disk: 0.2s, load config: 0.1s, create model: 1.1s, apply weights to model: 1.2s, apply float(): 0.6s, calculate empty prompt: 2.2s).
Starting job task(beknahsdxy9z2qr)
INFO:modules.shared_state:Starting job task(beknahsdxy9z2qr)
2024-08-17 11:11:01,068 - ControlNet - INFO - unit_separate = False, style_align = False
2024-08-17 11:11:01,248 - ControlNet - INFO - Loading model: ip-adapter-faceid-plus_sd15 [d86a490f]
2024-08-17 11:11:01,312 - ControlNet - INFO - Loaded state_dict from [C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\models\ControlNet\ip-adapter-faceid-plus_sd15.pth]
2024-08-17 11:11:01,771 - ControlNet - INFO - ControlNet model ip-adapter-faceid-plus_sd15 [d86a490f](ControlModelType.IPAdapter) loaded.
2024-08-17 11:11:01,774 - ControlNet - INFO - Using preprocessor: ip-adapter-auto
2024-08-17 11:11:01,774 - ControlNet - INFO - preprocessor resolution = 512
2024-08-17 11:11:01,775 - ControlNet - INFO - ip-adapter-auto => ip-adapter_face_id_plus
download_path: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l
Downloading C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
100%|████████████████████████████████████████████████████████████████████████| 281857/281857 [02:57<00:00, 1591.32KB/s]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
*** Error running process: C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1228, in process
        self.controlnet_hack(p)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1213, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\controlnet.py", line 941, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in get_control
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\controlnet.py", line 242, in preprocess_input_image
        result = preprocessor.cached_call(
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 198, in cached_call
        result = self._cached_call(input_image, *args, **kwargs)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\utils.py", line 82, in decorated_func
        return cached_func(*args, **kwargs)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\utils.py", line 66, in cached_func
        return func(*args, **kwargs)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 211, in _cached_call
        return self(*args, **kwargs)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\preprocessor\ip_adapter_auto.py", line 25, in __call__
        return p(*args, **kwargs)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 105, in __call__
        result, is_image = self.call_function(
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 769, in face_id_plus
        clip_embed, _ = clip(img, config='clip_h', low_vram=low_vram)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 394, in clip
        clip_encoder[config] = ClipVisionDetector(config, low_vram)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\extensions\sd-webui-controlnet\annotator\clipvision\__init__.py", line 121, in __init__
        sd = torch.load(file_path, map_location=self.device)
      File "C:\Users\desir\SD-2024_3\stable-diffusion-webui-amdgpu\modules\dml\hijack\torch.py", line 27, in load
        data[k][weight] = data[k][weight].to(device)
    IndexError: tensors used as indices must be long, int, byte or bool tensors

---
 25%|████████████████████▊                                                              | 5/20 [00:21<00:59,  3.94s/it]Received interrupt request████████████▊                                                  | 5/20 [00:15<00:49,  3.30s/it]
INFO:modules.shared_state:Received interrupt request
 30%|████████████████████████▉                                                          | 6/20 [00:24<00:57,  4.08s/it]
Total progress:  30%|████████████████████                                               | 6/20 [00:19<00:46,  3.31s/it]
Ending job task(beknahsdxy9z2qr) (220.79 seconds)                                       | 6/20 [00:19<00:46,  3.34s/it]
INFO:modules.shared_state:Ending job task(beknahsdxy9z2qr) (220.79 seconds)
```

#IP-Adapter.

**Comment by toxicmuffin13** [comment]
I am having the same issue. Is there a fix?
