### ISSUE TITLE
[Bug]: depth_hand_refiner webui 1.10.1 error

### ISSUE THREAD

**Issue by skyliwq** [Mikubill/sd-webui-controlnet#3049]
2024-09-16T23:58:22.990800211Z Traceback (most recent call last):
2024-09-16T23:58:22.991844844Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
2024-09-16T23:58:22.991883191Z     output = await app.get_blocks().process_api(
2024-09-16T23:58:22.991902345Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.991912273Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1431, in process_api
2024-09-16T23:58:22.991922349Z     result = await self.call_function(
2024-09-16T23:58:22.991931518Z              ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.991940696Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1103, in call_function
2024-09-16T23:58:22.991950772Z     prediction = await anyio.to_thread.run_sync(
2024-09-16T23:58:22.991959938Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.991969015Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
2024-09-16T23:58:22.991996533Z     return await get_asynclib().run_sync_in_worker_thread(
2024-09-16T23:58:22.992005911Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992015093Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2024-09-16T23:58:22.992024740Z     return await future
2024-09-16T23:58:22.992034007Z            ^^^^^^^^^^^^
2024-09-16T23:58:22.992043037Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2024-09-16T23:58:22.992052531Z     result = context.run(func, *args)
2024-09-16T23:58:22.992061461Z              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992070418Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/gradio/utils.py", line 707, in wrapper
2024-09-16T23:58:22.992079841Z     response = f(*args, **kwargs)
2024-09-16T23:58:22.992088649Z                ^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992097550Z   File "/app/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet_ui/controlnet_ui_group.py", line 951, in run_annotator
2024-09-16T23:58:22.992107338Z     result = preprocessor.cached_call(
2024-09-16T23:58:22.992116455Z              ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992125376Z   File "/app/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/supported_preprocessor.py", line 198, in cached_call
2024-09-16T23:58:22.992135024Z     result = self._cached_call(input_image, *args, **kwargs)
2024-09-16T23:58:22.992144165Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992153208Z   File "/app/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 82, in decorated_func
2024-09-16T23:58:22.992162686Z     return cached_func(*args, **kwargs)
2024-09-16T23:58:22.992173279Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992182369Z   File "/app/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 66, in cached_func
2024-09-16T23:58:22.992192341Z     return func(*args, **kwargs)
2024-09-16T23:58:22.992201455Z            ^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992210343Z   File "/app/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/supported_preprocessor.py", line 211, in _cached_call
2024-09-16T23:58:22.992219802Z     return self(*args, **kwargs)
2024-09-16T23:58:22.992228583Z            ^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992237492Z   File "/app/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/legacy/legacy_preprocessors.py", line 105, in __call__
2024-09-16T23:58:22.992247244Z     result, is_image = self.call_function(
2024-09-16T23:58:22.992256181Z                        ^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992265158Z   File "/app/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/legacy/processor.py", line 797, in run_model
2024-09-16T23:58:22.992283618Z     self.load_model()
2024-09-16T23:58:22.992309576Z   File "/app/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/preprocessor/legacy/processor.py", line 783, in load_model
2024-09-16T23:58:22.992319156Z     self.model = MeshGraphormerDetector.from_pretrained(
2024-09-16T23:58:22.992328177Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992337234Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/hand_refiner/__init__.py", line 17, in from_pretrained
2024-09-16T23:58:22.992346761Z     pipeline = MeshGraphormerMediapipe(args)
2024-09-16T23:58:22.992355650Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992364784Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/hand_refiner/pipeline.py", line 198, in __init__
2024-09-16T23:58:22.992374270Z     self.detector = vision.HandLandmarker.create_from_options(options)
2024-09-16T23:58:22.992383621Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992392883Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/mediapipe/tasks/python/vision/hand_landmarker.py", line 365, in create_from_options
2024-09-16T23:58:22.992402670Z     task_info.generate_graph_config(
2024-09-16T23:58:22.992411616Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/mediapipe/tasks/python/core/task_info.py", line 97, in generate_graph_config
2024-09-16T23:58:22.992421247Z     node_config.options.CopyFrom(task_subgraph_options)
2024-09-16T23:58:22.992430268Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/google/protobuf/message.py", line 129, in CopyFrom
2024-09-16T23:58:22.992440011Z     self.MergeFrom(other_msg)
2024-09-16T23:58:22.992449863Z   File "/app/stable-diffusion-webui/venv/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 1334, in MergeFrom
2024-09-16T23:58:22.992459571Z     field_value = field._default_constructor(self)
2024-09-16T23:58:22.992468560Z                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-16T23:58:22.992477549Z AttributeError: 'FieldDescriptor' object has no attribute '_default_constructor'

**Comment by skyliwq** [comment]
This issue occurs after the update version of Specify Controlnet_oux>=0.0.9

**Comment by sdbds** [comment]
It looks like your protobuf version is too high to cause this.
