### ISSUE TITLE
[Bug]: controlnet_aux换镜像源还是错误

### ISSUE THREAD

**Issue by xiahongyu939** [Mikubill/sd-webui-controlnet#3052]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

更换了镜像源，还是显示没有controlnet_aux的模块

### Steps to reproduce the problem

1. Go to .... fast_stable_diffusion.ipynb
2. Press ....Google Chrome
3. ...

### What should have happened?

修复

### Commit where the problem happens

webui: 
controlnet: 1.1.455

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
否
```

### List of enabled extensions

webui

### Console logs

```Shell
ControlNet preprocessor location: /root/main/extensions/sd-webui-controlnet/annotator/downloads
*** Error loading script: controlnet.py
    Traceback (most recent call last):
      File "/root/main/modules/scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/root/main/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/root/main/extensions/sd-webui-controlnet/scripts/controlnet.py", line 16, in <module>
        import scripts.preprocessor as preprocessor_init  # noqa
      File "/root/main/extensions/sd-webui-controlnet/scripts/preprocessor/__init__.py", line 9, in <module>
        from .mobile_sam import *
      File "/root/main/extensions/sd-webui-controlnet/scripts/preprocessor/mobile_sam.py", line 1, in <module>
        from annotator.mobile_sam import SamDetector_Aux
      File "/root/main/extensions/sd-webui-controlnet/annotator/mobile_sam/__init__.py", line 12, in <module>
        from controlnet_aux import SamDetector
    ModuleNotFoundError: No module named 'controlnet_aux'

---
```

**Comment by sdbds** [comment]
换https://pypi.org/simple
