### ISSUE TITLE
[Bug]: Extension crashes SD.Next when installed and backend="original"

### ISSUE THREAD

**Issue by anothertal3** [Mikubill/sd-webui-controlnet#3060]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I'm using SD.Next. The application is based on Automatic1111 and supports two modes of operation ("backend"): "diffusers" (which is the current one) and "original", which is older. "diffusers" brings its own "control" concept and disables your extension (I think), but "original" keeps everything similiar to Automatic1111 and the extension available.

Recently I've tried to switch over from an older SD.Next-version to the most current one and intended to keep using this extension in "original" mode. However, there seems to be some UI incompatibility now which crashes the application in a way preventing it even from starting.

Reverting is only possible by manually editing the `config.json`.

There are a couple of error messages in the log which I include in the proper forms below.

### Steps to reproduce the problem

1. Run SD.Next in "diffusers" mode and ensure that "sd-webui-controlnet" is not installed -> everything is fine
2. Switch SD.Next backend to "original" and restart application -> everything is fine
3. Install "https://github.com/Mikubill/sd-webui-controlnet" and restart application
4. The UI loading indicator keeps spinning indefinitely and there's no progress

### What should have happened?

The UI should load properly and the Controlnet panel should be available at least in "original" mode.

### Commit where the problem happens

I'm sorry but I have been using two different versions for SD.Next and Controlnet for many month and only recently discovered this behavior. Can't tell when it appeared for the first time.

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
webui.bat --upgrade --docs
```

### List of enabled extensions

```
INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg', 'a1111-sd-webui-tagcomplete', 
                         'adetailer', 'sd-dynamic-prompts', 'sd-webui-controlnet']
```

### Console logs

```Shell
Using VENV: f:\sd.next\venv
12:29:36-302411 INFO     Starting SD.Next
12:29:36-304409 INFO     Logger: file="f:\sd.next\sdnext.log" level=INFO size=22227919 mode=append
12:29:36-305455 INFO     Python version=3.10.11 platform=Windows
                         bin="f:\sd.next\venv\Scripts\python.exe"
                         venv="f:\sd.next\venv"
12:29:36-429296 INFO     Version: app=sd.next updated=2024-09-13 hash=e7ec07f9 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
12:29:36-848274 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
12:29:36-849348 INFO     HF cache folder: C:\Users\user\.cache\huggingface\hub
12:29:36-858094 INFO     nVidia CUDA toolkit detected: nvidia-smi present
12:29:36-954850 INFO     Verifying requirements
12:29:36-957854 WARNING  Package version mismatch: timm 0.6.7 required 0.9.16
12:29:36-958854 INFO     Install: package="timm==0.9.16" mode=pip
12:29:40-081092 INFO     Verifying packages
12:29:40-082098 INFO     Startup: standard
12:29:40-082098 INFO     Verifying submodules
12:29:52-615787 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg', 'a1111-sd-webui-tagcomplete',
                         'adetailer', 'sd-dynamic-prompts', 'sd-webui-controlnet']
12:29:52-617792 INFO     Verifying requirements
12:29:52-617792 INFO     Updating Wiki
12:29:53-227332 INFO     Command line args: ['--upgrade', '--docs'] upgrade=True docs=True
12:29:57-633179 INFO     Load packages: {'torch': '2.3.1+cu121', 'diffusers': '0.31.0.dev0', 'gradio': '3.43.2'}
12:29:58-033598 INFO     VRAM: Detected=16.0 GB Optimization=none
12:29:58-036108 INFO     Engine: backend=Backend.ORIGINAL compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
12:29:58-083109 INFO     Device: device=NVIDIA GeForce RTX 4060 Ti n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8907
                         driver=560.70
12:29:58-845244 INFO     Available VAEs: path="F:\stable-diffusion\models\VAE" items=4
12:29:58-847246 INFO     Disabled extensions: ['sdnext-modernui', 'sd-webui-prevent-artifact']
12:29:58-890018 INFO     Available models: path="F:\stable-diffusion\models\Stable-diffusion" items=31 time=0.04
12:29:59-186306 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m12:29:59-183789[0m[2;36m [0m[34mINFO    [0m LoRA networks: [33mavailable[0m=[1;36m3168[0m
                         [33mfolders[0m=[1;36m26[0m
12:29:59-601151 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
12:30:00-277310 INFO     Extension: script='extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py'
                         Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will
                         be limited to those added through the extra networks menu.
12:30:00-676933 INFO     Extension: script='extensions\adetailer\scripts\!adetailer.py' [-] ADetailer initialized.
                         version: 24.9.0, num models: 10
12:30:00-983678 INFO     Extension: script='extensions\sd-webui-controlnet\scripts\api.py' ControlNet preprocessor
                         location: f:\sd.next\extensions\sd-webui-controlnet\annotator\downloads
12:30:01-095392 INFO     Extension: script='extensions\sd-webui-controlnet\scripts\controlnet.py' Warning: ControlNet
                         failed to load SGM - will use LDM instead.
12:30:01-105543 INFO     Extension: script='extensions\sd-webui-controlnet\scripts\hook.py' Warning: ControlNet failed
                         to load SGM - will use LDM instead.
12:30:01-147262 INFO     UI theme: type=Standard name="black-orange"
12:30:03-545151 ERROR    Calling script: extensions\sd-webui-controlnet\scripts\controlnet.py/ui: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ f:\sd.next\modules\scripts.py:295 in wrap_call                                                     │
│                                                                                                                      │
│   294 │   try:                                                                                                       │
│ ❱ 295 │   │   res = func(*args, **kwargs)                                                                            │
│   296 │   │   return res                                                                                             │
│                                                                                                                      │
│ f:\sd.next\extensions\sd-webui-controlnet\scripts\controlnet.py:307 in ui                          │
│                                                                                                                      │
│    306 │   │   │   │   │   │   │   │   │   │   elem_classes=['cnet-unit-tab']):                                      │
│ ❱  307 │   │   │   │   │   │   │   │   group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname, p │
│    308 │   │   │   │   │   │   │   │   ui_groups.append(group)                                                       │
│                                                                                                                      │
│ f:\sd.next\extensions\sd-webui-controlnet\scripts\controlnet.py:246 in uigroup                     │
│                                                                                                                      │
│    245 │   │   group.render(tabname, elem_id_tabname, is_img2img)                                                    │
│ ❱  246 │   │   group.register_callbacks(is_img2img)                                                                  │
│    247 │   │   unit_state = group.render_and_register_unit(tabname, is_img2img)                                      │
│                                                                                                                      │
│ f:\sd.next\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:958 in regi │
│                                                                                                                      │
│    957 │   │   """                                                                                                   │
│ ❱  958 │   │   self.register_send_dimensions(is_img2img)                                                             │
│    959 │   │   self.register_webcam_toggle()                                                                         │
│                                                                                                                      │
│ f:\sd.next\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py:533 in regi │
│                                                                                                                      │
│    532 │   │   )                                                                                                     │
│ ❱  533 │   │   self.send_dimen_button.click(                                                                         │
│    534 │   │   │   fn=send_dimensions,                                                                               │
│                                                                                                                      │
│ f:\sd.next\venv\lib\site-packages\gradio\events.py:174 in __call__                                 │
│                                                                                                                      │
│   173 │   │                                                                                                          │
│ ❱ 174 │   │   dep, dep_index = self.trigger.set_event_trigger(                                                       │
│   175 │   │   │   self.event_name,                                                                                   │
│                                                                                                                      │
│ f:\sd.next\venv\lib\site-packages\gradio\blocks.py:287 in set_event_trigger                        │
│                                                                                                                      │
│    286 │   │   │   "inputs": [block._id for block in inputs],                                                        │
│ ❱  287 │   │   │   "outputs": [block._id for block in outputs],                                                      │
│    288 │   │   │   "backend_fn": fn is not None,                                                                     │
│                                                                                                                      │
│ f:\sd.next\venv\lib\site-packages\gradio\blocks.py:287 in <listcomp>                               │
│                                                                                                                      │
│    286 │   │   │   "inputs": [block._id for block in inputs],                                                        │
│ ❱  287 │   │   │   "outputs": [block._id for block in outputs],                                                      │
│    288 │   │   │   "backend_fn": fn is not None,                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute '_id'
12:30:05-057155 INFO     Local URL: http://127.0.0.1:7860/
12:30:05-058151 INFO     API Docs: http://127.0.0.1:7860/docs
12:30:05-058151 INFO     API ReDocs: http://127.0.0.1:7860/redocs
12:30:05-168063 INFO     [AgentScheduler] Task queue is empty
12:30:05-169068 INFO     [AgentScheduler] Registering APIs
12:30:05-267383 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16
                         context=no_grad fp16=True bf16=None optimization=Scaled-Dot-Product
12:30:05-270734 INFO     Select: model="sd15"
Loading model: F:\stable-diffusion\models\Stable-diffusion\sd15.safetensors ━━━━━━━━ 0.0/2.1 -:--:--
                                                                                                         GB
12:30:09-505301 INFO     LDM: LatentDiffusion: mode=eps
12:30:09-507308 INFO     LDM: DiffusionWrapper params=859.52M
12:30:09-507308 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="F:\stable-diffusion\models\Stable-diffusion\sd15.safetensors"
                         size=2034MB
Loading model: F:\stable-diffusion\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors ━━━━━━━━━━━━ 0.0/334.6 MB -:--:--
12:30:10-915862 INFO     Cross-attention: optimization=Scaled-Dot-Product
12:30:11-018960 INFO     Load embeddings: loaded=150 skipped=1 time=0.10
12:30:11-024662 INFO     Model loaded in 5.75 create=4.21 apply=0.52 vae=0.43 move=0.45 embeddings=0.10
12:30:11-254678 INFO     Model load finished: {'ram': {'used': 7.0, 'total': 31.21}, 'gpu': {'used': 3.18, 'total':
                         16.0}, 'retries': 0, 'oom': 0} cached=0
12:30:11-368563 INFO     Startup time: 18.14 torch=3.00 gradio=0.65 diffusers=0.29 libraries=1.58 samplers=0.09
                         extensions=2.18 face-restore=0.05 ui-networks=2.27 ui-txt2img=0.09 ui-img2img=0.23
                         ui-models=0.17 ui-settings=0.10 ui-extensions=0.65 launch=0.30 api=0.06 app-started=0.12
                         checkpoint=6.12
12:30:42-744300 INFO     MOTD: N/A
Traceback (most recent call last):
  File "f:\sd.next\venv\lib\site-packages\gradio\routes.py", line 507, in predict
    output = await route_utils.call_process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\sd.next\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "f:\sd.next\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "f:\sd.next\modules\call_queue.py", line 13, in f
    res = func(*args, **kwargs)
TypeError: update_token_counter() missing 2 required positional arguments: 'text' and 'steps'
Traceback (most recent call last):
  File "f:\sd.next\venv\lib\site-packages\gradio\routes.py", line 507, in predict
    output = await route_utils.call_process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\sd.next\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "f:\sd.next\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "f:\sd.next\modules\ui.py", line 483, in reference_submit
    if '@' not in model: # diffusers
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "f:\sd.next\venv\lib\site-packages\gradio\routes.py", line 507, in predict
    output = await route_utils.call_process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "f:\sd.next\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "f:\sd.next\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "f:\sd.next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "f:\sd.next\venv\lib\site-packages\gradio\utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "f:\sd.next\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py", line 198, in f
    raise Exception("Invalid call")
Exception: Invalid call
12:30:44-377865 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
```

**Comment by anothertal3** [comment]
I'm closing this issue already as it appears to have been fixable (and fixed) within SD.Next.
