### ISSUE TITLE
But my linux server reallly do not has webcam...

### ISSUE THREAD

**Issue by Alfred-Duncan** [Mikubill/sd-webui-controlnet#308]
Error calling: /home/stable-diffusion-webui-controlnet/extensions/sd-webui-controlnet/scripts/controlnet.py/ui
Traceback (most recent call last):
  File "/home/stable-diffusion-webui-controlnet/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/home/stable-diffusion-webui-controlnet/extensions/sd-webui-controlnet/scripts/controlnet.py", line 412, in ui
    ctrls_group += self.accordion(f"ControlNet", is_img2img)
  File "/home/stable-diffusion-webui-controlnet/extensions/sd-webui-controlnet/scripts/controlnet.py", line 243, in accordion
    webcam_enable.click(fn=webcam_toggle, outputs=input_image)
TypeError: Clickable.click() missing 1 required positional argument: 'inputs'

**Comment by Mikubill** [comment]
fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/524ee1551166d7fc8028e6b262f9910f0e2ad153

**Comment by Alfred-Duncan** [comment]
thx man, I'm going to try
