### ISSUE TITLE
Error loading segmentation model

### ISSUE THREAD

**Issue by jonesi13** [Mikubill/sd-webui-controlnet#310]
```
Loading model: control_seg-fp16 [b9c1cc12]
Loaded state_dict from [E:\sd.webui\webui\extensions\sd-webui-controlnet\models\control_seg-fp16.safetensors]
ControlNet model control_seg-fp16 [b9c1cc12] loaded.
Loading preprocessor: segmentation
Error running process: E:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "E:\sd.webui\webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 547, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\scripts\processor.py", line 155, in uniformer
    from annotator.uniformer import apply_uniformer
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\__init__.py", line 1, in <module>
    from annotator.uniformer.mmseg.apis import init_segmentor, inference_segmentor, show_result_pyplot
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\apis\__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\apis\inference.py", line 8, in <module>
    from annotator.uniformer.mmseg.models import build_segmentor
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\models\__init__.py", line 4, in <module>
    from .decode_heads import *  # noqa: F401,F403
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\models\decode_heads\__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\models\decode_heads\cc_head.py", line 7, in <module>
    from annotator.uniformer.mmcv.ops import CrissCrossAttention
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\mmcv\ops\__init__.py", line 10, in <module>
    from .corner_pool import CornerPool
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\mmcv\ops\corner_pool.py", line 8, in <module>
    ext_module = ext_loader.load_ext('_ext', [
  File "E:\sd.webui\webui\extensions\sd-webui-controlnet\annotator\uniformer\mmcv\utils\ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: top_pool_forward miss in module _ext
```

**Comment by Mikubill** [comment]
maybe related: https://github.com/lllyasviel/ControlNet/issues/61#issuecomment-1434005703

**Comment by jonesi13** [comment]
Removing mmcv folders from webui solved it.

**Comment by ameen-roayan** [comment]
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 378, in run_annotator
    result = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "E:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 155, in uniformer
    from annotator.uniformer import apply_uniformer
  File "E:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\__init__.py", line 1, in <module>
    from annotator.uniformer.mmseg.apis import init_segmentor, inference_segmentor, show_result_pyplot
  File "E:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\apis\__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "E:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\apis\inference.py", line 2, in <module>
    import annotator.uniformer.mmcv as mmcv
ModuleNotFoundError: No module named 'annotator.uniformer.mmcv'

Got this after remocing mmcv
