### ISSUE TITLE
Error using preprocesser of segmentation

### ISSUE THREAD

**Issue by EkaLinjas** [Mikubill/sd-webui-controlnet#320]
![image](https://user-images.githubusercontent.com/125619279/220886205-0e32471c-7ea7-4b16-a0d9-7dee209086cc.png)

Traceback (most recent call last):
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 378, in run_annotator
    result = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\scripts\processor.py", line 155, in uniformer
    from annotator.uniformer import apply_uniformer
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\__init__.py", line 1, in <module>
    from annotator.uniformer.mmseg.apis import init_segmentor, inference_segmentor, show_result_pyplot
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmseg\apis\__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmseg\apis\inference.py", line 8, in <module>
    from annotator.uniformer.mmseg.models import build_segmentor
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmseg\models\__init__.py", line 4, in <module>

**Comment by Mikubill** [comment]
Seems like the segment model is corrupt, and errlog is truncated. Could you share full traceback?

**Comment by EkaLinjas** [comment]
> Seems like the segment model is corrupt, and errlog is truncated. Could you share full traceback?

there is full traceback . Its occurs when i use segment proprocesser
![image](https://user-images.githubusercontent.com/125619279/220890454-9b515e08-19e8-4f86-8805-0a6f92b4e9fe.png)

Traceback (most recent call last):
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 378, in run_annotator
    result = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\scripts\processor.py", line 155, in uniformer
    from annotator.uniformer import apply_uniformer
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\__init__.py", line 1, in <module>
    from annotator.uniformer.mmseg.apis import init_segmentor, inference_segmentor, show_result_pyplot
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmseg\apis\__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmseg\apis\inference.py", line 8, in <module>
    from annotator.uniformer.mmseg.models import build_segmentor
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmseg\models\__init__.py", line 4, in <module>
    from .decode_heads import *  # noqa: F401,F403
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmseg\models\decode_heads\__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmseg\models\decode_heads\cc_head.py", line 7, in <module>
    from annotator.uniformer.mmcv.ops import CrissCrossAttention
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmcv\ops\__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmcv\ops\assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui/extensions/sd-webui-controlnet\annotator\uniformer\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的程序。

‘找不到指定的程序’ it means 'The specified program could not be found'

**Comment by EkaLinjas** [comment]
> Seems like the segment model is corrupt, and errlog is truncated. Could you share full traceback?

i tried reinstall the controlnet but not work

**Comment by Mikubill** [comment]
see https://github.com/lllyasviel/ControlNet/issues/61#issuecomment-1434005703

**Comment by EkaLinjas** [comment]
> see [lllyasviel/ControlNet#61 (comment)](https://github.com/lllyasviel/ControlNet/issues/61#issuecomment-1434005703)

![image](https://user-images.githubusercontent.com/125619279/220894839-3f75cc49-f601-4cb3-83a8-87fa66e896ea.png)
it works when i deleted \stable-diffusion-webui\extensions\ddetailer and pip uninstall mmcv-full -y
![image](https://user-images.githubusercontent.com/125619279/220895046-0b196183-cf7e-4ea9-876d-550c60684483.png)
