### ISSUE TITLE
Issue running on M2 Mac

### ISSUE THREAD

**Issue by Kitenite** [Mikubill/sd-webui-controlnet#337]
Whenever I try to run with ControlNet enabled, I'm seeing:
```
Loading model: control_sd15_canny [fef5e48e]
Loaded state_dict from [/Users/kietho/workplace/stable-diffusion-webui/models/ControlNet/control_sd15_canny.pth]
Error running process: /Users/kietho/workplace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/Users/kietho/workplace/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/Users/kietho/workplace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 538, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "/Users/kietho/workplace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 443, in build_control_model
    network = network_module(
  File "/Users/kietho/workplace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 64, in __init__
    self.control_model = ControlNet(**config.model.params.control_stage_config.params)
  File "/Users/kietho/workplace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 150, in __init__
    use_fp16 = getattr(devices, 'dtype_unet', devices.dtype) == th.float16 and not shared.cmd_opts.no_half_controlnet
AttributeError: 'Namespace' object has no attribute 'no_half_controlnet'
```

Apple M2 Pro
MacOS 13.2

**Comment by Mikubill** [comment]
Maybe restart WebUI will help

**Comment by Kitenite** [comment]
Unfortunately, that didn't work. I installed based on the README steps and using unpruned model

**Comment by Kitenite** [comment]
Nevermind, now it is working. I didn't do anything different just restarted the UI again. Thank you for the help :)
