### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'no_half_controlnet'

### ISSUE THREAD

**Issue by ZZZeeeZZZ** [Mikubill/sd-webui-controlnet#352]
I'm running the model below, but it shows some errors.

Loading model: control_sd15_openpose [fef5e48e]
Loaded state_dict from [/Users/zeenzcg/stable-diffusion-webui/extensions/ControlNetNet/models/control_sd15_openpose.pth]
Error running process: /Users/zeenzcg/stable-diffusion-webui/extensions/ControlNetNet/scripts/controlnet.py
Traceback (most recent call last):
  File "/Users/zeenzcg/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/Users/zeenzcg/stable-diffusion-webui/extensions/ControlNetNet/scripts/controlnet.py", line 557, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "/Users/zeenzcg/stable-diffusion-webui/extensions/ControlNetNet/scripts/controlnet.py", line 443, in build_control_model
    network = network_module(
  File "/Users/zeenzcg/stable-diffusion-webui/extensions/ControlNetNet/scripts/cldm.py", line 64, in __init__
    self.control_model = ControlNet(**config.model.params.control_stage_config.params)
  File "/Users/zeenzcg/stable-diffusion-webui/extensions/ControlNetNet/scripts/cldm.py", line 150, in __init__
    use_fp16 = getattr(devices, 'dtype_unet', devices.dtype) == th.float16 and not shared.cmd_opts.no_half_controlnet
AttributeError: 'Namespace' object has no attribute 'no_half_controlnet'

**Comment by Mikubill** [comment]
try fully restart webui

**Comment by ZZZeeeZZZ** [comment]
I tried it, but still failed

**Comment by brunogcar** [comment]
close and start again
instead of just reloading ui

**Comment by ZZZeeeZZZ** [comment]
I tried it, but still didn't work
