### ISSUE TITLE
Applying to Intel XPU

### ISSUE THREAD

**Issue by KreataWorld** [Mikubill/sd-webui-controlnet#358]
I'm currently trying to make controlnet extension work on sd webui based on [`Jbaboval's webui fork`](https://github.com/jbaboval/stable-diffusion-webui).

My system is i5-12400, msi pro b660m-a ddr4 with resizable bar enabled, intel arc a770. It can run webui and standard diffusion without problem.

While trying to run controlnet extension on intel gpu, I have modified a bit in both projects:
```
def torch_gc():
    empty_cache()
    gc()
```
added above to `devices.py, line 97` because controlnet extension needed it, and
```
            else:
                control = torch.from_numpy(detected_map.copy()).float().to(devices.cpu) / 255.0
                # control = torch.from_numpy(detected_map.copy()).float().to(devices.get_device_for("controlnet") / 255.0
```
modified `controlnet.py, line 606 to use cpu because transform functions beginning at line 611 needs fp64 calculation but a770 does cannot do that.

Now I got stuck at the next error:
```
Error completing request
Arguments: ('task(v7py9h4j5p93ur5)', 0, 'gorgeous medieval fortress, (realistic:1.3), looking up from front gate, hundreds of buildings and towers, good details', '(worst quality:1.4), (low quality:1.1)', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x7F76AAF1BD00>, None, None, None, None, None, None, 10, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.5, 2036544618.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 0, True, 'none', 'control_sd15_mlsd [fef5e48e]', 1, {'image': array([[[164, 159, 155],
        [165, 160, 156],
        [165, 160, 156],
        ...,
        [155, 156, 161],
        [155, 156, 161],
        [154, 155, 160]],

       [[165, 160, 156],
        [165, 160, 156],
        [165, 160, 156],
        ...,
        [155, 156, 161],
        [155, 156, 161],
        [154, 155, 160]],

       [[165, 160, 156],
        [166, 161, 157],
        [166, 161, 157],
        ...,
        [156, 157, 162],
        [156, 157, 162],
        [155, 156, 161]],

       ...,

       [[165, 171, 193],
        [166, 172, 194],
        [167, 173, 195],
        ...,
        [164, 154, 165],
        [143, 127, 138],
        [124, 104, 115]],

       [[165, 171, 193],
        [165, 171, 193],
        [166, 172, 194],
        ...,
        [169, 161, 172],
        [153, 140, 150],
        [136, 118, 130]],

       [[165, 171, 193],
        [166, 172, 194],
        [167, 173, 195],
        ...,
        [173, 165, 178],
        [158, 146, 158],
        [143, 125, 137]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/home/user/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/modules/img2img.py", line 171, in img2img
    processed = process_images(p)
  File "/home/user/stable-diffusion-webui/modules/processing.py", line 488, in process_images
    res = process_images_inner(p)
  File "/home/user/stable-diffusion-webui/modules/processing.py", line 634, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/home/user/stable-diffusion-webui/modules/processing.py", line 1050, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/home/user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 322, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "/home/user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 322, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 117, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/home/user/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 190, in forward2
    return forward(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 133, in forward
    control = param.control_model(x=x_in, hint=param.hint_cond, timesteps=timesteps, context=context)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 115, in forward
    return self.control_model(*args, **kwargs)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 370, in forward
    guided_hint = self.input_hint_block(cond_cast_unet(hint), emb, context)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 86, in forward
    x = layer(x)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (c10::Half) should be the same
```
I can understand that tensor type mismatch is the problem, but I don't know where to fix.
Did anyone solve the problem or can guide me to fix it?

**Comment by Mikubill** [comment]
Check if control var is none, float or other non-array input

**Comment by KreataWorld** [comment]
@Mikubill 
Sorry for misleading.
I added modifying control part so that someone with A770 might reproduce it. That part works without error.
Just to note, control dtype is float32.

That being said, I myself can't reproduce the problem now. Another problem related to Intel extension for Pytorch makes the problem hang... I guess I would have to solve that first.

**Comment by Lioric** [comment]
in controlnet.py, the tensor needs to be sent to the cpu to workaround the lack of FP64 in Intel dGPU hardware (not even emulation! what a mess), but it needs to be returned to XPU device to continue the pipeline

```
       # for log use
        detected_map = rearrange(detected_map, 'c h w -> h w c').numpy().astype(np.uint8)
        return control.to(devices.get_device_for("controlnet")), detected_map
```

and then it works, at least the openpose model:

![image](https://user-images.githubusercontent.com/7177570/227827236-b1baf353-a5f4-4b84-923f-f675f6baab7e.png)

**Comment by Lioric** [comment]
The Low VRAM code path needs to be patched as well, as it ends up with tensors in both devices (cpu and xpu), but not really sure if it is needed for ARC gpus after all, as the lowest is 8GB, so probably is better to just disable it
