### ISSUE TITLE
Why don't I have some settings?

### ISSUE THREAD

**Issue by AndreyRGW** [Mikubill/sd-webui-controlnet#380]
[Aitrepreneur settings](https://imgur.com/a/hkbYhGe)

[My settings](https://imgur.com/a/dsFf95o)

Also: 

```
Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "F:\WBC\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\WBC\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\WBC\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 118, in <module>
    add_axis_options(xyz_grid)
  File "F:\WBC\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 102, in add_axis_options
    AxisOption("[ControlNet] Model", str, apply_field("control_net_model"), choices=choices_model, confirm=confirm_model, cost=0.9),
  File "F:\WBC\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 37, in __new__
    this = super().__new__(xyz_grid.AxisOption)
TypeError: AxisOption.__new__() missing 5 required positional arguments: 'label', 'type', 'apply', 'format_value', and 'confirm'
```

**Comment by ClashSAN** [comment]
@AndreyRGW (you forgot to post webui and extension commit)

**Comment by AndreyRGW** [comment]
> @AndreyRGW (you forgot to post webui and extension commit)

I don't know which sd commit I'm using, but it's from February 20. But I tried the latest one extension commit and [this one.](https://github.com/Mikubill/sd-webui-controlnet/tree/695f72cdc41d1e634317e2e49c44d4c5122e2f2e)

**Comment by AndreyRGW** [comment]
I deleted the SD and downloaded a clean commit, put controlnet there and all the settings appeared.....

**Comment by ljleb** [comment]
Indeed, you have to be on the latest version to get the latest features. I'm closing this, feel free to reopen or open a new issue if the problem persists.
