### ISSUE TITLE
Error Completing Request

### ISSUE THREAD

**Issue by iSirIvan** [Mikubill/sd-webui-controlnet#386]
Any why this error is happening and how to fix it?
Arguments: ('task(g06caquifeclqsc)', 'masterpiece, 1girl, mythra (xenoblade), blonde long hair, detailed yellow eyes, full body, medium breast, green cross on her chest, white dress, <lora:pyraMythraPneuma_50Epochs:0.7>\n', '(worst quality, low quality:1.4), bad_prompt_version2, bad-artist, disfigured, loli, child, big breasts, weird hands, bad anatomy, bad proportions, bad hands, muscular body, weird fingers, melting face, long eyes, weird eyes', [], 20, 0, False, False, 1, 1, 7, 2575771268.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'Refresh models', False, True, 'openpose', 'control_openpose-fp16 [9ca67cc5]', 1, {'image': array([[[0, 0, 0],

[0, 0, 0],

[0, 0, 0],

...,

[0, 0, 0],

[0, 0, 0],

[0, 0, 0]],

[[0, 0, 0],

[0, 0, 0],

[0, 0, 0],

...,

[0, 0, 0],

[0, 0, 0],

[0, 0, 0]],

[[0, 0, 0],

[0, 0, 0],

[0, 0, 0],

...,

[0, 0, 0],

[0, 0, 0],

[0, 0, 0]],

...,

[[0, 0, 0],

[0, 0, 0],

[0, 0, 0],

...,

[0, 0, 0],

[0, 0, 0],

[0, 0, 0]],

[[0, 0, 0],

[0, 0, 0],

[0, 0, 0],

...,

[0, 0, 0],

[0, 0, 0],

[0, 0, 0]],

[[0, 0, 0],

[0, 0, 0],

[0, 0, 0],

...,

[0, 0, 0],

[0, 0, 0],

[0, 0, 0]]], dtype=uint8), 'mask': array([[[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

...,

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255]],

[[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

...,

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255]],

[[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

...,

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255]],

...,

[[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

...,

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255]],

[[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

...,

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255]],

[[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

...,

[ 0, 0, 0, 255],

[ 0, 0, 0, 255],

[ 0, 0, 0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, True, 512, 64, 64, 1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}

Traceback (most recent call last):

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\call_queue.py", line 56, in f

res = list(func(*args, **kwargs))

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\call_queue.py", line 37, in f

res = func(*args, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\[txt2img.py](https://txt2img.py/)", line 56, in txt2img

processed = process_images(p)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\[processing.py](https://processing.py/)", line 486, in process_images

res = process_images_inner(p)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\[processing.py](https://processing.py/)", line 632, in process_images_inner

samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\[processing.py](https://processing.py/)", line 832, in sample

samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 349, in sample

samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling

return func()

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>

samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context

return func(*args, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\[sampling.py](https://sampling.py/)", line 145, in sample_euler_ancestral

denoised = model(x, sigmas[i] * s_in, **extra_args)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 117, in forward

x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\[external.py](https://external.py/)", line 112, in forward

eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\[external.py](https://external.py/)", line 138, in get_eps

return self.inner_model.apply_model(*args, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>

setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__

return self.__orig_func(*args, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\[ddpm.py](https://ddpm.py/)", line 858, in apply_model

x_recon = self.model(x_noisy, t, **cond)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\[ddpm.py](https://ddpm.py/)", line 1329, in forward

out = self.diffusion_model(x, t, context=cc)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\[hook.py](https://hook.py/)", line 190, in forward2

return forward(*args, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\[hook.py](https://hook.py/)", line 133, in forward

control = param.control_model(x=x_in, hint=param.hint_cond, timesteps=timesteps, context=context)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\[cldm.py](https://cldm.py/)", line 115, in forward

return self.control_model(*args, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\[cldm.py](https://cldm.py/)", line 383, in forward

h = module(h, emb, context)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\[openaimodel.py](https://openaimodel.py/)", line 84, in forward

x = layer(x, context)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\[attention.py](https://attention.py/)", line 324, in forward

x = block(x, context=context[i])

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\[attention.py](https://attention.py/)", line 259, in forward

return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\[util.py](https://util.py/)", line 114, in checkpoint

return CheckpointFunction.apply(func, len(inputs), *args)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\[util.py](https://util.py/)", line 129, in forward

output_tensors = ctx.run_function(*ctx.input_tensors)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\[attention.py](https://attention.py/)", line 264, in _forward

x = self.ff(self.norm3(x)) + x

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\[attention.py](https://attention.py/)", line 73, in forward

return [self.net](https://self.net/)(x)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[container.py](https://container.py/)", line 204, in forward

input = module(input)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\[module.py](https://module.py/)", line 1194, in _call_impl

return forward_call(*input, **kwargs)

File "D:\Herramientas\AI\STABLE\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\[attention.py](https://attention.py/)", line 53, in forward

return x * F.gelu(gate)

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.42 GiB already allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by samsonsite1** [comment]
Not enough GPU memory.  You only have a 4GB card.  Reduce your image size and/or check the "Low VRAM" checkbox.
