### ISSUE TITLE
[Bug]: segmentation error

### ISSUE THREAD

**Issue by DJChief** [Mikubill/sd-webui-controlnet#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

MacOS Monterey
Automatic1111 
Chrome browser

tried to use controlnet segmentation to generate image2image + segmentation map, gives weird result and no seg map

### Steps to reproduce the problem

1. Go to .... segmentation model and preprocessor
2. Press ....generate 
3. ...

### What should have happened?

image to image file + segmentation map

### Commit where the problem happens

webui: commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)

controlnet:  ControlNet-0 Enabled: True, ControlNet-0 Module: segmentation, ControlNet-0 Model: control_sd15_seg [fef5e48e], ControlNet-0 Weight: 1, ControlNet-0 Guidance Strength: 1

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Loading model: control_sd15_seg [fef5e48e]
Loaded state_dict from [/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_sd15_seg.pth]
ControlNet model control_sd15_seg [fef5e48e] loaded.
Loading preprocessor: segmentation
Error running process: /Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/Users/chief/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 611, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 155, in uniformer
    from annotator.uniformer import apply_uniformer
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/__init__.py", line 1, in <module>
    from annotator.uniformer.mmseg.apis import init_segmentor, inference_segmentor, show_result_pyplot
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/mmseg/apis/inference.py", line 8, in <module>
    from annotator.uniformer.mmseg.models import build_segmentor
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/mmseg/models/__init__.py", line 4, in <module>
    from .decode_heads import *  # noqa: F401,F403
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/mmseg/models/decode_heads/__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/mmseg/models/decode_heads/cc_head.py", line 7, in <module>
    from annotator.uniformer.mmcv.ops import CrissCrossAttention
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/mmcv/ops/__init__.py", line 10, in <module>
    from .corner_pool import CornerPool
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/mmcv/ops/corner_pool.py", line 8, in <module>
    ext_module = ext_loader.load_ext('_ext', [
  File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: top_pool_forward miss in module _ext
```

**Comment by Mikubill** [comment]
see https://github.com/Mikubill/sd-webui-controlnet/issues/70
