### ISSUE TITLE
[Bug]: SyntaxError: invalid syntax ( := operator in python 3.7)

### ISSUE THREAD

**Issue by GrennKren** [Mikubill/sd-webui-controlnet#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

This has been happening since yesterday.
I'm using Kaggle's online Jupyter Notebook, which is still in Python 3.7.

Probably since 81aabe1 commit.

I also have tested it in python 3.8 in virtual environment and it's work though

### Steps to reproduce the problem

After webui trying to load controlnet extension

### What should have happened?

Load the extension correctly.

### Commit where the problem happens

webui:\t\t 0cc0ee1
controlnet:\t 7377d49

### Command Line Arguments

```Shell
--share 
--xformers 
--lowram 
--no-hashing 
--no-half-vae 
--lora-dir /kaggle/working/stable-diffusion-webui/models/Lora 
--ckpt-dir /kaggle/models/Stable-diffusion 
--hypernetwork-dir /kaggle/models/hypernetworks 
--disable-console-progressbars 
--enable-insecure-extension-access
```

### Console logs

```Shell
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI


Launching Web UI with arguments: --share --xformers --lowram --no-hashing --no-half-vae --lora-dir /kaggle/working/stable-diffusion-webui/models/Lora --ckpt-dir /kaggle/models/Stable-diffusion --hypernetwork-dir /kaggle/models/hypernetworks --disable-console-progressbars --enable-insecure-extension-access
Error loading script: xyz_grid_support.py 

Traceback (most recent call last): 
File "/kaggle/working/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts 
script_module = script_loading.load_module(scriptfile.path) 
File "/kaggle/working/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module 
module_spec.loader.exec_module(module) 
File "<frozen importlib._bootstrap_external>", line 724, in exec_module 
File "<frozen importlib._bootstrap_external>", line 860, in get_code 
File "<frozen importlib._bootstrap_external>", line 791, in source_to_code 
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
File "/kaggle/working/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/xyz_grid_support.py", line 146 
if s != (s := search_bracket(s, "[", replace="")): 
           ^ 

SyntaxError: invalid syntax
Loading weights [None] from /kaggle/models/Stable-diffusion/Cheese_Daddy_Landscapes_mix.safetensors 
Creating model from config: /kaggle/working/stable-diffusion-webui/configs/v1-inference.yaml 
LatentDiffusion: Running in eps-prediction mode 
DiffusionWrapper has 859.52 M params. 
Loading VAE weights found near the checkpoint: /kaggle/models/Stable-diffusion/Cheese_Daddy_Landscapes_mix.vae.pt 
Applying xformers cross attention optimization. 
Textual inversion embeddings loaded(4): verybadimagenegative_v1.1-6400, EasyNegative, bad-artist, ng_deepnegative_v1_75t 
Model loaded in 23.9s
```

### Additional information

Kaggle Notebook
Python 3.7

**Comment by Mikubill** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/e67ee2730457867f78cdbffd6361626abfed30e8

**Comment by GrennKren** [comment]
Thank you!
