### ISSUE TITLE
throw exceptions when starting use openpose

### ISSUE THREAD

**Issue by sean220** [Mikubill/sd-webui-controlnet#448]
Loaded state_dict from [C:\Workspace\novelai-webui-aki-v2\extensions\sd-webui-controlnet\models\control_openpose.pth]
Error running process: C:\Workspace\novelai-webui-aki-v2\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Workspace\novelai-webui-aki-v2\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\Workspace\novelai-webui-aki-v2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 612, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "C:\Workspace\novelai-webui-aki-v2\extensions\sd-webui-controlnet\scripts\controlnet.py", line 471, in build_control_model
    network = network_module(
  File "C:\Workspace\novelai-webui-aki-v2\extensions\sd-webui-controlnet\scripts\cldm.py", line 64, in __init__
    self.control_model = ControlNet(**config.model.params.control_stage_config.params)
  File "C:\Workspace\novelai-webui-aki-v2\py310\lib\site-packages\omegaconf\dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "C:\Workspace\novelai-webui-aki-v2\py310\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "C:\Workspace\novelai-webui-aki-v2\py310\lib\site-packages\omegaconf\_utils.py", line 900, in format_and_raise
    _raise(ex, cause)

**Comment by Mudereded401** [comment]
Exact same error :/

 For some reason any of the models works for me
