### ISSUE TITLE
[Bug]: T2I with multi-controlnet canny and HED throws `AttributeError: 'NoneType' object has no attribute 'split'`

### ISSUE THREAD

**Issue by oliverban** [Mikubill/sd-webui-controlnet#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Tried to render in t2i with controlnet set to Canny and HED, which worked fine with one. But then I added a second one with Guess Mode and got this:
Traceback (most recent call last):
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\olive\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 361, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1508, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 53, in decode_base64_to_image
    content = encoding.split(";")[1]
AttributeError: 'NoneType' object has no attribute 'split'

### Steps to reproduce the problem

1. Go to t2i
2. write some words like sword, helmet
3. Select Canny for cn1 and HED for cn2 and then have Guess Mode on for cn1
4. Hit generate

### What should have happened?

A render should have gone through and started showing me a render

### Commit where the problem happens

webui: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
controlnet: latest as of today (2023-03-02 21:55)

### Command Line Arguments

```Shell
--xformers --no-half-vae --no-half --deepdanbooru --autolaunch
```

### Console logs

```Shell
Loading model: difference_controlSd15Canny [ea6e3b9c]
Loaded state_dict from [C:\Users\XXXXXX\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\models\difference_controlSd15Canny.safetensors]
Offset cloned: 298 values
ControlNet model difference_controlSd15Canny [ea6e3b9c] loaded.
Loading preprocessor: canny
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:09<00:00,  3.27it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.60it/s]
Loading preprocessor: canny
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.56it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:08<00:00,  3.58it/s]
Traceback (most recent call last):
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\olive\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 361, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1508, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 53, in decode_base64_to_image
    content = encoding.split(";")[1]
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\olive\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 361, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1508, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 53, in decode_base64_to_image
    content = encoding.split(";")[1]
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\olive\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 361, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1508, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 53, in decode_base64_to_image
    content = encoding.split(";")[1]
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\olive\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 361, in svgPreprocess
    return input_image.orgpreprocess(inputs)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1508, in preprocess
    mask_im = processing_utils.decode_base64_to_image(mask)
  File "C:\Users\olive\Documents\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 53, in decode_base64_to_image
    content = encoding.split(";")[1]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by JuanuMusic** [comment]
I am actually experiencing this exact same problem.

**Comment by IgorDyx** [comment]
The same problem. After updating in the tab extensions openpose-editor and sd-webui-controlnet they just broke and doesnt work at all. I had error like in this topics and "ffmpy.FFExecutableNotFoundError: Executable 'ffmpeg' not found"
Now I have this 
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 349, in create_canvas
    return np.zeros(shape=(h, w, 3), dtype=np.uint8) + 255
TypeError: 'str' object cannot be interpreted as an integer
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "F:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "F:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "F:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 402, in predict
    if app.get_blocks().dependencies[fn_index_inferred]["cancels"]:
IndexError: list index out of range
Error running process: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 612, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "F:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 448, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None

**Comment by ImranBug** [comment]
I am facing the same problem but with only Canny model.
