### ISSUE TITLE
Feature request: support for new T2i Color (Spatial Palette) Adapter 

### ISSUE THREAD

**Issue by AugmentedRealityCat** [Mikubill/sd-webui-controlnet#476]
New T2i models have been released, and one of them is the T2i Color (Spatial Palette)  Adapter.

![222764508-aa469078-30a9-4271-9f23-57036abe6d48](https://user-images.githubusercontent.com/114955776/222844312-aed2c19d-ed05-4c06-bd7d-5590ce1e90ab.png)

I've downloaded the model over here:
https://huggingface.co/TencentARC/T2I-Adapter/tree/main/models

I've installed it with the other T2i and ControlNet models in `stable-diffusion-webui-master\extensions\sd-webui-controlnet\models`

So far I haven't been able to make it work. If I activate it I do get to generate an image, but that image is identical to the one I get without the T2i adapter activated - basically it has no effect. It also spills out the following error :
```

Loading model: t2iadapter_color_sd14v1 [8522029d]
Loaded state_dict from [C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\models\t2iadapter_color_sd14v1.pth]
Error running process: C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 608, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\controlnet.py", line 467, in build_control_model
    network = network_module(
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-controlnet\scripts\adapter.py", line 65, in __init__
    self.control_model.load_state_dict(state_dict)
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Adapter:
        Missing key(s) in state_dict: "body.0.block1.weight", "body.0.block1.bias", "body.0.block2.weight", "body.0.block2.bias", "body.1.block1.weight", "body.1.block1.bias", "body.1.block2.weight", "body.1.block2.bias", "body.2.block1.weight", "body.2.block1.bias", "body.2.block2.weight", "body.2.block2.bias", "body.3.block1.weight", "body.3.block1.bias", "body.3.block2.weight", "body.3.block2.bias", "body.4.in_conv.weight", "body.4.in_conv.bias", "body.4.block1.weight", "body.4.block1.bias", "body.4.block2.weight", "body.4.block2.bias", "body.5.block1.weight", "body.5.block1.bias", "body.5.block2.weight", "body.5.block2.bias", "body.6.block1.weight", "body.6.block1.bias", "body.6.block2.weight", "body.6.block2.bias", "body.7.block1.weight", "body.7.block1.bias", "body.7.block2.weight", "body.7.block2.bias", "conv_in.weight", "conv_in.bias".
        Unexpected key(s) in state_dict: "body.0.in_conv.weight", "body.0.in_conv.bias", "body.0.body.0.block1.weight", "body.0.body.0.block1.bias", "body.0.body.0.block2.weight", "body.0.body.0.block2.bias", "body.0.body.1.block1.weight", "body.0.body.1.block1.bias", "body.0.body.1.block2.weight", "body.0.body.1.block2.bias", "body.0.body.2.block1.weight", "body.0.body.2.block1.bias", "body.0.body.2.block2.weight", "body.0.body.2.block2.bias", "body.0.body.3.block1.weight", "body.0.body.3.block1.bias", "body.0.body.3.block2.weight", "body.0.body.3.block2.bias", "body.0.out_conv.weight", "body.0.out_conv.bias", "body.1.in_conv.weight", "body.1.in_conv.bias", "body.1.body.0.block1.weight", "body.1.body.0.block1.bias", "body.1.body.0.block2.weight", "body.1.body.0.block2.bias", "body.1.body.1.block1.weight", "body.1.body.1.block1.bias", "body.1.body.1.block2.weight", "body.1.body.1.block2.bias", "body.1.body.2.block1.weight", "body.1.body.2.block1.bias", "body.1.body.2.block2.weight", "body.1.body.2.block2.bias", "body.1.body.3.block1.weight", "body.1.body.3.block1.bias", "body.1.body.3.block2.weight", "body.1.body.3.block2.bias", "body.1.out_conv.weight", "body.1.out_conv.bias", "body.2.body.0.block1.weight", "body.2.body.0.block1.bias", "body.2.body.0.block2.weight", "body.2.body.0.block2.bias", "body.2.body.1.block1.weight", "body.2.body.1.block1.bias", "body.2.body.1.block2.weight", "body.2.body.1.block2.bias", "body.2.body.2.block1.weight", "body.2.body.2.block1.bias", "body.2.body.2.block2.weight", "body.2.body.2.block2.bias", "body.2.body.3.block1.weight", "body.2.body.3.block1.bias", "body.2.body.3.block2.weight", "body.2.body.3.block2.bias", "body.2.out_conv.weight", "body.2.out_conv.bias", "body.3.in_conv.weight", "body.3.in_conv.bias", "body.3.body.0.block1.weight", "body.3.body.0.block1.bias", "body.3.body.0.block2.weight", "body.3.body.0.block2.bias", "body.3.body.1.block1.weight", "body.3.body.1.block1.bias", "body.3.body.1.block2.weight", "body.3.body.1.block2.bias", "body.3.body.2.block1.weight", "body.3.body.2.block1.bias", "body.3.body.2.block2.weight", "body.3.body.2.block2.bias", "body.3.body.3.block1.weight", "body.3.body.3.block1.bias", "body.3.body.3.block2.weight", "body.3.body.3.block2.bias", "body.3.out_conv.weight", "body.3.out_conv.bias".
        size mismatch for body.2.in_conv.weight: copying a param with shape torch.Size([320, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([640, 320, 1, 1]).
        size mismatch for body.2.in_conv.bias: copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is torch.Size([640]).

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.36it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.01it/s]
```

**Comment by soysanti** [comment]
my solution was to use these: https://huggingface.co/TencentARC/T2I-Adapter/tree/main/models

**Comment by xucanjie** [comment]
I guess that you need to put the file "t2iadapter_color_sd14v1.yaml" in the same folder as the file "/models/ControlNet/t2iadapter_color_sd14v1.pth".

**Comment by soysanti** [comment]
thanks for answering. I have that file, I'm using light models.

This was the one that didn't work for me t2iadapter_style-fp16.safetensors

and now I use this one that works for me. t2iadapter_style_sd14v1.pth
