### ISSUE TITLE
[Bug]: Segmentation Error: 'Uniformer is already registered in models'

### ISSUE THREAD

**Issue by EmoryQ** [Mikubill/sd-webui-controlnet#488]
When I try to run a segmentation preprocessor, I get this error.

'Uniformer is already registered in models'

I did a complete fresh reinstall of Automatic1111, and ControlNet is the only extension installed, but the issue persists.

```
Error running process: C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 657, in process
    detected_map = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 157, in uniformer
    result = model_uniformer(img)
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\__init__.py", line 33, in apply_uniformer
    model = init_segmentor(config_file, modelpath)
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\inference.py", line 31, in init_segmentor
    config = mmcv.Config.fromfile(config)
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\config.py", line 334, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\uniformer.py", line 247, in <module>
    class UniFormer(nn.Module):
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\registry.py", line 311, in _register
    self._register_module(
  File "C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'UniFormer is already registered in models'
```

**Comment by EmoryQ** [comment]
This is what the console was showing right before the error:

```
Loading model: control_sd15_seg [fef5e48e]
Loaded state_dict from [C:\SD\AUTOMATIC1111\stable-diffusion-webui\models\ControlNet\control_sd15_seg.pth]
ControlNet model control_sd15_seg [fef5e48e] loaded.
Loading preprocessor: segmentation
Downloading: "https://huggingface.co/lllyasviel/ControlNet/resolve/main/annotator/ckpts/upernet_global_small.pth" to C:\SD\AUTOMATIC1111\stable-diffusion-webui\models\uniformer\upernet_global_small.pth

100%|██████████████████████████████████████████████████████████████| 197M/197M [00:13<00:00, 15.8MB/s]
Error running process: C:\SD\AUTOMATIC1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
```

**Comment by EmoryQ** [comment]
> Try with the latest commit.

Yes, this fixed it. That was so fast! Thank you so much!
