### ISSUE TITLE
[Bug]: Preview annotator result broken after Update

### ISSUE THREAD

**Issue by derappelt** [Mikubill/sd-webui-controlnet#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Since update today the "Preview annotator result" is broken for me.

### Steps to reproduce the problem

1. Load Image
2. Press "Preview annotator result"

### What should have happened?

Preview of annotator result showing up

### Commit where the problem happens

webui: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
controlnet: eab5bc08cb87c0ed2da53399cf402b20bfc0bb3c

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\DerAppelt\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\DerAppelt\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\DerAppelt\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 947, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "C:\Users\DerAppelt\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 379, in postprocess_update_dict
    prediction_value["value"] = block.postprocess(prediction_value["value"])
  File "C:\Users\DerAppelt\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1534, in postprocess
    raise ValueError("Cannot process this value as an Image")
ValueError: Cannot process this value as an Image
```

**Comment by RayHell** [comment]
I confirm

**Comment by Mikubill** [comment]
Fixed in https://github.com/Mikubill/sd-webui-controlnet/commit/63f7d3c2a6c451a64e9e1e8c4af21a774b6b85d1

**Comment by derappelt** [comment]
Wow that reaction speed is awesome.
@Mikubill Thanks a lot for you great work!
