### ISSUE TITLE
[Bug]: Style Adapter: Tensors must have same number of dimensions

### ISSUE THREAD

**Issue by kft334** [Mikubill/sd-webui-controlnet#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

This is the only adapter that doesn't work for me. All others work as expected. The error happens with both the API and webui.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

The style adapter should have worked.

### Commit where the problem happens

Style adapter commit...

### Command Line Arguments

```Shell
--api --ckpt-dir "D:\Models+" --disable-safe-unpickle --reinstall-xformers --reinstall-torch --xformers
```

### Console logs

```Shell
Loading model: t2iadapter_style_sd14v1 [202e85cc]
Loaded state_dict from [D:\Repos\ControlNet\models\Extracted\t2iadapter_style_sd14v1.pth]
ControlNet model t2iadapter_style_sd14v1 [202e85cc] loaded.
Loading preprocessor: none
  0%|                                                                                           | 0/50 [00:00<?, ?it/s]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Automatic1111\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\Automatic1111\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "C:\Automatic1111\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Automatic1111\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Automatic1111\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Automatic1111\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\base.py", line 104, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Automatic1111\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Automatic1111\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Automatic1111\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Automatic1111\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Automatic1111\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Automatic1111\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Automatic1111\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Automatic1111\extensions\sd-webui-controlnet\scripts\api.py", line 106, in controlnet_txt2img
    return self.controlnet_any2img(
  File "C:\Automatic1111\extensions\sd-webui-controlnet\scripts\api.py", line 129, in controlnet_any2img
    return original_callback(self_copy, any2img_request)
  File "C:\Automatic1111\modules\api\api.py", line 203, in text2imgapi
    processed = process_images(p)
  File "C:\Automatic1111\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Automatic1111\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Automatic1111\modules\processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Automatic1111\modules\sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Automatic1111\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "C:\Automatic1111\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Automatic1111\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Automatic1111\repositories\k-diffusion\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\modules\sd_samplers_kdiffusion.py", line 136, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Automatic1111\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Automatic1111\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Automatic1111\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Automatic1111\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\extensions\sd-webui-controlnet\scripts\hook.py", line 212, in forward2
    return forward(*args, **kwargs)
  File "C:\Automatic1111\extensions\sd-webui-controlnet\scripts\hook.py", line 139, in forward
    control = param.control_model(x=x_in, hint=param.hint_cond, timesteps=timesteps, context=context)
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\extensions\sd-webui-controlnet\scripts\adapter.py", line 104, in forward
    self.control = self.control_model(hint_in)
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\extensions\sd-webui-controlnet\scripts\adapter.py", line 324, in forward
    x = torch.cat([x, style_embedding], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 4 and 3
```

### Additional information

Configuration file used:

model:
  target: scripts.adapter.StyleAdapter
  params:
    width: 1024
    context_dim: 768
    num_head: 8
    n_layes: 3
    num_token: 8

**Comment by kft334** [comment]
The same error happens with txt2img after getting the error with the style adapter. Restarting A1111 stopped the error from happening with txt2img.

**Comment by kft334** [comment]
Resolved

**Comment by D-Mad** [comment]
hi ,how to fix RuntimeError: Tensors must have same number of dimensions: got 4 and 3 ?
