### ISSUE TITLE
[Bug]: No support for Guess mode for Adapters?

### ISSUE THREAD

**Issue by matrix4767** [Mikubill/sd-webui-controlnet#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Got an error when trying to use Guess Mode with color adapter.

### Steps to reproduce the problem

1. Go to Controlnet tab.
2. Select preprocessor and adapter for color.
3. Turn Guess Mode on.
4. Click Generate.

### What should have happened?

Guess Mode working for the Adapter model.

### Commit where the problem happens

webui: 0cc0ee1
controlnet: 84a2b22d 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers --api
```

### Console logs

```Shell
Traceback (most recent call last):
  File "G:\stable-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "G:\stable-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "G:\stable-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "G:\stable-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "G:\stable-webui\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "G:\stable-webui\modules\processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "G:\stable-webui\modules\sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "G:\stable-webui\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "G:\stable-webui\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "G:\stable-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "G:\stable-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "G:\stable-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\stable-webui\modules\sd_samplers_kdiffusion.py", line 136, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
  File "G:\stable-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\stable-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "G:\stable-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "G:\stable-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "G:\stable-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "G:\stable-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "G:\stable-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\stable-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "G:\stable-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\stable-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 212, in forward2
    return forward(*args, **kwargs)
  File "G:\stable-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 150, in forward
    control_scales = param.weight * [0.25, 0.62, 0.825, 1.0]
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by Mikubill** [comment]
Currently color adapter and style adapter not working with guess mode. We will add support later.
