### ISSUE TITLE
Segmentation dont work give a lot of errors!?

### ISSUE THREAD

**Issue by merecesarchviz** [Mikubill/sd-webui-controlnet#510]
hi

All the other models works well but the segmentation one give all this errors!:

Loading preprocessor: segmentation
Error running process: F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\inference.py", line 8, in <module>
    from mmseg.datasets.pipelines import Compose
ModuleNotFoundError: No module named 'mmseg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 753, in process
    detected_map, is_image = preprocessor(input_image, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 155, in uniformer
    from annotator.uniformer import apply_uniformer
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\__init__.py", line 4, in <module>
    from annotator.uniformer.inference import init_segmentor, inference_segmentor, show_result_pyplot
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\inference.py", line 15, in <module>
    from annotator.mmpkg.mmseg.models import build_segmentor
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmseg\models\__init__.py", line 4, in <module>
    from .decode_heads import *  # noqa: F401,F403
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmseg\models\decode_heads\__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmseg\models\decode_heads\cc_head.py", line 7, in <module>
    from annotator.mmpkg.mmcv.ops import CrissCrossAttention
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\ops\__init__.py", line 10, in <module>
    from .corner_pool import CornerPool
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\ops\corner_pool.py", line 8, in <module>
    ext_module = ext_loader.load_ext('_ext', [
  File "F:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: top_pool_forward miss in module _ext

**Comment by Mikubill** [comment]
Consider install [mmsegmentation](https://github.com/open-mmlab/mmsegmentation) or uninstall mmcv/mmcv-full

**Comment by merecesarchviz** [comment]
This is the last updated version of the extension, how we can install the mmsegmentation that you refer in the extension?

**Comment by Mikubill** [comment]
Update the extension to the latest version, (check if already fixed), then use `pip install mmdet mmsegmentation` to install the mmsegmentation. (don't forget to activate venv)
If segmentation still broken after installation, follow the instructions in https://github.com/Mikubill/sd-webui-controlnet/issues/485#issuecomment-1454739555
