### ISSUE TITLE
Preprocessor of segmentation dont work

### ISSUE THREAD

**Issue by 0n0gard** [Mikubill/sd-webui-controlnet#516]
When I click the button of "Preview annotator result" by using segmentation Preprocessor, there is an error:
```
Traceback (most recent call last):
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\inference.py", line 5, in <module>
    import mmcv as mmcv
ModuleNotFoundError: No module named 'mmcv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 448, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 155, in uniformer
    from annotator.uniformer import apply_uniformer
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\__init__.py", line 4, in <module>
    from annotator.uniformer.inference import init_segmentor, inference_segmentor, show_result_pyplot
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\inference.py", line 11, in <module>
    import annotator.mmpkg.mmcv as mmcv
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\__init__.py", line 4, in <module>
    from .fileio import *
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\fileio\file_client.py", line 15, in <module>
    from annotator.mmpkg.mmcv.utils.misc import has_method
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\__init__.py", line 39, in <module>
    from .env import collect_env
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\env.py", line 13, in <module>
    from .parrots_wrapper import get_build_config
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\parrots_wrapper.py", line 94, in <module>
    BuildExtension, CppExtension, CUDAExtension = _get_extension()
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\mmpkg\mmcv\utils\parrots_wrapper.py", line 64, in _get_extension
    from torch.utils.cpp_extension import (BuildExtension, CppExtension,
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 202, in <module>
    MIOPEN_HOME = _join_rocm_home('miopen') if ROCM_HOME else None
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 155, in _join_rocm_home
    raise EnvironmentError('Building PyTorch extensions using '
OSError: Building PyTorch extensions using ROCm and Windows is not supported.
```

Then I follow this:
https://github.com/Mikubill/sd-webui-controlnet/issues/485#issuecomment-1454739555

But still dont work, and the new error is:
```
Traceback (most recent call last):
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 448, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 155, in uniformer
    from annotator.uniformer import apply_uniformer
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\__init__.py", line 4, in <module>
    from annotator.uniformer.inference import init_segmentor, inference_segmentor, show_result_pyplot
  File "E:\gitRepository\AIGC\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\inference.py", line 5, in <module>
    import mmcv as mmcv
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\mmcv\__init__.py", line 6, in <module>
    from .fileio import *
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\mmcv\fileio\file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\__init__.py", line 41, in <module>
    from .env import collect_env
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\env.py", line 13, in <module>
    from .parrots_wrapper import get_build_config
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\parrots_wrapper.py", line 101, in <module>
    BuildExtension, CppExtension, CUDAExtension = _get_extension()
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\mmcv\utils\parrots_wrapper.py", line 71, in _get_extension
    from torch.utils.cpp_extension import (BuildExtension, CppExtension,
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 202, in <module>
    MIOPEN_HOME = _join_rocm_home('miopen') if ROCM_HOME else None
  File "E:\gitRepository\AIGC\stable-diffusion-webui\venv\lib\site-packages\torch\utils\cpp_extension.py", line 155, in _join_rocm_home
    raise EnvironmentError('Building PyTorch extensions using '
OSError: Building PyTorch extensions using ROCm and Windows is not supported.
```

Any help is appreciated!!!

**Comment by 0n0gard** [comment]
update extension to solve this error
