### ISSUE TITLE
[Bug]: T2I Adapter fails when using hires.fix

### ISSUE THREAD

**Issue by SasebonoShigure** [Mikubill/sd-webui-controlnet#530]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I'm using `t2iadapter_openpose_sd14v1.pth` with `image_adapter_v14.yaml`. T2I Adapter functions normally when I'm generating a 448*640 image. However, when I enabled hires.fix (from 448x640 to 896x1280), it raised error. This happens regardless of me checking or unchecking `Use mid-control on highres pass (second pass)` in settings. At the same time, the control-openpose model is fine with me. I also checked t2iadapter-canny and t2iadapter-depth, they all functioned normally without hires.fix and raised error with it.

### Steps to reproduce the problem

in txt2img.
Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1756929634, Size: 448x640, Model hash: 59ea4aa1d8, Model: cetusMix_cetusVersion3, Denoising strength: 0.6, Clip skip: 2, ENSD: 31337, ControlNet-0 Enabled: True, ControlNet-0 Module: openpose, ControlNet-0 Model: t2iadapter_openpose_sd14v1 [7e267e5e], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1, Hires upscale: 2, Hires steps: 25, Hires upscaler: R-ESRGAN 4x+ Anime6B

### What should have happened?

It should generate image normally.( ? )

### Commit where the problem happens

webui: `0cc0ee1`
controlnet: `fed7a5`

### Command Line Arguments

```Shell
--medvram --upcast-sampling --api --xformers
```

### Console logs

```Shell
Loading model: t2iadapter_openpose_sd14v1 [7e267e5e]
Loaded state_dict from [C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models\t2iadapter_openpose_sd14v1.pth]
ControlNet model t2iadapter_openpose_sd14v1 [7e267e5e] loaded.
Loading preprocessor: openpose
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.64it/s]
Total prTile 1/120it [03:03,  7.79it/s]
        Tile 2/12
        Tile 3/12
        Tile 4/12
        Tile 5/12
        Tile 6/12
        Tile 7/12
        Tile 8/12
        Tile 9/12
        Tile 10/12
        Tile 11/12
        Tile 12/12
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(c8mliw5ougrhpi5)', '(colorful:1.1),(masterpiece:1.2), best quality, masterpiece, highres, original, extremely detailed wallpaper, looking at viewer,1girl,elf, pointy ears , arms behind back,smile, very long hair,ponytail , blonde hair, hair between eyes, middle breasts ,[green eyes:yellow eyes:0.3],falling petals,( white flower hair ornament ),hair flower, hood down, hooded jacket,sneakers, solo, squatting, white footwear, white jacket,white background,', '(worst quality, low quality, extra digits:1.4),\n', [], 30, 15, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 640, 448, True, 0.6, 2, 'R-ESRGAN 4x+ Anime6B', 25, 0, 0, [], 0, False, '', False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'Refresh models', False, True, True, 'openpose', 't2iadapter_openpose_sd14v1 [7e267e5e]', 1, {'image': array([[[ 33,  39,  54],
        [ 33,  37,  50],
        [ 34,  37,  51],
        ...,
        [ 77,  73,  78],
        [ 78,  73,  80],
        [ 78,  72,  79]],

       [[ 32,  40,  55],
        [ 32,  37,  51],
        [ 32,  38,  52],
        ...,
        [ 77,  76,  82],
        [ 77,  74,  81],
        [ 78,  73,  79]],

       [[ 32,  39,  53],
        [ 32,  37,  52],
        [ 32,  38,  53],
        ...,
        [ 79,  77,  84],
        [ 77,  75,  82],
        [ 78,  74,  80]],

       ...,

       [[ 21,  26,  33],
        [ 21,  25,  33],
        [ 21,  27,  34],
        ...,
        [147, 173,  48],
        [146, 168,  54],
        [143, 163,  61]],

       [[ 22,  25,  35],
        [ 20,  25,  31],
        [ 20,  25,  33],
        ...,
        [147, 171,  48],
        [144, 168,  51],
        [146, 162,  62]],

       [[ 25,  27,  36],
        [ 20,  25,  33],
        [ 19,  25,  33],
        ...,
        [145, 172,  53],
        [147, 166,  58],
        [152, 162,  65]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 512, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, None, 50, False, '', '', True, 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', False, '', '', True, [], 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', False, False, '', '', True, 'Custom', 'HSL', 'abs(v)', 'abs(v)', 'abs(v)', '(2+v)/3', '1.0', '0.5', 'Auto [0,1]', -1, 1, 1, 0, False, '', False) {}
Traceback (most recent call last):
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 902, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, conditioning, unconditional_conditioning, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 322, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 322, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 136, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_unet.py", line 45, in apply_model
    return orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs).float()
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 227, in forward2
    return forward(*args, **kwargs)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 201, in forward
    h = cfg_based_adder(h, total_adapter.pop(0), require_inpaint_hijack, is_adapter=True)
  File "C:\Users\29694\Desktop\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 109, in cfg_based_adder
    return base + x
RuntimeError: The size of tensor a (112) must match the size of tensor b (56) at non-singleton dimension 3
```

**Comment by Neverdusk** [comment]
Chiming in to say I've had a similar error. I'm generating at 512x512 and doing a hires fix to 640x640. 

The metadata between the image output window says "RuntimeError: The size of tensor a (80) must match the size of tensor b (64) at non-singleton dimension 3".

**Comment by SasebonoShigure** [comment]
It has been fixed now. Thanks
