### ISSUE TITLE
[Bug]: Text2img color and style adapters throw runtime errors

### ISSUE THREAD

**Issue by orfeaus** [Mikubill/sd-webui-controlnet#540]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Errors thrown when trying to use new text2img style and color adapters on Mac.

### Steps to reproduce the problem

1. Go to automatic 1111 web ui
2. Enter prompt "a man."
3. Use default 512 x 512 resolution.
4. Enable controlnet and add an image.
5. Choose clip_vision or color from the preprocessor dropdown.
6. Chose the corresponding model.
7. Click generate button to generate an image.

Result:
- Nothing happens and an error is thrown in terminal.

### What should have happened?

- Should have generated an image using the style or color adapters.
- Other preprocessor / models (depth, canny, etc.) are working fine and do not throw an error.

### Commit where the problem happens

webui: 0cc0ee1
controlnet: ce365d1a

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
--upcast-sampling --no-half-vae --use-cpu interrogate
```

### Console logs

```Shell
Error for style:

Error completing request████                                                                                                                             | 4/75 [00:01<00:22,  3.11it/s]
Arguments: ('task(gi4k3jwtke8yfx8)', 'a bird in a snowstorm', '', [], 25, 0, False, False, 3, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, True, True, 'clip_vision', 't2iadapter_style_sd14v1 [202e85cc]', 1, {'image': array([[[15,  8,  7],
        [18,  8,  9],
        [16,  9, 10],
        ...,
        [ 5,  0,  0],
        [36, 18,  6],
        [52, 34, 17]],

       [[12,  6,  8],
        [16, 12, 11],
        [14,  8,  7],
        ...,
        [40, 28, 21],
        [33, 23, 15],
        [29, 11,  1]],

       [[20, 13, 13],
        [18, 11, 11],
        [22, 13, 13],
        ...,
        [28, 22, 18],
        [26, 26, 11],
        [42, 29, 19]],

       ...,

       [[37, 22, 21],
        [36, 18, 18],
        [48, 32, 25],
        ...,
        [73, 52, 41],
        [43, 23, 19],
        [51, 35, 30]],

       [[39, 25, 22],
        [43, 27, 22],
        [47, 33, 23],
        ...,
        [72, 47, 36],
        [79, 58, 45],
        [63, 38, 28]],

       [[40, 26, 23],
        [45, 27, 24],
        [49, 31, 26],
        ...,
        [87, 62, 47],
        [90, 69, 46],
        [99, 78, 62]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 512, 64, 64, 0.1, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, 50) {}
Traceback (most recent call last):
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 117, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 114, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 140, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_unet.py", line 45, in apply_model
    return orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs).float()
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 239, in forward2
    model.forward = forward2.__get__(model, UNetModel)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 135, in forward
    outer.batch_cond_available = False
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 105, in forward
    self.control = self.control_model(hint_in)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 326, in forward
    x = self.ln_pre(x)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 274, in forward
    ret = super().forward(x.type(torch.float32))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/mac_specific.py", line 42, in <lambda>
    CondFunc('torch.nn.functional.layer_norm', lambda orig_func, *args, **kwargs: orig_func(*([args[0].contiguous()] + list(args[1:])), **kwargs),
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2503, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: !(has_different_input_dtypes && !config.promote_inputs_to_common_dtype_ && (has_undefined_outputs || config.enforce_safe_casting_to_output_ || config.cast_common_dtype_to_outputs_)) INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/TensorIterator.cpp":407, please report a bug to PyTorch. 

Error for color:

Error completing request
Arguments: ('task(08cq41ondpo56ng)', 'a bird in a snowstorm', '', [], 25, 0, False, False, 3, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, True, True, 'color', 't2iadapter_color_sd14v1 [8522029d]', 1, {'image': array([[[15,  8,  7],
        [18,  8,  9],
        [16,  9, 10],
        ...,
        [ 5,  0,  0],
        [36, 18,  6],
        [52, 34, 17]],

       [[12,  6,  8],
        [16, 12, 11],
        [14,  8,  7],
        ...,
        [40, 28, 21],
        [33, 23, 15],
        [29, 11,  1]],

       [[20, 13, 13],
        [18, 11, 11],
        [22, 13, 13],
        ...,
        [28, 22, 18],
        [26, 26, 11],
        [42, 29, 19]],

       ...,

       [[37, 22, 21],
        [36, 18, 18],
        [48, 32, 25],
        ...,
        [73, 52, 41],
        [43, 23, 19],
        [51, 35, 30]],

       [[39, 25, 22],
        [43, 27, 22],
        [47, 33, 23],
        ...,
        [72, 47, 36],
        [79, 58, 45],
        [63, 38, 28]],

       [[40, 26, 23],
        [45, 27, 24],
        [49, 31, 26],
        ...,
        [87, 62, 47],
        [90, 69, 46],
        [99, 78, 62]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 512, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, 50) {}
Traceback (most recent call last):
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 117, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 114, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 140, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/modules/sd_hijack_unet.py", line 45, in apply_model
    return orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs).float()
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 239, in forward2
    model.forward = forward2.__get__(model, UNetModel)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 182, in forward
    if param.is_adapter:
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 105, in forward
    self.control = self.control_model(hint_in)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 395, in forward
    x = self.body[i](x)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 368, in forward
    x = self.in_conv(x)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/extensions/stable-diffusion-webui-composable-lora/composable_lora.py", line 154, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/me/Documents/stable-diffusion/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (MPSFloatType) and weight type (MPSHalfType) should be the same
```

### Additional information

Running on Mac.

**Comment by orfeaus** [comment]
Similar error described in #484
