### ISSUE TITLE
Error using style adapter

### ISSUE THREAD

**Issue by EkaLinjas** [Mikubill/sd-webui-controlnet#542]
```
Loading model from cache: t2iadapter_style_sd14v1 [202e85cc]
Loading preprocessor: none
  0%|                                                                                                                                                                                        | 0/16 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(amai1eo2avweeob)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=450x618 at 0x25A50979150>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 640, 512, 0, 0, 32, 0, '', '', '', [], 0, 0, 1, 512, 512, True, 'None', 'None', 0, 0, 0, 0, 0, 0.25, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, True, False, 0, -1, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 'x264', 'mci', 10, 0, False, True, True, True, 'intermediate', 'animation', False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'Refresh models', True, True, True, 'none', 't2iadapter_style_sd14v1 [202e85cc]', 1, {'image': array([[[ 41, 108, 152],
        [ 23, 107, 161],
        [ 24, 111, 162],
        ...,
        [152,  84,  45],
        [156,  86,  45],
        [149,  92,  58]],

       [[ 25, 112, 159],
        [ 21, 112, 165],
        [ 22, 112, 163],
        ...,
        [159,  90,  49],
        [160,  89,  48],
        [161,  93,  52]],

       [[ 26, 112, 163],
        [ 24, 112, 164],
        [ 22, 113, 164],
        ...,
        [163,  96,  51],
        [161,  92,  49],
        [161,  92,  51]],

       ...,

       [[209, 145,  95],
        [215, 146,  89],
        [213, 143,  87],
        ...,
        [ 43,  31,  30],
        [ 43,  31,  32],
        [ 47,  32,  33]],

       [[212, 145,  96],
        [217, 144,  90],
        [208, 137,  84],
        ...,
        [ 45,  30,  30],
        [ 43,  28,  30],
        [ 48,  31,  32]],

       [[199, 151, 112],
        [210, 146,  95],
        [206, 139,  92],
        ...,
        [ 45,  30,  30],
        [ 45,  29,  30],
        [ 50,  34,  34]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, False, False, 3, 0, False, False, 0, False, 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'first', -1, 1, 0, 1, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, False, '<p style="margin-bottom:0.75em">Recommended settings: Use from inpaint tab, inpaint at full res ON, denoise <0.5</p>', 'None', 30, 4, 0, 0, False, 'None', '<br>', 'None', 30, 4, 0, 0, 4, 0.4, True, 32, None, True, None, None, False, False, 0, True, 384, 384, False, 2, True, True, False, False, True, True, True, None, None, None, None, None, 50, False, 4.0, '', 10.0, 'Linear', 3, False, True, 30.0, True, False, False, 0, 0.0, 'Lanczos', 1, True, 10.0, True, 30.0, True, 0.0, 'Lanczos', 1, 0, 0, 512, 512, False, False, True, True, True, False, False, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False, '{inspiration}', None, 'linear', 'lerp', 'token', 'random', '30', 'fixed', 1, '8', None, 'Lanczos', 2, 0, 0, 'mp4', 10.0, 0, '', True, False, False, '', '', False, '', 127, False, 30, 9999, 1, 10, 0.25, True, False, '1', '', True, '', '', '', '', '', '', '', '', '', '', '', 'None', 0.3, 60) {}
Traceback (most recent call last):
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\img2img.py", line 169, in img2img
    processed = process_images(p)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 628, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\processing.py", line 1044, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 302, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 221, in launch_sampling
    return func()
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 302, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 116, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 233, in forward2
    return forward(*args, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 130, in forward
    control = param.control_model(x=x, hint=param.hint_cond, timesteps=timesteps, context=context)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 105, in forward
    self.control = self.control_model(hint_in)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\python\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "G:\Collection\BaiduDownload\stablediffusion\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\adapter.py", line 325, in forward
    x = torch.cat([x, style_embedding], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 4 and 3
```

I get same error after tried different browser with Edge and Chrome.
![image](https://user-images.githubusercontent.com/125619279/223735744-f31e9f06-e77a-426e-80d5-ee6df9a1bc90.png)
![image](https://user-images.githubusercontent.com/125619279/223735860-8005eae4-b4e3-45ba-9adb-cf1e93db0bb4.png)
![image](https://user-images.githubusercontent.com/125619279/223735977-6848bea8-2b70-4811-94a4-e339cc654aff.png)
![image](https://user-images.githubusercontent.com/125619279/223736160-817a7f07-0c3e-4f71-bb1d-7f803248bada.png)
Here is the setting i used

**Comment by ClashSAN** [comment]
@EkaLinjas you can only use it with `clip_vision`
![image](https://user-images.githubusercontent.com/98228077/223738309-e886087b-fde7-4cd0-880c-8bf464b3ee7e.png)
It takes at least 6gb
