### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\xca'.

### ISSUE THREAD

**Issue by JcynR** [Mikubill/sd-webui-controlnet#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I installed the ControlNet extension for stable-diffusion-webui and downloaded the necessary models from https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main.
I generated a pose image with Pose Editor and exported it to txt2img then when I enable the ControlNet in the UI and select the OpenPose preprocessor and model and hit generate and got an error (see below). I am using Google Colab.

### Steps to reproduce the problem

1. Install the ControlNet extension for stable-diffusion-webui
2. Download the models from https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main and place them in the correct folder (/content/stable-diffusion-webui/models/ControlNet/)
3. Generate OPenPose png with OpenPose Editor and export to txt2img
4. Enable the ControlNet in the UI, select the OpenPose preprocessor and model, and hit generate

### What should have happened?

The ControlNet should run without errors and generate the desired output.

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/27e319dc4f09a2f040043948e5c52965976f8491
controlnet: https://github.com/Mikubill/sd-webui-controlnet/tree/c9340671d6d59e5a79fc404f78f747f969f87374

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
--xformers --disable-safe-unpickle --no-half-vae --enable-insecure-extension-access --share --api
```

### Console logs

```Shell
Loading model: sd15_openpose [9ca67cc5]

Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 742, in process
    model_net = self.load_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 541, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 562, in build_control_model
    state_dict = load_state_dict(model_path)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 11, in load_state_dict
    state_dict = get_state_dict(torch.load(
  File "/content/stable-diffusion-webui/modules/safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "/content/stable-diffusion-webui/modules/safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xca'.

  0% 0/15 [00:00<?, ?it/s]
  7% 1/15 [00:07<01:43,  7.42s/it]
[...]
```

**Comment by camilovietnam** [comment]
This issue was closed and no response?
