### ISSUE TITLE
[Bug]: Output with shape [...] doesn't match broadcast shape [...]

### ISSUE THREAD

**Issue by jszeck** [Mikubill/sd-webui-controlnet#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Tried to make an images with auto1111, multidiffusion, and controlnet. The console made an error.

![image](https://user-images.githubusercontent.com/17091777/225175887-909cae69-554d-40f9-94d1-5d6c485bed34.png)

![image](https://user-images.githubusercontent.com/17091777/225176173-ab53f029-ca29-4cae-814f-dc1caddcaf96.png)

### Steps to reproduce the problem

1. Go to img2img
2. set setting as show in attached image
3. Press generate

### What should have happened?

generate image

### Commit where the problem happens

webui: [a9fed7c3](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2)
controlnet: e5ed9fcc (Wed Mar 8 11:58:19 2023)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--medvram --precision full --no-half --skip-torch-cuda-test --autolaunch
```

### Console logs

```Shell
MultiDiffusion Sampling:   0%|                                                                                                                                  | 0/96 [03:00<?, ?it/s]
ControlNet found. MultiDiffusion ControlNet support is enabled.
Loading model: controlnetPreTrained_openposeV10 [9ca67cc5]
Loaded state_dict from [C:\AI.art.C\automatic.1111\stable-diffusion-webui\extensions\sd-webui-controlnet\models\controlnetPreTrained_openposeV10.safetensors]
ControlNet model controlnetPreTrained_openposeV10 [9ca67cc5] loaded.
Loading preprocessor: none
MultiDiffusion hooked into DPM++ 2M Karras sampler. Tile size: 64 x 64 Tile batches: 4 Batch size: 1
  0%|                                                                                                                                                           | 0/24 [00:00<?, ?it/s]
Error completing request   0%|                                                                                                                                  | 0/96 [00:00<?, ?it/s]
Arguments: ('task(f6di2zrrkcjgo1h)', '(teen:1.2), (Hinata Hyuuga <lora:PixelHinata:1.0>), hyuuga hinata posing, (intricate details:1.2), in a fantasy village <lora:animeGameBackgrounds:.8>, kneeling, (1girl), (solo), white eyes, hand on head, slim, open jacket, headband, (short blue hair) in a bob cut, mullet, 4k,\nhigh saturation, \ndetailed background,\nsfw digital painting in hdr', 'easynegative, anime drawing by bad-artist-anime, (censored), watermark, signature, mosaic censoring, facing away, character sheet, 2girls, penis, sex, [muscles], 4 fingers, 6 fingers, bad hands, extra hands, extra legs, extra face, extra arm, boring, panties, pants, bra, shirt, dark, fit, large breasts, huge breasts, big tits, beard, facial hair, watercolor \\(medium\\), watercolor, nude, nsfw', [], 24, 15, False, False, 1, 1, 8, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.4, 1.5, 'R-ESRGAN 4x+ Anime6B', 10, 0, 0, [], 0, True, True, 768, 768, True, 64, 64, 32, 1, 'None', 2, False, False, True, True, 0, 512, 64, False, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, True, True, 'none', 'controlnetPreTrained_openposeV10 [9ca67cc5]', 1, {'image': array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8), 'mask': array([[[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       ...,

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]],

       [[  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        ...,
        [  0,   0,   0, 255],
        [  0,   0,   0, 255],
        [  0,   0,   0, 255]]], dtype=uint8)}, True, 'Scale to Fit (Inner Fit)', False, True, 64, 64, 64, 0, 0.3, False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, 'Denoised', 5.0, 0.0, 0.0, False, 'mp4', 'h264', 2.0, 0.0, 0.0, False, 0.0, True, True, False, False, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, None, 50) {}
Traceback (most recent call last):
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\processing.py", line 836, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 351, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 351, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 138, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 190, in kdiff_repeat
    return self.compute_x_tile(x_in, func)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 254, in compute_x_tile
    x_tile_out = func(x_tile, bboxes)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 188, in func
    x_tile_out = self.sampler_func(x_tile, sigma_in_tile, cond=new_cond)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 233, in forward2
    return forward(*args, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\hook.py", line 176, in forward
    control = param.control_model(x=x_in, hint=param.hint_cond, timesteps=timesteps, context=context)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 115, in forward
    return self.control_model(*args, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI.art.C\automatic.1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 380, in forward
    h += guided_hint
RuntimeError: output with shape [1, 320, 64, 64] doesn't match the broadcast shape [2, 320, 64, 64]
```

### Additional information

using CPU 
(I don't have NVIDIA)

The prompt I'm using works fine normally or with highres fix.

**Comment by LiamTTT** [comment]
Same problem. Dose anyone know why?
