### ISSUE TITLE
[Bug]: Critical - ControlNet cannot be disabled

### ISSUE THREAD

**Issue by vladmandic** [Mikubill/sd-webui-controlnet#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

controlnet will attempt to run regardless if its enabled or not since if it doesn't have any specific config, it will create new one which is **enabled by deafult**.

this is critical issue since controlnet attempts to run on ANY webui operation.

error seems to come from

> scripts/controlnet.py:process()
```python
        if len(params_group) == 0:
            # fill a null group
            remote_unit = self.parse_remote_call(p, external_code.ControlNetUnit(), 0)
            if remote_unit.enabled:
                params_group.append(remote_unit)
```

and what is a point of checking for

```python
if len(params_group) == 0
```
if above code **always** appends one?

what is even worse, since there is no controlnet configuration in place, it will cause a runtime error:
```log
Error running process: /home/vlado/dev/automatic/extensions-builtin/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/home/vlado/dev/automatic/modules/scripts.py", line 409, in process
    script.process(p, *script_args)
  File "/home/vlado/dev/automatic/extensions-builtin/sd-webui-controlnet/scripts/controlnet.py", line 677, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/home/vlado/dev/automatic/extensions-builtin/sd-webui-controlnet/scripts/controlnet.py", line 483, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/home/vlado/dev/automatic/extensions-builtin/sd-webui-controlnet/scripts/controlnet.py", line 494, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: None
```

so second part of this issue would be to handle missing configuration gracefully - if no model is selected, that is an extension configuration item, not something to raise a **RuntimeError**

### Steps to reproduce the problem

```shell
curl --header "Content-Type: application/json" --request POST --data '{}' http://127.0.0.1:7860/sdapi/v1/txt2img
```

    "extra_generation_params\": {\"ControlNet Enabled\": true, \"ControlNet Module\": null, \"ControlNet Model\": null, \"ControlNet Weight\": 1.0, \"ControlNet Guidance Start\": 0.0, \"ControlNet Guidance End\": 1.0}, \"index_of_first_image\": 0, \"infotexts\": [\"Steps: 50, Sampler: Euler, CFG scale: 7.0, Seed: 3164430982, Size: 512x512, Model hash: b0b2b630a5, Model: mood-photo-v03-fp16, Seed resize from: -1x-1, Denoising strength: 0, ControlNet Enabled: True, ControlNet Weight: 1.0, ControlNet Guidance Start: 0.0, ControlNet Guidance End: 1.0\"]

### What should have happened?

N/A

### Commit where the problem happens

webui: 
controlnet: 

### Command Line Arguments

```Shell
N/A
```

### Console logs

```Shell
N/A
```

**Comment by vladmandic** [comment]
confirming that issue is resolved with latest patch - thanks.

feel free to close the issue (or i can do it), just wanted to ask for a follow-up?
any chance you can replace

```python
if model_path is None:
    raise RuntimeError(f"model not found: {model}")
```

with

```python
assert model_path is not None, f"ControlNet model must be specified"
```

runtime errors trigger printing of a stack trace which is highly undesired for actually known configuration items.
i can create a pr, but opening a fork just for that seems like an overkill :)
