### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Diesellord** [Mikubill/sd-webui-controlnet#610]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

making a video in deforum with controlnet enebled

### Steps to reproduce the problem

1. Go to control NET 
2. Press enable
3. set all parameters
4. generate 
![image](https://user-images.githubusercontent.com/128121522/225823897-ddc3e27e-a800-49ec-8c27-e5d71b101132.png)

### What should have happened?

normaly generation start

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON="C:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe"
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --autolaunch
git pull
call webui.bat
```

### Console logs

```Shell
Already up to date.
venv "D:\SDLocal\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI



Launching Web UI with arguments: --autolaunch
No module 'xformers'. Proceeding without it.
Loading weights [9aba26abdf] from D:\SDLocal\models\Stable-diffusion\deliberate_v2.safetensors
Creating model from config: D:\SDLocal\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Textual inversion embeddings skipped(3): nartfixer, nfixer, nrealfixer
Model loaded in 2.8s (create model: 0.4s, apply weights to model: 0.5s, apply half(): 0.5s, move model to device: 0.5s, load textual inversion embeddings: 0.9s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 24.0s (import gradio: 3.6s, import ldm: 1.8s, other imports: 3.1s, list extensions: 0.6s, load scripts: 1.2s, load SD checkpoint: 3.0s, create ui: 10.2s, gradio launch: 0.5s).
reading custom settings from deforum_settings.txt
Deforum extension for auto1111 webui, v2.3b
Git commit: 15753b4c (Fri Mar 17 00:20:13 2023)
Exporting Video Frames (1 every 1) frames to D:\SDLocal\outputs/img2img-images\Anna_squat\inputframes...
Trying to extract frames from video with input FPS of 60.538410106626316. Please wait patiently.
Successfully extracted 112 frames from video.
Loading 112 input frames from D:\SDLocal\outputs/img2img-images\Anna_squat\inputframes and saving video frames to D:\SDLocal\outputs/img2img-images\Anna_squat
Unpacking ControlNet base video
Exporting Video Frames (1 every 1) frames to D:\SDLocal\outputs/img2img-images\Anna_squat\controlnet_inputframes...
Trying to extract frames from video with input FPS of 60.538410106626316. Please wait patiently.
Successfully extracted 112 frames from video.
Loading 112 input frames from D:\SDLocal\outputs/img2img-images\Anna_squat\controlnet_inputframes and saving video frames to D:\SDLocal\outputs/img2img-images\Anna_squat
ControlNet base video unpacked!
Saving animation frames to:
D:\SDLocal\outputs/img2img-images\Anna_squat
Animation frame: 0/112
Seed: 998132679
Prompt: cyberpunk woman in cyberpunk bikini and cyberpunk bra, neon lit, sunglasses, Deus Ex Human Revolution, digital glitch, (poster:1.6), poster on wall, movie poster, smoking, ((Tilt shift)),neonoir, night city ((japanese rock garden and pond, bonsai)), (digital pixel koi carp), (((high-tech interior style and futurism))), (((highly detailed face))), ((ultradetaled face and skin texture)), intricately detailed, fine details, hyperdetailed, raytracing, subsurface scattering, diffused soft lighting, shallow depth of field, by Oliver Wetter,
Neg Prompt: deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, ((((mutated hands and fingers)))), watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands
Using video init frame D:\SDLocal\outputs/img2img-images\Anna_squat\inputframes\very_short000000001.jpg
╭─────┬───┬───────╮
│Steps│CFG│Denoise│
├─────┼───┼───────┤
│ 25  │7.0│ 0.35  │
╰─────┴───┴───────╯
Reading ControlNet base frame 1 at D:\SDLocal\outputs/img2img-images\Anna_squat\controlnet_inputframes\000000001.jpg
Reading ControlNet mask frame 1 at D:\SDLocal\outputs/img2img-images\Anna_squat\controlnet_maskframes\000000001.jpg
                                                ControlNet params
╭──────┬─────────┬──────┬─────┬───────────┬─────────┬─────┬────────────────────────┬───────┬────────┬─────┬─────╮
│module│  model  │weight│ inv │guide_start│guide_end│guess│         resize         │rgb_bgr│proc res│thr a│thr b│
├──────┼─────────┼──────┼─────┼───────────┼─────────┼─────┼────────────────────────┼───────┼────────┼─────┼─────┤
│ hed  │sd15_hed │  1   │False│     0     │    1    │False│Scale to Fit (Inner Fit)│ False │  512   │ 64  │ 64  │
╰──────┴─────────┴──────┴─────┴───────────┴─────────┴─────┴────────────────────────┴───────┴────────┴─────┴─────╯
Error completing request
Arguments: ('task(eoylzj3q2n3z7nx)', None, False, '', 'Video Input', 120, 'replicate', '0:(0)', '0:(1.0025+0.002*sin(1.25*3.14*t/30))', '0:(0)', '0:(0)', '0:(1.75)', '0:(0.5)', '0:(0.5)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(0)', '0:(0)', '0:(53)', '0: (0.065)', '0: (0.65)', '0: (1.0)', '0: (7)', '0:(1.5)', False, '0:(1)', '0:(0)', False, '0: (25)', '0: (70)', '0: (1)', '0: (200)', '0: (10000)', '0:(s), 1:(-1), "max_f-2":(-1), "max_f-1":(s)', False, '0: ("Euler a")', '0: ("{video_mask}")', False, '0: ("{video_mask}")', False, '0: ("model1.ckpt"), 100: ("model2.ckpt")', False, '0: (2)', True, '0: (1.05)', '0: (5)', '0: (1.0)', '0: (0.1)', '0: (0.0)', 'LAB', '', 1.0, False, '2', False, 'perlin', 8, 8, 4, 0.5, True, 0.2, 'border', 'bicubic', False, 'D:\\very_short.mp4', 1, 0, -1, False, False, 'https://deforum.github.io/a1/VM1.mp4', False, '20230129210106', '{\n    "0": "cyberpunk woman in cyberpunk bikini and cyberpunk bra, neon lit, sunglasses, Deus Ex Human Revolution, digital glitch, (poster:1.6), poster on wall, movie poster, smoking, ((Tilt shift)),neonoir, night city ((japanese rock garden and pond, bonsai)), (digital pixel koi carp), (((high-tech interior style and futurism))), (((highly detailed face))), ((ultradetaled face and skin texture)), intricately detailed, fine details, hyperdetailed, raytracing, subsurface scattering, diffused soft lighting, shallow depth of field, by Oliver Wetter,"\n}', '', 'deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, ((((mutated hands and fingers)))), watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands', 540, 960, False, False, -1, 'Euler a', False, 0, 0, 25, 0.0, 1, True, True, False, False, False, 'Anna_squat', '{timestring}_{index}_{prompt}.png', 'fixed', 1, False, False, True, 0.8, 'https://deforum.github.io/a1/I1.png', False, False, False, True, 'https://deforum.github.io/a1/M1.jpg', 1.0, 1.0, 4, 1, True, 4, 'reroll', False, 60, False, False, 'FFMPEG mp4', 'D:\\SDLocal\\venv\\lib\\site-packages\\imageio_ffmpeg\\binaries\\ffmpeg-win64-v4.2.2.exe', '17', 'slow', 'None', 'https://deforum.github.io/a1/A1.mp3', False, 'realesr-animevideov3', 'x2', True, False, 'x0_pred', 'C:/SD/20230124234916_%09d.png', 'testvidmanualsettings.mp4', False, 'FILM', 2, False, 2, False, '', True, False, 'None', True, 'None', False, 'Farneback', False, 'None', False, 'None', False, False, '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://deforum.github.io/a1/Gi1.png",\n    "max_f/4-5": "https://deforum.github.io/a1/Gi2.png",\n    "max_f/2-10": "https://deforum.github.io/a1/Gi3.png",\n    "3*max_f/4-15": "https://deforum.github.io/a1/Gi4.jpg",\n    "max_f-20": "https://deforum.github.io/a1/Gi1.png"\n}', '0:(0.75)', '0:(0.35)', '0:(0.25)', '0:(20)', '0:(0.075)', None, None, True, 'D:\\very_short.mp4', '', True, False, False, False, False, 'hed', 'control_sd15_hed [fef5e48e]', 1, 0, 1, 512, 64, 64, 'Scale to Fit (Inner Fit)') {}
Traceback (most recent call last):
  File "D:\SDLocal\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\SDLocal\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\SDLocal\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 87, in run_deforum
    render_input_video(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root.animation_prompts, root)#TODO: prettify code
  File "D:\SDLocal/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\render_modes.py", line 50, in render_input_video
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, animation_prompts, root)
  File "D:\SDLocal/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\render.py", line 475, in render_animation
    image = generate(args, keys, anim_args, loop_args, controlnet_args, root, frame_idx, sampler_name=scheduled_sampler_name)
  File "D:\SDLocal/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\generate.py", line 220, in generate
    process_with_controlnet(p, args, anim_args, loop_args, controlnet_args, root, is_img2img=True, frame_idx=frame+1)
  File "D:\SDLocal/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\deforum_controlnet.py", line 295, in process_with_controlnet
    cnet.update_cn_script_in_processing(p, cn_units, is_img2img=is_img2img, is_ui=False)
TypeError: update_cn_script_in_processing() got an unexpected keyword argument 'is_img2img'

Deforum extension for auto1111 webui, v2.3b
Git commit: 15753b4c (Fri Mar 17 00:20:13 2023)
Unpacking ControlNet base video
Exporting Video Frames (1 every 1) frames to D:\SDLocal\outputs/img2img-images\Anna_squat\controlnet_inputframes...
Trying to extract frames from video with input FPS of 60.538410106626316. Please wait patiently.
Successfully extracted 112 frames from video.
Loading 120 input frames from D:\SDLocal\outputs/img2img-images\Anna_squat\controlnet_inputframes and saving video frames to D:\SDLocal\outputs/img2img-images\Anna_squat
ControlNet base video unpacked!
Saving animation frames to:
D:\SDLocal\outputs/img2img-images\Anna_squat
Animation frame: 0/120
Seed: 275175416
Prompt: cyberpunk woman in cyberpunk bikini and cyberpunk bra, neon lit, sunglasses, Deus Ex Human Revolution, digital glitch, (poster:1.6), poster on wall, movie poster, smoking, ((Tilt shift)),neonoir, night city ((japanese rock garden and pond, bonsai)), (digital pixel koi carp), (((high-tech interior style and futurism))), (((highly detailed face))), ((ultradetaled face and skin texture)), intricately detailed, fine details, hyperdetailed, raytracing, subsurface scattering, diffused soft lighting, shallow depth of field, by Oliver Wetter,
Neg Prompt: deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, ((((mutated hands and fingers)))), watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands
Not using an init image (doing pure txt2img)
╭─────┬───┬───────┬─────┬──────┬────┬────╮
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 25  │7.0│ None  │  0  │1.0025│ 0  │ 0  │
╰─────┴───┴───────┴─────┴──────┴────┴────╯
Reading ControlNet base frame 1 at D:\SDLocal\outputs/img2img-images\Anna_squat\controlnet_inputframes\000000001.jpg
Reading ControlNet mask frame 1 at D:\SDLocal\outputs/img2img-images\Anna_squat\controlnet_maskframes\000000001.jpg
                                                ControlNet params
╭──────┬─────────┬──────┬─────┬───────────┬─────────┬─────┬────────────────────────┬───────┬────────┬─────┬─────╮
│module│  model  │weight│ inv │guide_start│guide_end│guess│         resize         │rgb_bgr│proc res│thr a│thr b│
├──────┼─────────┼──────┼─────┼───────────┼─────────┼─────┼────────────────────────┼───────┼────────┼─────┼─────┤
│ hed  │sd15_hed │  1   │False│     0     │    1    │False│Scale to Fit (Inner Fit)│ False │  512   │ 64  │ 64  │
╰──────┴─────────┴──────┴─────┴───────────┴─────────┴─────┴────────────────────────┴───────┴────────┴─────┴─────╯
Error completing request
Arguments: ('task(7gy7o1qrwlz02q1)', None, False, '', '2D', 120, 'replicate', '0:(0)', '0:(1.0025+0.002*sin(1.25*3.14*t/30))', '0:(0)', '0:(0)', '0:(1.75)', '0:(0.5)', '0:(0.5)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(0)', '0:(0)', '0:(53)', '0: (0.065)', '0: (0.65)', '0: (1.0)', '0: (7)', '0:(1.5)', False, '0:(1)', '0:(0)', False, '0: (25)', '0: (70)', '0: (1)', '0: (200)', '0: (10000)', '0:(s), 1:(-1), "max_f-2":(-1), "max_f-1":(s)', False, '0: ("Euler a")', '0: ("{video_mask}")', False, '0: ("{video_mask}")', False, '0: ("model1.ckpt"), 100: ("model2.ckpt")', False, '0: (2)', True, '0: (1.05)', '0: (5)', '0: (1.0)', '0: (0.1)', '0: (0.0)', 'LAB', '', 1.0, False, '2', False, 'perlin', 8, 8, 4, 0.5, True, 0.2, 'border', 'bicubic', False, 'D:\\very_short.mp4', 1, 0, -1, False, False, 'https://deforum.github.io/a1/VM1.mp4', False, '20230129210106', '{\n    "0": "cyberpunk woman in cyberpunk bikini and cyberpunk bra, neon lit, sunglasses, Deus Ex Human Revolution, digital glitch, (poster:1.6), poster on wall, movie poster, smoking, ((Tilt shift)),neonoir, night city ((japanese rock garden and pond, bonsai)), (digital pixel koi carp), (((high-tech interior style and futurism))), (((highly detailed face))), ((ultradetaled face and skin texture)), intricately detailed, fine details, hyperdetailed, raytracing, subsurface scattering, diffused soft lighting, shallow depth of field, by Oliver Wetter,"\n}', '', 'deformed, bad anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, blurry, ((((mutated hands and fingers)))), watermark, watermarked, oversaturated, censored, distorted hands, amputation, missing hands, obese, doubled face, double hands', 540, 960, False, False, -1, 'Euler a', False, 0, 0, 25, 0.0, 1, True, True, False, False, False, 'Anna_squat', '{timestring}_{index}_{prompt}.png', 'fixed', 1, False, False, True, 0.8, 'https://deforum.github.io/a1/I1.png', False, False, False, True, 'https://deforum.github.io/a1/M1.jpg', 1.0, 1.0, 4, 1, True, 4, 'reroll', False, 60, False, False, 'FFMPEG mp4', 'D:\\SDLocal\\venv\\lib\\site-packages\\imageio_ffmpeg\\binaries\\ffmpeg-win64-v4.2.2.exe', '17', 'slow', 'None', 'https://deforum.github.io/a1/A1.mp3', False, 'realesr-animevideov3', 'x2', True, False, 'x0_pred', 'C:/SD/20230124234916_%09d.png', 'testvidmanualsettings.mp4', False, 'FILM', 2, False, 2, False, '', True, False, 'None', True, 'None', False, 'Farneback', False, 'None', False, 'None', False, False, '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://deforum.github.io/a1/Gi1.png",\n    "max_f/4-5": "https://deforum.github.io/a1/Gi2.png",\n    "max_f/2-10": "https://deforum.github.io/a1/Gi3.png",\n    "3*max_f/4-15": "https://deforum.github.io/a1/Gi4.jpg",\n    "max_f-20": "https://deforum.github.io/a1/Gi1.png"\n}', '0:(0.75)', '0:(0.35)', '0:(0.25)', '0:(20)', '0:(0.075)', None, None, True, 'D:\\very_short.mp4', '', True, False, False, False, False, 'hed', 'control_sd15_hed [fef5e48e]', 1, 0, 1, 512, 64, 64, 'Scale to Fit (Inner Fit)') {}
Traceback (most recent call last):
  File "D:\SDLocal\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\SDLocal\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\SDLocal\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 85, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root.animation_prompts, root)
  File "D:\SDLocal/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\render.py", line 475, in render_animation
    image = generate(args, keys, anim_args, loop_args, controlnet_args, root, frame_idx, sampler_name=scheduled_sampler_name)
  File "D:\SDLocal/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\generate.py", line 188, in generate
    process_with_controlnet(p_txt, args, anim_args, loop_args, controlnet_args, root, is_img2img=False, frame_idx=frame+1)
  File "D:\SDLocal/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\deforum_controlnet.py", line 295, in process_with_controlnet
    cnet.update_cn_script_in_processing(p, cn_units, is_img2img=is_img2img, is_ui=False)
TypeError: update_cn_script_in_processing() got an unexpected keyword argument 'is_img2img'
```

**Comment by ljleb** [comment]
Should be fixed in 2aa9c048cf59c0e4bacbc58c88b2c62d8a2319f3

**Comment by Diesellord** [comment]
thank you !! you are the best !

**Comment by ljleb** [comment]
Thank you. Mikubill deserves some praise too for this extension! Crazy work from them.
