### ISSUE TITLE
Error verifying pickled file from /content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body_pose_model.pth:

### ISSUE THREAD

**Issue by fakerzero00** [Mikubill/sd-webui-controlnet#618]
Error verifying pickled file from /content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body_pose_model.pth:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/content/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, '<'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 431, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 129, in openpose
    result, _ = model_openpose(img, has_hand)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/__init__.py", line 45, in apply_openpose
    body_estimation = Body(body_modelpath)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body.py", line 21, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/util.py", line 33, in transfer
    transfered_model_weights[weights_name] = model_weights['.'.join(weights_name.split('.')[1:])]
TypeError: 'NoneType' object is not subscriptable
Error verifying pickled file from /content/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body_pose_model.pth:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

_Originally posted by @jrq0928 in https://github.com/Mikubill/sd-webui-controlnet/discussions/499_

**Comment by OFSkean** [comment]
Check that you're downloading from the model file with the correct link. I had this problem and noticed I was downloading "https://huggingface.co/lllyasviel/ControlNet/blob/main/models/control_sd15_seg.pth" rather than "https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_seg.pth".  The former produced your issue, the latter worked perfectly.
