### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by enzyme69** [Mikubill/sd-webui-controlnet#65]
I kept getting this error and not working:

```
Restarting UI...
Error loading script: controlnet.py
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 101, in <module>
    update_cn_models()
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 81, in update_cn_models
    in (shared.opts.data.get("control_net_models_path", None), shared.cmd_opts.controlnet_dir)
AttributeError: 'Namespace' object has no attribute 'controlnet_dir'
```

**Comment by ljleb** [comment]
If you did not restart the webui completely, `preload.py` did not have a chance to run. It should work if you restart the webui.

**Comment by Mikubill** [comment]
Now it should work without any namespace issue.
