### ISSUE TITLE
ControlNet error

### ISSUE THREAD

**Issue by Lumiosphere** [Mikubill/sd-webui-controlnet#660]
Error loading script: controlnet.py
Traceback (most recent call last):
  File "C:\Stable-Diffusion\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Stable-Diffusion\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\controlnet.py", line 42, in <module>
    from svglib.svglib import svg2rlg
ValueError: source code string cannot contain null bytes

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "C:\Stable-Diffusion\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Stable-Diffusion\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 7, in <module>
    from scripts import controlnet
  File "C:\Stable-Diffusion\extensions\sd-webui-controlnet\scripts\controlnet.py", line 42, in <module>
    from svglib.svglib import svg2rlg
ValueError: source code string cannot contain null bytes

**Comment by ljleb** [comment]
Are you using an svg image? If so, there seems to be unexpected data in the svg image. Make sure it is composed of valid markdown.
