### ISSUE TITLE
[Bug]: Error in loading state_dict for Adapter:

### ISSUE THREAD

**Issue by vianseto** [Mikubill/sd-webui-controlnet#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hey, I'm facing this issue when trying to use the t2iadapter_style_sd14v1 model in clip_vision preprocessor. Can anyone help me?

### Steps to reproduce the problem

1. Open Automatic1111 UI
2. Press Control Net
3. Set enable
4. Select preprocessor "clip_vision"
5. Select model t2iadapter_style_sd14v1 [202e85cc]
6. Generate

### What should have happened?

https://www.youtube.com/watch?v=wDM8iDK-yng

### Commit where the problem happens

webui: [Automatic1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/955df7751eef11bb7697e2d77f6b8a6226b21e13)
controlnet: 

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Loading model: t2iadapter_style_sd14v1 [202e85cc]
Loaded state_dict from [/media/user/stable-diffusion-webui/models/ControlNet/t2iadapter_style_sd14v1.pth]
Error running process: /media/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/media/user/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/media/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 679, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/media/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 468, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/media/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 510, in build_control_model
    network = network_module(
  File "/media/user/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/adapter.py", line 82, in __init__
    self.control_model.load_state_dict(state_dict)
  File "/media/user/stable-diffusion-webui/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Adapter:
	Missing key(s) in state_dict: "body.0.block1.weight", "body.0.block1.bias", "body.0.block2.weight", "body.0.block2.bias", "body.1.block1.weight", "body.1.block1.bias", "body.1.block2.weight", "body.1.block2.bias", "body.2.in_conv.weight", "body.2.in_conv.bias", "body.2.block1.weight", "body.2.block1.bias", "body.2.block2.weight", "body.2.block2.bias", "body.3.block1.weight", "body.3.block1.bias", "body.3.block2.weight", "body.3.block2.bias", "body.4.in_conv.weight", "body.4.in_conv.bias", "body.4.block1.weight", "body.4.block1.bias", "body.4.block2.weight", "body.4.block2.bias", "body.5.block1.weight", "body.5.block1.bias", "body.5.block2.weight", "body.5.block2.bias", "body.6.block1.weight", "body.6.block1.bias", "body.6.block2.weight", "body.6.block2.bias", "body.7.block1.weight", "body.7.block1.bias", "body.7.block2.weight", "body.7.block2.bias", "conv_in.weight", "conv_in.bias". 
	Unexpected key(s) in state_dict: "style_embedding", "proj", "transformer_layes.0.attn.in_proj_weight", "transformer_layes.0.attn.in_proj_bias", "transformer_layes.0.attn.out_proj.weight", "transformer_layes.0.attn.out_proj.bias", "transformer_layes.0.ln_1.weight", "transformer_layes.0.ln_1.bias", "transformer_layes.0.mlp.c_fc.weight", "transformer_layes.0.mlp.c_fc.bias", "transformer_layes.0.mlp.c_proj.weight", "transformer_layes.0.mlp.c_proj.bias", "transformer_layes.0.ln_2.weight", "transformer_layes.0.ln_2.bias", "transformer_layes.1.attn.in_proj_weight", "transformer_layes.1.attn.in_proj_bias", "transformer_layes.1.attn.out_proj.weight", "transformer_layes.1.attn.out_proj.bias", "transformer_layes.1.ln_1.weight", "transformer_layes.1.ln_1.bias", "transformer_layes.1.mlp.c_fc.weight", "transformer_layes.1.mlp.c_fc.bias", "transformer_layes.1.mlp.c_proj.weight", "transformer_layes.1.mlp.c_proj.bias", "transformer_layes.1.ln_2.weight", "transformer_layes.1.ln_2.bias", "transformer_layes.2.attn.in_proj_weight", "transformer_layes.2.attn.in_proj_bias", "transformer_layes.2.attn.out_proj.weight", "transformer_layes.2.attn.out_proj.bias", "transformer_layes.2.ln_1.weight", "transformer_layes.2.ln_1.bias", "transformer_layes.2.mlp.c_fc.weight", "transformer_layes.2.mlp.c_fc.bias", "transformer_layes.2.mlp.c_proj.weight", "transformer_layes.2.mlp.c_proj.bias", "transformer_layes.2.ln_2.weight", "transformer_layes.2.ln_2.bias", "ln_post.weight", "ln_post.bias", "ln_pre.weight", "ln_pre.bias".
```

**Comment by ni4kmoon** [comment]
change the config file (*.yaml) according to the model (settings -> ControlNet ->Config file for Adapter models)

**Comment by zozero** [comment]
where get Config file for Adapter models

**Comment by zozero** [comment]
> change the config file (*.yaml) according to the model (settings -> ControlNet ->Config file for Adapter models)

where get Config file for Adapter models

**Comment by ni4kmoon** [comment]
> > change the config file (*.yaml) according to the model (settings -> ControlNet ->Config file for Adapter models)
> 
> where get Config file for Adapter models
upgrade the ControlNet extension, config file is in
"stable-diffusion-webui\extensions\sd-webui-controlnet\models"

**Comment by zozero** [comment]
> > > change the config file (*.yaml) according to the model (settings -> ControlNet ->Config file for Adapter models)
> > 
> > 
> > where get Config file for Adapter models
> > upgrade the ControlNet extension, config file is in
> > "stable-diffusion-webui\extensions\sd-webui-controlnet\models"

thanks
