### ISSUE TITLE
[Bug]: "Preview annotator result" can't work for preprocessor segmentation when use model control_seg-fp16[b9c1cc12]

### ISSUE THREAD

**Issue by FreeBlues** [Mikubill/sd-webui-controlnet#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

MacOS MacBookPro intel CPU
eGPU: RX6600 8G

The "Preview annotator result" can't work for preprocessor segmentation when use model control_seg-fp16[b9c1cc12].

return error.

BTW. The others: canny, hed,  normal_map, depth, openpose, mlcd, scribble all can work.

### Steps to reproduce the problem

1. At first, on webui, use Lora model chilloutmix_ni to generate an image.
2. Drag the image to the controlnet area.
3. select Preprocessor:segmentation, select Model:control_seg-fp16[b9c1cc12].
4. Click the button:Preview annotator result.
5. Get error: "AssertionError: Torch not compiled with CUDA enabled"

### What should have happened?

It should generate an seg image in the controlnet area

### Commit where the problem happens

webui: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
controlnet: 241c05f8c9d3c5abe637187e3c4bb46f17447029

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
(web-ui) ppt@pptdeMacBook-Pro stable-diffusion-webui % python webui.py --precision full --no-half --opt-split-attention-v1 --listen
```

### Console logs

```Shell
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:26<00:00,  1.32s/it]
Use Checkpoint: False
Checkpoint Number: [0, 0, 0, 0]
Use global window for all blocks in stage3
load checkpoint from local path: /Users/ppt/Github/stable-diffusion-webui/models/uniformer/upernet_global_small.pth
Traceback (most recent call last):
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/gradio/routes.py", line 283, in run_predict
    output = await app.blocks.process_api(
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/gradio/blocks.py", line 936, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/gradio/blocks.py", line 777, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/ppt/Github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 364, in run_annotator
    result, is_image = preprocessor(img)
  File "/Users/ppt/Github/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 157, in uniformer
    result = model_uniformer(img)
  File "/Users/ppt/Github/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/__init__.py", line 33, in apply_uniformer
    model = init_segmentor(config_file, modelpath)
  File "/Users/ppt/Github/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/uniformer/inference.py", line 43, in init_segmentor
    model.to(device)
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/Users/ppt/miniconda/envs/web-ui/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### Additional information

*

**Comment by Hyg900928** [comment]
I have the same problem with my Mac M1, how can I solve it?

**Comment by littleyeson** [comment]
open pose,depth,MLSD Proprocesser is not working,Just Canny can work
