### ISSUE TITLE
[Bug]: Cannot have more than 1 controlnet

### ISSUE THREAD

**Issue by githubUser01946** [Mikubill/sd-webui-controlnet#679]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have gone to Automatic1111 settings > ControlNet > Multi ControlNet: Max models amount (requires restart) and chosen 2, applied those settings and reloaded ui.

Then I go to img2img and it still shows the one.

![image](https://user-images.githubusercontent.com/117453319/228783014-0cb4e629-368c-4b0a-9a85-479375b08232.png)

### Steps to reproduce the problem

1. Go to Automatic1111 settings > ControlNet
2. Replace 1 with 2 in Multi ControlNet: Max models amount
3. Apply Settings
4. Reload Ui
5. Head to Img2Img

### What should have happened?

I should have tabs or an option to change to a different control net.

### Commit where the problem happens

webui: commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
controlnet: 241c05f8 (Thu Mar 23 15:18:35 2023)

### Command Line Arguments

```Shell
--xformers --medvram
```

### Console logs

```Shell
`Microsoft Windows [Version 10.0.19044.2728]
(c) Microsoft Corporation. All rights reserved.

D:\stable-diffusion-webui>webui-user.bat
venv "D:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
current transparent-background 1.2.3



Launching Web UI with arguments: --xformers --medvram
Loading weights [0466ae65a0] from D:\stable-diffusion-webui\models\Stable-diffusion\epicDiffusion_epicDiffusion11.safetensors
Creating model from config: D:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 155.7s (load weights from disk: 14.2s, create model: 0.8s, apply weights to model: 137.9s, apply half(): 1.4s, load VAE: 0.1s, load textual inversion embeddings: 1.2s).
Launching the Discord RPC extension. By https://github.com/kabachuha, version 0.1b
Use this link to report any problems or add suggestions https://github.com/kabachuha/discord-rpc-for-automatic1111-webui
Installing the missing 'discord-rpc' package and its dependencies,
In case it will give a package error after the installation, restart the webui.
Installing discord-rpc
failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'
failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'
Error executing callback ui_tabs_callback for D:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py", line 49, in on_ui_tabs
    start_rpc()
  File "D:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py", line 30, in start_rpc
    rpc = DiscordRPC.RPC.Set_ID(app_id=1065987911486550076)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\DiscordRPC\presence.py", line 46, in Set_ID
    return DiscordWindows(app_id)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\DiscordRPC\presence.py", line 33, in __init__
    self._connect()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\DiscordRPC\presence.py", line 235, in _connect
    raise DiscordNotOpened
DiscordRPC.exceptions.DiscordNotOpened: Error, could not find Discord. is Discord running?

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 266.4s (import torch: 15.9s, import gradio: 3.0s, import ldm: 5.1s, other imports: 16.8s, list SD models: 0.4s, setup codeformer: 0.6s, list builtin upscalers: 0.2s, load scripts: 8.5s, load SD checkpoint: 155.8s, create ui: 59.3s, gradio launch: 0.8s).
Closing server running on port: 7860
Restarting UI...
Launching the Discord RPC extension. By https://github.com/kabachuha, version 0.1b
Use this link to report any problems or add suggestions https://github.com/kabachuha/discord-rpc-for-automatic1111-webui
Installing the missing 'discord-rpc' package and its dependencies,
In case it will give a package error after the installation, restart the webui.
Installing discord-rpc
failed to open '\\\\?\\pipe\\discord-ipc-0': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-0'
failed to open '\\\\?\\pipe\\discord-ipc-1': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-1'
failed to open '\\\\?\\pipe\\discord-ipc-2': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-2'
failed to open '\\\\?\\pipe\\discord-ipc-3': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-3'
failed to open '\\\\?\\pipe\\discord-ipc-4': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-4'
failed to open '\\\\?\\pipe\\discord-ipc-5': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-5'
failed to open '\\\\?\\pipe\\discord-ipc-6': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-6'
failed to open '\\\\?\\pipe\\discord-ipc-7': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-7'
failed to open '\\\\?\\pipe\\discord-ipc-8': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-8'
failed to open '\\\\?\\pipe\\discord-ipc-9': [Errno 2] No such file or directory: '\\\\?\\pipe\\discord-ipc-9'
Error executing callback ui_tabs_callback for D:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py", line 49, in on_ui_tabs
    start_rpc()
  File "D:\stable-diffusion-webui\extensions\discord-rpc-for-automatic1111-webui\scripts\webui-rpc.py", line 30, in start_rpc
    rpc = DiscordRPC.RPC.Set_ID(app_id=1065987911486550076)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\DiscordRPC\presence.py", line 46, in Set_ID
    return DiscordWindows(app_id)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\DiscordRPC\presence.py", line 33, in __init__
    self._connect()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\DiscordRPC\presence.py", line 235, in _connect
    raise DiscordNotOpened
DiscordRPC.exceptions.DiscordNotOpened: Error, could not find Discord. is Discord running?

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.4s (load scripts: 1.1s, reload script modules: 0.2s, create ui: 12.9s, gradio launch: 0.2s).
`
```

**Comment by ClashSAN** [comment]
per readme, just restart webui (completely close webui, close the terminal window)

>This option allows multiple ControlNet inputs for a single generation. To enable this option, change Multi ControlNet: Max models amount (requires restart) in the settings. Note that you will need to restart the WebUI for changes to take effect.

https://github.com/Mikubill/sd-webui-controlnet#multi-controlnet--joint-conditioning-experimental

**Comment by githubUser01946** [comment]
> per readme, just restart webui (completely close webui, close the terminal window)
> 
> > This option allows multiple ControlNet inputs for a single generation. To enable this option, change Multi ControlNet: Max models amount (requires restart) in the settings. Note that you will need to restart the WebUI for changes to take effect.
> 
> https://github.com/Mikubill/sd-webui-controlnet#multi-controlnet--joint-conditioning-experimental

I did restart it multiple times but it eventually worked.

**Comment by winstonma** [comment]
@githubUser01946 I faced this issue when I came to this place.

Then I find video showing how to set [multiple controlnet](https://youtu.be/WZg3e6B2yPQ?t=199). Just watch that 50 second and it should do it.

**Comment by MojoGlover** [comment]
I’m having the same problem.  The setting seems stuck at 3, but I’m only getting 1 unit.  On a Mac.

**Comment by winstonma** [comment]
@MojoGlover Yeah that's why I attached the [youtube video in the post](https://github.com/Mikubill/sd-webui-controlnet/issues/679#issuecomment-1628262828). I just have to follow that 50 seconds. Go to Settings→Controlnet→Modify the controlnet unit value and click **apply settings** at the top. Then multiple controlnet would appear.

**Comment by mylee95** [comment]
Just in case if others come in with same issue, currently controlnet extension has default value of 3 units on its "Multi ControlNet: Max models amount" section, but it seems like you have to press "Apply settings" at least once after installing the extension to apply default setting values. 

So if you just installed controlnet extension and you see setting value 3 units but only getting 1 unit at controlnet UI section, then go to Settings > ControlNet and press Apply settings and restart the UI at terminal, then you'll see 3 units :)
