### ISSUE TITLE
[Bug]: TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'threshold_c'

### ISSUE THREAD

**Issue by ryouxin** [Mikubill/sd-webui-controlnet#681]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I have sent a request and tried to use controlnet when I use the API of stable diffusion, but the error happened, here are the logs

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1.6s (load scripts: 0.4s, create ui: 1.0s, scripts app_started_callback: 0.1s).
Couldn't find Lora with name FGMIX_2
Couldn't find Lora with name makotoShinkaiSubstyles_offset
100%|██████████| 31/31 [00:05<00:00,  5.83it/s]
Total progress: 1038it [1:02:09,  5.77it/s]
Error running process: /home/ipfs10/stable-diffusion-webui/extensions/controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/home/ipfs10/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/home/ipfs10/stable-diffusion-webui/extensions/controlnet/scripts/controlnet.py", line 619, in process
    params_group = external_code.get_all_units_from(args)
  File "/home/ipfs10/stable-diffusion-webui/extensions/controlnet/scripts/external_code.py", line 125, in get_all_units_from
    units.append(to_processing_unit(script_args[i]))
  File "/home/ipfs10/stable-diffusion-webui/extensions/controlnet/scripts/external_code.py", line 179, in to_processing_unit
    unit = ControlNetUnit(**unit)
TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'threshold_c'

 

### Steps to reproduce the problem

here is the request body:

{
        "init_images": [
            pic_base64
        ],
        "resize_mode": 0,
        "denoising_strength": 0.75,
        "image_cfg_scale": 3,
        "mask": pic_mask_base64,
        "mask_blur": 4,
        "inpainting_fill": 0,
        "inpaint_full_res": True,
        "inpaint_full_res_padding": 0,
        "inpainting_mask_invert": 0,
        "initial_noise_multiplier": 1,
        "prompt": "(full_body:1.4),best quality, masterpiece, illustration, an extremely delicate and beautiful, extremely detailed ,CG ,unity ,8k wallpaper, Amazing, finely detail, masterpiece,best quality,official art, extremely detailed CG unity 8k wallpaper, absurdres, incredibly absurdres, huge filesize, ultra-detailed, highres, extremely detailed, beautiful detailed girl,((detailed face,perfect face)), (extremely detailed eyes),((looking at viewer)),(real person,photograph),cute,1girl,18 yo,(white straight hair),makeup,(light blue shinny contact lens), (light pink eye shadow),(haunting smile),(moist lips),(long legs),middle breasts,narrow waist,(slim),(white_skin),blush, shy,((white dress)), (white elbow gloves:1.4),(earrings),(sitting),(green background),ulzzang-6500-v1.1:0.2, pureerosface_v1, <lora:FGMIX_2:1>, <lora:makotoShinkaiSubstyles_offset:1.25:NF>",
        "styles": [
        ],
        "seed": -1,
        "subseed": -1,
        "subseed_strength": 0,
        "seed_resize_from_h": -1,
        "seed_resize_from_w": -1,
        "sampler_name": "DPM++ SDE Karras",
        "batch_size": 1,
        "n_iter": 1,
        "steps": 40,
        "cfg_scale": 8,
        "width": 512,
        "height": 768,
        "restore_faces": False,
        "tiling": False,
        "do_not_save_samples": False,
        "do_not_save_grid": False,
        "negative_prompt": "(worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)),paintings, sketches,nipples, skin spots, acnes, skin blemishes, bad anatomy,facing away, looking away,tilted head, mult multiple girls, lowres,bad anatomy,bad hands, text, error, missing fingers,extra digit, fewer digits, blurry,bad feet,cropped,poorly drawn hands,poorly drawn face,mutation,deformed,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,extra fingers,fewer digits,extra limbs,extra arms,extra legs,malformed limbs,fused fingers,too many fingers,long neck,cross-eyed,mutated hands,polar lowres,bad body,bad proportions,gross,nipples",
        "eta": 0,
        "s_churn": 0,
        "s_tmax": 0,
        "s_tmin": 0,
        "s_noise": 1,
        "override_settings": {},
        "override_settings_restore_afterwards": True,
        "script_args": [],
        "sampler_index": "DPM++ SDE Karras",
        "include_init_images": False,
        "script_name": "",
        "send_images": True,
        "save_images": False,
        "alwayson_scripts": {
            "controlnet": {
                "args": [
                    {
                        "enabled": True,
                        "input_image": pic_mask_base64,
                        "mask": pic_mask_base64,
                        "module": "canny",
                        "model": "control_sd15_canny [fef5e48e]",
                        "weight": 1,
                        "resize_mode": "Scale to Fit (Inner Fit)",
                        "lowvram": False,
                        "processor_res": 512,
                        "threshold_a": 512,
                        "threshold_b": 100,
                        "threshold_c": 200,
                        "guidance": 1,
                        "guidance_start": 0,
                        "guidance_end": 1,
                        "guessmode": False
                    },
                    {
                        "enabled": True,
                        "input_image": pic_pose_base64,
                        "mask": pic_pose_base64,
                        "module": "",
                        "model": "control_sd15_openpose [fef5e48e]",
                        "weight": 1,
                        "resize_mode": "Scale to Fit (Inner Fit)",
                        "lowvram": False,
                        "processor_res": 512,
                        "guidance": 1,
                        "guidance_start": 0,
                        "guidance_end": 0.98,
                        "guessmode": False
                    }
                ]
            }
        },
    }

### What should have happened?

no error logs

### Commit where the problem happens

webui: 
controlnet: error log

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
nohup ./webui.sh --xformers --listen --enable-insecure-extension-access --api &
```

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
Startup time: 1.6s (load scripts: 0.4s, create ui: 1.0s, scripts app_started_callback: 0.1s).
Couldn't find Lora with name FGMIX_2
Couldn't find Lora with name makotoShinkaiSubstyles_offset
100%|██████████| 31/31 [00:05<00:00,  5.83it/s]
Total progress: 1038it [1:02:09,  5.77it/s]
Error running process: /home/ipfs10/stable-diffusion-webui/extensions/controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/home/ipfs10/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/home/ipfs10/stable-diffusion-webui/extensions/controlnet/scripts/controlnet.py", line 619, in process
    params_group = external_code.get_all_units_from(args)
  File "/home/ipfs10/stable-diffusion-webui/extensions/controlnet/scripts/external_code.py", line 125, in get_all_units_from
    units.append(to_processing_unit(script_args[i]))
  File "/home/ipfs10/stable-diffusion-webui/extensions/controlnet/scripts/external_code.py", line 179, in to_processing_unit
    unit = ControlNetUnit(**unit)
TypeError: ControlNetUnit.__init__() got an unexpected keyword argument 'threshold_c'
```

**Comment by ryouxin** [comment]
fixed
