### ISSUE TITLE
[Bug]: Fails to load when junctions used

### ISSUE THREAD

**Issue by guzuligo** [Mikubill/sd-webui-controlnet#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I use mklink /j to have a junction folder to help me save space. I put some of the controlNets on different drive using that.

But, when the drive is not mounted, the folder becomes inaccessible. When this happens, the script fails to load the files in the folder and stops working alltogether.

### Steps to reproduce the problem

-Open command line
-Open the controlNet model and make a junction folder to link to a different drive
-Remove that drive
-Try to reload the A1111 UI

### What should have happened?

The script should detect inaccessible folders and skip them

### Commit where the problem happens

webui: [22bcc7b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
controlnet: 241c05f

### Command Line Arguments

```Shell
--xformers --api
```

### Console logs

```Shell
Error loading script: api.py
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AUTOMATIC1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\api.py", line 18, in <module>
    from scripts.controlnet import update_cn_models, cn_models_names
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 168, in <module>
    update_cn_models()
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 156, in update_cn_models
    found = get_all_models(sort_by, filter_by, path)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 97, in get_all_models
    fileinfos = traverse_all_files(path, [])
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 91, in traverse_all_files
    model_list = traverse_all_files(fname, model_list)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 85, in traverse_all_files
    for entry in os.scandir(curr_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\AUTOMATIC1111\\models\\ControlNet\\External_Drive'

Error loading script: controlnet.py
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AUTOMATIC1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 168, in <module>
    update_cn_models()
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 156, in update_cn_models
    found = get_all_models(sort_by, filter_by, path)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 97, in get_all_models
    fileinfos = traverse_all_files(path, [])
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 91, in traverse_all_files
    model_list = traverse_all_files(fname, model_list)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 85, in traverse_all_files
    for entry in os.scandir(curr_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\AUTOMATIC1111\\models\\ControlNet\\External_Drive'

Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "C:\AUTOMATIC1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\AUTOMATIC1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 7, in <module>
    from scripts import controlnet
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 168, in <module>
    update_cn_models()
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 156, in update_cn_models
    found = get_all_models(sort_by, filter_by, path)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 97, in get_all_models
    fileinfos = traverse_all_files(path, [])
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 91, in traverse_all_files
    model_list = traverse_all_files(fname, model_list)
  File "C:\AUTOMATIC1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 85, in traverse_all_files
    for entry in os.scandir(curr_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\AUTOMATIC1111\\models\\ControlNet\\External_Drive'
```

### Additional information

I'm running on windows

In command line, use
 mklink /j sourceFolder targetFolder

This is to mount a folder from external drive into a local one

**Comment by ljleb** [comment]
You should use command line argument `--controlnet-dir` instead of making directory junctions. It will also save you having to redo the junction every time you want to update the repo.
