### ISSUE TITLE
[Bug]: clip_vision preprocessor won't load, just freezes console

### ISSUE THREAD

**Issue by spaciousmind** [Mikubill/sd-webui-controlnet#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Have been using controlnet in webui, works as expected for everything else, but when I try the style mode with clip_vision in preprocessor it just freezes in my console on this line: Loading preprocessor: clip_vision

I don't think this is related to the model t2iadapter_style_sd14v1 because it always freezes on loading clip_vision whether I have that model loaded or not.

### Steps to reproduce the problem

1. go to control net
2. click enable
3. load a style image in
4. choose clip_vision as in the preprocessor drop down
5.. click generate

### What should have happened?

it should have made an image, and showed me more outputs in the console.

### Commit where the problem happens

webui:  commit: 
[a9fed7c3](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2)
controlnet:
241c05f8 (Thu Mar 23 15:18:35 2023)

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS= --xformers --ckpt-dir E:\AI-models
```

### Console logs

```Shell
λ webui-user.bat
venv "D:\Projects\Git\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2
Installing requirements for Web UI
Fetching updates for midas...
Checking out commit for midas with hash: b845b78...






Initializing Riffusion

If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed accelerate-0.18.0 fastapi-0.94.1 gitpython-3.1.31 requests-2.28.2 transformers-4.26.1

Does your project take forever to startup?
Repetitive dependency installation may be the reason.
Automatic1111's base project sets strict requirements on outdated dependencies.
If an extension is using a newer version, the dependency is uninstalled and reinstalled twice every startup.

# Your version of xformers is 0.0.14.dev0.
# xformers >= 0.0.17.dev is required to be available on the Dreambooth tab.
# Torch 1 wheels of xformers >= 0.0.17.dev are no longer available on PyPI,
# but you can manually download them by going to:
https://github.com/facebookresearch/xformers/actions
# Click on the most recent action tagged with a release (middle column).
# Select a download based on your environment.
# Unzip your download
# Activate your venv and install the wheel: (from A1111 project root)
cd venv/Scripts
activate
pip install {REPLACE WITH PATH TO YOUR UNZIPPED .whl file}
# Then restart your project.
[!] xformers version 0.0.14.dev0 installed.
[!] torch version 1.12.1+cu113 installed.
[!] torchvision version 0.13.1+cu113 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

#######################################################################################################
#                                       LIBRARY ISSUE DETECTED
    #
#######################################################################################################
#
# torch is below the required 1.13.1+cu116 version.
# torchvision is below the required 0.14.1+cu116 version.
#
# Dreambooth may not work properly.
#
# TROUBLESHOOTING
# 1. Fully restart your project (not just the webpage)
# 2. Update your A1111 project and extensions
# 3. Dreambooth requirements should have installed automatically, but you can manually install them
#    by running the following 4 commands from the A1111 project root:
cd venv/Scripts
activate
cd ../..
pip install -r ./extensions/sd_dreambooth_extension/requirements.txt
#######################################################################################################

loading Smart Crop reqs from D:\Projects\Git\stable-diffusion-webui\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.

Installing requirements for Seed Travel




Launching Web UI with arguments: --xformers --ckpt-dir E:AI-models
==============================================================================
You are running torch 1.12.1+cu113.
The program is tested to work with torch 1.13.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.14.dev.
The program is tested to work with xformers 0.0.16rc425.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
Error loading script: txt2vectorgfx.py
Traceback (most recent call last):
  File "D:\Projects\Git\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Projects\Git\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Projects\Git\stable-diffusion-webui\scripts\txt2vectorgfx.py", line 70
    <title>Txt2Vectorgraphics/txt2vectorgfx.py at main · GeorgLegato/Txt2Vectorgraphics</title>
                                                       ^
SyntaxError: invalid character '·' (U+00B7)

[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Loading weights [6e430eb514] from D:\Projects\Git\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5-pruned.safetensors
Creating model from config: D:\Projects\Git\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights found near the checkpoint: D:\Projects\Git\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5-pruned.vae.pt
Applying xformers cross attention optimization.
Model loaded in 5.7s (create model: 0.6s, apply weights to model: 1.3s, apply half(): 0.7s, load VAE: 0.7s, move model to device: 1.0s, load textual inversion embeddings: 1.4s).
add tab
[VRAMEstimator] No stats available, run benchmark first
CUDA SETUP: Loading binary D:\Projects\Git\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 43.9s (import gradio: 3.3s, import ldm: 4.2s, other imports: 4.2s, list extensions: 3.9s, setup codeformer: 0.1s, load scripts: 6.3s, load SD checkpoint: 6.0s, create ui: 15.6s, gradio launch: 0.1s).
100%|████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.77it/s] Total progress: 100%|████████████████████████████████████████████| 20/20 [00:03<00:00,  5.53it/s] 100%|████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.37it/s] Total progress: 100%|████████████████████████████████████████████| 20/20 [00:03<00:00,  5.89it/s] 100%|████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.45it/s] Total progress: 100%|████████████████████████████████████████████| 20/20 [00:08<00:00,  2.28it/s] Loading model: t2iadapter_style_sd14v1 [202e85cc]████████████████| 20/20 [00:08<00:00,  2.83it/s] Loaded state_dict from [D:\Projects\Git\stable-diffusion-webui\extensions\sd-webui-controlnet\models\t2iadapter_style_sd14v1.pth]
ControlNet model t2iadapter_style_sd14v1 [202e85cc] loaded.
Loading preprocessor: clip_vision
```

**Comment by jbuckmccready** [comment]
I have this same problem, using chrome with latest sd-webui (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81) and controlnet extension (https://github.com/Mikubill/sd-webui-controlnet/commit/241c05f8c9d3c5abe637187e3c4bb46f17447029).

**Comment by spaciousmind** [comment]
I Had to do a whole fresh install of automatic, so now it's at version 22bcc7b. 
Still getting the same problem with clip_vision :(

**Comment by Natotela** [comment]
I'm getting no error in console but doesn't seem to make any significant effect.
Annotator doesn't show any preview.
t2iadapter style sd14v1 model

**Comment by spaciousmind** [comment]
My clip_vision randomly started working as of today (not sure what changed, maybe just a few settings on my end, I don't think there were any new updates). It happily downloaded clip_vision and I get expected results now using that with t2iadapter_style_sd14v1 [202e85cc]


@Natotela I don't think clip_vision is meant to give an annotator preview.
If console gives no errors and it already downloaded clip_vision for you I suspect it's related to something else.

I have noticed a more general bug (it's so common I'm sure there must be an existing issue) using ControlNet that sometimes it refuses to load / turn on / or turn off particular models or to load in my new image (I have multi controlnet enabled and am using sometimes 4 at a time, and I notice it often when trying to load a new image or something, it might keep using the old one, or not enable the controlnet). This could be what's happening in your case, usually I can fix mine by just mucking around, loading a different model and preprocessor from the dropdowns, and then loading back what you wanted, hiding/showing preview and checking /unchecking enable & loading in a new image, double check the canvas ratio... trying a couple generations, it sorts itself out eventually. Really annoying but I can live with it.

**Comment by Natotela** [comment]
trying to fix the issues I did some hard reset to a previous hash, then git pulled, and I noticed my mediapipe preprocessor was gone so I re-cloned the crucible_ai CN version.
a bit shooting in the dark but for now everything's working. also I changed some settings in order to (try to) evacuate some memory. currently my .bat file is:

```
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.7,max_split_size_mb:256
set ATTN_PRECISION=fp16
set SAFETENSORS_FAST_GPU=1
set COMMANDLINE_ARGS=--no-half-vae --medvram --opt-sdp-attention --api --enable-insecure-extension-access
```

**Comment by jbuckmccready** [comment]
Yeah, it's working for me now too, maybe latest version of controlnet extension fixed it? Not sure what changed...
