### ISSUE TITLE
[Bug]: Error loading script: controlnet.py

### ISSUE THREAD

**Issue by MrKuenning** [Mikubill/sd-webui-controlnet#739]
### Is there an existing issue for this?

No

### What happened?

After updating the extension today I started getting a bunch of errors in the console and ControlNet does not load.

### Steps to reproduce the problem

1. Update ControlNet
3. Reload WebUI

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--listen --port 7799 --api --xformers --enable-insecure-extension-access --disable-safe-unpickle --styles-file styles-full.csv
```

### Console logs

```Shell
Error loading script: api.py
Traceback (most recent call last):
  File "E:\AI\A1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\AI\A1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\A1111\extensions\sd-webui-controlnet\scripts\api.py", line 15, in <module>
    from scripts import external_code
ImportError: cannot import name 'external_code' from 'scripts' (unknown location)

Error loading script: controlnet.py
Traceback (most recent call last):
  File "E:\AI\A1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\AI\A1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\A1111\extensions\sd-webui-controlnet\scripts\controlnet.py", line 15, in <module>
    from scripts.cldm import PlugableControlModel
ModuleNotFoundError: No module named 'scripts.cldm'

Error loading script: external_code.py
Traceback (most recent call last):
  File "E:\AI\A1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\AI\A1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\A1111\extensions\sd-webui-controlnet\scripts\external_code.py", line 5, in <module>
    from scripts.global_state import update_cn_models, cn_models_names, cn_preprocessor_modules
ModuleNotFoundError: No module named 'scripts.global_state'

Error loading script: global_state.py
Traceback (most recent call last):
  File "E:\AI\A1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\AI\A1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\A1111\extensions\sd-webui-controlnet\scripts\global_state.py", line 7, in <module>
    from scripts.processor import *
ModuleNotFoundError: No module named 'scripts.processor'
```

**Comment by MrKuenning** [comment]
I noticed one of the pull requests was reverted 10 minutes ago, so I tried updating the extension and it still failed to load.
I then removed the extension and reinstalled and it still fails.

**Comment by MrKuenning** [comment]
Third git pull and restarted webUI and it seems to be working again.

**Comment by thatjimupnorth** [comment]
I'm getting the exact same thing but Git Pull says it's already up to date. CN doesn't launch and I get the same Error loading script: controlnet.py

**Comment by Vendaciousness** [comment]
I have a very similar error this morning, right after updating and reloading UI:
```
Restarting UI...0it [00:00, ?it/s]
Error loading script: controlnet.py
Traceback (most recent call last):
  File "G:\Code\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\Code\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Code\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 21, in <module>
    importlib.reload(global_state)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Code\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 21, in <module>
    "hed_safe": hed_safe,
NameError: name 'hed_safe' is not defined

Error loading script: global_state.py
Traceback (most recent call last):
  File "G:\Code\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\Code\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Code\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 21, in <module>
    "hed_safe": hed_safe,
NameError: name 'hed_safe' is not defined

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1.1s (load scripts: 0.3s, create ui: 0.6s, gradio launch: 0.1s).
```
I had also just installed Multidiffusion Tiled VAE, so unsure if that is related.
