### ISSUE TITLE
[Bug]:  Error with seed 

### ISSUE THREAD

**Issue by Suitz** [Mikubill/sd-webui-controlnet#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Error when using controlnet. Error see below

### Steps to reproduce the problem

just use the controlnet

### What should have happened?

it should work

### Commit where the problem happens

webui: +
controlnet: +

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
Error running process: F:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "F:\AI\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 736, in process
    np.random.seed(int(p.seed))
  File "mtrand.pyx", line 246, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1
```

**Comment by lllyasviel** [comment]
fixed
