### ISSUE TITLE
[Bug]: New CN models v1.1 don't work with external API

### ISSUE THREAD

**Issue by hithereai** [Mikubill/sd-webui-controlnet#762]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I try to run deforum with the new models, and I get an error every time. Listed below. The v1 models all work fine. 

### Steps to reproduce the problem

1. Go to Deforum tab
2. Go to control net tab inside deforum
3. Select Canny, and the latest 1.1 canny model (control_v11p_sd15_canny.pth)
4. Get error.

### What should have happened?

At step 4, I should have gotten the first frame of my animation, with CN applied to it. Like it works with the v1 models. 

### Commit where the problem happens

webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/70a0a11783747d2e77a08a63d9feeceb7d2d4f63
controlnet: https://github.com/Mikubill/sd-webui-controlnet/commit/c9a88e5b66c396ae5ebe99528df25a7b9c924cc6

### What browsers do you use to access the UI ?

Brave/ Chrome, doesn't matter for this particular issue. 

### Command Line Arguments

```Shell
--api --opt-sdp-no-mem-attention
```

### Console logs

```Shell
state_dict from [D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\models\control_v11p_sd15_canny.pth]
Error running process: D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "D:\D-SD\AUTO04\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 692, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 480, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 522, in build_control_model
    network = network_module(
  File "D:\D-SD\AUTO04\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 64, in __init__
    self.control_model = ControlNet(**self.config.model.params.control_stage_config.params)
  File "D:\D-SD\AUTO04\stable-diffusion-webui\venv\lib\site-packages\omegaconf\dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "D:\D-SD\AUTO04\stable-diffusion-webui\venv\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "D:\D-SD\AUTO04\stable-diffusion-webui\venv\lib\site-packages\omegaconf\_utils.py", line 900, in format_and_raise    _raise(ex, cause)
  File "D:\D-SD\AUTO04\stable-diffusion-webui\venv\lib\site-packages\omegaconf\_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "D:\D-SD\AUTO04\stable-diffusion-webui\venv\lib\site-packages\omegaconf\dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "D:\D-SD\AUTO04\stable-diffusion-webui\venv\lib\site-packages\omegaconf\dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "D:\D-SD\AUTO04\stable-diffusion-webui\venv\lib\site-packages\omegaconf\basecontainer.py", line 73, in _get_child    child = self._get_node(
  File "D:\D-SD\AUTO04\stable-diffusion-webui\venv\lib\site-packages\omegaconf\dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key model
    full_key: model
    object_type=dict
```

**Comment by hithereai** [comment]
For the protocol I also tested https://github.com/LonicaMewinsky/gif2gif, and got the exact same behaviour.

**Comment by hithereai** [comment]
Works after today's merged PRs.
