### ISSUE TITLE
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://github.com/Mikubill/sd-webui-controlnet C:\Users\T-300 V3\stable-diffusion-webui\tmp\sd-webui-controlnet stderr: 'Cloning into 'C:\Users\T-300 V3\stable-diffusion-webui\tmp\sd-webui-controlnet'... fatal: unable to access 'https://github.com/Mikubill/sd-webui-controlnet/': Failed to connect to 127.0.0.1 port 7890 after 2092 ms: Couldn't connect to server '[Bug]: 

### ISSUE THREAD

**Issue by amgad114111** [Mikubill/sd-webui-controlnet#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

after i take a copy of the github url and paste it in the extension in stable diffusion and this message appear 

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
.

### What should have happened?

the extension should be on the stable diffusion

### Commit where the problem happens

webui: .
controlnet: 

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
C:\Users\T-300 V3\stable-diffusion-webui>git pull
fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui.git/': Failed to connect to 127.0.0.1 port 7890 after 2092 ms: Couldn't connect to server
venv "C:\Users\T-300 V3\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [e1441589a6] from C:\Users\T-300 V3\stable-diffusion-webui\models\Stable-diffusion\model.ckpt
Creating model from config: C:\Users\T-300 V3\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 5.5s (load weights from disk: 2.9s, create model: 0.3s, apply weights to model: 0.5s, apply half(): 0.6s, move model to device: 0.5s, load textual inversion embeddings: 0.7s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.5s (import torch: 1.0s, import gradio: 0.7s, import ldm: 0.4s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 0.4s, load SD checkpoint: 6.0s, create ui: 0.2s).
Error completing request
Arguments: ('', 'https://github.com/Mikubill/sd-webui-controlnet') {}
Traceback (most recent call last):
  File "C:\Users\T-300 V3\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\T-300 V3\stable-diffusion-webui\modules\ui_extensions.py", line 153, in install_extension_from_url
    with git.Repo.clone_from(url, tmpdir) as repo:
  File "C:\Users\T-300 V3\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 1308, in clone_from
    return cls._clone(
  File "C:\Users\T-300 V3\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 1219, in _clone
    finalize_process(proc, stderr=stderr)
  File "C:\Users\T-300 V3\stable-diffusion-webui\venv\lib\site-packages\git\util.py", line 419, in finalize_process
    proc.wait(**kwargs)
  File "C:\Users\T-300 V3\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/Mikubill/sd-webui-controlnet C:\Users\T-300 V3\stable-diffusion-webui\tmp\sd-webui-controlnet
  stderr: 'Cloning into 'C:\Users\T-300 V3\stable-diffusion-webui\tmp\sd-webui-controlnet'...
fatal: unable to access 'https://github.com/Mikubill/sd-webui-controlnet/': Failed to connect to 127.0.0.1 port 7890 after 2023 ms: Couldn't connect to server
'

Error completing request
Arguments: ('', 'https://github.com/Mikubill/sd-webui-controlnet') {}
Traceback (most recent call last):
  File "C:\Users\T-300 V3\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\T-300 V3\stable-diffusion-webui\modules\ui_extensions.py", line 153, in install_extension_from_url
    with git.Repo.clone_from(url, tmpdir) as repo:
  File "C:\Users\T-300 V3\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 1308, in clone_from
    return cls._clone(
  File "C:\Users\T-300 V3\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 1219, in _clone
    finalize_process(proc, stderr=stderr)
  File "C:\Users\T-300 V3\stable-diffusion-webui\venv\lib\site-packages\git\util.py", line 419, in finalize_process
    proc.wait(**kwargs)
  File "C:\Users\T-300 V3\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 604, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- https://github.com/Mikubill/sd-webui-controlnet C:\Users\T-300 V3\stable-diffusion-webui\tmp\sd-webui-controlnet
  stderr: 'Cloning into 'C:\Users\T-300 V3\stable-diffusion-webui\tmp\sd-webui-controlnet'...
fatal: unable to access 'https://github.com/Mikubill/sd-webui-controlnet/': Failed to connect to 127.0.0.1 port 7890 after 2092 ms: Couldn't connect to server
'
```

**Comment by lllyasviel** [comment]
closed as no one can reproduce and lack descriptions

**Comment by machinex7** [comment]
I had this same error. In case anyone else has this problem as well and comes across this page, the solution was to update my local git install to the latest version. You can get the latest at https://git-scm.com/downloads

**Comment by xiaohuozilalala** [comment]
> I also encountered this problem, it should be because the network is unstable, I added 'gitclone.com' before 'github.com' and it succeeded.

Thanks!😊
