### ISSUE TITLE
ModuleNotFoundError:  No module named 'scripts.cldm'

### ISSUE THREAD

**Issue by Alchete** [Mikubill/sd-webui-controlnet#77]
Hi, I added the extension but am getting this error on startup.  

I verified that cldm.py is in fact in the extension's scripts directory.  

Seems like it's a search-path issue?  But I haven't seen anyone else with the same problem.

OS:  Windows 10

Error loading script: controlnet.py
Traceback (most recent call last):
  File "E:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  **File "E:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 15, in <module>
    from scripts.cldm import PlugableControlModel**
**ModuleNotFoundError: No module named 'scripts.cldm'**

**Comment by Alchete** [comment]
Strange, I disabled some other extensions, including one I was using as a development playground, and now controlnet loads successfully without an issue.
