### ISSUE TITLE
[Bug]: HED_Safe is not defined

### ISSUE THREAD

**Issue by StudioWren** [Mikubill/sd-webui-controlnet#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

as you can see below this is the error ive been getting since the most recent update today. I hope this helps squash some bugs for you guys.
Error loading script: global_state.py
Traceback (most recent call last):
  File "D:\AI Software\AMD WEBUI\stable-diffusion-webui-directml\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI Software\AMD WEBUI\stable-diffusion-webui-directml\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI Software\AMD WEBUI\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\global_state.py", line 21, in <module>
    "hed_safe": hed_safe,
NameError: name 'hed_safe' is not defined 

### Steps to reproduce the problem

1. Go to .... happens when loading automatic1111
2. Press ....
3. ...

### What should have happened?

load as normal.

### Commit where the problem happens

webui: 
controlnet: Seems to be a controlnet issue.

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Error loading script: global_state.py
Traceback (most recent call last):
  File "D:\AI Software\AMD WEBUI\stable-diffusion-webui-directml\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI Software\AMD WEBUI\stable-diffusion-webui-directml\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI Software\AMD WEBUI\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\global_state.py", line 21, in <module>
    "hed_safe": hed_safe,
NameError: name 'hed_safe' is not defined
```

### Additional information

hope this helps track down a bug.

**Comment by lllyasviel** [comment]
cannot reproduce. try update?

**Comment by StudioWren** [comment]
will do, thanks for the reply.

**Comment by StudioWren** [comment]
the latest update resolved the issue. great work.
