### ISSUE TITLE
[Bug]: Error running process: B:\Automatic SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py Traceback (most recent call last):   File "B:\Automatic SD\stable-diffusion-webui\modules\scripts.py", line 417, in process     script.process(p, *script_args)

### ISSUE THREAD

**Issue by zlikwidart** [Mikubill/sd-webui-controlnet#818]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Running any of the new Controlnet 1.1 models gives me this error

### Steps to reproduce the problem

Run controlnet 1.1 in Automatic 1111 SD

### What should have happened?

I should get an image that appears modified by controlnet but it doesn't

### Commit where the problem happens

webui:  22bcc7be428c94e9408f589966c2040187245d81
controlnet: 82c4228

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
100%|██████████████████████████████████████████████████████████████████████████████████| 52/52 [00:03<00:00, 15.52it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 52/52 [00:03<00:00, 14.65it/s]
Loading model: control_v11p_sd15_softedge [a8575a2a]███████████████████████████████████| 52/52 [00:03<00:00, 16.42it/s]
Loaded state_dict from [B:\Automatic SD\stable-diffusion-webui\models\ControlNet\control_v11p_sd15_softedge.pth]
Error running process: B:\Automatic SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "B:\Automatic SD\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "B:\Automatic SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 742, in process
    model_net = self.load_control_model(p, unet, model, lowvram)
  File "B:\Automatic SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 541, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "B:\Automatic SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 579, in build_control_model
    network = network_module(
  File "B:\Automatic SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 63, in __init__
    config = OmegaConf.load(config_path)
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\omegaconf\omegaconf.py", line 188, in load
    obj = yaml.load(f, Loader=get_yaml_loader())
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "B:\Automatic SD\stable-diffusion-webui\venv\lib\site-packages\yaml\scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "B:\Automatic SD\stable-diffusion-webui\models\ControlNet\control_v11p_sd15_softedge.yaml", line 3, column 1
```

### Additional information

Just not getting anything out of CNet 1.1 currently

**Comment by lllyasviel** [comment]
your yaml files are corrupted. download yaml files again

**Comment by SomeRandomWeirdGuy** [comment]
> 

which files? I'm getting what I think is the same issue, and I redownloaded the control_v11p_sd15_canny.yaml etc files and restarted, and it's still not working for me. Previewing the annotation works, but actually running the controlnet fails

**Comment by zlikwidart** [comment]
> > 
> 
> which files? I'm getting what I think is the same issue, and I redownloaded the control_v11p_sd15_canny.yaml etc files and restarted, and it's still not working for me. Previewing the annotation works, but actually running the controlnet fails

Yeah I've redownloaded the YAML from huggingface and I'm still getting the error

**Comment by zlikwidart** [comment]
I had to manually copy and paste the code into my yaml file.  Right clicking and saving isn't working.

**Comment by lllyasviel** [comment]
Do not right click the filenames in HuggingFace website to download. Some users right clicked those HuggingFace HTML websites as save them as YAML files. They are not downloading YAML files. Instead, click the small download arror icon “↓” in HuggingFace to download.
