### ISSUE TITLE
[Bug]:  no model is working , its coming with "AssertionError: Error: The model config /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_depth_fp16.yaml is missing. ControlNet 1.1 must have configs." error

### ISSUE THREAD

**Issue by revolverocelot1** [Mikubill/sd-webui-controlnet#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

its not working, i checked the github file, no similar file is there

### Steps to reproduce the problem

just try to run it

### What should have happened?

ran peoperly

### Commit where the problem happens

webui: 
controlnet: model and after running

### Command Line Arguments

```Shell
Loaded state_dict from [/content/stable-diffusion-webui/models/ControlNet/control_v11p_sd15_depth_fp16.safetensors]
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 717, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 496, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 541, in build_control_model
    assert os.path.exists(override_config), f'Error: The model config {override_config} is missing. ControlNet 1.1 must have configs.'
AssertionError: Error: The model config /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_depth_fp16.yaml is missing. ControlNet 1.1 must have configs.
```

### Console logs

```Shell
Loaded state_dict from [/content/stable-diffusion-webui/models/ControlNet/control_v11p_sd15_depth_fp16.safetensors]
Error running process: /content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 717, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 496, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/content/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 541, in build_control_model
    assert os.path.exists(override_config), f'Error: The model config {override_config} is missing. ControlNet 1.1 must have configs.'
AssertionError: Error: The model config /content/stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_v11p_sd15_depth_fp16.yaml is missing. ControlNet 1.1 must have configs.
```

**Comment by revolverocelot1** [comment]
yea, i kind of figured it out and made a fork of new names because i work on collab, if some one needs it use it, https://github.com/revolverocelot1/sd-webui-controlnet/tree/main/models

**Comment by revolverocelot1** [comment]
just made a pull request @Mikubill , @lllyasviel or any other approved contributor accept this? https://github.com/Mikubill/sd-webui-controlnet/pull/855

**Comment by lllyasviel** [comment]
fixed
