### ISSUE TITLE
[Bug]: Can't save ControlNet settings

### ISSUE THREAD

**Issue by rethink-studios** [Mikubill/sd-webui-controlnet#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

When deactivating "Do not append", and attempting to save settings, this error is displayed:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\ui.py", line 1406, in run_settings
    assert comp == dummy_component or opts.same_type(value, opts.data_labels[key].default), f"Bad value for setting {key}: {value}; expecting {type(opts.data_labels[key].default).__name__}"
AssertionError: Bad value for setting modelscope_deforum_keep_model_in_vram: False; expecting str

![image](https://user-images.githubusercontent.com/60104539/232664573-2f34a3a5-6368-46b0-857b-9fbd74038120.png)

### Steps to reproduce the problem

1. Go to Settings
2. Press ControlNet:
3. Click Do not append detectmap to output
4. Apply Settings

### What should have happened?

Settings should have saved

### Commit where the problem happens

webui: 22bcc7be428c94e9408f589966c2040187245d81
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Launching Web UI with arguments: --xformers --allow-code --no-half-vae --disable-nan-check --autolaunch --opt-channelslast --skip-torch-cuda-test --always-batch-cond-uncond --opt-split-attention --theme dark --api --cors-allow-origins=http://127.0.0.1:7860
```

### Console logs

```Shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.4s (load scripts: 1.8s, create ui: 4.4s, gradio launch: 0.1s).
Error completing request
Arguments: (True, 'png', '', True, True, 'png', False, True, False, -1, True, True, False, False, False, False, False, 80, False, True, 4.0, 4000.0, 200.0, False, False, True, False, '', False, True, False, '', 'outputs/txt2img-images', 'outputs/img2img-images', 'outputs/extras-images', '', 'outputs/txt2img-grids', 'outputs/img2img-grids', 'log/images', True, True, True, '[date]', 8, 192, 8, ['R-ESRGAN 4x+', 'R-ESRGAN 4x+ Anime6B'], None, 100, False, 192, 8, 'CodeFormer', 0, False, False, 8, False, True, False, False, False, False, True, '', ' ', 1, 500.0, False, False, False, 120.0, None, 0, 0, 'Automatic', True, 1, None, None, True, '#ffffff', False, True, True, 20, 1, False, False, False, False, False, False, False, 1, 24, 48, 1500.0, [], 0.5, True, False, True, '', 'cards', 1, 0.0, 0.0, ' ', 'None', 'None', True, False, False, False, True, True, False, True, True, '', True, True, True, True, True, 0.1, 0.05, 'sd_model_checkpoint, initial_noise_multiplier, img2img_color_correction', [], 'inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts', '', 'None', True, True, True, 10, 'Approx NN', 'Prompt', 1000.0, ['Euler', 'LMS', 'DPM2', 'DPM2 a', 'DPM fast', 'DPM adaptive', 'LMS Karras', 'DPM2 Karras', 'DPM2 a Karras', 'DDIM', 'PLMS'], 0, 1, 'uniform', 0, 0, 1, 0, False, 'bh1', 'time_uniform', 3, True, [], [], 5, None, None, None, False, False, 'models/Deforum/deforum_persistent_settings.txt', 'D:\\stable-diffusion-webui\\venv\\lib\\site-packages\\imageio_ffmpeg\\binaries\\ffmpeg-win64-v4.2.2.exe', 17, 'slow', False, False, ['Noise Schedule'], '', 'infinite-zooms', 512, 512, '', '#ffffff', '#ffffff', 512, 512, True, True, True, False, 'D:\\stable-diffusion-webui\\models\\Lora', 'name', False, '', '', 1.0, True, False, 'disabled', 20.0, 20.0, True, '1:1, 3:2, 4:3, 5:4, 16:9, 1.85:1, 2.35:1, 2.39:1, 2.40:1, 21:9, 1.375:1, 1.66:1, 1.75:1', 'Aspect Ratios Dropdown', True, False, 'MaxDimensionScaler, PredefinedAspectRatioButtons, PredefinedPercentageButtons', True, 1024, True, False, '1:1, 4:3, 16:9, 9:16, 21:9', True, '25, 50, 75, 125, 150, 175, 200', 'Incremental/decremental percentage (-50%, +50%)', 'D:\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\models\\cldm_v21.yaml', 'D:\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\models\\sketch_adapter_v14.yaml', 'D:\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\detected_maps', '', 4, 2, False, False, True, False, False, True, False, False, False, 'GPU (half precision)', -1.0, 'mocha', 'maroon', False, 1600.0, False, True, True, 2048.0, 'txt2img, img2img, txt2img-grids, img2img-grids, Extras, Favorites, Others', [], True, False, True, True, '0 - none', False, True, False, False, True, False, 6.0, 6.0, 20.0, False, 200.0, False, False, False, True, '{', '}', '__', False, False, 'Gustavosta/MagicPrompt-Stable-Diffusion', 1, 'bHEpG9Rp0Nq9XrLcwFNu') {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\ui.py", line 1406, in run_settings
    assert comp == dummy_component or opts.same_type(value, opts.data_labels[key].default), f"Bad value for setting {key}: {value}; expecting {type(opts.data_labels[key].default).__name__}"
AssertionError: Bad value for setting modelscope_deforum_keep_model_in_vram: False; expecting str

Error completing request
Arguments: (True, 'png', '', True, True, 'png', False, True, False, -1, True, True, False, False, False, False, False, 80, False, True, 4.0, 4000.0, 200.0, False, False, True, False, '', False, True, False, '', 'outputs/txt2img-images', 'outputs/img2img-images', 'outputs/extras-images', '', 'outputs/txt2img-grids', 'outputs/img2img-grids', 'log/images', True, True, True, '[date]', 8, 192, 8, ['R-ESRGAN 4x+', 'R-ESRGAN 4x+ Anime6B'], None, 100, False, 192, 8, 'CodeFormer', 0, False, False, 8, False, True, False, False, False, False, True, '', ' ', 1, 500.0, False, False, False, 120.0, None, 0, 0, 'Automatic', True, 1, None, None, True, '#ffffff', False, True, True, 20, 1, False, False, False, False, False, False, False, 1, 24, 48, 1500.0, [], 0.5, True, False, True, '', 'cards', 1, 0.0, 0.0, ' ', 'None', 'None', True, False, False, False, True, True, False, True, True, '', True, True, True, True, True, 0.1, 0.05, 'sd_model_checkpoint, initial_noise_multiplier, img2img_color_correction', [], 'inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts', '', 'None', True, True, True, 10, 'Approx NN', 'Prompt', 1000.0, ['Euler', 'LMS', 'DPM2', 'DPM2 a', 'DPM fast', 'DPM adaptive', 'LMS Karras', 'DPM2 Karras', 'DPM2 a Karras', 'DDIM', 'PLMS'], 0, 1, 'uniform', 0, 0, 1, 0, False, 'bh1', 'time_uniform', 3, True, [], [], 5, None, None, None, False, False, 'models/Deforum/deforum_persistent_settings.txt', 'D:\\stable-diffusion-webui\\venv\\lib\\site-packages\\imageio_ffmpeg\\binaries\\ffmpeg-win64-v4.2.2.exe', 17, 'slow', False, False, ['Noise Schedule'], '', 'infinite-zooms', 512, 512, '', '#ffffff', '#ffffff', 512, 512, True, True, True, False, 'D:\\stable-diffusion-webui\\models\\Lora', 'name', False, '', '', 1.0, True, False, 'disabled', 20.0, 20.0, True, '1:1, 3:2, 4:3, 5:4, 16:9, 1.85:1, 2.35:1, 2.39:1, 2.40:1, 21:9, 1.375:1, 1.66:1, 1.75:1', 'Aspect Ratios Dropdown', True, False, 'MaxDimensionScaler, PredefinedAspectRatioButtons, PredefinedPercentageButtons', True, 1024, True, False, '1:1, 4:3, 16:9, 9:16, 21:9', True, '25, 50, 75, 125, 150, 175, 200', 'Incremental/decremental percentage (-50%, +50%)', 'D:\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\models\\cldm_v21.yaml', 'D:\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\models\\sketch_adapter_v14.yaml', 'D:\\stable-diffusion-webui\\extensions\\sd-webui-controlnet\\detected_maps', '', 4, 2, False, False, False, False, False, True, False, False, False, 'GPU (half precision)', -1.0, 'mocha', 'maroon', False, 1600.0, False, True, True, 2048.0, 'txt2img, img2img, txt2img-grids, img2img-grids, Extras, Favorites, Others', [], True, False, True, True, '0 - none', False, True, False, False, True, False, 6.0, 6.0, 20.0, False, 200.0, False, False, False, True, '{', '}', '__', False, False, 'Gustavosta/MagicPrompt-Stable-Diffusion', 1, 'bHEpG9Rp0Nq9XrLcwFNu') {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\ui.py", line 1406, in run_settings
    assert comp == dummy_component or opts.same_type(value, opts.data_labels[key].default), f"Bad value for setting {key}: {value}; expecting {type(opts.data_labels[key].default).__name__}"
AssertionError: Bad value for setting modelscope_deforum_keep_model_in_vram: False; expecting str
```

**Comment by ljleb** [comment]
Refresh the page, or reload the webui. I assume this is related to a gradio update as I cannot reproduce.
