### ISSUE TITLE
[Bug]: ValueError: Key `epoch` is invalid, expected torch.Tensor but received <class 'int'>

### ISSUE THREAD

**Issue by alelordelo** [Mikubill/sd-webui-controlnet#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Tried to extract a ControlNet and got an error.

### Steps to reproduce the problem

1. Run this:
!python extract_controlnet.py --src "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/epoch=76-step=38576.ckpt" --dst "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/latestconverted.safetensors"
. 
2.got this:
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/extract_controlnet.py", line 25, in <module>
    save_file(state_dict, args.dst)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 71, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 221, in _flatten
    raise ValueError(f"Key `{k}` is invalid, expected torch.Tensor but received {type(v)}")
ValueError: Key `epoch` is invalid, expected torch.Tensor but received <class 'int'>

### What should have happened?

Should have extracted the safetensor

### Commit where the problem happens

webui: 
controlnet: [20a5310]

### What browsers do you use to access the UI ?

Apple Safari

### Command Line Arguments

```Shell
!python extract_controlnet.py --src "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/epoch=76-step=38576.ckpt" --dst "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/latestconverted.safetensors"
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/extract_controlnet.py", line 25, in <module>
    save_file(state_dict, args.dst)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 71, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 221, in _flatten
    raise ValueError(f"Key `{k}` is invalid, expected torch.Tensor but received {type(v)}")
ValueError: Key `epoch` is invalid, expected torch.Tensor but received <class 'int'>
```

**Comment by alelordelo** [comment]
fixed with this:
!python extract_controlnet.py --src "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/epoch=76-step=38576.ckpt" --dst "/content/drive/MyDrive/stable-diffusion-webui-colab/stable-diffusion-webui/extensions/sd-webui-controlnet/models/latestconverted.ckpt"

**Comment by alelordelo** [comment]
actually, not sure if the fixed the issue...

The latestconverted.ckpt model has the same size of epoch=76-step=38576.ckpt, which is 8.5GB.

Shouldn't this reduce the file size?
