### ISSUE TITLE
[Bug]: IndexError: list index out of range

### ISSUE THREAD

**Issue by My12123** [Mikubill/sd-webui-controlnet#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

restart

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

restart

### Commit where the problem happens

python: 3.10.10  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.23.0  •  commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)  •  checkpoint: [fbcf965a62](https://google.com/search?q=fbcf965a62d9d82e935d3d17e97522c29f44550aa9e120a6886f19b578521ec5)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers
```

### Console logs

```Shell
venv "M:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Installing sd-webui-controlnet requirement: mediapipe==0.9.1.0
Installing sd-webui-controlnet requirement: opencv-python

Installing requirements for Adverse Cleaner

Launching Web UI with arguments: --xformers
Loading weights [fbcf965a62] from M:\stable-diffusion-webui\models\Stable-diffusion\anything-v4.5.ckpt
Creating model from config: M:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): fish with legs
Model loaded in 166.1s (load weights from disk: 139.0s, create model: 3.5s, apply weights to model: 1.5s, apply half(): 1.4s, move model to device: 1.3s, load textual inversion embeddings: 19.4s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 260.6s (import torch: 30.6s, import gradio: 24.6s, import ldm: 8.5s, other imports: 21.1s, list SD models: 0.3s, setup codeformer: 1.5s, list builtin upscalers: 0.1s, load scripts: 4.9s, load SD checkpoint: 166.6s, create ui: 2.0s, gradio launch: 0.4s).
Closing server running on port: 7860
Restarting UI...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 3.1s (load scripts: 1.2s, reload script modules: 0.2s, create ui: 1.6s, gradio launch: 0.1s).
Traceback (most recent call last):
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
Traceback (most recent call last):
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "M:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
```

**Comment by ljleb** [comment]
This usually happens when you restart the backend without refreshing the browser gradio page. Although you probably tried this, just to be sure, does it work if you simply hit f5 or ctrl+f5 on your keyboard while in the browser window?

**Comment by My12123** [comment]
Yes

**Comment by ljleb** [comment]
IIUC this issue is resolved then? I'm closing, let me know if I misinterpreted your response.
