### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by HWiese1980** [Mikubill/sd-webui-controlnet#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I'm getting the following error with a freshly installed venv upon calling depth-related ControlNet preprocessors.

```
Traceback (most recent call last):
  File "K:\stablediffusionwebui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "K:\stablediffusionwebui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "K:\stablediffusionwebui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "K:\stablediffusionwebui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "K:\stablediffusionwebui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "K:\stablediffusionwebui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 399, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\processor.py", line 427, in zoe_depth
    result = model_zoe_depth(img)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 38, in __call__
    self.load_model()
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 27, in load_model
    model = ZoeDepth.build_from_config(conf)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas.py", line 343, in build
    midas = torch.hub.load(midas_path, midas_model_type,
  File "K:\stablediffusionwebui\venv\lib\site-packages\torch\hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "K:\stablediffusionwebui\venv\lib\site-packages\torch\hub.py", line 569, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "K:\stablediffusionwebui\venv\lib\site-packages\torch\hub.py", line 90, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\hubconf.py", line 5, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'
```

### Steps to reproduce the problem

I have no idea if and how this might be reproducable...

### What should have happened?

Well, the error should not have occurred in the first place. Depth delated stuff should work.

### Commit where the problem happens

webui:  d75b3fb2f0f6b7794898b7baaa90e0a097586fda
controlnet:  937e8f07

### Command Line Arguments

```Shell
--xformers --listen --enable-insecure-extension-access --api --cors-allow-origins-regex="https?://((localhost|127\.0\.0\.1|192\.168\.\d+\.\d+):\d+|example\.com)"
```

### Console logs

```Shell
Already up to date.
venv "K:\stablediffusionwebui\venv\Scripts\Python.exe"
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Commit hash: d75b3fb2f0f6b7794898b7baaa90e0a097586fda
Installing requirements for Web UI
Installing sd-webui-controlnet requirement: mediapipe==0.9.1.0
Installing sd-webui-controlnet requirement: opencv-python


Installing requirements for Unprompted - img2pez
Installing requirements for Unprompted - pix2pix_zero
Installing requirements for Unprompted - zoom_enhance

Launching Web UI with arguments: --xformers --listen --enable-insecure-extension-access --api --cors-allow-origins-regex=https?://((localhost|127\.0\.0\.1|192\.168\.\d+\.\d+):\d+|example\.com)
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: K:\stablediffusionwebui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Loading Unprompted v8.2.0 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Debug mode is False
Loading weights [9aba26abdf] from K:\stablediffusionwebui\models\Stable-diffusion\deliberate_v2.safetensors
Creating model from config: K:\stablediffusionwebui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: K:\stablediffusionwebui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(26): *****
Model loaded in 4.8s (load weights from disk: 0.3s, create model: 0.7s, apply weights to model: 0.8s, apply half(): 0.8s, load VAE: 0.3s, move model to device: 0.8s, load textual inversion embeddings: 1.1s).
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 24.9s (import torch: 2.9s, import gradio: 2.2s, import ldm: 0.7s, other imports: 1.6s, setup codeformer: 0.1s, load scripts: 3.5s, load SD checkpoint: 5.0s, create ui: 4.4s, gradio launch: 4.3s).
ControlNet preprocessor location: K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\downloads
img_size [384, 512]
Traceback (most recent call last):
  File "K:\stablediffusionwebui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "K:\stablediffusionwebui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "K:\stablediffusionwebui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "K:\stablediffusionwebui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "K:\stablediffusionwebui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "K:\stablediffusionwebui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 399, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\scripts\processor.py", line 427, in zoe_depth
    result = model_zoe_depth(img)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 38, in __call__
    self.load_model()
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 27, in load_model
    model = ZoeDepth.build_from_config(conf)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas.py", line 343, in build
    midas = torch.hub.load(midas_path, midas_model_type,
  File "K:\stablediffusionwebui\venv\lib\site-packages\torch\hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "K:\stablediffusionwebui\venv\lib\site-packages\torch\hub.py", line 569, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "K:\stablediffusionwebui\venv\lib\site-packages\torch\hub.py", line 90, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\hubconf.py", line 5, in <module>
    from midas.dpt_depth import DPTDepthModel
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "K:\stablediffusionwebui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'
```

### Additional information

More or less copied from the Automatic1111 issues board, as this is probably an extension related issue. The problem however occurs with other extensions that use midas depth as well. Deforum for instance.

**Comment by becausecurious** [comment]
I had this issue when I had timm==0.4.12. It was coming from https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements.txt, which was hardcoded in my command to launch the web ui. After fixing the command to not mention requirements.txt it started using https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements_versions.txt i.e. timm==0.6.7 and this solved the issue for me.

**Comment by Sefrautic** [comment]
> I had this issue when I had timm==0.4.12. It was coming from https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements.txt, which was hardcoded in my command to launch the web ui. After fixing the command to not mention requirements.txt it started using https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements_versions.txt i.e. timm==0.6.7 and this solved the issue for me.

I have the same issue with the zoe depth annotator exclusively, but can't quite grasp what you did to fix the problem. Can you please explain the steps on how to fix the error?

**Comment by HWiese1980** [comment]
Weirdly enough, it's also exclusively the zoe depth preprocessor for me now. The other two are working again.

**Comment by HWiese1980** [comment]
> > I had this issue when I had timm==0.4.12. It was coming from https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements.txt, which was hardcoded in my command to launch the web ui. After fixing the command to not mention requirements.txt it started using https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements_versions.txt i.e. timm==0.6.7 and this solved the issue for me.
> 
> I have the same issue with the zoe depth preprocessor exclusively, but can't quite grasp what you did to fix the problem. Can you please explain the steps on how to fix the error?

Sounds like they updated `timm` in the corresponding `requirements.txt` and reinstalled the dependencies.

**Comment by Sefrautic** [comment]
@HWiese1980 I rewrote version to 0.6.7, deleted venv and now waiting for dependencies to install

**Comment by HWiese1980** [comment]
Keep us informed if that solves the issue, please

**Comment by Sefrautic** [comment]
@HWiese1980 Yep, it's totally working, all 3 depth preprocessors. Would be nice to figure out what exact files you need to delete from venv, rather than entire folder, to fix the issue more easily. If anybody needs help, mention me here
