### ISSUE TITLE
Segmentation errors

### ISSUE THREAD

**Issue by mattieshadow** [Mikubill/sd-webui-controlnet#92]
When attempting to use the segmentation processor, I get an error.
`Traceback (most recent call last):
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\processing.py", line 628, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\processing.py", line 828, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 323, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 221, in launch_sampling
    return func()
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 323, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "B:\AI Generation Stuff\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "B:\AI Generation Stuff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 116, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "B:\AI Generation Stuff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "B:\AI Generation Stuff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "B:\AI Generation Stuff\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 161, in forward2
    return forward(*args, **kwargs)
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\cldm.py", line 122, in forward
    if abs(x.shape[-1] - outer.hint_cond.shape[-1] // 8) > 8:
AttributeError: 'NoneType' object has no attribute 'shape'`

Some more:
`Arguments: ('task(k0tvded5hleb1td)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=512x512 at 0x22FC1CBB130>, None, None, None, None, None, None, 20, 0, 8, 0, 0, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 0, True, 'segmentation', 'control_sd15_seg [fef5e48e]', 1, {'image': array([[[221, 210, 226],`

And last one:
`Error running process: B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "B:\AI Generation Stuff\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 317, in process
    detected_map = preprocessor(input_image)
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 136, in uniformer
    from annotator.uniformer import apply_uniformer
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\__init__.py", line 1, in <module>
    from annotator.uniformer.mmseg.apis import init_segmentor, inference_segmentor, show_result_pyplot
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\apis\__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\apis\inference.py", line 8, in <module>
    from annotator.uniformer.mmseg.models import build_segmentor
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\models\__init__.py", line 4, in <module>
    from .decode_heads import *  # noqa: F401,F403
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\models\decode_heads\__init__.py", line 4, in <module>
    from .cc_head import CCHead
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmseg\models\decode_heads\cc_head.py", line 7, in <module>
    from annotator.uniformer.mmcv.ops import CrissCrossAttention
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmcv\ops\__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmcv\ops\assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "B:\AI Generation Stuff\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\uniformer\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.`

I read the readme, and installed both prettytables and the other. I updated my Automatic1111 and this extension to latest prior to posting this, and attempting a multitude of different things to fix this issue. Can anyone be of assistance?

**Comment by Mikubill** [comment]
maybe related: https://github.com/Mikubill/sd-webui-controlnet/issues/70

**Comment by mattieshadow** [comment]
Yeah, and that issue fixed mine.
