### ISSUE TITLE
[Bug]: Control Net is not working

### ISSUE THREAD

**Issue by SGKino** [Mikubill/sd-webui-controlnet#928]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

The control net suddenly doesn't work.

### Steps to reproduce the problem

Unknown

### What should have happened?

Unknown

### Commit where the problem happens

webui: can work as usual
controlnet: not working, got erased from the UI

I have installed it once, and then reinstalled, yet the problem is still

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Error loading script: api.py
Traceback (most recent call last):
  File "I:\SDAI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "I:\SDAI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\SDAI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 13, in <module>
    from modules.api import api
  File "I:\SDAI\stable-diffusion-webui\modules\api\api.py", line 9, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (I:\SDAI\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py)

Error loading script: controlnet.py
Traceback (most recent call last):
  File "I:\SDAI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "I:\SDAI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\SDAI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 16, in <module>
    from scripts import global_state, hook, external_code, processor
  File "I:\SDAI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 7, in <module>
    from modules.api import api
  File "I:\SDAI\stable-diffusion-webui\modules\api\api.py", line 9, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (I:\SDAI\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py)

Error loading script: external_code.py
Traceback (most recent call last):
  File "I:\SDAI\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "I:\SDAI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\SDAI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 7, in <module>
    from modules.api import api
  File "I:\SDAI\stable-diffusion-webui\modules\api\api.py", line 9, in <module>
    from gradio.processing_utils import decode_base64_to_file
ImportError: cannot import name 'decode_base64_to_file' from 'gradio.processing_utils' (I:\SDAI\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py)
```

**Comment by SGKino** [comment]
> You somehow have a newer version of Gradio installed, you should be on `3.23.0`. This error isn't related to ControlNet.

Millions thanks. You really save my life. Bless you.

**Comment by MatiasWyso** [comment]
how can i fix it?
