### ISSUE TITLE
[Bug]: Tensor for argument #2 'mat1' is on CPU

### ISSUE THREAD

**Issue by CharlesTHN** [Mikubill/sd-webui-controlnet#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

MacBook Air M1 16 GB , 

When running openpose, depth, and lineart to generate images, a RuntimeError occurs. 

But it's work when controlnet disabled

### Steps to reproduce the problem

1. Go to txt2img
2. select contolnet and choose openpose or depth or lineart
3. prompt just "1 girl", and generate

### What should have happened?

no error

### Commit where the problem happens

webui: 

python: 3.10.10  •  torch: 1.12.1  •  xformers: N/A  •  gradio: 3.23.0  •  commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)  •  checkpoint: [6ce0161689](https://google.com/search?q=6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa)

controlnet: 
Version : a946afb3 (Mon Apr 17 00:40:26 2023)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-split-attention --
skip-version-check --lowvram --skip-torch-cuda-test --no-half --use-cpu all
```

### Console logs

```Shell
Arguments: ('task(gddiisfylhsnfcy)', '\x081girl', '', [], 20, 16, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, '', 0, <scripts.external_code.ControlNetUnit object at 0x384aa71c0>, <scripts.external_code.ControlNetUnit object at 0x384db0340>, <scripts.external_code.ControlNetUnit object at 0x384db1540>, <scripts.external_code.ControlNetUnit object at 0x385014790>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 132, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict([cond_in[a:b]], image_cond_in[a:b]))
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 270, in forward2
    return forward(*args, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 202, in forward
    control = param.control_model(x=x_in, hint=param.used_hint_cond, timesteps=timesteps, context=context)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 115, in forward
    return self.control_model(*args, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 368, in forward
    emb = self.time_embed(t_emb)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 307, in lora_Linear_forward
    return torch.nn.Linear_forward_before_lora(self, input)
  File "/Users/thn/Desktop/lightchain/project/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Tensor for argument #2 'mat1' is on CPU, but expected it to be on GPU (while checking arguments for addmm_out_mps_impl)
```
```


### Additional information

_No response_

**Comment by amujiu318** [comment]
Ran into same issue running on Mac cpu

**Comment by CharlesTHN** [comment]
I edited devices.py like this , it works。
But I don't know if it will have any other effect

![image](https://user-images.githubusercontent.com/19632429/233559443-c8394d33-a8e8-492e-8f9d-c1a3e00bf875.png)
