### ISSUE TITLE
[Bug]: ControlNet is not loading after latest update

### ISSUE THREAD

**Issue by DavidSchobl** [Mikubill/sd-webui-controlnet#932]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

After latest update I did today, ControlNET just stopped working at load. It is not loaded and in console I got this error:

```
Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 8, in <module>
    from scripts.global_state import update_cn_models, cn_models_names
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 21, in <module>
    "hed_safe": hed_safe,
NameError: name 'hed_safe' is not defined
```

Can you advice me how to repair it?

### Steps to reproduce the problem

Update ControlNet
and thats it, it stopped working.

### What should have happened?

It should update and work as before.

### Commit where the problem happens

Startup.

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--api --theme=dark --listen  --xformers --enable-insecure-extension-access
```

### Console logs

```Shell
Error loading script: xyz_grid_support.py
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\xyz_grid_support.py", line 8, in <module>
    from scripts.global_state import update_cn_models, cn_models_names
  File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\global_state.py", line 21, in <module>
    "hed_safe": hed_safe,
NameError: name 'hed_safe' is not defined
```

**Comment by mendynew** [comment]
have you downloaded the models and put into the correct folder?

**Comment by DavidSchobl** [comment]
> 

I have used integrated update engine in AUTOMATIC1111. As I did many times before. Only exception is that before it did not ruin my controlnet. :)

**Comment by ljleb** [comment]
If you reload the gradio interface a second time it should work. You can also restart your webui completely to be sure. IIUC #793 fixes this.
