### ISSUE TITLE
[Bug]: ImportError: cannot import name 'annotator_path' from 'annotator'  in controlnet.py

### ISSUE THREAD

**Issue by drwootton** [Mikubill/sd-webui-controlnet#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I'm running current automatic1111 with python 3.10 on Fedora 36 Linux. I have the ControlNet extension installed along with other extensions.

When I start webui.sh it runs for a while then I get the following error and traceback. Even though I have ControlNet enabled, it does not appear in the UI.

```
Launching Web UI with arguments: --xformers --theme=dark
/nvme/dave/git/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Error loading script: controlnet.py
Traceback (most recent call last):
  File "/nvme/dave/git/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/nvme/dave/git/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nvme/dave/git/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 15, in <module>
    from annotator import annotator_path
ImportError: cannot import name 'annotator_path' from 'annotator' (/nvme/dave/git/stable-diffusion-webui/venv/lib/python3.10/site-packages/annotator/__init__.py)
```

I think this is related to pull request #933. My venv setup for automatic1111 has an **annotator** package in it. I think this conflicts with the annotator directory in  the ControlNet repository since annotator_path can't be resolved.

I hacked this by creating an annotator2 symlink pointing to annotator and changed line 15 in controlnet.py to import from annotator2 and the error is gone.

### Steps to reproduce the problem

1. Update automatic1111 to current (22bcc7be428c94e9408f589966c2040187245d81)  and the ControlNet extension to commit d7c5dd45b15b4164e99b4690fd23d98145a1c4b9
2. Run webui.sh
3. Get noted exception

### What should have happened?

Successful startup with ControlNet present in UI

### Commit where the problem happens

webui: 22bcc7be428c94e9408f589966c2040187245d81
controlnet: d7c5dd45b15b4164e99b4690fd23d98145a1c4b9

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--xformers --theme=dark
```

### Console logs

```Shell
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on dave user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Installing None
Installing onnxruntime-gpu...
Installing None
Installing opencv-python...
Installing None
Installing Pillow...
Installing None
Installing segmentation-refinement...
Installing None
Installing scikit-learn...


Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...




current transparent-background 1.2.3



Launching Web UI with arguments: --xformers --theme=dark
/nvme/dave/git/stable-diffusion-webui/venv/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Error loading script: controlnet.py
Traceback (most recent call last):
  File "/nvme/dave/git/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/nvme/dave/git/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nvme/dave/git/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 15, in <module>
    from annotator import annotator_path
ImportError: cannot import name 'annotator_path' from 'annotator' (/nvme/dave/git/stable-diffusion-webui/venv/lib/python3.10/site-packages/annotator/__init__.py)
```

**Comment by ljleb** [comment]
So should we rename the annotator module? Without the importlib reload, users have to restart the webui completely for some settings change to take effect.

**Comment by ljleb** [comment]
Maybe we should move the annotator settings to a different module, i.e. global_state.
