### ISSUE TITLE
[Bug]: API : invalid encoded image 

### ISSUE THREAD

**Issue by psykokwak-com** [Mikubill/sd-webui-controlnet#950]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Since I updated to ControlNet 1.1, my scripts doesn't works.

### Steps to reproduce the problem

My script (see below) worked great with previous controlnet 1.0.

```
def myOpenImgFile(path):
    img = Image.open(path)
    #img.show()
    w, h = img.size

    encoded = ""  
    with io.BytesIO() as output:
        img.save(output, format="PNG")
        contents = output.getvalue()
        encoded = str(base64.b64encode(contents), encoding='utf-8')
        
    img.close()

    return encoded, w, h

def processStableDiffusion(json_payload):

    payload = json.dumps(json_payload)
    res = requests.post(url="http://127.0.0.1:7860/sdapi/v1/img2img", data=payload).json()

    imgs = []

    if res.get("images") is None:
        print("Error, got this returned:")
        print(res)
    else:
        for i in res['images']:
            imgs.append(i)
            
            img = Image.open(io.BytesIO(base64.b64decode(i)))
            #img.show()
    
    return imgs

def main()
    img_input_buffer, img_input_width, img_input_height = myOpenImgFile("myimg.jpg")
    img_output_width, img_output_height = myMaxOutputImgSize(img_input_width, img_input_height)

    img_prompt = "my prompt"
    img_neg_prompt = "my neg prompt"

    
    print("Generate image " + filename_input + " to " + filename_output)
    print("use prompt = " + img_prompt)

    # Stage 1 : Generate pass 1
    payload_02 = {
      "init_images": [
        img_input_buffer
      ],
      "resize_mode": 1,
      "denoising_strength": 9,
      "width": img_output_width,
      "height": img_output_height,
      "mask": "",
      "mask_blur": 4,
      "inpainting_fill": 2,
      "inpaint_full_res": False,
      "prompt": img_prompt,
      "negative_prompt": img_neg_prompt,
      "styles": [
        "Default"
      ],
      "alwayson_scripts": {
        "controlnet": {
          "args": [
            {
              "input_image": "",
              "mask": "",
              "module": "openpose",
              "model": "control_v11p_sd15_openpose [cab727d4]",
              "weight": 1,
              "resize_mode": "Scale to Fit (Inner Fit)",
              "lowvram": False,
              "processor_res": 64,
              "threshold_a": 64,
              "threshold_b": 64,
              "guidance": 1,
              "guidance_start": 0,
              "guidance_end": 1,
              "guessmode": False,
            }
          ]
        }
      }
    }

    images_pass_1 = processStableDiffusion(payload_02)
    #myShowImg(images_pass_1[0])
```

### What should have happened?

The script should generate an image taking controlnet openpose filter into account. But since the ControlNet 1.1 update, It get the following error.

### Commit where the problem happens

webui: 22bcc7be428c94e9408f589966c2040187245d81
controlnet: 85701f18 

### Command Line Arguments

```Shell
Launching Web UI with arguments: --xformers --api --gradio-img2img-tool color-sketch
```

### Console logs

```Shell
Error running process: C:\Users\Jyce\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Jyce\Desktop\stable-diffusion-webui\modules\api\api.py", line 62, in decode_base64_to_image
    image = Image.open(BytesIO(base64.b64decode(encoding)))
  File "C:\Users\Jyce\Desktop\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x0000029E2FF6EAC0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jyce\Desktop\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\Users\Jyce\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 824, in process
    image = image_dict_from_unit(unit)
  File "C:\Users\Jyce\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 123, in image_dict_from_unit
    result['image'] = external_code.to_base64_nparray(result['image'])
  File "C:\Users\Jyce\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\external_code.py", line 92, in to_base64_nparray
    return np.array(api.decode_base64_to_image(encoding)).astype('uint8')
  File "C:\Users\Jyce\Desktop\stable-diffusion-webui\modules\api\api.py", line 65, in decode_base64_to_image
    raise HTTPException(status_code=500, detail="Invalid encoded image")
```

**Comment by lllyasviel** [comment]
perhaps try to add 
"pixel_perfect": False 
next to "guessmode": False,

**Comment by psykokwak-com** [comment]
Still crash :(

**Comment by lllyasviel** [comment]
I am not familiar with api but will take a look

**Comment by lllyasviel** [comment]
can you produce more detailed steps for reproduce this?

**Comment by ljleb** [comment]
Can you try removing the `image` and `mask` properties altogether?

**Comment by lllyasviel** [comment]
perhaps change
"resize_mode": "Scale to Fit (Inner Fit)",
to
"resize_mode": "Crop and Resize",

**Comment by ljleb** [comment]
If you want to omit them, put `None` or json `null` for these keys.

**Comment by lllyasviel** [comment]
and what controlnet will do if  "processor_res": 64 ?
from codes it seems that if res is 64 something special will happen https://github.com/Mikubill/sd-webui-controlnet/blob/85701f1802318a42635f508f2e6344ead11bb945/scripts/controlnet.py#L409
why is this line is needed?

**Comment by psykokwak-com** [comment]
> Can you try removing the `image` and `mask` properties altogether? Instead of putting empty strings. We could test for these values but IIUC this might be the cause.

Thanks. It was the issue.
