### ISSUE TITLE
Preview seems to work, but controlnet gives various errors during inference.

### ISSUE THREAD

**Issue by skyler14** [Mikubill/sd-webui-controlnet#956]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

I just updated to the newest version of controlnet and that seems to have broken it. In the controlnet window I can get previews to display (though the preprocessor options for HED and sketch are no longer there I think), but during inference I get a large variety of different errors depending on the preprocessor, and controlnet doesn't get applied to the generation.

### Steps to reproduce the problem

1. Use Extension manager to update
2. Do txt2img or img2img, enabling controlnet and configuring with 'canny', 'openpose', etc. 
3. Inference ignores controlnet

### What should have happened?

Controlnet activate

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--xformers
```

### Console logs

```Shell
https://pastebin.com/2tq9MVRb
```

### Additional information

These are logs from various run attempts using different filters

```
100%|██████████████████████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.52it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.33it/s]
Loading model from cache: control_sd15_depth [fef5e48e]████████████████████████████████| 38/38 [00:08<00:00,  3.74it/s]
Loading preprocessor: depth_zoe
preprocessor resolution = 512
img_size [384, 512]
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 931, in process
    detected_map, is_image = preprocessor(input_image, res=preprocessor_resolution, thr_a=unit.threshold_a, thr_b=unit.threshold_b)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 427, in zoe_depth
    result = model_zoe_depth(img)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 38, in __call__
    self.load_model()
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\__init__.py", line 27, in load_model
    model = ZoeDepth.build_from_config(conf)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 250, in build_from_config
    return ZoeDepth.build(**config)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 240, in build
    core = MidasCore.build(midas_model_type=midas_model_type, use_pretrained_midas=use_pretrained_midas,
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas.py", line 343, in build
    midas = torch.hub.load(midas_path, midas_model_type,
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\zoe\zoedepth\models\base_models\midas_repo\hubconf.py", line 38, in DPT_BEiT_L_384
    model = DPTDepthModel(
  File "C:\Users\Skyler\Documents\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/src\midas\dpt_depth.py", line 102, in __init__
    self.scratch.refinenet2 = _make_fusion_block(features, use_bn)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/src\midas\dpt_depth.py", line 55, in __init__
    "swinl12_384": [1, 1, 17, 1],                   # [0, 1], [0,  1], [ 0, 17], [ 0,  1]
KeyError: 'beitl16_384'

100%|██████████████████████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.32it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 38/38 [00:09<00:00,  4.16it/s]
Loading model: control_sd15_canny [fef5e48e]███████████████████████████████████████████| 38/38 [00:09<00:00,  3.82it/s]
Loaded state_dict from [C:\Users\Skyler\Downloads\controlnet\control_sd15_canny.pth]
Loading config: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\models\cldm_v15.yaml
ControlNet model control_sd15_canny [fef5e48e] loaded.
Loading preprocessor: canny
preprocessor resolution = 512
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 980, in process
    global_average_pooling=model_net.config.model.params.get("global_average_pooling", False),
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PlugableControlModel' object has no attribute 'config'

100%|██████████████████████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.56it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.37it/s]
Loading model: control_sd15_openpose [fef5e48e]████████████████████████████████████████| 38/38 [00:08<00:00,  4.02it/s]
Loaded state_dict from [C:\Users\Skyler\Downloads\controlnet\control_sd15_openpose.pth]
Loading config: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\models\cldm_v15.yaml
ControlNet model control_sd15_openpose [fef5e48e] loaded.
Loading preprocessor: openpose_hand
preprocessor resolution = 512
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 931, in process
    detected_map, is_image = preprocessor(input_image, res=preprocessor_resolution, thr_a=unit.threshold_a, thr_b=unit.threshold_b)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\processor.py", line 217, in openpose_hand
    from annotator.openpose import OpenposeDetector
ImportError: cannot import name 'OpenposeDetector' from 'annotator.openpose' (C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\openpose\__init__.py)

100%|██████████████████████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.50it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.31it/s]
Downloading: "https://huggingface.co/lllyasviel/Annotators/resolve/main/scannet.pt" to C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads\normal_bae\scannet.pt

100%|███████████████████████████████████████████████████████████████████████████████| 277M/277M [00:04<00:00, 62.3MB/s]
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
Loading model: control_sd15_normal [fef5e48e]
Loaded state_dict from [C:\Users\Skyler\Downloads\controlnet\control_sd15_normal.pth]
Loading config: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\models\cldm_v15.yaml
ControlNet model control_sd15_normal [fef5e48e] loaded.
Loading preprocessor: normal_bae
preprocessor resolution = 512
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 980, in process
    global_average_pooling=model_net.config.model.params.get("global_average_pooling", False),
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PlugableControlModel' object has no attribute 'config'

100%|██████████████████████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.42it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 38/38 [00:08<00:00,  4.23it/s]
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.pyt/s]
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 433, in process
    while hasattr(autoinclude_obj,"children"): autoinclude_obj = autoinclude_obj.children[-1]
IndexError: list index out of range

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.91it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.92it/s]
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.pyt/s]
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 433, in process
    while hasattr(autoinclude_obj,"children"): autoinclude_obj = autoinclude_obj.children[-1]
IndexError: list index out of range

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.86it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.87it/s]
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.pyt/s]
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 433, in process
    while hasattr(autoinclude_obj,"children"): autoinclude_obj = autoinclude_obj.children[-1]
IndexError: list index out of range

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.81it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.83it/s]
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.pyt/s]
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 433, in process
    while hasattr(autoinclude_obj,"children"): autoinclude_obj = autoinclude_obj.children[-1]
IndexError: list index out of range

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.92it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.97it/s]
Loading model: control_sd15_canny [fef5e48e]███████████████████████████████████████████| 20/20 [00:04<00:00,  4.96it/s]
Loaded state_dict from [C:\Users\Skyler\Downloads\controlnet\control_sd15_canny.pth]
Loading config: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\models\cldm_v15.yaml
ControlNet model control_sd15_canny [fef5e48e] loaded.
Loading preprocessor: canny
preprocessor resolution = 512
Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 980, in process
    global_average_pooling=model_net.config.model.params.get("global_average_pooling", False),
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PlugableControlModel' object has no attribute 'config'

Error running process: C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py
Traceback (most recent call last):
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
  File "C:\Users\Skyler\Documents\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 433, in process
    while hasattr(autoinclude_obj,"children"): autoinclude_obj = autoinclude_obj.children[-1]
IndexError: list index out of range
```

**Comment by lllyasviel** [comment]
restart terminal completely after update

**Comment by skyler14** [comment]
I'll do a full reset of several extensions as well, I think there might be several things that broke. If I can isolate the incompatible extensions I'll put a matrix here, is there any easy way in the UI to manage extension installations?

**Comment by andlike** [comment]
depth zoe ,KeyError: 'beitl16_384',Restarting doesn't work either
