### ISSUE TITLE
[Bug]: Using Scribble on Apple Silicon_ The pidinet processor generates a preview error.

### ISSUE THREAD

**Issue by Gitawake** [Mikubill/sd-webui-controlnet#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Using Scribble on Apple Silicon_ The pidinet processor generates a preview error.
<img width="1273" alt="截屏2023-04-22 13 35 14" src="https://user-images.githubusercontent.com/37563768/233765054-e5f4e019-1d1f-468f-a2a5-3ae8a4db7baa.png">

### Steps to reproduce the problem

1. Click on Enable
2. Click on Allow Preview
3. import images
4. Select Scribble_ PIDINET preprocessing, model selection Scribble
5. Click to generate preview

### What should have happened?

The results should have a preview effect and produce a normal image.

### Commit where the problem happens

webui: 
controlnet: 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on gitawake0w user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI

Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [fc2511737a] from /Users/gitawake0w/PycharmProjects/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: /Users/gitawake0w/PycharmProjects/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0): 
Model loaded in 3.7s (load weights from disk: 0.2s, create model: 0.6s, apply weights to model: 2.0s, apply half(): 0.3s, move model to device: 0.6s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.0s (import torch: 0.8s, import gradio: 0.7s, import ldm: 0.3s, other imports: 0.7s, load scripts: 0.5s, load SD checkpoint: 3.7s, create ui: 0.2s).
ControlNet preprocessor location: /Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
Loaded state_dict from [/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads/pidinet/table5_pidinet.pth]
Traceback (most recent call last):
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 408, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 287, in scribble_pidinet
    result, _ = pidinet(img, res)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/processor.py", line 265, in pidinet
    result = model_pidinet(img)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/pidinet/__init__.py", line 38, in apply_pidinet
    edge = netNetwork(image_pidi)[-1]
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/pidinet/model.py", line 568, in forward
    x1 = self.block1_2(x1)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/pidinet/model.py", line 430, in forward
    y = self.conv1(x)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/pidinet/model.py", line 352, in forward
    return self.pdc(input, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
  File "/Users/gitawake0w/PycharmProjects/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/pidinet/model.py", line 310, in func
    buffer[:, :, [0, 2, 4, 10, 14, 20, 22, 24]] = weights[:, :, 1:]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!
```

**Comment by Gitawake** [comment]
Additional information, all pre processing with pidi have the same error

**Comment by lllyasviel** [comment]
pidi does not support amd and apple, unforyunately
