### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 98Martin** [Mikubill/sd-webui-controlnet#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

在webui里面扩展列表复制链接到git安装，然后就显示这一串内容，不太清楚怎么解决
![微信图片_20230423171357](https://user-images.githubusercontent.com/130293859/233830797-43deabf3-16cd-41a2-9dfd-6fe9e18e200e.png)

### Steps to reproduce the problem

1. Go to .... 1
2. Press ....2
3. ...

### What should have happened?

正常的行为就是现实安装成功

### Commit where the problem happens

webui: 
controlnet: 这里出现的问题

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
否
```

### Console logs

```Shell
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Launching Web UI with arguments: --medvram --xformers --autolaunch --api
AUTOMATIC1111/stable-diffusion-webui portable 本整合包完全免费，严禁倒卖。若您付费获得本软件请立刻举报商家。
[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

Loading weights [0bcee2e498] from E:\novelai-webui\novelai-webui-aki-v3\models\Stable-diffusion\chikmix_V2.safetensors
Creating model from config: E:\novelai-webui\novelai-webui-aki-v3\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: E:\novelai-webui\novelai-webui-aki-v3\models\VAE\kl-f8-anime2.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(1): my_yor
Model loaded in 25.8s (load weights from disk: 0.5s, create model: 0.9s, apply weights to model: 19.5s, apply half(): 3.1s, load VAE: 1.6s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Installing requirements for Mov2mov

Installing requirements for ffmpeg

Closing server running on port: 7860
Restarting UI...
[AddNet] Updating model hashes...

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Error completing request
Arguments: ('controlnet', 'https://github.com/Mikubill/sd-webui-controlnet.git') {}
Traceback (most recent call last):
  File "E:\novelai-webui\novelai-webui-aki-v3\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\novelai-webui\novelai-webui-aki-v3\modules\ui_extensions.py", line 145, in install_extension_from_url
    repo = git.Repo.clone_from(url, tmpdir)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\repo\base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\repo\base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/Mikubill/sd-webui-controlnet.git E:\novelai-webui\novelai-webui-aki-v3\tmp\controlnet
  stderr: 'Cloning into 'E:\novelai-webui\novelai-webui-aki-v3\tmp\controlnet'...
POST git-upload-pack (185 bytes)
POST git-upload-pack (577 bytes)
error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
error: 45635 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
'

Error completing request
Arguments: ('controlnet', 'https://github.com/Mikubill/sd-webui-controlnet.git') {}
Traceback (most recent call last):
  File "E:\novelai-webui\novelai-webui-aki-v3\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\novelai-webui\novelai-webui-aki-v3\modules\ui_extensions.py", line 145, in install_extension_from_url
    repo = git.Repo.clone_from(url, tmpdir)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\repo\base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\repo\base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/Mikubill/sd-webui-controlnet.git E:\novelai-webui\novelai-webui-aki-v3\tmp\controlnet
  stderr: 'Cloning into 'E:\novelai-webui\novelai-webui-aki-v3\tmp\controlnet'...
POST git-upload-pack (185 bytes)
POST git-upload-pack (577 bytes)
error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
error: 6074 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
'

Error completing request
Arguments: ('controlnet', 'https://github.com/Mikubill/sd-webui-controlnet.git') {}
Traceback (most recent call last):
  File "E:\novelai-webui\novelai-webui-aki-v3\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\novelai-webui\novelai-webui-aki-v3\modules\ui_extensions.py", line 145, in install_extension_from_url
    repo = git.Repo.clone_from(url, tmpdir)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\repo\base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\repo\base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "E:\novelai-webui\novelai-webui-aki-v3\py310\lib\site-packages\git\cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/Mikubill/sd-webui-controlnet.git E:\novelai-webui\novelai-webui-aki-v3\tmp\controlnet
  stderr: 'Cloning into 'E:\novelai-webui\novelai-webui-aki-v3\tmp\controlnet'...
POST git-upload-pack (185 bytes)
POST git-upload-pack (577 bytes)
error: RPC failed; curl 56 OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0
error: 59803 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
'
```

**Comment by lllyasviel** [comment]
If your A1111 Extension's ControlNet displays a link look like 'jihulab.com/affair3547', then unfortunately, your A1111 does NOT support ControlNet 1.1. Please use official version of A1111.
