### ISSUE TITLE
Cannot run controlnet for stable-diffusion-webui

### ISSUE THREAD

**Issue by longlnnm** [Mikubill/sd-webui-controlnet#984]
I have the following error for latest control net branch as of today. I have tried searching for error but seems that no error islike this
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/long/stable-diffusion-webui/modules/safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "/home/long/stable-diffusion-webui/modules/safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: invalid load key, 'v'.

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error running process: /home/long/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/home/long/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/home/long/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 842, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "/home/long/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 535, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "/home/long/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 560, in build_control_model
    state_dict = load_state_dict(model_path)
  File "/home/long/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 11, in load_state_dict
    state_dict = get_state_dict(torch.load(
  File "/home/long/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/utils.py", line 19, in get_state_dict
    return d.get('state_dict', d)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by lllyasviel** [comment]
file corrupted because you stop controlnet when it is downloading models. remove controlnet and install again can fix
